My Project: Json::Value Class Reference
Json::Value Class Reference
Represents a JSON value.
#include <value.h>
Classes
struct CommentInfo
class CZString
union ValueHolder
Public Types
typedef std::vector< JSONCPP_STRING > Members
typedef ValueIterator iterator
typedef ValueConstIterator const_iterator
typedef Json::UInt UInt
typedef Json::Int Int
typedef Json::UInt64 UInt64
typedef Json::Int64 Int64
typedef Json::LargestInt LargestInt
typedef Json::LargestUInt LargestUInt
typedef Json::ArrayIndex ArrayIndex
typedef std::map< CZString, Value > ObjectValues
Public Member Functions
Value (ValueType type=nullValue)
Create a default Value of the given type.
Value (Int value)
Value (UInt value)
Value (Int64 value)
Value (UInt64 value)
Value (double value)
Value (const char *value)
Copy til first 0. (NULL causes to seg-fault.)
Value (const char *begin, const char *end)
Copy all, incl zeroes.
Value (const StaticString &value)
Constructs a value from a static string.
Value (const JSONCPP_STRING &value)
Copy data() til size(). Embedded zeroes too.
Value (bool value)
Value (const Value &other)
Deep copy.
~Value ()
Value & operator= (Value other)
void swap (Value &other)
Swap everything.
void swapPayload (Value &other)
Swap values but leave comments and source offsets in place.
ValueType type () const
bool operator< (const Value &other) const
Compare payload only, not comments etc.
bool operator<= (const Value &other) const
bool operator>= (const Value &other) const
bool operator> (const Value &other) const
bool operator== (const Value &other) const
bool operator!= (const Value &other) const
int compare (const Value &other) const
const char * asCString () const
Embedded zeroes could cause you trouble!
JSONCPP_STRING asString () const
Embedded zeroes are possible.
bool getString (char const **begin, char const **end) const
Int asInt () const
UInt asUInt () const
Int64 asInt64 () const
UInt64 asUInt64 () const
LargestInt asLargestInt () const
LargestUInt asLargestUInt () const
float asFloat () const
double asDouble () const
bool asBool () const
bool isNull () const
bool isBool () const
bool isInt () const
bool isInt64 () const
bool isUInt () const
bool isUInt64 () const
bool isIntegral () const
bool isDouble () const
bool isNumeric () const
bool isString () const
bool isArray () const
bool isObject () const
bool isConvertibleTo (ValueType other) const
ArrayIndex size () const
Number of values in array or object.
bool empty () const
Return true if empty array, empty object, or null; otherwise, false.
bool operator! () const
Return isNull()
void clear ()
void resize (ArrayIndex size)
Value & operator[] (ArrayIndex index)
Value & operator[] (int index)
const Value & operator[] (ArrayIndex index) const
const Value & operator[] (int index) const
Value get (ArrayIndex index, const Value &defaultValue) const
bool isValidIndex (ArrayIndex index) const
Return true if index < size().
Value & append (const Value &value)
Append value to array at the end.
Value & operator[] (const char *key)
const Value & operator[] (const char *key) const
Value & operator[] (const JSONCPP_STRING &key)
const Value & operator[] (const JSONCPP_STRING &key) const
Value & operator[] (const StaticString &key)
Access an object value by name, create a null member if it does not exist.
Value get (const char *key, const Value &defaultValue) const
Value get (const char *begin, const char *end, const Value &defaultValue) const
Value get (const JSONCPP_STRING &key, const Value &defaultValue) const
Value const * find (char const *begin, char const *end) const
Value const * demand (char const *begin, char const *end)
Value removeMember (const char *key)
Remove and return the named member.
Value removeMember (const JSONCPP_STRING &key)
bool removeMember (const char *key, Value *removed)
bool removeMember (JSONCPP_STRING const &key, Value *removed)
Remove the named map member.
bool removeMember (const char *begin, const char *end, Value *removed)
Same as removeMember(JSONCPP_STRING const& key, Value* removed)
bool removeIndex (ArrayIndex i, Value *removed)
Remove the indexed array element.
bool isMember (const char *key) const
bool isMember (const JSONCPP_STRING &key) const
bool isMember (const char *begin, const char *end) const
Same as isMember(JSONCPP_STRING const& key)const.
Members getMemberNames () const
Return a list of the member names.
void setComment (const char *comment, CommentPlacement placement)
void setComment (const char *comment, size_t len, CommentPlacement placement)
Comments must be //... or /* ... *‍/.
void setComment (const JSONCPP_STRING &comment, CommentPlacement placement)
Comments must be //... or /* ... *‍/.
bool hasComment (CommentPlacement placement) const
JSONCPP_STRING getComment (CommentPlacement placement) const
Include delimiters and embedded newlines.
JSONCPP_STRING toStyledString () const
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
void setOffsetStart (ptrdiff_t start)
void setOffsetLimit (ptrdiff_t limit)
ptrdiff_t getOffsetStart () const
ptrdiff_t getOffsetLimit () const
Static Public Member Functions
static Value const & nullSingleton ()
Prefer this to null or nullRef.
Static Public Attributes
static const Value & null = Value::nullSingleton()
We regret this reference to a global instance; prefer the simpler Value().
static const Value & nullRef = Value::nullSingleton()
just a kludge for binary-compatibility; same as null
static const LargestInt minLargestInt = LargestInt(~(LargestUInt(-1) / 2))
Minimum signed integer value that can be stored in a Json::Value.
static const LargestInt maxLargestInt = LargestInt(LargestUInt(-1) / 2)
Maximum signed integer value that can be stored in a Json::Value.
static const LargestUInt maxLargestUInt = LargestUInt(-1)
Maximum unsigned integer value that can be stored in a Json::Value.
static const Int minInt = Int(~(UInt(-1) / 2))
Minimum signed int value that can be stored in a Json::Value.
static const Int maxInt = Int(UInt(-1) / 2)
Maximum signed int value that can be stored in a Json::Value.
static const UInt maxUInt = UInt(-1)
Maximum unsigned int value that can be stored in a Json::Value.
static const Int64 minInt64 = Int64(~(UInt64(-1) / 2))
Minimum signed 64 bits int value that can be stored in a Json::Value.
static const Int64 maxInt64 = Int64(UInt64(-1) / 2)
Maximum signed 64 bits int value that can be stored in a Json::Value.
static const UInt64 maxUInt64 = UInt64(-1)
Maximum unsigned 64 bits int value that can be stored in a Json::Value.
Private Member Functions
void initBasic (ValueType type, bool allocated=false)
Value & resolveReference (const char *key)
Value & resolveReference (const char *key, const char *end)
Private Attributes
union Json::Value::ValueHolder value_
ValueType type_: 8
unsigned int allocated_: 1
CommentInfo * comments_
ptrdiff_t start_
ptrdiff_t limit_
Friends
class ValueIteratorBase
Detailed Description
Represents a JSON value.
This class is a discriminated union wrapper that can represents a:
signed integer [range: Value::minInt - Value::maxInt]
unsigned integer (range: 0 - Value::maxUInt)
double
UTF-8 string
boolean
'null'
an ordered list of Value
collection of name/value pairs (javascript object)
The type of the held value is represented by a ValueType and can be obtained using type().
Values of an objectValue or arrayValue can be accessed using operator[]() methods. Non-const methods will automatically create the a nullValue element if it does not exist. The sequence of an arrayValue will be automatically resized and initialized with nullValue. resize() can be used to enlarge or truncate an arrayValue.
The get() methods can be used to obtain default value in the case the required element does not exist.
It is possible to iterate over the list of a objectValue values using the getMemberNames() method.
Note
Value string-length fit in size_t, but keys must be < 2^30. (The reason is an implementation detail.) A #CharReader will raise an exception if a bound is exceeded to avoid security holes in your app, but the Value API does not check bounds. That is the responsibility of the caller.
Definition at line 177 of file value.h.
Member Typedef Documentation
ArrayIndex
typedef Json::ArrayIndex Json::Value::ArrayIndex
Definition at line 191 of file value.h.
const_iterator
typedef ValueConstIterator Json::Value::const_iterator
Definition at line 182 of file value.h.
Int
typedef Json::Int Json::Value::Int
Definition at line 184 of file value.h.
Int64
typedef Json::Int64 Json::Value::Int64
Definition at line 187 of file value.h.
iterator
typedef ValueIterator Json::Value::iterator
Definition at line 181 of file value.h.
LargestInt
typedef Json::LargestInt Json::Value::LargestInt
Definition at line 189 of file value.h.
LargestUInt
typedef Json::LargestUInt Json::Value::LargestUInt
Definition at line 190 of file value.h.
Members
typedef std::vector<JSONCPP_STRING> Json::Value::Members
Definition at line 180 of file value.h.
ObjectValues
typedef std::map<CZString, Value> Json::Value::ObjectValues
Definition at line 262 of file value.h.
UInt
typedef Json::UInt Json::Value::UInt
Definition at line 183 of file value.h.
UInt64
typedef Json::UInt64 Json::Value::UInt64
Definition at line 186 of file value.h.
Constructor & Destructor Documentation
Value() [1/12]
Json::Value::Value (ValueType type = nullValue)
Create a default Value of the given type.
This is a very useful constructor. To create an empty array, pass arrayValue. To create an empty object, pass objectValue. Another Value can then be set to this one by assignment. This is useful since clear() and resize() will not alter types.
Examples:
Json::Value null_value; // null
Json::Value arr_value(Json::arrayValue); // []
Json::Value obj_value(Json::objectValue); // {}
Definition at line 345 of file json_value.cpp.
{
   static char const emptyString[] = "";
   initBasic(vtype);
   switch (vtype) {
   case nullValue:
     break;
   case intValue:
   case uintValue:
     value_.int_ = 0;
     break;
   case realValue:
     value_.real_ = 0.0;
     break;
   case stringValue:
     // allocated_ == false, so this is safe.
     value_.string_ = const_cast<char*>(static_cast<char const*>(emptyString));
     break;
   case arrayValue:
   case objectValue:
     value_.map_ = new ObjectValues();
     break;
   case booleanValue:
     value_.bool_ = false;
     break;
   default:
     JSON_ASSERT_UNREACHABLE;
   }
 }
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, initBasic(), Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, Json::uintValue, and value_.
Referenced by operator[](), resize(), and resolveReference().
Value() [2/12]
Json::Value::Value (Int value)
Definition at line 374 of file json_value.cpp.
                       {
   initBasic(intValue);
   value_.int_ = value;
 }
References initBasic(), Json::Value::ValueHolder::int_, Json::intValue, and value_.
Value() [3/12]
Json::Value::Value (UInt value)
Definition at line 379 of file json_value.cpp.
{
   initBasic(uintValue);
   value_.uint_ = value;
 }
References initBasic(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Value() [4/12]
Json::Value::Value (Int64 value)
Definition at line 384 of file json_value.cpp.
{
   initBasic(intValue);
   value_.int_ = value;
 }
References initBasic(), Json::Value::ValueHolder::int_, Json::intValue, and value_.
Value() [5/12]
Json::Value::Value (UInt64 value)
Definition at line 388 of file json_value.cpp.
{
   initBasic(uintValue);
   value_.uint_ = value;
 }
References initBasic(), Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Value() [6/12]
Json::Value::Value (double value)
Definition at line 394 of file json_value.cpp.
{
   initBasic(realValue);
   value_.real_ = value;
 }
References initBasic(), Json::Value::ValueHolder::real_, Json::realValue, and value_.
Value() [7/12]
Json::Value::Value (const char * value)
Copy til first 0. (NULL causes to seg-fault.)
Definition at line 399 of file json_value.cpp.
{
   initBasic(stringValue, true);
   JSON_ASSERT_MESSAGE(value != NULL, "Null Value Passed to Value Constructor");
   value_.string_ = duplicateAndPrefixStringValue(value, static_cast<unsigned>(strlen(value)));
 }
References Json::duplicateAndPrefixStringValue(), initBasic(), JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::string_, Json::stringValue, and value_.
Value() [8/12]
Json::Value::Value (const char * begin, const char * end)
Copy all, incl zeroes.
Definition at line 405 of file json_value.cpp.
{
   initBasic(stringValue, true);
   value_.string_ =
       duplicateAndPrefixStringValue(beginValue, static_cast<unsigned>(endValue - beginValue));
 }
References Json::duplicateAndPrefixStringValue(), initBasic(), Json::Value::ValueHolder::string_, Json::stringValue, and value_.
Value() [9/12]
Json::Value::Value (const StaticString & value)
Constructs a value from a static string.
Like other value string constructor but do not duplicate the string for internal storage. The given string must remain alive after the call to this constructor.
Note
This works only for null-terminated strings. (We cannot change the size of this class, so we have nowhere to store the length, which might be computed later for various operations.)
Example of usage:
static StaticString foo("some text");
Json::Value aValue(foo);
Definition at line 417 of file json_value.cpp.
{
   initBasic(stringValue);
   value_.string_ = const_cast<char*>(value.c_str());
 }
References Json::StaticString::c_str(), initBasic(), Json::Value::ValueHolder::string_, Json::stringValue, and value_.
Value() [10/12]
Json::Value::Value (const JSONCPP_STRING & value)
Copy data() til size(). Embedded zeroes too.
Definition at line 411 of file json_value.cpp.
{
   initBasic(stringValue, true);
   value_.string_ =
       duplicateAndPrefixStringValue(value.data(), static_cast<unsigned>(value.length()));
 }
References Json::duplicateAndPrefixStringValue(), initBasic(), Json::Value::ValueHolder::string_, Json::stringValue, and value_.
Value() [11/12]
Json::Value::Value (bool value)
Definition at line 429 of file json_value.cpp.
{
   initBasic(booleanValue);
   value_.bool_ = value;
 }
References Json::Value::ValueHolder::bool_, Json::booleanValue, initBasic(), and value_.
Value() [12/12]
Json::Value::Value (const Value & other)
Deep copy.
Definition at line 434 of file json_value.cpp.
     : type_(other.type_), allocated_(false)
       ,
       comments_(0), start_(other.start_), limit_(other.limit_)
 {
   switch (type_) {
   case nullValue:
   case intValue:
   case uintValue:
   case realValue:
   case booleanValue:
     value_ = other.value_;
     break;
   case stringValue:
     if (other.value_.string_ && other.allocated_) {
       unsigned len;
       char const* str;
       decodePrefixedString(other.allocated_, other.value_.string_,
           &len, &str);
       value_.string_ = duplicateAndPrefixStringValue(str, len);
       allocated_ = true;
     } else {
       value_.string_ = other.value_.string_;
       allocated_ = false;
     }
     break;
   case arrayValue:
   case objectValue:
     value_.map_ = new ObjectValues(*other.value_.map_);
     break;
   default:
     JSON_ASSERT_UNREACHABLE;
   }
   if (other.comments_) {
     comments_ = new CommentInfo[numberOfCommentPlacement];
     for (int comment = 0; comment < numberOfCommentPlacement; ++comment) {
       const CommentInfo& otherComment = other.comments_[comment];
       if (otherComment.comment_)
         comments_[comment].setComment(
             otherComment.comment_, strlen(otherComment.comment_));
     }
   }
 }
References allocated_, Json::arrayValue, Json::booleanValue, Json::Value::CommentInfo::comment_, comments_, Json::decodePrefixedString(), Json::duplicateAndPrefixStringValue(), Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::numberOfCommentPlacement, Json::objectValue, Json::realValue, Json::Value::CommentInfo::setComment(), Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::uintValue, and value_.
~Value()
Json::Value::~Value ()
Definition at line 486 of file json_value.cpp.
               {
   switch (type_) {
   case nullValue:
   case intValue:
   case uintValue:
   case realValue:
   case booleanValue:
     break;
   case stringValue:
     if (allocated_)
       releasePrefixedStringValue(value_.string_);
     break;
   case arrayValue:
   case objectValue:
     delete value_.map_;
     break;
   default:
     JSON_ASSERT_UNREACHABLE;
   }
   delete[] comments_;
   value_.uint_ = 0;
 }
References allocated_, Json::arrayValue, Json::booleanValue, comments_, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::realValue, Json::releasePrefixedStringValue(), Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Member Function Documentation
append()
Value & Json::Value::append (const Value & value)
Append value to array at the end.
Equivalent to jsonvalue[jsonvalue.size()] = value;
Definition at line 1125 of file json_value.cpp.
 { return (*this)[size()] = value; }
References size().
asBool()
bool Json::Value::asBool () const
Definition at line 859 of file json_value.cpp.
{
   switch (type_) {
   case booleanValue:
     return value_.bool_;
   case nullValue:
     return false;
   case intValue:
     return value_.int_ ? true : false;
   case uintValue:
     return value_.uint_ ? true : false;
   case realValue:
     // This is kind of strange. Not recommended.
     return (value_.real_ != 0.0) ? true : false;
   default:
     break;
   }
   JSON_FAIL_MESSAGE("Value is not convertible to bool.");
 }
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_FAIL_MESSAGE, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by Json::CharReaderBuilder::newCharReader(), cCtController::ParseParams(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
asCString()
const char * Json::Value::asCString () const
Embedded zeroes could cause you trouble!
Definition at line 643 of file json_value.cpp.
{
   JSON_ASSERT_MESSAGE(type_ == stringValue,
                       "in Json::Value::asCString(): requires stringValue");
   if (value_.string_ == 0) return 0;
   unsigned this_len;
   char const* this_str;
   decodePrefixedString(this->allocated_, this->value_.string_, &this_len, &this_str);
   return this_str;
 }
References allocated_, Json::decodePrefixedString(), JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::string_, Json::stringValue, type_, and value_.
Referenced by Json::Reader::readObject().
asDouble()
double Json::Value::asDouble () const
Definition at line 814 of file json_value.cpp.
{
   switch (type_) {
   case intValue:
     return static_cast<double>(value_.int_);
   case uintValue:
 #if !defined(JSON_USE_INT64_DOUBLE_CONVERSION)
     return static_cast<double>(value_.uint_);
 #else  // if !defined(JSON_USE_INT64_DOUBLE_CONVERSION)
     return integerToDouble(value_.uint_);
 #endif // if !defined(JSON_USE_INT64_DOUBLE_CONVERSION)
   case realValue:
     return value_.real_;
   case nullValue:
     return 0.0;
   case booleanValue:
     return value_.bool_ ? 1.0 : 0.0;
   default:
     break;
   }
   JSON_FAIL_MESSAGE("Value is not convertible to double.");
 }
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_FAIL_MESSAGE, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by isConvertibleTo(), cMotion::LoadJson(), cKinTree::ParseBodyDef(), cKinTree::ParseDrawShapeDef(), cMotion::ParseFrameJson(), cKinTree::ParseJoint(), cCtController::ParseParams(), cDeepMimicCharController::ParseParams(), cGroundBuilder::ParseParamsJson(), cPDController::ParsePDParams(), cJsonUtil::ReadVectorJson(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
asFloat()
float Json::Value::asFloat () const
Definition at line 836 of file json_value.cpp.
{
   switch (type_) {
   case intValue:
     return static_cast<float>(value_.int_);
   case uintValue:
 #if !defined(JSON_USE_INT64_DOUBLE_CONVERSION)
     return static_cast<float>(value_.uint_);
 #else  // if !defined(JSON_USE_INT64_DOUBLE_CONVERSION)
     // This can fail (silently?) if the value is bigger than MAX_FLOAT.
     return static_cast<float>(integerToDouble(value_.uint_));
 #endif // if !defined(JSON_USE_INT64_DOUBLE_CONVERSION)
   case realValue:
     return static_cast<float>(value_.real_);
   case nullValue:
     return 0.0;
   case booleanValue:
     return value_.bool_ ? 1.0f : 0.0f;
   default:
     break;
   }
   JSON_FAIL_MESSAGE("Value is not convertible to float.");
 }
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_FAIL_MESSAGE, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
asInt()
Value::Int Json::Value::asInt () const
Definition at line 709 of file json_value.cpp.
{
   switch (type_) {
   case intValue:
     JSON_ASSERT_MESSAGE(isInt(), "LargestInt out of Int range");
     return Int(value_.int_);
   case uintValue:
     JSON_ASSERT_MESSAGE(isInt(), "LargestUInt out of Int range");
     return Int(value_.uint_);
   case realValue:
     JSON_ASSERT_MESSAGE(InRange(value_.real_, minInt, maxInt),
                         "double out of Int range");
     return Int(value_.real_);
   case nullValue:
     return 0;
   case booleanValue:
     return value_.bool_ ? 1 : 0;
   default:
     break;
   }
   JSON_FAIL_MESSAGE("Value is not convertible to Int.");
 }
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::Value::ValueHolder::int_, Json::intValue, isInt(), JSON_ASSERT_MESSAGE, JSON_FAIL_MESSAGE, maxInt, minInt, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asLargestInt(), and Json::CharReaderBuilder::newCharReader().
asInt64()
Value::Int64 Json::Value::asInt64 () const
Definition at line 755 of file json_value.cpp.
{
   switch (type_) {
   case intValue:
     return Int64(value_.int_);
   case uintValue:
     JSON_ASSERT_MESSAGE(isInt64(), "LargestUInt out of Int64 range");
     return Int64(value_.uint_);
   case realValue:
     JSON_ASSERT_MESSAGE(InRange(value_.real_, minInt64, maxInt64),
                         "double out of Int64 range");
     return Int64(value_.real_);
   case nullValue:
     return 0;
   case booleanValue:
     return value_.bool_ ? 1 : 0;
   default:
     break;
   }
   JSON_FAIL_MESSAGE("Value is not convertible to Int64.");
 }
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::Value::ValueHolder::int_, Json::intValue, isInt64(), JSON_ASSERT_MESSAGE, JSON_FAIL_MESSAGE, maxInt64, minInt64, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asLargestInt().
asLargestInt()
LargestInt Json::Value::asLargestInt () const
Definition at line 798 of file json_value.cpp.
{
 #if defined(JSON_NO_INT64)
   return asInt();
 #else
   return asInt64();
 #endif
 }
References asInt(), and asInt64().
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
asLargestUInt()
LargestUInt Json::Value::asLargestUInt () const
Definition at line 806 of file json_value.cpp.
{
 #if defined(JSON_NO_INT64)
   return asUInt();
 #else
   return asUInt64();
 #endif
 }
References asUInt(), and asUInt64().
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
asString()
JSONCPP_STRING Json::Value::asString () const
Embedded zeroes are possible.
Definition at line 674 of file json_value.cpp.
{
   switch (type_) {
   case nullValue:
     return "";
   case stringValue:
   {
     if (value_.string_ == 0) return "";
     unsigned this_len;
     char const* this_str;
     decodePrefixedString(this->allocated_, this->value_.string_, &this_len, &this_str);
     return JSONCPP_STRING(this_str, this_len);
   }
   case booleanValue:
     return value_.bool_ ? "true" : "false";
   case intValue:
     return valueToString(value_.int_);
   case uintValue:
     return valueToString(value_.uint_);
   case realValue:
     return valueToString(value_.real_);
   default:
     JSON_FAIL_MESSAGE("Type is not convertible to string");
   }
 }
References allocated_, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::decodePrefixedString(), Json::Value::ValueHolder::int_, Json::intValue, JSON_FAIL_MESSAGE, JSONCPP_STRING, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, value_, and Json::valueToString().
Referenced by isConvertibleTo(), cMotion::LoadJson(), cCharacter::LoadMeshes(), cKinTree::ParseBodyDef(), cKinTree::ParseDrawShapeDef(), cKinTree::ParseJoint(), cGroundBuilder::ParseParamsJson(), and Json::OurReader::readObject().
asUInt()
Value::UInt Json::Value::asUInt () const
Definition at line 731 of file json_value.cpp.
{
   switch (type_) {
   case intValue:
     JSON_ASSERT_MESSAGE(isUInt(), "LargestInt out of UInt range");
     return UInt(value_.int_);
   case uintValue:
     JSON_ASSERT_MESSAGE(isUInt(), "LargestUInt out of UInt range");
     return UInt(value_.uint_);
   case realValue:
     JSON_ASSERT_MESSAGE(InRange(value_.real_, 0, maxUInt),
                         "double out of UInt range");
     return UInt(value_.real_);
   case nullValue:
     return 0;
   case booleanValue:
     return value_.bool_ ? 1 : 0;
   default:
     break;
   }
   JSON_FAIL_MESSAGE("Value is not convertible to UInt.");
 }
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::Value::ValueHolder::int_, Json::intValue, isUInt(), JSON_ASSERT_MESSAGE, JSON_FAIL_MESSAGE, maxUInt, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asLargestUInt().
asUInt64()
Value::UInt64 Json::Value::asUInt64 () const
Definition at line 776 of file json_value.cpp.
{
   switch (type_) {
   case intValue:
     JSON_ASSERT_MESSAGE(isUInt64(), "LargestInt out of UInt64 range");
     return UInt64(value_.int_);
   case uintValue:
     return UInt64(value_.uint_);
   case realValue:
     JSON_ASSERT_MESSAGE(InRange(value_.real_, 0, maxUInt64),
                         "double out of UInt64 range");
     return UInt64(value_.real_);
   case nullValue:
     return 0;
   case booleanValue:
     return value_.bool_ ? 1 : 0;
   default:
     break;
   }
   JSON_FAIL_MESSAGE("Value is not convertible to UInt64.");
 }
References Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::Value::ValueHolder::int_, Json::intValue, isUInt64(), JSON_ASSERT_MESSAGE, JSON_FAIL_MESSAGE, maxUInt64, Json::nullValue, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asLargestUInt().
begin() [1/2]
Value::iterator Json::Value::begin ()
Definition at line 1459 of file json_value.cpp.
{
   switch (type_) {
   case arrayValue:
   case objectValue:
     if (value_.map_)
       return iterator(value_.map_->begin());
     break;
   default:
     break;
   }
   return iterator();
 }
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type_, and value_.
begin() [2/2]
Value::const_iterator Json::Value::begin () const
Definition at line 1433 of file json_value.cpp.
{
   switch (type_) {
   case arrayValue:
   case objectValue:
     if (value_.map_)
       return const_iterator(value_.map_->begin());
     break;
   default:
     break;
   }
   return const_iterator();
 }
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type_, and value_.
clear()
void Json::Value::clear ()
Remove all object members and array elements.
Precondition
type() is arrayValue, objectValue, or nullValue
Postcondition
type() is unchanged
Definition at line 944 of file json_value.cpp.
                   {
   JSON_ASSERT_MESSAGE(type_ == nullValue || type_ == arrayValue ||
                           type_ == objectValue,
                       "in Json::Value::clear(): requires complex value");
   start_ = 0;
   limit_ = 0;
   switch (type_) {
   case arrayValue:
   case objectValue:
     value_.map_->clear();
     break;
   default:
     break;
   }
 }
References Json::arrayValue, JSON_ASSERT_MESSAGE, limit_, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, start_, type_, and value_.
Referenced by resize().
compare()
int Json::Value::compare (const Value & other) const
Definition at line 535 of file json_value.cpp.
{
   if (*this < other)
     return -1;
   if (*this > other)
     return 1;
   return 0;
 }
demand()
Value const* Json::Value::demand (char const * begin, char const * end)
Most general and efficient version of object-mutators.
Note
As stated elsewhere, behavior is undefined if (end-begin) >= 2^30
Returns
non-zero, but JSON_ASSERT if this is neither object nor nullValue.
empty()
bool Json::Value::empty () const
Return true if empty array, empty object, or null; otherwise, false.
Definition at line 935 of file json_value.cpp.
{
   if (isNull() || isArray() || isObject())
     return size() == 0u;
   else
     return false;
 }
References isArray(), isNull(), isObject(), and size().
end() [1/2]
Value::iterator Json::Value::end ()
Definition at line 1472 of file json_value.cpp.
{
   switch (type_) {
   case arrayValue:
   case objectValue:
     if (value_.map_)
       return iterator(value_.map_->end());
     break;
   default:
     break;
   }
   return iterator();
 }
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type_, and value_.
end() [2/2]
Value::const_iterator Json::Value::end () const
Definition at line 1446 of file json_value.cpp.
{
   switch (type_) {
   case arrayValue:
   case objectValue:
     if (value_.map_)
       return const_iterator(value_.map_->end());
     break;
   default:
     break;
   }
   return const_iterator();
 }
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type_, and value_.
find()
Value const * Json::Value::find (char const * begin, char const * end) const
Most general and efficient version of isMember()const, get()const, and operator[]const
Note
As stated elsewhere, behavior is undefined if (end-begin) >= 2^30
Definition at line 1077 of file json_value.cpp.
 {
   JSON_ASSERT_MESSAGE(
       type_ == nullValue || type_ == objectValue,
       "in Json::Value::find(key, end, found): requires objectValue or nullValue");
   if (type_ == nullValue) return NULL;
   CZString actualKey(key, static_cast<unsigned>(cend-key), CZString::noDuplication);
   ObjectValues::const_iterator it = value_.map_->find(actualKey);
   if (it == value_.map_->end()) return NULL;
   return &(*it).second;
 }
References JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::Value::CZString::noDuplication, Json::nullValue, Json::objectValue, type_, and value_.
Referenced by get(), isMember(), and operator[]().
get() [1/4]
Value Json::Value::get (ArrayIndex index, const Value & defaultValue) const
If the array contains at least index+1 elements, returns the element value, otherwise returns defaultValue.
Definition at line 1070 of file json_value.cpp.
{
   const Value* value = &((*this)[index]);
   return value == &nullSingleton() ? defaultValue : *value;
 }
References nullSingleton().
Referenced by get(), cKinTree::Load(), cKinTree::LoadBodyDefs(), cKinTree::LoadDrawShapeDefs(), cMotion::LoadJson(), cMotion::LoadJsonFrames(), cCharacter::LoadMeshes(), cPDController::LoadParams(), cKinTree::ParseBodyDef(), cKinTree::ParseDrawShapeDef(), cMotion::ParseFrameJson(), cCtController::ParseParams(), cDeepMimicCharController::ParseParams(), cGroundBuilder::ParseParamsJson(), and cJsonUtil::ReadVectorJson().
get() [2/4]
Value Json::Value::get (const char * begin, const char * end, const Value & defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
Note
deep copy
key may contain embedded nulls.
Definition at line 1127 of file json_value.cpp.
 {
   Value const* found = find(key, cend);
   return !found ? defaultValue : *found;
 }
References find().
get() [3/4]
Value Json::Value::get (const char * key, const Value & defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
Note
deep copy
Definition at line 1132 of file json_value.cpp.
 {
   return get(key, key + strlen(key), defaultValue);
 }
References get().
get() [4/4]
Value Json::Value::get (const JSONCPP_STRING & key, const Value & defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
Note
deep copy
Parameters
key may contain embedded nulls.
Definition at line 1136 of file json_value.cpp.
 {
   return get(key.data(), key.data() + key.length(), defaultValue);
 }
References get().
getComment()
JSONCPP_STRING Json::Value::getComment (CommentPlacement placement) const
Include delimiters and embedded newlines.
Definition at line 1414 of file json_value.cpp.
{
   if (hasComment(placement))
     return comments_[placement].comment_;
   return "";
 }
References Json::Value::CommentInfo::comment_, comments_, and hasComment().
Referenced by Json::StyledWriter::writeCommentAfterValueOnSameLine(), Json::StyledStreamWriter::writeCommentAfterValueOnSameLine(), Json::BuiltStyledStreamWriter::writeCommentAfterValueOnSameLine(), Json::StyledWriter::writeCommentBeforeValue(), Json::StyledStreamWriter::writeCommentBeforeValue(), and Json::BuiltStyledStreamWriter::writeCommentBeforeValue().
getMemberNames()
Value::Members Json::Value::getMemberNames () const
Return a list of the member names.
If null, return an empty list.
Precondition
type() is objectValue or nullValue
Postcondition
if type() was nullValue, it remains nullValue
Definition at line 1229 of file json_value.cpp.
{
   JSON_ASSERT_MESSAGE(
       type_ == nullValue || type_ == objectValue,
       "in Json::Value::getMemberNames(), value must be objectValue");
   if (type_ == nullValue)
     return Value::Members();
   Members members;
   members.reserve(value_.map_->size());
   ObjectValues::const_iterator it = value_.map_->begin();
   ObjectValues::const_iterator itEnd = value_.map_->end();
   for (; it != itEnd; ++it) {
     members.push_back(JSONCPP_STRING((*it).first.data(),
                                   (*it).first.length()));
   }
   return members;
 }
References JSON_ASSERT_MESSAGE, JSONCPP_STRING, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, type_, and value_.
Referenced by Json::CharReaderBuilder::validate(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
getOffsetLimit()
ptrdiff_t Json::Value::getOffsetLimit () const
Definition at line 1426 of file json_value.cpp.
 { return limit_; }
References limit_.
Referenced by Json::Reader::pushError(), and Json::OurReader::pushError().
getOffsetStart()
ptrdiff_t Json::Value::getOffsetStart () const
Definition at line 1424 of file json_value.cpp.
 { return start_; }
References start_.
Referenced by Json::Reader::pushError(), and Json::OurReader::pushError().
getString()
bool Json::Value::getString (char const ** begin, char const ** end) const
Get raw char* of string-value.
Returns
false if !string. (Seg-fault if str or end are NULL.)
Definition at line 665 of file json_value.cpp.
{
   if (type_ != stringValue) return false;
   if (value_.string_ == 0) return false;
   unsigned length;
   decodePrefixedString(this->allocated_, this->value_.string_, &length, str);
   *cend = *str + length;
   return true;
 }
References allocated_, Json::decodePrefixedString(), Json::Value::ValueHolder::string_, Json::stringValue, type_, and value_.
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
hasComment()
bool Json::Value::hasComment (CommentPlacement placement) const
Definition at line 1410 of file json_value.cpp.
{
   return comments_ != 0 && comments_[placement].comment_ != 0;
 }
References Json::Value::CommentInfo::comment_, and comments_.
Referenced by getComment(), Json::StyledWriter::hasCommentForValue(), Json::StyledStreamWriter::hasCommentForValue(), Json::BuiltStyledStreamWriter::hasCommentForValue(), Json::StyledWriter::writeCommentAfterValueOnSameLine(), Json::StyledStreamWriter::writeCommentAfterValueOnSameLine(), Json::BuiltStyledStreamWriter::writeCommentAfterValueOnSameLine(), Json::StyledWriter::writeCommentBeforeValue(), Json::StyledStreamWriter::writeCommentBeforeValue(), and Json::BuiltStyledStreamWriter::writeCommentBeforeValue().
initBasic()
void Json::Value::initBasic (ValueType type, bool allocated = false) private
Definition at line 1021 of file json_value.cpp.
{
   type_ = vtype;
   allocated_ = allocated;
   comments_ = 0;
   start_ = 0;
   limit_ = 0;
 }
References allocated_, comments_, limit_, start_, and type_.
Referenced by Value().
isArray()
bool Json::Value::isArray () const
Definition at line 1388 of file json_value.cpp.
 { return type_ == arrayValue; }
References Json::arrayValue, and type_.
Referenced by empty(), Json::StyledWriter::isMultineArray(), Json::StyledStreamWriter::isMultineArray(), Json::BuiltStyledStreamWriter::isMultineArray(), cMotion::LoadJsonFrames(), Json::Path::make(), Json::Reader::parse(), Json::OurReader::parse(), cMotion::ParseFrameJson(), cGroundBuilder::ParseParamsJson(), cJsonUtil::ReadVectorJson(), and Json::Path::resolve().
isBool()
bool Json::Value::isBool () const
Definition at line 1278 of file json_value.cpp.
 { return type_ == booleanValue; }
References Json::booleanValue, and type_.
isConvertibleTo()
bool Json::Value::isConvertibleTo (ValueType other) const
Definition at line 878 of file json_value.cpp.
{
   switch (other) {
   case nullValue:
     return (isNumeric() && asDouble() == 0.0) ||
            (type_ == booleanValue && value_.bool_ == false) ||
            (type_ == stringValue && asString().empty()) ||
            (type_ == arrayValue && value_.map_->size() == 0) ||
            (type_ == objectValue && value_.map_->size() == 0) ||
            type_ == nullValue;
   case intValue:
     return isInt() ||
            (type_ == realValue && InRange(value_.real_, minInt, maxInt)) ||
            type_ == booleanValue || type_ == nullValue;
   case uintValue:
     return isUInt() ||
            (type_ == realValue && InRange(value_.real_, 0, maxUInt)) ||
            type_ == booleanValue || type_ == nullValue;
   case realValue:
     return isNumeric() || type_ == booleanValue || type_ == nullValue;
   case booleanValue:
     return isNumeric() || type_ == booleanValue || type_ == nullValue;
   case stringValue:
     return isNumeric() || type_ == booleanValue || type_ == stringValue ||
            type_ == nullValue;
   case arrayValue:
     return type_ == arrayValue || type_ == nullValue;
   case objectValue:
     return type_ == objectValue || type_ == nullValue;
   }
   JSON_ASSERT_UNREACHABLE;
   return false;
 }
References Json::arrayValue, asDouble(), asString(), Json::Value::ValueHolder::bool_, Json::booleanValue, Json::InRange(), Json::intValue, isInt(), isNumeric(), isUInt(), JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, maxInt, maxUInt, minInt, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::stringValue, type_, Json::uintValue, and value_.
isDouble()
bool Json::Value::isDouble () const
Definition at line 1382 of file json_value.cpp.
 { return type_ == intValue || type_ == uintValue || type_ == realValue; }
References Json::intValue, Json::realValue, type_, and Json::uintValue.
Referenced by isNumeric().
isInt()
bool Json::Value::isInt () const
Definition at line 1280 of file json_value.cpp.
{
   switch (type_) {
   case intValue:
 #if defined(JSON_HAS_INT64)
     return value_.int_ >= minInt && value_.int_ <= maxInt;
 #else
     return true;
 #endif
   case uintValue:
     return value_.uint_ <= UInt(maxInt);
   case realValue:
     return value_.real_ >= minInt && value_.real_ <= maxInt &&
            IsIntegral(value_.real_);
   default:
     break;
   }
   return false;
 }
References Json::Value::ValueHolder::int_, Json::intValue, Json::IsIntegral(), maxInt, minInt, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asInt(), and isConvertibleTo().
isInt64()
bool Json::Value::isInt64 () const
Definition at line 1322 of file json_value.cpp.
{
 #if defined(JSON_HAS_INT64)
   switch (type_) {
   case intValue:
     return true;
   case uintValue:
     return value_.uint_ <= UInt64(maxInt64);
   case realValue:
     // Note that maxInt64 (= 2^63 - 1) is not exactly representable as a
     // double, so double(maxInt64) will be rounded up to 2^63. Therefore we
     // require the value to be strictly less than the limit.
     return value_.real_ >= double(minInt64) &&
            value_.real_ < double(maxInt64) && IsIntegral(value_.real_);
   default:
     break;
   }
 #endif // JSON_HAS_INT64
   return false;
 }
References Json::intValue, Json::IsIntegral(), maxInt64, minInt64, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asInt64().
isIntegral()
bool Json::Value::isIntegral () const
Definition at line 1362 of file json_value.cpp.
{
   switch (type_) {
     case intValue:
     case uintValue:
       return true;
     case realValue:
 #if defined(JSON_HAS_INT64)
       // Note that maxUInt64 (= 2^64 - 1) is not exactly representable as a
       // double, so double(maxUInt64) will be rounded up to 2^64. Therefore we
       // require the value to be strictly less than the limit.
       return value_.real_ >= double(minInt64) && value_.real_ < maxUInt64AsDouble && IsIntegral(value_.real_);
 #else
       return value_.real_ >= minInt && value_.real_ <= maxUInt && IsIntegral(value_.real_);
 #endif // JSON_HAS_INT64
     default:
       break;
   }
   return false;
 }
References Json::intValue, Json::IsIntegral(), maxUInt, Json::maxUInt64AsDouble, minInt, minInt64, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::uintValue, and value_.
isMember() [1/3]
bool Json::Value::isMember (const char * begin, const char * end) const
Same as isMember(JSONCPP_STRING const& key)const.
Definition at line 1209 of file json_value.cpp.
 {
   Value const* value = find(key, cend);
   return NULL != value;
 }
References find().
isMember() [2/3]
bool Json::Value::isMember (const char * key) const
Return true if the object has a member named key.
Note
'key' must be null-terminated.
Definition at line 1214 of file json_value.cpp.
 {
   return isMember(key, key + strlen(key));
 }
Referenced by isMember().
isMember() [3/3]
bool Json::Value::isMember (const JSONCPP_STRING & key) const
Return true if the object has a member named key.
Parameters
key may contain embedded nulls.
Definition at line 1218 of file json_value.cpp.
 {
   return isMember(key.data(), key.data() + key.length());
 }
References isMember().
isNull()
bool Json::Value::isNull () const
Definition at line 1276 of file json_value.cpp.
 { return type_ == nullValue; }
References Json::nullValue, and type_.
Referenced by empty(), operator!(), and cKinTree::ParseJoint().
isNumeric()
bool Json::Value::isNumeric () const
Definition at line 1384 of file json_value.cpp.
 { return isDouble(); }
References isDouble().
Referenced by isConvertibleTo().
isObject()
bool Json::Value::isObject () const
Definition at line 1390 of file json_value.cpp.
 { return type_ == objectValue; }
References Json::objectValue, and type_.
Referenced by empty(), Json::StyledWriter::isMultineArray(), Json::StyledStreamWriter::isMultineArray(), Json::BuiltStyledStreamWriter::isMultineArray(), Json::Path::make(), Json::Reader::parse(), Json::OurReader::parse(), and Json::Path::resolve().
isString()
bool Json::Value::isString () const
Definition at line 1386 of file json_value.cpp.
 { return type_ == stringValue; }
References Json::stringValue, and type_.
isUInt()
bool Json::Value::isUInt () const
Definition at line 1299 of file json_value.cpp.
{
   switch (type_) {
   case intValue:
 #if defined(JSON_HAS_INT64)
     return value_.int_ >= 0 && LargestUInt(value_.int_) <= LargestUInt(maxUInt);
 #else
     return value_.int_ >= 0;
 #endif
   case uintValue:
 #if defined(JSON_HAS_INT64)
     return value_.uint_ <= maxUInt;
 #else
     return true;
 #endif
   case realValue:
     return value_.real_ >= 0 && value_.real_ <= maxUInt &&
            IsIntegral(value_.real_);
   default:
     break;
   }
   return false;
 }
References Json::Value::ValueHolder::int_, Json::intValue, Json::IsIntegral(), maxUInt, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by asUInt(), and isConvertibleTo().
isUInt64()
bool Json::Value::isUInt64 () const
Definition at line 1342 of file json_value.cpp.
{
 #if defined(JSON_HAS_INT64)
   switch (type_) {
   case intValue:
     return value_.int_ >= 0;
   case uintValue:
     return true;
   case realValue:
     // Note that maxUInt64 (= 2^64 - 1) is not exactly representable as a
     // double, so double(maxUInt64) will be rounded up to 2^64. Therefore we
     // require the value to be strictly less than the limit.
     return value_.real_ >= 0 && value_.real_ < maxUInt64AsDouble &&
            IsIntegral(value_.real_);
   default:
     break;
   }
 #endif // JSON_HAS_INT64
   return false;
 }
References Json::Value::ValueHolder::int_, Json::intValue, Json::IsIntegral(), Json::maxUInt64AsDouble, Json::Value::ValueHolder::real_, Json::realValue, type_, Json::uintValue, and value_.
Referenced by asUInt64().
isValidIndex()
bool Json::Value::isValidIndex (ArrayIndex index) const
Return true if index < size().
Definition at line 1075 of file json_value.cpp.
 { return index < size(); }
References size().
Referenced by Json::Path::resolve().
nullSingleton()
Value const & Json::Value::nullSingleton () static
Prefer this to null or nullRef.
Definition at line 40 of file json_value.cpp.
 {
  static Value const nullStatic;
  return nullStatic;
 }
Referenced by get(), operator[](), removeMember(), Json::Path::resolve(), and resolveReference().
operator!()
bool Json::Value::operator! () const
Return isNull()
Definition at line 942 of file json_value.cpp.
 { return isNull(); }
References isNull().
operator!=()
bool Json::Value::operator!= (const Value & other) const
Definition at line 641 of file json_value.cpp.
 { return !(*this == other); }
operator<()
bool Json::Value::operator< (const Value & other) const
Compare payload only, not comments etc.
Definition at line 543 of file json_value.cpp.
{
   int typeDelta = type_ - other.type_;
   if (typeDelta)
     return typeDelta < 0 ? true : false;
   switch (type_) {
   case nullValue:
     return false;
   case intValue:
     return value_.int_ < other.value_.int_;
   case uintValue:
     return value_.uint_ < other.value_.uint_;
   case realValue:
     return value_.real_ < other.value_.real_;
   case booleanValue:
     return value_.bool_ < other.value_.bool_;
   case stringValue:
   {
     if ((value_.string_ == 0) || (other.value_.string_ == 0)) {
       if (other.value_.string_) return true;
       else return false;
     }
     unsigned this_len;
     unsigned other_len;
     char const* this_str;
     char const* other_str;
     decodePrefixedString(this->allocated_, this->value_.string_, &this_len, &this_str);
     decodePrefixedString(other.allocated_, other.value_.string_, &other_len, &other_str);
     unsigned min_len = std::min<unsigned>(this_len, other_len);
     JSON_ASSERT(this_str && other_str);
     int comp = memcmp(this_str, other_str, min_len);
     if (comp < 0) return true;
     if (comp > 0) return false;
     return (this_len < other_len);
   }
   case arrayValue:
   case objectValue: {
     int delta = int(value_.map_->size() - other.value_.map_->size());
     if (delta)
       return delta < 0;
     return (*value_.map_) < (*other.value_.map_);
   }
   default:
     JSON_ASSERT_UNREACHABLE;
   }
   return false; // unreachable
 }
References allocated_, Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::decodePrefixedString(), Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
operator<=()
bool Json::Value::operator<= (const Value & other) const
Definition at line 590 of file json_value.cpp.
 { return !(other < *this); }
operator=()
Value & Json::Value::operator= (Value other)
Deep copy, then swap(other).
Note
Over-write existing comments. To preserve comments, use swapPayload().
Definition at line 511 of file json_value.cpp.
{
   swap(other);
   return *this;
 }
References swap().
operator==()
bool Json::Value::operator== (const Value & other) const
Definition at line 596 of file json_value.cpp.
{
   // if ( type_ != other.type_ )
   // GCC 2.95.3 says:
   // attempt to take address of bit-field structure member `Json::Value::type_'
   // Beats me, but a temp solves the problem.
   int temp = other.type_;
   if (type_ != temp)
     return false;
   switch (type_) {
   case nullValue:
     return true;
   case intValue:
     return value_.int_ == other.value_.int_;
   case uintValue:
     return value_.uint_ == other.value_.uint_;
   case realValue:
     return value_.real_ == other.value_.real_;
   case booleanValue:
     return value_.bool_ == other.value_.bool_;
   case stringValue:
   {
     if ((value_.string_ == 0) || (other.value_.string_ == 0)) {
       return (value_.string_ == other.value_.string_);
     }
     unsigned this_len;
     unsigned other_len;
     char const* this_str;
     char const* other_str;
     decodePrefixedString(this->allocated_, this->value_.string_, &this_len, &this_str);
     decodePrefixedString(other.allocated_, other.value_.string_, &other_len, &other_str);
     if (this_len != other_len) return false;
     JSON_ASSERT(this_str && other_str);
     int comp = memcmp(this_str, other_str, this_len);
     return comp == 0;
   }
   case arrayValue:
   case objectValue:
     return value_.map_->size() == other.value_.map_->size() &&
            (*value_.map_) == (*other.value_.map_);
   default:
     JSON_ASSERT_UNREACHABLE;
   }
   return false; // unreachable
 }
References allocated_, Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::decodePrefixedString(), Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
operator>()
bool Json::Value::operator> (const Value & other) const
Definition at line 594 of file json_value.cpp.
 { return other < *this; }
operator>=()
bool Json::Value::operator>= (const Value & other) const
Definition at line 592 of file json_value.cpp.
 { return !(*this < other); }
operator[]() [1/9]
Value & Json::Value::operator[] (ArrayIndex index)
Access an array element (zero based index). If the array contains less than index element, then null value are inserted in the array so that its size is index+1. (You may need to say 'value[0u]' to get your compiler to distinguish this from the operator[] which takes a string.)
Definition at line 978 of file json_value.cpp.
{
   JSON_ASSERT_MESSAGE(
       type_ == nullValue || type_ == arrayValue,
       "in Json::Value::operator[](ArrayIndex): requires arrayValue");
   if (type_ == nullValue)
     *this = Value(arrayValue);
   CZString key(index);
   ObjectValues::iterator it = value_.map_->lower_bound(key);
   if (it != value_.map_->end() && (*it).first == key)
     return (*it).second;
   ObjectValues::value_type defaultValue(key, nullSingleton());
   it = value_.map_->insert(it, defaultValue);
   return (*it).second;
 }
References Json::arrayValue, JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, nullSingleton(), Json::nullValue, type_, Value(), and value_.
operator[]() [2/9]
const Value & Json::Value::operator[] (ArrayIndex index) const
Access an array element (zero based index) (You may need to say 'value[0u]' to get your compiler to distinguish this from the operator[] which takes a string.)
Definition at line 1001 of file json_value.cpp.
{
   JSON_ASSERT_MESSAGE(
       type_ == nullValue || type_ == arrayValue,
       "in Json::Value::operator[](ArrayIndex)const: requires arrayValue");
   if (type_ == nullValue)
     return nullSingleton();
   CZString key(index);
   ObjectValues::const_iterator it = value_.map_->find(key);
   if (it == value_.map_->end())
     return nullSingleton();
   return (*it).second;
 }
References Json::arrayValue, JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, nullSingleton(), Json::nullValue, type_, and value_.
operator[]() [3/9]
Value & Json::Value::operator[] (const char * key)
Access an object value by name, create a null member if it does not exist.
Note
Because of our implementation, keys are limited to 2^30 -1 chars. Exceeding that will cause an exception.
Definition at line 1101 of file json_value.cpp.
{
   return resolveReference(key, key + strlen(key));
 }
References resolveReference().
operator[]() [4/9]
const Value & Json::Value::operator[] (const char * key) const
Access an object value by name, returns null if there is no member with that name.
Definition at line 1088 of file json_value.cpp.
 {
   Value const* found = find(key, key + strlen(key));
   if (!found) return nullSingleton();
   return *found;
 }
References find(), and nullSingleton().
operator[]() [5/9]
Value & Json::Value::operator[] (const JSONCPP_STRING & key)
Access an object value by name, create a null member if it does not exist.
Parameters
key may contain embedded nulls.
Definition at line 1105 of file json_value.cpp.
{
   return resolveReference(key.data(), key.data() + key.length());
 }
References resolveReference().
operator[]() [6/9]
Value const & Json::Value::operator[] (const JSONCPP_STRING & key) const
Access an object value by name, returns null if there is no member with that name.
Parameters
key may contain embedded nulls.
Definition at line 1094 of file json_value.cpp.
 {
   Value const* found = find(key.data(), key.data() + key.length());
   if (!found) return nullSingleton();
   return *found;
 }
References find(), and nullSingleton().
operator[]() [7/9]
Value & Json::Value::operator[] (const StaticString & key)
Access an object value by name, create a null member if it does not exist.
If the object has no entry for that name, then the member name used to store the new entry is not duplicated. Example of use:
Json::Value object;
static const StaticString code("code");
object[code] = 1234;
Definition at line 1109 of file json_value.cpp.
{
   return resolveReference(key.c_str());
 }
References Json::StaticString::c_str(), and resolveReference().
operator[]() [8/9]
Value & Json::Value::operator[] (int index)
Access an array element (zero based index). If the array contains less than index element, then null value are inserted in the array so that its size is index+1. (You may need to say 'value[0u]' to get your compiler to distinguish this from the operator[] which takes a string.)
Definition at line 994 of file json_value.cpp.
{
   JSON_ASSERT_MESSAGE(
       index >= 0,
       "in Json::Value::operator[](int index): index cannot be negative");
   return (*this)[ArrayIndex(index)];
 }
References JSON_ASSERT_MESSAGE.
operator[]() [9/9]
const Value & Json::Value::operator[] (int index) const
Access an array element (zero based index) (You may need to say 'value[0u]' to get your compiler to distinguish this from the operator[] which takes a string.)
Definition at line 1014 of file json_value.cpp.
{
   JSON_ASSERT_MESSAGE(
       index >= 0,
       "in Json::Value::operator[](int index) const: index cannot be negative");
   return (*this)[ArrayIndex(index)];
 }
References JSON_ASSERT_MESSAGE.
removeIndex()
bool Json::Value::removeIndex (ArrayIndex i, Value * removed)
Remove the indexed array element.
O(n) expensive operations. Update 'removed' iff removed.
Returns
true iff removed (no exceptions)
Definition at line 1179 of file json_value.cpp.
{
   if (type_ != arrayValue) {
     return false;
   }
   CZString key(index);
   ObjectValues::iterator it = value_.map_->find(key);
   if (it == value_.map_->end()) {
     return false;
   }
   *removed = it->second;
   ArrayIndex oldSize = size();
   // shift left all items left, into the place of the "removed"
   for (ArrayIndex i = index; i < (oldSize - 1); ++i){
     CZString keey(i);
     (*value_.map_)[keey] = (*this)[i + 1];
   }
   // erase the last one ("leftover")
   CZString keyLast(oldSize - 1);
   ObjectValues::iterator itLast = value_.map_->find(keyLast);
   value_.map_->erase(itLast);
   return true;
 }
References Json::arrayValue, Json::Value::ValueHolder::map_, size(), type_, and value_.
removeMember() [1/5]
bool Json::Value::removeMember (const char * begin, const char * end, Value * removed)
Same as removeMember(JSONCPP_STRING const& key, Value* removed)
Definition at line 1142 of file json_value.cpp.
 {
   if (type_ != objectValue) {
     return false;
   }
   CZString actualKey(key, static_cast<unsigned>(cend-key), CZString::noDuplication);
   ObjectValues::iterator it = value_.map_->find(actualKey);
   if (it == value_.map_->end())
     return false;
   *removed = it->second;
   value_.map_->erase(it);
   return true;
 }
References Json::Value::ValueHolder::map_, Json::Value::CZString::noDuplication, Json::objectValue, type_, and value_.
removeMember() [2/5]
Value Json::Value::removeMember (const char * key)
Remove and return the named member.
Do nothing if it did not exist.
Returns
the removed Value, or null.
Precondition
type() is objectValue or nullValue
Postcondition
type() is unchanged
Deprecated:
Definition at line 1163 of file json_value.cpp.
 {
   JSON_ASSERT_MESSAGE(type_ == nullValue || type_ == objectValue,
                       "in Json::Value::removeMember(): requires objectValue");
   if (type_ == nullValue)
     return nullSingleton();
   Value removed;  // null
   removeMember(key, key + strlen(key), &removed);
   return removed; // still null if removeMember() did nothing
 }
References JSON_ASSERT_MESSAGE, nullSingleton(), Json::nullValue, Json::objectValue, and type_.
Referenced by removeMember().
removeMember() [3/5]
bool Json::Value::removeMember (const char * key, Value * removed)
Same as removeMember(const char* begin, const char* end, Value* removed), but 'key' is null-terminated.
Definition at line 1155 of file json_value.cpp.
 {
   return removeMember(key, key + strlen(key), removed);
 }
References removeMember().
removeMember() [4/5]
Value Json::Value::removeMember (const JSONCPP_STRING & key)
Same as removeMember(const char*)
Parameters
key may contain embedded nulls.
Deprecated:
Definition at line 1174 of file json_value.cpp.
 {
   return removeMember(key.c_str());
 }
References removeMember().
removeMember() [5/5]
bool Json::Value::removeMember (JSONCPP_STRING const & key, Value * removed)
Remove the named map member.
Update 'removed' iff removed.
Parameters
key may contain embedded nulls.
Returns
true iff removed (no exceptions)
Definition at line 1159 of file json_value.cpp.
 {
   return removeMember(key.data(), key.data() + key.length(), removed);
 }
References removeMember().
resize()
void Json::Value::resize (ArrayIndex size)
Resize the array to size elements. New elements are initialized to null. May only be called on nullValue or arrayValue.
Precondition
type() is arrayValue or nullValue
Postcondition
type() is arrayValue
Definition at line 960 of file json_value.cpp.
{
   JSON_ASSERT_MESSAGE(type_ == nullValue || type_ == arrayValue,
                       "in Json::Value::resize(): requires arrayValue");
   if (type_ == nullValue)
     *this = Value(arrayValue);
   ArrayIndex oldSize = size();
   if (newSize == 0)
     clear();
   else if (newSize > oldSize)
     (*this)[newSize - 1];
   else {
     for (ArrayIndex index = newSize; index < oldSize; ++index) {
       value_.map_->erase(index);
     }
     JSON_ASSERT(size() == newSize);
   }
 }
References Json::arrayValue, clear(), JSON_ASSERT, JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::nullValue, size(), type_, Value(), and value_.
resolveReference() [1/2]
Value & Json::Value::resolveReference (const char * key) private
Definition at line 1032 of file json_value.cpp.
{
   JSON_ASSERT_MESSAGE(
       type_ == nullValue || type_ == objectValue,
       "in Json::Value::resolveReference(): requires objectValue");
   if (type_ == nullValue)
     *this = Value(objectValue);
   CZString actualKey(
       key, static_cast<unsigned>(strlen(key)), CZString::noDuplication); // NOTE!
   ObjectValues::iterator it = value_.map_->lower_bound(actualKey);
   if (it != value_.map_->end() && (*it).first == actualKey)
     return (*it).second;
   ObjectValues::value_type defaultValue(actualKey, nullSingleton());
   it = value_.map_->insert(it, defaultValue);
   Value& value = (*it).second;
   return value;
 }
References JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, Json::Value::CZString::noDuplication, nullSingleton(), Json::nullValue, Json::objectValue, type_, Value(), and value_.
Referenced by operator[]().
resolveReference() [2/2]
Value & Json::Value::resolveReference (const char * key, const char * end) private
Definition at line 1051 of file json_value.cpp.
 {
   JSON_ASSERT_MESSAGE(
       type_ == nullValue || type_ == objectValue,
       "in Json::Value::resolveReference(key, end): requires objectValue");
   if (type_ == nullValue)
     *this = Value(objectValue);
   CZString actualKey(
       key, static_cast<unsigned>(cend-key), CZString::duplicateOnCopy);
   ObjectValues::iterator it = value_.map_->lower_bound(actualKey);
   if (it != value_.map_->end() && (*it).first == actualKey)
     return (*it).second;
   ObjectValues::value_type defaultValue(actualKey, nullSingleton());
   it = value_.map_->insert(it, defaultValue);
   Value& value = (*it).second;
   return value;
 }
References Json::Value::CZString::duplicateOnCopy, JSON_ASSERT_MESSAGE, Json::Value::ValueHolder::map_, nullSingleton(), Json::nullValue, Json::objectValue, type_, Value(), and value_.
setComment() [1/3]
void Json::Value::setComment (const char * comment, CommentPlacement placement)
Deprecated:
Always pass len.
Definition at line 1402 of file json_value.cpp.
{
   setComment(comment, strlen(comment), placement);
 }
Referenced by Json::Reader::addComment(), Json::OurReader::addComment(), Json::Reader::parse(), Json::OurReader::parse(), Json::Reader::readValue(), Json::OurReader::readValue(), and setComment().
setComment() [2/3]
void Json::Value::setComment (const char * comment, size_t len, CommentPlacement placement)
Comments must be //... or /* ... *‍/.
Definition at line 1392 of file json_value.cpp.
{
   if (!comments_)
     comments_ = new CommentInfo[numberOfCommentPlacement];
   if ((len > 0) && (comment[len-1] == '\n')) {
     // Always discard trailing newline, to aid indentation.
     len -= 1;
   }
   comments_[placement].setComment(comment, len);
 }
References comments_, Json::numberOfCommentPlacement, and Json::Value::CommentInfo::setComment().
setComment() [3/3]
void Json::Value::setComment (const JSONCPP_STRING & comment, CommentPlacement placement)
Comments must be //... or /* ... *‍/.
Definition at line 1406 of file json_value.cpp.
{
   setComment(comment.c_str(), comment.length(), placement);
 }
References setComment().
setOffsetLimit()
void Json::Value::setOffsetLimit (ptrdiff_t limit)
Definition at line 1422 of file json_value.cpp.
 { limit_ = limit; }
References limit_.
Referenced by Json::Reader::decodeDouble(), Json::OurReader::decodeDouble(), Json::Reader::decodeNumber(), Json::OurReader::decodeNumber(), Json::Reader::decodeString(), Json::OurReader::decodeString(), Json::Reader::readValue(), and Json::OurReader::readValue().
setOffsetStart()
void Json::Value::setOffsetStart (ptrdiff_t start)
Definition at line 1420 of file json_value.cpp.
 { start_ = start; }
References start_.
Referenced by Json::Reader::decodeDouble(), Json::OurReader::decodeDouble(), Json::Reader::decodeNumber(), Json::OurReader::decodeNumber(), Json::Reader::decodeString(), Json::OurReader::decodeString(), Json::Reader::readArray(), Json::OurReader::readArray(), Json::Reader::readObject(), Json::OurReader::readObject(), Json::Reader::readValue(), and Json::OurReader::readValue().
size()
ArrayIndex Json::Value::size () const
Number of values in array or object.
Definition at line 912 of file json_value.cpp.
{
   switch (type_) {
   case nullValue:
   case intValue:
   case uintValue:
   case realValue:
   case booleanValue:
   case stringValue:
     return 0;
   case arrayValue: // size of the array is highest index + 1
     if (!value_.map_->empty()) {
       ObjectValues::const_iterator itLast = value_.map_->end();
       --itLast;
       return (*itLast).first.index() + 1;
     }
     return 0;
   case objectValue:
     return ArrayIndex(value_.map_->size());
   }
   JSON_ASSERT_UNREACHABLE;
   return 0; // unreachable;
 }
References Json::arrayValue, Json::booleanValue, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::realValue, Json::stringValue, type_, Json::uintValue, and value_.
Referenced by append(), empty(), Json::StyledWriter::isMultineArray(), Json::StyledStreamWriter::isMultineArray(), Json::BuiltStyledStreamWriter::isMultineArray(), isValidIndex(), cKinTree::Load(), cKinTree::LoadBodyDefs(), cKinTree::LoadDrawShapeDefs(), cMotion::LoadJsonFrames(), cMotion::LoadJsonJoints(), cCharacter::LoadMeshes(), cPDController::LoadParams(), cMotion::ParseFrameJson(), cGroundBuilder::ParseParamsJson(), cJsonUtil::ReadVectorJson(), removeIndex(), resize(), Json::StreamWriterBuilder::validate(), Json::CharReaderBuilder::validate(), Json::StyledWriter::writeArrayValue(), Json::StyledStreamWriter::writeArrayValue(), Json::BuiltStyledStreamWriter::writeArrayValue(), and Json::FastWriter::writeValue().
swap()
void Json::Value::swap (Value & other)
Swap everything.
Definition at line 526 of file json_value.cpp.
{
   swapPayload(other);
   std::swap(comments_, other.comments_);
   std::swap(start_, other.start_);
   std::swap(limit_, other.limit_);
 }
References comments_, limit_, start_, std::swap(), and swapPayload().
Referenced by Json::Value::CZString::operator=(), operator=(), and std::swap().
swapPayload()
void Json::Value::swapPayload (Value & other)
Swap values but leave comments and source offsets in place.
Definition at line 516 of file json_value.cpp.
{
   ValueType temp = type_;
   type_ = other.type_;
   other.type_ = temp;
   std::swap(value_, other.value_);
   int temp2 = allocated_;
   allocated_ = other.allocated_;
   other.allocated_ = temp2 & 0x1;
 }
References allocated_, std::swap(), type_, and value_.
Referenced by Json::Reader::decodeDouble(), Json::OurReader::decodeDouble(), Json::Reader::decodeNumber(), Json::OurReader::decodeNumber(), Json::Reader::decodeString(), Json::OurReader::decodeString(), Json::Reader::readArray(), Json::OurReader::readArray(), Json::Reader::readObject(), Json::OurReader::readObject(), Json::Reader::readValue(), Json::OurReader::readValue(), and swap().
toStyledString()
JSONCPP_STRING Json::Value::toStyledString () const
Definition at line 1428 of file json_value.cpp.
{
   StyledWriter writer;
   return writer.write(*this);
 }
References Json::StyledWriter::write().
type()
ValueType Json::Value::type () const
Definition at line 533 of file json_value.cpp.
 { return type_; }
References type_.
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
Friends And Related Function Documentation
ValueIteratorBase
friend class ValueIteratorBase friend
Definition at line 178 of file value.h.
Member Data Documentation
allocated_
unsigned int Json::Value::allocated_ private
Definition at line 615 of file value.h.
Referenced by asCString(), asString(), getString(), initBasic(), operator<(), operator==(), swapPayload(), Value(), and ~Value().
comments_
CommentInfo* Json::Value::comments_ private
Definition at line 617 of file value.h.
Referenced by getComment(), hasComment(), initBasic(), setComment(), swap(), Value(), and ~Value().
limit_
ptrdiff_t Json::Value::limit_ private
Definition at line 622 of file value.h.
Referenced by clear(), getOffsetLimit(), initBasic(), setOffsetLimit(), and swap().
maxInt
const Int Json::Value::maxInt = Int(UInt(-1) / 2) static
Maximum signed int value that can be stored in a Json::Value.
Definition at line 207 of file value.h.
Referenced by asInt(), Json::Reader::decodeNumber(), Json::OurReader::decodeNumber(), Json::duplicateAndPrefixStringValue(), Json::duplicateStringValue(), isConvertibleTo(), and isInt().
maxInt64
const Int64 Json::Value::maxInt64 = Int64(UInt64(-1) / 2) static
Maximum signed 64 bits int value that can be stored in a Json::Value.
Definition at line 215 of file value.h.
Referenced by asInt64(), and isInt64().
maxLargestInt
const LargestInt Json::Value::maxLargestInt = LargestInt(LargestUInt(-1) / 2) static
Maximum signed integer value that can be stored in a Json::Value.
Definition at line 200 of file value.h.
Referenced by Json::Reader::decodeNumber(), and Json::valueToString().
maxLargestUInt
const LargestUInt Json::Value::maxLargestUInt = LargestUInt(-1) static
Maximum unsigned integer value that can be stored in a Json::Value.
Definition at line 202 of file value.h.
Referenced by Json::Reader::decodeNumber(), and Json::OurReader::decodeNumber().
maxUInt
const UInt Json::Value::maxUInt = UInt(-1) static
Maximum unsigned int value that can be stored in a Json::Value.
Definition at line 209 of file value.h.
Referenced by asUInt(), isConvertibleTo(), isIntegral(), and isUInt().
maxUInt64
const UInt64 Json::Value::maxUInt64 = UInt64(-1) static
Maximum unsigned 64 bits int value that can be stored in a Json::Value.
Definition at line 217 of file value.h.
Referenced by asUInt64().
minInt
const Int Json::Value::minInt = Int(~(UInt(-1) / 2)) static
Minimum signed int value that can be stored in a Json::Value.
Definition at line 205 of file value.h.
Referenced by asInt(), isConvertibleTo(), isInt(), and isIntegral().
minInt64
const Int64 Json::Value::minInt64 = Int64(~(UInt64(-1) / 2)) static
Minimum signed 64 bits int value that can be stored in a Json::Value.
Definition at line 213 of file value.h.
Referenced by asInt64(), isInt64(), and isIntegral().
minLargestInt
const LargestInt Json::Value::minLargestInt = LargestInt(~(LargestUInt(-1) / 2)) static
Minimum signed integer value that can be stored in a Json::Value.
Definition at line 198 of file value.h.
Referenced by Json::Reader::decodeNumber(), Json::OurReader::decodeNumber(), and Json::valueToString().
null
Value const & Json::Value::null = Value::nullSingleton() static
We regret this reference to a global instance; prefer the simpler Value().
Definition at line 193 of file value.h.
Referenced by Json::Path::resolve().
nullRef
Value const & Json::Value::nullRef = Value::nullSingleton() static
just a kludge for binary-compatibility; same as null
Definition at line 194 of file value.h.
start_
ptrdiff_t Json::Value::start_ private
Definition at line 621 of file value.h.
Referenced by clear(), getOffsetStart(), initBasic(), setOffsetStart(), and swap().
type_
ValueType Json::Value::type_ private
Definition at line 614 of file value.h.
Referenced by asBool(), asCString(), asDouble(), asFloat(), asInt(), asInt64(), asString(), asUInt(), asUInt64(), begin(), clear(), end(), find(), getMemberNames(), getString(), initBasic(), isArray(), isBool(), isConvertibleTo(), isDouble(), isInt(), isInt64(), isIntegral(), isNull(), isObject(), isString(), isUInt(), isUInt64(), operator<(), operator==(), operator[](), removeIndex(), removeMember(), resize(), resolveReference(), size(), swapPayload(), type(), Value(), and ~Value().
value_
union Json::Value::ValueHolder Json::Value::value_ private
Referenced by asBool(), asCString(), asDouble(), asFloat(), asInt(), asInt64(), asString(), asUInt(), asUInt64(), begin(), clear(), end(), find(), getMemberNames(), getString(), isConvertibleTo(), isInt(), isInt64(), isIntegral(), isUInt(), isUInt64(), operator<(), operator==(), operator[](), removeIndex(), removeMember(), resize(), resolveReference(), size(), swapPayload(), Value(), and ~Value().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/json/value.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/json/json_value.cpp