My Project: cDrawRLScene Class Reference
cDrawRLScene Class Reference abstract
#include <DrawRLScene.h>
Public Member Functions
virtual ~cDrawRLScene ()
virtual void Init ()
virtual int GetNumAgents () const
virtual bool NeedNewAction (int agent_id) const
virtual void RecordState (int agent_id, Eigen::VectorXd &out_state) const
virtual void RecordGoal (int agent_id, Eigen::VectorXd &out_goal) const
virtual void SetAction (int agent_id, const Eigen::VectorXd &action)
virtual eActionSpace GetActionSpace (int agent_id) const
virtual int GetStateSize (int agent_id) const
virtual int GetGoalSize (int agent_id) const
virtual int GetActionSize (int agent_id) const
virtual int GetNumActions (int agent_id) const
virtual void BuildStateOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildGoalOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionBounds (int agent_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max) const
virtual void BuildStateNormGroups (int agent_id, Eigen::VectorXi &out_groups) const
virtual void BuildGoalNormGroups (int agent_id, Eigen::VectorXi &out_groups) const
virtual double CalcReward (int agent_id) const
virtual double GetRewardMin (int agent_id) const
virtual double GetRewardMax (int agent_id) const
virtual double GetRewardFail (int agent_id)
virtual double GetRewardSucc (int agent_id)
virtual bool IsEpisodeEnd () const
virtual eTerminate CheckTerminate (int agent_id) const
virtual bool CheckValidEpisode () const
virtual void SetMode (eMode mode)
virtual void SetSampleCount (int count)
virtual void LogVal (int agent_id, double val)
virtual std::string GetName () const
Public Member Functions inherited from cRLScene
virtual ~cRLScene ()
virtual void Clear ()
Public Member Functions inherited from cScene
virtual ~cScene ()
virtual void Update (double timestep)
virtual void Keyboard (unsigned char key, double device_x, double device_y)
virtual void Shutdown ()
virtual bool IsDone () const
virtual double GetTime () const
virtual bool HasRandSeed () const
virtual void SetRandSeed (unsigned long seed)
virtual unsigned long GetRandSeed () const
Public Member Functions inherited from cDrawScene
virtual ~cDrawScene ()
virtual void ParseArgs (const std::shared_ptr< cArgParser > &parser)
virtual void Reset ()
virtual void Draw ()
virtual void MouseClick (int button, int state, double device_x, double device_y)
virtual void MouseMove (double device_x, double device_y)
virtual void EnableDrawInfo (bool enable)
Protected Member Functions
cDrawRLScene ()
virtual cRLScene * GetRLScene () const =0
Protected Member Functions inherited from cRLScene
cRLScene ()
Protected Member Functions inherited from cScene
cScene ()
virtual void ResetParams ()
virtual void ResetScene ()
virtual void InitTimers ()
virtual void ResetTimers ()
virtual void UpdateTimers (double timestep)
Protected Member Functions inherited from cDrawScene
cDrawScene ()
virtual void ParseCamTrackMode (const std::shared_ptr< cArgParser > &parser, eCamTrackMode &out_mode) const
virtual void Reshape (int w, int h)
virtual void ResizeCamera (int w, int h)
virtual void InitCamera ()
virtual eCamTrackMode GetCamTrackMode () const
virtual void UpdateCamera ()
virtual void UpdateCameraTracking ()
virtual void UpdateCameraStill ()
virtual double GetCamStillSnapDistX () const
virtual tVector GetCamTrackPos () const
virtual tVector GetCamStillPos () const
virtual void ResetCamera ()
virtual tVector GetDefaultCamFocus () const
virtual void ClearFrame ()
virtual tVector GetBkgColor () const
virtual void SetupView ()
virtual void RestoreView ()
virtual tVector GetLightDirection () const
virtual void DrawScene ()
virtual void DrawGrid () const
virtual void DrawGroundMainScene ()
virtual void DrawCharacterMainScene ()
virtual void DrawObjsMainScene ()
virtual void DrawMiscMainScene ()
virtual void DrawGround () const
virtual void DrawCharacters () const
virtual void DrawObjs () const
virtual void DrawMisc () const
virtual void DrawInfo () const
virtual tVector GetVisOffset () const
virtual tVector GetLineColor () const
virtual tVector GetGroundColor () const
virtual void InitRenderResources ()
virtual bool LoadTextures ()
virtual void SetupMeshShader ()
virtual void DoShadowPass ()
Additional Inherited Members
Public Types inherited from cRLScene
enum eMode { eModeTrain, eModeTest, eModeMax }
enum eTerminate { eTerminateNull, eTerminateFail, eTerminateSucc, eTerminateMax }
Public Types inherited from cDrawScene
enum eCamTrackMode {
eCamTrackModeXZ, eCamTrackModeY, eCamTrackModeXYZ, eCamTrackModeStill,
eCamTrackModeFixed, eCamTrackModeMax
}
Protected Attributes inherited from cRLScene
eMode mMode
int mSampleCount
Protected Attributes inherited from cScene
cRand mRand
bool mHasRandSeed
unsigned long mRandSeed
std::shared_ptr< cArgParser > mArgParser
cTimer::tParams mTimerParams
cTimer mTimer
Protected Attributes inherited from cDrawScene
eCamTrackMode mCamTrackMode
cCamera mCamera
cCamera mShadowCam
bool mDrawInfo
std::unique_ptr< cShadowMap > mShadowMap
std::unique_ptr< cTextureDesc > mGridTex
std::unique_ptr< cShader > mShaderMesh
std::unique_ptr< cShader > mShaderDepth
GLuint mMeshLightDirHandle
GLuint mMeshLightColourHandle
GLuint mMeshAmbientColourHandle
GLuint mMeshShadowProjHandle
GLuint mMeshMaterialDataHandle
GLuint mMeshFogColorHandle
GLuint mMeshFogDataHandle
Detailed Description
Definition at line 6 of file DrawRLScene.h.
Constructor & Destructor Documentation
~cDrawRLScene()
cDrawRLScene::~cDrawRLScene () virtual
Definition at line 7 of file DrawRLScene.cpp.
 {
 }
cDrawRLScene()
cDrawRLScene::cDrawRLScene () protected
Definition at line 3 of file DrawRLScene.cpp.
 {
 }
Member Function Documentation
BuildActionBounds()
void cDrawRLScene::BuildActionBounds (int agent_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) const virtual
Implements cRLScene.
Definition at line 82 of file DrawRLScene.cpp.
 {
     GetRLScene()->BuildActionBounds(agent_id, out_min, out_max);
 }
References cRLScene::BuildActionBounds(), and GetRLScene().
BuildActionOffsetScale()
void cDrawRLScene::BuildActionOffsetScale (int agent_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const virtual
Implements cRLScene.
Definition at line 77 of file DrawRLScene.cpp.
 {
     GetRLScene()->BuildActionOffsetScale(agent_id, out_offset, out_scale);
 }
References cRLScene::BuildActionOffsetScale(), and GetRLScene().
BuildGoalNormGroups()
void cDrawRLScene::BuildGoalNormGroups (int agent_id, Eigen::VectorXi & out_groups) const virtual
Implements cRLScene.
Definition at line 92 of file DrawRLScene.cpp.
 {
     GetRLScene()->BuildGoalNormGroups(agent_id, out_groups);
 }
References cRLScene::BuildGoalNormGroups(), and GetRLScene().
BuildGoalOffsetScale()
void cDrawRLScene::BuildGoalOffsetScale (int agent_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const virtual
Implements cRLScene.
Definition at line 72 of file DrawRLScene.cpp.
 {
     GetRLScene()->BuildGoalOffsetScale(agent_id, out_offset, out_scale);
 }
References cRLScene::BuildGoalOffsetScale(), and GetRLScene().
BuildStateNormGroups()
void cDrawRLScene::BuildStateNormGroups (int agent_id, Eigen::VectorXi & out_groups) const virtual
Implements cRLScene.
Definition at line 87 of file DrawRLScene.cpp.
 {
     GetRLScene()->BuildStateNormGroups(agent_id, out_groups);
 }
References cRLScene::BuildStateNormGroups(), and GetRLScene().
BuildStateOffsetScale()
void cDrawRLScene::BuildStateOffsetScale (int agent_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const virtual
Implements cRLScene.
Definition at line 67 of file DrawRLScene.cpp.
 {
     GetRLScene()->BuildStateOffsetScale(agent_id, out_offset, out_scale);
 }
References cRLScene::BuildStateOffsetScale(), and GetRLScene().
CalcReward()
double cDrawRLScene::CalcReward (int agent_id) const virtual
Implements cRLScene.
Definition at line 97 of file DrawRLScene.cpp.
 {
     return GetRLScene()->CalcReward(agent_id);
 }
References cRLScene::CalcReward(), and GetRLScene().
CheckTerminate()
cDrawRLScene::eTerminate cDrawRLScene::CheckTerminate (int agent_id) const virtual
Reimplemented from cRLScene.
Definition at line 127 of file DrawRLScene.cpp.
 {
     return GetRLScene()->CheckTerminate(agent_id);
 }
References cRLScene::CheckTerminate(), and GetRLScene().
CheckValidEpisode()
bool cDrawRLScene::CheckValidEpisode () const virtual
Reimplemented from cScene.
Reimplemented in cDrawSceneImitate.
Definition at line 132 of file DrawRLScene.cpp.
 {
     return GetRLScene()->CheckValidEpisode();
 }
References cScene::CheckValidEpisode(), and GetRLScene().
Referenced by cDrawSceneImitate::CheckValidEpisode().
GetActionSize()
int cDrawRLScene::GetActionSize (int agent_id) const virtual
Implements cRLScene.
Definition at line 57 of file DrawRLScene.cpp.
 {
     return GetRLScene()->GetActionSize(agent_id);
 }
References cRLScene::GetActionSize(), and GetRLScene().
GetActionSpace()
eActionSpace cDrawRLScene::GetActionSpace (int agent_id) const virtual
Implements cRLScene.
Definition at line 42 of file DrawRLScene.cpp.
 {
     return GetRLScene()->GetActionSpace(agent_id);
 }
References cRLScene::GetActionSpace(), and GetRLScene().
GetGoalSize()
int cDrawRLScene::GetGoalSize (int agent_id) const virtual
Implements cRLScene.
Definition at line 52 of file DrawRLScene.cpp.
 {
     return GetRLScene()->GetGoalSize(agent_id);
 }
References cRLScene::GetGoalSize(), and GetRLScene().
GetName()
std::string cDrawRLScene::GetName () const virtual
Reimplemented from cDrawScene.
Reimplemented in cDrawSceneImitate.
Definition at line 152 of file DrawRLScene.cpp.
 {
     return GetRLScene()->GetName();
 }
References cScene::GetName(), and GetRLScene().
Referenced by cDrawSceneImitate::GetName().
GetNumActions()
int cDrawRLScene::GetNumActions (int agent_id) const virtual
Implements cRLScene.
Definition at line 62 of file DrawRLScene.cpp.
 {
     return GetRLScene()->GetNumActions(agent_id);
 }
References cRLScene::GetNumActions(), and GetRLScene().
GetNumAgents()
int cDrawRLScene::GetNumAgents () const virtual
Implements cRLScene.
Definition at line 17 of file DrawRLScene.cpp.
 {
     return GetRLScene()->GetNumAgents();
 }
References cRLScene::GetNumAgents(), and GetRLScene().
GetRewardFail()
double cDrawRLScene::GetRewardFail (int agent_id) virtual
Reimplemented from cRLScene.
Definition at line 112 of file DrawRLScene.cpp.
 {
     return GetRLScene()->GetRewardFail(agent_id);
 }
References cRLScene::GetRewardFail(), and GetRLScene().
GetRewardMax()
double cDrawRLScene::GetRewardMax (int agent_id) const virtual
Implements cRLScene.
Definition at line 107 of file DrawRLScene.cpp.
 {
     return GetRLScene()->GetRewardMax(agent_id);
 }
References cRLScene::GetRewardMax(), and GetRLScene().
GetRewardMin()
double cDrawRLScene::GetRewardMin (int agent_id) const virtual
Implements cRLScene.
Definition at line 102 of file DrawRLScene.cpp.
 {
     return GetRLScene()->GetRewardMin(agent_id);
 }
References cRLScene::GetRewardMin(), and GetRLScene().
GetRewardSucc()
double cDrawRLScene::GetRewardSucc (int agent_id) virtual
Reimplemented from cRLScene.
Definition at line 117 of file DrawRLScene.cpp.
 {
     return GetRLScene()->GetRewardSucc(agent_id);
 }
References cRLScene::GetRewardSucc(), and GetRLScene().
GetRLScene()
virtual cRLScene* cDrawRLScene::GetRLScene () const protected pure virtual
Implemented in cDrawSceneImitate.
Referenced by BuildActionBounds(), BuildActionOffsetScale(), BuildGoalNormGroups(), BuildGoalOffsetScale(), BuildStateNormGroups(), BuildStateOffsetScale(), CalcReward(), CheckTerminate(), CheckValidEpisode(), GetActionSize(), GetActionSpace(), GetGoalSize(), GetName(), GetNumActions(), GetNumAgents(), GetRewardFail(), GetRewardMax(), GetRewardMin(), GetRewardSucc(), GetStateSize(), IsEpisodeEnd(), LogVal(), NeedNewAction(), RecordGoal(), RecordState(), SetAction(), SetMode(), and SetSampleCount().
GetStateSize()
int cDrawRLScene::GetStateSize (int agent_id) const virtual
Implements cRLScene.
Definition at line 47 of file DrawRLScene.cpp.
 {
     return GetRLScene()->GetStateSize(agent_id);
 }
References GetRLScene(), and cRLScene::GetStateSize().
Init()
void cDrawRLScene::Init () virtual
Reimplemented from cDrawScene.
Reimplemented in cDrawSceneImitate.
Definition at line 11 of file DrawRLScene.cpp.
 {
     cRLScene::Init();
     cDrawScene::Init();
 }
References cDrawScene::Init(), and cRLScene::Init().
IsEpisodeEnd()
bool cDrawRLScene::IsEpisodeEnd () const virtual
Reimplemented from cRLScene.
Reimplemented in cDrawSceneImitate.
Definition at line 122 of file DrawRLScene.cpp.
 {
     return GetRLScene()->IsEpisodeEnd();
 }
References GetRLScene(), and cRLScene::IsEpisodeEnd().
Referenced by cDrawSceneImitate::IsEpisodeEnd().
LogVal()
void cDrawRLScene::LogVal (int agent_id, double val) virtual
Implements cRLScene.
Definition at line 147 of file DrawRLScene.cpp.
 {
     GetRLScene()->LogVal(agent_id, val);
 }
References GetRLScene(), and cRLScene::LogVal().
NeedNewAction()
bool cDrawRLScene::NeedNewAction (int agent_id) const virtual
Implements cRLScene.
Definition at line 22 of file DrawRLScene.cpp.
 {
     return GetRLScene()->NeedNewAction(agent_id);
 }
References GetRLScene(), and cRLScene::NeedNewAction().
RecordGoal()
void cDrawRLScene::RecordGoal (int agent_id, Eigen::VectorXd & out_goal) const virtual
Implements cRLScene.
Definition at line 32 of file DrawRLScene.cpp.
 {
     GetRLScene()->RecordGoal(agent_id, out_goal);
 }
References GetRLScene(), and cRLScene::RecordGoal().
RecordState()
void cDrawRLScene::RecordState (int agent_id, Eigen::VectorXd & out_state) const virtual
Implements cRLScene.
Definition at line 27 of file DrawRLScene.cpp.
 {
     GetRLScene()->RecordState(agent_id, out_state);
 }
References GetRLScene(), and cRLScene::RecordState().
SetAction()
void cDrawRLScene::SetAction (int agent_id, const Eigen::VectorXd & action) virtual
Implements cRLScene.
Definition at line 37 of file DrawRLScene.cpp.
 {
     GetRLScene()->SetAction(agent_id, action);
 }
References GetRLScene(), and cRLScene::SetAction().
SetMode()
void cDrawRLScene::SetMode (eMode mode) virtual
Reimplemented from cRLScene.
Definition at line 137 of file DrawRLScene.cpp.
 {
     return GetRLScene()->SetMode(mode);
 }
References GetRLScene(), and cRLScene::SetMode().
SetSampleCount()
void cDrawRLScene::SetSampleCount (int count) virtual
Reimplemented from cRLScene.
Definition at line 142 of file DrawRLScene.cpp.
 {
     return GetRLScene()->SetSampleCount(count);
 }
References GetRLScene(), and cRLScene::SetSampleCount().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/DrawRLScene.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/DrawRLScene.cpp