My Project: cGroundBuilder Class Reference
cGroundBuilder Class Reference
#include <GroundBuilder.h>
Static Public Member Functions
static bool ParseParamsJson (const std::string &param_file, cGround::tParams &out_params)
static void BuildGround (const std::shared_ptr< cWorld > &world, const cGround::tParams &params, std::shared_ptr< cGround > &out_ground)
Static Protected Member Functions
static bool ParseParamsJason (cGround::eType type, const Json::Value &json, Eigen::VectorXd &out_params)
static void BuildGroundPlane (const std::shared_ptr< cWorld > &world, const cGround::tParams &params, std::shared_ptr< cGround > &out_ground)
Detailed Description
Definition at line 5 of file GroundBuilder.h.
Member Function Documentation
BuildGround()
void cGroundBuilder::BuildGround (const std::shared_ptr< cWorld > & world, const cGround::tParams & params, std::shared_ptr< cGround > & out_ground) static
Definition at line 56 of file GroundBuilder.cpp.
 {
     cGround::eClass ground_class = cGround::GetClassFromType(params.mType);
     switch (ground_class)
     {
     case cGround::eClassPlane:
         BuildGroundPlane(world, params, out_ground);
         break;
     default:
         assert(false); // unsupported ground class
         break;
     }
 }
References BuildGroundPlane(), cGround::eClassPlane, cGround::GetClassFromType(), and cGround::tParams::mType.
Referenced by cSceneSimChar::BuildGround().
BuildGroundPlane()
void cGroundBuilder::BuildGroundPlane (const std::shared_ptr< cWorld > & world, const cGround::tParams & params, std::shared_ptr< cGround > & out_ground) static protected
Definition at line 86 of file GroundBuilder.cpp.
 {
     std::shared_ptr<cGroundPlane> ground_plane = std::shared_ptr<cGroundPlane>(new cGroundPlane());
     ground_plane->Init(world, params);
     out_ground = ground_plane;
 }
Referenced by BuildGround().
ParseParamsJason()
bool cGroundBuilder::ParseParamsJason (cGround::eType type, const Json::Value & json, Eigen::VectorXd & out_params) static protected
Definition at line 70 of file GroundBuilder.cpp.
 {
     cGround::eClass ground_class = cGround::GetClassFromType(type);
     bool succ = false;
     switch (ground_class)
     {
     case cGround::eClassPlane:
         succ = cGroundPlane::ParseParamsJson(json, out_params);
         break;
     default:
         assert(false); // unsupported ground class
         break;
     }
     return succ;
 }
References cGround::eClassPlane, cGround::GetClassFromType(), and cGroundPlane::ParseParamsJson().
Referenced by ParseParamsJson().
ParseParamsJson()
bool cGroundBuilder::ParseParamsJson (const std::string & param_file, cGround::tParams & out_params) static
Definition at line 4 of file GroundBuilder.cpp.
 {
     std::ifstream f_stream(param_file);
     Json::Reader reader;
     Json::Value root;
     bool succ = reader.parse(f_stream, root);
     f_stream.close();
     if (succ)
     {
         if (!root[cGround::gTypeKey].isNull())
         {
             std::string type_str = root[cGround::gTypeKey].asString();
             cGround::ParseType(type_str, out_params.mType);
         }
         out_params.mGroundWidth = root.get(cGround::gGroundWidthKey, out_params.mGroundWidth).asDouble();
         out_params.mVertSpacingX = root.get(cGround::gVertSpacingXKey, out_params.mVertSpacingX).asDouble();
         out_params.mVertSpacingZ = root.get(cGround::gVertSpacingZKey, out_params.mVertSpacingZ).asDouble();
         if (!root[cGround::gParamsKey].isNull())
         {
             Json::Value params_arr = root[cGround::gParamsKey];
             assert(params_arr.isArray());
             int num = params_arr.size();
             out_params.mParamArr.resize(0, 0);
             if (num > 0)
             {
                 for (int i = 0; i < num; ++i)
                 {
                     Eigen::VectorXd curr_params;
                     succ &= ParseParamsJason(out_params.mType, params_arr.get(i, 0), curr_params);
                     if (succ)
                     {
                         if (i == 0)
{
                             size_t m = num;
                             size_t n = curr_params.size();
                             out_params.mParamArr.resize(m, n);
                         }
                         out_params.mParamArr.row(i) = curr_params;
                     }
                 }
             }
         }
     }
     return succ;
 }
References Json::Value::asDouble(), Json::Value::asString(), Json::Value::get(), cGround::gGroundWidthKey, cGround::gParamsKey, cGround::gTypeKey, cGround::gVertSpacingXKey, cGround::gVertSpacingZKey, Json::Value::isArray(), cGround::tParams::mGroundWidth, cGround::tParams::mParamArr, cGround::tParams::mType, cGround::tParams::mVertSpacingX, cGround::tParams::mVertSpacingZ, Json::Reader::parse(), ParseParamsJason(), cGround::ParseType(), and Json::Value::size().
Referenced by cSceneSimChar::ParseGroundParams().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/GroundBuilder.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/GroundBuilder.cpp