My Project: Json::StreamWriterBuilder Class Reference
Json::StreamWriterBuilder Class Reference
Build a StreamWriter implementation.
#include <writer.h>
Public Member Functions
StreamWriterBuilder ()
~StreamWriterBuilder () JSONCPP_OVERRIDE
StreamWriter * newStreamWriter () const JSONCPP_OVERRIDE
bool validate (Json::Value *invalid) const
Value & operator[] (JSONCPP_STRING key)
Public Member Functions inherited from Json::StreamWriter::Factory
virtual ~Factory ()
Static Public Member Functions
static void setDefaults (Json::Value *settings)
Public Attributes
Json::Value settings_
Detailed Description
Build a StreamWriter implementation.
Usage:
using namespace Json;
Value value = ...;
StreamWriterBuilder builder;
builder["commentStyle"] = "None";
builder["indentation"] = "   ";  // or whatever you like
std::unique_ptr<Json::StreamWriter> writer(
    builder.newStreamWriter());
writer->write(value, &std::cout);
std::cout << std::endl;  // add lf and flush
Definition at line 89 of file writer.h.
Constructor & Destructor Documentation
StreamWriterBuilder()
Json::StreamWriterBuilder::StreamWriterBuilder ()
Definition at line 1128 of file json_writer.cpp.
 {
   setDefaults(&settings_);
 }
~StreamWriterBuilder()
Json::StreamWriterBuilder::~StreamWriterBuilder ()
Definition at line 1132 of file json_writer.cpp.
 {}
Member Function Documentation
newStreamWriter()
StreamWriter * Json::StreamWriterBuilder::newStreamWriter () const virtual
Exceptions
std::exception if something goes wrong (e.g. invalid settings)
Implements Json::StreamWriter::Factory.
Definition at line 1134 of file json_writer.cpp.
 {
   JSONCPP_STRING indentation = settings_["indentation"].asString();
   JSONCPP_STRING cs_str = settings_["commentStyle"].asString();
   bool eyc = settings_["enableYAMLCompatibility"].asBool();
   bool dnp = settings_["dropNullPlaceholders"].asBool();
   bool usf = settings_["useSpecialFloats"].asBool();
   unsigned int pre = settings_["precision"].asUInt();
   CommentStyle::Enum cs = CommentStyle::All;
   if (cs_str == "All") {
     cs = CommentStyle::All;
   } else if (cs_str == "None") {
     cs = CommentStyle::None;
   } else {
     throwRuntimeError("commentStyle must be 'All' or 'None'");
   }
   JSONCPP_STRING colonSymbol = " : ";
   if (eyc) {
     colonSymbol = ": ";
   } else if (indentation.empty()) {
     colonSymbol = ":";
   }
   JSONCPP_STRING nullSymbol = "null";
   if (dnp) {
     nullSymbol.clear();
   }
   if (pre > 17) pre = 17;
   JSONCPP_STRING endingLineFeedSymbol;
   return new BuiltStyledStreamWriter(
       indentation, cs,
       colonSymbol, nullSymbol, endingLineFeedSymbol, usf, pre);
 }
References Json::CommentStyle::All, JSONCPP_STRING, Json::CommentStyle::None, and Json::throwRuntimeError().
Referenced by Json::operator<<().
operator[]()
Value & Json::StreamWriterBuilder::operator[] (JSONCPP_STRING key)
A simple way to update a specific setting.
Definition at line 1193 of file json_writer.cpp.
 {
   return settings_[key];
 }
setDefaults()
void Json::StreamWriterBuilder::setDefaults (Json::Value * settings) static
Called by ctor, but you can use this to reset settings_.
Precondition
'settings' != NULL (but Json::null is fine)
Remarks
Defaults:
[StreamWriterBuilderDefaults]
[StreamWriterBuilderDefaults]
Definition at line 1198 of file json_writer.cpp.
 {
   (*settings)["commentStyle"] = "All";
   (*settings)["indentation"] = "\t";
   (*settings)["enableYAMLCompatibility"] = false;
   (*settings)["dropNullPlaceholders"] = false;
   (*settings)["useSpecialFloats"] = false;
   (*settings)["precision"] = 17;
 }
validate()
bool Json::StreamWriterBuilder::validate (Json::Value * invalid) const
Returns
true if 'settings' are legal and consistent; otherwise, indicate bad settings via 'invalid'.
Definition at line 1176 of file json_writer.cpp.
 {
   Json::Value my_invalid;
   if (!invalid) invalid = &my_invalid;  // so we do not need to test for NULL
   Json::Value& inv = *invalid;
   std::set<JSONCPP_STRING> valid_keys;
   getValidWriterKeys(&valid_keys);
   Value::Members keys = settings_.getMemberNames();
   size_t n = keys.size();
   for (size_t i = 0; i < n; ++i) {
     JSONCPP_STRING const& key = keys[i];
     if (valid_keys.find(key) == valid_keys.end()) {
       inv[key] = settings_[key];
     }
   }
   return 0u == inv.size();
 }
References Json::getValidWriterKeys(), JSONCPP_STRING, and Json::Value::size().
Member Data Documentation
settings_
Json::Value Json::StreamWriterBuilder::settings_
Configuration of this builder. Available settings (case-sensitive):
"commentStyle": "None" or "All"
"indentation": "<anything>"
"enableYAMLCompatibility": false or true
slightly change the whitespace around colons
"dropNullPlaceholders": false or true
Drop the "null" string from the writer's output for nullValues. Strictly speaking, this is not valid JSON. But when the output is being fed to a browser's Javascript, it makes for smaller output and the browser can handle the output just fine.
"useSpecialFloats": false or true
If true, outputs non-finite floating point values in the following way: NaN values as "NaN", positive infinity as "Infinity", and negative infinity as "-Infinity".
You can examine 'settings_` yourself to see the defaults. You can also write and read them just like any JSON Value.
See also
setDefaults()
Definition at line 114 of file writer.h.
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/json/writer.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/json/json_writer.cpp