My Project: cIBuffer Class Reference
cIBuffer Class Reference
#include <IBuffer.h>
Public Member Functions
cIBuffer ()
cIBuffer (GLuint bufferID, cRenderState &r_state)
~cIBuffer ()
void SetRender (GLuint buffID, cRenderState &r_state)
void ResizeBuffer (int size)
void LoadBuffer (int num_elem, int elem_size, int *data, int offset=0)
void SyncBuffer ()
void SyncBuffer (GLuint buffer)
int GetNumElems () const
Public Attributes
int mSize
int mElemSize
GLubyte * mLocalData
GLuint mRenderID
cRenderState * mRenderState
Detailed Description
The CPU side representation of a buffer used to store indices to index into the other vertex attributes. This has been made into a separate class for efficieny. It need not do as much as a vertex buffer, and is stored with different commands onto the GPU.
Definition at line 27 of file IBuffer.h.
Constructor & Destructor Documentation
cIBuffer() [1/2]
cIBuffer::cIBuffer () inline
Definition at line 32 of file IBuffer.h.
               : mRenderID(0), mRenderState(NULL), mLocalData(NULL), mElemSize(0), mSize(0)
     {}
cIBuffer() [2/2]
cIBuffer::cIBuffer (GLuint bufferID, cRenderState & r_state) inline
Definition at line 34 of file IBuffer.h.
                                                     : mRenderID(bufferID), mRenderState(&r_state), mLocalData(NULL), mElemSize(0), mSize(0)
     {}
~cIBuffer()
cIBuffer::~cIBuffer () inline
Definition at line 36 of file IBuffer.h.
     {
         if (mLocalData)
             delete [] mLocalData;
     }
References mLocalData.
Member Function Documentation
GetNumElems()
int cIBuffer::GetNumElems () const
Definition at line 69 of file IBuffer.cpp.
 {
     // mSize = num_elem * elem_size + data_offset
     int num_elem = mSize / mElemSize;
     return num_elem;
 }
References mElemSize, and mSize.
Referenced by cDrawMesh::GetNumFaces().
LoadBuffer()
void cIBuffer::LoadBuffer (int num_elem, int elem_size, int * data, int offset = 0)
Definition at line 43 of file IBuffer.cpp.
 {
     if (data == NULL)
         return;
     mElemSize = elem_size;
     ResizeBuffer(num_elem * elem_size + data_offset); // does nothing if data is already allocated and large enough
     memcpy(mLocalData, data, num_elem * elem_size);     // note: don't use mSize. This method allows partial copies
 #ifdef DEBUG
     GLenum err =  glGetError();
     if (err != GL_NO_ERROR)
     {
         fprintf(stderr, "Buffer Assignment Failed: %08x\n", err);
     }
 #endif
 }
References mElemSize, mLocalData, and ResizeBuffer().
Referenced by cDrawMesh::LoadIBuffer().
ResizeBuffer()
void cIBuffer::ResizeBuffer (int size)
Definition at line 22 of file IBuffer.cpp.
 {
     if (size <= mSize)
         return;
     GLubyte *tmp = new GLubyte[size];
     if (mLocalData)
     {
         memcpy(tmp, mLocalData, mSize);
         delete [] mLocalData;
     }
     mLocalData = tmp;
     mSize = size;
     if (!mLocalData)
     {
         fprintf(stderr, "unable to allocate Ibuffer");
     }
 }
References mLocalData, and mSize.
Referenced by LoadBuffer().
SetRender()
void cIBuffer::SetRender (GLuint buffID, cRenderState & r_state) inline
Definition at line 42 of file IBuffer.h.
     {
         mRenderID = buffID;
         mRenderState = &r_state;
     }
References mRenderID, and mRenderState.
Referenced by cDrawMesh::Init().
SyncBuffer() [1/2]
void cIBuffer::SyncBuffer ()
Definition at line 78 of file IBuffer.cpp.
 { SyncBuffer(mRenderID); }
References mRenderID.
Referenced by cDrawMesh::SyncGPU().
SyncBuffer() [2/2]
void cIBuffer::SyncBuffer (GLuint buffer)
Definition at line 63 of file IBuffer.cpp.
 {
     mRenderState->BindIBO(buffer);
     mRenderState->SetBufferData(buffer, mSize, (unsigned char *)mLocalData);
 }
References cRenderState::BindIBO(), mLocalData, mRenderState, mSize, and cRenderState::SetBufferData().
Member Data Documentation
mElemSize
int cIBuffer::mElemSize
Definition at line 54 of file IBuffer.h.
Referenced by GetNumElems(), and LoadBuffer().
mLocalData
GLubyte* cIBuffer::mLocalData
Definition at line 55 of file IBuffer.h.
Referenced by cDrawMesh::GetIdxData(), LoadBuffer(), ResizeBuffer(), SyncBuffer(), and ~cIBuffer().
mRenderID
GLuint cIBuffer::mRenderID
Definition at line 57 of file IBuffer.h.
Referenced by SetRender(), and SyncBuffer().
mRenderState
cRenderState* cIBuffer::mRenderState
Definition at line 58 of file IBuffer.h.
Referenced by SetRender(), and SyncBuffer().
mSize
int cIBuffer::mSize
Definition at line 53 of file IBuffer.h.
Referenced by GetNumElems(), ResizeBuffer(), and SyncBuffer().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/IBuffer.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/IBuffer.cpp