My Project: F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/BVHReader.h File Reference
BVHReader.h File Reference
#include <string>
#include <vector>
#include <set>
#include <sstream>
#include <fstream>
#include <algorithm>
#include <memory>
#include <cctype>
#include "MathUtil.h"
#include "anim/KinTree.h"
#include "anim/Motion.h"
Classes
class cBVHReader
struct cBVHReader::tJointData
struct cBVHReader::PoseData
Functions
static std::string & ltrim (std::string &s)
static std::string & rtrim (std::string &s)
static std::string & trim (std::string &s)
Function Documentation
ltrim()
static std::string& ltrim (std::string & s) inline static
Definition at line 155 of file BVHReader.h.
{
     s.erase(s.begin(), std::find_if(s.begin(), s.end(), std::not1(std::ptr_fun<int, int>(std::isspace))));
     return s;
 }
Referenced by trim().
rtrim()
static std::string& rtrim (std::string & s) inline static
Definition at line 161 of file BVHReader.h.
{
     s.erase(std::find_if(s.rbegin(), s.rend(), std::not1(std::ptr_fun<int, int>(std::isspace))).base(), s.end());
     return s;
 }
Referenced by trim().
trim()
static std::string& trim (std::string & s) inline static
Definition at line 167 of file BVHReader.h.
{
     return ltrim(rtrim(s));
 }
References ltrim(), and rtrim().
Referenced by cBVHReader::parseBVH(), cBVHReader::parseHierarchy(), cBVHReader::parseJoint(), and cBVHReader::parseMotion().