My Project: cSimObj Class Reference
cSimObj Class Reference abstract
#include <SimObj.h>
Public Types
enum eType { eTypeDynamic, eTypeStatic, eTypeMax }
Public Member Functions
virtual ~cSimObj ()
virtual tVector GetPos () const
virtual void SetPos (const tVector &pos)
virtual void GetRotation (tVector &out_axis, double &out_theta) const
virtual tQuaternion GetRotation () const
virtual void SetRotation (const tVector &axis, double theta)
virtual void SetRotation (const tQuaternion &q)
virtual tMatrix GetWorldTransform () const
virtual tMatrix GetLocalTransform () const
virtual tVector GetLinearVelocity () const =0
virtual tVector GetLinearVelocity (const tVector &local_pos) const =0
virtual void SetLinearVelocity (const tVector &vel)=0
virtual tVector GetAngularVelocity () const =0
virtual void SetAngularVelocity (const tVector &vel)=0
virtual tVector WorldToLocalPos (const tVector &world_pos) const
virtual tVector LocalToWorldPos (const tVector &local_pos) const
virtual tMatrix3 GetLocalToWorldRotMat () const
virtual tVector CalcCOM () const
virtual tVector CalcCOMVel () const
virtual void RegisterContact ()
virtual void RegisterContact (int contact_flags, int filter_flags)
virtual void UpdateContact (int contact_flags, int filter_flags)
virtual const cContactManager::tContactHandle & GetContactHandle () const
virtual bool IsInContact () const
virtual const tEigenArr< cContactManager::tContactPt > & GetContactPts () const
virtual void ApplyForce (const tVector &force)=0
virtual void ApplyForce (const tVector &force, const tVector &local_pos)=0
virtual void ApplyTorque (const tVector &torque)=0
virtual void ClearForces ()=0
virtual short GetColGroup () const
virtual void SetColGroup (short col_group)
virtual short GetColMask () const
virtual void SetColMask (short col_mask)
virtual eType GetType () const
virtual cShape::eShape GetShape () const
virtual tVector GetSize () const =0
virtual void CalcAABB (tVector &out_min, tVector &out_max) const
virtual const btCollisionShape * GetCollisionShape () const
Protected Member Functions
cSimObj ()
virtual const std::shared_ptr< cWorld > & GetWorld () const
virtual const btCollisionObject * GetCollisionObject () const =0
virtual btCollisionObject * GetCollisionObject ()=0
Protected Attributes
std::shared_ptr< cWorld > mWorld
std::unique_ptr< btCollisionShape > mColShape
cContactManager::tContactHandle mContactHandle
bool mEnableContactFall
eType mType
short mColGroup
short mColMask
Detailed Description
Definition at line 7 of file SimObj.h.
Member Enumeration Documentation
eType
enum cSimObj::eType
Enumerator
eTypeDynamic
eTypeStatic
eTypeMax
Definition at line 10 of file SimObj.h.
     {
         eTypeDynamic,
         eTypeStatic,
         eTypeMax
     };
Constructor & Destructor Documentation
~cSimObj()
cSimObj::~cSimObj () virtual
Definition at line 11 of file SimObj.cpp.
 {
 }
cSimObj()
cSimObj::cSimObj () protected
Definition at line 3 of file SimObj.cpp.
     : mWorld(nullptr)
 {
     mType = eTypeDynamic;
     mColGroup = cContactManager::gFlagAll;
     mColMask = cContactManager::gFlagAll;
 }
References eTypeDynamic, cContactManager::gFlagAll, mColGroup, mColMask, and mType.
Member Function Documentation
ApplyForce() [1/2]
virtual void cSimObj::ApplyForce (const tVector & force) pure virtual
Implemented in cSimCharacter, cSimBodyLink, and cSimRigidBody.
Referenced by tPerturb::ApplyForce().
ApplyForce() [2/2]
virtual void cSimObj::ApplyForce (const tVector & force, const tVector & local_pos) pure virtual
Implemented in cSimCharacter, cSimBodyLink, and cSimRigidBody.
ApplyTorque()
virtual void cSimObj::ApplyTorque (const tVector & torque) pure virtual
Implemented in cSimCharacter, cSimBodyLink, and cSimRigidBody.
Referenced by tPerturb::ApplyTorque().
CalcAABB()
void cSimObj::CalcAABB (tVector & out_min, tVector & out_max) const virtual
Reimplemented in cSimCharacter, and cGroundPlane.
Definition at line 224 of file SimObj.cpp.
 {
     const auto* obj = GetCollisionObject();
     const auto* shape = GetCollisionShape();
     btVector3 bt_min;
     btVector3 bt_max;
     shape->getAabb(obj->getWorldTransform(), bt_min, bt_max);
     double scale = mWorld->GetScale();
     out_min = tVector(bt_min[0], bt_min[1], bt_min[2], 0) / scale;
     out_max = tVector(bt_max[0], bt_max[1], bt_max[2], 0) / scale;
 }
References GetCollisionObject(), GetCollisionShape(), and mWorld.
CalcCOM()
tVector cSimObj::CalcCOM () const virtual
Reimplemented in cSimCharacter.
Definition at line 139 of file SimObj.cpp.
 {
     return GetPos();
 }
References GetPos().
CalcCOMVel()
tVector cSimObj::CalcCOMVel () const virtual
Reimplemented in cSimCharacter.
Definition at line 144 of file SimObj.cpp.
 {
     return GetLinearVelocity();
 }
References GetLinearVelocity().
ClearForces()
virtual void cSimObj::ClearForces () pure virtual
Implemented in cSimCharacter, cSimBodyLink, and cSimRigidBody.
GetAngularVelocity()
virtual tVector cSimObj::GetAngularVelocity () const pure virtual
Implemented in cSimCharacter, cSimBodyLink, and cSimRigidBody.
GetColGroup()
short cSimObj::GetColGroup () const virtual
Reimplemented in cSimCharacter.
Definition at line 194 of file SimObj.cpp.
 {
     return mColGroup;
 }
References mColGroup.
Referenced by cWorld::AddRigidBody().
GetCollisionObject() [1/2]
virtual const btCollisionObject* cSimObj::GetCollisionObject () const protected pure virtual
Implemented in cSimCharacter, cSimBodyLink, and cSimRigidBody.
Referenced by CalcAABB(), GetPos(), GetRotation(), GetWorldTransform(), SetPos(), and SetRotation().
GetCollisionObject() [2/2]
virtual btCollisionObject* cSimObj::GetCollisionObject () protected pure virtual
Implemented in cSimCharacter, cSimBodyLink, and cSimRigidBody.
GetCollisionShape()
const btCollisionShape * cSimObj::GetCollisionShape () const virtual
Definition at line 238 of file SimObj.cpp.
 {
     return mColShape.get();
 }
References mColShape.
Referenced by CalcAABB(), cWorld::GetSizeBox(), cWorld::GetSizeCapsule(), cWorld::GetSizeCylinder(), cWorld::GetSizePlane(), and cWorld::GetSizeSphere().
GetColMask()
short cSimObj::GetColMask () const virtual
Reimplemented in cSimCharacter.
Definition at line 204 of file SimObj.cpp.
 {
     return mColMask;
 }
References mColMask.
Referenced by cWorld::AddRigidBody().
GetContactHandle()
const cContactManager::tContactHandle & cSimObj::GetContactHandle () const virtual
Reimplemented in cSimCharacter.
Definition at line 178 of file SimObj.cpp.
 {
     return mContactHandle;
 }
References mContactHandle.
Referenced by cContactManager::Update().
GetContactPts()
const tEigenArr< cContactManager::tContactPt > & cSimObj::GetContactPts () const virtual
Reimplemented in cSimCharacter.
Definition at line 189 of file SimObj.cpp.
 {
     return mWorld->GetContactPts(mContactHandle);
 }
References mContactHandle, and mWorld.
GetLinearVelocity() [1/2]
virtual tVector cSimObj::GetLinearVelocity () const pure virtual
Implemented in cSimCharacter, cSimBodyLink, and cSimRigidBody.
Referenced by CalcCOMVel().
GetLinearVelocity() [2/2]
virtual tVector cSimObj::GetLinearVelocity (const tVector & local_pos) const pure virtual
Implemented in cSimCharacter, cSimBodyLink, and cSimRigidBody.
GetLocalToWorldRotMat()
tMatrix3 cSimObj::GetLocalToWorldRotMat () const virtual
Definition at line 132 of file SimObj.cpp.
 {
     tMatrix local_to_world = GetWorldTransform();
     tMatrix3 mat = local_to_world.block(0, 0, 3, 3);
     return mat;
 }
References GetWorldTransform().
Referenced by cSimRigidBody::ApplyForce(), and cSimRigidBody::GetLinearVelocity().
GetLocalTransform()
tMatrix cSimObj::GetLocalTransform () const virtual
Definition at line 101 of file SimObj.cpp.
 {
     tMatrix trans = GetWorldTransform();
     trans = cMathUtil::InvRigidMat(trans);
     return trans;
 }
References GetWorldTransform(), and cMathUtil::InvRigidMat().
Referenced by WorldToLocalPos().
GetPos()
tVector cSimObj::GetPos () const virtual
Reimplemented in cSimCharacter.
Definition at line 15 of file SimObj.cpp.
 {
     const btCollisionObject* col_obj = GetCollisionObject();
     btTransform trans = col_obj->getWorldTransform();
     btVector3 origin = trans.getOrigin();
     tVector pos = tVector(origin[0], origin[1], origin[2], 0);
     pos /= mWorld->GetScale();
     return pos;
 }
References GetCollisionObject(), and mWorld.
Referenced by cDrawGround::BuildMeshPlane(), CalcCOM(), cDrawObj::DrawBox(), cDrawObj::DrawCapsule(), cDrawObj::DrawCylinder(), and cDrawObj::DrawSphere().
GetRotation() [1/2]
tQuaternion cSimObj::GetRotation () const virtual
Reimplemented in cSimCharacter.
Definition at line 52 of file SimObj.cpp.
 {
     const btCollisionObject* col_obj = GetCollisionObject();
     btTransform trans = col_obj->getWorldTransform();
     btQuaternion bt_q = trans.getRotation();
     tQuaternion q = tQuaternion(bt_q.w(), bt_q.x(), bt_q.y(), bt_q.z());
     return q;
 }
References GetCollisionObject().
Referenced by cSimBodyLink::GetLinearVelocity().
GetRotation() [2/2]
void cSimObj::GetRotation (tVector & out_axis, double & out_theta) const virtual
Reimplemented in cSimCharacter.
Definition at line 38 of file SimObj.cpp.
 {
     const btCollisionObject* col_obj = GetCollisionObject();
     btTransform trans = col_obj->getWorldTransform();
     btQuaternion bt_q = trans.getRotation();
     btVector3 axis = bt_q.getAxis();
     out_theta = bt_q.getAngle();
     out_axis[0] = axis[0];
     out_axis[1] = axis[1];
     out_axis[2] = axis[2];
     out_axis[3] = 0;
 }
References GetCollisionObject().
Referenced by cDrawObj::DrawBox(), cDrawObj::DrawCapsule(), cDrawObj::DrawCylinder(), and cDrawObj::DrawSphere().
GetShape()
cShape::eShape cSimObj::GetShape () const virtual
Reimplemented in cSimBodyLink, cSimCapsule, cSimCylinder, cSimSphere, cSimBox, and cSimPlane.
Definition at line 219 of file SimObj.cpp.
 {
     return cShape::eShapeNull;
 }
References cShape::eShapeNull.
Referenced by cDrawObj::Draw(), cDrawObj::DrawBox(), cDrawObj::DrawCapsule(), cDrawObj::DrawCylinder(), cDrawObj::DrawPlane(), cDrawObj::DrawSphere(), cWorld::GetSizeBox(), cWorld::GetSizeCapsule(), cWorld::GetSizeCylinder(), cWorld::GetSizePlane(), and cWorld::GetSizeSphere().
GetSize()
virtual tVector cSimObj::GetSize () const pure virtual
Implemented in cGround, cSimCharacter, cSimCapsule, cSimCylinder, cSimSphere, cSimBox, cSimPlane, and cSimBodyLink.
Referenced by cDrawObj::DrawBox(), cDrawObj::DrawCapsule(), cDrawObj::DrawCylinder(), cDrawObj::DrawPlane(), and cDrawObj::DrawSphere().
GetType()
cSimObj::eType cSimObj::GetType () const virtual
Definition at line 214 of file SimObj.cpp.
 {
     return mType;
 }
References mType.
Referenced by cDrawSceneSimChar::HandleRayTest().
GetWorld()
const std::shared_ptr< cWorld > & cSimObj::GetWorld () const protected virtual
Reimplemented in cSimCharacter.
Definition at line 243 of file SimObj.cpp.
 {
     return mWorld;
 }
References mWorld.
GetWorldTransform()
tMatrix cSimObj::GetWorldTransform () const virtual
Reimplemented in cSimCharacter.
Definition at line 79 of file SimObj.cpp.
 {
     const btCollisionObject* col_obj = GetCollisionObject();
     const btTransform& bt_trans = col_obj->getWorldTransform();
     const btMatrix3x3& basis = bt_trans.getBasis();
     const btVector3& origin = bt_trans.getOrigin();
     double scale = mWorld->GetScale();
     tMatrix trans = tMatrix::Identity();
     for (int i = 0; i < 3; ++i)
     {
         auto curr_row = trans.row(i);
         auto bt_row = basis.getRow(i);
         for (int j = 0; j < 3; ++j)
         {
             curr_row[j] = bt_row[j];
         }
         curr_row[3] = origin[i] / scale;
     }
     return trans;
 }
References GetCollisionObject(), and mWorld.
Referenced by cSimBodyLink::ApplyForce(), GetLocalToWorldRotMat(), GetLocalTransform(), and LocalToWorldPos().
IsInContact()
bool cSimObj::IsInContact () const virtual
Reimplemented in cSimCharacter.
Definition at line 183 of file SimObj.cpp.
 {
     bool in_contact = mWorld->IsInContact(mContactHandle);
     return in_contact;
 }
References mContactHandle, and mWorld.
LocalToWorldPos()
tVector cSimObj::LocalToWorldPos (const tVector & local_pos) const virtual
Definition at line 120 of file SimObj.cpp.
 {
     tMatrix local_to_world = GetWorldTransform();
     tVector world_pos = local_pos;
     world_pos[3] = 1;
     world_pos = local_to_world * world_pos;
     world_pos[3] = 0;
     return world_pos;
 }
References GetWorldTransform().
Referenced by cDrawPerturb::DrawForce(), and cDrawPerturb::DrawTorque().
RegisterContact() [1/2]
void cSimObj::RegisterContact () virtual
Definition at line 149 of file SimObj.cpp.
 {
     RegisterContact(cContactManager::gFlagAll, cContactManager::gFlagAll);
 }
References cContactManager::gFlagAll.
RegisterContact() [2/2]
void cSimObj::RegisterContact (int contact_flags, int filter_flags) virtual
Definition at line 154 of file SimObj.cpp.
 {
     if (!mContactHandle.IsValid())
     {
         mContactHandle = mWorld->RegisterContact(contact_flags, filter_flags);
         assert(mContactHandle.IsValid());
     }
     else
     {
         assert(false); // already registered contact
     }
 }
References cContactManager::tContactHandle::IsValid(), mContactHandle, and mWorld.
SetAngularVelocity()
virtual void cSimObj::SetAngularVelocity (const tVector & vel) pure virtual
Implemented in cSimCharacter, cSimBodyLink, and cSimRigidBody.
SetColGroup()
void cSimObj::SetColGroup (short col_group) virtual
Reimplemented in cSimCharacter.
Definition at line 199 of file SimObj.cpp.
 {
     mColGroup = col_group;
 }
References mColGroup.
SetColMask()
void cSimObj::SetColMask (short col_mask) virtual
Reimplemented in cSimCharacter.
Definition at line 209 of file SimObj.cpp.
 {
     mColMask = col_mask;
 }
References mColMask.
SetLinearVelocity()
virtual void cSimObj::SetLinearVelocity (const tVector & vel) pure virtual
Implemented in cSimCharacter, cSimBodyLink, and cSimRigidBody.
SetPos()
void cSimObj::SetPos (const tVector & pos) virtual
Reimplemented in cSimCharacter, and cSimRigidBody.
Definition at line 25 of file SimObj.cpp.
 {
     btCollisionObject* col_obj = GetCollisionObject();
     btTransform trans = col_obj->getWorldTransform();
     btScalar scale = static_cast<btScalar>(mWorld->GetScale());
     trans.setOrigin(scale * btVector3(static_cast<btScalar>(pos[0]),
         static_cast<btScalar>(pos[1]),
         static_cast<btScalar>(pos[2])));
     col_obj->setWorldTransform(trans);
 }
References GetCollisionObject(), and mWorld.
Referenced by cSimRigidBody::SetPos().
SetRotation() [1/2]
void cSimObj::SetRotation (const tQuaternion & q) virtual
Reimplemented in cSimCharacter, and cSimRigidBody.
Definition at line 67 of file SimObj.cpp.
 {
     btCollisionObject* col_obj = GetCollisionObject();
     btTransform trans = col_obj->getWorldTransform();
     btQuaternion bt_q = btQuaternion(static_cast<btScalar>(q.x()),
         static_cast<btScalar>(q.y()),
         static_cast<btScalar>(q.z()),
         static_cast<btScalar>(q.w()));
     trans.setRotation(bt_q);
     col_obj->setWorldTransform(trans);
 }
References GetCollisionObject().
SetRotation() [2/2]
void cSimObj::SetRotation (const tVector & axis, double theta) virtual
Reimplemented in cSimCharacter, and cSimRigidBody.
Definition at line 61 of file SimObj.cpp.
 {
     tQuaternion q = cMathUtil::AxisAngleToQuaternion(axis, theta);
     SetRotation(q);
 }
References cMathUtil::AxisAngleToQuaternion().
Referenced by cSimRigidBody::SetRotation().
UpdateContact()
void cSimObj::UpdateContact (int contact_flags, int filter_flags) virtual
Reimplemented in cSimCharacter.
Definition at line 167 of file SimObj.cpp.
 {
     mContactHandle.mFlags = contact_flags;
     mContactHandle.mFilterFlags = filter_flags;
     if (mContactHandle.IsValid())
     {
         mWorld->UpdateContact(mContactHandle);
     }
 }
References cContactManager::tContactHandle::IsValid(), mContactHandle, cContactManager::tContactHandle::mFilterFlags, cContactManager::tContactHandle::mFlags, and mWorld.
Referenced by cGround::Init().
WorldToLocalPos()
tVector cSimObj::WorldToLocalPos (const tVector & world_pos) const virtual
Definition at line 108 of file SimObj.cpp.
 {
     tMatrix world_to_local = GetLocalTransform();
     tVector local_pt = world_pos;
     local_pt[3] = 1;
     local_pt = world_to_local * local_pt;
     local_pt[3] = 0;
     return local_pt;
 }
References GetLocalTransform().
Referenced by cDrawSceneSimChar::HandleRayTest().
Member Data Documentation
mColGroup
short cSimObj::mColGroup protected
Definition at line 72 of file SimObj.h.
Referenced by cSimObj(), GetColGroup(), and SetColGroup().
mColMask
short cSimObj::mColMask protected
Definition at line 73 of file SimObj.h.
Referenced by cSimObj(), GetColMask(), and SetColMask().
mColShape
std::unique_ptr<btCollisionShape> cSimObj::mColShape protected
Definition at line 67 of file SimObj.h.
Referenced by cSimBodyLink::FetchObjShape(), GetCollisionShape(), cGroundPlane::Init(), cSimBodyLink::Init(), cSimPlane::Init(), cSimSphere::Init(), cSimBox::Init(), cSimCylinder::Init(), cSimCapsule::Init(), cSimRigidBody::RemoveFromWorld(), cSimBodyLink::RemoveFromWorld(), and cGroundPlane::SampleHeight().
mContactHandle
cContactManager::tContactHandle cSimObj::mContactHandle protected
Definition at line 68 of file SimObj.h.
Referenced by GetContactHandle(), GetContactPts(), IsInContact(), RegisterContact(), and UpdateContact().
mEnableContactFall
bool cSimObj::mEnableContactFall protected
Definition at line 69 of file SimObj.h.
Referenced by cSimCharacter::cSimCharacter(), cSimCharacter::HasFallen(), and cSimCharacter::Init().
mType
eType cSimObj::mType protected
Definition at line 71 of file SimObj.h.
Referenced by cGround::cGround(), cSimObj(), GetType(), cSimBodyLink::Init(), cSimPlane::Init(), cSimSphere::Init(), cSimBox::Init(), cSimCapsule::Init(), and cSimCylinder::Init().
mWorld
std::shared_ptr<cWorld> cSimObj::mWorld protected
Definition at line 66 of file SimObj.h.
Referenced by cSimRigidBody::AddToWorld(), cSimRigidBody::ApplyForce(), cSimBodyLink::ApplyForce(), cSimRigidBody::ApplyTorque(), cSimBodyLink::ApplyTorque(), cSimCharacter::BuildBodyLinks(), cSimCharacter::BuildCollisionShape(), cSimCharacter::BuildConstraints(), cSimCharacter::BuildJoints(), cSimCharacter::BuildMultiBody(), cSimCharacter::BuildSimBody(), CalcAABB(), cSimRigidBody::Constrain(), GetContactPts(), cSimRigidBody::GetLinearVelocity(), GetPos(), cSimPlane::GetSize(), cSimBox::GetSize(), cSimSphere::GetSize(), cSimCylinder::GetSize(), cSimCapsule::GetSize(), GetWorld(), cSimCharacter::GetWorld(), GetWorldTransform(), cSimBodyLink::Init(), cSimCharacter::Init(), cSimBodyLink::InitSize(), IsInContact(), RegisterContact(), cSimRigidBody::RemoveFromWorld(), cSimBodyLink::RemoveFromWorld(), cSimCharacter::RemoveFromWorld(), cSimRigidBody::SetLinearVelocity(), SetPos(), cSimCharacter::SetPose(), cSimCharacter::SetVel(), UpdateContact(), and cSimCharacter::UpdateLinkVel().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimObj.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimObj.cpp