My Project: cDrawMesh Class Reference
cDrawMesh Class Reference
#include <DrawMesh.h>
Public Member Functions
cDrawMesh ()
~cDrawMesh ()
void Init (int num_buffers)
void Draw (GLenum primitive=GL_TRIANGLES)
void Draw (GLenum primitive, int idx_start)
void Draw (GLenum primitive, int idx_start, int idx_end)
void AddBuffer (int buff_num)
void LoadVBuffer (unsigned int buffer_num, int size, GLubyte *data, int data_offset, int num_attr, tAttribInfo *attr_info)
void LoadIBuffer (int num_elem, int elem_size, int *data)
const float * GetData (int i) const
const int * GetIdxData () const
int GetNumVBO ()
void SyncGPU (unsigned int base, size_t extent=0)
int GetNumFaces () const
int GetNumVerts () const
Private Member Functions
void ResizeBuffer (int size)
Private Attributes
GLsizei mNumElem
cIBuffer mIbo
cRenderState mState
std::vector< cVertexBuffer > mVbos
Detailed Description
Storage for all of the vertex attributes needed for rending a single mesh, as well as any state data specific to that mesh. (such as object model transforms)
Definition at line 29 of file DrawMesh.h.
Constructor & Destructor Documentation
cDrawMesh()
cDrawMesh::cDrawMesh ()
Definition at line 22 of file DrawMesh.cpp.
                      : mNumElem(0), mVbos(0)
 {
 }
~cDrawMesh()
cDrawMesh::~cDrawMesh ()
Definition at line 26 of file DrawMesh.cpp.
 {
 }
Member Function Documentation
AddBuffer()
void cDrawMesh::AddBuffer (int buff_num)
Definition at line 64 of file DrawMesh.cpp.
 {
     mVbos.push_back(cVertexBuffer(buff_num, mState));
     mVbos[buff_num].mRenderID = mVbos[buff_num].mRenderID + 1;
 }
References mState, and mVbos.
Referenced by LoadVBuffer().
Draw() [1/3]
void cDrawMesh::Draw (GLenum primitive, int idx_start)
Definition at line 47 of file DrawMesh.cpp.
 {
     mState.BindVAO();
     SyncGPU(0, 0);
     cDrawUtil::LoadShaderUniforms();
     glDrawElements(primitive, mNumElem - start_idx, GL_UNSIGNED_INT, (void*)(start_idx * sizeof(GLuint)));
 }
References cRenderState::BindVAO(), cDrawUtil::LoadShaderUniforms(), mNumElem, mState, and SyncGPU().
Draw() [2/3]
void cDrawMesh::Draw (GLenum primitive, int idx_start, int idx_end)
Definition at line 55 of file DrawMesh.cpp.
 {
     mState.BindVAO();
     SyncGPU(0, 0);
     int num_elem = std::min(idx_end, mNumElem) - idx_start;
     cDrawUtil::LoadShaderUniforms();
     glDrawElements(primitive, num_elem, GL_UNSIGNED_INT, (void*)(idx_start * sizeof(GLuint)));
 }
References cRenderState::BindVAO(), cDrawUtil::LoadShaderUniforms(), mNumElem, mState, and SyncGPU().
Draw() [3/3]
void cDrawMesh::Draw (GLenum primitive = GL_TRIANGLES)
Definition at line 42 of file DrawMesh.cpp.
 {
     Draw(primitive, 0);
 }
Referenced by cDrawCharacter::DrawShapeMesh().
GetData()
const float* cDrawMesh::GetData (int i) const inline
Definition at line 50 of file DrawMesh.h.
 { return mVbos[i].mLocalData; }
References mVbos.
Referenced by cMeshUtil::GetVertex().
GetIdxData()
const int* cDrawMesh::GetIdxData () const inline
Definition at line 51 of file DrawMesh.h.
 { return reinterpret_cast<int*>(mIbo.mLocalData); }
References mIbo, and cIBuffer::mLocalData.
Referenced by cMeshUtil::GetFace().
GetNumFaces()
int cDrawMesh::GetNumFaces () const
Definition at line 101 of file DrawMesh.cpp.
 {
     const int verts_per_face = 3;
     int num_faces = mIbo.GetNumElems() / verts_per_face;
     return num_faces;
 }
References cIBuffer::GetNumElems(), and mIbo.
Referenced by cMeshUtil::ExpandFaces(), and cMeshUtil::RayTest().
GetNumVBO()
int cDrawMesh::GetNumVBO () inline
Definition at line 53 of file DrawMesh.h.
 { return static_cast<int>(mVbos.size()); }
References mVbos.
GetNumVerts()
int cDrawMesh::GetNumVerts () const
Definition at line 108 of file DrawMesh.cpp.
 {
     int num_verts = 0;
     if (mVbos.size() > 0)
     {
         const cVertexBuffer& vbos = mVbos[0];
         int comp = vbos.mAttrInfo->mNumComp;
         int attr_size = vbos.mAttrInfo->mAttribSize;
         int size = vbos.mSize;
         num_verts = size / (comp * attr_size);
     }
     return num_verts;
 }
References tAttribInfo::mAttribSize, cVertexBuffer::mAttrInfo, tAttribInfo::mNumComp, cVertexBuffer::mSize, and mVbos.
Init()
void cDrawMesh::Init (int num_buffers)
Definition at line 30 of file DrawMesh.cpp.
 {
     mState.BindVAO();
     mVbos.resize(num_buffers);
     // set the buffer IDs that the buffer objects will use
     mIbo.SetRender(0, mState);
     for (int i = 0; i < num_buffers; i++)
         mVbos[i].SetRender(i + 1, mState);
 }
References cRenderState::BindVAO(), mIbo, mState, mVbos, and cIBuffer::SetRender().
Referenced by cMeshUtil::BuildDrawMesh().
LoadIBuffer()
void cDrawMesh::LoadIBuffer (int num_elem, int elem_size, int * data)
Definition at line 78 of file DrawMesh.cpp.
 {
     // no need to bind vertex array buffer, since this is an index buffer
     mIbo.LoadBuffer(num_elem, elem_size, data);
     mNumElem = num_elem;
 }
References cIBuffer::LoadBuffer(), mIbo, and mNumElem.
Referenced by cMeshUtil::BuildDrawMesh().
LoadVBuffer()
void cDrawMesh::LoadVBuffer (unsigned int buffer_num, int size, GLubyte * data, int data_offset, int num_attr, tAttribInfo * attr_info)
Definition at line 70 of file DrawMesh.cpp.
 {
     if (buffer_num >= mVbos.size())
         AddBuffer(buffer_num);
     mVbos[buffer_num].LoadBuffer(data_size, data, data_offset, num_attr, attr_info);
 }
References AddBuffer(), and mVbos.
Referenced by cMeshUtil::BuildDrawMesh().
ResizeBuffer()
void cDrawMesh::ResizeBuffer (int size) private
SyncGPU()
void cDrawMesh::SyncGPU (unsigned int base, size_t extent = 0)
Definition at line 87 of file DrawMesh.cpp.
 {
     if (base + extent > mVbos.size() ||
         extent == 0)
         extent = mVbos.size() - base;
     // bind the vertex array object to store all the vertex settings
     mState.BindVAO();
     for (unsigned int i = base; i < extent; i++)
         mVbos[i].SyncBuffer();
     mIbo.SyncBuffer();
 }
References cRenderState::BindVAO(), mIbo, mState, mVbos, and cIBuffer::SyncBuffer().
Referenced by Draw().
Member Data Documentation
mIbo
cIBuffer cDrawMesh::mIbo private
Definition at line 62 of file DrawMesh.h.
Referenced by GetIdxData(), GetNumFaces(), Init(), LoadIBuffer(), and SyncGPU().
mNumElem
GLsizei cDrawMesh::mNumElem private
Definition at line 61 of file DrawMesh.h.
Referenced by Draw(), and LoadIBuffer().
mState
cRenderState cDrawMesh::mState private
Definition at line 64 of file DrawMesh.h.
Referenced by AddBuffer(), Draw(), Init(), and SyncGPU().
mVbos
std::vector<cVertexBuffer> cDrawMesh::mVbos private
Definition at line 65 of file DrawMesh.h.
Referenced by AddBuffer(), GetData(), GetNumVBO(), GetNumVerts(), Init(), LoadVBuffer(), and SyncGPU().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/DrawMesh.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/DrawMesh.cpp