My Project: cSpAlg Class Reference
cSpAlg Class Reference
#include <SpAlg.h>
Public Types
typedef Eigen::Matrix< double, gSVTransRows, gSVTransCols > tSpTrans
typedef Eigen::Matrix< double, gSpVecSize, 1 > tSpVec
typedef Eigen::Matrix< double, gSpVecSize, gSpVecSize > tSpMat
Static Public Member Functions
static tSpVec ConvertCoordM (const tSpVec &m0, const tVector &origin0, const tVector &origin1)
static tSpVec ConvertCoordM (const tSpVec &m0, const tVector &origin0, const tMatrix &R0, const tVector &origin1, const tMatrix &R1)
static tSpVec ConvertCoordM (const tSpVec &m0, const tVector &origin0, const tVector &origin1, const tMatrix &R)
static tSpVec ConvertCoordF (const tSpVec &m0, const tVector &origin0, const tVector &origin1)
static tSpVec ConvertCoordF (const tSpVec &m0, const tVector &origin0, const tMatrix &R0, const tVector &origin1, const tMatrix &R1)
static tSpVec ConvertCoordF (const tSpVec &m0, const tVector &origin0, const tVector &origin1, const tMatrix &R)
static tSpVec CrossM (const tSpVec &sv, const tSpVec &m)
static Eigen::MatrixXd CrossMs (const tSpVec &sv, const Eigen::MatrixXd &ms)
static tSpVec CrossF (const tSpVec &sv, const tSpVec &f)
static Eigen::MatrixXd CrossFs (const tSpVec &sv, const Eigen::MatrixXd &fs)
static tSpVec BuildSV (const tVector &v)
static tSpVec BuildSV (const tVector &o, const tVector &v)
static tVector GetOmega (const tSpVec &sv)
static void SetOmega (const tVector &o, tSpVec &out_sv)
static tVector GetV (const tSpVec &sv)
static void SetV (const tVector &v, tSpVec &out_sv)
static tSpTrans BuildTrans ()
static tSpTrans BuildTrans (const tMatrix &E, const tVector &r)
static tSpTrans BuildTrans (const tVector &r)
static tSpTrans MatToTrans (const tMatrix &mat)
static tMatrix TransToMat (const tSpTrans &X)
static tSpMat BuildSpatialMatM (const tSpTrans &X)
static tSpMat BuildSpatialMatF (const tSpTrans &X)
static tSpTrans InvTrans (const tSpTrans &X)
static tMatrix GetRot (const tSpTrans &X)
static void SetRot (const tMatrix &E, tSpTrans &out_X)
static tVector GetRad (const tSpTrans &X)
static void SetRad (const tVector &r, tSpTrans &out_X)
static tSpVec ApplyTransM (const tSpTrans &X, const tSpVec &sv)
static tSpVec ApplyTransF (const tSpTrans &X, const tSpVec &sv)
static Eigen::MatrixXd ApplyTransM (const tSpTrans &X, const Eigen::MatrixXd &sm)
static Eigen::MatrixXd ApplyTransF (const tSpTrans &X, const Eigen::MatrixXd &sm)
static tSpVec ApplyInvTransM (const tSpTrans &X, const tSpVec &sv)
static tSpVec ApplyInvTransF (const tSpTrans &X, const tSpVec &sv)
static Eigen::MatrixXd ApplyInvTransM (const tSpTrans &X, const Eigen::MatrixXd &sm)
static Eigen::MatrixXd ApplyInvTransF (const tSpTrans &X, const Eigen::MatrixXd &sm)
static tSpTrans CompTrans (const tSpTrans &X0, const tSpTrans &X1)
static tSpTrans GetTrans (const Eigen::MatrixXd &trans_arr, int j)
Static Public Attributes
const static int gSpVecSize = 6
const static int gSVTransRows = 3
const static int gSVTransCols = 4
Detailed Description
Definition at line 6 of file SpAlg.h.
Member Typedef Documentation
tSpMat
typedef Eigen::Matrix<double, gSpVecSize, gSpVecSize> cSpAlg::tSpMat
Definition at line 16 of file SpAlg.h.
tSpTrans
typedef Eigen::Matrix<double, gSVTransRows, gSVTransCols> cSpAlg::tSpTrans
Definition at line 14 of file SpAlg.h.
tSpVec
typedef Eigen::Matrix<double, gSpVecSize, 1> cSpAlg::tSpVec
Definition at line 15 of file SpAlg.h.
Member Function Documentation
ApplyInvTransF() [1/2]
Eigen::MatrixXd cSpAlg::ApplyInvTransF (const tSpTrans & X, const Eigen::MatrixXd & sm) static
Definition at line 322 of file SpAlg.cpp.
 {
     assert(sm.rows() == gSpVecSize);
     Eigen::MatrixXd result(sm.rows(), sm.cols());
     for (int i = 0; i < sm.cols(); ++i)
     {
         const tSpVec& curr_sv = sm.col(i);
         result.col(i) = ApplyInvTransF(X, curr_sv);
     }
     return result;
 }
References ApplyInvTransF(), and gSpVecSize.
ApplyInvTransF() [2/2]
cSpAlg::tSpVec cSpAlg::ApplyInvTransF (const tSpTrans & X, const tSpVec & sv) static
Definition at line 296 of file SpAlg.cpp.
 {
     tMatrix E = GetRot(X);
     tVector r = GetRad(X);
     tVector o0 = GetOmega(sv);
     tVector v0 = GetV(sv);
     tVector o1 = E.transpose() * o0 + r.cross3(E.transpose() * v0);
     tVector v1 = E.transpose() * v0;
     tSpVec new_vec = BuildSV(o1, v1);
     return new_vec;
 }
References BuildSV(), GetOmega(), GetRad(), GetRot(), and GetV().
Referenced by ApplyInvTransF().
ApplyInvTransM() [1/2]
Eigen::MatrixXd cSpAlg::ApplyInvTransM (const tSpTrans & X, const Eigen::MatrixXd & sm) static
Definition at line 310 of file SpAlg.cpp.
 {
     assert(sm.rows() == gSpVecSize);
     Eigen::MatrixXd result(sm.rows(), sm.cols());
     for (int i = 0; i < sm.cols(); ++i)
     {
         const tSpVec& curr_sv = sm.col(i);
         result.col(i) = ApplyInvTransM(X, curr_sv);
     }
     return result;
 }
References ApplyInvTransM(), and gSpVecSize.
ApplyInvTransM() [2/2]
cSpAlg::tSpVec cSpAlg::ApplyInvTransM (const tSpTrans & X, const tSpVec & sv) static
Definition at line 282 of file SpAlg.cpp.
 {
     tMatrix E = GetRot(X);
     tVector r = GetRad(X);
     tVector o0 = GetOmega(sv);
     tVector v0 = GetV(sv);
     tVector o1 = E.transpose() * o0;
     tVector v1 = E.transpose() * v0 + r.cross3(E.transpose() * o0);
     tSpVec new_vec = BuildSV(o1, v1);
     return new_vec;
 }
References BuildSV(), GetOmega(), GetRad(), GetRot(), and GetV().
Referenced by ApplyInvTransM(), cRBDUtil::BuildEndEffectorJacobian(), cRBDUtil::BuildJacobian(), cRBDUtil::BuildJacobianDot(), and cRBDUtil::CalcVelProdAcc().
ApplyTransF() [1/2]
Eigen::MatrixXd cSpAlg::ApplyTransF (const tSpTrans & X, const Eigen::MatrixXd & sm) static
Definition at line 270 of file SpAlg.cpp.
 {
     assert(sm.rows() == gSpVecSize);
     Eigen::MatrixXd result(gSpVecSize, sm.cols());
     for (int i = 0; i < sm.cols(); ++i)
     {
         const tSpVec& curr_sv = sm.col(i);
         result.col(i) = ApplyTransF(X, curr_sv);
     }
     return result;
 }
References ApplyTransF(), and gSpVecSize.
ApplyTransF() [2/2]
cSpAlg::tSpVec cSpAlg::ApplyTransF (const tSpTrans & X, const tSpVec & sv) static
Definition at line 244 of file SpAlg.cpp.
 {
     tMatrix E = GetRot(X);
     tVector r = GetRad(X);
     tVector o0 = GetOmega(sv);
     tVector v0 = GetV(sv);
     tVector o1 = E * (o0 - r.cross3(v0));
     tVector v1 = E * v0;
     tSpVec new_vec = BuildSV(o1, v1);
     return new_vec;
 }
References BuildSV(), GetOmega(), GetRad(), GetRot(), and GetV().
Referenced by cSimBodyJoint::ApplyTauPlanar(), ApplyTransF(), cRBDUtil::CalcGravityForce(), ConvertCoordF(), and cRBDUtil::SolveInvDyna().
ApplyTransM() [1/2]
Eigen::MatrixXd cSpAlg::ApplyTransM (const tSpTrans & X, const Eigen::MatrixXd & sm) static
Definition at line 258 of file SpAlg.cpp.
 {
     assert(sm.rows() == gSpVecSize);
     Eigen::MatrixXd result(gSpVecSize, sm.cols());
     for (int i = 0; i < sm.cols(); ++i)
     {
         const tSpVec& curr_sv = sm.col(i);
         result.col(i) = ApplyTransM(X, curr_sv);
     }
     return result;
 }
References ApplyTransM(), and gSpVecSize.
ApplyTransM() [2/2]
cSpAlg::tSpVec cSpAlg::ApplyTransM (const tSpTrans & X, const tSpVec & sv) static
Definition at line 230 of file SpAlg.cpp.
 {
     tMatrix E = GetRot(X);
     tVector r = GetRad(X);
     tVector o0 = GetOmega(sv);
     tVector v0 = GetV(sv);
     tVector o1 = E * o0;
     tVector v1 = E * (v0 - r.cross3(o0));
     tSpVec new_vec = BuildSV(o1, v1);
     return new_vec;
 }
References BuildSV(), GetOmega(), GetRad(), GetRot(), and GetV().
Referenced by ApplyTransM(), cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildCOMVelProdAccAux(), cRBDUtil::BuildEndEffectorJacobian(), cSimBodyJoint::BuildVel(), cRBDUtil::CalcCoM(), cRBDUtil::CalcGravityForce(), cKinTree::CalcWorldAngularVel(), cKinTree::CalcWorldVel(), ConvertCoordM(), cSimBodyJoint::SetVel(), and cRBDUtil::SolveInvDyna().
BuildSpatialMatF()
cSpAlg::tSpMat cSpAlg::BuildSpatialMatF (const tSpTrans & X) static
Definition at line 184 of file SpAlg.cpp.
 {
     tSpMat m = tSpMat::Zero();
     tMatrix E = GetRot(X);
     tVector r = GetRad(X);
     tMatrix Er = E * cMathUtil::CrossMat(r);
     m.block(0, 0, 3, 3) = E.block(0, 0, 3, 3);
     m.block(3, 3, 3, 3) = E.block(0, 0, 3, 3);
     m.block(0, 3, 3, 3) = -Er.block(0, 0, 3, 3);
     return m;
 }
References cMathUtil::CrossMat(), GetRad(), and GetRot().
Referenced by cRBDUtil::BuildInertiaSpatialMat(), and cRBDUtil::BuildMassMat().
BuildSpatialMatM()
cSpAlg::tSpMat cSpAlg::BuildSpatialMatM (const tSpTrans & X) static
Definition at line 171 of file SpAlg.cpp.
 {
     tSpMat m = tSpMat::Zero();
     tMatrix E = GetRot(X);
     tVector r = GetRad(X);
     tMatrix Er = E * cMathUtil::CrossMat(r);
     m.block(0, 0, 3, 3) = E.block(0, 0, 3, 3);
     m.block(3, 3, 3, 3) = E.block(0, 0, 3, 3);
     m.block(3, 0, 3, 3) = -Er.block(0, 0, 3, 3);
     return m;
 }
References cMathUtil::CrossMat(), GetRad(), and GetRot().
Referenced by cRBDUtil::BuildInertiaSpatialMat(), and cRBDUtil::BuildMassMat().
BuildSV() [1/2]
cSpAlg::tSpVec cSpAlg::BuildSV (const tVector & o, const tVector & v) static
Definition at line 102 of file SpAlg.cpp.
 {
     tSpVec sv;
     SetOmega(o, sv);
     SetV(v, sv);
     return sv;
 }
References SetOmega(), and SetV().
BuildSV() [2/2]
cSpAlg::tSpVec cSpAlg::BuildSV (const tVector & v) static
Definition at line 97 of file SpAlg.cpp.
 {
     return BuildSV(tVector::Zero(), v);
 }
Referenced by ApplyInvTransF(), ApplyInvTransM(), cSimBodyJoint::ApplyTauPlanar(), ApplyTransF(), ApplyTransM(), cSimBodyJoint::BuildVel(), cRBDUtil::CalcGravityForce(), cRBDUtil::CalcVelProdAcc(), CrossF(), CrossM(), cSimBodyJoint::SetVel(), and cRBDUtil::SolveInvDyna().
BuildTrans() [1/3]
cSpAlg::tSpTrans cSpAlg::BuildTrans () static
Definition at line 134 of file SpAlg.cpp.
 {
     return BuildTrans(tMatrix::Identity(), tVector::Zero());
 }
Referenced by cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildCOMVelProdAccAux(), cRBDUtil::BuildEndEffectorJacobian(), BuildTrans(), cRBDUtil::CalcCoM(), cKinTree::CalcWorldAngularVel(), cRBDUtil::CalcWorldJointTransforms(), cKinTree::CalcWorldVel(), CompTrans(), ConvertCoordF(), ConvertCoordM(), InvTrans(), and MatToTrans().
BuildTrans() [2/3]
cSpAlg::tSpTrans cSpAlg::BuildTrans (const tMatrix & E, const tVector & r) static
Definition at line 139 of file SpAlg.cpp.
 {
     tSpTrans X;
     SetRad(r, X);
     SetRot(E, X);
     return X;
 }
References SetRad(), and SetRot().
BuildTrans() [3/3]
cSpAlg::tSpTrans cSpAlg::BuildTrans (const tVector & r) static
Definition at line 147 of file SpAlg.cpp.
 {
     return BuildTrans(tMatrix::Identity(), r);
 }
References BuildTrans().
CompTrans()
cSpAlg::tSpTrans cSpAlg::CompTrans (const tSpTrans & X0, const tSpTrans & X1) static
Definition at line 334 of file SpAlg.cpp.
 {
     tMatrix E0 = GetRot(X0);
     tMatrix E1 = GetRot(X1);
     tVector r0 = GetRad(X0);
     tVector r1 = GetRad(X1);
     tSpTrans X = BuildTrans(E0 * E1, r1 + E1.transpose() * r0);
     return X;
 }
References BuildTrans(), GetRad(), and GetRot().
Referenced by cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildEndEffectorJacobian(), and cRBDUtil::CalcWorldJointTransforms().
ConvertCoordF() [1/3]
cSpAlg::tSpVec cSpAlg::ConvertCoordF (const tSpVec & m0, const tVector & origin0, const tMatrix & R0, const tVector & origin1, const tMatrix & R1) static
Definition at line 32 of file SpAlg.cpp.
 {
     tMatrix R = R1 * R0.transpose();
     return ConvertCoordF(f0, origin0, origin1, R);
 }
References ConvertCoordF().
ConvertCoordF() [2/3]
cSpAlg::tSpVec cSpAlg::ConvertCoordF (const tSpVec & m0, const tVector & origin0, const tVector & origin1) static
Definition at line 27 of file SpAlg.cpp.
 {
     return ConvertCoordF(f0, origin0, origin1, tMatrix::Identity());
 }
Referenced by ConvertCoordF().
ConvertCoordF() [3/3]
cSpAlg::tSpVec cSpAlg::ConvertCoordF (const tSpVec & m0, const tVector & origin0, const tVector & origin1, const tMatrix & R) static
Definition at line 39 of file SpAlg.cpp.
 {
     tSpTrans X = BuildTrans(R, origin1 - origin0);
     return ApplyTransF(X, f0);
 }
References ApplyTransF(), and BuildTrans().
ConvertCoordM() [1/3]
cSpAlg::tSpVec cSpAlg::ConvertCoordM (const tSpVec & m0, const tVector & origin0, const tMatrix & R0, const tVector & origin1, const tMatrix & R1) static
Definition at line 13 of file SpAlg.cpp.
 {
     tMatrix R = R1 * R0.transpose();
     return ConvertCoordM(m0, origin0, origin1, R);
 }
References ConvertCoordM().
ConvertCoordM() [2/3]
cSpAlg::tSpVec cSpAlg::ConvertCoordM (const tSpVec & m0, const tVector & origin0, const tVector & origin1) static
Definition at line 8 of file SpAlg.cpp.
 {
     return ConvertCoordM(m0, origin0, origin1, tMatrix::Identity());
 }
Referenced by ConvertCoordM().
ConvertCoordM() [3/3]
cSpAlg::tSpVec cSpAlg::ConvertCoordM (const tSpVec & m0, const tVector & origin0, const tVector & origin1, const tMatrix & R) static
Definition at line 21 of file SpAlg.cpp.
 {
     tSpTrans X = BuildTrans(R, origin1 - origin0);
     return ApplyTransM(X, m0);
 }
References ApplyTransM(), and BuildTrans().
CrossF()
cSpAlg::tSpVec cSpAlg::CrossF (const tSpVec & sv, const tSpVec & f) static
Definition at line 72 of file SpAlg.cpp.
 {
     tVector sv_o = GetOmega(sv);
     tVector sv_v = GetV(sv);
     tVector f_o = GetOmega(f);
     tVector f_v = GetV(f);
     tVector o = sv_o.cross3(f_o) + sv_v.cross3(f_v);
     tVector v = sv_o.cross3(f_v);
     return BuildSV(o, v);
 }
References BuildSV(), GetOmega(), and GetV().
Referenced by CrossFs(), and cRBDUtil::SolveInvDyna().
CrossFs()
Eigen::MatrixXd cSpAlg::CrossFs (const tSpVec & sv, const Eigen::MatrixXd & fs) static
Definition at line 85 of file SpAlg.cpp.
 {
     assert(fs.rows() == gSpVecSize);
     Eigen::MatrixXd result(gSpVecSize, fs.cols());
     for (int i = 0; i < fs.cols(); ++i)
     {
         const tSpVec& curr_f = fs.col(i);
         result.col(i) = CrossF(sv, curr_f);
     }
     return result;
 }
References CrossF(), and gSpVecSize.
CrossM()
cSpAlg::tSpVec cSpAlg::CrossM (const tSpVec & sv, const tSpVec & m) static
Definition at line 47 of file SpAlg.cpp.
 {
     tVector sv_o = GetOmega(sv);
     tVector sv_v = GetV(sv);
     tVector m_o = GetOmega(m);
     tVector m_v = GetV(m);
     tVector o = sv_o.cross3(m_o);
     tVector v = sv_v.cross3(m_o) + sv_o.cross3(m_v);
     return BuildSV(o, v);
 }
References BuildSV(), GetOmega(), and GetV().
Referenced by CrossMs(), and cRBDUtil::SolveInvDyna().
CrossMs()
Eigen::MatrixXd cSpAlg::CrossMs (const tSpVec & sv, const Eigen::MatrixXd & ms) static
Definition at line 60 of file SpAlg.cpp.
 {
     assert(ms.rows() == gSpVecSize);
     Eigen::MatrixXd result(gSpVecSize, ms.cols());
     for (int i = 0; i < ms.cols(); ++i)
     {
         const tSpVec& curr_m = ms.col(i);
         result.col(i) = CrossM(sv, curr_m);
     }
     return result;
 }
References CrossM(), and gSpVecSize.
Referenced by cRBDUtil::BuildJacobianDot().
GetOmega()
tVector cSpAlg::GetOmega (const tSpVec & sv) static
Definition at line 110 of file SpAlg.cpp.
 {
     tVector o = tVector::Zero();
     o.block(0, 0, 3, 1) = sv.block(0, 0, 3, 1);
     return o;
 }
Referenced by ApplyInvTransF(), ApplyInvTransM(), cSimBodyJoint::ApplyTauPlanar(), ApplyTransF(), ApplyTransM(), cSimBodyJoint::BuildVel(), cKinTree::CalcWorldAngularVel(), CrossF(), CrossM(), cSimBodyJoint::GetTotalTorque(), and cSimJoint::GetTotalTorque().
GetRad()
tVector cSpAlg::GetRad (const tSpTrans & X) static
Definition at line 218 of file SpAlg.cpp.
 {
     tVector r = tVector::Zero();
     r.block(0, 0, 3, 1) = X.block(0, 3, 3, 1);
     return r;
 }
Referenced by ApplyInvTransF(), ApplyInvTransM(), ApplyTransF(), ApplyTransM(), BuildSpatialMatF(), BuildSpatialMatM(), cRBDModel::CalcJointWorldPos(), CompTrans(), InvTrans(), and TransToMat().
GetRot()
tMatrix cSpAlg::GetRot (const tSpTrans & X) static
Definition at line 206 of file SpAlg.cpp.
 {
     tMatrix E = tMatrix::Zero();
     E.block(0, 0, 3, 3) = X.block(0, 0, 3, 3);
     return E;
 }
Referenced by ApplyInvTransF(), ApplyInvTransM(), ApplyTransF(), ApplyTransM(), BuildSpatialMatF(), BuildSpatialMatM(), CompTrans(), InvTrans(), and TransToMat().
GetTrans()
cSpAlg::tSpTrans cSpAlg::GetTrans (const Eigen::MatrixXd & trans_arr, int j) static
Definition at line 345 of file SpAlg.cpp.
 {
     assert(trans_arr.rows() >= gSVTransRows);
     assert((trans_arr.rows() % gSVTransRows) == 0);
     assert(trans_arr.cols() == gSVTransCols);
     int row_idx = j * gSVTransRows;
     assert(row_idx <= trans_arr.rows() - gSVTransRows);
     tSpTrans X = trans_arr.block(row_idx, 0, gSVTransRows, gSVTransCols);
     return X;
 }
References gSVTransCols, and gSVTransRows.
Referenced by cRBDUtil::CalcWorldJointTransforms(), and cRBDModel::GetSpWorldJointTrans().
GetV()
tVector cSpAlg::GetV (const tSpVec & sv) static
Definition at line 122 of file SpAlg.cpp.
 {
     tVector v = tVector::Zero();
     v.block(0, 0, 3, 1) = sv.block(3, 0, 3, 1);
     return v;
 }
Referenced by ApplyInvTransF(), ApplyInvTransM(), cSimBodyJoint::ApplyTauPlanar(), ApplyTransF(), ApplyTransM(), cSimBodyJoint::BuildVel(), cRBDUtil::CalcCoM(), cKinTree::CalcWorldVel(), CrossF(), CrossM(), cSimBodyJoint::GetTotalForce(), cSimJoint::GetTotalForce(), and cSimBodyJoint::SetVel().
InvTrans()
cSpAlg::tSpTrans cSpAlg::InvTrans (const tSpTrans & X) static
Definition at line 198 of file SpAlg.cpp.
 {
     tMatrix E = GetRot(X);
     tVector r = GetRad(X);
     tSpTrans inv_X = BuildTrans(E.transpose(), -E * r);
     return inv_X;
 }
References BuildTrans(), GetRad(), and GetRot().
Referenced by cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildInertiaSpatialMat(), cRBDUtil::BuildMassMat(), cRBDUtil::BuildParentChildTransform(), cRBDUtil::CalcCoM(), and cRBDModel::GetSpJointWorldTrans().
MatToTrans()
cSpAlg::tSpTrans cSpAlg::MatToTrans (const tMatrix & mat) static
Definition at line 152 of file SpAlg.cpp.
 {
     tMatrix E = mat;
     tVector r = mat.col(3);
     r[3] = 0;
     r = -E.transpose() * r;
     return BuildTrans(E, r);
 }
References BuildTrans().
Referenced by cSimBodyJoint::ApplyTauPlanar(), cRBDUtil::BuildChildParentTransform(), cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildInertiaSpatialMat(), cSimBodyJoint::BuildVel(), cRBDModel::GetSpChildParentTrans(), cRBDModel::GetSpParentChildTrans(), and cSimBodyJoint::SetVel().
SetOmega()
void cSpAlg::SetOmega (const tVector & o, tSpVec & out_sv) static
Definition at line 117 of file SpAlg.cpp.
 {
     out_sv.block(0, 0, 3, 1) = o.block(0, 0, 3, 1);
 }
Referenced by BuildSV(), cSimBodyJoint::SetTotalTorque(), and cSimJoint::SetTotalTorque().
SetRad()
void cSpAlg::SetRad (const tVector & r, tSpTrans & out_X) static
Definition at line 225 of file SpAlg.cpp.
 {
     out_X.block(0, 3, 3, 1) = r.block(0, 0, 3, 1);
 }
Referenced by BuildTrans().
SetRot()
void cSpAlg::SetRot (const tMatrix & E, tSpTrans & out_X) static
Definition at line 213 of file SpAlg.cpp.
 {
     out_X.block(0, 0, 3, 3) = E.block(0, 0, 3, 3);
 }
Referenced by BuildTrans().
SetV()
void cSpAlg::SetV (const tVector & v, tSpVec & out_sv) static
Definition at line 129 of file SpAlg.cpp.
 {
     out_sv.block(3, 0, 3, 1) = v.block(0, 0, 3, 1);
 }
Referenced by BuildSV(), cSimBodyJoint::SetTotalForce(), and cSimJoint::SetTotalForce().
TransToMat()
tMatrix cSpAlg::TransToMat (const tSpTrans & X) static
Definition at line 161 of file SpAlg.cpp.
 {
     tMatrix E = GetRot(X);
     tVector r = GetRad(X);
     tMatrix m = E;
     m.col(3) = -E * r;
     m(3, 3) = 1;
     return m;
 }
References GetRad(), and GetRot().
Referenced by cRBDUtil::BuildCOMJacobian(), cRBDUtil::CalcCoM(), cRBDModel::GetJointWorldMat(), and cRBDModel::GetWorldJointMat().
Member Data Documentation
gSpVecSize
const int cSpAlg::gSpVecSize = 6 static
Definition at line 9 of file SpAlg.h.
Referenced by ApplyInvTransF(), ApplyInvTransM(), ApplyTransF(), ApplyTransM(), cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildEndEffectorJacobian(), cRBDUtil::BuildJacobian(), cRBDUtil::BuildJacobianDot(), cRBDUtil::BuildJointSubspaceFixed(), cRBDUtil::BuildJointSubspacePlanar(), cRBDUtil::BuildJointSubspacePrismatic(), cRBDUtil::BuildJointSubspaceRevolute(), cRBDUtil::BuildJointSubspaceRoot(), cRBDUtil::BuildJointSubspaceSpherical(), cRBDUtil::BuildMassMat(), cRBDUtil::CalcGravityForce(), cRBDUtil::CalcVelProdAcc(), CrossFs(), CrossMs(), cRBDUtil::ExtractEndEffJacobian(), cRBDModel::Init(), cRBDModel::InitJointSubspaceArr(), cRBDUtil::MultJacobianEndEff(), and cRBDUtil::SolveInvDyna().
gSVTransCols
const int cSpAlg::gSVTransCols = 4 static
Definition at line 11 of file SpAlg.h.
Referenced by cRBDUtil::CalcWorldJointTransforms(), GetTrans(), and cRBDModel::Init().
gSVTransRows
const int cSpAlg::gSVTransRows = 3 static
Definition at line 10 of file SpAlg.h.
Referenced by cRBDUtil::CalcWorldJointTransforms(), GetTrans(), and cRBDModel::Init().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SpAlg.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SpAlg.cpp