My Project: cJsonUtil Class Reference
cJsonUtil Class Reference
#include <JsonUtil.h>
Static Public Member Functions
static std::string BuildVectorJson (const tVector &vec)
static bool ReadVectorJson (const Json::Value &root, tVector &out_vec)
static std::string BuildVectorJson (const Eigen::VectorXd &vec)
static std::string BuildVectorString (const Eigen::VectorXd &vec)
static bool ReadVectorJson (const Json::Value &root, Eigen::VectorXd &out_vec)
Detailed Description
Definition at line 7 of file JsonUtil.h.
Member Function Documentation
BuildVectorJson() [1/2]
std::string cJsonUtil::BuildVectorJson (const Eigen::VectorXd & vec) static
Definition at line 39 of file JsonUtil.cpp.
 {
     std::string json = BuildVectorString(vec);
     json = "[" + json + "]";
     return json;
 }
References BuildVectorString().
BuildVectorJson() [2/2]
std::string cJsonUtil::BuildVectorJson (const tVector & vec) static
Definition at line 3 of file JsonUtil.cpp.
 {
     std::string json = "";
     for (int i = 0; i < vec.size(); ++i)
     {
         if (i != 0)
         {
             json += ", ";
         }
         json += std::to_string(vec[i]);
     }
     json = "[" + json + "]";
     return json;
 }
Referenced by cMotion::BuildFrameJson(), cCharacter::BuildStateJson(), and cMotion::Output().
BuildVectorString()
std::string cJsonUtil::BuildVectorString (const Eigen::VectorXd & vec) static
Definition at line 46 of file JsonUtil.cpp.
 {
     std::string str = "";
     char str_buffer[32];
     for (int i = 0; i < vec.size(); ++i)
     {
         if (i != 0)
         {
             str += ",";
         }
         sprintf(str_buffer, "%20.10f", vec[i]);
         str += std::string(str_buffer);
     }
     return str;
 }
Referenced by BuildVectorJson().
ReadVectorJson() [1/2]
bool cJsonUtil::ReadVectorJson (const Json::Value & root, Eigen::VectorXd & out_vec) static
Definition at line 62 of file JsonUtil.cpp.
 {
     bool succ = false;
     int num_vals = root.size();
     if (root.isArray())
     {
         out_vec.resize(num_vals);
         for (int i = 0; i < num_vals; ++i)
         {
             Json::Value json_elem = root.get(i, 0);
             out_vec[i] = json_elem.asDouble();
         }
         succ = true;
     }
     return succ;
 }
References Json::Value::asDouble(), Json::Value::get(), Json::Value::isArray(), and Json::Value::size().
ReadVectorJson() [2/2]
bool cJsonUtil::ReadVectorJson (const Json::Value & root, tVector & out_vec) static
Definition at line 18 of file JsonUtil.cpp.
 {
     bool succ = false;
     int num_vals = root.size();
     assert(num_vals <= 4);
     num_vals = std::min(num_vals, static_cast<int>(out_vec.size()));
     if (root.isArray())
     {
         out_vec.setZero();
         for (int i = 0; i < num_vals; ++i)
         {
             Json::Value json_elem = root.get(i, 0);
             out_vec[i] = json_elem.asDouble();
         }
         succ = true;
     }
     return succ;
 }
References Json::Value::asDouble(), Json::Value::get(), Json::Value::isArray(), and Json::Value::size().
Referenced by cCharacter::ParseState().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/JsonUtil.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/JsonUtil.cpp