My Project: lodepng Namespace Reference
lodepng Namespace Reference
Classes
struct ExtractPNG
struct ExtractZlib
struct ZlibBlockInfo
Functions
LodePNGInfo getPNGHeaderInfo (const std::vector< unsigned char > &png)
unsigned getChunkInfo (std::vector< std::string > &names, std::vector< size_t > &sizes, const std::vector< unsigned char > &png)
unsigned getChunks (std::vector< std::string > names[3], std::vector< std::vector< unsigned char > > chunks[3], const std::vector< unsigned char > &png)
unsigned insertChunks (std::vector< unsigned char > &png, const std::vector< std::vector< unsigned char > > chunks[3])
unsigned getFilterTypesInterlaced (std::vector< std::vector< unsigned char > > &filterTypes, const std::vector< unsigned char > &png)
unsigned getFilterTypes (std::vector< unsigned char > &filterTypes, const std::vector< unsigned char > &png)
int getPaletteValue (const unsigned char *data, size_t i, int bits)
void extractZlibInfo (std::vector< ZlibBlockInfo > &zlibinfo, const std::vector< unsigned char > &in)
Variables
static const unsigned long LENBASE [29]
static const unsigned long LENEXTRA [29]
static const unsigned long DISTBASE [30]
static const unsigned long DISTEXTRA [30]
static const unsigned long CLCL [19]
Function Documentation
extractZlibInfo()
void lodepng::extractZlibInfo (std::vector< ZlibBlockInfo > & zlibinfo, const std::vector< unsigned char > & in)
Definition at line 658 of file lodepng_util.cpp.
 {
   ExtractPNG decoder(&zlibinfo);
   decoder.decode(&in[0], in.size());
   if(decoder.error) std::cout << "extract error: " << decoder.error << std::endl;
 }
References lodepng::ExtractPNG::decode(), and lodepng::ExtractPNG::error.
getChunkInfo()
unsigned lodepng::getChunkInfo (std::vector< std::string > & names, std::vector< size_t > & sizes, const std::vector< unsigned char > & png)
Definition at line 40 of file lodepng_util.cpp.
 {
   // Listing chunks is based on the original file, not the decoded png info.
   const unsigned char *chunk, *begin, *end, *next;
   end = &png.back() + 1;
   begin = chunk = &png.front() + 8;
   while(chunk + 8 < end && chunk >= begin)
   {
     char type[5];
     lodepng_chunk_type(type, chunk);
     if(std::string(type).size() != 4) return 1;
     unsigned length = lodepng_chunk_length(chunk);
     if(chunk + length + 12 > end) return 1;
     names.push_back(type);
     sizes.push_back(length);
     next = lodepng_chunk_next_const(chunk);
     if (next <= chunk) return 1; // integer overflow
     chunk = next;
   }
   return 0;
 }
References lodepng_chunk_length(), lodepng_chunk_next_const(), and lodepng_chunk_type().
getChunks()
unsigned lodepng::getChunks (std::vector< std::string > names[3], std::vector< std::vector< unsigned char > > chunks[3], const std::vector< unsigned char > & png)
Definition at line 66 of file lodepng_util.cpp.
 {
   const unsigned char *chunk, *next, *begin, *end;
   end = &png.back() + 1;
   begin = chunk = &png.front() + 8;
   int location = 0;
   while(chunk + 8 < end && chunk >= begin)
   {
     char type[5];
     lodepng_chunk_type(type, chunk);
     std::string name(type);
     if(name.size() != 4) return 1;
     next = lodepng_chunk_next_const(chunk);
     if (next <= chunk) return 1; // integer overflow
     if(name == "IHDR")
     {
       location = 0;
     }
     else if(name == "PLTE")
     {
       location = 1;
     }
     else if(name == "IDAT")
     {
       location = 2;
     }
     else if(name != "IEND")
     {
       names[location].push_back(name);
       chunks[location].push_back(std::vector<unsigned char>(chunk, next));
     }
     chunk = next;
   }
   return 0;
 }
References lodepng_chunk_next_const(), and lodepng_chunk_type().
getFilterTypes()
unsigned lodepng::getFilterTypes (std::vector< unsigned char > & filterTypes, const std::vector< unsigned char > & png)
Definition at line 250 of file lodepng_util.cpp.
 {
   std::vector<std::vector<unsigned char> > passes;
   unsigned error = getFilterTypesInterlaced(passes, png);
   if(error) return error;
   if(passes.size() == 1)
   {
     filterTypes.swap(passes[0]);
   }
   else
   {
     lodepng::State state;
     unsigned w, h;
     lodepng_inspect(&w, &h, &state, &png[0], png.size());
     /*
     Interlaced. Simplify it: put pass 6 and 7 alternating in the one vector so
     that one filter per scanline of the uninterlaced image is given, with that
     filter corresponding the closest to what it would be for non-interlaced
     image.
     */
     for(size_t i = 0; i < h; i++)
     {
       filterTypes.push_back(i % 2 == 0 ? passes[5][i / 2] : passes[6][i / 2]);
     }
   }
   return 0; /* OK */
 }
References getFilterTypesInterlaced(), and lodepng_inspect().
getFilterTypesInterlaced()
unsigned lodepng::getFilterTypesInterlaced (std::vector< std::vector< unsigned char > > & filterTypes, const std::vector< unsigned char > & png)
Definition at line 161 of file lodepng_util.cpp.
 {
   //Get color type and interlace type
   lodepng::State state;
   unsigned w, h;
   unsigned error;
   error = lodepng_inspect(&w, &h, &state, &png[0], png.size());
   if(error) return 1;
   //Read literal data from all IDAT chunks
   const unsigned char *chunk, *begin, *end, *next;
   end = &png.back() + 1;
   begin = chunk = &png.front() + 8;
   std::vector<unsigned char> zdata;
   while(chunk + 8 < end && chunk >= begin)
   {
     char type[5];
     lodepng_chunk_type(type, chunk);
     if(std::string(type).size() != 4) return 1; //Probably not a PNG file
     if(std::string(type) == "IDAT")
     {
       const unsigned char* cdata = lodepng_chunk_data_const(chunk);
       unsigned clength = lodepng_chunk_length(chunk);
       if(chunk + clength + 12 > end || clength > png.size() || chunk + clength + 12 < begin) {
         // corrupt chunk length
         return 1;
       }
       for(unsigned i = 0; i < clength; i++)
       {
         zdata.push_back(cdata[i]);
       }
     }
     next = lodepng_chunk_next_const(chunk);
     if (next <= chunk) return 1; // integer overflow
     chunk = next;
   }
   //Decompress all IDAT data
   std::vector<unsigned char> data;
   error = lodepng::decompress(data, &zdata[0], zdata.size());
   if(error) return 1;
   if(state.info_png.interlace_method == 0)
   {
     filterTypes.resize(1);
     //A line is 1 filter byte + all pixels
     size_t linebytes = 1 + lodepng_get_raw_size(w, 1, &state.info_png.color);
     for(size_t i = 0; i < data.size(); i += linebytes)
     {
       filterTypes[0].push_back(data[i]);
     }
   }
   else
   {
     //Interlaced
     filterTypes.resize(7);
     static const unsigned ADAM7_IX[7] = { 0, 4, 0, 2, 0, 1, 0 }; /*x start values*/
     static const unsigned ADAM7_IY[7] = { 0, 0, 4, 0, 2, 0, 1 }; /*y start values*/
     static const unsigned ADAM7_DX[7] = { 8, 8, 4, 4, 2, 2, 1 }; /*x delta values*/
     static const unsigned ADAM7_DY[7] = { 8, 8, 8, 4, 4, 2, 2 }; /*y delta values*/
     size_t pos = 0;
     for(size_t j = 0; j < 7; j++)
     {
       unsigned w2 = (w - ADAM7_IX[j] + ADAM7_DX[j] - 1) / ADAM7_DX[j];
       unsigned h2 = (h - ADAM7_IY[j] + ADAM7_DY[j] - 1) / ADAM7_DY[j];
       if(ADAM7_IX[j] >= w) w2 = 0;
       if(ADAM7_IY[j] >= h) h2 = 0;
       size_t linebytes = 1 + lodepng_get_raw_size(w2, 1, &state.info_png.color);
       for(size_t i = 0; i < h2; i++)
       {
         filterTypes[j].push_back(data[pos]);
         pos += linebytes;
       }
     }
   }
   return 0; /* OK */
 }
References ADAM7_DX, ADAM7_DY, ADAM7_IX, ADAM7_IY, lodepng_chunk_data_const(), lodepng_chunk_length(), lodepng_chunk_next_const(), lodepng_chunk_type(), lodepng_get_raw_size(), and lodepng_inspect().
Referenced by getFilterTypes().
getPaletteValue()
int lodepng::getPaletteValue (const unsigned char * data, size_t i, int bits)
Definition at line 279 of file lodepng_util.cpp.
 {
   if(bits == 8) return data[i];
   else if(bits == 4) return (data[i / 2] >> ((i % 2) * 4)) & 15;
   else if(bits == 2) return (data[i / 4] >> ((i % 4) * 2)) & 3;
   else if(bits == 1) return (data[i / 8] >> (i % 8)) & 1;
   else return 0;
 }
getPNGHeaderInfo()
LodePNGInfo lodepng::getPNGHeaderInfo (const std::vector< unsigned char > & png)
Definition at line 32 of file lodepng_util.cpp.
 {
   unsigned w, h;
   lodepng::State state;
   lodepng_inspect(&w, &h, &state, &png[0], png.size());
   return state.info_png;
 }
References lodepng_inspect().
insertChunks()
unsigned lodepng::insertChunks (std::vector< unsigned char > & png, const std::vector< std::vector< unsigned char > > chunks[3])
Definition at line 110 of file lodepng_util.cpp.
 {
   const unsigned char *chunk, *next, *begin, *end;
   end = &png.back() + 1;
   begin = chunk = &png.front() + 8;
   long l0 = 0; //location 0: IHDR-l0-PLTE (or IHDR-l0-l1-IDAT)
   long l1 = 0; //location 1: PLTE-l1-IDAT (or IHDR-l0-l1-IDAT)
   long l2 = 0; //location 2: IDAT-l2-IEND
   while(chunk + 8 < end && chunk >= begin)
   {
     char type[5];
     lodepng_chunk_type(type, chunk);
     std::string name(type);
     if(name.size() != 4) return 1;
     next = lodepng_chunk_next_const(chunk);
     if (next <= chunk) return 1; // integer overflow
     if(name == "PLTE")
     {
       if(l0 == 0) l0 = chunk - begin + 8;
     }
     else if(name == "IDAT")
     {
       if(l0 == 0) l0 = chunk - begin + 8;
       if(l1 == 0) l1 = chunk - begin + 8;
     }
     else if(name == "IEND")
     {
       if(l2 == 0) l2 = chunk - begin + 8;
     }
     chunk = next;
   }
   std::vector<unsigned char> result;
   result.insert(result.end(), png.begin(), png.begin() + l0);
   for(size_t i = 0; i < chunks[0].size(); i++) result.insert(result.end(), chunks[0][i].begin(), chunks[0][i].end());
   result.insert(result.end(), png.begin() + l0, png.begin() + l1);
   for(size_t i = 0; i < chunks[1].size(); i++) result.insert(result.end(), chunks[1][i].begin(), chunks[1][i].end());
   result.insert(result.end(), png.begin() + l1, png.begin() + l2);
   for(size_t i = 0; i < chunks[2].size(); i++) result.insert(result.end(), chunks[2][i].begin(), chunks[2][i].end());
   result.insert(result.end(), png.begin() + l2, png.end());
   png = result;
   return 0;
 }
References lodepng_chunk_next_const(), and lodepng_chunk_type().
Variable Documentation
CLCL
const unsigned long lodepng::CLCL[19] static
Initial value:
=
    {16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15}
Definition at line 297 of file lodepng_util.cpp.
Referenced by lodepng::ExtractZlib::getTreeInflateDynamic().
DISTBASE
const unsigned long lodepng::DISTBASE[30] static
Initial value:
=
    {1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577}
Definition at line 293 of file lodepng_util.cpp.
Referenced by lodepng::ExtractZlib::inflateHuffmanBlock().
DISTEXTRA
const unsigned long lodepng::DISTEXTRA[30] static
Initial value:
=
    {0,0,0,0,1,1,2, 2, 3, 3, 4, 4, 5, 5,  6,  6,  7,  7,  8,  8,   9,   9,  10,  10,  11,  11,  12,   12,   13,   13}
Definition at line 295 of file lodepng_util.cpp.
Referenced by lodepng::ExtractZlib::inflateHuffmanBlock().
LENBASE
const unsigned long lodepng::LENBASE[29] static
Initial value:
=
    {3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258}
Definition at line 289 of file lodepng_util.cpp.
Referenced by lodepng::ExtractZlib::inflateHuffmanBlock().
LENEXTRA
const unsigned long lodepng::LENEXTRA[29] static
Initial value:
=
    {0,0,0,0,0,0,0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4,  4,  5,  5,  5,  5,  0}
Definition at line 291 of file lodepng_util.cpp.
Referenced by lodepng::ExtractZlib::inflateHuffmanBlock().