My Project: cExpPDController Class Reference
cExpPDController Class Reference
#include <ExpPDController.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cExpPDController ()
virtual ~cExpPDController ()
virtual void Init (cSimCharacter *character, const Eigen::MatrixXd &pd_params)
virtual void Reset ()
virtual void Clear ()
virtual void Update (double time_step)
virtual void UpdateControlForce (double time_step, Eigen::VectorXd &out_tau)
virtual int GetNumJoints () const
virtual int GetNumDof () const
virtual void GetTargetTheta (int joint_id, Eigen::VectorXd &out_theta) const
virtual void SetTargetTheta (int joint_id, const Eigen::VectorXd &theta)
virtual void GetTargetVel (int joint_id, Eigen::VectorXd &out_vel) const
virtual void SetTargetVel (int joint_id, const Eigen::VectorXd &vel)
virtual bool UseWorldCoord (int joint_id) const
virtual void SetUseWorldCoord (int joint_id, bool use)
virtual void SetKp (int joint_id, double kp)
virtual void SetKd (int joint_id, double kd)
virtual bool IsValidPDCtrl (int joint_id) const
virtual cPDController & GetPDCtrl (int joint_id)
virtual const cPDController & GetPDCtrl (int joint_id) const
Public Member Functions inherited from cController
virtual ~cController ()
virtual void Init (cSimCharacter *character)
virtual bool IsValid () const
virtual bool LoadParams (const std::string &param_file)
virtual int GetNumOptParams () const
virtual void BuildOptParams (Eigen::VectorXd &out_params) const
virtual void SetOptParams (const Eigen::VectorXd &params)
virtual void SetOptParams (const Eigen::VectorXd &params, Eigen::VectorXd &out_params) const
virtual void FetchOptParamScale (Eigen::VectorXd &out_scale) const
virtual void OutputOptParams (const std::string &file, const Eigen::VectorXd &params) const
virtual void OutputOptParams (FILE *f, const Eigen::VectorXd &params) const
virtual void SetActive (bool active)
virtual bool IsActive () const
virtual void SetMode (eMode mode)
virtual const cSimCharacter * GetChar () const
Protected Member Functions
virtual void CalcControlForces (double time_step, Eigen::VectorXd &out_tau)
virtual void ApplyControlForces (const Eigen::VectorXd &tau)
Protected Member Functions inherited from cController
cController ()
virtual bool ParseParams (const Json::Value &json)
Protected Attributes
tEigenArr< cPDController > mPDCtrls
Protected Attributes inherited from cController
cSimCharacter * mChar
eMode mMode
bool mValid
Additional Inherited Members
Public Types inherited from cController
enum eMode { eModeActive, eModeInactive, eModePassive, eModeMax }
Detailed Description
Definition at line 7 of file ExpPDController.h.
Constructor & Destructor Documentation
cExpPDController()
cExpPDController::cExpPDController ()
Definition at line 6 of file ExpPDController.cpp.
 {
 }
~cExpPDController()
cExpPDController::~cExpPDController () virtual
Definition at line 10 of file ExpPDController.cpp.
 {
 }
Member Function Documentation
ApplyControlForces()
void cExpPDController::ApplyControlForces (const Eigen::VectorXd & tau) protected virtual
Definition at line 155 of file ExpPDController.cpp.
 {
     mChar->ApplyControlForces(tau);
 }
References cSimCharacter::ApplyControlForces(), and cController::mChar.
Referenced by Update().
CalcControlForces()
void cExpPDController::CalcControlForces (double time_step, Eigen::VectorXd & out_tau) protected virtual
Reimplemented in cImpPDController.
Definition at line 143 of file ExpPDController.cpp.
 {
     for (int i = 0; i < static_cast<int>(mPDCtrls.size()); ++i)
     {
         cPDController& pd_ctrl = GetPDCtrl(i);
         if (pd_ctrl.IsValid())
         {
             pd_ctrl.UpdateControlForce(time_step, out_tau);
         }
     }
 }
References GetPDCtrl(), cController::IsValid(), mPDCtrls, and cPDController::UpdateControlForce().
Referenced by UpdateControlForce().
Clear()
void cExpPDController::Clear () virtual
Reimplemented from cController.
Reimplemented in cImpPDController.
Definition at line 45 of file ExpPDController.cpp.
 {
     cController::Clear();
     mPDCtrls.clear();
 }
References cController::Clear(), and mPDCtrls.
Referenced by cImpPDController::Clear().
GetNumDof()
int cExpPDController::GetNumDof () const virtual
Definition at line 72 of file ExpPDController.cpp.
 {
     return mChar->GetNumDof();
 }
References cCharacter::GetNumDof(), and cController::mChar.
Referenced by cImpPDController::BuildTargetPose(), cImpPDController::BuildTargetVel(), cImpPDController::InitGains(), and Update().
GetNumJoints()
int cExpPDController::GetNumJoints () const virtual
Definition at line 67 of file ExpPDController.cpp.
 {
     return mChar->GetNumJoints();
 }
References cCharacter::GetNumJoints(), and cController::mChar.
Referenced by cImpPDController::BuildTargetPose(), cImpPDController::BuildTargetVel(), cImpPDController::CalcControlForces(), GetPDCtrl(), cImpPDController::InitGains(), and cCtVelController::SetupPDControllers().
GetPDCtrl() [1/2]
cPDController & cExpPDController::GetPDCtrl (int joint_id) virtual
Definition at line 131 of file ExpPDController.cpp.
 {
     assert(joint_id >= 0 && joint_id < GetNumJoints());
     return mPDCtrls[joint_id];
 }
References GetNumJoints(), and mPDCtrls.
Referenced by cImpPDController::BuildTargetPose(), cImpPDController::BuildTargetVel(), CalcControlForces(), cImpPDController::CalcControlForces(), cCtPDController::GetJointType(), GetTargetTheta(), GetTargetVel(), cImpPDController::InitGains(), IsValidPDCtrl(), SetKd(), SetKp(), SetTargetTheta(), SetTargetVel(), SetUseWorldCoord(), and UseWorldCoord().
GetPDCtrl() [2/2]
const cPDController & cExpPDController::GetPDCtrl (int joint_id) const virtual
Definition at line 137 of file ExpPDController.cpp.
 {
     assert(joint_id >= 0 && joint_id < GetNumJoints());
     return mPDCtrls[joint_id];
 }
References GetNumJoints(), and mPDCtrls.
GetTargetTheta()
void cExpPDController::GetTargetTheta (int joint_id, Eigen::VectorXd & out_theta) const virtual
Definition at line 77 of file ExpPDController.cpp.
 {
     const cPDController& pd_ctrl = GetPDCtrl(joint_id);
     pd_ctrl.GetTargetTheta(out_theta);
 }
References GetPDCtrl(), and cPDController::GetTargetTheta().
GetTargetVel()
void cExpPDController::GetTargetVel (int joint_id, Eigen::VectorXd & out_vel) const virtual
Definition at line 89 of file ExpPDController.cpp.
 {
     const cPDController& pd_ctrl = GetPDCtrl(joint_id);
     pd_ctrl.GetTargetVel(out_vel);
 }
References GetPDCtrl(), and cPDController::GetTargetVel().
Init()
void cExpPDController::Init (cSimCharacter * character, const Eigen::MatrixXd & pd_params) virtual
Definition at line 14 of file ExpPDController.cpp.
 {
     cController::Init(character);
     int num_joints = mChar->GetNumJoints();
     mPDCtrls.resize(num_joints);
     assert(pd_params.rows() == num_joints);
     int root_id = mChar->GetRootID();
     for (int j = 0; j < num_joints; ++j)
     {
         cSimBodyJoint& joint = mChar->GetJoint(j);
         if (joint.IsValid() && j != root_id)
         {
             const cPDController::tParams& curr_params = pd_params.row(j);
             cPDController& ctrl = mPDCtrls[j];
             ctrl.Init(mChar, curr_params);
         }
     }
     mValid = true;
 }
References cSimCharacter::GetJoint(), cCharacter::GetNumJoints(), cCharacter::GetRootID(), cController::Init(), cPDController::Init(), cSimBodyJoint::IsValid(), cController::mChar, mPDCtrls, and cController::mValid.
Referenced by cImpPDController::Init().
IsValidPDCtrl()
bool cExpPDController::IsValidPDCtrl (int joint_id) const virtual
Definition at line 125 of file ExpPDController.cpp.
 {
     const cPDController& pd_ctrl = GetPDCtrl(joint_id);
     return pd_ctrl.IsValid();
 }
References GetPDCtrl(), and cController::IsValid().
Referenced by cCtVelController::ApplyAction(), cCtPDController::SetPDTargets(), and cCtVelController::SetupPDControllers().
Reset()
void cExpPDController::Reset () virtual
Reimplemented from cController.
Definition at line 36 of file ExpPDController.cpp.
 {
     cController::Reset();
     for (size_t i = 0; i < mPDCtrls.size(); ++i)
     {
         mPDCtrls[i].Reset();
     }
 }
References mPDCtrls, and cController::Reset().
Referenced by cCtPDController::Reset().
SetKd()
void cExpPDController::SetKd (int joint_id, double kd) virtual
Reimplemented in cImpPDController.
Definition at line 119 of file ExpPDController.cpp.
 {
     cPDController& pd_ctrl = GetPDCtrl(joint_id);
     pd_ctrl.SetKd(kd);
 }
References GetPDCtrl(), and cPDController::SetKd().
Referenced by cImpPDController::SetKd().
SetKp()
void cExpPDController::SetKp (int joint_id, double kp) virtual
Reimplemented in cImpPDController.
Definition at line 113 of file ExpPDController.cpp.
 {
     cPDController& pd_ctrl = GetPDCtrl(joint_id);
     pd_ctrl.SetKp(kp);
 }
References GetPDCtrl(), and cPDController::SetKp().
Referenced by cImpPDController::SetKp().
SetTargetTheta()
void cExpPDController::SetTargetTheta (int joint_id, const Eigen::VectorXd & theta) virtual
Definition at line 83 of file ExpPDController.cpp.
 {
     cPDController& pd_ctrl = GetPDCtrl(joint_id);
     pd_ctrl.SetTargetTheta(theta);
 }
References GetPDCtrl(), and cPDController::SetTargetTheta().
Referenced by cCtPDController::SetPDTargets().
SetTargetVel()
void cExpPDController::SetTargetVel (int joint_id, const Eigen::VectorXd & vel) virtual
Definition at line 95 of file ExpPDController.cpp.
 {
     cPDController& pd_ctrl = GetPDCtrl(joint_id);
     pd_ctrl.SetTargetVel(vel);
 }
References GetPDCtrl(), and cPDController::SetTargetVel().
Referenced by cCtVelController::ApplyAction().
SetUseWorldCoord()
void cExpPDController::SetUseWorldCoord (int joint_id, bool use) virtual
Definition at line 107 of file ExpPDController.cpp.
 {
     cPDController& pd_ctrl = GetPDCtrl(joint_id);
     pd_ctrl.SetUseWorldCoord(use);
 }
References GetPDCtrl(), and cPDController::SetUseWorldCoord().
Update()
void cExpPDController::Update (double time_step) virtual
Reimplemented from cController.
Definition at line 51 of file ExpPDController.cpp.
 {
     Eigen::VectorXd tau = Eigen::VectorXd::Zero(GetNumDof());
     UpdateControlForce(time_step, tau);
     ApplyControlForces(tau);
 }
References ApplyControlForces(), GetNumDof(), and UpdateControlForce().
UpdateControlForce()
void cExpPDController::UpdateControlForce (double time_step, Eigen::VectorXd & out_tau) virtual
Reimplemented in cImpPDController.
Definition at line 58 of file ExpPDController.cpp.
 {
     cController::Update(time_step);
     if (time_step > 0)
     {
         CalcControlForces(time_step, out_tau);
     }
 }
References CalcControlForces(), and cController::Update().
Referenced by Update().
UseWorldCoord()
bool cExpPDController::UseWorldCoord (int joint_id) const virtual
Definition at line 101 of file ExpPDController.cpp.
 {
     const cPDController& pd_ctrl = GetPDCtrl(joint_id);
     return pd_ctrl.UseWorldCoord();
 }
References GetPDCtrl(), and cPDController::UseWorldCoord().
Member Data Documentation
mPDCtrls
tEigenArr<cPDController> cExpPDController::mPDCtrls protected
Definition at line 38 of file ExpPDController.h.
Referenced by CalcControlForces(), Clear(), GetPDCtrl(), Init(), and Reset().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/ExpPDController.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/ExpPDController.cpp