My Project: cCtrlBuilder Class Reference
cCtrlBuilder Class Reference
#include <CtrlBuilder.h>
Classes
struct tCtrlParams
Public Types
enum eCharCtrl {
eCharCtrlNone, eCharCtrlCt, eCharCtrlCtPD, eCharCtrlCtVel,
eCharCtrlMax
}
Static Public Member Functions
static void ParseCharCtrl (const std::string &char_ctrl_str, eCharCtrl &out_char_ctrl)
static bool BuildController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
Static Protected Member Functions
static bool BuildCtController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildCtPDController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildCtVelController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildCtTargetController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildDogController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildRaptorController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildBiped3DStepController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildBiped3DSymStepController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildCtTarPoseController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildCtSymPDController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildCtHeadingController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildCtHeadingPDController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildCtSymHeadingPDController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildCtStrikePDController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildCtStrikeObjPDController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
static bool BuildCtCmdPDController (const tCtrlParams &params, std::shared_ptr< cCharController > &out_ctrl)
Detailed Description
Definition at line 11 of file CtrlBuilder.h.
Member Enumeration Documentation
eCharCtrl
enum cCtrlBuilder::eCharCtrl
Enumerator
eCharCtrlNone
eCharCtrlCt
eCharCtrlCtPD
eCharCtrlCtVel
eCharCtrlMax
Definition at line 15 of file CtrlBuilder.h.
     {
         eCharCtrlNone,
         eCharCtrlCt,
         eCharCtrlCtPD,
         eCharCtrlCtVel,
         eCharCtrlMax
     };
Member Function Documentation
BuildBiped3DStepController()
static bool cCtrlBuilder::BuildBiped3DStepController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
BuildBiped3DSymStepController()
static bool cCtrlBuilder::BuildBiped3DSymStepController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
BuildController()
bool cCtrlBuilder::BuildController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static
Definition at line 53 of file CtrlBuilder.cpp.
 {
     bool succ = true;
     switch (params.mCharCtrl)
     {
     case eCharCtrlNone:
         break;
     case eCharCtrlCt:
         succ = BuildCtController(params, out_ctrl);
         break;
     case eCharCtrlCtPD:
         succ = BuildCtPDController(params, out_ctrl);
         break;
     case eCharCtrlCtVel:
         succ = BuildCtVelController(params, out_ctrl);
         break;
     default:
         assert(false && "Failed Building Unsupported Controller\n"); // unsupported controller
         break;
     }
     return succ;
 }
References BuildCtController(), BuildCtPDController(), BuildCtVelController(), eCharCtrlCt, eCharCtrlCtPD, eCharCtrlCtVel, eCharCtrlNone, and cCtrlBuilder::tCtrlParams::mCharCtrl.
Referenced by cSceneSimChar::BuildController().
BuildCtCmdPDController()
static bool cCtrlBuilder::BuildCtCmdPDController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
BuildCtController()
bool cCtrlBuilder::BuildCtController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
Definition at line 78 of file CtrlBuilder.cpp.
 {
     bool succ = true;
     std::shared_ptr<cCtController> ctrl = std::shared_ptr<cCtController>(new cCtController());
     ctrl->Init(params.mChar.get(), params.mCtrlFile);
     out_ctrl = ctrl;
     return succ;
 }
References cCtrlBuilder::tCtrlParams::mChar, and cCtrlBuilder::tCtrlParams::mCtrlFile.
Referenced by BuildController().
BuildCtHeadingController()
static bool cCtrlBuilder::BuildCtHeadingController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
BuildCtHeadingPDController()
static bool cCtrlBuilder::BuildCtHeadingPDController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
BuildCtPDController()
bool cCtrlBuilder::BuildCtPDController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
Definition at line 88 of file CtrlBuilder.cpp.
 {
     bool succ = true;
     std::shared_ptr<cCtPDController> ctrl = std::shared_ptr<cCtPDController>(new cCtPDController());
     ctrl->SetGravity(params.mGravity);
     ctrl->Init(params.mChar.get(), params.mCtrlFile);
     out_ctrl = ctrl;
     return succ;
 }
References cCtrlBuilder::tCtrlParams::mChar, cCtrlBuilder::tCtrlParams::mCtrlFile, and cCtrlBuilder::tCtrlParams::mGravity.
Referenced by BuildController().
BuildCtStrikeObjPDController()
static bool cCtrlBuilder::BuildCtStrikeObjPDController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
BuildCtStrikePDController()
static bool cCtrlBuilder::BuildCtStrikePDController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
BuildCtSymHeadingPDController()
static bool cCtrlBuilder::BuildCtSymHeadingPDController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
BuildCtSymPDController()
static bool cCtrlBuilder::BuildCtSymPDController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
BuildCtTargetController()
static bool cCtrlBuilder::BuildCtTargetController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
BuildCtTarPoseController()
static bool cCtrlBuilder::BuildCtTarPoseController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
BuildCtVelController()
bool cCtrlBuilder::BuildCtVelController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
Definition at line 99 of file CtrlBuilder.cpp.
 {
     bool succ = true;
     std::shared_ptr<cCtVelController> ctrl = std::shared_ptr<cCtVelController>(new cCtVelController());
     ctrl->SetGravity(params.mGravity);
     ctrl->Init(params.mChar.get(), params.mCtrlFile);
     out_ctrl = ctrl;
     return succ;
 }
References cCtrlBuilder::tCtrlParams::mChar, cCtrlBuilder::tCtrlParams::mCtrlFile, and cCtrlBuilder::tCtrlParams::mGravity.
Referenced by BuildController().
BuildDogController()
static bool cCtrlBuilder::BuildDogController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
BuildRaptorController()
static bool cCtrlBuilder::BuildRaptorController (const tCtrlParams & params, std::shared_ptr< cCharController > & out_ctrl) static protected
ParseCharCtrl()
void cCtrlBuilder::ParseCharCtrl (const std::string & char_ctrl_str, eCharCtrl & out_char_ctrl) static
Definition at line 25 of file CtrlBuilder.cpp.
 {
     bool found = false;
     if (char_ctrl_str == "" || char_ctrl_str == "none")
     {
         out_char_ctrl = eCharCtrlNone;
         found = true;
     }
     else
     {
         for (int i = 0; i < eCharCtrlMax; ++i)
         {
             const std::string& name = gCharCtrlName[i];
             if (char_ctrl_str == name)
             {
                 out_char_ctrl = static_cast<eCharCtrl>(i);
                 found = true;
                 break;
             }
         }
     }
     if (!found)
     {
         assert(false && "Unsupported character controller\n"); // unsupported character controller
     }
 }
References eCharCtrlMax, eCharCtrlNone, and gCharCtrlName.
Referenced by cSceneSimChar::ParseCharCtrlParams().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/CtrlBuilder.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/CtrlBuilder.cpp