My Project: cContactManager Class Reference
cContactManager Class Reference
#include <ContactManager.h>
Classes
struct tContactEntry
struct tContactHandle
struct tContactPt
Public Member Functions
cContactManager (cWorld &world)
virtual ~cContactManager ()
virtual void Init ()
virtual void Reset ()
virtual void Clear ()
virtual void Update ()
virtual tContactHandle RegisterContact (int contact_flags, int filter_flags)
virtual void UpdateContact (const cContactManager::tContactHandle &handle)
virtual int GetNumEntries () const
virtual bool IsInContact (const tContactHandle &handle) const
virtual const tEigenArr< tContactPt > & GetContactPts (const tContactHandle &handle) const
virtual const tEigenArr< tContactPt > & GetContactPts (int handle_id) const
Static Public Attributes
const static int gInvalidID = -1
const static short gFlagAll = -1
const static short gFlagNone = 0
const static short gFlagRayTest = 1
Protected Member Functions
virtual int RegisterNewID ()
virtual void ClearContacts ()
virtual bool IsValidContact (const tContactHandle &h0, const tContactHandle &h1) const
Protected Attributes
cWorld & mWorld
tEigenArr< tContactEntry > mContactEntries
Detailed Description
Definition at line 8 of file ContactManager.h.
Constructor & Destructor Documentation
cContactManager()
cContactManager::cContactManager (cWorld & world)
Definition at line 32 of file ContactManager.cpp.
     : mWorld(world)
 {
 }
~cContactManager()
cContactManager::~cContactManager () virtual
Definition at line 38 of file ContactManager.cpp.
 {
 }
Member Function Documentation
Clear()
void cContactManager::Clear () virtual
Definition at line 57 of file ContactManager.cpp.
 {
     mContactEntries.clear();
 }
References mContactEntries.
Referenced by Init().
ClearContacts()
void cContactManager::ClearContacts () protected virtual
Definition at line 176 of file ContactManager.cpp.
 {
     int num_entries = GetNumEntries();
     for (int i = 0; i < num_entries; ++i)
     {
         tContactEntry& curr_entry = mContactEntries[i];
         curr_entry.mContactPts.clear();
     }
 }
References GetNumEntries(), mContactEntries, and cContactManager::tContactEntry::mContactPts.
Referenced by Update().
GetContactPts() [1/2]
const tEigenArr< cContactManager::tContactPt > & cContactManager::GetContactPts (const tContactHandle & handle) const virtual
Definition at line 157 of file ContactManager.cpp.
 {
     return GetContactPts(handle.mID);
 }
References cContactManager::tContactHandle::mID.
Referenced by cWorld::GetContactPts().
GetContactPts() [2/2]
const tEigenArr< cContactManager::tContactPt > & cContactManager::GetContactPts (int handle_id) const virtual
Definition at line 162 of file ContactManager.cpp.
 {
     assert(handle_id != gInvalidID);
     return mContactEntries[handle_id].mContactPts;
 }
References gInvalidID, and mContactEntries.
GetNumEntries()
int cContactManager::GetNumEntries () const virtual
Definition at line 143 of file ContactManager.cpp.
 {
     return static_cast<int>(mContactEntries.size());
 }
References mContactEntries.
Referenced by ClearContacts(), and Reset().
Init()
void cContactManager::Init () virtual
Definition at line 43 of file ContactManager.cpp.
 {
     Clear();
 }
References Clear().
Referenced by cWorld::Init().
IsInContact()
bool cContactManager::IsInContact (const tContactHandle & handle) const virtual
Definition at line 148 of file ContactManager.cpp.
 {
     if (handle.IsValid())
     {
         return mContactEntries[handle.mID].mContactPts.size() > 0;
     }
     return false;
 }
References cContactManager::tContactHandle::IsValid(), mContactEntries, and cContactManager::tContactHandle::mID.
Referenced by cWorld::IsInContact().
IsValidContact()
bool cContactManager::IsValidContact (const tContactHandle & h0, const tContactHandle & h1) const protected virtual
Definition at line 186 of file ContactManager.cpp.
 {
     bool valid_h0 = ((h0.mFilterFlags & h1.mFlags) != 0);
     bool valid_h1 = ((h1.mFilterFlags & h0.mFlags) != 0);
     bool valid_contact = valid_h0 && valid_h1;
     return valid_contact;
 }
References cContactManager::tContactHandle::mFilterFlags, and cContactManager::tContactHandle::mFlags.
Referenced by Update().
RegisterContact()
cContactManager::tContactHandle cContactManager::RegisterContact (int contact_flags, int filter_flags) virtual
Definition at line 120 of file ContactManager.cpp.
 {
     tContactHandle handle;
     handle.mFlags = contact_flags;
     handle.mFilterFlags = filter_flags;
     handle.mID = RegisterNewID();
     tContactEntry& entry = mContactEntries[handle.mID];
     entry.mFlags = contact_flags;
     entry.mFilterFlags = filter_flags;
     assert(handle.IsValid());
     return handle;
 }
References cContactManager::tContactHandle::IsValid(), mContactEntries, cContactManager::tContactHandle::mFilterFlags, cContactManager::tContactEntry::mFilterFlags, cContactManager::tContactHandle::mFlags, cContactManager::tContactEntry::mFlags, cContactManager::tContactHandle::mID, and RegisterNewID().
Referenced by cWorld::RegisterContact().
RegisterNewID()
int cContactManager::RegisterNewID () protected virtual
Definition at line 168 of file ContactManager.cpp.
 {
     int id = gInvalidID;
     id = static_cast<int>(mContactEntries.size());
     mContactEntries.resize(id + 1);
     return id;
 }
References gInvalidID, and mContactEntries.
Referenced by RegisterContact().
Reset()
void cContactManager::Reset () virtual
Definition at line 48 of file ContactManager.cpp.
 {
     for (int i = 0; i < GetNumEntries(); ++i)
     {
         tContactEntry& entry = mContactEntries[i];
         entry.mContactPts.clear();
     }
 }
References GetNumEntries(), mContactEntries, and cContactManager::tContactEntry::mContactPts.
Referenced by cWorld::Reset().
Update()
void cContactManager::Update () virtual
Definition at line 62 of file ContactManager.cpp.
 {
     ClearContacts();
     double world_scale = mWorld.GetScale();
     double timestep = mWorld.GetTimeStep();
     std::unique_ptr<btMultiBodyDynamicsWorld>& bt_world = mWorld.GetInternalWorld();
     int num_manifolds = bt_world->getDispatcher()->getNumManifolds();
     for (int i = 0; i < num_manifolds; ++i)
     {
         btPersistentManifold* mani = bt_world->getDispatcher()->getManifoldByIndexInternal(i);
         const btCollisionObject* obj0 = static_cast<const btCollisionObject*>(mani->getBody0());
         const btCollisionObject* obj1 = static_cast<const btCollisionObject*>(mani->getBody1());
         int num_contacts = mani->getNumContacts();
         for (int j = 0; j < num_contacts; ++j)
         {
             btManifoldPoint& pt = mani->getContactPoint(j);
             btScalar dist_tol = static_cast<btScalar>(0.001 * world_scale);
             if (pt.getDistance() <= dist_tol)
             {
                 const cSimObj* sim_obj0 = static_cast<const cSimObj*>(obj0->getUserPointer());
                 const cSimObj* sim_obj1 = static_cast<const cSimObj*>(obj1->getUserPointer());
                 const tContactHandle& h0 = sim_obj0->GetContactHandle();
                 const tContactHandle& h1 = sim_obj1->GetContactHandle();
                 bool valid_contact = IsValidContact(h0, h1);
                 if (valid_contact)
                 {
                     double impulse = pt.getAppliedImpulse() / world_scale;
                     tVector normal = tVector(pt.m_normalWorldOnB[0], pt.m_normalWorldOnB[1], pt.m_normalWorldOnB[2], 0);
                     tVector force0 = (impulse / timestep) * normal;
                     if (h0.IsValid())
                     {
                         tContactPt pt0;
                         const btVector3& contact_pt = pt.getPositionWorldOnA();
                         pt0.mPos = tVector(contact_pt[0], contact_pt[1], contact_pt[2], 0) / world_scale;
                         pt0.mForce = force0;
                         mContactEntries[h0.mID].mContactPts.push_back(pt0);
                     }
                     if (h1.IsValid())
                     {
                         tContactPt pt1;
                         const btVector3& contact_pt = pt.getPositionWorldOnB();
                         pt1.mPos = tVector(contact_pt[0], contact_pt[1], contact_pt[2], 0) / world_scale;
                         pt1.mForce = -force0;
                         mContactEntries[h1.mID].mContactPts.push_back(pt1);
                     }
                 }
             }
         }
     }
 }
References ClearContacts(), cSimObj::GetContactHandle(), cWorld::GetInternalWorld(), cWorld::GetScale(), cWorld::GetTimeStep(), cContactManager::tContactHandle::IsValid(), IsValidContact(), mContactEntries, cContactManager::tContactPt::mForce, cContactManager::tContactHandle::mID, cContactManager::tContactPt::mPos, and mWorld.
Referenced by cWorld::Update().
UpdateContact()
void cContactManager::UpdateContact (const cContactManager::tContactHandle & handle) virtual
Definition at line 135 of file ContactManager.cpp.
 {
     assert(handle.IsValid());
     tContactEntry& entry = mContactEntries[handle.mID];
     entry.mFlags = handle.mFlags;
     entry.mFilterFlags = handle.mFilterFlags;
 }
References cContactManager::tContactHandle::IsValid(), mContactEntries, cContactManager::tContactHandle::mFilterFlags, cContactManager::tContactHandle::mFlags, and cContactManager::tContactHandle::mID.
Referenced by cWorld::UpdateContact().
Member Data Documentation
gFlagAll
const static short cContactManager::gFlagAll = -1 static
Definition at line 12 of file ContactManager.h.
Referenced by cSimObj::cSimObj(), cSimCharacter::GetPartColMask(), cSimObj::RegisterContact(), cContactManager::tContactEntry::tContactEntry(), and cContactManager::tContactHandle::tContactHandle().
gFlagNone
const static short cContactManager::gFlagNone = 0 static
Definition at line 13 of file ContactManager.h.
Referenced by cSimCharacter::GetPartColMask(), and cSceneSimChar::SpawnProjectile().
gFlagRayTest
const static short cContactManager::gFlagRayTest = 1 static
Definition at line 14 of file ContactManager.h.
Referenced by cWorld::AddCollisionObject(), and cWorld::AddRigidBody().
gInvalidID
const int cContactManager::gInvalidID = -1 static
Definition at line 11 of file ContactManager.h.
Referenced by GetContactPts(), cContactManager::tContactHandle::IsValid(), RegisterNewID(), and cContactManager::tContactHandle::tContactHandle().
mContactEntries
tEigenArr<tContactEntry> cContactManager::mContactEntries protected
Definition at line 62 of file ContactManager.h.
Referenced by Clear(), ClearContacts(), GetContactPts(), GetNumEntries(), IsInContact(), RegisterContact(), RegisterNewID(), Reset(), Update(), and UpdateContact().
mWorld
cWorld& cContactManager::mWorld protected
Definition at line 61 of file ContactManager.h.
Referenced by Update().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/ContactManager.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/ContactManager.cpp