My Project: cDrawUtil Class Reference
cDrawUtil Class Reference
#include <DrawUtil.h>
Public Types
enum eDrawMode { eDrawSolid, eDrawWire, eDrawWireSimple, eDrawMax }
Static Public Member Functions
static void EnableDraw (bool enable)
static bool EnableDraw ()
static void InitOffscreenDrawContext ()
static bool CheckDrawContextInit ()
static void InitDrawUtil ()
static void DrawRect (const tVector &pos, const tVector &size, eDrawMode draw_mode=eDrawSolid)
static void DrawBox (const tVector &pos, const tVector &size, eDrawMode draw_mode=eDrawSolid)
static void DrawBox (const tVector &pos, const tVector &size, const tVector &tex_coord_min, const tVector &tex_coord_max, eDrawMode draw_mode=eDrawSolid)
static void DrawTriangle (const tVector &pos, double side_len, eDrawMode draw_mode=eDrawSolid)
static void DrawQuad (const tVector &a, const tVector &b, const tVector &c, const tVector &d, eDrawMode draw_mode=eDrawSolid)
static void DrawQuad (const tVector &a, const tVector &b, const tVector &c, const tVector &d, const tVector &coord_a, const tVector &coord_b, const tVector &coord_c, const tVector &coord_d, eDrawMode draw_mode=eDrawSolid)
static void DrawDisk (const tVector &pos, double r, eDrawMode draw_mode=eDrawSolid)
static void DrawDisk (const tVector &pos, const tVector &r, eDrawMode draw_mode=eDrawSolid)
static void DrawDisk (double r, eDrawMode draw_mode=eDrawSolid)
static void DrawDisk (const tVector &r, eDrawMode draw_mode=eDrawSolid)
static void DrawPoint (const tVector &pt)
static void DrawLine (const tVector &a, const tVector &b)
static void DrawLineStrip (const tVectorArr &pts)
static void DrawStrip (const tVector &a, const tVector &b, double width, eDrawMode draw_mode=eDrawSolid)
static void DrawCross (const tVector &pos, double size)
static void DrawPlane (const tVector &coeffs, double size, eDrawMode draw_mode=eDrawSolid)
static void DrawSphere (double r, eDrawMode draw_mode=eDrawSolid)
static void DrawHemisphere (double r, eDrawMode draw_mode=eDrawSolid)
static void DrawCylinder (double r, double h, eDrawMode draw_mode=eDrawSolid)
static void DrawCone (double r, double h, eDrawMode draw_mode=eDrawSolid)
static void DrawTube (double r, double h, eDrawMode draw_mode=eDrawSolid)
static void DrawCapsule (double r, double h, eDrawMode draw_mode=eDrawSolid)
static void DrawArrow2D (const tVector &start, const tVector &end, double head_size)
static void DrawArrow3D (const tVector &start, const tVector &end, double head_size)
static void DrawGrid2D (const tVector &origin, const tVector &size, double spacing, double line_width)
static void DrawRuler2D (const tVector &origin, const tVector &size, const tVector &col, double line_width, double marker_spacing, double marker_h, double marker_line_width)
static void DrawSemiCircle (const tVector &pos, double r, int slices, double min_theta, double max_theta, eDrawMode draw_mode=eDrawSolid)
static void DrawCalibMarker (const tVector &pos, double r, int slices, const tVector &col0, const tVector &col1, eDrawMode draw_mode=eDrawSolid)
static void DrawTexQuad (const cTextureDesc &tex, const tVector &pos, const tVector &size)
static void CopyTexture (const cTextureDesc &src_tex, const cTextureDesc &dst_tex)
static void CopyTexture (const cTextureDesc &src_tex, const cTextureDesc &dst_tex, const tVector &dst_min_coord, const tVector &dst_max_coord)
static void CopyTexture (const cTextureDesc &src_tex)
static void CopyTexture (const cTextureDesc &src_tex, const tVector &dst_min_coord, const tVector &dst_max_coord)
static void ClearColor (const tVector &col)
static void ClearDepth (double depth=1)
static void Translate (const tVector &trans)
static void Scale (const tVector &scale)
static void Rotate (const tVector &euler)
static void Rotate (double theta, const tVector &axis)
static void Rotate (const tQuaternion &q)
static void SetColor (const tVector &col)
static void SetLineWidth (double w)
static void SetPointSize (double pt_size)
static void MultMatrixView (const tMatrix &mat)
static void MultMatrixProj (const tMatrix &mat)
static void LoadMatrixView (const tMatrix &mat)
static void LoadMatrixProj (const tMatrix &mat)
static void LoadIdentityView ()
static void LoadIdentityProj ()
static void PushMatrixView ()
static void PushMatrixProj ()
static void PopMatrixView ()
static void PopMatrixProj ()
static void BindDefaultProg ()
static void UnbindDefaultProg ()
static void BindCopyMeshProg ()
static void UnbindCopyMeshProg ()
static void LoadShaderUniforms ()
static void Finish ()
static void BuildMeshes ()
Static Protected Member Functions
static void BuildShaders ()
static void DrawBoxSolid (const tVector &pos, const tVector &size, const tVector &tex_coord_min, const tVector &tex_coord_max)
static void DrawBoxWire (const tVector &pos, const tVector &size)
static void DrawCylinderSolidWire (double r, double h, eDrawMode draw_mode=eDrawSolid)
static void DrawCylinderWireSimple (double r, double h)
static void DrawTubeSolidWire (double r, double h, eDrawMode draw_mode=eDrawSolid)
static void DrawConeSolidWire (double r, double h, eDrawMode draw_mode=eDrawSolid)
static void DrawConeWireSimple (double r, double h)
Static Protected Attributes
static bool gEnableDraw = true
static tVector gColor = tVector::Ones()
static cShader gDefaultProg = cShader()
static cShader gCopyProg = cShader()
static cShader gCopyMeshProg = cShader()
static cMatrixStack gMatStackView = cMatrixStack(gMatStackSize)
static cMatrixStack gMatStackProj = cMatrixStack(gMatStackSize)
static std::unique_ptr< cDrawMesh > gPointMesh = nullptr
static std::unique_ptr< cDrawMesh > gLineMesh = nullptr
static std::unique_ptr< cDrawMesh > gQuadMesh = nullptr
static std::unique_ptr< cDrawMesh > gBoxSolidMesh = nullptr
static std::unique_ptr< cDrawMesh > gBoxWireMesh = nullptr
static std::unique_ptr< cDrawMesh > gSphereMesh = nullptr
static std::unique_ptr< cDrawMesh > gSphereWireSimpleMesh = nullptr
static std::unique_ptr< cDrawMesh > gDiskMesh = nullptr
static std::unique_ptr< cDrawMesh > gTriangleMesh = nullptr
static std::unique_ptr< cDrawMesh > gCylinderMesh = nullptr
static std::unique_ptr< cDrawMesh > gCylinderWireSimpleMesh = nullptr
static std::unique_ptr< cDrawMesh > gConeMesh = nullptr
static std::unique_ptr< cDrawMesh > gConeWireSimpleMesh = nullptr
Detailed Description
Definition at line 11 of file DrawUtil.h.
Member Enumeration Documentation
eDrawMode
enum cDrawUtil::eDrawMode
Enumerator
eDrawSolid
eDrawWire
eDrawWireSimple
eDrawMax
Definition at line 14 of file DrawUtil.h.
     {
         eDrawSolid,
         eDrawWire,
         eDrawWireSimple,
         eDrawMax
     };
Member Function Documentation
BindCopyMeshProg()
void cDrawUtil::BindCopyMeshProg () static
Definition at line 840 of file DrawUtil.cpp.
 {
     gCopyMeshProg.Bind();
 }
References cShader::Bind(), and gCopyMeshProg.
BindDefaultProg()
void cDrawUtil::BindDefaultProg () static
Definition at line 830 of file DrawUtil.cpp.
 {
     gDefaultProg.Bind();
 }
References cShader::Bind(), and gDefaultProg.
Referenced by InitDrawUtil().
BuildMeshes()
void cDrawUtil::BuildMeshes () static
Definition at line 879 of file DrawUtil.cpp.
 {
     cMeshUtil::BuildPointMesh(gPointMesh);
     cMeshUtil::BuildLineMesh(gLineMesh);
     cMeshUtil::BuildQuadMesh(gQuadMesh);
     cMeshUtil::BuildBoxSolidMesh(gBoxSolidMesh);
     cMeshUtil::BuildBoxWireMesh(gBoxWireMesh);
     cMeshUtil::BuildSphereMesh(gNumStacks, gNumSlice, gSphereMesh);
     cMeshUtil::BuildSphereWireSimpleMesh(gNumStacks, gNumSlice, gSphereWireSimpleMesh);
     cMeshUtil::BuildDiskMesh(gNumSlice, gDiskMesh);
     cMeshUtil::BuildTriangleMesh(gTriangleMesh);
     cMeshUtil::BuildCylinder(gNumSlice, gCylinderMesh);
     cMeshUtil::BuildCylinderWireSimple(gNumSlice, gCylinderWireSimpleMesh);
     cMeshUtil::BuildCone(gNumSlice, gConeMesh);
     cMeshUtil::BuildConeWireSimple(gNumSlice, gConeWireSimpleMesh);
 }
References cMeshUtil::BuildBoxSolidMesh(), cMeshUtil::BuildBoxWireMesh(), cMeshUtil::BuildCone(), cMeshUtil::BuildConeWireSimple(), cMeshUtil::BuildCylinder(), cMeshUtil::BuildCylinderWireSimple(), cMeshUtil::BuildDiskMesh(), cMeshUtil::BuildLineMesh(), cMeshUtil::BuildPointMesh(), cMeshUtil::BuildQuadMesh(), cMeshUtil::BuildSphereMesh(), cMeshUtil::BuildSphereWireSimpleMesh(), cMeshUtil::BuildTriangleMesh(), gBoxSolidMesh, gBoxWireMesh, gConeMesh, gConeWireSimpleMesh, gCylinderMesh, gCylinderWireSimpleMesh, gDiskMesh, gLineMesh, gNumSlice, gNumStacks, gPointMesh, gQuadMesh, gSphereMesh, gSphereWireSimpleMesh, and gTriangleMesh.
Referenced by InitDrawUtil().
BuildShaders()
void cDrawUtil::BuildShaders () static protected
Definition at line 942 of file DrawUtil.cpp.
 {
     {
         gDefaultProg.BuildShader("data/shaders/Mesh_VS.glsl", "data/shaders/VertColor_PS.glsl");
     }
     {
         gCopyProg.BuildShader("data/shaders/FullScreenQuad_VS.glsl", "data/shaders/DownSample_PS.glsl");
     }
     {
         gCopyMeshProg.BuildShader("data/shaders/Mesh_VS.glsl", "data/shaders/DownSample_PS.glsl");
     }
 }
References cShader::BuildShader(), gCopyMeshProg, gCopyProg, and gDefaultProg.
Referenced by InitDrawUtil().
CheckDrawContextInit()
bool cDrawUtil::CheckDrawContextInit () static
Definition at line 52 of file DrawUtil.cpp.
 {
     int state = glutGet(GLUT_INIT_STATE);
     return state == 1;
 }
ClearColor()
void cDrawUtil::ClearColor (const tVector & col) static
Definition at line 766 of file DrawUtil.cpp.
 {
     glClearColor(static_cast<float>(col[0]), static_cast<float>(col[1]),
         static_cast<float>(col[2]), static_cast<float>(col[3]));
     glClear(GL_COLOR_BUFFER_BIT);
 }
Referenced by cDrawScene::ClearFrame(), and cDrawScene::DoShadowPass().
ClearDepth()
void cDrawUtil::ClearDepth (double depth = 1) static
Definition at line 773 of file DrawUtil.cpp.
 {
     glClearDepth(depth);
     glClear(GL_DEPTH_BUFFER_BIT);
 }
Referenced by cDrawScene::ClearFrame(), and cDrawScene::DoShadowPass().
CopyTexture() [1/4]
void cDrawUtil::CopyTexture (const cTextureDesc & src_tex) static
Definition at line 722 of file DrawUtil.cpp.
 {
     CopyTexture(src_tex, tVector(-1, -1, 0, 0), tVector(1, 1, 0, 0));
 }
References CopyTexture().
CopyTexture() [2/4]
void cDrawUtil::CopyTexture (const cTextureDesc & src_tex, const cTextureDesc & dst_tex) static
Definition at line 709 of file DrawUtil.cpp.
 {
     CopyTexture(src_tex, tVector(-1, -1, 0, 0), tVector(1, 1, 0, 0));
 }
Referenced by cDeepMimicCore::CopyFrame(), and CopyTexture().
CopyTexture() [3/4]
void cDrawUtil::CopyTexture (const cTextureDesc & src_tex, const cTextureDesc & dst_tex, const tVector & dst_min_coord, const tVector & dst_max_coord) static
Definition at line 714 of file DrawUtil.cpp.
 {
     dst_tex.BindBuffer();
     CopyTexture(src_tex, dst_min_coord, dst_max_coord);
     dst_tex.UnbindBuffer();
 }
References cTextureDesc::BindBuffer(), CopyTexture(), and cTextureDesc::UnbindBuffer().
CopyTexture() [4/4]
void cDrawUtil::CopyTexture (const cTextureDesc & src_tex, const tVector & dst_min_coord, const tVector & dst_max_coord) static
Definition at line 727 of file DrawUtil.cpp.
 {
     cDrawUtil::PushMatrixProj();
     cDrawUtil::LoadIdentityProj();
     cDrawUtil::PushMatrixView();
     cDrawUtil::LoadIdentityView();
     GLint depth_test_param;
     glGetIntegerv(GL_DEPTH_TEST, &depth_test_param);
     glDisable(GL_DEPTH_TEST);
     GLint blend_param;
     glGetIntegerv(GL_BLEND, &blend_param);
     glDisable(GL_BLEND);
     SetColor(tVector::Ones());
     gCopyProg.Bind();
     tVector quad_pos = 0.5 * (dst_max_coord + dst_min_coord);
     tVector quad_size = dst_max_coord - dst_min_coord;
     DrawTexQuad(src_tex, quad_pos, quad_size);
     gCopyProg.Unbind();
     if (depth_test_param == 1)
     {
         glEnable(GL_DEPTH_TEST);
     }
     if (blend_param == 1)
     {
         glEnable(GL_BLEND);
     }
     cDrawUtil::PopMatrixView();
     cDrawUtil::PopMatrixProj();
 }
References cShader::Bind(), DrawTexQuad(), gCopyProg, LoadIdentityProj(), LoadIdentityView(), PopMatrixProj(), PopMatrixView(), PushMatrixProj(), PushMatrixView(), SetColor(), and cShader::Unbind().
DrawArrow2D()
void cDrawUtil::DrawArrow2D (const tVector & start, const tVector & end, double head_size) static
Definition at line 522 of file DrawUtil.cpp.
 {
     GLboolean prev_enable;
     glGetBooleanv(GL_CULL_FACE, &prev_enable);
     glDisable(GL_CULL_FACE);
     tVector dir = tVector(0, 1, 0, 0);
     double dir_len = 0;
     if (start != end)
     {
         dir = end - start;
         dir_len = dir.norm();
         dir /= dir_len;
     }
     dir[3] = 0;
     tVector axis = tVector(0, 0, 1, 0);
     tVector tangent = axis.cross3(dir);
     tangent.normalize();
     const double width = head_size * 0.1854;
     tVector body_end = end - dir * head_size;
     tVector a = start - width * tangent;
     tVector b = body_end - width * tangent;
     tVector c = body_end + width * tangent;
     tVector d = start + width * tangent;
     DrawQuad(a, b, c, d);
     tVector e0 = body_end - tangent * head_size * 0.5f;
     tVector e1 = body_end + tangent * head_size * 0.5f;
     DrawQuad(end, e1, e0, end);
     if (prev_enable)
     {
         glEnable(GL_CULL_FACE);
     }
 }
References DrawQuad().
Referenced by cDrawSimCharacter::DrawCoM(), and cDrawCharacter::DrawHeading().
DrawArrow3D()
void cDrawUtil::DrawArrow3D (const tVector & start, const tVector & end, double head_size) static
Definition at line 561 of file DrawUtil.cpp.
 {
     tVector dir = tVector(0, 1, 0, 0);
     double dir_len = 0;
     if (start != end)
     {
         dir = end - start;
         dir_len = dir.norm();
         dir /= dir_len;
     }
     tQuaternion rot = cMathUtil::VecDiffQuat(tVector(0, 1, 0, 0), dir);
     tMatrix rot_mat = cMathUtil::RotateMat(rot);
     double body_len = dir_len - head_size;
     double body_radius = head_size * 0.1854;
     double head_len = head_size;
     double head_radius = 0.5 * head_size;
     cDrawUtil::PushMatrixView();
     cDrawUtil::Translate(start);
     cDrawUtil::MultMatrixView(rot_mat);
     cDrawUtil::Translate(tVector(0, body_len, 0, 0));
     cDrawUtil::DrawCone(head_radius, head_len, cDrawUtil::eDrawSolid);
     cDrawUtil::Translate(tVector(0, -0.5 * body_len, 0, 0));
     cDrawUtil::DrawCylinder(body_radius, body_len, cDrawUtil::eDrawSolid);
     cDrawUtil::PopMatrixView();
 }
References DrawCone(), DrawCylinder(), eDrawSolid, MultMatrixView(), PopMatrixView(), PushMatrixView(), cMathUtil::RotateMat(), Translate(), and cMathUtil::VecDiffQuat().
Referenced by cDrawPerturb::DrawForce().
DrawBox() [1/2]
void cDrawUtil::DrawBox (const tVector & pos, const tVector & size, const tVector & tex_coord_min, const tVector & tex_coord_max, eDrawMode draw_mode = eDrawSolid) static
Definition at line 96 of file DrawUtil.cpp.
 {
     if (draw_mode == eDrawWire || draw_mode == eDrawWireSimple)
     {
         DrawBoxWire(pos, size);
     }
     else if (draw_mode == eDrawSolid)
     {
         DrawBoxSolid(pos, size, tex_coord_min, tex_coord_max);
     }
     else
     {
         assert(false); // unsupported draw mode
     }
 }
References DrawBoxSolid(), DrawBoxWire(), eDrawSolid, eDrawWire, and eDrawWireSimple.
DrawBox() [2/2]
void cDrawUtil::DrawBox (const tVector & pos, const tVector & size, eDrawMode draw_mode = eDrawSolid) static
Definition at line 91 of file DrawUtil.cpp.
 {
     DrawBox(pos, size, tVector::Zero(), tVector::Ones(), draw_mode);
 }
Referenced by cDrawObj::DrawBox(), cDrawCharacter::DrawShapeBox(), and cDrawKinTree::DrawTree().
DrawBoxSolid()
void cDrawUtil::DrawBoxSolid (const tVector & pos, const tVector & size, const tVector & tex_coord_min, const tVector & tex_coord_max) static protected
Definition at line 112 of file DrawUtil.cpp.
 {
     const int num_faces = 6;
     const int coord_len = num_faces * 6 * cMeshUtil::gCoordDim;
     const float coord_data[coord_len] = {
         static_cast<float>(tex_coord_min[0]), static_cast<float>(tex_coord_min[2]), // top
         static_cast<float>(tex_coord_max[0]), static_cast<float>(tex_coord_min[2]),
         static_cast<float>(tex_coord_max[0]), static_cast<float>(tex_coord_max[2]),
         static_cast<float>(tex_coord_max[0]), static_cast<float>(tex_coord_max[2]),
         static_cast<float>(tex_coord_min[0]), static_cast<float>(tex_coord_max[2]),
         static_cast<float>(tex_coord_min[0]), static_cast<float>(tex_coord_min[2]),
         static_cast<float>(tex_coord_max[0]), static_cast<float>(tex_coord_min[2]), // bottom
         static_cast<float>(tex_coord_max[0]), static_cast<float>(tex_coord_max[2]),
         static_cast<float>(tex_coord_min[0]), static_cast<float>(tex_coord_max[2]),
         static_cast<float>(tex_coord_min[0]), static_cast<float>(tex_coord_max[2]),
         static_cast<float>(tex_coord_min[0]), static_cast<float>(tex_coord_min[2]),
         static_cast<float>(tex_coord_max[0]), static_cast<float>(tex_coord_min[2]),
         static_cast<float>(tex_coord_min[0]), static_cast<float>(tex_coord_min[1]), // front
         static_cast<float>(tex_coord_max[0]), static_cast<float>(tex_coord_min[1]),
         static_cast<float>(tex_coord_max[0]), static_cast<float>(tex_coord_max[1]),
         static_cast<float>(tex_coord_max[0]), static_cast<float>(tex_coord_max[1]),
         static_cast<float>(tex_coord_min[0]), static_cast<float>(tex_coord_max[1]),
         static_cast<float>(tex_coord_min[0]), static_cast<float>(tex_coord_min[1]),
         static_cast<float>(tex_coord_min[0]), static_cast<float>(tex_coord_min[1]), // back
         static_cast<float>(tex_coord_max[0]), static_cast<float>(tex_coord_min[1]),
         static_cast<float>(tex_coord_max[0]), static_cast<float>(tex_coord_max[1]),
         static_cast<float>(tex_coord_max[0]), static_cast<float>(tex_coord_max[1]),
         static_cast<float>(tex_coord_min[0]), static_cast<float>(tex_coord_max[1]),
         static_cast<float>(tex_coord_min[0]), static_cast<float>(tex_coord_min[1]),
         static_cast<float>(tex_coord_max[2]), static_cast<float>(tex_coord_min[1]), // left
         static_cast<float>(tex_coord_max[2]), static_cast<float>(tex_coord_max[1]),
         static_cast<float>(tex_coord_min[2]), static_cast<float>(tex_coord_max[1]),
         static_cast<float>(tex_coord_min[2]), static_cast<float>(tex_coord_max[1]),
         static_cast<float>(tex_coord_min[2]), static_cast<float>(tex_coord_min[1]),
         static_cast<float>(tex_coord_max[2]), static_cast<float>(tex_coord_min[1]),
         static_cast<float>(tex_coord_max[2]), static_cast<float>(tex_coord_min[1]), // right
         static_cast<float>(tex_coord_max[2]), static_cast<float>(tex_coord_max[1]),
         static_cast<float>(tex_coord_min[2]), static_cast<float>(tex_coord_max[1]),
         static_cast<float>(tex_coord_min[2]), static_cast<float>(tex_coord_max[1]),
         static_cast<float>(tex_coord_min[2]), static_cast<float>(tex_coord_min[1]),
         static_cast<float>(tex_coord_max[2]), static_cast<float>(tex_coord_min[1])
     };
     tAttribInfo attr_info;
     attr_info.mAttribNumber = cMeshUtil::eAttributeCoord;
     attr_info.mAttribSize = sizeof(coord_data[0]);
     attr_info.mDataOffset = 0;
     attr_info.mDataStride = 0;
     attr_info.mNumComp = cMeshUtil::gCoordDim;
     gBoxSolidMesh->LoadVBuffer(attr_info.mAttribNumber, sizeof(float) * coord_len, (GLubyte*)coord_data, 0, 1, &attr_info);
     PushMatrixView();
     Translate(pos);
     Scale(size);
     gBoxSolidMesh->Draw(GL_TRIANGLES);
     PopMatrixView();
 }
References cMeshUtil::eAttributeCoord, gBoxSolidMesh, cMeshUtil::gCoordDim, tAttribInfo::mAttribNumber, tAttribInfo::mAttribSize, tAttribInfo::mDataOffset, tAttribInfo::mDataStride, tAttribInfo::mNumComp, PopMatrixView(), PushMatrixView(), Scale(), and Translate().
Referenced by DrawBox().
DrawBoxWire()
void cDrawUtil::DrawBoxWire (const tVector & pos, const tVector & size) static protected
Definition at line 176 of file DrawUtil.cpp.
 {
     PushMatrixView();
     Translate(pos);
     Scale(size);
     gBoxWireMesh->Draw(GL_LINES);
     PopMatrixView();
 }
References gBoxWireMesh, PopMatrixView(), PushMatrixView(), Scale(), and Translate().
Referenced by DrawBox().
DrawCalibMarker()
void cDrawUtil::DrawCalibMarker (const tVector & pos, double r, int slices, const tVector & col0, const tVector & col1, eDrawMode draw_mode = eDrawSolid) static
Definition at line 684 of file DrawUtil.cpp.
 {
     SetColor(col0);
     DrawSemiCircle(pos, r, slices, 0, M_PI * 0.5, draw_mode);
     DrawSemiCircle(pos, r, slices, M_PI, M_PI * 1.5, draw_mode);
     SetColor(col1);
     DrawSemiCircle(pos, r, slices, M_PI * 0.5, M_PI, draw_mode);
     DrawSemiCircle(pos, r, slices, M_PI * 1.5, M_PI * 2, draw_mode);
 }
References DrawSemiCircle(), and SetColor().
DrawCapsule()
void cDrawUtil::DrawCapsule (double r, double h, eDrawMode draw_mode = eDrawSolid) static
Definition at line 506 of file DrawUtil.cpp.
 {
     PushMatrixView();
     DrawTube(r, h, draw_mode);
     Translate(tVector(0, 0.5 * h, 0, 0));
     DrawHemisphere(r, draw_mode);
     Translate(tVector(0, -h, 0, 0));
     Rotate(tVector(0, 0, M_PI, 0));
     DrawHemisphere(r, draw_mode);
     PopMatrixView();
 }
References DrawHemisphere(), DrawTube(), PopMatrixView(), PushMatrixView(), Rotate(), and Translate().
Referenced by cDrawObj::DrawCapsule(), and cDrawCharacter::DrawShapeCapsule().
DrawCone()
void cDrawUtil::DrawCone (double r, double h, eDrawMode draw_mode = eDrawSolid) static
Definition at line 447 of file DrawUtil.cpp.
 {
     if (draw_mode == eDrawSolid || draw_mode == eDrawWire)
     {
         DrawConeSolidWire(r, h, draw_mode);
     }
     else if (draw_mode == eDrawWireSimple)
     {
         DrawConeWireSimple(r, h);
     }
     else
     {
         assert(false); // unsupported draw mode
     }
 }
References DrawConeSolidWire(), DrawConeWireSimple(), eDrawSolid, eDrawWire, and eDrawWireSimple.
Referenced by DrawArrow3D().
DrawConeSolidWire()
void cDrawUtil::DrawConeSolidWire (double r, double h, eDrawMode draw_mode = eDrawSolid) static protected
Definition at line 989 of file DrawUtil.cpp.
 {
     GLenum gl_mode = (draw_mode == eDrawSolid) ? GL_TRIANGLES : GL_LINES;
     PushMatrixView();
     Scale(tVector(r, h, r, 0));
     gConeMesh->Draw(gl_mode);
     PopMatrixView();
 }
References eDrawSolid, gConeMesh, PopMatrixView(), PushMatrixView(), and Scale().
Referenced by DrawCone().
DrawConeWireSimple()
void cDrawUtil::DrawConeWireSimple (double r, double h) static protected
Definition at line 998 of file DrawUtil.cpp.
 {
     PushMatrixView();
     Scale(tVector(r, h, r, 0));
     gConeWireSimpleMesh->Draw(GL_LINES);
     PopMatrixView();
 }
References gConeWireSimpleMesh, PopMatrixView(), PushMatrixView(), and Scale().
Referenced by DrawCone().
DrawCross()
void cDrawUtil::DrawCross (const tVector & pos, double size) static
Definition at line 368 of file DrawUtil.cpp.
 {
     DrawLine(tVector(pos[0] - 0.5 * size, pos[1], pos[2], 0),
         tVector(pos[0] + 0.5 * size, pos[1], pos[2], 0));
     DrawLine(tVector(pos[0], pos[1] - 0.5 * size, pos[2], 0),
         tVector(pos[0], pos[1] + 0.5 * size, pos[2], 0));
     DrawLine(tVector(pos[0], pos[1], pos[2] - 0.5 * size, 0),
         tVector(pos[0], pos[1], pos[2] + 0.5 * size, 0));
 }
References DrawLine().
Referenced by cDrawSimCharacter::DrawCoM(), and cObjTracer::DrawTraceContact().
DrawCylinder()
void cDrawUtil::DrawCylinder (double r, double h, eDrawMode draw_mode = eDrawSolid) static
Definition at line 431 of file DrawUtil.cpp.
 {
     if (draw_mode == eDrawSolid || draw_mode == eDrawWire)
     {
         DrawCylinderSolidWire(r, h, draw_mode);
     }
     else if (draw_mode == eDrawWireSimple)
     {
         DrawCylinderWireSimple(r, h);
     }
     else
     {
         assert(false); // unsupported draw mode
     }
 }
References DrawCylinderSolidWire(), DrawCylinderWireSimple(), eDrawSolid, eDrawWire, and eDrawWireSimple.
Referenced by DrawArrow3D(), cDrawObj::DrawCylinder(), and cDrawCharacter::DrawShapeCylinder().
DrawCylinderSolidWire()
void cDrawUtil::DrawCylinderSolidWire (double r, double h, eDrawMode draw_mode = eDrawSolid) static protected
Definition at line 957 of file DrawUtil.cpp.
 {
     GLenum gl_mode = (draw_mode == eDrawSolid) ? GL_TRIANGLES : GL_LINES;
     PushMatrixView();
     Scale(tVector(r, h, r, 0));
     gCylinderMesh->Draw(gl_mode);
     PopMatrixView();
 }
References eDrawSolid, gCylinderMesh, PopMatrixView(), PushMatrixView(), and Scale().
Referenced by DrawCylinder().
DrawCylinderWireSimple()
void cDrawUtil::DrawCylinderWireSimple (double r, double h) static protected
Definition at line 966 of file DrawUtil.cpp.
 {
     PushMatrixView();
     Scale(tVector(r, h, r, 0));
     gCylinderWireSimpleMesh->Draw(GL_LINES);
     PopMatrixView();
 }
References gCylinderWireSimpleMesh, PopMatrixView(), PushMatrixView(), and Scale().
Referenced by DrawCylinder(), and DrawTube().
DrawDisk() [1/4]
void cDrawUtil::DrawDisk (const tVector & pos, const tVector & r, eDrawMode draw_mode = eDrawSolid) static
Definition at line 277 of file DrawUtil.cpp.
 {
     cDrawUtil::PushMatrixView();
     cDrawUtil::Translate(pos);
     DrawDisk(r, draw_mode);
     cDrawUtil::PopMatrixView();
 }
References DrawDisk(), PopMatrixView(), PushMatrixView(), and Translate().
DrawDisk() [2/4]
void cDrawUtil::DrawDisk (const tVector & pos, double r, eDrawMode draw_mode = eDrawSolid) static
Definition at line 272 of file DrawUtil.cpp.
 {
     DrawDisk(pos, tVector(r, r, r, 1), draw_mode);
 }
Referenced by DrawDisk(), cDrawPerturb::DrawTorque(), and cObjTracer::DrawTraceContact().
DrawDisk() [3/4]
void cDrawUtil::DrawDisk (const tVector & r, eDrawMode draw_mode = eDrawSolid) static
Definition at line 290 of file DrawUtil.cpp.
 {
     cDrawUtil::PushMatrixView();
     cDrawUtil::Scale(r);
     if (draw_mode == eDrawWireSimple || draw_mode == eDrawWire)
     {
         gDiskMesh->Draw(GL_LINE_STRIP, 1);
     }
     else if (draw_mode == eDrawSolid)
     {
         gDiskMesh->Draw(GL_TRIANGLE_FAN);
     }
     else
     {
         assert(false); //unsupported draw mode
     }
     cDrawUtil::PopMatrixView();
 }
References eDrawSolid, eDrawWire, eDrawWireSimple, gDiskMesh, PopMatrixView(), PushMatrixView(), and Scale().
DrawDisk() [4/4]
void cDrawUtil::DrawDisk (double r, eDrawMode draw_mode = eDrawSolid) static
Definition at line 285 of file DrawUtil.cpp.
 {
     cDrawUtil::DrawDisk(tVector(r, r, r, 1), draw_mode);
 }
References DrawDisk().
DrawGrid2D()
void cDrawUtil::DrawGrid2D (const tVector & origin, const tVector & size, double spacing, double line_width) static
Definition at line 592 of file DrawUtil.cpp.
 {
     double w = size[0];
     double h = size[1];
     double min_x = origin(0) - w;
     double min_y = origin(1) - h;
     double max_x = origin(0) + w;
     double max_y = origin(1) + h;
     const double offset_z = origin[2];
     cDrawUtil::SetLineWidth(line_width);
     cDrawUtil::SetColor(tVector(188 / 255.f, 219 / 255.f, 242 / 255.f, 1.f));
     for (double x = min_x - std::fmod(min_x, spacing); x < max_x; x += spacing)
     {
         tVector a = tVector(x, min_y, offset_z, offset_z);
         tVector b = tVector(x, max_y, offset_z, offset_z);
         cDrawUtil::DrawLine(a, b);
     }
     for (double y = min_y - std::fmod(min_y, spacing); y < max_y; y += spacing)
     {
         tVector a = tVector(min_x, y, offset_z, offset_z);
         tVector b = tVector(max_x, y, offset_z, offset_z);
         cDrawUtil::DrawLine(a, b);
     }
 }
References DrawLine(), SetColor(), and SetLineWidth().
Referenced by cDrawScene::DrawGrid().
DrawHemisphere()
void cDrawUtil::DrawHemisphere (double r, eDrawMode draw_mode = eDrawSolid) static
Definition at line 403 of file DrawUtil.cpp.
 {
     cDrawUtil::PushMatrixView();
     cDrawUtil::Scale(tVector(r, r, r, 1));
     int elem = gSphereMesh->GetNumVerts() / 2;
     if (draw_mode == eDrawSolid)
     {
         gSphereMesh->Draw(GL_TRIANGLES, 0, elem);
     }
     else if (draw_mode == eDrawWire)
     {
         gSphereMesh->Draw(GL_LINES, 0, elem);
         cDrawUtil::Rotate(tVector(-M_PI / 2, 0, 0, 0));
         gDiskMesh->Draw(GL_LINE_STRIP);
     }
     else if (draw_mode == eDrawWireSimple)
     {
         gSphereWireSimpleMesh->Draw(GL_LINES, 0, ((gNumStacks / 2) * 4 + gNumSlice) * 2);
     }
     else
     {
         assert(false); // unsupported draw mode
     }
     cDrawUtil::PopMatrixView();
 }
References eDrawSolid, eDrawWire, eDrawWireSimple, gDiskMesh, gNumSlice, gNumStacks, gSphereMesh, gSphereWireSimpleMesh, PopMatrixView(), PushMatrixView(), Rotate(), and Scale().
Referenced by DrawCapsule().
DrawLine()
void cDrawUtil::DrawLine (const tVector & a, const tVector & b) static
Definition at line 319 of file DrawUtil.cpp.
 {
     const int num_verts = 2;
     const int pos_len = num_verts * cMeshUtil::gPosDim;
     const float pos_data[pos_len] =
     {
         static_cast<float>(a[0]), static_cast<float>(a[1]), static_cast<float>(a[2]),
         static_cast<float>(b[0]), static_cast<float>(b[1]), static_cast<float>(b[2])
     };
     tAttribInfo attr_info;
     attr_info.mAttribNumber = cMeshUtil::eAttributePosition;
     attr_info.mAttribSize = sizeof(pos_data[0]);
     attr_info.mDataOffset = 0;
     attr_info.mDataStride = 0;
     attr_info.mNumComp = cMeshUtil::gPosDim;
     gLineMesh->LoadVBuffer(attr_info.mAttribNumber, sizeof(float) * pos_len, (GLubyte*)pos_data, 0, 1, &attr_info);
     gLineMesh->Draw(GL_LINES);
 }
References cMeshUtil::eAttributePosition, gLineMesh, cMeshUtil::gPosDim, tAttribInfo::mAttribNumber, tAttribInfo::mAttribSize, tAttribInfo::mDataOffset, tAttribInfo::mDataStride, and tAttribInfo::mNumComp.
Referenced by cGraphUtil::DrawBarPlot(), cDrawSimCharacter::DrawBodyVel(), DrawCross(), DrawGrid2D(), cDrawSimCharacter::DrawInfoValLog(), and DrawRuler2D().
DrawLineStrip()
void cDrawUtil::DrawLineStrip (const tVectorArr & pts) static
Definition at line 340 of file DrawUtil.cpp.
 {
     int num_pts = static_cast<int>(pts.size());
     glBegin(GL_LINE_STRIP);
     for (int i = 0; i < num_pts - 1; ++i)
     {
         const tVector& a = pts[i];
         const tVector& b = pts[i + 1];
         glVertex3d(a[0], a[1], a[2]);
         glVertex3d(b[0], b[1], b[2]);
     }
     glEnd();
 }
DrawPlane()
void cDrawUtil::DrawPlane (const tVector & coeffs, double size, eDrawMode draw_mode = eDrawSolid) static
Definition at line 479 of file DrawUtil.cpp.
 {
     const Eigen::Vector3d ref = Eigen::Vector3d(0, 0, 1);
     Eigen::Vector3d n = Eigen::Vector3d(coeffs[0], coeffs[1], coeffs[2]);
     double c = coeffs[3];
     Eigen::Vector3d axis = ref.cross(n);
     double axis_len = axis.norm();
     double theta = 0;
     if (axis_len != 0)
     {
         axis /= axis_len;
         theta = std::acos(ref.dot(n));
     }
     Eigen::Vector3d offset = c * n;
     cDrawUtil::PushMatrixView();
     cDrawUtil::Translate(tVector(offset[0], offset[1], offset[2], 0));
     if (theta != 0)
     {
         cDrawUtil::Rotate(theta, tVector(axis[0], axis[1], axis[2], 0));
     }
     DrawRect(tVector::Zero(), tVector(size, size, 0, 0), draw_mode);
     cDrawUtil::PopMatrixView();
 }
References DrawRect(), PopMatrixView(), PushMatrixView(), Rotate(), and Translate().
Referenced by cDrawObj::DrawPlane().
DrawPoint()
void cDrawUtil::DrawPoint (const tVector & pt) static
Definition at line 311 of file DrawUtil.cpp.
 {
     cDrawUtil::PushMatrixView();
     cDrawUtil::Translate(pt);
     gPointMesh->Draw(GL_POINTS);
     cDrawUtil::PopMatrixView();
 }
References gPointMesh, PopMatrixView(), PushMatrixView(), and Translate().
Referenced by cDrawSimCharacter::DrawInfoValLog().
DrawQuad() [1/2]
void cDrawUtil::DrawQuad (const tVector & a, const tVector & b, const tVector & c, const tVector & d, const tVector & coord_a, const tVector & coord_b, const tVector & coord_c, const tVector & coord_d, eDrawMode draw_mode = eDrawSolid) static
Definition at line 201 of file DrawUtil.cpp.
 {
     const int num_verts = 4;
     const int pos_len = num_verts * cMeshUtil::gPosDim;
     const int norm_len = num_verts * cMeshUtil::gNormDim;
     const int coord_len = num_verts * cMeshUtil::gCoordDim;
     GLenum gl_mode = (draw_mode == eDrawSolid) ? GL_TRIANGLE_FAN : GL_LINE_LOOP;
     tVector normal = (b - a).cross3(d - a);
     double normal_len = normal.norm();
     if (normal_len == 0)
     {
         normal = tVector(0, 0, 1, 0);
     }
     else
     {
         normal = (normal / normal_len);
     }
     const float pos_data[pos_len] =
     {
         static_cast<float>(a[0]), static_cast<float>(a[1]), static_cast<float>(a[2]),
         static_cast<float>(b[0]), static_cast<float>(b[1]), static_cast<float>(b[2]),
         static_cast<float>(c[0]), static_cast<float>(c[1]), static_cast<float>(c[2]),
         static_cast<float>(d[0]), static_cast<float>(d[1]), static_cast<float>(d[2])
     };
     const float norm_data[norm_len] =
     {
         static_cast<float>(normal[0]), static_cast<float>(normal[1]), static_cast<float>(normal[2]),
         static_cast<float>(normal[0]), static_cast<float>(normal[1]), static_cast<float>(normal[2]),
         static_cast<float>(normal[0]), static_cast<float>(normal[1]), static_cast<float>(normal[2]),
         static_cast<float>(normal[0]), static_cast<float>(normal[1]), static_cast<float>(normal[2])
     };
     const float coord_data[coord_len] =
     {
         static_cast<float>(coord_a[0]), static_cast<float>(coord_a[1]),
         static_cast<float>(coord_b[0]), static_cast<float>(coord_b[1]),
         static_cast<float>(coord_c[0]), static_cast<float>(coord_c[1]),
         static_cast<float>(coord_d[0]), static_cast<float>(coord_d[1])
     };
     tAttribInfo attr_info;
     attr_info.mAttribNumber = cMeshUtil::eAttributePosition;
     attr_info.mAttribSize = sizeof(pos_data[0]);
     attr_info.mDataOffset = 0;
     attr_info.mDataStride = 0;
     attr_info.mNumComp = cMeshUtil::gPosDim;
     gQuadMesh->LoadVBuffer(attr_info.mAttribNumber, sizeof(float) * pos_len, (GLubyte*)pos_data, 0, 1, &attr_info);
     attr_info.mAttribNumber = cMeshUtil::eAttributeNormal;
     attr_info.mAttribSize = sizeof(norm_data[0]);
     attr_info.mDataOffset = 0;
     attr_info.mDataStride = 0;
     attr_info.mNumComp = cMeshUtil::gNormDim;
     gQuadMesh->LoadVBuffer(attr_info.mAttribNumber, sizeof(float) * norm_len, (GLubyte*)norm_data, 0, 1, &attr_info);
     attr_info.mAttribNumber = cMeshUtil::eAttributeCoord;
     attr_info.mAttribSize = sizeof(norm_data[0]);
     attr_info.mDataOffset = 0;
     attr_info.mDataStride = 0;
     attr_info.mNumComp = cMeshUtil::gCoordDim;
     gQuadMesh->LoadVBuffer(attr_info.mAttribNumber, sizeof(float) * coord_len, (GLubyte*)coord_data, 0, 1, &attr_info);
     gQuadMesh->Draw(gl_mode);
 }
References cMeshUtil::eAttributeCoord, cMeshUtil::eAttributeNormal, cMeshUtil::eAttributePosition, eDrawSolid, cMeshUtil::gCoordDim, cMeshUtil::gNormDim, cMeshUtil::gPosDim, gQuadMesh, tAttribInfo::mAttribNumber, tAttribInfo::mAttribSize, tAttribInfo::mDataOffset, tAttribInfo::mDataStride, and tAttribInfo::mNumComp.
DrawQuad() [2/2]
void cDrawUtil::DrawQuad (const tVector & a, const tVector & b, const tVector & c, const tVector & d, eDrawMode draw_mode = eDrawSolid) static
Definition at line 195 of file DrawUtil.cpp.
 {
     DrawQuad(a, b, c, d, tVector(0, 0, 0, 0), tVector(1, 0, 0, 0),
         tVector(1, 1, 0, 0), tVector(0, 1, 0, 0), draw_mode);
 }
Referenced by DrawArrow2D(), cDrawSceneKinChar::DrawGround3D(), DrawRect(), DrawStrip(), and DrawTexQuad().
DrawRect()
void cDrawUtil::DrawRect (const tVector & pos, const tVector & size, eDrawMode draw_mode = eDrawSolid) static
Definition at line 82 of file DrawUtil.cpp.
 {
     tVector a = tVector(pos[0] - 0.5 * size[0], pos[1] - 0.5 * size[1], pos[2], 0);
     tVector b = tVector(pos[0] + 0.5 * size[0], pos[1] - 0.5 * size[1], pos[2], 0);
     tVector c = tVector(pos[0] + 0.5 * size[0], pos[1] + 0.5 * size[1], pos[2], 0);
     tVector d = tVector(pos[0] - 0.5 * size[0], pos[1] + 0.5 * size[1], pos[2], 0);
     DrawQuad(a, b, c, d, draw_mode);
 }
References DrawQuad().
Referenced by cGraphUtil::DrawBarPlot(), cDrawSimCharacter::DrawInfoValLog(), DrawPlane(), DrawRuler2D(), and cObjTracer::DrawTraceContact().
DrawRuler2D()
void cDrawUtil::DrawRuler2D (const tVector & origin, const tVector & size, const tVector & col, double line_width, double marker_spacing, double marker_h, double marker_line_width) static
Definition at line 622 of file DrawUtil.cpp.
 {
     double w = size[0];
     double h = size[1];
     double min_x = origin(0) - w * 0.5;
     double max_x = origin(0) + w * 0.5;
     double max_y = origin(1) + h * 0.5;
     if (line_width > 0)
     {
         glTexCoord2d(0, 0);
         cDrawUtil::SetLineWidth(line_width);
         cDrawUtil::SetColor(col);
         cDrawUtil::DrawRect(origin, size, cDrawUtil::eDrawSolid);
         cDrawUtil::SetColor(tVector(0, 0, 0, 1));
         cDrawUtil::DrawLine(tVector(min_x, max_y, 0, 0), tVector(max_x, max_y, 0, 0));
     }
     // draw markers
     if (marker_line_width > 0)
     {
         cDrawUtil::SetColor(tVector(0.f, 0.f, 0.f, 1.f));
         cDrawUtil::SetLineWidth(marker_line_width);
         for (double x = min_x - std::fmod(min_x, marker_spacing); x < max_x; x += marker_spacing)
         {
             tVector a = tVector(x, max_y + marker_h * 0.5f, 0, 0);
             tVector b = tVector(x, max_y - marker_h * 0.5f, 0, 0);
             cDrawUtil::DrawLine(a, b);
         }
     }
 }
References DrawLine(), DrawRect(), eDrawSolid, SetColor(), and SetLineWidth().
DrawSemiCircle()
void cDrawUtil::DrawSemiCircle (const tVector & pos, double r, int slices, double min_theta, double max_theta, eDrawMode draw_mode = eDrawSolid) static
Definition at line 657 of file DrawUtil.cpp.
 {
     double d_theta = (max_theta - min_theta) / (slices - 1);
     GLenum gl_mode = (draw_mode == eDrawSolid) ? GL_TRIANGLE_FAN : GL_LINE_LOOP;
     glBegin(gl_mode);
     glTexCoord2d(0, 0);
     glNormal3d(0, 0, 1);
     glVertex3d(pos[0], pos[1], pos[2]);
     for (int i = 0; i < slices; ++i)
     {
         double theta0 = i * d_theta + min_theta;
         double theta1 = i * d_theta + min_theta;
         double x0 = r * std::cos(theta0) + pos[0];
         double y0 = r * std::sin(theta0) + pos[1];
         double x1 = r * std::cos(theta1) + pos[0];
         double y1 = r * std::sin(theta1) + pos[1];;
         glVertex3d(x0, y0, pos[2]);
         glVertex3d(x1, y1, pos[2]);
     }
     glEnd();
 }
References eDrawSolid.
Referenced by DrawCalibMarker().
DrawSphere()
void cDrawUtil::DrawSphere (double r, eDrawMode draw_mode = eDrawSolid) static
Definition at line 378 of file DrawUtil.cpp.
 {
     cDrawUtil::PushMatrixView();
     cDrawUtil::Scale(tVector(r, r, r, 1));
     if (draw_mode == eDrawSolid)
     {
         gSphereMesh->Draw(GL_TRIANGLES);
     }
     else if (draw_mode == eDrawWire)
     {
         gSphereMesh->Draw(GL_LINES);
     }
     else if (draw_mode == eDrawWireSimple)
     {
         gSphereWireSimpleMesh->Draw(GL_LINES);
     }
     else
     {
         assert(false); // unsupported draw mode
     }
     cDrawUtil::PopMatrixView();
 }
References eDrawSolid, eDrawWire, eDrawWireSimple, gSphereMesh, gSphereWireSimpleMesh, PopMatrixView(), PushMatrixView(), and Scale().
Referenced by cDrawCharacter::DrawShapeSphere(), cDrawObj::DrawSphere(), and cDrawKinTree::DrawTree().
DrawStrip()
void cDrawUtil::DrawStrip (const tVector & a, const tVector & b, double width, eDrawMode draw_mode = eDrawSolid) static
Definition at line 354 of file DrawUtil.cpp.
 {
     tVector delta = b - a;
     tVector orthogonal = tVector(-delta[1], delta[0], 0, 0);
     orthogonal.normalize();
     tVector v0 = a - width * 0.5 * orthogonal;
     tVector v1 = b - width * 0.5 * orthogonal;
     tVector v2 = b + width * 0.5 * orthogonal;
     tVector v3 = a + width * 0.5 * orthogonal;
     DrawQuad(v0, v1, v2, v3, draw_mode);
 }
References DrawQuad().
DrawTexQuad()
void cDrawUtil::DrawTexQuad (const cTextureDesc & tex, const tVector & pos, const tVector & size) static
Definition at line 697 of file DrawUtil.cpp.
 {
     tex.BindTex(GL_TEXTURE0);
     DrawQuad(tVector(pos[0] - 0.5 * size[0], pos[1] - 0.5 * size[1], pos[2], 0),
         tVector(pos[0] + 0.5 * size[0], pos[1] - 0.5 * size[1], pos[2], 0),
         tVector(pos[0] + 0.5 * size[0], pos[1] + 0.5 * size[1], pos[2], 0),
         tVector(pos[0] - 0.5 * size[0], pos[1] + 0.5 * size[1], pos[2], 0),
         tVector(0, 0, 0, 0), tVector(1, 0, 0, 0), tVector(1, 1, 0, 0), tVector(0, 1, 0, 0),
         eDrawSolid);
     tex.UnbindTex(GL_TEXTURE0);
 }
References cTextureDesc::BindTex(), DrawQuad(), eDrawSolid, and cTextureDesc::UnbindTex().
Referenced by CopyTexture().
DrawTriangle()
void cDrawUtil::DrawTriangle (const tVector & pos, double side_len, eDrawMode draw_mode = eDrawSolid) static
Definition at line 185 of file DrawUtil.cpp.
 {
     GLenum gl_mode = (draw_mode == eDrawSolid) ? GL_TRIANGLES : GL_LINE_LOOP;
     PushMatrixView();
     Translate(pos);
     Scale(tVector(side_len, side_len, side_len, 1));
     gTriangleMesh->Draw(gl_mode);
     PopMatrixView();
 }
References eDrawSolid, gTriangleMesh, PopMatrixView(), PushMatrixView(), Scale(), and Translate().
Referenced by cObjTracer::DrawTraceContact().
DrawTube()
void cDrawUtil::DrawTube (double r, double h, eDrawMode draw_mode = eDrawSolid) static
Definition at line 463 of file DrawUtil.cpp.
 {
     if (draw_mode == eDrawSolid || draw_mode == eDrawWire)
     {
         DrawTubeSolidWire(r, h, draw_mode);
     }
     else if (draw_mode == eDrawWireSimple)
     {
         DrawCylinderWireSimple(r, h);
     }
     else
     {
         assert(false); // unsupported draw mode
     }
 }
References DrawCylinderWireSimple(), DrawTubeSolidWire(), eDrawSolid, eDrawWire, and eDrawWireSimple.
Referenced by DrawCapsule().
DrawTubeSolidWire()
void cDrawUtil::DrawTubeSolidWire (double r, double h, eDrawMode draw_mode = eDrawSolid) static protected
Definition at line 974 of file DrawUtil.cpp.
 {
     PushMatrixView();
     Scale(tVector(r, h, r, 0));
     if (draw_mode == eDrawSolid)
     {
         gCylinderMesh->Draw(GL_TRIANGLES, 0, gNumSlice * 6);
     }
     else
     {
         gCylinderMesh->Draw(GL_LINES);
     }
     PopMatrixView();
 }
References eDrawSolid, gCylinderMesh, gNumSlice, PopMatrixView(), PushMatrixView(), and Scale().
Referenced by DrawTube().
EnableDraw() [1/2]
bool cDrawUtil::EnableDraw () static
Definition at line 38 of file DrawUtil.cpp.
 {
     return gEnableDraw;
 }
References gEnableDraw.
Referenced by cDeepMimicCore::cDeepMimicCore(), cDeepMimicCore::EnableDraw(), and cCharacter::Init().
EnableDraw() [2/2]
void cDrawUtil::EnableDraw (bool enable) static
Definition at line 33 of file DrawUtil.cpp.
 {
     gEnableDraw = enable;
 }
References gEnableDraw.
Finish()
void cDrawUtil::Finish () static
Definition at line 874 of file DrawUtil.cpp.
 {
     glFinish();
 }
InitDrawUtil()
void cDrawUtil::InitDrawUtil () static
Definition at line 58 of file DrawUtil.cpp.
 {
     glewInit();
     const GLubyte* renderer = glGetString(GL_RENDERER); // get renderer string
     const GLubyte* version = glGetString(GL_VERSION); // version as a string
     printf("Renderer: %s\n", renderer);
     printf("OpenGL version supported %s\n", version);
     glEnable(GL_TEXTURE_2D);
     glEnable(GL_BLEND);
     glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
     glEnable(GL_DEPTH_TEST);
     glDepthFunc(GL_LEQUAL);
     glFrontFace(GL_CCW);
     BuildShaders();
     BuildMeshes();
     gMatStackView.Clear();
     gMatStackProj.Clear();
     cDrawUtil::BindDefaultProg();
 }
References BindDefaultProg(), BuildMeshes(), BuildShaders(), cMatrixStack::Clear(), gMatStackProj, and gMatStackView.
Referenced by cDeepMimicCore::Init().
InitOffscreenDrawContext()
void cDrawUtil::InitOffscreenDrawContext () static
Definition at line 43 of file DrawUtil.cpp.
 {
     int argc = 0;
     glutInit(&argc, nullptr);
     glutInitDisplayMode(GLUT_RGBA | GLUT_DOUBLE | GLUT_DEPTH);
     glutInitWindowSize(1, 1);
     glutCreateWindow("DeepMimic");
 }
LoadIdentityProj()
void cDrawUtil::LoadIdentityProj () static
Definition at line 805 of file DrawUtil.cpp.
 {
     gMatStackProj.SetIdentity();
 }
References gMatStackProj, and cMatrixStack::SetIdentity().
Referenced by CopyTexture(), and cDrawScene::DrawScene().
LoadIdentityView()
void cDrawUtil::LoadIdentityView () static
Definition at line 800 of file DrawUtil.cpp.
 {
     gMatStackView.SetIdentity();
 }
References gMatStackView, and cMatrixStack::SetIdentity().
Referenced by CopyTexture(), and cDrawScene::DrawScene().
LoadMatrixProj()
void cDrawUtil::LoadMatrixProj (const tMatrix & mat) static
Definition at line 795 of file DrawUtil.cpp.
 {
     gMatStackProj.SetMatrix(mat);
 }
References gMatStackProj, and cMatrixStack::SetMatrix().
Referenced by cCamera::SetupGLProj().
LoadMatrixView()
void cDrawUtil::LoadMatrixView (const tMatrix & mat) static
Definition at line 790 of file DrawUtil.cpp.
 {
     gMatStackView.SetMatrix(mat);
 }
References gMatStackView, and cMatrixStack::SetMatrix().
Referenced by cCamera::SetupGLView().
LoadShaderUniforms()
void cDrawUtil::LoadShaderUniforms () static
Definition at line 850 of file DrawUtil.cpp.
 {
     const cShader* curr_shader = cShader::GetBoundShader();
     if (curr_shader != nullptr)
     {
         if (curr_shader->HasUniform(cShader::eUniformModelViewMatrix))
         {
             tMatrix view_mat = gMatStackView.GetMatrix();
             curr_shader->SetUniformMat(cShader::eUniformModelViewMatrix, view_mat);
         }
         if (curr_shader->HasUniform(cShader::eUniformProjectionMatrix))
         {
             tMatrix proj_mat = gMatStackProj.GetMatrix();
             curr_shader->SetUniformMat(cShader::eUniformProjectionMatrix, proj_mat);
         }
         if (curr_shader->HasUniform(cShader::eUniformColor))
         {
             curr_shader->SetUniform4(cShader::eUniformColor, gColor);
         }
     }
 }
References cShader::eUniformColor, cShader::eUniformModelViewMatrix, cShader::eUniformProjectionMatrix, gColor, cShader::GetBoundShader(), cMatrixStack::GetMatrix(), gMatStackProj, gMatStackView, cShader::HasUniform(), cShader::SetUniform4(), and cShader::SetUniformMat().
Referenced by cDrawMesh::Draw().
MultMatrixProj()
void cDrawUtil::MultMatrixProj (const tMatrix & mat) static
Definition at line 785 of file DrawUtil.cpp.
 {
     gMatStackProj.MultMatrix(mat);
 }
References gMatStackProj, and cMatrixStack::MultMatrix().
MultMatrixView()
void cDrawUtil::MultMatrixView (const tMatrix & mat) static
Definition at line 780 of file DrawUtil.cpp.
 {
     gMatStackView.MultMatrix(mat);
 }
References gMatStackView, and cMatrixStack::MultMatrix().
Referenced by DrawArrow3D(), cDrawCharacter::DrawHeading(), cDrawCharacter::DrawShapeBox(), cDrawCharacter::DrawShapeCapsule(), cDrawCharacter::DrawShapeCylinder(), cDrawCharacter::DrawShapeMesh(), cDrawCharacter::DrawShapeSphere(), and cDrawKinTree::DrawTree().
PopMatrixProj()
void cDrawUtil::PopMatrixProj () static
Definition at line 825 of file DrawUtil.cpp.
 {
     gMatStackProj.Pop();
 }
References gMatStackProj, and cMatrixStack::Pop().
Referenced by CopyTexture(), cDrawScene::DoShadowPass(), cDrawScene::DrawScene(), and cDrawScene::RestoreView().
PopMatrixView()
void cDrawUtil::PopMatrixView () static
Definition at line 820 of file DrawUtil.cpp.
 {
     gMatStackView.Pop();
 }
References gMatStackView, and cMatrixStack::Pop().
Referenced by CopyTexture(), cDrawScene::DoShadowPass(), DrawArrow3D(), cDrawObj::DrawBox(), DrawBoxSolid(), DrawBoxWire(), cDrawObj::DrawCapsule(), DrawCapsule(), DrawConeSolidWire(), DrawConeWireSimple(), cDrawObj::DrawCylinder(), DrawCylinderSolidWire(), DrawCylinderWireSimple(), DrawDisk(), cDrawCharacter::DrawHeading(), DrawHemisphere(), DrawPlane(), DrawPoint(), cDrawScene::DrawScene(), cDrawCharacter::DrawShapeBox(), cDrawCharacter::DrawShapeCapsule(), cDrawCharacter::DrawShapeCylinder(), cDrawCharacter::DrawShapeMesh(), cDrawCharacter::DrawShapeSphere(), cDrawObj::DrawSphere(), DrawSphere(), cDrawPerturb::DrawTorque(), cDrawSceneSimChar::DrawTrace(), cDrawKinTree::DrawTree(), DrawTriangle(), DrawTubeSolidWire(), and cDrawScene::RestoreView().
PushMatrixProj()
void cDrawUtil::PushMatrixProj () static
Definition at line 815 of file DrawUtil.cpp.
 {
     gMatStackProj.Push();
 }
References gMatStackProj, and cMatrixStack::Push().
Referenced by CopyTexture(), cDrawScene::DoShadowPass(), cDrawScene::DrawScene(), and cDrawScene::SetupView().
PushMatrixView()
void cDrawUtil::PushMatrixView () static
Definition at line 810 of file DrawUtil.cpp.
 {
     gMatStackView.Push();
 }
References gMatStackView, and cMatrixStack::Push().
Referenced by CopyTexture(), cDrawScene::DoShadowPass(), DrawArrow3D(), cDrawObj::DrawBox(), DrawBoxSolid(), DrawBoxWire(), cDrawObj::DrawCapsule(), DrawCapsule(), DrawConeSolidWire(), DrawConeWireSimple(), cDrawObj::DrawCylinder(), DrawCylinderSolidWire(), DrawCylinderWireSimple(), DrawDisk(), cDrawCharacter::DrawHeading(), DrawHemisphere(), DrawPlane(), DrawPoint(), cDrawScene::DrawScene(), cDrawCharacter::DrawShapeBox(), cDrawCharacter::DrawShapeCapsule(), cDrawCharacter::DrawShapeCylinder(), cDrawCharacter::DrawShapeMesh(), cDrawCharacter::DrawShapeSphere(), cDrawObj::DrawSphere(), DrawSphere(), cDrawPerturb::DrawTorque(), cDrawSceneSimChar::DrawTrace(), cDrawKinTree::DrawTree(), DrawTriangle(), DrawTubeSolidWire(), and cDrawScene::SetupView().
Rotate() [1/3]
void cDrawUtil::Rotate (const tQuaternion & q) static
Definition at line 919 of file DrawUtil.cpp.
 {
     double theta;
     tVector axis;
     cMathUtil::QuaternionToAxisAngle(q, axis, theta);
     Rotate(theta, axis);
 }
References cMathUtil::QuaternionToAxisAngle(), and Rotate().
Rotate() [2/3]
void cDrawUtil::Rotate (const tVector & euler) static
Definition at line 906 of file DrawUtil.cpp.
 {
     double theta;
     tVector axis;
     cMathUtil::EulerToAxisAngle(euler, axis, theta);
     Rotate(theta, axis);
 }
References cMathUtil::EulerToAxisAngle().
Referenced by cDrawObj::DrawBox(), cDrawObj::DrawCapsule(), DrawCapsule(), cDrawObj::DrawCylinder(), DrawHemisphere(), DrawPlane(), cDrawCharacter::DrawShapeBox(), cDrawCharacter::DrawShapeCapsule(), cDrawCharacter::DrawShapeCylinder(), cDrawCharacter::DrawShapeMesh(), cDrawCharacter::DrawShapeSphere(), cDrawObj::DrawSphere(), cDrawKinTree::DrawTree(), and Rotate().
Rotate() [3/3]
void cDrawUtil::Rotate (double theta, const tVector & axis) static
Definition at line 914 of file DrawUtil.cpp.
 {
     gMatStackView.Rotate(theta, axis);
 }
References gMatStackView, and cMatrixStack::Rotate().
Scale()
void cDrawUtil::Scale (const tVector & scale) static
Definition at line 901 of file DrawUtil.cpp.
 {
     gMatStackView.Scale(scale);
 }
References gMatStackView, and cMatrixStack::Scale().
Referenced by DrawBoxSolid(), DrawBoxWire(), DrawConeSolidWire(), DrawConeWireSimple(), DrawCylinderSolidWire(), DrawCylinderWireSimple(), DrawDisk(), DrawHemisphere(), cDrawCharacter::DrawShapeMesh(), DrawSphere(), DrawTriangle(), and DrawTubeSolidWire().
SetColor()
void cDrawUtil::SetColor (const tVector & col) static
Definition at line 927 of file DrawUtil.cpp.
 {
     gColor = col;
 }
References gColor.
Referenced by CopyTexture(), cGraphUtil::DrawBarPlot(), cDrawSimCharacter::DrawBodyVel(), DrawCalibMarker(), cDrawSimCharacter::DrawCoM(), cDrawPerturb::DrawForce(), DrawGrid2D(), cDrawSceneKinChar::DrawGround(), cDrawSceneSimChar::DrawGround(), cDrawCharacter::DrawHeading(), cDrawSimCharacter::DrawInfoValLog(), cDrawSceneSimChar::DrawObjs(), DrawRuler2D(), cDrawCharacter::DrawShapeBox(), cDrawCharacter::DrawShapeCapsule(), cDrawCharacter::DrawShapeCylinder(), cDrawCharacter::DrawShapeMesh(), cDrawCharacter::DrawShapeSphere(), cDrawSimCharacter::DrawSimBody(), cDrawPerturb::DrawTorque(), cObjTracer::DrawTraceContact(), cObjTracer::DrawTracePos(), and cDrawKinTree::DrawTree().
SetLineWidth()
void cDrawUtil::SetLineWidth (double w) static
Definition at line 932 of file DrawUtil.cpp.
 {
     glLineWidth(static_cast<float>(w));
 }
Referenced by cDrawKinTree::Draw(), cGraphUtil::DrawBarPlot(), cDrawSimCharacter::DrawBodyVel(), cDrawCharacter::DrawCharShapes(), cDrawSimCharacter::DrawCoM(), DrawGrid2D(), cDrawSimCharacter::DrawInfoValLog(), cDrawCharacter::DrawPoseCharShapes(), DrawRuler2D(), cDrawSimCharacter::DrawSimBody(), and cObjTracer::DrawTrace().
SetPointSize()
void cDrawUtil::SetPointSize (double pt_size) static
Definition at line 937 of file DrawUtil.cpp.
 {
     glPointSize(static_cast<float>(pt_size));
 }
Referenced by cDrawSimCharacter::DrawInfoValLog().
Translate()
void cDrawUtil::Translate (const tVector & trans) static
Definition at line 896 of file DrawUtil.cpp.
 {
     gMatStackView.Translate(trans);
 }
References gMatStackView, and cMatrixStack::Translate().
Referenced by DrawArrow3D(), cDrawObj::DrawBox(), DrawBoxSolid(), DrawBoxWire(), cDrawObj::DrawCapsule(), DrawCapsule(), cDrawObj::DrawCylinder(), DrawDisk(), DrawPlane(), DrawPoint(), cDrawCharacter::DrawShapeBox(), cDrawCharacter::DrawShapeCapsule(), cDrawCharacter::DrawShapeCylinder(), cDrawCharacter::DrawShapeMesh(), cDrawCharacter::DrawShapeSphere(), cDrawObj::DrawSphere(), cDrawPerturb::DrawTorque(), cDrawSceneSimChar::DrawTrace(), cDrawKinTree::DrawTree(), and DrawTriangle().
UnbindCopyMeshProg()
void cDrawUtil::UnbindCopyMeshProg () static
Definition at line 845 of file DrawUtil.cpp.
 {
     gCopyMeshProg.Unbind();
 }
References gCopyMeshProg, and cShader::Unbind().
UnbindDefaultProg()
void cDrawUtil::UnbindDefaultProg () static
Definition at line 835 of file DrawUtil.cpp.
 {
     gDefaultProg.Unbind();
 }
References gDefaultProg, and cShader::Unbind().
Member Data Documentation
gBoxSolidMesh
std::unique_ptr< cDrawMesh > cDrawUtil::gBoxSolidMesh = nullptr static protected
Definition at line 120 of file DrawUtil.h.
Referenced by BuildMeshes(), and DrawBoxSolid().
gBoxWireMesh
std::unique_ptr< cDrawMesh > cDrawUtil::gBoxWireMesh = nullptr static protected
Definition at line 121 of file DrawUtil.h.
Referenced by BuildMeshes(), and DrawBoxWire().
gColor
tVector cDrawUtil::gColor = tVector::Ones() static protected
Definition at line 109 of file DrawUtil.h.
Referenced by LoadShaderUniforms(), and SetColor().
gConeMesh
std::unique_ptr< cDrawMesh > cDrawUtil::gConeMesh = nullptr static protected
Definition at line 128 of file DrawUtil.h.
Referenced by BuildMeshes(), and DrawConeSolidWire().
gConeWireSimpleMesh
std::unique_ptr< cDrawMesh > cDrawUtil::gConeWireSimpleMesh = nullptr static protected
Definition at line 129 of file DrawUtil.h.
Referenced by BuildMeshes(), and DrawConeWireSimple().
gCopyMeshProg
cShader cDrawUtil::gCopyMeshProg = cShader() static protected
Definition at line 112 of file DrawUtil.h.
Referenced by BindCopyMeshProg(), BuildShaders(), and UnbindCopyMeshProg().
gCopyProg
cShader cDrawUtil::gCopyProg = cShader() static protected
Definition at line 111 of file DrawUtil.h.
Referenced by BuildShaders(), and CopyTexture().
gCylinderMesh
std::unique_ptr< cDrawMesh > cDrawUtil::gCylinderMesh = nullptr static protected
Definition at line 126 of file DrawUtil.h.
Referenced by BuildMeshes(), DrawCylinderSolidWire(), and DrawTubeSolidWire().
gCylinderWireSimpleMesh
std::unique_ptr< cDrawMesh > cDrawUtil::gCylinderWireSimpleMesh = nullptr static protected
Definition at line 127 of file DrawUtil.h.
Referenced by BuildMeshes(), and DrawCylinderWireSimple().
gDefaultProg
cShader cDrawUtil::gDefaultProg = cShader() static protected
Definition at line 110 of file DrawUtil.h.
Referenced by BindDefaultProg(), BuildShaders(), and UnbindDefaultProg().
gDiskMesh
std::unique_ptr< cDrawMesh > cDrawUtil::gDiskMesh = nullptr static protected
Definition at line 124 of file DrawUtil.h.
Referenced by BuildMeshes(), DrawDisk(), and DrawHemisphere().
gEnableDraw
bool cDrawUtil::gEnableDraw = true static protected
Definition at line 108 of file DrawUtil.h.
Referenced by EnableDraw().
gLineMesh
std::unique_ptr< cDrawMesh > cDrawUtil::gLineMesh = nullptr static protected
Definition at line 118 of file DrawUtil.h.
Referenced by BuildMeshes(), and DrawLine().
gMatStackProj
cMatrixStack cDrawUtil::gMatStackProj = cMatrixStack(gMatStackSize) static protected
Definition at line 115 of file DrawUtil.h.
Referenced by InitDrawUtil(), LoadIdentityProj(), LoadMatrixProj(), LoadShaderUniforms(), MultMatrixProj(), PopMatrixProj(), and PushMatrixProj().
gMatStackView
cMatrixStack cDrawUtil::gMatStackView = cMatrixStack(gMatStackSize) static protected
Definition at line 114 of file DrawUtil.h.
Referenced by InitDrawUtil(), LoadIdentityView(), LoadMatrixView(), LoadShaderUniforms(), MultMatrixView(), PopMatrixView(), PushMatrixView(), Rotate(), Scale(), and Translate().
gPointMesh
std::unique_ptr< cDrawMesh > cDrawUtil::gPointMesh = nullptr static protected
Definition at line 117 of file DrawUtil.h.
Referenced by BuildMeshes(), and DrawPoint().
gQuadMesh
std::unique_ptr< cDrawMesh > cDrawUtil::gQuadMesh = nullptr static protected
Definition at line 119 of file DrawUtil.h.
Referenced by BuildMeshes(), and DrawQuad().
gSphereMesh
std::unique_ptr< cDrawMesh > cDrawUtil::gSphereMesh = nullptr static protected
Definition at line 122 of file DrawUtil.h.
Referenced by BuildMeshes(), DrawHemisphere(), and DrawSphere().
gSphereWireSimpleMesh
std::unique_ptr< cDrawMesh > cDrawUtil::gSphereWireSimpleMesh = nullptr static protected
Definition at line 123 of file DrawUtil.h.
Referenced by BuildMeshes(), DrawHemisphere(), and DrawSphere().
gTriangleMesh
std::unique_ptr< cDrawMesh > cDrawUtil::gTriangleMesh = nullptr static protected
Definition at line 125 of file DrawUtil.h.
Referenced by BuildMeshes(), and DrawTriangle().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/DrawUtil.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/DrawUtil.cpp