My Project: cSimCharacter Class Reference
cSimCharacter Class Reference
#include <SimCharacter.h>
Classes
struct tParams
Public Member Functions
cSimCharacter ()
virtual ~cSimCharacter ()
virtual bool Init (const std::shared_ptr< cWorld > &world, const tParams &params)
virtual void Clear ()
virtual void Reset ()
virtual void Update (double time_step)
virtual void PostUpdate (double time_step)
virtual tVector GetRootPos () const
virtual void GetRootRotation (tVector &out_axis, double &out_theta) const
virtual tQuaternion GetRootRotation () const
virtual tVector GetRootVel () const
virtual tVector GetRootAngVel () const
virtual const Eigen::MatrixXd & GetBodyDefs () const
virtual void SetRootPos (const tVector &pos)
virtual void SetRootRotation (const tVector &axis, double theta)
virtual void SetRootRotation (const tQuaternion &q)
virtual void SetRootTransform (const tVector &pos, const tQuaternion &rot)
virtual void SetRootVel (const tVector &vel)
virtual void SetRootAngVel (const tVector &ang_vel)
virtual tQuaternion CalcHeadingRot () const
virtual int GetNumBodyParts () const
virtual void SetPose (const Eigen::VectorXd &pose)
virtual void SetVel (const Eigen::VectorXd &vel)
virtual tVector CalcJointPos (int joint_id) const
virtual tVector CalcJointVel (int joint_id) const
virtual void CalcJointWorldRotation (int joint_id, tVector &out_axis, double &out_theta) const
virtual tQuaternion CalcJointWorldRotation (int joint_id) const
virtual tMatrix BuildJointWorldTrans (int joint_id) const
virtual tVector CalcCOM () const
virtual tVector CalcCOMVel () const
virtual void CalcAABB (tVector &out_min, tVector &out_max) const
virtual tVector GetSize () const
virtual const cSimBodyJoint & GetJoint (int joint_id) const
virtual cSimBodyJoint & GetJoint (int joint_id)
virtual const std::shared_ptr< cSimBodyLink > & GetBodyPart (int idx) const
virtual std::shared_ptr< cSimBodyLink > & GetBodyPart (int idx)
virtual tVector GetBodyPartPos (int idx) const
virtual tVector GetBodyPartVel (int idx) const
virtual const std::shared_ptr< cSimBodyLink > & GetRootPart () const
virtual std::shared_ptr< cSimBodyLink > GetRootPart ()
virtual void RegisterContacts (int contact_flags, int filter_flags)
virtual void UpdateContact (int contact_flags, int filter_flags)
virtual bool IsInContact () const
virtual bool IsInContact (int idx) const
virtual const tEigenArr< cContactManager::tContactPt > & GetContactPts (int idx) const
virtual const tEigenArr< cContactManager::tContactPt > & GetContactPts () const
virtual const cContactManager::tContactHandle & GetContactHandle () const
virtual bool HasFallen () const
virtual bool HasStumbled () const
virtual bool HasVelExploded (double vel_threshold=100.0) const
virtual bool IsValidBodyPart (int idx) const
virtual bool EnableBodyPartFallContact (int idx) const
virtual void SetBodyPartFallContact (int idx, bool enable)
virtual void SetController (std::shared_ptr< cCharController > ctrl)
virtual void RemoveController ()
virtual bool HasController () const
virtual const std::shared_ptr< cCharController > & GetController ()
virtual const std::shared_ptr< cCharController > & GetController () const
virtual void EnableController (bool enable)
virtual void ApplyForce (const tVector &force)
virtual void ApplyForce (const tVector &force, const tVector &local_pos)
virtual void ApplyTorque (const tVector &torque)
virtual void ClearForces ()
virtual void ApplyControlForces (const Eigen::VectorXd &tau)
virtual void PlayPossum ()
virtual tVector GetPartColor (int part_id) const
virtual double CalcTotalMass () const
virtual void SetLinearDamping (double damping)
virtual void SetAngularDamping (double damping)
virtual const std::shared_ptr< cWorld > & GetWorld () const
virtual const std::shared_ptr< cMultiBody > & GetMultiBody () const
virtual const std::vector< std::shared_ptr< btMultiBodyJointLimitConstraint > > & GetConstraints () const
virtual tVector GetPos () const
virtual void SetPos (const tVector &pos)
virtual void GetRotation (tVector &out_axis, double &out_theta) const
virtual tQuaternion GetRotation () const
virtual void SetRotation (const tVector &axis, double theta)
virtual void SetRotation (const tQuaternion &q)
virtual tMatrix GetWorldTransform () const
virtual tVector GetLinearVelocity () const
virtual tVector GetLinearVelocity (const tVector &local_pos) const
virtual void SetLinearVelocity (const tVector &vel)
virtual tVector GetAngularVelocity () const
virtual void SetAngularVelocity (const tVector &vel)
virtual short GetColGroup () const
virtual void SetColGroup (short col_group)
virtual short GetColMask () const
virtual void SetColMask (short col_mask)
Public Member Functions inherited from cCharacter
virtual ~cCharacter ()
virtual void SetID (int id)
virtual int GetID () const
virtual bool Init (const std::string &char_file, bool load_draw_shapes)
virtual int GetNumDof () const
virtual const Eigen::MatrixXd & GetJointMat () const
virtual int GetNumJoints () const
virtual const Eigen::VectorXd & GetPose () const
virtual const Eigen::VectorXd & GetPose0 () const
virtual void SetPose0 (const Eigen::VectorXd &pose)
virtual const Eigen::VectorXd & GetVel () const
virtual const Eigen::VectorXd & GetVel0 () const
virtual void SetVel0 (const Eigen::VectorXd &vel)
virtual int GetRootID () const
virtual void SetRootPos0 (const tVector &pose)
virtual void RotateRoot (const tQuaternion &rot)
virtual double CalcHeading () const
virtual tMatrix BuildOriginTrans () const
virtual int GetParamOffset (int joint_id) const
virtual int GetParamSize (int joint_id) const
virtual bool IsEndEffector (int joint_id) const
virtual int GetParentJoint (int joint_id) const
virtual double CalcJointChainLength (int joint_id)
virtual int CalcNumEndEffectors () const
virtual double GetJointDiffWeight (int joint_id) const
virtual bool WriteState (const std::string &file) const
virtual bool WriteState (const std::string &file, const tMatrix &root_trans) const
virtual bool ReadState (const std::string &file)
virtual bool LoadSkeleton (const Json::Value &root)
virtual void InitDefaultState ()
virtual bool HasDrawShapes () const
virtual const Eigen::MatrixXd & GetDrawShapeDefs () const
virtual const std::shared_ptr< cDrawMesh > & GetMesh (int i) const
virtual int GetNumMeshes () const
Public Member Functions inherited from cSimObj
virtual ~cSimObj ()
virtual tMatrix GetLocalTransform () const
virtual tVector WorldToLocalPos (const tVector &world_pos) const
virtual tVector LocalToWorldPos (const tVector &local_pos) const
virtual tMatrix3 GetLocalToWorldRotMat () const
virtual void RegisterContact ()
virtual void RegisterContact (int contact_flags, int filter_flags)
virtual eType GetType () const
virtual cShape::eShape GetShape () const
virtual const btCollisionShape * GetCollisionShape () const
Protected Member Functions
virtual bool LoadBodyDefs (const std::string &char_file, Eigen::MatrixXd &out_body_defs) const
virtual bool BuildSimBody (const tParams &params)
virtual bool BuildMultiBody (std::shared_ptr< cMultiBody > &out_body)
virtual bool BuildConstraints (std::shared_ptr< cMultiBody > &out_body)
virtual bool BuildBodyLinks ()
virtual btCollisionShape * BuildCollisionShape (const cShape::eShape shape, const tVector &shape_size)
virtual bool BuildJoints ()
virtual void BuildConsFactor (int joint_id, tVector &out_linear_factor, tVector &out_angular_factor) const
virtual void BuildRootConsFactor (cKinTree::eJointType joint_type, tVector &out_linear_factor, tVector &out_angular_factor) const
virtual bool FixedBase () const
virtual void RemoveFromWorld ()
virtual void ClearJointTorques ()
virtual void UpdateJoints ()
virtual void UpdateLinkPos ()
virtual void UpdateLinkVel ()
virtual short GetPartColGroup (int part_id) const
virtual short GetPartColMask (int part_id) const
virtual void BuildJointPose (int joint_id, Eigen::VectorXd &out_pose) const
virtual void BuildJointVel (int joint_id, Eigen::VectorXd &out_vel) const
virtual void BuildPose (Eigen::VectorXd &out_pose) const
virtual void BuildVel (Eigen::VectorXd &out_vel) const
virtual bool CheckFallContact () const
virtual const btCollisionObject * GetCollisionObject () const
virtual btCollisionObject * GetCollisionObject ()
Protected Member Functions inherited from cCharacter
cCharacter ()
virtual void ResetParams ()
virtual bool ParseState (const Json::Value &root, Eigen::VectorXd &out_state) const
virtual std::string BuildStateJson (const Eigen::VectorXd &pose, const Eigen::VectorXd &vel) const
virtual bool LoadDrawShapeDefs (const std::string &char_file, Eigen::MatrixXd &out_draw_defs) const
virtual bool LoadMeshes (const std::string &char_file, std::vector< std::shared_ptr< cDrawMesh >> &out_meshes) const
Protected Member Functions inherited from cSimObj
cSimObj ()
Protected Attributes
std::shared_ptr< cMultiBody > mMultBody
std::vector< std::shared_ptr< cSimBodyLink > > mBodyParts
tEigenArr< cSimBodyJoint > mJoints
std::vector< std::shared_ptr< btMultiBodyJointLimitConstraint > > mCons
double mFriction
Eigen::MatrixXd mBodyDefs
std::shared_ptr< cCharController > mController
tQuaternion mInvRootAttachRot
btAlignedObjectArray< btVector3 > mVecBuffer0
btAlignedObjectArray< btVector3 > mVecBuffer1
btAlignedObjectArray< btQuaternion > mRotBuffer
Protected Attributes inherited from cCharacter
int mID
Eigen::MatrixXd mJointMat
Eigen::VectorXd mPose
Eigen::VectorXd mVel
Eigen::VectorXd mPose0
Eigen::VectorXd mVel0
Eigen::MatrixXd mDrawShapeDefs
std::vector< std::shared_ptr< cDrawMesh > > mMeshes
Protected Attributes inherited from cSimObj
std::shared_ptr< cWorld > mWorld
std::unique_ptr< btCollisionShape > mColShape
cContactManager::tContactHandle mContactHandle
bool mEnableContactFall
eType mType
short mColGroup
short mColMask
Additional Inherited Members
Public Types inherited from cSimObj
enum eType { eTypeDynamic, eTypeStatic, eTypeMax }
Static Public Attributes inherited from cCharacter
static const std::string gSkeletonKey = "Skeleton"
Detailed Description
Definition at line 13 of file SimCharacter.h.
Constructor & Destructor Documentation
cSimCharacter()
cSimCharacter::cSimCharacter ()
Definition at line 24 of file SimCharacter.cpp.
 {
     mFriction = 0.9;
     mEnableContactFall = true;
 }
References cSimObj::mEnableContactFall, and mFriction.
~cSimCharacter()
cSimCharacter::~cSimCharacter () virtual
Definition at line 30 of file SimCharacter.cpp.
 {
     RemoveFromWorld();
 }
References RemoveFromWorld().
Member Function Documentation
ApplyControlForces()
void cSimCharacter::ApplyControlForces (const Eigen::VectorXd & tau) virtual
Definition at line 698 of file SimCharacter.cpp.
 {
     assert(tau.size() == GetNumDof());
     for (int j = 1; j < GetNumJoints(); ++j)
     {
         cSimBodyJoint& joint = GetJoint(j);
         if (joint.IsValid())
         {
             int param_offset = GetParamOffset(j);
             int param_size = GetParamSize(j);
             if (param_size > 0)
             {
                 Eigen::VectorXd curr_tau = tau.segment(param_offset, param_size);
                 joint.AddTau(curr_tau);
             }
         }
     }
 }
References cSimBodyJoint::AddTau(), GetJoint(), cCharacter::GetNumDof(), cCharacter::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), and cSimBodyJoint::IsValid().
Referenced by cExpPDController::ApplyControlForces(), cPDController::ApplyControlForces(), and cDeepMimicCharController::UpdateApplyTau().
ApplyForce() [1/2]
void cSimCharacter::ApplyForce (const tVector & force) virtual
Implements cSimObj.
Definition at line 660 of file SimCharacter.cpp.
 {
     ApplyForce(force, tVector::Zero());
 }
ApplyForce() [2/2]
void cSimCharacter::ApplyForce (const tVector & force, const tVector & local_pos) virtual
Implements cSimObj.
Definition at line 665 of file SimCharacter.cpp.
 {
     const auto& root_body = GetRootPart();
     const auto& joint = GetJoint(GetRootID());
     tVector world_pos = local_pos;
     world_pos[3] = 1;
     tMatrix joint_to_world = joint.BuildWorldTrans();
     world_pos = joint_to_world * world_pos;
     tVector body_local = root_body->WorldToLocalPos(world_pos);
     root_body->ApplyForce(force, body_local);
 }
References GetJoint(), cCharacter::GetRootID(), and GetRootPart().
ApplyTorque()
void cSimCharacter::ApplyTorque (const tVector & torque) virtual
Implements cSimObj.
Definition at line 679 of file SimCharacter.cpp.
 {
     const auto& root_body = GetRootPart();
     root_body->ApplyTorque(torque);
 }
References GetRootPart().
BuildBodyLinks()
bool cSimCharacter::BuildBodyLinks () protected virtual
Definition at line 984 of file SimCharacter.cpp.
 {
     int num_joints = GetNumJoints();
     mBodyParts.clear();
     mBodyParts.resize(num_joints);
     for (int j = 0; j < num_joints; ++j)
     {
         std::shared_ptr<cSimBodyLink>& curr_part = mBodyParts[j];
         cSimBodyLink::tParams params;
         params.mMass = cKinTree::GetBodyMass(mBodyDefs, j);
         params.mJointID = j;
         curr_part = std::shared_ptr<cSimBodyLink>(new cSimBodyLink());
         short col_group = GetPartColGroup(j);
         short col_mask = GetPartColMask(j);
         curr_part->SetColGroup(col_group);
         curr_part->SetColMask(col_mask);
         curr_part->Init(mWorld, mMultBody, params);
     }
     return true;
 }
References cKinTree::GetBodyMass(), cCharacter::GetNumJoints(), GetPartColGroup(), GetPartColMask(), mBodyDefs, mBodyParts, cSimBodyLink::tParams::mJointID, cSimBodyLink::tParams::mMass, mMultBody, and cSimObj::mWorld.
Referenced by BuildSimBody().
BuildCollisionShape()
btCollisionShape * cSimCharacter::BuildCollisionShape (const cShape::eShape shape, const tVector & shape_size) protected virtual
Definition at line 1011 of file SimCharacter.cpp.
 {
     btCollisionShape* col_shape = nullptr;
     switch (shape)
     {
     case cShape::eShapeBox:
         col_shape = mWorld->BuildBoxShape(shape_size);
         break;
     case cShape::eShapeCapsule:
         col_shape = mWorld->BuildCapsuleShape(0.5 * shape_size[0], shape_size[1]);
         break;
     case cShape::eShapeSphere:
         col_shape = mWorld->BuildSphereShape(0.5 * shape_size[0]);
         break;
     case cShape::eShapeCylinder:
         col_shape = mWorld->BuildCylinderShape(0.5 * shape_size[0], shape_size[1]);
         break;
     default:
         printf("Unsupported body link shape\n");
         assert(false);
         break;
     }
     return col_shape;
 }
References cShape::eShapeBox, cShape::eShapeCapsule, cShape::eShapeCylinder, cShape::eShapeSphere, and cSimObj::mWorld.
Referenced by BuildMultiBody().
BuildConsFactor()
void cSimCharacter::BuildConsFactor (int joint_id, tVector & out_linear_factor, tVector & out_angular_factor) const protected virtual
Definition at line 1088 of file SimCharacter.cpp.
 {
     cKinTree::eJointType joint_type = cKinTree::GetJointType(mJointMat, joint_id);
     bool is_root = cKinTree::IsRoot(mJointMat, joint_id);
     out_linear_factor.setOnes();
     out_angular_factor.setOnes();
     if (is_root)
     {
         BuildRootConsFactor(joint_type, out_linear_factor, out_angular_factor);
     }
 }
References BuildRootConsFactor(), cKinTree::GetJointType(), cKinTree::IsRoot(), and cCharacter::mJointMat.
BuildConstraints()
bool cSimCharacter::BuildConstraints (std::shared_ptr< cMultiBody > & out_body) protected virtual
Definition at line 948 of file SimCharacter.cpp.
 {
     double world_scale = mWorld->GetScale();
     for (int j = 0; j < GetNumJoints(); ++j)
     {
         cKinTree::eJointType joint_type = cKinTree::GetJointType(mJointMat, j);
         if (joint_type == cKinTree::eJointTypeRevolute || joint_type == cKinTree::eJointTypePrismatic)
         {
             tVector lim_low = cKinTree::GetJointLimLow(mJointMat, j);
             tVector lim_high = cKinTree::GetJointLimHigh(mJointMat, j);
             if (lim_low[0] <= lim_high[1])
             {
                 if (joint_type == cKinTree::eJointTypePrismatic)
                 {
                     lim_low *= world_scale;
                     lim_high *= world_scale;
                 }
                 auto joint_cons = std::shared_ptr<btMultiBodyJointLimitConstraint>(new btMultiBodyJointLimitConstraint(mMultBody.get(), j, lim_low[0], lim_high[0]));
                 joint_cons->finalizeMultiDof();
                 mCons.push_back(joint_cons);
             }
         }
     }
     return true;
 }
References cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::GetJointLimHigh(), cKinTree::GetJointLimLow(), cKinTree::GetJointType(), cCharacter::GetNumJoints(), mCons, cCharacter::mJointMat, mMultBody, and cSimObj::mWorld.
Referenced by BuildSimBody().
BuildJointPose()
void cSimCharacter::BuildJointPose (int joint_id, Eigen::VectorXd & out_pose) const protected virtual
Definition at line 1428 of file SimCharacter.cpp.
 {
     bool is_root = cKinTree::IsRoot(mJointMat, joint_id);
     if (is_root)
     {
         int param_size = GetParamSize(joint_id);
         out_pose = Eigen::VectorXd::Zero(param_size);
         assert(out_pose.size() == cKinTree::gRootDim);
         tVector root_pos = GetRootPos();
         tQuaternion root_rot = GetRootRotation();
         out_pose.segment(0, cKinTree::gPosDim) = root_pos.segment(0, cKinTree::gPosDim);
         out_pose(cKinTree::gPosDim) = root_rot.w();
         out_pose(cKinTree::gPosDim + 1) = root_rot.x();
         out_pose(cKinTree::gPosDim + 2) = root_rot.y();
         out_pose(cKinTree::gPosDim + 3) = root_rot.z();
     }
     else
     {
         const cSimBodyJoint& joint = GetJoint(joint_id);
         joint.BuildPose(out_pose);
     }
 }
References cSimBodyJoint::BuildPose(), GetJoint(), cCharacter::GetParamSize(), GetRootPos(), GetRootRotation(), cKinTree::gPosDim, cKinTree::gRootDim, cKinTree::IsRoot(), and cCharacter::mJointMat.
Referenced by BuildPose().
BuildJoints()
bool cSimCharacter::BuildJoints () protected virtual
Definition at line 1036 of file SimCharacter.cpp.
 {
     int num_joints = GetNumJoints();
     mJoints.clear();
     mJoints.resize(num_joints);
     for (int j = 0; j < num_joints; ++j)
     {
         bool is_root = cKinTree::IsRoot(mJointMat, j);
         cSimBodyJoint& curr_joint = GetJoint(j);
         cSimBodyJoint::tParams joint_params;
         joint_params.mID = j;
         joint_params.mLimLow = cKinTree::GetJointLimLow(mJointMat, j);
         joint_params.mLimHigh = cKinTree::GetJointLimHigh(mJointMat, j);
         joint_params.mTorqueLimit = (is_root) ? 0 : cKinTree::GetTorqueLimit(mJointMat, j);
         joint_params.mForceLimit = (is_root) ? 0 : cKinTree::GetForceLimit(mJointMat, j);
         tVector child_attach_pt = cKinTree::GetBodyAttachPt(mBodyDefs, j);
         tVector child_attach_theta = cKinTree::GetBodyAttachTheta(mBodyDefs, j);
         tMatrix child_to_joint = cMathUtil::TranslateMat(child_attach_pt) * cMathUtil::RotateMat(child_attach_theta);
         tMatrix joint_to_child = cMathUtil::InvRigidMat(child_to_joint);
         joint_params.mChildRot = cMathUtil::RotMatToQuaternion(joint_to_child);
         joint_params.mChildPos = cMathUtil::GetRigidTrans(joint_to_child);
         std::shared_ptr<cSimBodyLink> child_link = GetBodyPart(j);
         std::shared_ptr<cSimBodyLink> parent_link = nullptr;
         int parent_id = cKinTree::GetParent(mJointMat, j);
         if (parent_id != gInvalidIdx)
         {
             tVector joint_attach_pt = cKinTree::GetAttachPt(mJointMat, j);
             tVector joint_attach_theta = cKinTree::GetAttachTheta(mJointMat, j);
             tVector parent_attach_pt = cKinTree::GetBodyAttachPt(mBodyDefs, parent_id);
             tVector parent_attach_theta = cKinTree::GetBodyAttachTheta(mBodyDefs, parent_id);
             tMatrix parent_to_parent_joint = cMathUtil::TranslateMat(parent_attach_pt) * cMathUtil::RotateMat(parent_attach_theta);
             tMatrix joint_to_parent_joint = cMathUtil::TranslateMat(joint_attach_pt) * cMathUtil::RotateMat(joint_attach_theta);
             tMatrix joint_to_parent = cMathUtil::InvRigidMat(parent_to_parent_joint) * joint_to_parent_joint;
             parent_link = GetBodyPart(parent_id);
             joint_params.mParentRot = cMathUtil::RotMatToQuaternion(joint_to_parent);
             joint_params.mParentPos = cMathUtil::GetRigidTrans(joint_to_parent);
         }
         curr_joint.Init(mWorld, mMultBody, parent_link, child_link, joint_params);
     }
     return true;
 }
References cKinTree::GetAttachPt(), cKinTree::GetAttachTheta(), cKinTree::GetBodyAttachPt(), cKinTree::GetBodyAttachTheta(), GetBodyPart(), cKinTree::GetForceLimit(), GetJoint(), cKinTree::GetJointLimHigh(), cKinTree::GetJointLimLow(), cCharacter::GetNumJoints(), cKinTree::GetParent(), cMathUtil::GetRigidTrans(), cKinTree::GetTorqueLimit(), gInvalidIdx, cSimBodyJoint::Init(), cMathUtil::InvRigidMat(), cKinTree::IsRoot(), mBodyDefs, cSimBodyJoint::tParams::mChildPos, cSimBodyJoint::tParams::mChildRot, cSimBodyJoint::tParams::mForceLimit, cSimBodyJoint::tParams::mID, cCharacter::mJointMat, mJoints, cSimBodyJoint::tParams::mLimHigh, cSimBodyJoint::tParams::mLimLow, mMultBody, cSimBodyJoint::tParams::mParentPos, cSimBodyJoint::tParams::mParentRot, cSimBodyJoint::tParams::mTorqueLimit, cSimObj::mWorld, cMathUtil::RotateMat(), cMathUtil::RotMatToQuaternion(), and cMathUtil::TranslateMat().
Referenced by BuildSimBody().
BuildJointVel()
void cSimCharacter::BuildJointVel (int joint_id, Eigen::VectorXd & out_vel) const protected virtual
Definition at line 1453 of file SimCharacter.cpp.
 {
     bool is_root = cKinTree::IsRoot(mJointMat, joint_id);
     if (is_root)
     {
         int param_size = GetParamSize(joint_id);
         out_vel = Eigen::VectorXd::Zero(param_size);
         assert(out_vel.size() == cKinTree::gRootDim);
         tVector root_vel = GetRootVel();
         tVector ang_vel = GetRootAngVel();
         out_vel.segment(0, cKinTree::gPosDim) = root_vel.segment(0, cKinTree::gPosDim);
         out_vel.segment(cKinTree::gPosDim, cKinTree::gRotDim) = ang_vel.segment(0, cKinTree::gRotDim);
     }
     else
     {
         const cSimBodyJoint& joint = GetJoint(joint_id);
         joint.BuildVel(out_vel);
     }
 }
References cSimBodyJoint::BuildVel(), GetJoint(), cCharacter::GetParamSize(), GetRootAngVel(), GetRootVel(), cKinTree::gPosDim, cKinTree::gRootDim, cKinTree::gRotDim, cKinTree::IsRoot(), and cCharacter::mJointMat.
Referenced by BuildVel().
BuildJointWorldTrans()
tMatrix cSimCharacter::BuildJointWorldTrans (int joint_id) const virtual
Reimplemented from cCharacter.
Definition at line 1175 of file SimCharacter.cpp.
 {
     const cSimBodyJoint& joint = GetJoint(joint_id);
     if (joint.IsValid())
     {
         return joint.BuildWorldTrans();
     }
     else
     {
         return cCharacter::BuildJointWorldTrans(joint_id);
     }
 }
References cCharacter::BuildJointWorldTrans(), cSimBodyJoint::BuildWorldTrans(), GetJoint(), and cSimBodyJoint::IsValid().
BuildMultiBody()
bool cSimCharacter::BuildMultiBody (std::shared_ptr< cMultiBody > & out_body) protected virtual
Definition at line 789 of file SimCharacter.cpp.
 {
     bool succ = true;
     double world_scale = mWorld->GetScale();
     int num_joints = GetNumJoints();
     bool fixed_base = FixedBase();
     btVector3 base_intertia = btVector3(0, 0, 0);
     btScalar base_mass = 0;
     mMultBody = std::shared_ptr<cMultiBody>(new cMultiBody(num_joints, base_mass, base_intertia, fixed_base, false));
     btTransform base_trans;
     base_trans.setIdentity();
     mMultBody->setBaseWorldTransform(base_trans);
     for (int j = 0; j < num_joints; ++j)
     {
         cShape::eShape body_shape = cKinTree::GetBodyShape(mBodyDefs, j);
         tVector body_size = cKinTree::GetBodySize(mBodyDefs, j);
         double mass = cKinTree::GetBodyMass(mBodyDefs, j);
         cKinTree::eJointType joint_type = cKinTree::GetJointType(mJointMat, j);
         int parent_joint = cKinTree::GetParent(mJointMat, j);
         bool is_root = cKinTree::IsRoot(mJointMat, j);
         btCollisionShape* col_shape = BuildCollisionShape(body_shape, body_size);
         btVector3 inertia = btVector3(0, 0, 0);
         col_shape->calculateLocalInertia(static_cast<btScalar>(mass), inertia);
         // arg so many transforms...
         tQuaternion this_to_parent = cMathUtil::EulerToQuaternion(cKinTree::GetAttachTheta(mJointMat, j));
         tQuaternion body_to_this = cMathUtil::EulerToQuaternion(cKinTree::GetBodyAttachTheta(mBodyDefs, j));
         tQuaternion this_to_body = body_to_this.inverse();
         tQuaternion parent_body_to_parent = tQuaternion::Identity();
         if (parent_joint != gInvalidIdx)
         {
             parent_body_to_parent = cMathUtil::EulerToQuaternion(cKinTree::GetBodyAttachTheta(mBodyDefs, parent_joint));
         }
         tQuaternion parent_to_parent_body = parent_body_to_parent.inverse();
         tQuaternion body_to_parent_body = parent_to_parent_body * this_to_parent * body_to_this;
         tQuaternion parent_body_to_body = body_to_parent_body.inverse();
         // parent body attachment point in body's coordinate frame
         tVector parent_body_attach_pt = tVector::Zero();
         if (parent_joint != gInvalidIdx)
         {
             parent_body_attach_pt = cKinTree::GetBodyAttachPt(mBodyDefs, parent_joint);
         }
         parent_body_attach_pt = cMathUtil::QuatRotVec(parent_to_parent_body, parent_body_attach_pt);
         tVector joint_attach_pt = cKinTree::GetAttachPt(mJointMat, j);
         tVector body_attach_pt = cKinTree::GetBodyAttachPt(mBodyDefs, j);
         joint_attach_pt = cMathUtil::QuatRotVec(parent_to_parent_body, joint_attach_pt);
         joint_attach_pt -= parent_body_attach_pt;
         body_attach_pt = cMathUtil::QuatRotVec(body_to_this.inverse(), body_attach_pt);
         btTransform parent_body_to_body_trans = btTransform::getIdentity();
         parent_body_to_body_trans.setRotation(btQuaternion(parent_body_to_body.x(), parent_body_to_body.y(), parent_body_to_body.z(), parent_body_to_body.w()));
         bool disable_parent_collision = true;
         if (is_root && !fixed_base)
         {
             mMultBody->setupFixed(j, static_cast<btScalar>(mass), inertia, parent_joint,
                 parent_body_to_body_trans.getRotation(),
                 world_scale * btVector3(joint_attach_pt[0], joint_attach_pt[1], joint_attach_pt[2]),
                 world_scale * btVector3(body_attach_pt[0], body_attach_pt[1], body_attach_pt[2]),
                 disable_parent_collision);
         }
         else
         {
             switch (joint_type)
             {
             case cKinTree::eJointTypeRevolute:
             {
                 tVector axis = tVector(0, 0, 1, 0);
                 axis = cMathUtil::QuatRotVec(this_to_body, axis);
                 mMultBody->setupRevolute(j, static_cast<btScalar>(mass), inertia, parent_joint,
                     parent_body_to_body_trans.getRotation(),
                     btVector3(axis[0], axis[1], axis[2]),
                     world_scale * btVector3(joint_attach_pt[0], joint_attach_pt[1], joint_attach_pt[2]),
                     world_scale * btVector3(body_attach_pt[0], body_attach_pt[1], body_attach_pt[2]),
                     disable_parent_collision);
             }
             break;
             case cKinTree::eJointTypePlanar:
             {
                 tVector offset = parent_body_attach_pt + joint_attach_pt
                                 + cMathUtil::QuatRotVec(body_to_parent_body, body_attach_pt);
                 tVector axis = tVector(0, 0, 1, 0);
                 axis = cMathUtil::QuatRotVec(this_to_body, axis);
                 mMultBody->setupPlanar(j, static_cast<btScalar>(mass), inertia, parent_joint,
                     parent_body_to_body_trans.getRotation(),
                     btVector3(axis[0], axis[1], axis[2]),
                     world_scale * btVector3(offset[0], offset[1], offset[2]),
                     disable_parent_collision);
             }
             break;
             case cKinTree::eJointTypePrismatic:
             {
                 tVector axis = tVector(1, 0, 0, 0);
                 axis = cMathUtil::QuatRotVec(this_to_body, axis);
                 mMultBody->setupPrismatic(j, static_cast<btScalar>(mass), inertia, parent_joint,
                     parent_body_to_body_trans.getRotation(),
                     btVector3(axis[0], axis[1], axis[2]),
                     world_scale * btVector3(joint_attach_pt[0], joint_attach_pt[1], joint_attach_pt[2]),
                     world_scale * btVector3(body_attach_pt[0], body_attach_pt[1], body_attach_pt[2]),
                     disable_parent_collision);
             }
             break;
             case cKinTree::eJointTypeFixed:
             {
                 mMultBody->setupFixed(j, static_cast<btScalar>(mass), inertia, parent_joint,
                     parent_body_to_body_trans.getRotation(),
                     world_scale * btVector3(joint_attach_pt[0], joint_attach_pt[1], joint_attach_pt[2]),
                     world_scale * btVector3(body_attach_pt[0], body_attach_pt[1], body_attach_pt[2]),
                     disable_parent_collision);
             }
             break;
             case cKinTree::eJointTypeSpherical:
             {
                 mMultBody->setupSpherical(j, static_cast<btScalar>(mass), inertia, parent_joint,
                     parent_body_to_body_trans.getRotation(),
                     world_scale * btVector3(joint_attach_pt[0], joint_attach_pt[1], joint_attach_pt[2]),
                     world_scale * btVector3(body_attach_pt[0], body_attach_pt[1], body_attach_pt[2]),
                     disable_parent_collision);
             }
             break;
             default:
                 printf("Unsupported joint type");
                 assert(false);
                 break;
             }
         }
         btMultiBodyLinkCollider* col_obj = new btMultiBodyLinkCollider(mMultBody.get(), j);
         col_obj->setCollisionShape(col_shape);
         btTransform col_obj_trans;
         col_obj_trans.setIdentity();
         col_obj->setWorldTransform(col_obj_trans);
         col_obj->setFriction(mFriction);
         int collisionFilterGroup = GetPartColGroup(j);
         int collisionFilterMask = GetPartColMask(j);
         mWorld->AddCollisionObject(col_obj, collisionFilterGroup, collisionFilterMask);
         mMultBody->getLink(j).m_collider = col_obj;
     }
     mMultBody->finalizeMultiDof();
     return succ;
 }
References BuildCollisionShape(), cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, cMathUtil::EulerToQuaternion(), FixedBase(), cKinTree::GetAttachPt(), cKinTree::GetAttachTheta(), cKinTree::GetBodyAttachPt(), cKinTree::GetBodyAttachTheta(), cKinTree::GetBodyMass(), cKinTree::GetBodyShape(), cKinTree::GetBodySize(), cKinTree::GetJointType(), cCharacter::GetNumJoints(), cKinTree::GetParent(), GetPartColGroup(), GetPartColMask(), gInvalidIdx, cKinTree::IsRoot(), mBodyDefs, mFriction, cCharacter::mJointMat, mMultBody, cSimObj::mWorld, and cMathUtil::QuatRotVec().
Referenced by BuildSimBody().
BuildPose()
void cSimCharacter::BuildPose (Eigen::VectorXd & out_pose) const protected virtual
Definition at line 1474 of file SimCharacter.cpp.
 {
     int num_joints = GetNumJoints();
     int num_dof = cKinTree::GetNumDof(mJointMat);
     out_pose.resize(num_dof);
     for (int j = 0; j < num_joints; ++j)
     {
         Eigen::VectorXd joint_pose;
         BuildJointPose(j, joint_pose);
         int param_offset = GetParamOffset(j);
         int param_size = GetParamSize(j);
         assert(joint_pose.size() == param_size);
         out_pose.segment(param_offset, param_size) = joint_pose;
     }
 }
References BuildJointPose(), cKinTree::GetNumDof(), cCharacter::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), and cCharacter::mJointMat.
Referenced by PostUpdate().
BuildRootConsFactor()
void cSimCharacter::BuildRootConsFactor (cKinTree::eJointType joint_type, tVector & out_linear_factor, tVector & out_angular_factor) const protected virtual
Definition at line 1101 of file SimCharacter.cpp.
 {
     out_linear_factor = tVector::Ones();
     out_angular_factor = tVector::Ones();
     switch (joint_type)
     {
     case cKinTree::eJointTypeRevolute:
         out_linear_factor = tVector::Zero();
         out_angular_factor = tVector(0, 0, 1, 0);
         break;
     case cKinTree::eJointTypePlanar:
         out_linear_factor = tVector(1, 1, 0, 0);
         out_angular_factor = tVector(0, 0, 1, 0);
         break;
     case cKinTree::eJointTypePrismatic:
         out_linear_factor = tVector(0, 0, 1, 0);
         out_angular_factor = tVector::Zero();
         break;
     case cKinTree::eJointTypeFixed:
         out_linear_factor = tVector::Zero();
         out_angular_factor = tVector::Zero();
         break;
     case cKinTree::eJointTypeNone:
         out_linear_factor = tVector::Ones();
         out_angular_factor = tVector::Ones();
         break;
     case cKinTree::eJointTypeSpherical:
         out_linear_factor = tVector::Zero();
         out_angular_factor = tVector(1, 1, 1, 0);
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References cKinTree::eJointTypeFixed, cKinTree::eJointTypeNone, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, and cKinTree::eJointTypeSpherical.
Referenced by BuildConsFactor().
BuildSimBody()
bool cSimCharacter::BuildSimBody (const tParams & params) protected virtual
Definition at line 765 of file SimCharacter.cpp.
 {
     bool succ = true;
     succ = LoadBodyDefs(params.mCharFile, mBodyDefs);
     if (succ)
     {
         mInvRootAttachRot = cMathUtil::EulerToQuaternion(cKinTree::GetAttachTheta(mJointMat, GetRootID())).inverse();
         succ &= BuildMultiBody(mMultBody);
         succ &= BuildConstraints(mMultBody);
         succ &= BuildBodyLinks();
         succ &= BuildJoints();
         mWorld->AddCharacter(*this);
         mVecBuffer0.resize(mMultBody->getNumLinks() + 1);
         mVecBuffer1.resize(mMultBody->getNumLinks() + 1);
         mRotBuffer.resize(mMultBody->getNumLinks() + 1);
     }
     return succ;
 }
References BuildBodyLinks(), BuildConstraints(), BuildJoints(), BuildMultiBody(), cMathUtil::EulerToQuaternion(), cKinTree::GetAttachTheta(), cCharacter::GetRootID(), LoadBodyDefs(), mBodyDefs, cSimCharacter::tParams::mCharFile, mInvRootAttachRot, cCharacter::mJointMat, mMultBody, mRotBuffer, mVecBuffer0, mVecBuffer1, and cSimObj::mWorld.
Referenced by Init().
BuildVel()
void cSimCharacter::BuildVel (Eigen::VectorXd & out_vel) const protected virtual
Definition at line 1491 of file SimCharacter.cpp.
 {
     int num_joints = GetNumJoints();
     int num_dof = cKinTree::GetNumDof(mJointMat);
     out_vel.resize(num_dof);
     for (int j = 0; j < num_joints; ++j)
     {
         Eigen::VectorXd joint_vel;
         BuildJointVel(j, joint_vel);
         int param_offset = GetParamOffset(j);
         int param_size = GetParamSize(j);
         assert(joint_vel.size() == param_size);
         out_vel.segment(param_offset, param_size) = joint_vel;
     }
 }
References BuildJointVel(), cKinTree::GetNumDof(), cCharacter::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), and cCharacter::mJointMat.
Referenced by PostUpdate().
CalcAABB()
void cSimCharacter::CalcAABB (tVector & out_min, tVector & out_max) const virtual
Reimplemented from cCharacter.
Definition at line 438 of file SimCharacter.cpp.
 {
     out_min[0] = std::numeric_limits<double>::infinity();
     out_min[1] = std::numeric_limits<double>::infinity();
     out_min[2] = std::numeric_limits<double>::infinity();
     out_max[0] = -std::numeric_limits<double>::infinity();
     out_max[1] = -std::numeric_limits<double>::infinity();
     out_max[2] = -std::numeric_limits<double>::infinity();
     for (int i = 0; i < GetNumBodyParts(); ++i)
     {
         if (IsValidBodyPart(i))
         {
             const auto& part = GetBodyPart(i);
             tVector curr_min = tVector::Zero();
             tVector curr_max = tVector::Zero();
             part->CalcAABB(curr_min, curr_max);
             out_min = out_min.cwiseMin(curr_min);
             out_max = out_max.cwiseMax(curr_max);
         }
     }
 }
References GetBodyPart(), GetNumBodyParts(), and IsValidBodyPart().
Referenced by GetSize().
CalcCOM()
tVector cSimCharacter::CalcCOM () const virtual
Reimplemented from cSimObj.
Definition at line 398 of file SimCharacter.cpp.
 {
     tVector com = tVector::Zero();
     double total_mass = 0;
     for (int i = 0; i < static_cast<int>(mBodyParts.size()); ++i)
     {
         if (IsValidBodyPart(i))
         {
             const auto& part = mBodyParts[i];
             double mass = part->GetMass();
             tVector curr_com = part->GetPos();
             com += mass * curr_com;
             total_mass += mass;
         }
     }
     com /= total_mass;
     return com;
 }
References IsValidBodyPart(), and mBodyParts.
Referenced by cSceneImitate::CalcRewardImitate(), cDrawSimCharacter::DrawCoM(), and cDeepMimicCharController::HandleNewAction().
CalcCOMVel()
tVector cSimCharacter::CalcCOMVel () const virtual
Reimplemented from cSimObj.
Definition at line 418 of file SimCharacter.cpp.
 {
     tVector com_vel = tVector::Zero();
     double total_mass = 0;
     for (int i = 0; i < static_cast<int>(mBodyParts.size()); ++i)
     {
         if (IsValidBodyPart(i))
         {
             const auto& part = mBodyParts[i];
             double mass = part->GetMass();
             tVector curr_vel = part->GetLinearVelocity();
             com_vel += mass * curr_vel;
             total_mass += mass;
         }
     }
     com_vel /= total_mass;
     return com_vel;
 }
References IsValidBodyPart(), and mBodyParts.
Referenced by cSceneImitate::CalcRewardImitate(), and cDrawSimCharacter::DrawCoM().
CalcHeadingRot()
tQuaternion cSimCharacter::CalcHeadingRot () const virtual
Reimplemented from cCharacter.
Definition at line 216 of file SimCharacter.cpp.
 {
     tVector ref_dir = tVector(1, 0, 0, 0);
     tQuaternion root_rot = GetRootRotation();
     tVector rot_dir = cMathUtil::QuatRotVec(root_rot, ref_dir);
     double heading = std::atan2(-rot_dir[2], rot_dir[0]);
     return cMathUtil::AxisAngleToQuaternion(tVector(0, 1, 0, 0), heading);
 }
References cMathUtil::AxisAngleToQuaternion(), GetRootRotation(), and cMathUtil::QuatRotVec().
CalcJointPos()
tVector cSimCharacter::CalcJointPos (int joint_id) const virtual
Reimplemented from cCharacter.
Definition at line 308 of file SimCharacter.cpp.
 {
     const cSimBodyJoint& joint = GetJoint(joint_id);
     tVector pos;
     if (joint.IsValid())
     {
         pos = joint.CalcWorldPos();
     }
     else
     {
         int parent_id = cKinTree::GetParent(mJointMat, joint_id);
         assert(parent_id != cKinTree::gInvalidJointID);
         assert(IsValidBodyPart(parent_id));
         tVector attach_pt = cKinTree::GetAttachPt(mJointMat, joint_id);
         tVector part_attach_pt = cKinTree::GetBodyAttachPt(mBodyDefs, parent_id);
         attach_pt -= part_attach_pt;
         const auto& parent_part = GetBodyPart(parent_id);
         pos = parent_part->LocalToWorldPos(attach_pt);
     }
     return pos;
 }
References cSimBodyJoint::CalcWorldPos(), cKinTree::GetAttachPt(), cKinTree::GetBodyAttachPt(), GetBodyPart(), GetJoint(), cKinTree::GetParent(), cKinTree::gInvalidJointID, cSimBodyJoint::IsValid(), IsValidBodyPart(), mBodyDefs, and cCharacter::mJointMat.
Referenced by cSceneImitate::CalcRewardImitate().
CalcJointVel()
tVector cSimCharacter::CalcJointVel (int joint_id) const virtual
Reimplemented from cCharacter.
Definition at line 333 of file SimCharacter.cpp.
 {
     const cSimBodyJoint& joint = GetJoint(joint_id);
     tVector vel;
     if (joint.IsValid())
     {
         vel = joint.CalcWorldVel();
     }
     else
     {
         int parent_id = cKinTree::GetParent(mJointMat, joint_id);
         assert(parent_id != cKinTree::gInvalidJointID);
         assert(IsValidBodyPart(parent_id));
         tVector attach_pt = cKinTree::GetAttachPt(mJointMat, joint_id);
         tVector part_attach_pt = cKinTree::GetBodyAttachPt(mBodyDefs, parent_id);
         attach_pt -= part_attach_pt;
         const auto& parent_part = GetBodyPart(parent_id);
         vel = parent_part->GetLinearVelocity(attach_pt);
     }
     return vel;
 }
References cSimBodyJoint::CalcWorldVel(), cKinTree::GetAttachPt(), cKinTree::GetBodyAttachPt(), GetBodyPart(), GetJoint(), cKinTree::GetParent(), cKinTree::gInvalidJointID, cSimBodyJoint::IsValid(), IsValidBodyPart(), mBodyDefs, and cCharacter::mJointMat.
CalcJointWorldRotation() [1/2]
tQuaternion cSimCharacter::CalcJointWorldRotation (int joint_id) const virtual
Reimplemented from cCharacter.
Definition at line 377 of file SimCharacter.cpp.
 {
     tQuaternion rot = tQuaternion::Identity();
     const auto& joint = GetJoint(joint_id);
     if (joint.IsValid())
     {
         rot = joint.CalcWorldRotation();
     }
     else
     {
         int parent_id = cKinTree::GetParent(mJointMat, joint_id);
         assert(parent_id != cKinTree::gInvalidJointID);
         assert(IsValidBodyPart(parent_id));
         const auto& parent_part = GetBodyPart(parent_id);
         rot = parent_part->GetRotation();
     }
     return rot;
 }
References GetBodyPart(), GetJoint(), cKinTree::GetParent(), cKinTree::gInvalidJointID, IsValidBodyPart(), and cCharacter::mJointMat.
CalcJointWorldRotation() [2/2]
void cSimCharacter::CalcJointWorldRotation (int joint_id, tVector & out_axis, double & out_theta) const virtual
Reimplemented from cCharacter.
Definition at line 359 of file SimCharacter.cpp.
 {
     const auto& joint = GetJoint(joint_id);
     if (joint.IsValid())
     {
         joint.CalcWorldRotation(out_axis, out_theta);
     }
     else
     {
         int parent_id = cKinTree::GetParent(mJointMat, joint_id);
         assert(parent_id != cKinTree::gInvalidJointID);
         assert(IsValidBodyPart(parent_id));
         const auto& parent_part = GetBodyPart(parent_id);
         parent_part->GetRotation(out_axis, out_theta);
     }
 }
References GetBodyPart(), GetJoint(), cKinTree::GetParent(), cKinTree::gInvalidJointID, IsValidBodyPart(), and cCharacter::mJointMat.
CalcTotalMass()
double cSimCharacter::CalcTotalMass () const virtual
Definition at line 1289 of file SimCharacter.cpp.
 {
     double m = 0;
     for (int i = 0; i < GetNumBodyParts(); ++i)
     {
         if (IsValidBodyPart(i))
         {
             m += GetBodyPart(i)->GetMass();
         }
     }
     return m;
 }
References GetBodyPart(), GetNumBodyParts(), and IsValidBodyPart().
CheckFallContact()
bool cSimCharacter::CheckFallContact () const protected virtual
Definition at line 1509 of file SimCharacter.cpp.
 {
     int num_parts = GetNumBodyParts();
     for (int b = 0; b < num_parts; ++b)
     {
         if (IsValidBodyPart(b) && EnableBodyPartFallContact(b))
         {
             const auto& curr_part = GetBodyPart(b);
             bool has_contact = curr_part->IsInContact();
             if (has_contact)
             {
                 return true;
             }
         }
     }
     return false;
 }
References EnableBodyPartFallContact(), GetBodyPart(), GetNumBodyParts(), and IsValidBodyPart().
Referenced by HasFallen().
Clear()
void cSimCharacter::Clear () virtual
Reimplemented from cCharacter.
Definition at line 73 of file SimCharacter.cpp.
 {
     cCharacter::Clear();
     RemoveFromWorld();
     mBodyDefs.resize(0, 0);
     if (HasController())
     {
         mController->Clear();
     }
 }
References cCharacter::Clear(), HasController(), mBodyDefs, mController, and RemoveFromWorld().
ClearForces()
void cSimCharacter::ClearForces () virtual
Implements cSimObj.
Definition at line 685 of file SimCharacter.cpp.
 {
     int num_parts = GetNumBodyParts();
     for (int b = 0; b < num_parts; ++b)
     {
         if (IsValidBodyPart(b))
         {
             auto& part = GetBodyPart(b);
             part->ClearForces();
         }
     }
 }
References GetBodyPart(), GetNumBodyParts(), and IsValidBodyPart().
ClearJointTorques()
void cSimCharacter::ClearJointTorques () protected virtual
Definition at line 1188 of file SimCharacter.cpp.
 {
     int num_joints = GetNumJoints();
     for (int j = 1; j < num_joints; ++j)
     {
         cSimBodyJoint& joint = GetJoint(j);
         if (joint.IsValid())
         {
             joint.ClearTau();
         }
     }
 }
References cSimBodyJoint::ClearTau(), GetJoint(), cCharacter::GetNumJoints(), and cSimBodyJoint::IsValid().
Referenced by Reset(), and Update().
EnableBodyPartFallContact()
bool cSimCharacter::EnableBodyPartFallContact (int idx) const virtual
Definition at line 1163 of file SimCharacter.cpp.
 {
     assert(idx >= 0 && idx < GetNumBodyParts());
     return cKinTree::GetBodyEnableFallContact(mBodyDefs, idx);
 }
References cKinTree::GetBodyEnableFallContact(), GetNumBodyParts(), and mBodyDefs.
Referenced by CheckFallContact().
EnableController()
void cSimCharacter::EnableController (bool enable) virtual
Definition at line 652 of file SimCharacter.cpp.
 {
     if (HasController())
     {
         mController->SetActive(enable);
     }
 }
References HasController(), and mController.
FixedBase()
bool cSimCharacter::FixedBase () const protected virtual
Definition at line 1138 of file SimCharacter.cpp.
 {
     int root_id = GetRootID();
     cKinTree::eJointType joint_type = cKinTree::GetJointType(mJointMat, root_id);
     return joint_type != cKinTree::eJointTypeNone;
 }
References cKinTree::eJointTypeNone, cKinTree::GetJointType(), cCharacter::GetRootID(), and cCharacter::mJointMat.
Referenced by BuildMultiBody().
GetAngularVelocity()
tVector cSimCharacter::GetAngularVelocity () const virtual
Implements cSimObj.
Definition at line 1371 of file SimCharacter.cpp.
 {
     return GetRootAngVel();
 }
References GetRootAngVel().
GetBodyDefs()
const Eigen::MatrixXd & cSimCharacter::GetBodyDefs () const virtual
Definition at line 163 of file SimCharacter.cpp.
 {
     return mBodyDefs;
 }
References mBodyDefs.
Referenced by cImpPDController::BuildRBDModel(), cSceneImitate::CalcRewardImitate(), and UpdateLinkVel().
GetBodyPart() [1/2]
std::shared_ptr< cSimBodyLink > & cSimCharacter::GetBodyPart (int idx) virtual
Definition at line 487 of file SimCharacter.cpp.
 {
     return mBodyParts[idx];
 }
References mBodyParts.
GetBodyPart() [2/2]
const std::shared_ptr< cSimBodyLink > & cSimCharacter::GetBodyPart (int idx) const virtual
Definition at line 482 of file SimCharacter.cpp.
 {
     return mBodyParts[idx];
 }
References mBodyParts.
Referenced by BuildJoints(), cCtController::BuildStatePose(), cDeepMimicCharController::BuildStatePose(), cCtController::BuildStateVel(), CalcAABB(), CalcJointPos(), CalcJointVel(), CalcJointWorldRotation(), CalcTotalMass(), CheckFallContact(), ClearForces(), cDrawSimCharacter::DrawBodyVel(), cDrawSimCharacter::DrawSimBody(), GetBodyPartPos(), GetBodyPartVel(), GetContactPts(), HasStumbled(), HasVelExploded(), IsInContact(), SetColGroup(), SetColMask(), and UpdateLinkVel().
GetBodyPartPos()
tVector cSimCharacter::GetBodyPartPos (int idx) const virtual
Definition at line 492 of file SimCharacter.cpp.
 {
     auto& part = GetBodyPart(idx);
     tVector pos = part->GetPos();
     return pos;
 }
References GetBodyPart().
GetBodyPartVel()
tVector cSimCharacter::GetBodyPartVel (int idx) const virtual
Definition at line 499 of file SimCharacter.cpp.
 {
     auto& part = GetBodyPart(idx);
     tVector vel = part->GetLinearVelocity();
     return vel;
 }
References GetBodyPart().
Referenced by cDeepMimicCharController::BuildStateVel().
GetColGroup()
short cSimCharacter::GetColGroup () const virtual
Reimplemented from cSimObj.
Definition at line 1381 of file SimCharacter.cpp.
 {
     return GetRootPart()->GetColGroup();
 }
References GetRootPart().
GetCollisionObject() [1/2]
btCollisionObject * cSimCharacter::GetCollisionObject () protected virtual
Implements cSimObj.
Definition at line 1532 of file SimCharacter.cpp.
 {
     return nullptr;
 }
GetCollisionObject() [2/2]
const btCollisionObject * cSimCharacter::GetCollisionObject () const protected virtual
Implements cSimObj.
Definition at line 1527 of file SimCharacter.cpp.
 {
     return nullptr;
 }
GetColMask()
short cSimCharacter::GetColMask () const virtual
Reimplemented from cSimObj.
Definition at line 1397 of file SimCharacter.cpp.
 {
     return GetRootPart()->GetColMask();
 }
References GetRootPart().
GetConstraints()
const std::vector< std::shared_ptr< btMultiBodyJointLimitConstraint > > & cSimCharacter::GetConstraints () const virtual
Definition at line 1423 of file SimCharacter.cpp.
 {
     return mCons;
 }
References mCons.
Referenced by cWorld::AddCharacter(), and cWorld::RemoveCharacter().
GetContactHandle()
const cContactManager::tContactHandle & cSimCharacter::GetContactHandle () const virtual
Reimplemented from cSimObj.
Definition at line 618 of file SimCharacter.cpp.
 {
     return GetRootPart()->GetContactHandle();
 }
References GetRootPart().
GetContactPts() [1/2]
const tEigenArr< cContactManager::tContactPt > & cSimCharacter::GetContactPts () const virtual
Reimplemented from cSimObj.
Definition at line 613 of file SimCharacter.cpp.
 {
     return GetContactPts(GetRootID());
 }
References cCharacter::GetRootID().
GetContactPts() [2/2]
const tEigenArr< cContactManager::tContactPt > & cSimCharacter::GetContactPts (int idx) const virtual
Definition at line 608 of file SimCharacter.cpp.
 {
     return GetBodyPart(idx)->GetContactPts();
 }
References GetBodyPart().
GetController() [1/2]
const std::shared_ptr< cCharController > & cSimCharacter::GetController () virtual
Definition at line 642 of file SimCharacter.cpp.
 {
     return mController;
 }
References mController.
GetController() [2/2]
const std::shared_ptr< cCharController > & cSimCharacter::GetController () const virtual
Definition at line 647 of file SimCharacter.cpp.
 {
     return mController;
 }
References mController.
GetJoint() [1/2]
cSimBodyJoint & cSimCharacter::GetJoint (int joint_id) virtual
Definition at line 477 of file SimCharacter.cpp.
 {
     return mJoints[joint_id];
 }
References mJoints.
GetJoint() [2/2]
const cSimBodyJoint & cSimCharacter::GetJoint (int joint_id) const virtual
Definition at line 472 of file SimCharacter.cpp.
 {
     return mJoints[joint_id];
 }
References mJoints.
Referenced by ApplyControlForces(), ApplyForce(), cCtController::BuildActionBounds(), cCtController::BuildActionOffsetScale(), BuildJointPose(), BuildJoints(), BuildJointVel(), BuildJointWorldTrans(), CalcJointPos(), CalcJointVel(), CalcJointWorldRotation(), ClearJointTorques(), cDrawSimCharacter::DrawTorque(), cPDController::GetJoint(), GetLinearVelocity(), GetRootAngVel(), GetRootPos(), GetRootRotation(), GetRootVel(), GetWorldTransform(), cExpPDController::Init(), SetPose(), SetVel(), and UpdateJoints().
GetLinearVelocity() [1/2]
tVector cSimCharacter::GetLinearVelocity () const virtual
Implements cSimObj.
Definition at line 1347 of file SimCharacter.cpp.
 {
     return GetRootVel();
 }
References GetRootVel().
GetLinearVelocity() [2/2]
tVector cSimCharacter::GetLinearVelocity (const tVector & local_pos) const virtual
Implements cSimObj.
Definition at line 1352 of file SimCharacter.cpp.
 {
     const auto& root_body = GetRootPart();
     const auto& joint = GetJoint(GetRootID());
     tVector world_pos = local_pos;
     world_pos[3] = 1;
     tMatrix joint_to_world = joint.BuildWorldTrans();
     world_pos = joint_to_world * world_pos;
     tVector body_local = root_body->WorldToLocalPos(world_pos);
     return root_body->GetLinearVelocity(body_local);
 }
References GetJoint(), cCharacter::GetRootID(), and GetRootPart().
GetMultiBody()
const std::shared_ptr< cMultiBody > & cSimCharacter::GetMultiBody () const virtual
Definition at line 1418 of file SimCharacter.cpp.
 {
     return mMultBody;
 }
References mMultBody.
Referenced by cWorld::AddCharacter(), and cWorld::RemoveCharacter().
GetNumBodyParts()
int cSimCharacter::GetNumBodyParts () const virtual
Definition at line 225 of file SimCharacter.cpp.
 {
     return static_cast<int>(mBodyParts.size());
 }
References mBodyParts.
Referenced by cCtController::BuildStatePose(), cDeepMimicCharController::BuildStatePose(), cCtController::BuildStateVel(), cDeepMimicCharController::BuildStateVel(), CalcAABB(), CalcTotalMass(), CheckFallContact(), ClearForces(), cDrawSimCharacter::DrawBodyVel(), cDrawSimCharacter::DrawSimBody(), EnableBodyPartFallContact(), cCtController::GetStatePoseSize(), cDeepMimicCharController::GetStatePoseSize(), cCtController::GetStateVelSize(), cDeepMimicCharController::GetStateVelSize(), HasVelExploded(), IsInContact(), SetBodyPartFallContact(), SetColGroup(), SetColMask(), cSceneSimChar::SetFallContacts(), and UpdateLinkVel().
GetPartColGroup()
short cSimCharacter::GetPartColGroup (int part_id) const protected virtual
Definition at line 1258 of file SimCharacter.cpp.
 {
     return GetPartColMask(part_id);
 }
References GetPartColMask().
Referenced by BuildBodyLinks(), and BuildMultiBody().
GetPartColMask()
short cSimCharacter::GetPartColMask (int part_id) const protected virtual
Definition at line 1263 of file SimCharacter.cpp.
 {
     int col_group = cKinTree::GetBodyColGroup(mBodyDefs, part_id);
     assert(col_group < static_cast<int>(sizeof(short) * 8));
     short flags;
     if (col_group == 0)
     {
         flags = cContactManager::gFlagNone;
     }
     else if (col_group == -1)
     {
         flags = cContactManager::gFlagAll;
     }
     else
     {
         flags = 1 << col_group;
     }
     return flags;
 }
References cKinTree::GetBodyColGroup(), cContactManager::gFlagAll, cContactManager::gFlagNone, and mBodyDefs.
Referenced by BuildBodyLinks(), BuildMultiBody(), and GetPartColGroup().
GetPartColor()
tVector cSimCharacter::GetPartColor (int part_id) const virtual
Definition at line 1284 of file SimCharacter.cpp.
 {
     return cKinTree::GetBodyColor(mBodyDefs, part_id);
 }
References cKinTree::GetBodyColor(), and mBodyDefs.
Referenced by cDrawSimCharacter::DrawSimBody().
GetPos()
tVector cSimCharacter::GetPos () const virtual
Reimplemented from cSimObj.
Definition at line 1312 of file SimCharacter.cpp.
 {
     return GetRootPos();
 }
References GetRootPos().
GetRootAngVel()
tVector cSimCharacter::GetRootAngVel () const virtual
Definition at line 155 of file SimCharacter.cpp.
 {
     int root_id = GetRootID();
     const cSimBodyJoint& root = GetJoint(root_id);
     tVector ang_vel = root.CalcWorldAngVel();
     return ang_vel;
 }
References cSimBodyJoint::CalcWorldAngVel(), GetJoint(), and cCharacter::GetRootID().
Referenced by BuildJointVel(), and GetAngularVelocity().
GetRootPart() [1/2]
std::shared_ptr< cSimBodyLink > cSimCharacter::GetRootPart () virtual
Definition at line 512 of file SimCharacter.cpp.
 {
     int root_idx = GetRootID();
     return mBodyParts[root_idx];
 }
References cCharacter::GetRootID(), and mBodyParts.
GetRootPart() [2/2]
const std::shared_ptr< cSimBodyLink > & cSimCharacter::GetRootPart () const virtual
Definition at line 506 of file SimCharacter.cpp.
 {
     int root_idx = GetRootID();
     return mBodyParts[root_idx];
 }
References cCharacter::GetRootID(), and mBodyParts.
Referenced by ApplyForce(), ApplyTorque(), GetColGroup(), GetColMask(), GetContactHandle(), and GetLinearVelocity().
GetRootPos()
tVector cSimCharacter::GetRootPos () const virtual
Reimplemented from cCharacter.
Definition at line 124 of file SimCharacter.cpp.
 {
     int root_id = GetRootID();
     const cSimBodyJoint& root = GetJoint(root_id);
     tVector pos = root.CalcWorldPos();
     return pos;
 }
References cSimBodyJoint::CalcWorldPos(), GetJoint(), and cCharacter::GetRootID().
Referenced by BuildJointPose(), cCtController::BuildStatePose(), cDeepMimicCharController::BuildStatePose(), cDeepMimicCharController::BuildStateVel(), cSceneImitate::CalcRewardImitate(), GetPos(), cDeepMimicCharController::GetViewBound(), cSceneSimChar::HasFallen(), SetRootRotation(), and cSceneImitate::SyncKinCharNewCycle().
GetRootRotation() [1/2]
tQuaternion cSimCharacter::GetRootRotation () const virtual
Reimplemented from cCharacter.
Definition at line 138 of file SimCharacter.cpp.
 {
     int root_id = GetRootID();
     const cSimBodyJoint& root = GetJoint(root_id);
     tQuaternion rot = root.CalcWorldRotation();
     rot = mInvRootAttachRot * rot;
     return rot;
 }
References cSimBodyJoint::CalcWorldRotation(), GetJoint(), cCharacter::GetRootID(), and mInvRootAttachRot.
Referenced by BuildJointPose(), CalcHeadingRot(), GetRootRotation(), and GetRotation().
GetRootRotation() [2/2]
void cSimCharacter::GetRootRotation (tVector & out_axis, double & out_theta) const virtual
Reimplemented from cCharacter.
Definition at line 132 of file SimCharacter.cpp.
 {
     tQuaternion rot = GetRootRotation();
     cMathUtil::QuaternionToAxisAngle(rot, out_axis, out_theta);
 }
References GetRootRotation(), and cMathUtil::QuaternionToAxisAngle().
Referenced by cSceneImitate::CheckRootRotFail().
GetRootVel()
tVector cSimCharacter::GetRootVel () const virtual
Definition at line 147 of file SimCharacter.cpp.
 {
     int root_id = GetRootID();
     const cSimBodyJoint& root = GetJoint(root_id);
     tVector vel = root.CalcWorldVel();
     return vel;
 }
References cSimBodyJoint::CalcWorldVel(), GetJoint(), and cCharacter::GetRootID().
Referenced by BuildJointVel(), and GetLinearVelocity().
GetRotation() [1/2]
tQuaternion cSimCharacter::GetRotation () const virtual
Reimplemented from cSimObj.
Definition at line 1327 of file SimCharacter.cpp.
 {
     return GetRootRotation();
 }
References GetRootRotation().
GetRotation() [2/2]
void cSimCharacter::GetRotation (tVector & out_axis, double & out_theta) const virtual
Reimplemented from cSimObj.
Definition at line 1322 of file SimCharacter.cpp.
 {
     return GetRootRotation(out_axis, out_theta);
 }
References GetRootRotation().
GetSize()
tVector cSimCharacter::GetSize () const virtual
Implements cSimObj.
Definition at line 464 of file SimCharacter.cpp.
 {
     tVector aabb_min;
     tVector aabb_max;
     CalcAABB(aabb_min, aabb_max);
     return aabb_max - aabb_min;
 }
References CalcAABB().
GetWorld()
const std::shared_ptr< cWorld > & cSimCharacter::GetWorld () const virtual
Reimplemented from cSimObj.
Definition at line 1413 of file SimCharacter.cpp.
 {
     return mWorld;
 }
References cSimObj::mWorld.
GetWorldTransform()
tMatrix cSimCharacter::GetWorldTransform () const virtual
Reimplemented from cSimObj.
Definition at line 1342 of file SimCharacter.cpp.
 {
     return GetJoint(GetRootID()).BuildWorldTrans();
 }
References cSimBodyJoint::BuildWorldTrans(), GetJoint(), and cCharacter::GetRootID().
HasController()
bool cSimCharacter::HasController () const virtual
Definition at line 637 of file SimCharacter.cpp.
 {
     return mController != nullptr;
 }
References mController.
Referenced by Clear(), EnableController(), PlayPossum(), PostUpdate(), RemoveController(), Reset(), SetPose(), SetVel(), and Update().
HasFallen()
bool cSimCharacter::HasFallen () const virtual
Definition at line 542 of file SimCharacter.cpp.
 {
     bool fallen = false;
     if (mEnableContactFall)
     {
         fallen |= CheckFallContact();
     }
     return fallen;
 }
References CheckFallContact(), and cSimObj::mEnableContactFall.
Referenced by cSceneSimChar::HasFallen().
HasStumbled()
bool cSimCharacter::HasStumbled () const virtual
Definition at line 552 of file SimCharacter.cpp.
 {
     bool stumbled = false;
     for (int j = 0; j < GetNumJoints(); ++j)
     {
         if (!IsEndEffector(j))
         {
             const auto& curr_part = GetBodyPart(j);
             bool contact = curr_part->IsInContact();
             if (contact)
             {
                 stumbled = true;
                 break;
             }
         }
     }
     return stumbled;
 }
References GetBodyPart(), cCharacter::GetNumJoints(), and cCharacter::IsEndEffector().
HasVelExploded()
bool cSimCharacter::HasVelExploded (double vel_threshold = 100.0) const virtual
Definition at line 571 of file SimCharacter.cpp.
 {
     int num_bodies = GetNumBodyParts();
     for (int b = 0; b < num_bodies; ++b)
     {
         const auto& body = GetBodyPart(b);
         tVector vel = body->GetLinearVelocity();
         tVector ang_vel = body->GetAngularVelocity();
         double max_val = std::max(vel.cwiseAbs().maxCoeff(), ang_vel.cwiseAbs().maxCoeff());
         if (max_val > vel_threshold)
         {
             return true;
         }
     }
     return false;
 }
References GetBodyPart(), and GetNumBodyParts().
Init()
bool cSimCharacter::Init (const std::shared_ptr< cWorld > & world, const tParams & params) virtual
Definition at line 35 of file SimCharacter.cpp.
 {
     bool succ = true;
     bool succ_skeleton = cCharacter::Init(params.mCharFile, params.mLoadDrawShapes);
     succ &= succ_skeleton;
     SetID(params.mID);
     RemoveFromWorld();
     mWorld = world;
     mEnableContactFall = params.mEnableContactFall;
     if (succ_skeleton)
     {
         succ &= BuildSimBody(params);
     }
     if (params.mStateFile != "")
     {
         bool succ_state = ReadState(params.mStateFile);
         if (!succ_state)
         {
             printf("Failed to load character state from %s\n", params.mStateFile.c_str());
         }
     }
     if (succ)
     {
         mPose0 = mPose;
         mVel0 = mVel;
         SetPose(mPose);
         SetVel(mVel);
     }
     return succ;
 }
References BuildSimBody(), cCharacter::Init(), cSimCharacter::tParams::mCharFile, cSimCharacter::tParams::mEnableContactFall, cSimObj::mEnableContactFall, cSimCharacter::tParams::mID, cSimCharacter::tParams::mLoadDrawShapes, cCharacter::mPose, cCharacter::mPose0, cSimCharacter::tParams::mStateFile, cCharacter::mVel, cCharacter::mVel0, cSimObj::mWorld, cCharacter::ReadState(), RemoveFromWorld(), cCharacter::SetID(), SetPose(), and SetVel().
IsInContact() [1/2]
bool cSimCharacter::IsInContact () const virtual
Reimplemented from cSimObj.
Definition at line 588 of file SimCharacter.cpp.
 {
     for (int i = 0; i < GetNumBodyParts(); ++i)
     {
         if (IsValidBodyPart(i))
         {
             if (IsInContact(i))
             {
                 return true;
             }
         }
     }
     return false;
 }
References GetNumBodyParts(), and IsValidBodyPart().
IsInContact() [2/2]
bool cSimCharacter::IsInContact (int idx) const virtual
Definition at line 603 of file SimCharacter.cpp.
 {
     return GetBodyPart(idx)->IsInContact();
 }
References GetBodyPart().
IsValidBodyPart()
bool cSimCharacter::IsValidBodyPart (int idx) const virtual
Definition at line 1158 of file SimCharacter.cpp.
 {
     return mBodyParts[idx] != nullptr;
 }
References mBodyParts.
Referenced by cCtController::BuildStatePose(), cDeepMimicCharController::BuildStatePose(), CalcAABB(), CalcCOM(), CalcCOMVel(), CalcJointPos(), CalcJointVel(), CalcJointWorldRotation(), CalcTotalMass(), CheckFallContact(), ClearForces(), cDrawSimCharacter::DrawBodyVel(), cDrawSimCharacter::DrawSimBody(), IsInContact(), RegisterContacts(), SetColGroup(), SetColMask(), UpdateContact(), and UpdateLinkVel().
LoadBodyDefs()
bool cSimCharacter::LoadBodyDefs (const std::string & char_file, Eigen::MatrixXd & out_body_defs) const protected virtual
Definition at line 975 of file SimCharacter.cpp.
 {
     bool succ = cKinTree::LoadBodyDefs(char_file, out_body_defs);
     int num_joints = GetNumJoints();
     int num_body_defs = static_cast<int>(out_body_defs.rows());
     assert(num_joints == num_body_defs);
     return succ;
 }
References cCharacter::GetNumJoints(), and cKinTree::LoadBodyDefs().
Referenced by BuildSimBody().
PlayPossum()
void cSimCharacter::PlayPossum () virtual
Definition at line 717 of file SimCharacter.cpp.
 {
     if (HasController())
     {
         mController->SetMode(cController::eModePassive);
     }
 }
References cController::eModePassive, HasController(), and mController.
PostUpdate()
void cSimCharacter::PostUpdate (double time_step) virtual
Definition at line 112 of file SimCharacter.cpp.
 {
     UpdateLinkVel();
     BuildPose(mPose);
     BuildVel(mVel);
     if (HasController())
     {
         mController->PostUpdate(time_step);
     }
 }
References BuildPose(), BuildVel(), HasController(), mController, cCharacter::mPose, cCharacter::mVel, and UpdateLinkVel().
RegisterContacts()
void cSimCharacter::RegisterContacts (int contact_flags, int filter_flags) virtual
Definition at line 518 of file SimCharacter.cpp.
 {
     for (int i = 0; i < static_cast<int>(mBodyParts.size()); ++i)
     {
         if (IsValidBodyPart(i))
         {
             std::shared_ptr<cSimBodyLink>& part = mBodyParts[i];
             part->RegisterContact(contact_flags, filter_flags);
         }
     }
 }
References IsValidBodyPart(), and mBodyParts.
RemoveController()
void cSimCharacter::RemoveController () virtual
Definition at line 629 of file SimCharacter.cpp.
 {
     if (HasController())
     {
         mController.reset();
     }
 }
References HasController(), and mController.
Referenced by SetController().
RemoveFromWorld()
void cSimCharacter::RemoveFromWorld () protected virtual
Definition at line 1145 of file SimCharacter.cpp.
 {
     if (mWorld != nullptr)
     {
         mWorld->RemoveCharacter(*this);
         mJoints.clear();
         mBodyParts.clear();
         mCons.clear();
         mMultBody.reset();
         mWorld.reset();
     }
 }
References mBodyParts, mCons, mJoints, mMultBody, and cSimObj::mWorld.
Referenced by Clear(), Init(), and ~cSimCharacter().
Reset()
void cSimCharacter::Reset () virtual
Reimplemented from cCharacter.
Definition at line 87 of file SimCharacter.cpp.
 {
     cCharacter::Reset();
     if (HasController())
     {
         mController->Reset();
     }
     ClearJointTorques();
 }
References ClearJointTorques(), HasController(), mController, and cCharacter::Reset().
SetAngularDamping()
void cSimCharacter::SetAngularDamping (double damping) virtual
Definition at line 1307 of file SimCharacter.cpp.
 {
     mMultBody->setAngularDamping(damping);
 }
References mMultBody.
Referenced by cWorld::AddCharacter().
SetAngularVelocity()
void cSimCharacter::SetAngularVelocity (const tVector & vel) virtual
Implements cSimObj.
Definition at line 1376 of file SimCharacter.cpp.
 {
     SetRootAngVel(vel);
 }
References SetRootAngVel().
SetBodyPartFallContact()
void cSimCharacter::SetBodyPartFallContact (int idx, bool enable) virtual
Definition at line 1169 of file SimCharacter.cpp.
 {
     assert(idx >= 0 && idx < GetNumBodyParts());
     cKinTree::SetBodyEnableFallContact(idx, enable, mBodyDefs);
 }
References GetNumBodyParts(), mBodyDefs, and cKinTree::SetBodyEnableFallContact().
Referenced by cSceneSimChar::SetFallContacts().
SetColGroup()
void cSimCharacter::SetColGroup (short col_group) virtual
Reimplemented from cSimObj.
Definition at line 1386 of file SimCharacter.cpp.
 {
     for (int i = 0; i < GetNumBodyParts(); ++i)
     {
         if (IsValidBodyPart(i))
         {
             GetBodyPart(i)->SetColGroup(col_group);
         }
     }
 }
References GetBodyPart(), GetNumBodyParts(), and IsValidBodyPart().
SetColMask()
void cSimCharacter::SetColMask (short col_mask) virtual
Reimplemented from cSimObj.
Definition at line 1402 of file SimCharacter.cpp.
 {
     for (int i = 0; i < GetNumBodyParts(); ++i)
     {
         if (IsValidBodyPart(i))
         {
             GetBodyPart(i)->SetColMask(col_mask);
         }
     }
 }
References GetBodyPart(), GetNumBodyParts(), and IsValidBodyPart().
SetController()
void cSimCharacter::SetController (std::shared_ptr< cCharController > ctrl) virtual
Definition at line 623 of file SimCharacter.cpp.
 {
     RemoveController();
     mController = ctrl;
 }
References mController, and RemoveController().
SetLinearDamping()
void cSimCharacter::SetLinearDamping (double damping) virtual
Definition at line 1302 of file SimCharacter.cpp.
 {
     mMultBody->setLinearDamping(damping);
 }
References mMultBody.
Referenced by cWorld::AddCharacter().
SetLinearVelocity()
void cSimCharacter::SetLinearVelocity (const tVector & vel) virtual
Implements cSimObj.
Definition at line 1366 of file SimCharacter.cpp.
 {
     SetRootVel(vel);
 }
References SetRootVel().
SetPos()
void cSimCharacter::SetPos (const tVector & pos) virtual
Reimplemented from cSimObj.
Definition at line 1317 of file SimCharacter.cpp.
 {
     SetRootPos(pos);
 }
References SetRootPos().
SetPose()
void cSimCharacter::SetPose (const Eigen::VectorXd & pose) virtual
Reimplemented from cCharacter.
Definition at line 725 of file SimCharacter.cpp.
 {
     cCharacter::SetPose(pose);
     double world_scale = mWorld->GetScale();
     int root_id = cKinTree::GetRoot(mJointMat);
     tVector root_pos = cKinTree::GetRootPos(mJointMat, pose);
     tQuaternion root_rot = cKinTree::GetRootRot(mJointMat, pose);
     cKinTree::eJointType root_type = cKinTree::GetJointType(mJointMat, root_id);
     tVector euler = cMathUtil::QuaternionToEuler(root_rot);
     mMultBody->setBasePos(world_scale * btVector3(root_pos[0], root_pos[1], root_pos[2]));
     mMultBody->setWorldToBaseRot(btQuaternion(root_rot.x(), root_rot.y(), root_rot.z(), root_rot.w()).inverse());
     cSimBodyJoint& root_joint = GetJoint(root_id);
     Eigen::VectorXd root_pose = Eigen::VectorXd::Zero(GetParamSize(root_id));
     if (root_type == cKinTree::eJointTypeSpherical)
     {
         root_pose = cMathUtil::QuatToVec(tQuaternion::Identity());
     }
     root_joint.SetPose(root_pose);
     for (int j = 1; j < GetNumJoints(); ++j)
     {
         cSimBodyJoint& curr_joint = GetJoint(j);
         int param_offset = GetParamOffset(j);
         int param_size = GetParamSize(j);
         Eigen::VectorXd curr_params = pose.segment(param_offset, param_size);
         curr_joint.SetPose(curr_params);
     }
     UpdateLinkPos();
     UpdateLinkVel();
     if (HasController())
     {
         mController->HandlePoseReset();
     }
 }
References cKinTree::eJointTypeSpherical, GetJoint(), cKinTree::GetJointType(), cCharacter::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), cKinTree::GetRoot(), cKinTree::GetRootPos(), cKinTree::GetRootRot(), HasController(), mController, cCharacter::mJointMat, mMultBody, cSimObj::mWorld, cMathUtil::QuaternionToEuler(), cMathUtil::QuatToVec(), cCharacter::SetPose(), cSimBodyJoint::SetPose(), UpdateLinkPos(), and UpdateLinkVel().
Referenced by Init(), SetRootPos(), and SetRootTransform().
SetRootAngVel()
void cSimCharacter::SetRootAngVel (const tVector & ang_vel) virtual
Reimplemented from cCharacter.
Definition at line 210 of file SimCharacter.cpp.
 {
     cCharacter::SetRootAngVel(ang_vel);
     SetVel(mVel);
 }
References cCharacter::mVel, cCharacter::SetRootAngVel(), and SetVel().
Referenced by SetAngularVelocity().
SetRootPos()
void cSimCharacter::SetRootPos (const tVector & pos) virtual
Reimplemented from cCharacter.
Definition at line 168 of file SimCharacter.cpp.
 {
     cCharacter::SetRootPos(pos);
     SetPose(mPose);
 }
References cCharacter::mPose, SetPose(), and cCharacter::SetRootPos().
Referenced by SetPos().
SetRootRotation() [1/2]
void cSimCharacter::SetRootRotation (const tQuaternion & q) virtual
Reimplemented from cCharacter.
Definition at line 180 of file SimCharacter.cpp.
 {
     SetRootTransform(GetRootPos(), q);
 }
References GetRootPos(), and SetRootTransform().
SetRootRotation() [2/2]
void cSimCharacter::SetRootRotation (const tVector & axis, double theta) virtual
Definition at line 174 of file SimCharacter.cpp.
 {
     tQuaternion q = cMathUtil::AxisAngleToQuaternion(axis, theta);
     SetRootTransform(GetRootPos(), q);
 }
References cMathUtil::AxisAngleToQuaternion(), GetRootPos(), and SetRootTransform().
Referenced by SetRotation().
SetRootTransform()
void cSimCharacter::SetRootTransform (const tVector & pos, const tQuaternion & rot) virtual
Definition at line 185 of file SimCharacter.cpp.
 {
     tQuaternion root_rot = cKinTree::GetRootRot(mJointMat, mPose);
     tVector root_vel = cKinTree::GetRootVel(mJointMat, mVel);
     tVector root_ang_vel = cKinTree::GetRootAngVel(mJointMat, mVel);
     tQuaternion delta_rot = rot * root_rot.inverse();
     root_vel = cMathUtil::QuatRotVec(delta_rot, root_vel);
     root_ang_vel = cMathUtil::QuatRotVec(delta_rot, root_ang_vel);
     cKinTree::SetRootPos(mJointMat, pos, mPose);
     cKinTree::SetRootRot(mJointMat, rot, mPose);
     cKinTree::SetRootVel(mJointMat, root_vel, mVel);
     cKinTree::SetRootAngVel(mJointMat, root_ang_vel, mVel);
     SetPose(mPose);
     SetVel(mVel);
 }
References cKinTree::GetRootAngVel(), cKinTree::GetRootRot(), cKinTree::GetRootVel(), cCharacter::mJointMat, cCharacter::mPose, cCharacter::mVel, cMathUtil::QuatRotVec(), SetPose(), cKinTree::SetRootAngVel(), cKinTree::SetRootPos(), cKinTree::SetRootRot(), cKinTree::SetRootVel(), and SetVel().
Referenced by SetRootRotation().
SetRootVel()
void cSimCharacter::SetRootVel (const tVector & vel) virtual
Reimplemented from cCharacter.
Definition at line 204 of file SimCharacter.cpp.
 {
     cCharacter::SetRootVel(vel);
     SetVel(mVel);
 }
References cCharacter::mVel, cCharacter::SetRootVel(), and SetVel().
Referenced by SetLinearVelocity().
SetRotation() [1/2]
void cSimCharacter::SetRotation (const tQuaternion & q) virtual
Reimplemented from cSimObj.
Definition at line 1337 of file SimCharacter.cpp.
 {
     SetRootRotation(q);
 }
References SetRootRotation().
SetRotation() [2/2]
void cSimCharacter::SetRotation (const tVector & axis, double theta) virtual
Reimplemented from cSimObj.
Definition at line 1332 of file SimCharacter.cpp.
 {
     SetRootRotation(axis, theta);
 }
References SetRootRotation().
SetVel()
void cSimCharacter::SetVel (const Eigen::VectorXd & vel) virtual
Reimplemented from cCharacter.
Definition at line 230 of file SimCharacter.cpp.
 {
     cCharacter::SetVel(vel);
     double world_scale = mWorld->GetScale();
     int root_id = cKinTree::GetRoot(mJointMat);
     tVector root_vel = cKinTree::GetRootVel(mJointMat, vel);
     tVector root_ang_vel = cKinTree::GetRootAngVel(mJointMat, vel);
     cKinTree::eJointType root_type = cKinTree::GetJointType(mJointMat, root_id);
     if (!mMultBody->hasFixedBase())
     {
         mMultBody->setBaseVel(world_scale * btVector3(root_vel[0], root_vel[1], root_vel[2]));
         mMultBody->setBaseOmega(btVector3(root_ang_vel[0], root_ang_vel[1], root_ang_vel[2]));
     }
     else
     {
         cSimBodyJoint& root_joint = GetJoint(root_id);
         tQuaternion world_to_root = root_joint.CalcWorldRotation().inverse();
         tVector local_root_vel = cMathUtil::QuatRotVec(world_to_root, root_vel);
         tVector local_root_ang_vel = cMathUtil::QuatRotVec(world_to_root, root_ang_vel);
         Eigen::VectorXd root_params = Eigen::VectorXd::Zero(GetParamSize(root_id));
         switch (root_type)
         {
         case cKinTree::eJointTypeRevolute:
         {
             root_params[0] = local_root_ang_vel[2];
             break;
         }
         case cKinTree::eJointTypePlanar:
         {
             root_params[0] = local_root_vel[0];
             root_params[1] = local_root_vel[1];
             root_params[2] = local_root_ang_vel[2];
             break;
         }
         case cKinTree::eJointTypePrismatic:
         {
             root_params[0] = local_root_vel[0];
             break;
         }
         case cKinTree::eJointTypeFixed:
         {
             break;
         }
         case cKinTree::eJointTypeSpherical:
         {
             root_params[0] = local_root_ang_vel[0];
             root_params[1] = local_root_ang_vel[1];
             root_params[2] = local_root_ang_vel[2];
             break;
         }
         default:
             assert(false); // unsupported joint type
             break;
         }
         root_joint.SetVel(root_params);
     }
     for (int j = 1; j < GetNumJoints(); ++j)
     {
         cSimBodyJoint& curr_jont = GetJoint(j);
         int param_offset = GetParamOffset(j);
         int param_size = GetParamSize(j);
         Eigen::VectorXd curr_params = vel.segment(param_offset, param_size);
         curr_jont.SetVel(curr_params);
     }
     UpdateLinkVel();
     if (HasController())
     {
         mController->HandleVelReset();
     }
 }
References cSimBodyJoint::CalcWorldRotation(), cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, GetJoint(), cKinTree::GetJointType(), cCharacter::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), cKinTree::GetRoot(), cKinTree::GetRootAngVel(), cKinTree::GetRootVel(), HasController(), mController, cCharacter::mJointMat, mMultBody, cSimObj::mWorld, cMathUtil::QuatRotVec(), cCharacter::SetVel(), cSimBodyJoint::SetVel(), and UpdateLinkVel().
Referenced by Init(), SetRootAngVel(), SetRootTransform(), and SetRootVel().
Update()
void cSimCharacter::Update (double time_step) virtual
Reimplemented from cCharacter.
Definition at line 99 of file SimCharacter.cpp.
 {
     ClearJointTorques();
     if (HasController())
     {
         mController->Update(timestep);
     }
     // dont clear torques until next frame since they can be useful for visualization
     UpdateJoints();
 }
References ClearJointTorques(), HasController(), mController, and UpdateJoints().
UpdateContact()
void cSimCharacter::UpdateContact (int contact_flags, int filter_flags) virtual
Reimplemented from cSimObj.
Definition at line 530 of file SimCharacter.cpp.
 {
     for (int i = 0; i < static_cast<int>(mBodyParts.size()); ++i)
     {
         if (IsValidBodyPart(i))
         {
             std::shared_ptr<cSimBodyLink>& part = mBodyParts[i];
             part->UpdateContact(contact_flags, filter_flags);
         }
     }
 }
References IsValidBodyPart(), and mBodyParts.
UpdateJoints()
void cSimCharacter::UpdateJoints () protected virtual
Definition at line 1201 of file SimCharacter.cpp.
 {
     int num_joints = GetNumJoints();
     for (int j = 1; j < num_joints; ++j)
     {
         cSimBodyJoint& joint = GetJoint(j);
         if (joint.IsValid())
         {
             joint.ApplyTau();
         }
     }
 }
References cSimBodyJoint::ApplyTau(), GetJoint(), cCharacter::GetNumJoints(), and cSimBodyJoint::IsValid().
Referenced by Update().
UpdateLinkPos()
void cSimCharacter::UpdateLinkPos () protected virtual
Definition at line 1214 of file SimCharacter.cpp.
 {
     mMultBody->updateCollisionObjectWorldTransforms(mRotBuffer, mVecBuffer0);
 }
References mMultBody, mRotBuffer, and mVecBuffer0.
Referenced by SetPose().
UpdateLinkVel()
void cSimCharacter::UpdateLinkVel () protected virtual
Definition at line 1219 of file SimCharacter.cpp.
 {
     static double max_vel_err = 0;
     static double max_omega_err = 0;
     const auto& joint_mat = GetJointMat();
     const auto& body_defs = GetBodyDefs();
     const auto& pose = GetPose();
     const auto& vel = GetVel();
     btAlignedObjectArray<btVector3>& ang_vel_buffer = mVecBuffer0;
     btAlignedObjectArray<btVector3>& vel_buffer = mVecBuffer1;
     mMultBody->compTreeLinkVelocities(&ang_vel_buffer[0], &vel_buffer[0]);
     double world_scale = mWorld->GetScale();
     for (int b = 0; b < GetNumBodyParts(); ++b)
     {
         if (IsValidBodyPart(b))
         {
             const btVector3& bt_vel = vel_buffer[b + 1];
             const btVector3& bt_ang_vel = ang_vel_buffer[b + 1];
             tVector com_vel = tVector(bt_vel[0], bt_vel[1], bt_vel[2], 0);
             tVector com_omega = tVector(bt_ang_vel[0], bt_ang_vel[1], bt_ang_vel[2], 0);
             com_vel /= world_scale;
             // velocities are in the body's local coordinates
             // so need to transform them into world coords
             tQuaternion world_rot = GetBodyPart(b)->GetRotation();
             com_vel = cMathUtil::QuatRotVec(world_rot, com_vel);
             com_omega = cMathUtil::QuatRotVec(world_rot, com_omega);
             const auto& link = GetBodyPart(b);
             link->UpdateVel(com_vel, com_omega);
         }
     }
 }
References GetBodyDefs(), GetBodyPart(), cCharacter::GetJointMat(), GetNumBodyParts(), cCharacter::GetPose(), cCharacter::GetVel(), IsValidBodyPart(), mMultBody, mVecBuffer0, mVecBuffer1, cSimObj::mWorld, and cMathUtil::QuatRotVec().
Referenced by PostUpdate(), SetPose(), and SetVel().
Member Data Documentation
mBodyDefs
Eigen::MatrixXd cSimCharacter::mBodyDefs protected
Definition at line 150 of file SimCharacter.h.
Referenced by BuildBodyLinks(), BuildJoints(), BuildMultiBody(), BuildSimBody(), CalcJointPos(), CalcJointVel(), Clear(), EnableBodyPartFallContact(), GetBodyDefs(), GetPartColMask(), GetPartColor(), and SetBodyPartFallContact().
mBodyParts
std::vector<std::shared_ptr<cSimBodyLink> > cSimCharacter::mBodyParts protected
Definition at line 145 of file SimCharacter.h.
Referenced by BuildBodyLinks(), CalcCOM(), CalcCOMVel(), GetBodyPart(), GetNumBodyParts(), GetRootPart(), IsValidBodyPart(), RegisterContacts(), RemoveFromWorld(), and UpdateContact().
mCons
std::vector<std::shared_ptr<btMultiBodyJointLimitConstraint> > cSimCharacter::mCons protected
Definition at line 147 of file SimCharacter.h.
Referenced by BuildConstraints(), GetConstraints(), and RemoveFromWorld().
mController
std::shared_ptr<cCharController> cSimCharacter::mController protected
Definition at line 152 of file SimCharacter.h.
Referenced by Clear(), EnableController(), GetController(), HasController(), PlayPossum(), PostUpdate(), RemoveController(), Reset(), SetController(), SetPose(), SetVel(), and Update().
mFriction
double cSimCharacter::mFriction protected
Definition at line 149 of file SimCharacter.h.
Referenced by BuildMultiBody(), and cSimCharacter().
mInvRootAttachRot
tQuaternion cSimCharacter::mInvRootAttachRot protected
Definition at line 153 of file SimCharacter.h.
Referenced by BuildSimBody(), and GetRootRotation().
mJoints
tEigenArr<cSimBodyJoint> cSimCharacter::mJoints protected
Definition at line 146 of file SimCharacter.h.
Referenced by BuildJoints(), GetJoint(), and RemoveFromWorld().
mMultBody
std::shared_ptr<cMultiBody> cSimCharacter::mMultBody protected
Definition at line 144 of file SimCharacter.h.
Referenced by BuildBodyLinks(), BuildConstraints(), BuildJoints(), BuildMultiBody(), BuildSimBody(), GetMultiBody(), RemoveFromWorld(), SetAngularDamping(), SetLinearDamping(), SetPose(), SetVel(), UpdateLinkPos(), and UpdateLinkVel().
mRotBuffer
btAlignedObjectArray<btQuaternion> cSimCharacter::mRotBuffer protected
Definition at line 158 of file SimCharacter.h.
Referenced by BuildSimBody(), and UpdateLinkPos().
mVecBuffer0
btAlignedObjectArray<btVector3> cSimCharacter::mVecBuffer0 protected
Definition at line 156 of file SimCharacter.h.
Referenced by BuildSimBody(), UpdateLinkPos(), and UpdateLinkVel().
mVecBuffer1
btAlignedObjectArray<btVector3> cSimCharacter::mVecBuffer1 protected
Definition at line 157 of file SimCharacter.h.
Referenced by BuildSimBody(), and UpdateLinkVel().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimCharacter.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimCharacter.cpp