My Project: Json::CharReaderBuilder Class Reference
Json::CharReaderBuilder Class Reference
Build a CharReader implementation.
#include <reader.h>
Public Member Functions
CharReaderBuilder ()
~CharReaderBuilder () JSONCPP_OVERRIDE
CharReader * newCharReader () const JSONCPP_OVERRIDE
Allocate a CharReader via operator new().
bool validate (Json::Value *invalid) const
Value & operator[] (JSONCPP_STRING key)
Public Member Functions inherited from Json::CharReader::Factory
virtual ~Factory ()
Static Public Member Functions
static void setDefaults (Json::Value *settings)
static void strictMode (Json::Value *settings)
Public Attributes
Json::Value settings_
Detailed Description
Build a CharReader implementation.
Usage:
using namespace Json;
CharReaderBuilder builder;
builder["collectComments"] = false;
Value value;
JSONCPP_STRING errs;
bool ok = parseFromStream(builder, std::cin, &value, &errs);
Definition at line 295 of file reader.h.
Constructor & Destructor Documentation
CharReaderBuilder()
Json::CharReaderBuilder::CharReaderBuilder ()
Definition at line 1917 of file json_reader.cpp.
 {
   setDefaults(&settings_);
 }
References setDefaults(), and settings_.
~CharReaderBuilder()
Json::CharReaderBuilder::~CharReaderBuilder ()
Definition at line 1921 of file json_reader.cpp.
 {}
Member Function Documentation
newCharReader()
CharReader * Json::CharReaderBuilder::newCharReader () const virtual
Allocate a CharReader via operator new().
Exceptions
std::exception if something goes wrong (e.g. invalid settings)
Implements Json::CharReader::Factory.
Definition at line 1923 of file json_reader.cpp.
 {
   bool collectComments = settings_["collectComments"].asBool();
   OurFeatures features = OurFeatures::all();
   features.allowComments_ = settings_["allowComments"].asBool();
   features.strictRoot_ = settings_["strictRoot"].asBool();
   features.allowDroppedNullPlaceholders_ = settings_["allowDroppedNullPlaceholders"].asBool();
   features.allowNumericKeys_ = settings_["allowNumericKeys"].asBool();
   features.allowSingleQuotes_ = settings_["allowSingleQuotes"].asBool();
   features.stackLimit_ = settings_["stackLimit"].asInt();
   features.failIfExtra_ = settings_["failIfExtra"].asBool();
   features.rejectDupKeys_ = settings_["rejectDupKeys"].asBool();
   features.allowSpecialFloats_ = settings_["allowSpecialFloats"].asBool();
   return new OurCharReader(collectComments, features);
 }
References Json::OurFeatures::all(), Json::OurFeatures::allowComments_, Json::OurFeatures::allowDroppedNullPlaceholders_, Json::OurFeatures::allowNumericKeys_, Json::OurFeatures::allowSingleQuotes_, Json::OurFeatures::allowSpecialFloats_, Json::Value::asBool(), Json::Value::asInt(), Json::OurFeatures::failIfExtra_, Json::OurFeatures::rejectDupKeys_, settings_, Json::OurFeatures::stackLimit_, and Json::OurFeatures::strictRoot_.
operator[]()
Value & Json::CharReaderBuilder::operator[] (JSONCPP_STRING key)
A simple way to update a specific setting.
Definition at line 1969 of file json_reader.cpp.
 {
   return settings_[key];
 }
References settings_.
setDefaults()
void Json::CharReaderBuilder::setDefaults (Json::Value * settings) static
Called by ctor, but you can use this to reset settings_.
Precondition
'settings' != NULL (but Json::null is fine)
Remarks
Defaults:
[CharReaderBuilderDefaults]
[CharReaderBuilderDefaults]
Definition at line 1989 of file json_reader.cpp.
 {
   (*settings)["collectComments"] = true;
   (*settings)["allowComments"] = true;
   (*settings)["strictRoot"] = false;
   (*settings)["allowDroppedNullPlaceholders"] = false;
   (*settings)["allowNumericKeys"] = false;
   (*settings)["allowSingleQuotes"] = false;
   (*settings)["stackLimit"] = 1000;
   (*settings)["failIfExtra"] = false;
   (*settings)["rejectDupKeys"] = false;
   (*settings)["allowSpecialFloats"] = false;
 }
Referenced by CharReaderBuilder().
strictMode()
void Json::CharReaderBuilder::strictMode (Json::Value * settings) static
Same as old Features::strictMode().
Precondition
'settings' != NULL (but Json::null is fine)
Remarks
Defaults:
[CharReaderBuilderStrictMode]
[CharReaderBuilderStrictMode]
Definition at line 1974 of file json_reader.cpp.
 {
   (*settings)["allowComments"] = false;
   (*settings)["strictRoot"] = true;
   (*settings)["allowDroppedNullPlaceholders"] = false;
   (*settings)["allowNumericKeys"] = false;
   (*settings)["allowSingleQuotes"] = false;
   (*settings)["stackLimit"] = 1000;
   (*settings)["failIfExtra"] = true;
   (*settings)["rejectDupKeys"] = true;
   (*settings)["allowSpecialFloats"] = false;
 }
validate()
bool Json::CharReaderBuilder::validate (Json::Value * invalid) const
Returns
true if 'settings' are legal and consistent; otherwise, indicate bad settings via 'invalid'.
Definition at line 1952 of file json_reader.cpp.
 {
   Json::Value my_invalid;
   if (!invalid) invalid = &my_invalid;  // so we do not need to test for NULL
   Json::Value& inv = *invalid;
   std::set<JSONCPP_STRING> valid_keys;
   getValidReaderKeys(&valid_keys);
   Value::Members keys = settings_.getMemberNames();
   size_t n = keys.size();
   for (size_t i = 0; i < n; ++i) {
     JSONCPP_STRING const& key = keys[i];
     if (valid_keys.find(key) == valid_keys.end()) {
       inv[key] = settings_[key];
     }
   }
   return 0u == inv.size();
 }
References Json::Value::getMemberNames(), Json::getValidReaderKeys(), JSONCPP_STRING, settings_, and Json::Value::size().
Member Data Documentation
settings_
Json::Value Json::CharReaderBuilder::settings_
Configuration of this builder. These are case-sensitive. Available settings (case-sensitive):
"collectComments": false or true
true to collect comment and allow writing them back during serialization, false to discard comments. This parameter is ignored if allowComments is false.
"allowComments": false or true
true if comments are allowed.
"strictRoot": false or true
true if root must be either an array or an object value
"allowDroppedNullPlaceholders": false or true
true if dropped null placeholders are allowed. (See StreamWriterBuilder.)
"allowNumericKeys": false or true
true if numeric object keys are allowed.
"allowSingleQuotes": false or true
true if '' are allowed for strings (both keys and values)
"stackLimit": integer
Exceeding stackLimit (recursive depth of readValue()) will cause an exception.
This is a security issue (seg-faults caused by deeply nested JSON), so the default is low.
"failIfExtra": false or true
If true, parse() returns false when extra non-whitespace trails the JSON value in the input string.
"rejectDupKeys": false or true
If true, parse() returns false when a key is duplicated within an object.
"allowSpecialFloats": false or true
If true, special float values (NaNs and infinities) are allowed and their values are lossfree restorable.
You can examine 'settings_` yourself to see the defaults. You can also write and read them just like any JSON Value.
See also
setDefaults()
Definition at line 335 of file reader.h.
Referenced by CharReaderBuilder(), newCharReader(), operator[](), and validate().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/json/reader.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/json/json_reader.cpp