My Project: cDrawWorld Class Reference
cDrawWorld Class Reference
#include <DrawWorld.h>
Static Public Member Functions
static void DrawPerturbs (const cWorld &world)
Detailed Description
Definition at line 5 of file DrawWorld.h.
Member Function Documentation
DrawPerturbs()
void cDrawWorld::DrawPerturbs (const cWorld & world) static
Definition at line 4 of file DrawWorld.cpp.
 {
     const cPerturbManager& perturb_man = world.GetPerturbManager();
     int num_perturbs = perturb_man.GetNumPerturbs();
     for (int p = 0; p < num_perturbs; ++p)
     {
         const tPerturb& perturb = perturb_man.GetPerturb(p);
         cDrawPerturb::Draw(perturb);
     }
 }
References cDrawPerturb::Draw(), cPerturbManager::GetNumPerturbs(), cPerturbManager::GetPerturb(), and cWorld::GetPerturbManager().
Referenced by cDrawSceneSimChar::DrawPerturbs().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/DrawWorld.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/DrawWorld.cpp