My Project: cImpPDController Class Reference
cImpPDController Class Reference
#include <ImpPDController.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cImpPDController ()
virtual ~cImpPDController ()
virtual void Init (cSimCharacter *character, const Eigen::MatrixXd &pd_params, const tVector &gravity)
virtual void Init (cSimCharacter *character, const std::shared_ptr< cRBDModel > &model, const Eigen::MatrixXd &pd_params, const tVector &gravity)
virtual void Clear ()
virtual void UpdateControlForce (double time_step, Eigen::VectorXd &out_tau)
virtual void SetKp (int joint_id, double kp)
virtual void SetKd (int joint_id, double kd)
Public Member Functions inherited from cExpPDController
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cExpPDController ()
virtual ~cExpPDController ()
virtual void Init (cSimCharacter *character, const Eigen::MatrixXd &pd_params)
virtual void Reset ()
virtual void Update (double time_step)
virtual int GetNumJoints () const
virtual int GetNumDof () const
virtual void GetTargetTheta (int joint_id, Eigen::VectorXd &out_theta) const
virtual void SetTargetTheta (int joint_id, const Eigen::VectorXd &theta)
virtual void GetTargetVel (int joint_id, Eigen::VectorXd &out_vel) const
virtual void SetTargetVel (int joint_id, const Eigen::VectorXd &vel)
virtual bool UseWorldCoord (int joint_id) const
virtual void SetUseWorldCoord (int joint_id, bool use)
virtual bool IsValidPDCtrl (int joint_id) const
virtual cPDController & GetPDCtrl (int joint_id)
virtual const cPDController & GetPDCtrl (int joint_id) const
Public Member Functions inherited from cController
virtual ~cController ()
virtual void Init (cSimCharacter *character)
virtual bool IsValid () const
virtual bool LoadParams (const std::string &param_file)
virtual int GetNumOptParams () const
virtual void BuildOptParams (Eigen::VectorXd &out_params) const
virtual void SetOptParams (const Eigen::VectorXd &params)
virtual void SetOptParams (const Eigen::VectorXd &params, Eigen::VectorXd &out_params) const
virtual void FetchOptParamScale (Eigen::VectorXd &out_scale) const
virtual void OutputOptParams (const std::string &file, const Eigen::VectorXd &params) const
virtual void OutputOptParams (FILE *f, const Eigen::VectorXd &params) const
virtual void SetActive (bool active)
virtual bool IsActive () const
virtual void SetMode (eMode mode)
virtual const cSimCharacter * GetChar () const
Protected Member Functions
virtual void InitGains ()
virtual std::shared_ptr< cRBDModel > BuildRBDModel (const cSimCharacter &character, const tVector &gravity) const
virtual void UpdateRBDModel ()
virtual void CalcControlForces (double time_step, Eigen::VectorXd &out_tau)
virtual void BuildTargetPose (Eigen::VectorXd &out_pose) const
virtual void BuildTargetVel (Eigen::VectorXd &out_vel) const
Protected Member Functions inherited from cExpPDController
virtual void ApplyControlForces (const Eigen::VectorXd &tau)
Protected Member Functions inherited from cController
cController ()
virtual bool ParseParams (const Json::Value &json)
Protected Attributes
Eigen::VectorXd mKp
Eigen::VectorXd mKd
tEigenArr< cPDController > mPDCtrls
tVector mGravity
bool mExternRBDModel
std::shared_ptr< cRBDModel > mRBDModel
Protected Attributes inherited from cExpPDController
tEigenArr< cPDController > mPDCtrls
Protected Attributes inherited from cController
cSimCharacter * mChar
eMode mMode
bool mValid
Additional Inherited Members
Public Types inherited from cController
enum eMode { eModeActive, eModeInactive, eModePassive, eModeMax }
Detailed Description
Definition at line 8 of file ImpPDController.h.
Constructor & Destructor Documentation
cImpPDController()
cImpPDController::cImpPDController ()
Definition at line 9 of file ImpPDController.cpp.
 {
     mExternRBDModel = true;
 #if defined(IMP_PD_CTRL_PROFILER)
     mPerfSolveTime = 0;
     mPerfTotalTime = 0;
     mPerfSolveCount = 0;
     mPerfTotalCount = 0;
 #endif // IMP_PD_CTRL_PROFILER
 }
References mExternRBDModel.
~cImpPDController()
cImpPDController::~cImpPDController () virtual
Definition at line 21 of file ImpPDController.cpp.
 {
 }
Member Function Documentation
BuildRBDModel()
std::shared_ptr< cRBDModel > cImpPDController::BuildRBDModel (const cSimCharacter & character, const tVector & gravity) const protected virtual
Definition at line 122 of file ImpPDController.cpp.
 {
     std::shared_ptr<cRBDModel> model = std::shared_ptr<cRBDModel>(new cRBDModel());
     model->Init(character.GetJointMat(), character.GetBodyDefs(), gravity);
     return model;
 }
References cSimCharacter::GetBodyDefs(), and cCharacter::GetJointMat().
Referenced by Init().
BuildTargetPose()
void cImpPDController::BuildTargetPose (Eigen::VectorXd & out_pose) const protected virtual
Definition at line 197 of file ImpPDController.cpp.
 {
     out_pose = Eigen::VectorXd::Zero(GetNumDof());
     //const auto& joint_mat = mChar->GetJointMat();
     //tVector root_pos = mChar->GetRootPos();
     //tQuaternion root_rot = mChar->GetRootRotation();
     //cKinTree::SetRootPos(joint_mat, root_pos, out_pose);
     //cKinTree::SetRootRot(joint_mat, root_rot, out_pose);
     for (int j = 0; j < GetNumJoints(); ++j)
     {
         const cPDController& pd_ctrl = GetPDCtrl(j);
         if (pd_ctrl.IsValid())
         {
             Eigen::VectorXd curr_pose;
             pd_ctrl.GetTargetTheta(curr_pose);
             int param_offset = mChar->GetParamOffset(j);
             int param_size = mChar->GetParamSize(j);
             out_pose.segment(param_offset, param_size) = curr_pose;
         }
     }
 }
References cExpPDController::GetNumDof(), cExpPDController::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), cExpPDController::GetPDCtrl(), cPDController::GetTargetTheta(), cController::IsValid(), and cController::mChar.
Referenced by CalcControlForces().
BuildTargetVel()
void cImpPDController::BuildTargetVel (Eigen::VectorXd & out_vel) const protected virtual
Definition at line 221 of file ImpPDController.cpp.
 {
     out_vel = Eigen::VectorXd::Zero(GetNumDof());
     //const auto& joint_mat = mChar->GetJointMat();
     //tVector root_vel = mChar->GetRootVel();
     //tVector root_ang_vel = mChar->GetRootAngVel();
     //cKinTree::SetRootVel(joint_mat, root_vel, out_vel);
     //cKinTree::SetRootAngVel(joint_mat, root_ang_vel, out_vel);
     for (int j = 0; j < GetNumJoints(); ++j)
     {
         const cPDController& pd_ctrl = GetPDCtrl(j);
         if (pd_ctrl.IsValid())
         {
             Eigen::VectorXd curr_vel;
             pd_ctrl.GetTargetVel(curr_vel);
             int param_offset = mChar->GetParamOffset(j);
             int param_size = mChar->GetParamSize(j);
             out_vel.segment(param_offset, param_size) = curr_vel;
         }
     }
 }
References cExpPDController::GetNumDof(), cExpPDController::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), cExpPDController::GetPDCtrl(), cPDController::GetTargetVel(), cController::IsValid(), and cController::mChar.
Referenced by CalcControlForces().
CalcControlForces()
void cImpPDController::CalcControlForces (double time_step, Eigen::VectorXd & out_tau) protected virtual
Reimplemented from cExpPDController.
Definition at line 136 of file ImpPDController.cpp.
 {
     double t = time_step;
     const Eigen::VectorXd& pose = mChar->GetPose();
     const Eigen::VectorXd& vel = mChar->GetVel();
     Eigen::VectorXd tar_pose;
     Eigen::VectorXd tar_vel;
     BuildTargetPose(tar_pose);
     BuildTargetVel(tar_vel);
     Eigen::DiagonalMatrix<double, Eigen::Dynamic> Kp_mat = mKp.asDiagonal();
     Eigen::DiagonalMatrix<double, Eigen::Dynamic> Kd_mat = mKd.asDiagonal();
     for (int j = 0; j < GetNumJoints(); ++j)
     {
         const cPDController& pd_ctrl = GetPDCtrl(j);
         if (!pd_ctrl.IsValid() || !pd_ctrl.IsActive())
         {
             int param_offset = mChar->GetParamOffset(j);
             int param_size = mChar->GetParamSize(j);
             Kp_mat.diagonal().segment(param_offset, param_size).setZero();
             Kd_mat.diagonal().segment(param_offset, param_size).setZero();
         }
     }
     Eigen::MatrixXd M = mRBDModel->GetMassMat();
     const Eigen::VectorXd& C = mRBDModel->GetBiasForce();
     M.diagonal() += t * mKd;
     Eigen::VectorXd pose_inc;
     const Eigen::MatrixXd& joint_mat = mChar->GetJointMat();
     cKinTree::VelToPoseDiff(joint_mat, pose, vel, pose_inc);
     pose_inc = pose + t * pose_inc;
     cKinTree::PostProcessPose(joint_mat, pose_inc);
     Eigen::VectorXd pose_err;
     cKinTree::CalcVel(joint_mat, pose_inc, tar_pose, 1, pose_err);
     Eigen::VectorXd vel_err = tar_vel - vel;
     Eigen::VectorXd acc = Kp_mat * pose_err + Kd_mat * vel_err - C;
 #if defined(IMP_PD_CTRL_PROFILER)
     TIMER_RECORD_BEG(Solve)
 #endif
     //int root_size = cKinTree::gRootDim;
     //int num_act_dofs = static_cast<int>(acc.size()) - root_size;
     //auto M_act = M.block(root_size, root_size, num_act_dofs, num_act_dofs);
     //auto acc_act = acc.segment(root_size, num_act_dofs);
     //acc_act = M_act.ldlt().solve(acc_act);
     acc = M.ldlt().solve(acc);
 #if defined(IMP_PD_CTRL_PROFILER)
     TIMER_RECORD_END(Solve, mPerfSolveTime, mPerfSolveCount)
 #endif
     out_tau += Kp_mat * pose_err + Kd_mat * (vel_err - t * acc);
 }
References BuildTargetPose(), BuildTargetVel(), cKinTree::CalcVel(), cCharacter::GetJointMat(), cExpPDController::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), cExpPDController::GetPDCtrl(), cCharacter::GetPose(), cCharacter::GetVel(), cPDController::IsActive(), cController::IsValid(), cController::mChar, mKd, mKp, mRBDModel, cKinTree::PostProcessPose(), and cKinTree::VelToPoseDiff().
Referenced by UpdateControlForce().
Clear()
void cImpPDController::Clear () virtual
Reimplemented from cExpPDController.
Definition at line 40 of file ImpPDController.cpp.
 {
     cExpPDController::Clear();
     mExternRBDModel = true;
     mRBDModel.reset();
 }
References cExpPDController::Clear(), mExternRBDModel, and mRBDModel.
Referenced by cCtPDController::Clear().
Init() [1/2]
void cImpPDController::Init (cSimCharacter * character, const Eigen::MatrixXd & pd_params, const tVector & gravity) virtual
Definition at line 25 of file ImpPDController.cpp.
 {
     std::shared_ptr<cRBDModel> model = BuildRBDModel(*character, gravity);
     Init(character, model, pd_params, gravity);
     mExternRBDModel = false;
 }
References BuildRBDModel(), and mExternRBDModel.
Referenced by cCtPDController::SetupPDControllers().
Init() [2/2]
void cImpPDController::Init (cSimCharacter * character, const std::shared_ptr< cRBDModel > & model, const Eigen::MatrixXd & pd_params, const tVector & gravity) virtual
Definition at line 32 of file ImpPDController.cpp.
 {
     cExpPDController::Init(character, pd_params);
     mGravity = gravity;
     mRBDModel = model;
     InitGains();
 }
References cExpPDController::Init(), InitGains(), mGravity, and mRBDModel.
InitGains()
void cImpPDController::InitGains () protected virtual
Definition at line 99 of file ImpPDController.cpp.
 {
     int num_dof = GetNumDof();
     mKp = Eigen::VectorXd::Zero(num_dof);
     mKd = Eigen::VectorXd::Zero(num_dof);
     for (int j = 0; j < GetNumJoints(); ++j)
     {
         const cPDController& pd_ctrl = GetPDCtrl(j);
         if (pd_ctrl.IsValid())
         {
             int param_offset = mChar->GetParamOffset(j);
             int param_size = mChar->GetParamSize(j);
             double kp = pd_ctrl.GetKp();
             double kd = pd_ctrl.GetKd();
             mKp.segment(param_offset, param_size) = Eigen::VectorXd::Ones(param_size) * kp;
             mKd.segment(param_offset, param_size) = Eigen::VectorXd::Ones(param_size) * kd;
         }
     }
 }
References cPDController::GetKd(), cPDController::GetKp(), cExpPDController::GetNumDof(), cExpPDController::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), cExpPDController::GetPDCtrl(), cController::IsValid(), cController::mChar, mKd, and mKp.
Referenced by Init().
SetKd()
void cImpPDController::SetKd (int joint_id, double kd) virtual
Reimplemented from cExpPDController.
Definition at line 87 of file ImpPDController.cpp.
 {
     cExpPDController::SetKd(joint_id, kd);
     int param_offset = mChar->GetParamOffset(joint_id);
     int param_size = mChar->GetParamSize(joint_id);
     auto curr_kd = mKd.segment(param_offset, param_size);
     curr_kd.setOnes();
     curr_kd *= kd;
 }
References cCharacter::GetParamOffset(), cCharacter::GetParamSize(), cController::mChar, mKd, and cExpPDController::SetKd().
SetKp()
void cImpPDController::SetKp (int joint_id, double kp) virtual
Reimplemented from cExpPDController.
Definition at line 75 of file ImpPDController.cpp.
 {
     cExpPDController::SetKp(joint_id, kp);
     int param_offset = mChar->GetParamOffset(joint_id);
     int param_size = mChar->GetParamSize(joint_id);
     auto curr_kp = mKp.segment(param_offset, param_size);
     curr_kp.setOnes();
     curr_kp *= kp;
 }
References cCharacter::GetParamOffset(), cCharacter::GetParamSize(), cController::mChar, mKp, and cExpPDController::SetKp().
Referenced by cCtVelController::SetupPDControllers().
UpdateControlForce()
void cImpPDController::UpdateControlForce (double time_step, Eigen::VectorXd & out_tau) virtual
Reimplemented from cExpPDController.
Definition at line 47 of file ImpPDController.cpp.
 {
     cController::Update(time_step);
 #if defined(IMP_PD_CTRL_PROFILER)
     TIMER_RECORD_BEG(Update_Ctrl_Force)
 #endif
     if (time_step > 0)
     {
         if (!mExternRBDModel)
         {
             UpdateRBDModel();
         }
         CalcControlForces(time_step, out_tau);
     }
 #if defined(IMP_PD_CTRL_PROFILER)
     TIMER_RECORD_END(Update_Ctrl_Force, mPerfTotalTime, mPerfTotalCount)
 #endif
 #if defined(IMP_PD_CTRL_PROFILER)
     printf("Solve Time: %.5f\n", mPerfSolveTime);
     printf("Total Time: %.5f\n", mPerfTotalTime);
 #endif
 }
References CalcControlForces(), mExternRBDModel, cController::Update(), and UpdateRBDModel().
Referenced by cCtPDController::UpdatePDCtrls().
UpdateRBDModel()
void cImpPDController::UpdateRBDModel () protected virtual
Definition at line 129 of file ImpPDController.cpp.
 {
     const Eigen::VectorXd& pose = mChar->GetPose();
     const Eigen::VectorXd& vel = mChar->GetVel();
     mRBDModel->Update(pose, vel);
 }
References cCharacter::GetPose(), cCharacter::GetVel(), cController::mChar, and mRBDModel.
Referenced by UpdateControlForce().
Member Data Documentation
mExternRBDModel
bool cImpPDController::mExternRBDModel protected
Definition at line 30 of file ImpPDController.h.
Referenced by cImpPDController(), Clear(), Init(), and UpdateControlForce().
mGravity
tVector cImpPDController::mGravity protected
Definition at line 29 of file ImpPDController.h.
Referenced by Init().
mKd
Eigen::VectorXd cImpPDController::mKd protected
Definition at line 26 of file ImpPDController.h.
Referenced by CalcControlForces(), InitGains(), and SetKd().
mKp
Eigen::VectorXd cImpPDController::mKp protected
Definition at line 25 of file ImpPDController.h.
Referenced by CalcControlForces(), InitGains(), and SetKp().
mPDCtrls
tEigenArr<cPDController> cImpPDController::mPDCtrls protected
Definition at line 27 of file ImpPDController.h.
mRBDModel
std::shared_ptr<cRBDModel> cImpPDController::mRBDModel protected
Definition at line 31 of file ImpPDController.h.
Referenced by CalcControlForces(), Clear(), Init(), and UpdateRBDModel().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/ImpPDController.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/ImpPDController.cpp