My Project: cCircularBuffer< tVal, tAlloc > Class Template Reference
cCircularBuffer< tVal, tAlloc > Class Template Reference
#include <CircularBuffer.h>
Public Member Functions
cCircularBuffer ()
cCircularBuffer (size_t capacity)
virtual ~cCircularBuffer ()
virtual void Reserve (size_t capacity)
virtual void Clear ()
virtual size_t GetSize () const
virtual size_t GetCapacity () const
virtual void Add (const tVal &val)
virtual const tVal & operator[] (size_t i) const
virtual tVal & operator[] (size_t i)
Protected Member Functions
virtual size_t CalcIdx (size_t i) const
Protected Attributes
size_t mHead
size_t mSize
std::vector< tVal, tAlloc > mData
Detailed Description
template<typename tVal, typename tAlloc = std::allocator<tVal>>
class cCircularBuffer< tVal, tAlloc >
Definition at line 5 of file CircularBuffer.h.
Constructor & Destructor Documentation
cCircularBuffer() [1/2]
template<typename tVal , typename tAlloc > cCircularBuffer< tVal, tAlloc >::cCircularBuffer ()
Definition at line 30 of file CircularBuffer.h.
                                                :
         cCircularBuffer(0)
 {
 }
cCircularBuffer() [2/2]
template<typename tVal , typename tAlloc > cCircularBuffer< tVal, tAlloc >::cCircularBuffer (size_t capacity)
Definition at line 36 of file CircularBuffer.h.
 {
     mHead = 0;
     mSize = 0;
     Reserve(capacity);
 }
~cCircularBuffer()
template<typename tVal , typename tAlloc > cCircularBuffer< tVal, tAlloc >::~cCircularBuffer () virtual
Definition at line 44 of file CircularBuffer.h.
 {
 }
Member Function Documentation
Add()
template<typename tVal, typename tAlloc > void cCircularBuffer< tVal, tAlloc >::Add (const tVal & val) virtual
Definition at line 91 of file CircularBuffer.h.
 {
     mData[mHead] = val;
     size_t capacity = GetCapacity();
     mHead = (mHead + 1) % capacity;
     mSize = std::min((mSize + 1), capacity);
 }
Referenced by cDeepMimicCharController::LogVal(), cObjTracer::UpdateTraceCOM(), cObjTracer::UpdateTraceContact(), and cObjTracer::UpdateTracePos().
CalcIdx()
template<typename tVal , typename tAlloc > size_t cCircularBuffer< tVal, tAlloc >::CalcIdx (size_t i) const protected virtual
Definition at line 114 of file CircularBuffer.h.
 {
     size_t idx = (mHead + i) % GetSize();
     return idx;
 }
Clear()
template<typename tVal , typename tAlloc > void cCircularBuffer< tVal, tAlloc >::Clear () virtual
Definition at line 72 of file CircularBuffer.h.
 {
     mHead = 0;
     mSize = 0;
 }
Referenced by cDeepMimicCharController::ResetParams(), and cObjTracer::ResetTrace().
GetCapacity()
template<typename tVal , typename tAlloc > size_t cCircularBuffer< tVal, tAlloc >::GetCapacity () const virtual
Definition at line 85 of file CircularBuffer.h.
 {
     return mData.size();
 }
Referenced by cDrawSimCharacter::DrawInfoValLog().
GetSize()
template<typename tVal , typename tAlloc > size_t cCircularBuffer< tVal, tAlloc >::GetSize () const virtual
Definition at line 79 of file CircularBuffer.h.
 {
     return mSize;
 }
Referenced by cDrawSimCharacter::DrawInfoValLog(), cObjTracer::DrawTraceContact(), and cObjTracer::DrawTracePos().
operator[]() [1/2]
template<typename tVal , typename tAlloc > tVal & cCircularBuffer< tVal, tAlloc >::operator[] (size_t i) virtual
Definition at line 107 of file CircularBuffer.h.
 {
     size_t idx = CalcIdx(i);
     return mData[idx];
 }
operator[]() [2/2]
template<typename tVal , typename tAlloc > const tVal & cCircularBuffer< tVal, tAlloc >::operator[] (size_t i) const virtual
Definition at line 100 of file CircularBuffer.h.
 {
     size_t idx = CalcIdx(i);
     return mData[idx];
 }
Reserve()
template<typename tVal , typename tAlloc > void cCircularBuffer< tVal, tAlloc >::Reserve (size_t capacity) virtual
Definition at line 49 of file CircularBuffer.h.
 {
     size_t prev_size = mData.size();
     mData.resize(capacity);
     if (prev_size > 0 && capacity > prev_size)
     {
         for (size_t i = mHead; i < prev_size; ++i)
         {
             size_t old_idx = prev_size - 1 - (i - mHead);
             size_t new_idx = capacity - 1 - (i - mHead);
             mData[new_idx] = mData[i];
         }
     }
     mSize = std::min(mSize, capacity);
     if (mHead > capacity)
     {
         mHead = 0;
     }
 }
Referenced by cObjTracer::BuildTrace(), and cDeepMimicCharController::cDeepMimicCharController().
Member Data Documentation
mData
template<typename tVal, typename tAlloc = std::allocator<tVal>> std::vector<tVal, tAlloc> cCircularBuffer< tVal, tAlloc >::mData protected
Definition at line 24 of file CircularBuffer.h.
mHead
template<typename tVal, typename tAlloc = std::allocator<tVal>> size_t cCircularBuffer< tVal, tAlloc >::mHead protected
Definition at line 22 of file CircularBuffer.h.
mSize
template<typename tVal, typename tAlloc = std::allocator<tVal>> size_t cCircularBuffer< tVal, tAlloc >::mSize protected
Definition at line 23 of file CircularBuffer.h.
The documentation for this class was generated from the following file:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/CircularBuffer.h