My Project: cSimCapsule Class Reference
cSimCapsule Class Reference
#include <SimCapsule.h>
Classes
struct tParams
Public Member Functions
cSimCapsule ()
virtual ~cSimCapsule ()
virtual void Init (const std::shared_ptr< cWorld > &world, const tParams &params)
virtual double GetHeight () const
virtual double GetRadius () const
virtual cShape::eShape GetShape () const
virtual tVector GetSize () const
Public Member Functions inherited from cSimRigidBody
virtual ~cSimRigidBody ()
virtual void SetPos (const tVector &pos)
virtual void SetRotation (const tVector &axis, double theta)
virtual void SetRotation (const tQuaternion &q)
virtual tVector GetLinearVelocity () const
virtual tVector GetLinearVelocity (const tVector &local_pos) const
virtual void SetLinearVelocity (const tVector &vel)
virtual tVector GetAngularVelocity () const
virtual void SetAngularVelocity (const tVector &vel)
virtual void SetDamping (double linear_damping, double angular_damping)
virtual double GetMass () const
virtual void ApplyForce (const tVector &force)
virtual void ApplyForce (const tVector &force, const tVector &local_pos)
virtual void ApplyTorque (const tVector &torque)
virtual void ClearForces ()
virtual void SetKinematicObject (bool is_kin)
virtual bool IsKinematicObject () const
virtual void DisableDeactivation ()
virtual void Constrain (const tVector &linear_factor, const tVector &angular_factor)
virtual bool HasSimBody () const
virtual const std::unique_ptr< btRigidBody > & GetSimBody () const
Public Member Functions inherited from cSimObj
virtual ~cSimObj ()
virtual tVector GetPos () const
virtual void GetRotation (tVector &out_axis, double &out_theta) const
virtual tQuaternion GetRotation () const
virtual tMatrix GetWorldTransform () const
virtual tMatrix GetLocalTransform () const
virtual tVector WorldToLocalPos (const tVector &world_pos) const
virtual tVector LocalToWorldPos (const tVector &local_pos) const
virtual tMatrix3 GetLocalToWorldRotMat () const
virtual tVector CalcCOM () const
virtual tVector CalcCOMVel () const
virtual void RegisterContact ()
virtual void RegisterContact (int contact_flags, int filter_flags)
virtual void UpdateContact (int contact_flags, int filter_flags)
virtual const cContactManager::tContactHandle & GetContactHandle () const
virtual bool IsInContact () const
virtual const tEigenArr< cContactManager::tContactPt > & GetContactPts () const
virtual short GetColGroup () const
virtual void SetColGroup (short col_group)
virtual short GetColMask () const
virtual void SetColMask (short col_mask)
virtual eType GetType () const
virtual void CalcAABB (tVector &out_min, tVector &out_max) const
virtual const btCollisionShape * GetCollisionShape () const
Additional Inherited Members
Public Types inherited from cSimObj
enum eType { eTypeDynamic, eTypeStatic, eTypeMax }
Protected Member Functions inherited from cSimRigidBody
cSimRigidBody ()
virtual void Init (const std::shared_ptr< cWorld > &world)
virtual void AddToWorld (const std::shared_ptr< cWorld > &world)
virtual void RemoveFromWorld ()
virtual const btCollisionObject * GetCollisionObject () const
virtual btCollisionObject * GetCollisionObject ()
virtual int GetNumConstraints () const
virtual cWorld::tConstraintHandle GetConstraint (int c) const
Protected Member Functions inherited from cSimObj
cSimObj ()
virtual const std::shared_ptr< cWorld > & GetWorld () const
Protected Attributes inherited from cSimRigidBody
std::unique_ptr< btRigidBody > mSimBody
Protected Attributes inherited from cSimObj
std::shared_ptr< cWorld > mWorld
std::unique_ptr< btCollisionShape > mColShape
cContactManager::tContactHandle mContactHandle
bool mEnableContactFall
eType mType
short mColGroup
short mColMask
Detailed Description
Definition at line 5 of file SimCapsule.h.
Constructor & Destructor Documentation
cSimCapsule()
cSimCapsule::cSimCapsule ()
Definition at line 16 of file SimCapsule.cpp.
 {
 }
~cSimCapsule()
cSimCapsule::~cSimCapsule () virtual
Definition at line 20 of file SimCapsule.cpp.
 {
 }
Member Function Documentation
GetHeight()
double cSimCapsule::GetHeight () const virtual
Definition at line 43 of file SimCapsule.cpp.
 {
     tVector size = GetSize();
     return size[1] - size[0];
 }
References GetSize().
GetRadius()
double cSimCapsule::GetRadius () const virtual
Definition at line 49 of file SimCapsule.cpp.
 {
     tVector size = GetSize();
     return 0.5 * size[0];
 }
References GetSize().
GetShape()
cShape::eShape cSimCapsule::GetShape () const virtual
Reimplemented from cSimObj.
Definition at line 55 of file SimCapsule.cpp.
 {
     return cShape::eShapeCapsule;
 }
References cShape::eShapeCapsule.
GetSize()
tVector cSimCapsule::GetSize () const virtual
Implements cSimObj.
Definition at line 60 of file SimCapsule.cpp.
 {
     return mWorld->GetSizeCapsule(*this);
 }
References cSimObj::mWorld.
Referenced by GetHeight(), and GetRadius().
Init()
void cSimCapsule::Init (const std::shared_ptr< cWorld > & world, const tParams & params) virtual
Definition at line 24 of file SimCapsule.cpp.
 {
     mType = params.mType;
     btScalar mass = (params.mType == eTypeDynamic) ? static_cast<btScalar>(params.mMass) : 0;
     mColShape = std::unique_ptr<btCollisionShape>(world->BuildCapsuleShape(params.mRadius, params.mHeight));
     btVector3 inertia(0, 0, 0);
     mColShape->calculateLocalInertia(mass, inertia);
     btRigidBody::btRigidBodyConstructionInfo cons_info(mass, this, mColShape.get(), inertia);
     mSimBody = std::unique_ptr<btRigidBody>(new btRigidBody(cons_info));
     mSimBody->setFriction(static_cast<btScalar>(params.mFriction));
     cSimRigidBody::Init(world);
     SetPos(params.mPos);
     SetRotation(params.mAxis, params.mTheta);
 }
References cSimObj::eTypeDynamic, cSimRigidBody::Init(), cSimCapsule::tParams::mAxis, cSimObj::mColShape, cSimCapsule::tParams::mFriction, cSimCapsule::tParams::mHeight, cSimCapsule::tParams::mMass, cSimCapsule::tParams::mPos, cSimCapsule::tParams::mRadius, cSimRigidBody::mSimBody, cSimCapsule::tParams::mTheta, cSimCapsule::tParams::mType, cSimObj::mType, cSimRigidBody::SetPos(), and cSimRigidBody::SetRotation().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimCapsule.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimCapsule.cpp