My Project: cCamera Class Reference
cCamera Class Reference
#include <Camera.h>
Public Types
enum eProj { eProjPerspective, eProjOrtho, eProjMax }
Public Member Functions
cCamera ()
cCamera (eProj proj, const tVector &pos, const tVector &focus, const tVector &up, double w, double h, double near_z, double far_z)
virtual ~cCamera ()
virtual const tVector & GetPosition () const
virtual tVector GetFocus () const
virtual const tVector & GetUp () const
virtual tVector GetViewDir () const
virtual double GetWidth () const
virtual double GetHeight () const
virtual double GetAspectRatio () const
virtual double GetNearZ () const
virtual double GetFarZ () const
virtual double CalcFOV () const
virtual void SetPosition (const tVector &pos)
virtual void SetFocus (const tVector &focus)
virtual void SetUp (const tVector &up)
virtual void SetNearZ (double near_z)
virtual void SetFarZ (double far_z)
virtual void Resize (double w, double h)
virtual void SetViewWidth (double w)
virtual void SetViewHeight (double h)
virtual void TranslatePos (const tVector &pos)
virtual void TranslateFocus (const tVector &focus)
virtual void RotatePos (const tVector &axis, double theta)
virtual void RotatePos (const tQuaternion &quat)
virtual tVector ScreenToWorldPos (const tVector &screen_pos) const
virtual tVector ProjectToFocalPlane (const tVector &world_pos) const
virtual tMatrix BuildViewWorldMatrix () const
virtual tMatrix BuildWorldViewMatrix () const
virtual tMatrix BuildProjMatrix () const
virtual void SetProj (eProj proj)
virtual eProj GetProj () const
virtual void SetupGLView () const
virtual void SetupGLProj () const
virtual tVector GetRayCastDir (const tVector &pos) const
virtual void MouseClick (int button, int state, double x, double y)
virtual void MouseMove (double x, double y)
Protected Member Functions
virtual double CalcFocalLen () const
virtual tMatrix BuildProjMatrixOrtho () const
virtual tMatrix BuildProjMatrixProj () const
virtual void Zoom (double zoom)
Protected Attributes
eProj mProj
tVector mPosition
tVector mFocusDelta
tVector mUp
double mWidth
double mAspectRatio
double mNearZ
double mFarZ
bool mMouseDown
tVector mMousePos
Detailed Description
Definition at line 5 of file Camera.h.
Member Enumeration Documentation
eProj
enum cCamera::eProj
Enumerator
eProjPerspective
eProjOrtho
eProjMax
Definition at line 10 of file Camera.h.
     {
         eProjPerspective,
         eProjOrtho,
         eProjMax
     };
Constructor & Destructor Documentation
cCamera() [1/2]
cCamera::cCamera ()
Definition at line 7 of file Camera.cpp.
 {
     mPosition = tVector(0, 0, 1, 0);
     mFocusDelta = -mPosition;
     mUp = tVector(0, 1, 0, 0);
     mNearZ = 0;
     mFarZ = 1;
     mProj = eProjPerspective;
     mMouseDown = 0;
     mMousePos = tVector::Zero();
     Resize(1, 1);
 }
References eProjPerspective, mFarZ, mFocusDelta, mMouseDown, mMousePos, mNearZ, mPosition, mProj, mUp, and Resize().
cCamera() [2/2]
cCamera::cCamera (eProj proj, const tVector & pos, const tVector & focus, const tVector & up, double w, double h, double near_z, double far_z)
Definition at line 27 of file Camera.cpp.
 {
     mPosition = pos;
     mFocusDelta = focus - pos;
     mUp = up;
     mNearZ = near_z;
     mFarZ = far_z;
     mProj = proj;
     Resize(w, h);
     mMouseDown = 0;
     mMousePos = tVector::Zero();
 }
References mFarZ, mFocusDelta, mMouseDown, mMousePos, mNearZ, mPosition, mProj, mUp, and Resize().
~cCamera()
cCamera::~cCamera () virtual
Definition at line 23 of file Camera.cpp.
 {
 }
Member Function Documentation
BuildProjMatrix()
tMatrix cCamera::BuildProjMatrix () const virtual
Definition at line 228 of file Camera.cpp.
 {
     tMatrix proj_mat;
     switch (mProj)
     {
     case eProjPerspective:
         proj_mat = BuildProjMatrixProj();
         break;
     case eProjOrtho:
         proj_mat = BuildProjMatrixOrtho();
         break;
     default:
         assert(false); // unsupported projection
         break;
     }
     return proj_mat;
 }
References BuildProjMatrixOrtho(), BuildProjMatrixProj(), eProjOrtho, eProjPerspective, and mProj.
Referenced by SetupGLProj(), and cDrawScene::SetupMeshShader().
BuildProjMatrixOrtho()
tMatrix cCamera::BuildProjMatrixOrtho () const protected virtual
Definition at line 348 of file Camera.cpp.
 {
     tMatrix mat = tMatrix::Identity();
     double w = GetWidth();
     double h = GetHeight();
     mat(0, 0) = 2 / w;
     mat(1, 1) = 2 / h;
     mat(2, 2) = -2 / (mFarZ - mNearZ);
     mat(2, 3) = -(mFarZ + mNearZ) / (mFarZ - mNearZ);
     return mat;
 }
References GetHeight(), GetWidth(), mFarZ, and mNearZ.
Referenced by BuildProjMatrix().
BuildProjMatrixProj()
tMatrix cCamera::BuildProjMatrixProj () const protected virtual
Definition at line 362 of file Camera.cpp.
 {
     tMatrix mat = tMatrix::Zero();
     double focal_len = CalcFocalLen();
     double w = GetWidth();
     double h = GetHeight();
     mat(0, 0) = 2 * focal_len / w;
     mat(1, 1) = 2 * focal_len / h;
     mat(2, 2) = -(mFarZ + mNearZ) / (mFarZ - mNearZ);
     mat(2, 3) = -2 * mFarZ * mNearZ / (mFarZ - mNearZ);
     mat(3, 2) = -1;
     return mat;
 }
References CalcFocalLen(), GetHeight(), GetWidth(), mFarZ, and mNearZ.
Referenced by BuildProjMatrix().
BuildViewWorldMatrix()
tMatrix cCamera::BuildViewWorldMatrix () const virtual
Definition at line 203 of file Camera.cpp.
 {
     tVector up = GetUp();
     const tVector& forward = GetViewDir();
     tVector left = up.cross3(forward).normalized();
     up = -left.cross3(forward).normalized();
     const tVector& pos = GetPosition();
     tMatrix T;
     T.col(0) = -left;
     T.col(1) = up;
     T.col(2) = -forward;
     T.col(3) = pos;
     T(3, 3) = 1;
     return T;
 }
References GetPosition(), GetUp(), and GetViewDir().
Referenced by BuildWorldViewMatrix(), ScreenToWorldPos(), and cDrawScene::SetupMeshShader().
BuildWorldViewMatrix()
tMatrix cCamera::BuildWorldViewMatrix () const virtual
Definition at line 221 of file Camera.cpp.
 {
     tMatrix view_world = BuildViewWorldMatrix();
     tMatrix world_view = cMathUtil::InvRigidMat(view_world);
     return world_view;
 }
References BuildViewWorldMatrix(), and cMathUtil::InvRigidMat().
Referenced by SetupGLView(), and cDrawScene::SetupMeshShader().
CalcFocalLen()
double cCamera::CalcFocalLen () const protected virtual
Definition at line 343 of file Camera.cpp.
 {
     return mFocusDelta.norm();
 }
References mFocusDelta.
Referenced by BuildProjMatrixProj(), CalcFOV(), and ScreenToWorldPos().
CalcFOV()
double cCamera::CalcFOV () const virtual
Definition at line 92 of file Camera.cpp.
 {
     double focal_len = CalcFocalLen();
     double h = GetHeight();
     double fov = std::atan(h * 0.5 / focal_len) * 2;
     return fov;
 }
References CalcFocalLen(), and GetHeight().
GetAspectRatio()
double cCamera::GetAspectRatio () const virtual
Definition at line 76 of file Camera.cpp.
 {
     return mAspectRatio;
 }
References mAspectRatio.
Referenced by cDrawSimCharacter::DrawInfoValLog().
GetFarZ()
double cCamera::GetFarZ () const virtual
Definition at line 87 of file Camera.cpp.
 {
     return mFarZ;
 }
References mFarZ.
GetFocus()
tVector cCamera::GetFocus () const virtual
Definition at line 48 of file Camera.cpp.
 {
     return mFocusDelta + mPosition;
 }
References mFocusDelta, and mPosition.
Referenced by cDrawScene::DoShadowPass(), cDrawScene::DrawGrid(), cDrawSceneSimChar::DrawGround(), cDrawScene::GetCamStillSnapDistX(), MouseMove(), ProjectToFocalPlane(), RotatePos(), SetPosition(), cDrawScene::SetupMeshShader(), cDrawScene::UpdateCameraStill(), cDrawScene::UpdateCameraTracking(), and Zoom().
GetHeight()
double cCamera::GetHeight () const virtual
Definition at line 71 of file Camera.cpp.
 {
     return mWidth / mAspectRatio;
 }
References mAspectRatio, and mWidth.
Referenced by BuildProjMatrixOrtho(), BuildProjMatrixProj(), CalcFOV(), cDrawScene::DrawGrid(), cDrawSceneSimChar::DrawGround(), cDrawSceneSimChar::GetCamStillPos(), MouseMove(), cDrawScene::ResizeCamera(), ScreenToWorldPos(), cDrawScene::UpdateCameraStill(), cDrawScene::UpdateCameraTracking(), and Zoom().
GetNearZ()
double cCamera::GetNearZ () const virtual
Definition at line 82 of file Camera.cpp.
 {
     return mNearZ;
 }
References mNearZ.
Referenced by cDrawScene::GetCamStillSnapDistX(), and cDrawScene::SetupMeshShader().
GetPosition()
const tVector & cCamera::GetPosition () const virtual
Definition at line 43 of file Camera.cpp.
 {
     return mPosition;
 }
References mPosition.
Referenced by BuildViewWorldMatrix(), cDrawScene::GetCamStillSnapDistX(), RotatePos(), cDrawScene::SetupMeshShader(), and cDrawScene::UpdateCameraTracking().
GetProj()
cCamera::eProj cCamera::GetProj () const virtual
Definition at line 251 of file Camera.cpp.
 {
     return mProj;
 }
References mProj.
GetRayCastDir()
tVector cCamera::GetRayCastDir (const tVector & pos) const virtual
Definition at line 268 of file Camera.cpp.
 {
     tVector dir = tVector::Zero();
     switch (mProj)
     {
     case eProjPerspective:
         dir = pos - mPosition;
         break;
     case eProjOrtho:
         dir = mFocusDelta;
         break;
     default:
         assert(false); // unsupported projection
         break;
     }
     dir[3] = 0;
     dir = dir.normalized();
     return dir;
 }
References eProjOrtho, eProjPerspective, mFocusDelta, mPosition, and mProj.
Referenced by cDrawSceneSimChar::MouseClick(), ProjectToFocalPlane(), and ScreenToWorldPos().
GetUp()
const tVector & cCamera::GetUp () const virtual
Definition at line 53 of file Camera.cpp.
 {
     return mUp;
 }
References mUp.
Referenced by BuildViewWorldMatrix().
GetViewDir()
tVector cCamera::GetViewDir () const virtual
Definition at line 58 of file Camera.cpp.
 {
     tVector dir = mFocusDelta;
     dir[3] = 0;
     dir = dir.normalized();
     return dir;
 }
References mFocusDelta.
Referenced by BuildViewWorldMatrix(), and ProjectToFocalPlane().
GetWidth()
double cCamera::GetWidth () const virtual
Definition at line 67 of file Camera.cpp.
 {
     return mWidth;
 }
References mWidth.
Referenced by BuildProjMatrixOrtho(), BuildProjMatrixProj(), cDrawScene::DrawGrid(), cDrawSceneSimChar::DrawGround(), cDrawSceneSimChar::GetCamStillPos(), cDrawScene::GetCamStillSnapDistX(), MouseMove(), cDrawScene::ResizeCamera(), ScreenToWorldPos(), cDrawScene::UpdateCameraStill(), cDrawScene::UpdateCameraTracking(), and Zoom().
MouseClick()
void cCamera::MouseClick (int button, int state, double x, double y) virtual
Definition at line 288 of file Camera.cpp.
 {
     mMouseDown = (button == GLUT_RIGHT_BUTTON) && (state == GLUT_DOWN);
     mMousePos[0] = x;
     mMousePos[1] = y;
     bool mouse_wheel = (button == 3) || (button == 4);
     if (mouse_wheel)
     {
         double zoom = (button == 3) ? -0.05 : 0.05;
         Zoom(zoom);
     }
 }
References mMouseDown, mMousePos, and Zoom().
Referenced by cDrawScene::MouseClick().
MouseMove()
void cCamera::MouseMove (double x, double y) virtual
Definition at line 302 of file Camera.cpp.
 {
     if (mMouseDown)
     {
         int mouse_mod = glutGetModifiers();
         double w = GetWidth();
         double h = GetHeight();
         double dx = x - mMousePos[0];
         double dy = y - mMousePos[1];
         tVector focus = GetFocus();
         tVector cam_offset = -mFocusDelta;
         tVector cam_dir = -cam_offset.normalized();
         tVector right = -mUp.cross3(cam_dir).normalized();
         mUp = right.cross3(cam_dir).normalized();
         if (mouse_mod & GLUT_ACTIVE_ALT) {
             // translate
             tVector delta = 0.5 * (-w * right * dx - h * mUp * dy);
             mPosition += delta;
             focus += delta;
         }
         else
         {
             // rotate
             tMatrix rot_mat = cMathUtil::RotateMat(tVector(0, 1, 0, 0), -M_PI * dx)
                 * cMathUtil::RotateMat(right, M_PI * dy);
             cam_offset = rot_mat * cam_offset;
             mUp = rot_mat * mUp;
             mPosition = focus + cam_offset;
         }
         SetFocus(focus);
         // Remember mouse coords for next time.
         mMousePos[0] = x;
         mMousePos[1] = y;
     }
 }
References GetFocus(), GetHeight(), GetWidth(), mFocusDelta, mMouseDown, mMousePos, mPosition, mUp, cMathUtil::RotateMat(), and SetFocus().
Referenced by cDrawScene::MouseMove().
ProjectToFocalPlane()
tVector cCamera::ProjectToFocalPlane (const tVector & world_pos) const virtual
Definition at line 192 of file Camera.cpp.
 {
     tVector dir = GetRayCastDir(world_pos);
     tVector origin = GetFocus();
     tVector norm = GetViewDir();
     tVector delta = world_pos - origin;
     double t = (origin - world_pos).dot(norm) / dir.dot(norm);
     tVector proj_pos = t * dir + world_pos;
     return proj_pos;
 }
References GetFocus(), GetRayCastDir(), and GetViewDir().
Referenced by cDrawSceneSimChar::ApplyUIForce().
Resize()
void cCamera::Resize (double w, double h) virtual
Definition at line 130 of file Camera.cpp.
 {
     mWidth = w;
     mAspectRatio = w / h;
 }
References mAspectRatio, and mWidth.
Referenced by cCamera(), cDrawScene::ResizeCamera(), SetViewHeight(), SetViewWidth(), and Zoom().
RotatePos() [1/2]
void cCamera::RotatePos (const tQuaternion & quat) virtual
Definition at line 164 of file Camera.cpp.
 {
     tVector pos = GetPosition() - GetFocus();
     pos = cMathUtil::QuatRotVec(quat, pos);
     pos += GetFocus();
     SetPosition(pos);
 }
References GetFocus(), GetPosition(), cMathUtil::QuatRotVec(), and SetPosition().
RotatePos() [2/2]
void cCamera::RotatePos (const tVector & axis, double theta) virtual
Definition at line 158 of file Camera.cpp.
 {
     tQuaternion q = cMathUtil::AxisAngleToQuaternion(axis, theta);
     RotatePos(q);
 }
References cMathUtil::AxisAngleToQuaternion().
ScreenToWorldPos()
tVector cCamera::ScreenToWorldPos (const tVector & screen_pos) const virtual
Definition at line 173 of file Camera.cpp.
 {
     tMatrix T = BuildViewWorldMatrix();
     double w = GetWidth();
     double h = GetHeight();
     double focal_len = CalcFocalLen();
     tVector view_pos = tVector(0.5 * screen_pos[0] * w,
         0.5 * screen_pos[1] * h,
         -focal_len, 1);
     tVector world_pos = T * view_pos;
     world_pos[3] = 0;
     tVector dir = GetRayCastDir(world_pos);
     world_pos += -dir * (focal_len - mNearZ);
     return world_pos;
 }
References BuildViewWorldMatrix(), CalcFocalLen(), GetHeight(), GetRayCastDir(), GetWidth(), and mNearZ.
Referenced by cDrawSceneSimChar::ApplyUIForce(), and cDrawSceneSimChar::MouseClick().
SetFarZ()
void cCamera::SetFarZ (double far_z) virtual
Definition at line 124 of file Camera.cpp.
 {
     assert(far_z > mNearZ);
     mFarZ = far_z;
 }
References mFarZ, and mNearZ.
SetFocus()
void cCamera::SetFocus (const tVector & focus) virtual
Definition at line 108 of file Camera.cpp.
 {
     mFocusDelta = focus - mPosition;
 }
References mFocusDelta, and mPosition.
Referenced by cDrawScene::DoShadowPass(), MouseMove(), and Zoom().
SetNearZ()
void cCamera::SetNearZ (double near_z) virtual
Definition at line 118 of file Camera.cpp.
 {
     assert(near_z < mFarZ);
     mNearZ = near_z;
 }
References mFarZ, and mNearZ.
SetPosition()
void cCamera::SetPosition (const tVector & pos) virtual
Definition at line 101 of file Camera.cpp.
 {
     tVector focus = GetFocus();
     mPosition = pos;
     mFocusDelta = focus - mPosition;
 }
References GetFocus(), mFocusDelta, and mPosition.
Referenced by cDrawScene::DoShadowPass(), and RotatePos().
SetProj()
void cCamera::SetProj (eProj proj) virtual
Definition at line 246 of file Camera.cpp.
 {
     mProj = proj;
 }
References mProj.
SetUp()
void cCamera::SetUp (const tVector & up) virtual
Definition at line 113 of file Camera.cpp.
 {
     mUp = up;
 }
References mUp.
SetupGLProj()
void cCamera::SetupGLProj () const virtual
Definition at line 262 of file Camera.cpp.
 {
     tMatrix proj_mat = BuildProjMatrix();
     cDrawUtil::LoadMatrixProj(proj_mat);
 }
References BuildProjMatrix(), and cDrawUtil::LoadMatrixProj().
Referenced by cDrawScene::DoShadowPass(), and cDrawScene::SetupView().
SetupGLView()
void cCamera::SetupGLView () const virtual
Definition at line 256 of file Camera.cpp.
 {
     tMatrix world_view = BuildWorldViewMatrix();
     cDrawUtil::LoadMatrixView(world_view);
 }
References BuildWorldViewMatrix(), and cDrawUtil::LoadMatrixView().
Referenced by cDrawScene::DoShadowPass(), and cDrawScene::SetupView().
SetViewHeight()
void cCamera::SetViewHeight (double h) virtual
Definition at line 142 of file Camera.cpp.
 {
     double w = h * mAspectRatio;
     Resize(w, h);
 }
References mAspectRatio, and Resize().
SetViewWidth()
void cCamera::SetViewWidth (double w) virtual
Definition at line 136 of file Camera.cpp.
 {
     double h = w / mAspectRatio;
     Resize(w, h);
 }
References mAspectRatio, and Resize().
TranslateFocus()
void cCamera::TranslateFocus (const tVector & focus) virtual
Definition at line 153 of file Camera.cpp.
 {
     mPosition = focus - mFocusDelta;
 }
References mFocusDelta, and mPosition.
Referenced by cDrawScene::ResetCamera(), cDrawScene::UpdateCameraStill(), and cDrawScene::UpdateCameraTracking().
TranslatePos()
void cCamera::TranslatePos (const tVector & pos) virtual
Definition at line 148 of file Camera.cpp.
 {
     mPosition = pos;
 }
References mPosition.
Zoom()
void cCamera::Zoom (double zoom) protected virtual
Definition at line 378 of file Camera.cpp.
 {
     tVector focus = GetFocus();
     tVector cam_offset = -mFocusDelta;
     double w = GetWidth();
     double h = GetHeight();
     double delta_scale = 1 - zoom;
     tVector delta = cam_offset * delta_scale;
     mPosition = focus + delta;
     w *= delta_scale;
     h *= delta_scale;
     Resize(w, h);
     SetFocus(focus);
 }
References GetFocus(), GetHeight(), GetWidth(), mFocusDelta, mPosition, Resize(), and SetFocus().
Referenced by MouseClick().
Member Data Documentation
mAspectRatio
double cCamera::mAspectRatio protected
Definition at line 73 of file Camera.h.
Referenced by GetAspectRatio(), GetHeight(), Resize(), SetViewHeight(), and SetViewWidth().
mFarZ
double cCamera::mFarZ protected
Definition at line 75 of file Camera.h.
Referenced by BuildProjMatrixOrtho(), BuildProjMatrixProj(), cCamera(), GetFarZ(), SetFarZ(), and SetNearZ().
mFocusDelta
tVector cCamera::mFocusDelta protected
Definition at line 69 of file Camera.h.
Referenced by CalcFocalLen(), cCamera(), GetFocus(), GetRayCastDir(), GetViewDir(), MouseMove(), SetFocus(), SetPosition(), TranslateFocus(), and Zoom().
mMouseDown
bool cCamera::mMouseDown protected
Definition at line 77 of file Camera.h.
Referenced by cCamera(), MouseClick(), and MouseMove().
mMousePos
tVector cCamera::mMousePos protected
Definition at line 78 of file Camera.h.
Referenced by cCamera(), MouseClick(), and MouseMove().
mNearZ
double cCamera::mNearZ protected
Definition at line 74 of file Camera.h.
Referenced by BuildProjMatrixOrtho(), BuildProjMatrixProj(), cCamera(), GetNearZ(), ScreenToWorldPos(), SetFarZ(), and SetNearZ().
mPosition
tVector cCamera::mPosition protected
Definition at line 68 of file Camera.h.
Referenced by cCamera(), GetFocus(), GetPosition(), GetRayCastDir(), MouseMove(), SetFocus(), SetPosition(), TranslateFocus(), TranslatePos(), and Zoom().
mProj
eProj cCamera::mProj protected
Definition at line 66 of file Camera.h.
Referenced by BuildProjMatrix(), cCamera(), GetProj(), GetRayCastDir(), and SetProj().
mUp
tVector cCamera::mUp protected
Definition at line 70 of file Camera.h.
Referenced by cCamera(), GetUp(), MouseMove(), and SetUp().
mWidth
double cCamera::mWidth protected
Definition at line 72 of file Camera.h.
Referenced by GetHeight(), GetWidth(), and Resize().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/Camera.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/Camera.cpp