My Project: cDrawSceneKinChar Class Reference
cDrawSceneKinChar Class Reference
#include <DrawSceneKinChar.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cDrawSceneKinChar ()
virtual ~cDrawSceneKinChar ()
virtual void Init ()
virtual void Reset ()
virtual void Clear ()
virtual void Update (double time_elapsed)
std::string GetName () const
Public Member Functions inherited from cDrawScene
virtual ~cDrawScene ()
virtual void ParseArgs (const std::shared_ptr< cArgParser > &parser)
virtual void Draw ()
virtual void MouseClick (int button, int state, double device_x, double device_y)
virtual void MouseMove (double device_x, double device_y)
virtual void EnableDrawInfo (bool enable)
Public Member Functions inherited from cScene
virtual ~cScene ()
virtual void Keyboard (unsigned char key, double device_x, double device_y)
virtual void Shutdown ()
virtual bool IsDone () const
virtual double GetTime () const
virtual bool HasRandSeed () const
virtual void SetRandSeed (unsigned long seed)
virtual unsigned long GetRandSeed () const
virtual bool IsEpisodeEnd () const
virtual bool CheckValidEpisode () const
Protected Member Functions
virtual void BuildScene (std::shared_ptr< cSceneKinChar > &out_scene) const
virtual void SetupScene (std::shared_ptr< cSceneKinChar > &out_scene)
virtual void UpdateScene (double time_elapsed)
virtual tVector GetCamTrackPos () const
virtual tVector GetCamStillPos () const
virtual tVector GetDefaultCamFocus () const
virtual void DrawGround () const
virtual void DrawGround3D () const
virtual void DrawCharacters () const
Protected Member Functions inherited from cDrawScene
cDrawScene ()
virtual void ParseCamTrackMode (const std::shared_ptr< cArgParser > &parser, eCamTrackMode &out_mode) const
virtual void Reshape (int w, int h)
virtual void ResizeCamera (int w, int h)
virtual void InitCamera ()
virtual eCamTrackMode GetCamTrackMode () const
virtual void UpdateCamera ()
virtual void UpdateCameraTracking ()
virtual void UpdateCameraStill ()
virtual double GetCamStillSnapDistX () const
virtual void ResetCamera ()
virtual void ClearFrame ()
virtual tVector GetBkgColor () const
virtual void SetupView ()
virtual void RestoreView ()
virtual tVector GetLightDirection () const
virtual void DrawScene ()
virtual void DrawGrid () const
virtual void DrawGroundMainScene ()
virtual void DrawCharacterMainScene ()
virtual void DrawObjsMainScene ()
virtual void DrawMiscMainScene ()
virtual void DrawObjs () const
virtual void DrawMisc () const
virtual void DrawInfo () const
virtual tVector GetVisOffset () const
virtual tVector GetLineColor () const
virtual tVector GetGroundColor () const
virtual void InitRenderResources ()
virtual bool LoadTextures ()
virtual void SetupMeshShader ()
virtual void DoShadowPass ()
Protected Member Functions inherited from cScene
cScene ()
virtual void ResetParams ()
virtual void ResetScene ()
virtual void InitTimers ()
virtual void ResetTimers ()
virtual void UpdateTimers (double timestep)
Protected Attributes
std::shared_ptr< cSceneKinChar > mScene
Protected Attributes inherited from cDrawScene
eCamTrackMode mCamTrackMode
cCamera mCamera
cCamera mShadowCam
bool mDrawInfo
std::unique_ptr< cShadowMap > mShadowMap
std::unique_ptr< cTextureDesc > mGridTex
std::unique_ptr< cShader > mShaderMesh
std::unique_ptr< cShader > mShaderDepth
GLuint mMeshLightDirHandle
GLuint mMeshLightColourHandle
GLuint mMeshAmbientColourHandle
GLuint mMeshShadowProjHandle
GLuint mMeshMaterialDataHandle
GLuint mMeshFogColorHandle
GLuint mMeshFogDataHandle
Protected Attributes inherited from cScene
cRand mRand
bool mHasRandSeed
unsigned long mRandSeed
std::shared_ptr< cArgParser > mArgParser
cTimer::tParams mTimerParams
cTimer mTimer
Additional Inherited Members
Public Types inherited from cDrawScene
enum eCamTrackMode {
eCamTrackModeXZ, eCamTrackModeY, eCamTrackModeXYZ, eCamTrackModeStill,
eCamTrackModeFixed, eCamTrackModeMax
}
Detailed Description
Definition at line 7 of file DrawSceneKinChar.h.
Constructor & Destructor Documentation
cDrawSceneKinChar()
cDrawSceneKinChar::cDrawSceneKinChar ()
Definition at line 12 of file DrawSceneKinChar.cpp.
                                      : cDrawScene()
 {
 }
~cDrawSceneKinChar()
cDrawSceneKinChar::~cDrawSceneKinChar () virtual
Definition at line 16 of file DrawSceneKinChar.cpp.
 {
 }
Member Function Documentation
BuildScene()
void cDrawSceneKinChar::BuildScene (std::shared_ptr< cSceneKinChar > & out_scene) const protected virtual
Definition at line 52 of file DrawSceneKinChar.cpp.
 {
     out_scene = std::shared_ptr<cSceneKinChar>(new cSceneKinChar());
 }
Referenced by Init().
Clear()
void cDrawSceneKinChar::Clear () virtual
Reimplemented from cScene.
Definition at line 34 of file DrawSceneKinChar.cpp.
 {
     cDrawScene::Clear();
     mScene->Clear();
 }
References cScene::Clear(), and mScene.
DrawCharacters()
void cDrawSceneKinChar::DrawCharacters () const protected virtual
Reimplemented from cDrawScene.
Definition at line 120 of file DrawSceneKinChar.cpp.
 {
     const auto& character = mScene->GetCharacter();
     cDrawCharacter::Draw(*character, gLinkWidth, gFilLColor, gLineColor);
 }
References cDrawCharacter::Draw(), gFilLColor, gLineColor, gLinkWidth, and mScene.
DrawGround()
void cDrawSceneKinChar::DrawGround () const protected virtual
Reimplemented from cDrawScene.
Definition at line 83 of file DrawSceneKinChar.cpp.
 {
     tVector ground_col = GetGroundColor();
     cDrawUtil::SetColor(ground_col);
     DrawGround3D();
 }
References DrawGround3D(), cDrawScene::GetGroundColor(), and cDrawUtil::SetColor().
DrawGround3D()
void cDrawSceneKinChar::DrawGround3D () const protected virtual
Definition at line 90 of file DrawSceneKinChar.cpp.
 {
     const double w = 200;
     const tVector ground_origin = tVector(0, gGroundHeight, 0, 0);
     const tVector tex_size = tVector(0.5, 0.5, 0, 0);
     const auto& character = mScene->GetCharacter();
     tVector char_pos = character->GetRootPos();
     char_pos[1] = gGroundHeight;
     tVector a = char_pos - tVector(-0.5 * w, 0, -0.5 * w, 0);
     tVector b = char_pos - tVector(-0.5 * w, 0, 0.5 * w, 0);
     tVector c = char_pos - tVector(0.5 * w, 0, 0.5 * w, 0);
     tVector d = char_pos - tVector(0.5 * w, 0, -0.5 * w, 0);
     tVector min_coord = a - ground_origin;
     tVector max_coord = c - ground_origin;
     min_coord[0] /= tex_size[0];
     min_coord[1] = min_coord[2] / tex_size[1];
     max_coord[0] /= tex_size[0];
     max_coord[1] = max_coord[2] / tex_size[1];
     tVector coord_a = tVector(min_coord[0], min_coord[1], 0, 0);
     tVector coord_b = tVector(min_coord[0], max_coord[1], 0, 0);
     tVector coord_c = tVector(max_coord[0], max_coord[1], 0, 0);
     tVector coord_d = tVector(max_coord[0], min_coord[1], 0, 0);
     cDrawUtil::DrawQuad(a, b, c, d, coord_a, coord_b, coord_c, coord_d);
 }
References cDrawUtil::DrawQuad(), gGroundHeight, and mScene.
Referenced by DrawGround().
GetCamStillPos()
tVector cDrawSceneKinChar::GetCamStillPos () const protected virtual
Reimplemented from cDrawScene.
Definition at line 73 of file DrawSceneKinChar.cpp.
 {
     return mScene->GetCharPos();
 }
References mScene.
GetCamTrackPos()
tVector cDrawSceneKinChar::GetCamTrackPos () const protected virtual
Reimplemented from cDrawScene.
Definition at line 68 of file DrawSceneKinChar.cpp.
 {
     return mScene->GetCharPos();
 }
References mScene.
GetDefaultCamFocus()
tVector cDrawSceneKinChar::GetDefaultCamFocus () const protected virtual
Reimplemented from cDrawScene.
Definition at line 78 of file DrawSceneKinChar.cpp.
 {
     return gCamFocus0;
 }
References gCamFocus0.
GetName()
std::string cDrawSceneKinChar::GetName () const virtual
Reimplemented from cDrawScene.
Definition at line 47 of file DrawSceneKinChar.cpp.
 {
     return mScene->GetName();
 }
References mScene.
Init()
void cDrawSceneKinChar::Init () virtual
Reimplemented from cDrawScene.
Definition at line 20 of file DrawSceneKinChar.cpp.
 {
     BuildScene(mScene);
     SetupScene(mScene);
     cDrawScene::Init();
 }
References BuildScene(), cDrawScene::Init(), mScene, and SetupScene().
Reset()
void cDrawSceneKinChar::Reset () virtual
Reimplemented from cDrawScene.
Definition at line 28 of file DrawSceneKinChar.cpp.
 {
     cDrawScene::Reset();
     mScene->Reset();
 }
References mScene, and cDrawScene::Reset().
SetupScene()
void cDrawSceneKinChar::SetupScene (std::shared_ptr< cSceneKinChar > & out_scene) protected virtual
Definition at line 57 of file DrawSceneKinChar.cpp.
 {
     out_scene->ParseArgs(mArgParser);
     out_scene->Init();
 }
References cScene::mArgParser.
Referenced by Init().
Update()
void cDrawSceneKinChar::Update (double time_elapsed) virtual
Reimplemented from cScene.
Definition at line 40 of file DrawSceneKinChar.cpp.
 {
     cDrawScene::Update(time_elapsed);
     UpdateScene(time_elapsed);
     UpdateCamera();
 }
References cScene::Update(), cDrawScene::UpdateCamera(), and UpdateScene().
UpdateScene()
void cDrawSceneKinChar::UpdateScene (double time_elapsed) protected virtual
Definition at line 63 of file DrawSceneKinChar.cpp.
 {
     mScene->Update(time_elapsed);
 }
References mScene.
Referenced by Update().
Member Data Documentation
mScene
std::shared_ptr<cSceneKinChar> cDrawSceneKinChar::mScene protected
Definition at line 23 of file DrawSceneKinChar.h.
Referenced by Clear(), DrawCharacters(), DrawGround3D(), GetCamStillPos(), GetCamTrackPos(), GetName(), Init(), Reset(), and UpdateScene().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/DrawSceneKinChar.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/DrawSceneKinChar.cpp