My Project: cWorld Class Reference
cWorld Class Reference
#include <World.h>
Classes
struct tConstraintEntry
struct tConstraintHandle
struct tParams
struct tRayTestResult
Public Types
enum eContactFlag {
eContactFlagNone = 0, eContactFlagCharacter = 0x1, eContactFlagEnvironment = 0x1 << 1, eContactFlagObject = 0x1 << 2,
eContactFlagAll = cContactManager::gFlagAll
}
typedef tEigenArr< tRayTestResult > tRayTestResults
Public Member Functions
cWorld ()
virtual ~cWorld ()
virtual void Init (const tParams &params)
virtual void Reset ()
virtual void Update (double time_elapsed)
virtual void AddRigidBody (cSimRigidBody &obj)
virtual void RemoveRigidBody (cSimRigidBody &obj)
virtual void AddCollisionObject (btCollisionObject *col_obj, int col_filter_group, int col_filter_mask)
virtual void RemoveCollisionObject (btCollisionObject *col_obj)
virtual void AddCharacter (cSimCharacter &sim_char)
virtual void RemoveCharacter (cSimCharacter &sim_char)
virtual void Constrain (cSimRigidBody &obj)
virtual void Constrain (cSimRigidBody &obj, const tVector &linear_factor, const tVector &angular_factor)
virtual void RemoveConstraint (tConstraintHandle &handle)
virtual void AddJoint (const cSimJoint &joint)
virtual void RemoveJoint (cSimJoint &joint)
virtual void SetGravity (const tVector &gravity)
virtual cContactManager::tContactHandle RegisterContact (int contact_flags, int filter_flags)
virtual void UpdateContact (const cContactManager::tContactHandle &handle)
virtual bool IsInContact (const cContactManager::tContactHandle &handle) const
virtual const tEigenArr< cContactManager::tContactPt > & GetContactPts (const cContactManager::tContactHandle &handle) const
virtual const cContactManager & GetContactManager () const
virtual void RayTest (const tVector &beg, const tVector &end, tRayTestResults &results) const
virtual void AddPerturb (const tPerturb &perturb)
virtual const cPerturbManager & GetPerturbManager () const
virtual tVector GetGravity () const
virtual double GetScale () const
virtual double GetTimeStep () const
virtual void SetDefaultLinearDamping (double damping)
virtual double GetDefaultLinearDamping () const
virtual void SetDefaultAngularDamping (double damping)
virtual double GetDefaultAngularDamping () const
std::unique_ptr< btMultiBodyDynamicsWorld > & GetInternalWorld ()
const std::unique_ptr< btMultiBodyDynamicsWorld > & GetInternalWorld () const
virtual btBoxShape * BuildBoxShape (const tVector &box_sizee) const
virtual btCapsuleShape * BuildCapsuleShape (double radius, double height) const
virtual btStaticPlaneShape * BuildPlaneShape (const tVector &normal, const tVector &origin) const
virtual btSphereShape * BuildSphereShape (double radius) const
virtual btCylinderShape * BuildCylinderShape (double radius, double height) const
virtual tVector GetSizeBox (const cSimObj &obj) const
virtual tVector GetSizeCapsule (const cSimObj &obj) const
virtual tVector GetSizePlane (const cSimObj &obj) const
virtual tVector GetSizeSphere (const cSimObj &obj) const
virtual tVector GetSizeCylinder (const cSimObj &obj) const
Protected Member Functions
virtual int GetNumConstriants () const
virtual void BuildConsFactor (tVector &out_linear_factor, tVector &out_angular_factor)
Protected Attributes
tParams mParams
double mTimeStep
double mDefaultLinearDamping
double mDefaultAngularDamping
std::unique_ptr< btMultiBodyDynamicsWorld > mSimWorld
std::unique_ptr< btConstraintSolver > mSolver
std::unique_ptr< btCollisionDispatcher > mCollisionDispatcher
std::unique_ptr< btDefaultCollisionConfiguration > mCollisionConfig
std::unique_ptr< btBroadphaseInterface > mBroadPhase
cContactManager mContactManager
cPerturbManager mPerturbManager
Detailed Description
Definition at line 24 of file World.h.
Member Typedef Documentation
tRayTestResults
typedef tEigenArr<tRayTestResult> cWorld::tRayTestResults
Definition at line 61 of file World.h.
Member Enumeration Documentation
eContactFlag
enum cWorld::eContactFlag
Enumerator
eContactFlagNone
eContactFlagCharacter
eContactFlagEnvironment
eContactFlagObject
eContactFlagAll
Definition at line 27 of file World.h.
     {
         eContactFlagNone = 0,
         eContactFlagCharacter = 0x1,
         eContactFlagEnvironment = 0x1 << 1,
         eContactFlagObject = 0x1 << 2,
         eContactFlagAll = cContactManager::gFlagAll
     };
Constructor & Destructor Documentation
cWorld()
cWorld::cWorld ()
Definition at line 40 of file World.cpp.
     : mContactManager(*this)
 {
     mDefaultLinearDamping = 0;
     mDefaultAngularDamping = 0;
     mTimeStep = 0;
 }
References mDefaultAngularDamping, mDefaultLinearDamping, and mTimeStep.
~cWorld()
cWorld::~cWorld () virtual
Definition at line 48 of file World.cpp.
 {
 }
Member Function Documentation
AddCharacter()
void cWorld::AddCharacter (cSimCharacter & sim_char) virtual
Definition at line 136 of file World.cpp.
 {
     sim_char.SetLinearDamping(mDefaultLinearDamping);
     sim_char.SetAngularDamping(mDefaultAngularDamping);
     mSimWorld->addMultiBody(sim_char.GetMultiBody().get());
     const auto& constraints = sim_char.GetConstraints();
     for (int c = 0; c < static_cast<int>(constraints.size()); ++c)
     {
         mSimWorld->addMultiBodyConstraint(constraints[c].get());
     }
 }
References cSimCharacter::GetConstraints(), cSimCharacter::GetMultiBody(), mDefaultAngularDamping, mDefaultLinearDamping, mSimWorld, cSimCharacter::SetAngularDamping(), and cSimCharacter::SetLinearDamping().
AddCollisionObject()
void cWorld::AddCollisionObject (btCollisionObject * col_obj, int col_filter_group, int col_filter_mask) virtual
Definition at line 125 of file World.cpp.
 {
     col_filter_mask |= cContactManager::gFlagRayTest;
     mSimWorld->addCollisionObject(col_obj, col_filter_group, col_filter_mask);
 }
References cContactManager::gFlagRayTest, and mSimWorld.
AddJoint()
void cWorld::AddJoint (const cSimJoint & joint) virtual
Definition at line 192 of file World.cpp.
 {
     const auto& cons = joint.GetCons();
     const auto& mult_body_cons = joint.GetMultBodyCons();
     assert(cons == nullptr || mult_body_cons == nullptr);
     if (cons != nullptr)
     {
         mSimWorld->addConstraint(cons.get(), joint.EnableAdjacentCollision());
     }
     if (mult_body_cons != nullptr)
     {
         mSimWorld->addMultiBodyConstraint(mult_body_cons.get());
     }
 }
References cSimJoint::EnableAdjacentCollision(), cSimJoint::GetCons(), cSimJoint::GetMultBodyCons(), and mSimWorld.
AddPerturb()
void cWorld::AddPerturb (const tPerturb & perturb) virtual
Definition at line 288 of file World.cpp.
 {
     mPerturbManager.AddPerturb(perturb);
 }
References cPerturbManager::AddPerturb(), and mPerturbManager.
AddRigidBody()
void cWorld::AddRigidBody (cSimRigidBody & obj) virtual
Definition at line 106 of file World.cpp.
 {
     const std::unique_ptr<btRigidBody>& body = obj.GetSimBody();
     short col_group = obj.GetColGroup();
     short col_mask = obj.GetColMask();
     col_mask |= cContactManager::gFlagRayTest;
     obj.SetDamping(mDefaultLinearDamping, mDefaultAngularDamping);
     mSimWorld->addRigidBody(body.get(), col_group, col_mask);
     Constrain(obj);
 }
References Constrain(), cSimObj::GetColGroup(), cSimObj::GetColMask(), cSimRigidBody::GetSimBody(), cContactManager::gFlagRayTest, mDefaultAngularDamping, mDefaultLinearDamping, mSimWorld, and cSimRigidBody::SetDamping().
BuildBoxShape()
btBoxShape * cWorld::BuildBoxShape (const tVector & box_sizee) const virtual
Definition at line 335 of file World.cpp.
 {
     btScalar scale = static_cast<btScalar>(GetScale());
     return new btBoxShape(scale * btVector3(static_cast<btScalar>(box_size[0] * 0.5),
                             static_cast<btScalar>(box_size[1] * 0.5),
                             static_cast<btScalar>(box_size[2] * 0.5)));
 }
References GetScale().
BuildCapsuleShape()
btCapsuleShape * cWorld::BuildCapsuleShape (double radius, double height) const virtual
Definition at line 343 of file World.cpp.
 {
     btScalar scale = static_cast<btScalar>(GetScale());
     return new btCapsuleShape(static_cast<btScalar>(scale * radius),
                                 static_cast<btScalar>(scale * height));
 }
References GetScale().
BuildConsFactor()
void cWorld::BuildConsFactor (tVector & out_linear_factor, tVector & out_angular_factor) protected virtual
Definition at line 223 of file World.cpp.
 {
     out_linear_factor = tVector::Ones();
     out_angular_factor = tVector::Ones();
 }
Referenced by Constrain().
BuildCylinderShape()
btCylinderShape * cWorld::BuildCylinderShape (double radius, double height) const virtual
Definition at line 371 of file World.cpp.
 {
     btScalar scale = static_cast<btScalar>(GetScale());
     return new btCylinderShape(btVector3(static_cast<btScalar>(scale * radius),
                                         static_cast<btScalar>(0.5 * scale * height),
                                         static_cast<btScalar>(scale * radius)));
 }
References GetScale().
BuildPlaneShape()
btStaticPlaneShape * cWorld::BuildPlaneShape (const tVector & normal, const tVector & origin) const virtual
Definition at line 350 of file World.cpp.
 {
     btVector3 bt_normal = btVector3(static_cast<btScalar>(normal[0]),
                                     static_cast<btScalar>(normal[1]),
                                     static_cast<btScalar>(normal[2]));
     btVector3 bt_origin = btVector3(static_cast<btScalar>(origin[0]),
                                     static_cast<btScalar>(origin[1]),
                                     static_cast<btScalar>(origin[2]));
     bt_normal.normalize();
     double scale = GetScale();
     btScalar w = static_cast<btScalar>(scale * bt_normal.dot(bt_origin));
     return new btStaticPlaneShape(bt_normal, w);
 }
References GetScale().
BuildSphereShape()
btSphereShape * cWorld::BuildSphereShape (double radius) const virtual
Definition at line 365 of file World.cpp.
 {
     btScalar scale = static_cast<btScalar>(GetScale());
     return new btSphereShape(static_cast<btScalar>(scale * radius));
 }
References GetScale().
Constrain() [1/2]
void cWorld::Constrain (cSimRigidBody & obj) virtual
Definition at line 160 of file World.cpp.
 {
     Constrain(obj, tVector::Ones(), tVector::Ones());
 }
Referenced by AddRigidBody().
Constrain() [2/2]
void cWorld::Constrain (cSimRigidBody & obj, const tVector & linear_factor, const tVector & angular_factor) virtual
Definition at line 165 of file World.cpp.
 {
     auto& body = obj.GetSimBody();
     tVector lin_f = tVector::Ones();
     tVector ang_f = tVector::Ones();
     BuildConsFactor(lin_f, ang_f);
     lin_f = lin_f.cwiseProduct(linear_factor);
     ang_f = ang_f.cwiseProduct(angular_factor);
     body->setLinearFactor(btVector3(static_cast<btScalar>(lin_f[0]),
                                     static_cast<btScalar>(lin_f[1]),
                                     static_cast<btScalar>(lin_f[2])));
     body->setAngularFactor(btVector3(static_cast<btScalar>(ang_f[0]),
                                     static_cast<btScalar>(ang_f[1]),
                                     static_cast<btScalar>(ang_f[2])));
 }
References BuildConsFactor(), and cSimRigidBody::GetSimBody().
GetContactManager()
const cContactManager & cWorld::GetContactManager () const virtual
Definition at line 252 of file World.cpp.
 {
     return mContactManager;
 }
References mContactManager.
GetContactPts()
const tEigenArr< cContactManager::tContactPt > & cWorld::GetContactPts (const cContactManager::tContactHandle & handle) const virtual
Definition at line 247 of file World.cpp.
 {
     return mContactManager.GetContactPts(handle);
 }
References cContactManager::GetContactPts(), and mContactManager.
GetDefaultAngularDamping()
double cWorld::GetDefaultAngularDamping () const virtual
Definition at line 330 of file World.cpp.
 {
     return mDefaultAngularDamping;
 }
References mDefaultAngularDamping.
GetDefaultLinearDamping()
double cWorld::GetDefaultLinearDamping () const virtual
Definition at line 320 of file World.cpp.
 {
     return mDefaultLinearDamping;
 }
References mDefaultLinearDamping.
GetGravity()
tVector cWorld::GetGravity () const virtual
Definition at line 298 of file World.cpp.
 {
     double scale = GetScale();
     btVector3 bt_gravity = mSimWorld->getGravity();
     return tVector(bt_gravity[0], bt_gravity[1], bt_gravity[2], 0) / scale;
 }
References GetScale(), and mSimWorld.
GetInternalWorld() [1/2]
std::unique_ptr< btMultiBodyDynamicsWorld > & cWorld::GetInternalWorld ()
Definition at line 433 of file World.cpp.
 {
     return mSimWorld;
 }
References mSimWorld.
Referenced by cContactManager::Update().
GetInternalWorld() [2/2]
const std::unique_ptr< btMultiBodyDynamicsWorld > & cWorld::GetInternalWorld () const
Definition at line 438 of file World.cpp.
 {
     return mSimWorld;
 }
References mSimWorld.
GetNumConstriants()
int cWorld::GetNumConstriants () const protected virtual
Definition at line 443 of file World.cpp.
 {
     return static_cast<int>(mSimWorld->getNumConstraints());
 }
References mSimWorld.
GetPerturbManager()
const cPerturbManager & cWorld::GetPerturbManager () const virtual
Definition at line 293 of file World.cpp.
 {
     return mPerturbManager;
 }
References mPerturbManager.
Referenced by cDrawWorld::DrawPerturbs().
GetScale()
double cWorld::GetScale () const virtual
Definition at line 305 of file World.cpp.
 {
     return mParams.mScale;
 }
References mParams, and cWorld::tParams::mScale.
Referenced by BuildBoxShape(), BuildCapsuleShape(), BuildCylinderShape(), BuildPlaneShape(), BuildSphereShape(), GetGravity(), GetSizeBox(), GetSizeCapsule(), GetSizeCylinder(), GetSizePlane(), GetSizeSphere(), RayTest(), SetGravity(), and cContactManager::Update().
GetSizeBox()
tVector cWorld::GetSizeBox (const cSimObj & obj) const virtual
Definition at line 379 of file World.cpp.
 {
     assert(obj.GetShape() == cShape::eShapeBox);
     const btBoxShape* box_shape = reinterpret_cast<const btBoxShape*>(obj.GetCollisionShape());
     btVector3 half_len = box_shape->getHalfExtentsWithMargin();
     double scale = GetScale();
     return tVector(half_len[0] * 2, half_len[1] * 2, half_len[2] * 2, 0) / scale;
 }
References cShape::eShapeBox, cSimObj::GetCollisionShape(), GetScale(), and cSimObj::GetShape().
GetSizeCapsule()
tVector cWorld::GetSizeCapsule (const cSimObj & obj) const virtual
Definition at line 388 of file World.cpp.
 {
     assert(obj.GetShape() == cShape::eShapeCapsule);
     const btCapsuleShape* shape = reinterpret_cast<const btCapsuleShape*>(obj.GetCollisionShape());
     double scale = GetScale();
     double r = shape->getRadius();
     double h = shape->getHalfHeight();
     r /= scale;
     h /= scale;
     return tVector(2 * r, 2 * (h + r), 2 * r, 0);
 }
References cShape::eShapeCapsule, cSimObj::GetCollisionShape(), GetScale(), and cSimObj::GetShape().
GetSizeCylinder()
tVector cWorld::GetSizeCylinder (const cSimObj & obj) const virtual
Definition at line 421 of file World.cpp.
 {
     assert(obj.GetShape() == cShape::eShapeCylinder);
     const btCylinderShape* shape = reinterpret_cast<const btCylinderShape*>(obj.GetCollisionShape());
     double scale = GetScale();
     double r = shape->getRadius();
     double h = 2 * shape->getHalfExtentsWithMargin()[1];
     r /= scale;
     h /= scale;
     return tVector(2 * r, h, 2 * r, 0);
 }
References cShape::eShapeCylinder, cSimObj::GetCollisionShape(), GetScale(), and cSimObj::GetShape().
GetSizePlane()
tVector cWorld::GetSizePlane (const cSimObj & obj) const virtual
Definition at line 400 of file World.cpp.
 {
     assert(obj.GetShape() == cShape::eShapePlane);
     const btStaticPlaneShape* shape = reinterpret_cast<const btStaticPlaneShape*>(obj.GetCollisionShape());
     double scale = GetScale();
     btVector3 n = shape->getPlaneNormal();
     btScalar c = shape->getPlaneConstant();
     return tVector(n[0], n[1], n[2], c / scale);
 }
References cShape::eShapePlane, cSimObj::GetCollisionShape(), GetScale(), and cSimObj::GetShape().
GetSizeSphere()
tVector cWorld::GetSizeSphere (const cSimObj & obj) const virtual
Definition at line 410 of file World.cpp.
 {
     assert(obj.GetShape() == cShape::eShapeSphere);
     const btSphereShape* ball_shape = reinterpret_cast<const btSphereShape*>(obj.GetCollisionShape());
     double r = ball_shape->getRadius();
     double scale = GetScale();
     r /= scale;
     double d = 2 * r;
     return tVector(d, d, d, 0);
 }
References cShape::eShapeSphere, cSimObj::GetCollisionShape(), GetScale(), and cSimObj::GetShape().
GetTimeStep()
double cWorld::GetTimeStep () const virtual
Definition at line 310 of file World.cpp.
 {
     return mTimeStep;
 }
References mTimeStep.
Referenced by cContactManager::Update().
Init()
void cWorld::Init (const tParams & params) virtual
Definition at line 52 of file World.cpp.
 {
     mParams = params;
     mBroadPhase = std::unique_ptr<btBroadphaseInterface>(new btDbvtBroadphase());
     mCollisionConfig = std::unique_ptr<btDefaultCollisionConfiguration>(new btDefaultCollisionConfiguration());
     mCollisionDispatcher = std::unique_ptr<btCollisionDispatcher>(new btCollisionDispatcher(mCollisionConfig.get()));
     btGImpactCollisionAlgorithm::registerAlgorithm(mCollisionDispatcher.get());
     auto solver = new btMultiBodyConstraintSolver();
     mSolver = std::unique_ptr<btSequentialImpulseConstraintSolver>(solver);
     mSimWorld = std::unique_ptr<btMultiBodyDynamicsWorld>(new btMultiBodyDynamicsWorld(mCollisionDispatcher.get(),
                                                         mBroadPhase.get(), solver, mCollisionConfig.get()));
     btContactSolverInfo& info = mSimWorld->getSolverInfo();
     info.m_solverMode = SOLVER_SIMD | SOLVER_USE_2_FRICTION_DIRECTIONS | SOLVER_FRICTION_SEPARATE | SOLVER_USE_WARMSTARTING;
     SetGravity(params.mGravity);
     mContactManager.Init();
     mPerturbManager.Clear();
 }
References cPerturbManager::Clear(), cContactManager::Init(), mBroadPhase, mCollisionConfig, mCollisionDispatcher, mContactManager, cWorld::tParams::mGravity, mParams, mPerturbManager, mSimWorld, mSolver, and SetGravity().
IsInContact()
bool cWorld::IsInContact (const cContactManager::tContactHandle & handle) const virtual
Definition at line 257 of file World.cpp.
 {
     return mContactManager.IsInContact(handle);
 }
References cContactManager::IsInContact(), and mContactManager.
RayTest()
void cWorld::RayTest (const tVector & beg, const tVector & end, tRayTestResults & results) const virtual
Definition at line 262 of file World.cpp.
 {
     btScalar scale = static_cast<btScalar>(GetScale());
     btVector3 bt_beg = scale * btVector3(static_cast<btScalar>(beg[0]),
                                 static_cast<btScalar>(beg[1]),
                                 static_cast<btScalar>(beg[2]));
     btVector3 bt_end = scale * btVector3(static_cast<btScalar>(end[0]),
                                 static_cast<btScalar>(end[1]),
                                 static_cast<btScalar>(end[2]));
     btCollisionWorld::ClosestRayResultCallback ray_callback(bt_beg, bt_end);
     mSimWorld->rayTest(bt_beg, bt_end, ray_callback);
     results.clear();
     if (ray_callback.hasHit())
     {
         auto& obj = ray_callback.m_collisionObject;
         const auto& hit_pt = ray_callback.m_hitPointWorld;
         tRayTestResult result;
         result.mObj = static_cast<cSimObj*>(obj->getUserPointer());
         result.mHitPos = tVector(hit_pt[0], hit_pt[1], hit_pt[2], 0) / scale;
         results.push_back(result);
     }
 }
References GetScale(), cWorld::tRayTestResult::mHitPos, cWorld::tRayTestResult::mObj, and mSimWorld.
RegisterContact()
cContactManager::tContactHandle cWorld::RegisterContact (int contact_flags, int filter_flags) virtual
Definition at line 237 of file World.cpp.
 {
     return mContactManager.RegisterContact(contact_flags, filter_flags);
 }
References mContactManager, and cContactManager::RegisterContact().
RemoveCharacter()
void cWorld::RemoveCharacter (cSimCharacter & sim_char) virtual
Definition at line 149 of file World.cpp.
 {
     const auto& constraints = sim_char.GetConstraints();
     for (int c = 0; c < static_cast<int>(constraints.size()); ++c)
     {
         mSimWorld->removeMultiBodyConstraint(constraints[c].get());
     }
     mSimWorld->removeMultiBody(sim_char.GetMultiBody().get());
 }
References cSimCharacter::GetConstraints(), cSimCharacter::GetMultiBody(), and mSimWorld.
RemoveCollisionObject()
void cWorld::RemoveCollisionObject (btCollisionObject * col_obj) virtual
Definition at line 131 of file World.cpp.
 {
     mSimWorld->removeCollisionObject(col_obj);
 }
References mSimWorld.
RemoveConstraint()
void cWorld::RemoveConstraint (tConstraintHandle & handle) virtual
Definition at line 183 of file World.cpp.
 {
     if (handle.IsValid())
     {
         mSimWorld->removeConstraint(handle.mCons);
     }
     handle.Clear();
 }
References cWorld::tConstraintHandle::Clear(), cWorld::tConstraintHandle::IsValid(), cWorld::tConstraintHandle::mCons, and mSimWorld.
RemoveJoint()
void cWorld::RemoveJoint (cSimJoint & joint) virtual
Definition at line 208 of file World.cpp.
 {
     const auto& cons = joint.GetCons();
     const auto& mult_body_cons = joint.GetMultBodyCons();
     if (cons != nullptr)
     {
         mSimWorld->removeConstraint(cons.get());
     }
     if (mult_body_cons != nullptr)
     {
         mSimWorld->removeMultiBodyConstraint(mult_body_cons.get());
     }
 }
References cSimJoint::GetCons(), cSimJoint::GetMultBodyCons(), and mSimWorld.
RemoveRigidBody()
void cWorld::RemoveRigidBody (cSimRigidBody & obj) virtual
Definition at line 120 of file World.cpp.
 {
     mSimWorld->removeRigidBody(obj.GetSimBody().get());
 }
References cSimRigidBody::GetSimBody(), and mSimWorld.
Reset()
void cWorld::Reset () virtual
Definition at line 75 of file World.cpp.
 {
     mTimeStep = 0;
     mContactManager.Reset();
     mPerturbManager.Clear();
     mSimWorld->clearForces();
     mSolver->reset();
     mBroadPhase->resetPool(mCollisionDispatcher.get());
     btOverlappingPairCache* pair_cache = mSimWorld->getBroadphase()->getOverlappingPairCache();
     btBroadphasePairArray& pair_array = pair_cache->getOverlappingPairArray();
     for (int i = 0; i < pair_array.size(); ++i)
     {
         pair_cache->cleanOverlappingPair(pair_array[i], mSimWorld->getDispatcher());
     }
 }
References cPerturbManager::Clear(), mBroadPhase, mCollisionDispatcher, mContactManager, mPerturbManager, mSimWorld, mSolver, mTimeStep, and cContactManager::Reset().
SetDefaultAngularDamping()
void cWorld::SetDefaultAngularDamping (double damping) virtual
Definition at line 325 of file World.cpp.
 {
     mDefaultAngularDamping = damping;
 }
References mDefaultAngularDamping.
SetDefaultLinearDamping()
void cWorld::SetDefaultLinearDamping (double damping) virtual
Definition at line 315 of file World.cpp.
 {
     mDefaultLinearDamping = damping;
 }
References mDefaultLinearDamping.
SetGravity()
void cWorld::SetGravity (const tVector & gravity) virtual
Definition at line 229 of file World.cpp.
 {
     double scale = GetScale();
     mSimWorld->setGravity(btVector3(static_cast<btScalar>(gravity[0] * scale),
                                     static_cast<btScalar>(gravity[1] * scale),
                                     static_cast<btScalar>(gravity[2] * scale)));
 }
References GetScale(), and mSimWorld.
Referenced by Init().
Update()
void cWorld::Update (double time_elapsed) virtual
Definition at line 93 of file World.cpp.
 {
     time_elapsed = std::max(0.0, time_elapsed);
     mPerturbManager.Update(time_elapsed);
     btScalar timestep = static_cast<btScalar>(time_elapsed);
     btScalar subtimestep = timestep / mParams.mNumSubsteps;
     mSimWorld->stepSimulation(timestep, mParams.mNumSubsteps, subtimestep);
     mTimeStep = subtimestep;
     mContactManager.Update();
 }
References mContactManager, cWorld::tParams::mNumSubsteps, mParams, mPerturbManager, mSimWorld, mTimeStep, cPerturbManager::Update(), and cContactManager::Update().
UpdateContact()
void cWorld::UpdateContact (const cContactManager::tContactHandle & handle) virtual
Definition at line 242 of file World.cpp.
 {
     mContactManager.UpdateContact(handle);
 }
References mContactManager, and cContactManager::UpdateContact().
Member Data Documentation
mBroadPhase
std::unique_ptr<btBroadphaseInterface> cWorld::mBroadPhase protected
Definition at line 136 of file World.h.
Referenced by Init(), and Reset().
mCollisionConfig
std::unique_ptr<btDefaultCollisionConfiguration> cWorld::mCollisionConfig protected
Definition at line 135 of file World.h.
Referenced by Init().
mCollisionDispatcher
std::unique_ptr<btCollisionDispatcher> cWorld::mCollisionDispatcher protected
Definition at line 134 of file World.h.
Referenced by Init(), and Reset().
mContactManager
cContactManager cWorld::mContactManager protected
Definition at line 138 of file World.h.
Referenced by GetContactManager(), GetContactPts(), Init(), IsInContact(), RegisterContact(), Reset(), Update(), and UpdateContact().
mDefaultAngularDamping
double cWorld::mDefaultAngularDamping protected
Definition at line 130 of file World.h.
Referenced by AddCharacter(), AddRigidBody(), cWorld(), GetDefaultAngularDamping(), and SetDefaultAngularDamping().
mDefaultLinearDamping
double cWorld::mDefaultLinearDamping protected
Definition at line 129 of file World.h.
Referenced by AddCharacter(), AddRigidBody(), cWorld(), GetDefaultLinearDamping(), and SetDefaultLinearDamping().
mParams
tParams cWorld::mParams protected
Definition at line 127 of file World.h.
Referenced by GetScale(), Init(), and Update().
mPerturbManager
cPerturbManager cWorld::mPerturbManager protected
Definition at line 139 of file World.h.
Referenced by AddPerturb(), GetPerturbManager(), Init(), Reset(), and Update().
mSimWorld
std::unique_ptr<btMultiBodyDynamicsWorld> cWorld::mSimWorld protected
Definition at line 131 of file World.h.
Referenced by AddCharacter(), AddCollisionObject(), AddJoint(), AddRigidBody(), GetGravity(), GetInternalWorld(), GetNumConstriants(), Init(), RayTest(), RemoveCharacter(), RemoveCollisionObject(), RemoveConstraint(), RemoveJoint(), RemoveRigidBody(), Reset(), SetGravity(), and Update().
mSolver
std::unique_ptr<btConstraintSolver> cWorld::mSolver protected
Definition at line 133 of file World.h.
Referenced by Init(), and Reset().
mTimeStep
double cWorld::mTimeStep protected
Definition at line 128 of file World.h.
Referenced by cWorld(), GetTimeStep(), Reset(), and Update().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/World.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/World.cpp