My Project: cAnnealer Class Reference
cAnnealer Class Reference
#include <Annealer.h>
Classes
struct tParams
Public Types
enum eType { eTypeLinear, eTypePow, eTypeMax }
Public Member Functions
cAnnealer ()
virtual ~cAnnealer ()
virtual void Init (const tParams &params)
virtual double Eval (double t)
Protected Attributes
tParams mParams
Detailed Description
Definition at line 3 of file Annealer.h.
Member Enumeration Documentation
eType
enum cAnnealer::eType
Enumerator
eTypeLinear
eTypePow
eTypeMax
Definition at line 6 of file Annealer.h.
     {
         eTypeLinear,
         eTypePow,
         eTypeMax
     };
Constructor & Destructor Documentation
cAnnealer()
cAnnealer::cAnnealer ()
Definition at line 10 of file Annealer.cpp.
 {
 }
~cAnnealer()
cAnnealer::~cAnnealer () virtual
Definition at line 14 of file Annealer.cpp.
 {
 }
Member Function Documentation
Eval()
double cAnnealer::Eval (double t) virtual
Definition at line 23 of file Annealer.cpp.
 {
     double val = 0;
     t = cMathUtil::Clamp(t, 0.0, 1.0);
     switch (mParams.mType)
     {
     case eTypeLinear:
         val = t;
         break;
     case eTypePow:
         val = std::pow(t, mParams.mPow);
         break;
     default:
         assert(false); // unsupported
         break;
     }
     return val;
 }
References cMathUtil::Clamp(), eTypeLinear, eTypePow, mParams, cAnnealer::tParams::mPow, and cAnnealer::tParams::mType.
Referenced by cRLSceneSimChar::UpdateTimerParams().
Init()
void cAnnealer::Init (const tParams & params) virtual
Definition at line 18 of file Annealer.cpp.
 {
     mParams = params;
 }
References mParams.
Referenced by cRLSceneSimChar::SetupTimerAnnealer().
Member Data Documentation
mParams
tParams cAnnealer::mParams protected
Definition at line 27 of file Annealer.h.
Referenced by Eval(), and Init().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/Annealer.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/Annealer.cpp