My Project: cDrawSceneImitate Class Reference
cDrawSceneImitate Class Reference
#include <DrawSceneImitate.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cDrawSceneImitate ()
virtual ~cDrawSceneImitate ()
virtual void Init ()
virtual void Clear ()
virtual bool IsEpisodeEnd () const
virtual bool CheckValidEpisode () const
virtual void Keyboard (unsigned char key, double device_x, double device_y)
virtual void DrawKinChar (bool enable)
virtual std::string GetName () const
Public Member Functions inherited from cDrawRLScene
virtual ~cDrawRLScene ()
virtual int GetNumAgents () const
virtual bool NeedNewAction (int agent_id) const
virtual void RecordState (int agent_id, Eigen::VectorXd &out_state) const
virtual void RecordGoal (int agent_id, Eigen::VectorXd &out_goal) const
virtual void SetAction (int agent_id, const Eigen::VectorXd &action)
virtual eActionSpace GetActionSpace (int agent_id) const
virtual int GetStateSize (int agent_id) const
virtual int GetGoalSize (int agent_id) const
virtual int GetActionSize (int agent_id) const
virtual int GetNumActions (int agent_id) const
virtual void BuildStateOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildGoalOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionBounds (int agent_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max) const
virtual void BuildStateNormGroups (int agent_id, Eigen::VectorXi &out_groups) const
virtual void BuildGoalNormGroups (int agent_id, Eigen::VectorXi &out_groups) const
virtual double CalcReward (int agent_id) const
virtual double GetRewardMin (int agent_id) const
virtual double GetRewardMax (int agent_id) const
virtual double GetRewardFail (int agent_id)
virtual double GetRewardSucc (int agent_id)
virtual eTerminate CheckTerminate (int agent_id) const
virtual void SetMode (eMode mode)
virtual void SetSampleCount (int count)
virtual void LogVal (int agent_id, double val)
Public Member Functions inherited from cRLScene
virtual ~cRLScene ()
Public Member Functions inherited from cScene
virtual ~cScene ()
virtual void Shutdown ()
virtual bool IsDone () const
virtual bool HasRandSeed () const
virtual void SetRandSeed (unsigned long seed)
virtual unsigned long GetRandSeed () const
Public Member Functions inherited from cDrawScene
virtual ~cDrawScene ()
virtual void ParseArgs (const std::shared_ptr< cArgParser > &parser)
virtual void Reset ()
virtual void Draw ()
virtual void EnableDrawInfo (bool enable)
Public Member Functions inherited from cDrawSceneSimChar
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cDrawSceneSimChar ()
virtual ~cDrawSceneSimChar ()
virtual void Update (double time_elapsed)
virtual const std::shared_ptr< cSceneSimChar > & GetScene () const
virtual void MouseClick (int button, int state, double x, double y)
virtual void MouseMove (double x, double y)
virtual double GetTime () const
Protected Member Functions
virtual cRLScene * GetRLScene () const
virtual void BuildScene (std::shared_ptr< cSceneSimChar > &out_scene) const
virtual void DrawCharacters () const
virtual void DrawKinCharacters () const
virtual void DrawKinCharacter (const std::shared_ptr< cKinCharacter > &kin_char) const
virtual const std::shared_ptr< cKinCharacter > & GetKinChar () const
Protected Member Functions inherited from cDrawRLScene
cDrawRLScene ()
Protected Member Functions inherited from cRLScene
cRLScene ()
Protected Member Functions inherited from cScene
cScene ()
virtual void InitTimers ()
virtual void ResetTimers ()
virtual void UpdateTimers (double timestep)
Protected Member Functions inherited from cDrawScene
cDrawScene ()
virtual void ParseCamTrackMode (const std::shared_ptr< cArgParser > &parser, eCamTrackMode &out_mode) const
virtual void Reshape (int w, int h)
virtual void ResizeCamera (int w, int h)
virtual void InitCamera ()
virtual eCamTrackMode GetCamTrackMode () const
virtual void UpdateCamera ()
virtual void UpdateCameraTracking ()
virtual void UpdateCameraStill ()
virtual double GetCamStillSnapDistX () const
virtual void ResetCamera ()
virtual void ClearFrame ()
virtual tVector GetBkgColor () const
virtual void SetupView ()
virtual void RestoreView ()
virtual tVector GetLightDirection () const
virtual void DrawScene ()
virtual void DrawGrid () const
virtual void DrawGroundMainScene ()
virtual void DrawCharacterMainScene ()
virtual void DrawObjsMainScene ()
virtual void DrawMiscMainScene ()
virtual tVector GetVisOffset () const
virtual tVector GetLineColor () const
virtual tVector GetGroundColor () const
virtual void InitRenderResources ()
virtual bool LoadTextures ()
virtual void SetupMeshShader ()
virtual void DoShadowPass ()
Protected Member Functions inherited from cDrawSceneSimChar
virtual void SetupScene (std::shared_ptr< cSceneSimChar > &out_scene)
virtual void UpdateScene (double time_elapsed)
virtual void ResetScene ()
virtual tVector GetCamTrackPos () const
virtual tVector GetCamStillPos () const
virtual tVector GetDefaultCamFocus () const
virtual void ResetParams ()
virtual void ToggleTrace ()
virtual void InitTracer ()
virtual void AddTraces ()
virtual void AddCharTrace (const std::shared_ptr< cSimCharacter > &character, const tVectorArr &cols)
virtual void UpdateTracer (double time_elapsed)
virtual void SpawnProjectile ()
virtual void SpawnBigProjectile ()
virtual void OutputCharState (const std::string &out_file) const
virtual std::string GetOutputCharFile () const
virtual void ResetUI ()
virtual void RayTest (const tVector &start, const tVector &end, cWorld::tRayTestResult &out_result)
virtual bool ObjectSelected () const
virtual void HandleRayTest (const cWorld::tRayTestResult &result)
virtual void ApplyUIForce (double time_step)
virtual void DrawObjs () const
virtual void DrawMisc () const
virtual void DrawCoM () const
virtual void DrawTorque () const
virtual void DrawBodyVel () const
virtual void DrawHeading () const
virtual void DrawTrace () const
virtual void DrawPerturbs () const
virtual void DrawGround () const
virtual void DrawCharacter (const std::shared_ptr< cSimCharacter > &character) const
virtual void UpdateGroundDrawMesh ()
virtual void BuildGroundDrawMesh ()
virtual void DrawInfo () const
virtual void DrawPoliInfo () const
Protected Attributes
bool mDrawKinChar
Protected Attributes inherited from cRLScene
eMode mMode
int mSampleCount
Protected Attributes inherited from cScene
cRand mRand
bool mHasRandSeed
unsigned long mRandSeed
std::shared_ptr< cArgParser > mArgParser
cTimer::tParams mTimerParams
cTimer mTimer
Protected Attributes inherited from cDrawScene
eCamTrackMode mCamTrackMode
cCamera mCamera
cCamera mShadowCam
bool mDrawInfo
std::unique_ptr< cShadowMap > mShadowMap
std::unique_ptr< cTextureDesc > mGridTex
std::unique_ptr< cShader > mShaderMesh
std::unique_ptr< cShader > mShaderDepth
GLuint mMeshLightDirHandle
GLuint mMeshLightColourHandle
GLuint mMeshAmbientColourHandle
GLuint mMeshShadowProjHandle
GLuint mMeshMaterialDataHandle
GLuint mMeshFogColorHandle
GLuint mMeshFogDataHandle
Protected Attributes inherited from cDrawSceneSimChar
std::shared_ptr< cSceneSimChar > mScene
std::unique_ptr< cDrawMesh > mGroundDrawMesh
size_t mPrevGroundUpdateCount
bool mEnableTrace
cObjTracer mTracer
std::vector< int > mTraceHandles
tVector mClickScreenPos
tVector mDragScreenPos
tVector mSelectObjLocalPos
cSimObj * mSelectedObj
int mTracerBufferSize
double mTracerSamplePeriod
Additional Inherited Members
Public Types inherited from cRLScene
enum eMode { eModeTrain, eModeTest, eModeMax }
enum eTerminate { eTerminateNull, eTerminateFail, eTerminateSucc, eTerminateMax }
Public Types inherited from cDrawScene
enum eCamTrackMode {
eCamTrackModeXZ, eCamTrackModeY, eCamTrackModeXYZ, eCamTrackModeStill,
eCamTrackModeFixed, eCamTrackModeMax
}
Detailed Description
Definition at line 7 of file DrawSceneImitate.h.
Constructor & Destructor Documentation
cDrawSceneImitate()
cDrawSceneImitate::cDrawSceneImitate ()
Definition at line 11 of file DrawSceneImitate.cpp.
 {
     mDrawKinChar = false;
 }
References mDrawKinChar.
~cDrawSceneImitate()
cDrawSceneImitate::~cDrawSceneImitate () virtual
Definition at line 16 of file DrawSceneImitate.cpp.
 {
 }
Member Function Documentation
BuildScene()
void cDrawSceneImitate::BuildScene (std::shared_ptr< cSceneSimChar > & out_scene) const protected virtual
Reimplemented from cDrawSceneSimChar.
Definition at line 79 of file DrawSceneImitate.cpp.
 {
     out_scene = std::shared_ptr<cSceneImitate>(new cSceneImitate());
 }
CheckValidEpisode()
bool cDrawSceneImitate::CheckValidEpisode () const virtual
Reimplemented from cDrawRLScene.
Definition at line 37 of file DrawSceneImitate.cpp.
 {
     return cDrawRLScene::CheckValidEpisode();
 }
References cDrawRLScene::CheckValidEpisode().
Clear()
void cDrawSceneImitate::Clear () virtual
Reimplemented from cDrawSceneSimChar.
Definition at line 26 of file DrawSceneImitate.cpp.
 {
     cDrawSceneSimChar::Clear();
     cDrawRLScene::Clear();
 }
References cDrawSceneSimChar::Clear(), and cRLScene::Clear().
DrawCharacters()
void cDrawSceneImitate::DrawCharacters () const protected virtual
Reimplemented from cDrawSceneSimChar.
Definition at line 84 of file DrawSceneImitate.cpp.
 {
     if (mDrawKinChar)
     {
         DrawKinCharacters();
     }
     cDrawSceneSimChar::DrawCharacters();
 }
References cDrawSceneSimChar::DrawCharacters(), DrawKinCharacters(), and mDrawKinChar.
DrawKinChar()
void cDrawSceneImitate::DrawKinChar (bool enable) virtual
Definition at line 56 of file DrawSceneImitate.cpp.
 {
     mDrawKinChar = enable;
     if (mDrawKinChar)
     {
         printf("Enabled draw kinematic character\n");
     }
     else
     {
         printf("Disabled draw kinematic character\n");
     }
 }
References mDrawKinChar.
Referenced by Keyboard().
DrawKinCharacter()
void cDrawSceneImitate::DrawKinCharacter (const std::shared_ptr< cKinCharacter > & kin_char) const protected virtual
Definition at line 98 of file DrawSceneImitate.cpp.
 {
     cDrawCharacter::Draw(*kin_char, gLinkWidth, gFilLColor, gLineColor);
 }
References cDrawCharacter::Draw(), gFilLColor, gLineColor, and gLinkWidth.
Referenced by DrawKinCharacters().
DrawKinCharacters()
void cDrawSceneImitate::DrawKinCharacters () const protected virtual
Definition at line 93 of file DrawSceneImitate.cpp.
 {
     const auto& kin_char = GetKinChar();
     DrawKinCharacter(kin_char);
 }
References DrawKinCharacter(), and GetKinChar().
Referenced by DrawCharacters().
GetKinChar()
const std::shared_ptr< cKinCharacter > & cDrawSceneImitate::GetKinChar () const protected virtual
Definition at line 103 of file DrawSceneImitate.cpp.
 {
     const cSceneImitate* scene = dynamic_cast<const cSceneImitate*>(mScene.get());
     return scene->GetKinChar();
 }
References cSceneImitate::GetKinChar(), and cDrawSceneSimChar::mScene.
Referenced by DrawKinCharacters().
GetName()
std::string cDrawSceneImitate::GetName () const virtual
Reimplemented from cDrawRLScene.
Definition at line 69 of file DrawSceneImitate.cpp.
 {
     return cDrawRLScene::GetName();
 }
References cDrawRLScene::GetName().
GetRLScene()
cRLScene * cDrawSceneImitate::GetRLScene () const protected virtual
Implements cDrawRLScene.
Definition at line 74 of file DrawSceneImitate.cpp.
 {
     return dynamic_cast<cRLScene*>(mScene.get());
 }
References cDrawSceneSimChar::mScene.
Init()
void cDrawSceneImitate::Init () virtual
Reimplemented from cDrawRLScene.
Definition at line 20 of file DrawSceneImitate.cpp.
 {
     cDrawSceneSimChar::Init();
     cRLScene::Init();
 }
References cDrawSceneSimChar::Init(), and cRLScene::Init().
IsEpisodeEnd()
bool cDrawSceneImitate::IsEpisodeEnd () const virtual
Reimplemented from cDrawRLScene.
Definition at line 32 of file DrawSceneImitate.cpp.
 {
     return cDrawRLScene::IsEpisodeEnd();
 }
References cDrawRLScene::IsEpisodeEnd().
Keyboard()
void cDrawSceneImitate::Keyboard (unsigned char key, double device_x, double device_y) virtual
Reimplemented from cDrawSceneSimChar.
Definition at line 42 of file DrawSceneImitate.cpp.
 {
     cDrawSceneSimChar::Keyboard(key, device_x, device_y);
     switch (key)
     {
     case 'k':
         DrawKinChar(!mDrawKinChar);
         break;
     default:
         break;
     }
 }
References DrawKinChar(), cDrawSceneSimChar::Keyboard(), and mDrawKinChar.
Member Data Documentation
mDrawKinChar
bool cDrawSceneImitate::mDrawKinChar protected
Definition at line 27 of file DrawSceneImitate.h.
Referenced by cDrawSceneImitate(), DrawCharacters(), DrawKinChar(), and Keyboard().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/DrawSceneImitate.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/DrawSceneImitate.cpp