My Project: F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/DrawScene.cpp File Reference
DrawScene.cpp File Reference
#include "DrawScene.h"
#include "render/DrawUtil.h"
Variables
const tVector gCameraPosition = tVector(0, 0, 30, 0)
const tVector gCameraFocus = tVector(gCameraPosition[0], gCameraPosition[1], 0.0, 0.0)
const tVector gCameraUp = tVector(0, 1, 0, 0)
const double gViewWidth = 4.5
const double gViewHeight = gViewWidth * 9.0 / 16.0
const double gViewNearZ = 2
const double gViewFarZ = 500
const tVector gLineColor = tVector(0, 0, 0, 1)
const tVector gVisOffset = tVector(0, 0, 1, 0)
Variable Documentation
gCameraFocus
const tVector gCameraFocus = tVector(gCameraPosition[0], gCameraPosition[1], 0.0, 0.0)
Definition at line 7 of file DrawScene.cpp.
Referenced by cDrawScene::InitCamera().
gCameraPosition
const tVector gCameraPosition = tVector(0, 0, 30, 0)
Definition at line 6 of file DrawScene.cpp.
Referenced by cDrawScene::InitCamera().
gCameraUp
const tVector gCameraUp = tVector(0, 1, 0, 0)
Definition at line 8 of file DrawScene.cpp.
Referenced by cDrawScene::InitCamera().
gLineColor
const tVector gLineColor = tVector(0, 0, 0, 1)
Definition at line 15 of file DrawScene.cpp.
Referenced by cDrawScene::GetLineColor().
gViewFarZ
const double gViewFarZ = 500
Definition at line 13 of file DrawScene.cpp.
Referenced by cDrawScene::InitCamera().
gViewHeight
const double gViewHeight = gViewWidth * 9.0 / 16.0
Definition at line 11 of file DrawScene.cpp.
Referenced by cDrawScene::InitCamera().
gViewNearZ
const double gViewNearZ = 2
Definition at line 12 of file DrawScene.cpp.
Referenced by cDrawScene::InitCamera().
gViewWidth
const double gViewWidth = 4.5
Definition at line 10 of file DrawScene.cpp.
Referenced by cDrawScene::InitCamera().
gVisOffset
const tVector gVisOffset = tVector(0, 0, 1, 0)
Definition at line 16 of file DrawScene.cpp.