My Project: F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/DrawSceneKinChar.cpp File Reference
DrawSceneKinChar.cpp File Reference
#include "DrawSceneKinChar.h"
#include "render/DrawUtil.h"
#include "render/DrawCharacter.h"
#include "util/FileUtil.h"
Variables
const double gLinkWidth = 0.025f
const tVector gLineColor = tVector(0, 0, 0, 1)
const tVector gFilLColor = tVector(0.6f, 0.65f, 0.675f, 1)
const tVector gCamFocus0 = tVector(0, 0.75, 0, 0)
const double gGroundHeight = 0
Variable Documentation
gCamFocus0
const tVector gCamFocus0 = tVector(0, 0.75, 0, 0)
Definition at line 9 of file DrawSceneKinChar.cpp.
Referenced by cDrawSceneKinChar::GetDefaultCamFocus().
gFilLColor
const tVector gFilLColor = tVector(0.6f, 0.65f, 0.675f, 1)
Definition at line 8 of file DrawSceneKinChar.cpp.
Referenced by cDrawSceneKinChar::DrawCharacters().
gGroundHeight
const double gGroundHeight = 0
Definition at line 10 of file DrawSceneKinChar.cpp.
Referenced by cDrawSceneKinChar::DrawGround3D().
gLineColor
const tVector gLineColor = tVector(0, 0, 0, 1)
Definition at line 7 of file DrawSceneKinChar.cpp.
Referenced by cDrawSceneKinChar::DrawCharacters().
gLinkWidth
const double gLinkWidth = 0.025f
Definition at line 6 of file DrawSceneKinChar.cpp.
Referenced by cDrawSceneKinChar::DrawCharacters().