My Project: Json::FastWriter Class Reference
Json::FastWriter Class Reference
Outputs a Value in JSON format without formatting (not human friendly).
#include <writer.h>
Public Member Functions
FastWriter ()
~FastWriter () JSONCPP_OVERRIDE
void enableYAMLCompatibility ()
void dropNullPlaceholders ()
Drop the "null" string from the writer's output for nullValues. Strictly speaking, this is not valid JSON. But when the output is being fed to a browser's Javascript, it makes for smaller output and the browser can handle the output just fine.
void omitEndingLineFeed ()
JSONCPP_STRING write (const Value &root) JSONCPP_OVERRIDE
Public Member Functions inherited from Json::Writer
virtual ~Writer ()
Private Member Functions
void writeValue (const Value &value)
Private Attributes
JSONCPP_STRING document_
bool yamlCompatiblityEnabled_
bool dropNullPlaceholders_
bool omitEndingLineFeed_
Detailed Description
Outputs a Value in JSON format without formatting (not human friendly).
The JSON document is written in a single line. It is not intended for 'human' consumption, but may be usefull to support feature such as RPC where bandwith is limited.
See also
Reader, Value
Deprecated:
Use StreamWriterBuilder.
Definition at line 159 of file writer.h.
Constructor & Destructor Documentation
FastWriter()
Json::FastWriter::FastWriter ()
Definition at line 327 of file json_writer.cpp.
     : yamlCompatiblityEnabled_(false), dropNullPlaceholders_(false),
       omitEndingLineFeed_(false) {}
~FastWriter()
Json::FastWriter::~FastWriter () inline
Definition at line 163 of file writer.h.
 {}
Member Function Documentation
dropNullPlaceholders()
void Json::FastWriter::dropNullPlaceholders ()
Drop the "null" string from the writer's output for nullValues. Strictly speaking, this is not valid JSON. But when the output is being fed to a browser's Javascript, it makes for smaller output and the browser can handle the output just fine.
Definition at line 333 of file json_writer.cpp.
 { dropNullPlaceholders_ = true; }
References dropNullPlaceholders_.
enableYAMLCompatibility()
void Json::FastWriter::enableYAMLCompatibility ()
Definition at line 331 of file json_writer.cpp.
 { yamlCompatiblityEnabled_ = true; }
References yamlCompatiblityEnabled_.
omitEndingLineFeed()
void Json::FastWriter::omitEndingLineFeed ()
Definition at line 335 of file json_writer.cpp.
 { omitEndingLineFeed_ = true; }
References omitEndingLineFeed_.
write()
JSONCPP_STRING Json::FastWriter::write (const Value & root) virtual
Implements Json::Writer.
Definition at line 337 of file json_writer.cpp.
{
   document_.clear();
   writeValue(root);
   if (!omitEndingLineFeed_)
     document_ += "\n";
   return document_;
 }
References document_, omitEndingLineFeed_, and writeValue().
writeValue()
void Json::FastWriter::writeValue (const Value & value) private
Definition at line 345 of file json_writer.cpp.
{
   switch (value.type()) {
   case nullValue:
     if (!dropNullPlaceholders_)
       document_ += "null";
     break;
   case intValue:
     document_ += valueToString(value.asLargestInt());
     break;
   case uintValue:
     document_ += valueToString(value.asLargestUInt());
     break;
   case realValue:
     document_ += valueToString(value.asDouble());
     break;
   case stringValue:
   {
     // Is NULL possible for value.string_? No.
     char const* str;
     char const* end;
     bool ok = value.getString(&str, &end);
     if (ok) document_ += valueToQuotedStringN(str, static_cast<unsigned>(end-str));
     break;
   }
   case booleanValue:
     document_ += valueToString(value.asBool());
     break;
   case arrayValue: {
     document_ += '[';
     ArrayIndex size = value.size();
     for (ArrayIndex index = 0; index < size; ++index) {
       if (index > 0)
         document_ += ',';
       writeValue(value[index]);
     }
     document_ += ']';
   } break;
   case objectValue: {
     Value::Members members(value.getMemberNames());
     document_ += '{';
     for (Value::Members::iterator it = members.begin(); it != members.end();
          ++it) {
       const JSONCPP_STRING& name = *it;
       if (it != members.begin())
         document_ += ',';
       document_ += valueToQuotedStringN(name.data(), static_cast<unsigned>(name.length()));
       document_ += yamlCompatiblityEnabled_ ? ": " : ":";
       writeValue(value[name]);
     }
     document_ += '}';
   } break;
   }
 }
References Json::arrayValue, Json::Value::asBool(), Json::Value::asDouble(), Json::Value::asLargestInt(), Json::Value::asLargestUInt(), Json::booleanValue, document_, dropNullPlaceholders_, Json::Value::getMemberNames(), Json::Value::getString(), Json::intValue, JSONCPP_STRING, Json::nullValue, Json::objectValue, Json::realValue, Json::Value::size(), Json::stringValue, Json::Value::type(), Json::uintValue, Json::valueToQuotedStringN(), Json::valueToString(), and yamlCompatiblityEnabled_.
Referenced by write().
Member Data Documentation
document_
JSONCPP_STRING Json::FastWriter::document_ private
Definition at line 182 of file writer.h.
Referenced by write(), and writeValue().
dropNullPlaceholders_
bool Json::FastWriter::dropNullPlaceholders_ private
Definition at line 184 of file writer.h.
Referenced by dropNullPlaceholders(), and writeValue().
omitEndingLineFeed_
bool Json::FastWriter::omitEndingLineFeed_ private
Definition at line 185 of file writer.h.
Referenced by omitEndingLineFeed(), and write().
yamlCompatiblityEnabled_
bool Json::FastWriter::yamlCompatiblityEnabled_ private
Definition at line 183 of file writer.h.
Referenced by enableYAMLCompatibility(), and writeValue().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/json/writer.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/json/json_writer.cpp