My Project: cMotion Class Reference
cMotion Class Reference
#include <Motion.h>
Classes
struct tParams
Public Types
enum eFrameParams { eFrameTime, eFrameMax }
enum eLoop { eLoopNone, eLoopWrap, eLoopMirror, eLoopMax }
typedef Eigen::VectorXd tFrame
typedef std::function< void(const tFrame *a, const tFrame *b, double lerp, tFrame *out_frame)> tBlendFunc
typedef std::function< void(const std::vector< int > *right_joints, const std::vector< int > *left_joints, tFrame *out_frame)> tMirrorFunc
typedef std::function< void(const tFrame *a, const tFrame *b, double timestep, tFrame *out_vel)> tVelFunc
typedef std::function< void(tFrame *out_frame)> tPostProcessFunc
Public Member Functions
cMotion ()
virtual ~cMotion ()
virtual void Clear ()
virtual bool Load (const tParams &params)
virtual void Init (int num_frames, int num_dofs)
virtual bool IsValid () const
virtual int GetNumFrames () const
virtual int GetNumDof () const
virtual tFrame GetFrame (int i) const
virtual void SetFrame (int i, const tFrame &frame)
virtual void SetFrameTime (int i, double time)
virtual void BlendFrames (int a, int b, double lerp, tFrame &out_frame) const
virtual void CalcFrame (double time, tFrame &out_frame, bool force_mirror=false) const
virtual void CalcFrameVel (double time, cMotion::tFrame &out_vel, bool force_mirror=false) const
virtual void CalcFramePhase (double phase, tFrame &out_frame, bool force_mirror=false) const
virtual double GetDuration () const
virtual void SetDuration (double dur)
virtual double GetFrameTime (int f) const
virtual double GetFrameDuration (int f) const
virtual int CalcCycleCount (double time) const
virtual void CalcIndexPhase (double time, int &out_idx, double &out_phase) const
virtual void UpdateVel ()
virtual bool IsOver (double time) const
virtual bool HasBlendFunc () const
virtual bool HasMirrorFunc () const
virtual bool HasVelFunc () const
virtual bool HasPostProcessFunc () const
virtual bool EnableLoop () const
virtual eLoop GetLoop () const
virtual void SetLoop (eLoop loop)
virtual void Output (const std::string &out_filepath) const
Static Public Member Functions
static std::string BuildFrameJson (const Eigen::VectorXd &frame)
Static Public Attributes
static const std::string gFrameKey = "Frames"
static const std::string gLoopKey = "Loop"
static const std::string gVelFilterCutoffKey = "VelFilterCutoff"
Protected Member Functions
virtual bool LoadJson (const Json::Value &root)
virtual bool ParseLoop (const std::string &str, eLoop &out_loop) const
virtual bool LoadJsonFrames (const Json::Value &root, Eigen::MatrixXd &out_frames) const
virtual bool ParseFrameJson (const Json::Value &root, Eigen::VectorXd &out_frame) const
virtual bool LoadJsonJoints (const Json::Value &root, std::vector< int > &out_right_joints, std::vector< int > &out_left_joints) const
virtual std::string BuildLoopStr (eLoop loop) const
virtual void PostProcessFrames (Eigen::MatrixXd &frames) const
virtual int GetFrameSize () const
virtual void BuildFrameVel (Eigen::MatrixXd &out_frame_vel, bool mirror=false) const
virtual void FilterFrameVel (Eigen::MatrixXd &out_frame_vel) const
virtual void BlendFramesIntern (const cMotion::tFrame *a, const cMotion::tFrame *b, double lerp, cMotion::tFrame *out_frame) const
virtual bool NeedMirrorFrame (double time) const
virtual void MirrorFrame (tFrame &out_frame) const
virtual void CalcFrameVel (const tFrame &frame0, const tFrame &frame1, double dt, tFrame &out_vel) const
Protected Attributes
eLoop mLoop
double mVelFilterCutoff
tParams mParams
Eigen::MatrixXd mFrames
Eigen::MatrixXd mFrameVel
Eigen::MatrixXd mFrameVelMirror
Detailed Description
Definition at line 6 of file Motion.h.
Member Typedef Documentation
tBlendFunc
typedef std::function<void(const tFrame* a, const tFrame* b, double lerp, tFrame* out_frame)> cMotion::tBlendFunc
Definition at line 15 of file Motion.h.
tFrame
typedef Eigen::VectorXd cMotion::tFrame
Definition at line 14 of file Motion.h.
tMirrorFunc
typedef std::function<void(const std::vector<int>* right_joints, const std::vector<int>* left_joints, tFrame* out_frame)> cMotion::tMirrorFunc
Definition at line 16 of file Motion.h.
tPostProcessFunc
typedef std::function<void(tFrame* out_frame)> cMotion::tPostProcessFunc
Definition at line 18 of file Motion.h.
tVelFunc
typedef std::function<void(const tFrame* a, const tFrame* b, double timestep, tFrame* out_vel)> cMotion::tVelFunc
Definition at line 17 of file Motion.h.
Member Enumeration Documentation
eFrameParams
enum cMotion::eFrameParams
Enumerator
eFrameTime
eFrameMax
Definition at line 9 of file Motion.h.
     {
         eFrameTime,
         eFrameMax
     };
eLoop
enum cMotion::eLoop
Enumerator
eLoopNone
eLoopWrap
eLoopMirror
eLoopMax
Definition at line 20 of file Motion.h.
     {
         eLoopNone,
         eLoopWrap,
         eLoopMirror,
         eLoopMax
     };
Constructor & Destructor Documentation
cMotion()
cMotion::cMotion ()
Definition at line 42 of file Motion.cpp.
 {
     Clear();
     mLoop = eLoopNone;
     mVelFilterCutoff = 6; // cutoff 6 Hz
 }
References Clear(), eLoopNone, mLoop, and mVelFilterCutoff.
~cMotion()
cMotion::~cMotion () virtual
Definition at line 49 of file Motion.cpp.
 {
 }
Member Function Documentation
BlendFrames()
void cMotion::BlendFrames (int a, int b, double lerp, tFrame & out_frame) const virtual
Definition at line 185 of file Motion.cpp.
 {
     lerp = cMathUtil::Saturate(lerp);
     // remove time params
     tFrame frame0 = GetFrame(a);
     tFrame frame1 = GetFrame(b);
     if (HasBlendFunc())
     {
         mParams.mBlendFunc(&frame0, &frame1, lerp, &out_frame);
     }
     else
     {
         BlendFramesIntern(&frame0, &frame1, lerp, &out_frame);
     }
 }
References BlendFramesIntern(), GetFrame(), HasBlendFunc(), cMotion::tParams::mBlendFunc, mParams, and cMathUtil::Saturate().
Referenced by CalcFrame().
BlendFramesIntern()
void cMotion::BlendFramesIntern (const cMotion::tFrame * a, const cMotion::tFrame * b, double lerp, cMotion::tFrame * out_frame) const protected virtual
Definition at line 546 of file Motion.cpp.
 {
     *out_frame = (1 - lerp) * (*a) + lerp * (*b);
 }
Referenced by BlendFrames().
BuildFrameJson()
std::string cMotion::BuildFrameJson (const Eigen::VectorXd & frame) static
Definition at line 24 of file Motion.cpp.
 {
     std::string json = cJsonUtil::BuildVectorJson(frame);
     return json;
 }
References cJsonUtil::BuildVectorJson().
BuildFrameVel()
void cMotion::BuildFrameVel (Eigen::MatrixXd & out_frame_vel, bool mirror = false) const protected virtual
Definition at line 121 of file Motion.cpp.
 {
     int num_frames = GetNumFrames();
     int dof = GetNumDof();
     out_frame_vel = Eigen::MatrixXd::Zero(num_frames, dof);
     Eigen::VectorXd vel;
     for (int f = 0; f < num_frames - 1; ++f)
     {
         double dt = GetFrameDuration(f);
         Eigen::VectorXd frame0 = GetFrame(f);
         Eigen::VectorXd frame1 = GetFrame(f + 1);
         if (mirror)
         {
             MirrorFrame(frame0);
             MirrorFrame(frame1);
         }
         CalcFrameVel(frame0, frame1, dt, vel);
         out_frame_vel.row(f) = vel;
     }
     if (num_frames > 1)
     {
         out_frame_vel.row(num_frames - 1) = out_frame_vel.row(num_frames - 2);
     }
     if (mVelFilterCutoff > 0)
     {
         FilterFrameVel(out_frame_vel);
     }
 }
References CalcFrameVel(), FilterFrameVel(), GetFrame(), GetFrameDuration(), GetNumDof(), GetNumFrames(), MirrorFrame(), and mVelFilterCutoff.
Referenced by UpdateVel().
BuildLoopStr()
std::string cMotion::BuildLoopStr (eLoop loop) const protected virtual
Definition at line 386 of file Motion.cpp.
 {
     return gLoopStr[loop];
 }
References gLoopStr.
Referenced by Output().
CalcCycleCount()
int cMotion::CalcCycleCount (double time) const virtual
Definition at line 450 of file Motion.cpp.
 {
     double dur = GetDuration();
     double phases = time / dur;
     int count = static_cast<int>(std::floor(phases));
     bool loop = EnableLoop();
     count = (loop) ? count : cMathUtil::Clamp(count, 0, 1);
     return count;
 }
References cMathUtil::Clamp(), EnableLoop(), and GetDuration().
Referenced by CalcIndexPhase(), cKinCharacter::CalcPose(), and NeedMirrorFrame().
CalcFrame()
void cMotion::CalcFrame (double time, tFrame & out_frame, bool force_mirror = false) const virtual
Definition at line 203 of file Motion.cpp.
 {
     int idx;
     double phase;
     CalcIndexPhase(time, idx, phase);
     BlendFrames(idx, idx + 1, phase, out_frame);
     if (NeedMirrorFrame(time) || force_mirror)
     {
         MirrorFrame(out_frame);
     }
 }
References BlendFrames(), CalcIndexPhase(), MirrorFrame(), and NeedMirrorFrame().
Referenced by CalcFramePhase(), and cKinCharacter::CalcPose().
CalcFramePhase()
void cMotion::CalcFramePhase (double phase, tFrame & out_frame, bool force_mirror = false) const virtual
Definition at line 243 of file Motion.cpp.
 {
     double max_time = GetDuration();
     double time = phase * max_time;
     CalcFrame(time, out_frame, force_mirror);
 }
References CalcFrame(), and GetDuration().
CalcFrameVel() [1/2]
void cMotion::CalcFrameVel (const tFrame & frame0, const tFrame & frame1, double dt, tFrame & out_vel) const protected virtual
Definition at line 569 of file Motion.cpp.
 {
     if (HasVelFunc())
     {
         mParams.mVelFunc(&frame0, &frame1, dt, &out_vel);
     }
     else
     {
         out_vel = (frame1 - frame0) / dt;
     }
 }
References HasVelFunc(), mParams, and cMotion::tParams::mVelFunc.
CalcFrameVel() [2/2]
void cMotion::CalcFrameVel (double time, cMotion::tFrame & out_vel, bool force_mirror = false) const virtual
Definition at line 216 of file Motion.cpp.
 {
     if (!EnableLoop() && time >= GetDuration())
     {
         out_vel = Eigen::VectorXd::Zero(GetNumDof());
     }
     else
     {
         const Eigen::MatrixXd* vel_frame = nullptr;
         if (NeedMirrorFrame(time) || force_mirror)
         {
             vel_frame = &mFrameVelMirror;
         }
         else
         {
             vel_frame = &mFrameVel;
         }
         int idx;
         double phase;
         CalcIndexPhase(time, idx, phase);
         auto vel0 = vel_frame->row(idx);
         auto vel1 = vel_frame->row(idx + 1);
         out_vel = (1 - phase) * vel0 + phase * vel1;
     }
 }
References CalcIndexPhase(), EnableLoop(), GetDuration(), GetNumDof(), mFrameVel, mFrameVelMirror, and NeedMirrorFrame().
Referenced by BuildFrameVel(), and cKinCharacter::CalcVel().
CalcIndexPhase()
void cMotion::CalcIndexPhase (double time, int & out_idx, double & out_phase) const virtual
Definition at line 460 of file Motion.cpp.
 {
     double max_time = GetDuration();
     if (!EnableLoop())
     {
         if (time <= gMinTime)
         {
             out_idx = 0;
             out_phase = 0;
             return;
         }
         else if (time >= max_time)
         {
             out_idx = GetNumFrames() - 2;
             out_phase = 1;
             return;
         }
     }
     int cycle_count = CalcCycleCount(time);
     time -= cycle_count * GetDuration();
     if (time < 0)
     {
         time += max_time;
     }
     const Eigen::VectorXd& frame_times = mFrames.col(eFrameTime);
     auto it = std::upper_bound(frame_times.data(), frame_times.data() + frame_times.size(), time);
     out_idx = static_cast<int>(it - frame_times.data() - 1);
     double time0 = frame_times(out_idx);
     double time1 = frame_times(out_idx + 1);
     out_phase = (time - time0) / (time1 - time0);
 }
References CalcCycleCount(), eFrameTime, EnableLoop(), GetDuration(), GetNumFrames(), gMinTime, and mFrames.
Referenced by CalcFrame(), and CalcFrameVel().
Clear()
void cMotion::Clear () virtual
Definition at line 54 of file Motion.cpp.
 {
     mFrames.resize(0, 0);
     mFrameVel.resize(0, 0);
     mFrameVelMirror.resize(0, 0);
     mParams = tParams();
 }
References mFrames, mFrameVel, mFrameVelMirror, and mParams.
Referenced by cKinCharacter::Clear(), cMotion(), Init(), Load(), and cKinCharacter::LoadMotion().
EnableLoop()
bool cMotion::EnableLoop () const virtual
Definition at line 531 of file Motion.cpp.
 {
     return mLoop != eLoopNone;
 }
References eLoopNone, and mLoop.
Referenced by CalcCycleCount(), CalcFrameVel(), CalcIndexPhase(), cKinCharacter::CalcPose(), cKinCharacter::GetCycle(), cKinCharacter::GetPhase(), and IsOver().
FilterFrameVel()
void cMotion::FilterFrameVel (Eigen::MatrixXd & out_frame_vel) const protected virtual
Definition at line 154 of file Motion.cpp.
 {
     double dt = GetFrameDuration(0);
     int num_dof = static_cast<int>(out_frame_vel.cols());
     for (int i = 0; i < num_dof; ++i)
     {
         Eigen::VectorXd x = out_frame_vel.col(i);
         cMathUtil::ButterworthFilter(dt, mVelFilterCutoff, x);
         out_frame_vel.col(i) = x;
     }
 }
References cMathUtil::ButterworthFilter(), GetFrameDuration(), and mVelFilterCutoff.
Referenced by BuildFrameVel().
GetDuration()
double cMotion::GetDuration () const virtual
Definition at line 413 of file Motion.cpp.
 {
     int num_frames = GetNumFrames();
     double max_time = mFrames(num_frames - 1, eFrameTime);
     return max_time;
 }
References eFrameTime, GetNumFrames(), and mFrames.
Referenced by CalcCycleCount(), CalcFramePhase(), CalcFrameVel(), CalcIndexPhase(), cSceneImitate::CheckTerminate(), cKinCharacter::GetCycle(), cKinCharacter::GetMotionDuration(), cKinCharacter::GetPhase(), IsOver(), and SetDuration().
GetFrame()
cMotion::tFrame cMotion::GetFrame (int i) const virtual
Definition at line 167 of file Motion.cpp.
 {
     int frame_size = GetFrameSize();
     return mFrames.row(i).segment(eFrameMax, frame_size - eFrameMax);
 }
References eFrameMax, GetFrameSize(), and mFrames.
Referenced by BlendFrames(), BuildFrameVel(), and cKinCharacter::CalcCycleRootDelta().
GetFrameDuration()
double cMotion::GetFrameDuration (int f) const virtual
Definition at line 440 of file Motion.cpp.
 {
     double dur = 0;
     if (f < GetNumFrames() - 1)
     {
         dur = GetFrameTime(f + 1) - GetFrameTime(f);
     }
     return dur;
 }
References GetFrameTime(), and GetNumFrames().
Referenced by BuildFrameVel(), FilterFrameVel(), and Output().
GetFrameSize()
int cMotion::GetFrameSize () const protected virtual
Definition at line 116 of file Motion.cpp.
 {
     return static_cast<int>(mFrames.cols());
 }
References mFrames.
Referenced by GetFrame(), GetNumDof(), PostProcessFrames(), and SetFrame().
GetFrameTime()
double cMotion::GetFrameTime (int f) const virtual
Definition at line 435 of file Motion.cpp.
 {
     return mFrames(f, eFrameTime);
 }
References eFrameTime, and mFrames.
Referenced by GetFrameDuration(), and SetDuration().
GetLoop()
cMotion::eLoop cMotion::GetLoop () const virtual
Definition at line 536 of file Motion.cpp.
 {
     return mLoop;
 }
References mLoop.
Referenced by cSceneImitate::CheckTerminate().
GetNumDof()
int cMotion::GetNumDof () const virtual
Definition at line 106 of file Motion.cpp.
 {
     return GetFrameSize() - eFrameMax;
 }
References eFrameMax, and GetFrameSize().
Referenced by BuildFrameVel(), CalcFrameVel(), and cKinCharacter::LoadMotion().
GetNumFrames()
int cMotion::GetNumFrames () const virtual
Definition at line 111 of file Motion.cpp.
 {
     return static_cast<int>(mFrames.rows());
 }
References mFrames.
Referenced by BuildFrameVel(), cKinCharacter::CalcCycleRootDelta(), CalcIndexPhase(), GetDuration(), GetFrameDuration(), IsValid(), Output(), and SetDuration().
HasBlendFunc()
bool cMotion::HasBlendFunc () const virtual
Definition at line 511 of file Motion.cpp.
 {
     return mParams.mBlendFunc != nullptr;
 }
References cMotion::tParams::mBlendFunc, and mParams.
Referenced by BlendFrames().
HasMirrorFunc()
bool cMotion::HasMirrorFunc () const virtual
Definition at line 516 of file Motion.cpp.
 {
     return mParams.mMirrorFunc != nullptr;
 }
References cMotion::tParams::mMirrorFunc, and mParams.
HasPostProcessFunc()
bool cMotion::HasPostProcessFunc () const virtual
Definition at line 526 of file Motion.cpp.
 {
     return mParams.mPostProcessFunc != nullptr;
 }
References mParams, and cMotion::tParams::mPostProcessFunc.
Referenced by PostProcessFrames().
HasVelFunc()
bool cMotion::HasVelFunc () const virtual
Definition at line 521 of file Motion.cpp.
 {
     return mParams.mVelFunc != nullptr;
 }
References mParams, and cMotion::tParams::mVelFunc.
Referenced by CalcFrameVel().
Init()
void cMotion::Init (int num_frames, int num_dofs) virtual
Definition at line 95 of file Motion.cpp.
 {
     Clear();
     mFrames = Eigen::MatrixXd::Zero(num_frames, num_dofs + eFrameMax);
 }
References Clear(), eFrameMax, and mFrames.
Referenced by cBVHReader::BuildMotion().
IsOver()
bool cMotion::IsOver (double time) const virtual
Definition at line 506 of file Motion.cpp.
 {
     return !EnableLoop() && (time >= GetDuration());
 }
References EnableLoop(), and GetDuration().
Referenced by cKinCharacter::IsMotionOver().
IsValid()
bool cMotion::IsValid () const virtual
Definition at line 101 of file Motion.cpp.
 {
     return GetNumFrames() > 0;
 }
References GetNumFrames().
Referenced by cKinCharacter::GetMotionDuration(), and cKinCharacter::HasMotion().
Load()
bool cMotion::Load (const tParams & params) virtual
Definition at line 62 of file Motion.cpp.
 {
     Clear();
     mParams = params;
     std::ifstream f_stream(mParams.mMotionFile);
     Json::Value root;
     Json::Reader reader;
     bool succ = reader.parse(f_stream, root);
     f_stream.close();
     if (succ)
     {
         succ = LoadJson(root);
         if (succ)
         {
             PostProcessFrames(mFrames);
             UpdateVel();
         }
         else
         {
             printf("Failed to load motion from file %s\n", mParams.mMotionFile.c_str());
             assert(false);
         }
     }
     else
     {
         printf("Failed to parse Json from %s\n", mParams.mMotionFile.c_str());
         assert(false);
     }
     return succ;
 }
References Clear(), LoadJson(), mFrames, cMotion::tParams::mMotionFile, mParams, Json::Reader::parse(), PostProcessFrames(), and UpdateVel().
Referenced by cKinCharacter::LoadMotion().
LoadJson()
bool cMotion::LoadJson (const Json::Value & root) protected virtual
Definition at line 250 of file Motion.cpp.
 {
     bool succ = true;
     if (!root[gLoopKey].isNull())
     {
         std::string loop_str = root[gLoopKey].asString();
         ParseLoop(loop_str, mLoop);
     }
     mVelFilterCutoff = root.get(gVelFilterCutoffKey, mVelFilterCutoff).asDouble();
     if (mParams.mRightJoints.size() == 0 && mParams.mLeftJoints.size() == 0)
     {
         succ &= LoadJsonJoints(root, mParams.mRightJoints, mParams.mLeftJoints);
     }
     assert(mParams.mRightJoints.size() == mParams.mLeftJoints.size());
     if (!root[gFrameKey].isNull())
     {
         succ &= LoadJsonFrames(root[gFrameKey], mFrames);
     }
     return succ;
 }
References Json::Value::asDouble(), Json::Value::asString(), Json::Value::get(), gFrameKey, gLoopKey, gVelFilterCutoffKey, LoadJsonFrames(), LoadJsonJoints(), mFrames, cMotion::tParams::mLeftJoints, mLoop, mParams, cMotion::tParams::mRightJoints, mVelFilterCutoff, and ParseLoop().
Referenced by Load().
LoadJsonFrames()
bool cMotion::LoadJsonFrames (const Json::Value & root, Eigen::MatrixXd & out_frames) const protected virtual
Definition at line 296 of file Motion.cpp.
 {
     bool succ = true;
     assert(root.isArray());
     int num_frames = root.size();
     int data_size = 0;
     if (num_frames > 0)
     {
         int idx0 = 0;
         Json::Value frame_json = root.get(idx0, 0);
         data_size = frame_json.size();
         out_frames.resize(num_frames, data_size);
     }
     for (int f = 0; f < num_frames; ++f)
     {
         Eigen::VectorXd curr_frame;
         succ &= ParseFrameJson(root.get(f, 0), curr_frame);
         if (succ)
         {
             assert(mFrames.cols() == curr_frame.size());
             out_frames.row(f) = curr_frame;
         }
         else
         {
             out_frames.resize(0, 0);
             break;
         }
     }
     return succ;
 }
References Json::Value::get(), Json::Value::isArray(), mFrames, ParseFrameJson(), and Json::Value::size().
Referenced by LoadJson().
LoadJsonJoints()
bool cMotion::LoadJsonJoints (const Json::Value & root, std::vector< int > & out_right_joints, std::vector< int > & out_left_joints) const protected virtual
Definition at line 348 of file Motion.cpp.
 {
     bool succ = true;
     if (!root[gRightJointsKey].isNull() && !root[gLeftJointsKey].isNull())
     {
         auto right_joints_json = root[gRightJointsKey];
         auto left_joints_json = root[gLeftJointsKey];
         assert(right_joints_json.isArray());
         assert(left_joints_json.isArray());
         int num_right_joints = right_joints_json.size();
         assert(num_right_joints == left_joints_json.size());
         succ = num_right_joints == left_joints_json.size();
         if (succ)
         {
             std::vector<int> right_joints(num_right_joints);
             std::vector<int> left_joints(num_right_joints);
             out_right_joints.resize(num_right_joints);
             out_left_joints.resize(num_right_joints);
             for (int i = 0; i < num_right_joints; ++i)
             {
                 int right_id = right_joints_json[i].asInt();
                 int left_id = left_joints_json[i].asInt();
                 out_right_joints[i] = right_id;
                 out_left_joints[i] = left_id;
             }
         }
     }
     else
     {
         out_right_joints.clear();
         out_left_joints.clear();
     }
     return succ;
 }
References gLeftJointsKey, gRightJointsKey, and Json::Value::size().
Referenced by LoadJson().
MirrorFrame()
void cMotion::MirrorFrame (tFrame & out_frame) const protected virtual
Definition at line 562 of file Motion.cpp.
 {
     assert(mParams.mMirrorFunc != nullptr);
     assert(mParams.mLeftJoints.size() > 0 && mParams.mRightJoints.size() > 0);
     mParams.mMirrorFunc(&mParams.mLeftJoints, &mParams.mRightJoints, &out_frame);
 }
References cMotion::tParams::mLeftJoints, cMotion::tParams::mMirrorFunc, mParams, and cMotion::tParams::mRightJoints.
Referenced by BuildFrameVel(), and CalcFrame().
NeedMirrorFrame()
bool cMotion::NeedMirrorFrame (double time) const protected virtual
Definition at line 551 of file Motion.cpp.
 {
     bool mirror = false;
     if (mLoop == eLoopMirror)
     {
         int cycle = CalcCycleCount(time);
         mirror = cycle % 2 != 0;
     }
     return mirror;
 }
References CalcCycleCount(), eLoopMirror, and mLoop.
Referenced by CalcFrame(), and CalcFrameVel().
Output()
void cMotion::Output (const std::string & out_filepath) const virtual
Definition at line 581 of file Motion.cpp.
 {
     FILE* file = cFileUtil::OpenFile(out_filepath, "w");
     fprintf(file, "{\n");
     fprintf(file, "\"%s\": ", gLoopKey.c_str());
     std::string loop_str = BuildLoopStr(mLoop);
     fprintf(file, "\"%s\",\n", loop_str.c_str());
     fprintf(file, "\"%s\": %.5f,\n", gVelFilterCutoffKey.c_str(), mVelFilterCutoff);
     if (mParams.mRightJoints.size() > 0 && mParams.mLeftJoints.size() > 0)
     {
         fprintf(file, "\"%s\": [", gRightJointsKey.c_str());
         for (size_t i = 0; i < mParams.mRightJoints.size(); ++i)
         {
             if (i != 0)
             {
                 fprintf(file, ", ");
             }
             fprintf(file, "%i", mParams.mRightJoints[i]);
         }
         fprintf(file, "],\n");
         fprintf(file, "\"%s\": [", gLeftJointsKey.c_str());
         for (size_t i = 0; i < mParams.mLeftJoints.size(); ++i)
         {
             if (i != 0)
             {
                 fprintf(file, ", ");
             }
             fprintf(file, "%i", mParams.mLeftJoints[i]);
         }
         fprintf(file, "],\n");
     }
     fprintf(file, "\"Frames\":\n[\n");
     int num_frames = GetNumFrames();
     for (int f = 0; f < num_frames; ++f)
     {
         if (f != 0)
         {
             fprintf(file, ",\n");
         }
         Eigen::VectorXd curr_frame = mFrames.row(f);
         double dur = 0;
         if (f < num_frames - 1)
         {
             dur = GetFrameDuration(f);
         }
         curr_frame[eFrameTime] = dur;
         std::string frame_json = cJsonUtil::BuildVectorJson(curr_frame);
         fprintf(file, "%s", frame_json.c_str());
     }
     fprintf(file, "\n]");
     fprintf(file, "\n}");
     cFileUtil::CloseFile(file);
 }
References BuildLoopStr(), cJsonUtil::BuildVectorJson(), cFileUtil::CloseFile(), eFrameTime, GetFrameDuration(), GetNumFrames(), gLeftJointsKey, gLoopKey, gRightJointsKey, gVelFilterCutoffKey, mFrames, cMotion::tParams::mLeftJoints, mLoop, mParams, cMotion::tParams::mRightJoints, mVelFilterCutoff, and cFileUtil::OpenFile().
ParseFrameJson()
bool cMotion::ParseFrameJson (const Json::Value & root, Eigen::VectorXd & out_frame) const protected virtual
Definition at line 330 of file Motion.cpp.
 {
     bool succ = false;
     if (root.isArray())
     {
         int data_size = root.size();
         out_frame.resize(data_size);
         for (int i = 0; i < data_size; ++i)
         {
             Json::Value json_elem = root.get(i, 0);
             out_frame[i] = json_elem.asDouble();
         }
         succ = true;
     }
     return succ;
 }
References Json::Value::asDouble(), Json::Value::get(), Json::Value::isArray(), and Json::Value::size().
Referenced by LoadJsonFrames().
ParseLoop()
bool cMotion::ParseLoop (const std::string & str, eLoop & out_loop) const protected virtual
Definition at line 274 of file Motion.cpp.
 {
     bool succ = false;
     for (int i = 0; i < eLoopMax; ++i)
     {
         if (str == gLoopStr[i])
         {
             out_loop = static_cast<eLoop>(i);
             succ = true;
             break;
         }
     }
     if (!succ)
     {
         printf("Unsupported loop mode: %s\n", str.c_str());
         assert(false);
         succ = false;
     }
     return succ;
 }
References eLoopMax, and gLoopStr.
Referenced by LoadJson().
PostProcessFrames()
void cMotion::PostProcessFrames (Eigen::MatrixXd & frames) const protected virtual
Definition at line 391 of file Motion.cpp.
 {
     int frame_size = GetFrameSize();
     int num_frames = static_cast<int>(frames.rows());
     double curr_time = gMinTime;
     for (int f = 0; f < num_frames; ++f)
     {
         auto curr_frame = frames.row(f);
         double duration = curr_frame(0, eFrameTime);
         curr_frame(0, eFrameTime) = curr_time;
         curr_time += duration;
         if (HasPostProcessFunc())
         {
             Eigen::VectorXd pose = curr_frame.segment(eFrameMax, frame_size - eFrameMax);
             mParams.mPostProcessFunc(&pose);
             curr_frame.segment(eFrameMax, frame_size - eFrameMax) = pose;
         }
     }
 }
References eFrameMax, eFrameTime, GetFrameSize(), gMinTime, HasPostProcessFunc(), mParams, and cMotion::tParams::mPostProcessFunc.
Referenced by Load().
SetDuration()
void cMotion::SetDuration (double dur) virtual
Definition at line 420 of file Motion.cpp.
 {
     double dur_old = GetDuration();
     int num_frames = GetNumFrames();
     for (int f = 0; f < num_frames; ++f)
     {
         double t = GetFrameTime(f);
         t /= dur_old;
         t *= dur;
         SetFrameTime(f, t);
     }
     UpdateVel();
 }
References GetDuration(), GetFrameTime(), GetNumFrames(), SetFrameTime(), and UpdateVel().
Referenced by cKinCharacter::SetMotionDuration().
SetFrame()
void cMotion::SetFrame (int i, const tFrame & frame) virtual
Definition at line 173 of file Motion.cpp.
 {
     int frame_size = GetFrameSize();
     assert(frame.size() == frame_size - eFrameMax);
     mFrames.row(i).segment(eFrameMax, frame_size - eFrameMax) = frame;
 }
References eFrameMax, GetFrameSize(), and mFrames.
Referenced by cBVHReader::BuildMotion().
SetFrameTime()
void cMotion::SetFrameTime (int i, double time) virtual
Definition at line 180 of file Motion.cpp.
 {
     mFrames(i, 0) = time;
 }
References mFrames.
Referenced by cBVHReader::BuildMotion(), and SetDuration().
SetLoop()
void cMotion::SetLoop (eLoop loop) virtual
Definition at line 541 of file Motion.cpp.
 {
     mLoop = loop;
 }
References mLoop.
UpdateVel()
void cMotion::UpdateVel () virtual
Definition at line 496 of file Motion.cpp.
 {
     BuildFrameVel(mFrameVel, false);
     if (mLoop == eLoopMirror)
     {
         BuildFrameVel(mFrameVelMirror, true);
     }
 }
References BuildFrameVel(), eLoopMirror, mFrameVel, mFrameVelMirror, and mLoop.
Referenced by Load(), and SetDuration().
Member Data Documentation
gFrameKey
const std::string cMotion::gFrameKey = "Frames" static
Definition at line 42 of file Motion.h.
Referenced by LoadJson().
gLoopKey
const std::string cMotion::gLoopKey = "Loop" static
Definition at line 43 of file Motion.h.
Referenced by LoadJson(), and Output().
gVelFilterCutoffKey
const std::string cMotion::gVelFilterCutoffKey = "VelFilterCutoff" static
Definition at line 44 of file Motion.h.
Referenced by LoadJson(), and Output().
mFrames
Eigen::MatrixXd cMotion::mFrames protected
Definition at line 90 of file Motion.h.
Referenced by CalcIndexPhase(), Clear(), GetDuration(), GetFrame(), GetFrameSize(), GetFrameTime(), GetNumFrames(), Init(), Load(), LoadJson(), LoadJsonFrames(), Output(), SetFrame(), and SetFrameTime().
mFrameVel
Eigen::MatrixXd cMotion::mFrameVel protected
Definition at line 91 of file Motion.h.
Referenced by CalcFrameVel(), Clear(), and UpdateVel().
mFrameVelMirror
Eigen::MatrixXd cMotion::mFrameVelMirror protected
Definition at line 92 of file Motion.h.
Referenced by CalcFrameVel(), Clear(), and UpdateVel().
mLoop
eLoop cMotion::mLoop protected
Definition at line 87 of file Motion.h.
Referenced by cMotion(), EnableLoop(), GetLoop(), LoadJson(), NeedMirrorFrame(), Output(), SetLoop(), and UpdateVel().
mParams
tParams cMotion::mParams protected
Definition at line 89 of file Motion.h.
Referenced by BlendFrames(), CalcFrameVel(), Clear(), HasBlendFunc(), HasMirrorFunc(), HasPostProcessFunc(), HasVelFunc(), Load(), LoadJson(), MirrorFrame(), Output(), and PostProcessFrames().
mVelFilterCutoff
double cMotion::mVelFilterCutoff protected
Definition at line 88 of file Motion.h.
Referenced by BuildFrameVel(), cMotion(), FilterFrameVel(), LoadJson(), and Output().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/anim/Motion.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/anim/Motion.cpp