My Project: cDeepMimicCharController Class Reference
cDeepMimicCharController Class Reference
#include <DeepMimicCharController.h>
Public Member Functions
virtual EIGEN_MAKE_ALIGNED_OPERATOR_NEW ~cDeepMimicCharController ()
virtual void Init (cSimCharacter *character, const std::string &param_file)
virtual void Reset ()
virtual void Clear ()
virtual void Update (double timestep)
virtual void PostUpdate (double timestep)
virtual void UpdateCalcTau (double timestep, Eigen::VectorXd &out_tau)
virtual void UpdateApplyTau (const Eigen::VectorXd &tau)
virtual bool NeedNewAction () const
virtual void ApplyAction (const Eigen::VectorXd &action)
virtual void RecordState (Eigen::VectorXd &out_state)
virtual void RecordGoal (Eigen::VectorXd &out_goal) const
virtual void RecordAction (Eigen::VectorXd &out_action) const
virtual eActionSpace GetActionSpace () const
virtual int GetStateSize () const
virtual double GetRewardMin () const
virtual double GetRewardMax () const
virtual void SetViewDistMin (double dist)
virtual void SetViewDistMax (double dist)
virtual double GetViewDistMin () const
virtual double GetViewDistMax () const
virtual void GetViewBound (tVector &out_min, tVector &out_max) const
virtual double GetPrevActionTime () const
virtual const tVector & GetPrevActionCOM () const
virtual double GetTime () const
virtual const Eigen::VectorXd & GetTau () const
virtual const cCircularBuffer< double > & GetValLog () const
virtual void LogVal (double val)
Public Member Functions inherited from cCharController
virtual ~cCharController ()
virtual int GetGoalSize () const
virtual int GetActionSize () const
virtual int GetNumActions () const
virtual void HandlePoseReset ()
virtual void HandleVelReset ()
virtual void BuildStateOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildGoalOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionBounds (Eigen::VectorXd &out_min, Eigen::VectorXd &out_max) const
virtual void BuildStateNormGroups (Eigen::VectorXi &out_groups) const
virtual void BuildGoalNormGroups (Eigen::VectorXi &out_groups) const
virtual int NumChildren () const
virtual const std::shared_ptr< cCharController > & GetChild (int i) const
virtual std::string GetName () const =0
Public Member Functions inherited from cController
virtual ~cController ()
virtual void Init (cSimCharacter *character)
virtual bool IsValid () const
virtual bool LoadParams (const std::string &param_file)
virtual int GetNumOptParams () const
virtual void BuildOptParams (Eigen::VectorXd &out_params) const
virtual void SetOptParams (const Eigen::VectorXd &params)
virtual void SetOptParams (const Eigen::VectorXd &params, Eigen::VectorXd &out_params) const
virtual void FetchOptParamScale (Eigen::VectorXd &out_scale) const
virtual void OutputOptParams (const std::string &file, const Eigen::VectorXd &params) const
virtual void OutputOptParams (FILE *f, const Eigen::VectorXd &params) const
virtual void SetActive (bool active)
virtual bool IsActive () const
virtual void SetMode (eMode mode)
virtual const cSimCharacter * GetChar () const
Protected Member Functions
cDeepMimicCharController ()
virtual bool ParseParams (const Json::Value &json)
virtual void ResetParams ()
virtual void InitResources ()
virtual void InitAction ()
virtual void InitTau ()
virtual int GetPosDim () const
virtual bool CheckNeedNewAction (double timestep) const
virtual void NewActionUpdate ()
virtual void HandleNewAction ()
virtual void PostProcessAction (Eigen::VectorXd &out_action) const
virtual void BuildStatePose (Eigen::VectorXd &out_pose) const
virtual void BuildStateVel (Eigen::VectorXd &out_vel) const
virtual int GetStatePoseOffset () const
virtual int GetStateVelOffset () const
virtual int GetStatePoseSize () const
virtual int GetStateVelSize () const
Protected Member Functions inherited from cCharController
cCharController ()
Protected Member Functions inherited from cController
cController ()
Protected Attributes
double mTime
bool mNeedNewAction
Eigen::VectorXd mAction
Eigen::VectorXd mTau
double mViewDistMin
double mViewDistMax
int mPosDim
double mPrevActionTime
tVector mPrevActionCOM
cCircularBuffer< double > mValLog
Protected Attributes inherited from cController
cSimCharacter * mChar
eMode mMode
bool mValid
Additional Inherited Members
Public Types inherited from cController
enum eMode { eModeActive, eModeInactive, eModePassive, eModeMax }
Static Public Attributes inherited from cCharController
const static int gNormGroupSingle = 0
const static int gNormGroupNone = -1
Detailed Description
Definition at line 6 of file DeepMimicCharController.h.
Constructor & Destructor Documentation
~cDeepMimicCharController()
cDeepMimicCharController::~cDeepMimicCharController () virtual
Definition at line 26 of file DeepMimicCharController.cpp.
 {
 }
cDeepMimicCharController()
cDeepMimicCharController::cDeepMimicCharController () protected
Definition at line 13 of file DeepMimicCharController.cpp.
                                                    : cCharController()
 {
     mTime = 0;
     mPosDim = 0;
     SetViewDistMin(-0.5);
     SetViewDistMax(10);
     mPrevActionTime = mTime;
     mPrevActionCOM.setZero();
     mValLog.Reserve(gValLogSize);
 }
References gValLogSize, mPosDim, mPrevActionCOM, mPrevActionTime, mTime, mValLog, cCircularBuffer< tVal, tAlloc >::Reserve(), SetViewDistMax(), and SetViewDistMin().
Member Function Documentation
ApplyAction()
void cDeepMimicCharController::ApplyAction (const Eigen::VectorXd & action) virtual
Reimplemented from cCharController.
Reimplemented in cCtPDController, and cCtVelController.
Definition at line 149 of file DeepMimicCharController.cpp.
 {
     assert(action.size() == GetActionSize());
     mAction = action;
     PostProcessAction(mAction);
 }
References cCharController::GetActionSize(), mAction, and PostProcessAction().
Referenced by cCtVelController::ApplyAction(), and cCtPDController::ApplyAction().
BuildStatePose()
void cDeepMimicCharController::BuildStatePose (Eigen::VectorXd & out_pose) const protected virtual
Reimplemented in cCtController.
Definition at line 274 of file DeepMimicCharController.cpp.
 {
     tMatrix origin_trans = mChar->BuildOriginTrans();
     tVector root_pos = mChar->GetRootPos();
     tVector root_pos_rel = root_pos;
     root_pos_rel[3] = 1;
     root_pos_rel = origin_trans * root_pos_rel;
     root_pos_rel[3] = 0;
     out_pose = Eigen::VectorXd::Zero(GetStatePoseSize());
     out_pose[0] = root_pos_rel[1];
     int idx = 1;
     int num_parts = mChar->GetNumBodyParts();
     for (int i = 1; i < num_parts; ++i)
     {
         if (mChar->IsValidBodyPart(i))
         {
             const auto& curr_part = mChar->GetBodyPart(i);
             tVector curr_pos = curr_part->GetPos();
             curr_pos[3] = 1;
             curr_pos = origin_trans * curr_pos;
             curr_pos[3] = 0;
             curr_pos -= root_pos_rel;
             out_pose.segment(idx, mPosDim) = curr_pos.segment(0, mPosDim);
             idx += mPosDim;
         }
     }
 }
References cCharacter::BuildOriginTrans(), cSimCharacter::GetBodyPart(), cSimCharacter::GetNumBodyParts(), cSimCharacter::GetRootPos(), GetStatePoseSize(), cSimCharacter::IsValidBodyPart(), cController::mChar, and mPosDim.
Referenced by RecordState().
BuildStateVel()
void cDeepMimicCharController::BuildStateVel (Eigen::VectorXd & out_vel) const protected virtual
Reimplemented in cCtController.
Definition at line 308 of file DeepMimicCharController.cpp.
 {
     out_vel.resize(GetStateVelSize());
     tMatrix origin_trans = mChar->BuildOriginTrans();
     tVector root_pos = mChar->GetRootPos();
     int idx = 0;
     int num_parts = mChar->GetNumBodyParts();
     for (int i = 0; i < num_parts; ++i)
     {
         tVector curr_vel = mChar->GetBodyPartVel(i);
         curr_vel = origin_trans * curr_vel;
         out_vel.segment(idx, mPosDim) = curr_vel.segment(0, mPosDim);
         idx += mPosDim;
     }
 }
References cCharacter::BuildOriginTrans(), cSimCharacter::GetBodyPartVel(), cSimCharacter::GetNumBodyParts(), cSimCharacter::GetRootPos(), GetStateVelSize(), cController::mChar, and mPosDim.
Referenced by RecordState().
CheckNeedNewAction()
bool cDeepMimicCharController::CheckNeedNewAction (double timestep) const protected virtual
Reimplemented in cCtController.
Definition at line 254 of file DeepMimicCharController.cpp.
 {
     return false;
 }
Referenced by PostUpdate().
Clear()
void cDeepMimicCharController::Clear () virtual
Reimplemented from cController.
Reimplemented in cCtPDController.
Definition at line 49 of file DeepMimicCharController.cpp.
 {
     cCharController::Clear();
     ResetParams();
 }
References cController::Clear(), and ResetParams().
Referenced by cCtPDController::Clear().
GetActionSpace()
eActionSpace cDeepMimicCharController::GetActionSpace () const virtual
Implements cCharController.
Definition at line 183 of file DeepMimicCharController.cpp.
 {
     return eActionSpaceContinuous;
 }
References eActionSpaceContinuous.
GetPosDim()
int cDeepMimicCharController::GetPosDim () const protected virtual
Definition at line 248 of file DeepMimicCharController.cpp.
 {
     int dim = 3;
     return dim;
 }
Referenced by Init().
GetPrevActionCOM()
const tVector & cDeepMimicCharController::GetPrevActionCOM () const virtual
Definition at line 119 of file DeepMimicCharController.cpp.
 {
     return mPrevActionCOM;
 }
References mPrevActionCOM.
GetPrevActionTime()
double cDeepMimicCharController::GetPrevActionTime () const virtual
Definition at line 114 of file DeepMimicCharController.cpp.
 {
     return mPrevActionTime;
 }
References mPrevActionTime.
GetRewardMax()
double cDeepMimicCharController::GetRewardMax () const virtual
Reimplemented from cCharController.
Definition at line 206 of file DeepMimicCharController.cpp.
 {
     return 1;
 }
GetRewardMin()
double cDeepMimicCharController::GetRewardMin () const virtual
Reimplemented from cCharController.
Definition at line 201 of file DeepMimicCharController.cpp.
 {
     return 0;
 }
GetStatePoseOffset()
int cDeepMimicCharController::GetStatePoseOffset () const protected virtual
Reimplemented in cCtController.
Definition at line 326 of file DeepMimicCharController.cpp.
 {
     return 0;
 }
Referenced by cCtController::GetStatePoseOffset(), GetStateVelOffset(), and RecordState().
GetStatePoseSize()
int cDeepMimicCharController::GetStatePoseSize () const protected virtual
Reimplemented in cCtController.
Definition at line 336 of file DeepMimicCharController.cpp.
 {
     return mChar->GetNumBodyParts() * mPosDim - 1; // -1 for root x
 }
References cSimCharacter::GetNumBodyParts(), cController::mChar, and mPosDim.
Referenced by BuildStatePose(), GetStateSize(), GetStateVelOffset(), and RecordState().
GetStateSize()
int cDeepMimicCharController::GetStateSize () const virtual
Reimplemented from cCharController.
Reimplemented in cCtController.
Definition at line 193 of file DeepMimicCharController.cpp.
 {
     int state_size = 0;
     state_size += GetStatePoseSize();
     state_size += GetStateVelSize();
     return state_size;
 }
References GetStatePoseSize(), and GetStateVelSize().
Referenced by cCtController::GetStateSize(), and RecordState().
GetStateVelOffset()
int cDeepMimicCharController::GetStateVelOffset () const protected virtual
Definition at line 331 of file DeepMimicCharController.cpp.
 {
     return GetStatePoseOffset() + GetStatePoseSize();
 }
References GetStatePoseOffset(), and GetStatePoseSize().
Referenced by RecordState().
GetStateVelSize()
int cDeepMimicCharController::GetStateVelSize () const protected virtual
Reimplemented in cCtController.
Definition at line 341 of file DeepMimicCharController.cpp.
 {
     return mChar->GetNumBodyParts() * mPosDim;
 }
References cSimCharacter::GetNumBodyParts(), cController::mChar, and mPosDim.
Referenced by BuildStateVel(), GetStateSize(), and RecordState().
GetTau()
const Eigen::VectorXd & cDeepMimicCharController::GetTau () const virtual
Definition at line 129 of file DeepMimicCharController.cpp.
 {
     return mTau;
 }
References mTau.
GetTime()
double cDeepMimicCharController::GetTime () const virtual
Definition at line 124 of file DeepMimicCharController.cpp.
 {
     return mTime;
 }
References mTime.
GetValLog()
const cCircularBuffer< double > & cDeepMimicCharController::GetValLog () const virtual
Definition at line 134 of file DeepMimicCharController.cpp.
 {
     return mValLog;
 }
References mValLog.
Referenced by cDrawSceneSimChar::DrawPoliInfo().
GetViewBound()
void cDeepMimicCharController::GetViewBound (tVector & out_min, tVector & out_max) const virtual
Definition at line 106 of file DeepMimicCharController.cpp.
 {
     tVector origin = mChar->GetRootPos();
     double max_len = mViewDistMax;
     out_min = origin - tVector(max_len, 0, max_len, 0);
     out_max = origin + tVector(max_len, 0, max_len, 0);
 }
References cSimCharacter::GetRootPos(), cController::mChar, and mViewDistMax.
Referenced by cSceneSimChar::GetViewBound().
GetViewDistMax()
double cDeepMimicCharController::GetViewDistMax () const virtual
Definition at line 101 of file DeepMimicCharController.cpp.
 {
     return mViewDistMax;
 }
References mViewDistMax.
GetViewDistMin()
double cDeepMimicCharController::GetViewDistMin () const virtual
Definition at line 96 of file DeepMimicCharController.cpp.
 {
     return mViewDistMin;
 }
References mViewDistMin.
HandleNewAction()
void cDeepMimicCharController::HandleNewAction () protected virtual
Definition at line 263 of file DeepMimicCharController.cpp.
 {
     mPrevActionTime = mTime;
     mPrevActionCOM = mChar->CalcCOM();
     mNeedNewAction = false;
 }
References cSimCharacter::CalcCOM(), cController::mChar, mNeedNewAction, mPrevActionCOM, mPrevActionTime, and mTime.
Referenced by UpdateCalcTau().
Init()
void cDeepMimicCharController::Init (cSimCharacter * character, const std::string & param_file) virtual
Definition at line 30 of file DeepMimicCharController.cpp.
 {
     cCharController::Init(character);
     LoadParams(param_file);
     ResetParams();
     mPosDim = GetPosDim();
     InitResources();
     mValid = true;
 }
References GetPosDim(), cController::Init(), InitResources(), cController::LoadParams(), mPosDim, cController::mValid, and ResetParams().
InitAction()
void cDeepMimicCharController::InitAction () protected virtual
Definition at line 238 of file DeepMimicCharController.cpp.
 {
     mAction = Eigen::VectorXd::Zero(GetActionSize());
 }
References cCharController::GetActionSize(), and mAction.
Referenced by InitResources().
InitResources()
void cDeepMimicCharController::InitResources () protected virtual
Definition at line 232 of file DeepMimicCharController.cpp.
 {
     InitAction();
     InitTau();
 }
References InitAction(), and InitTau().
Referenced by Init().
InitTau()
void cDeepMimicCharController::InitTau () protected virtual
Definition at line 243 of file DeepMimicCharController.cpp.
 {
     mTau = Eigen::VectorXd::Zero(mChar->GetNumDof());
 }
References cCharacter::GetNumDof(), cController::mChar, and mTau.
Referenced by InitResources().
LogVal()
void cDeepMimicCharController::LogVal (double val) virtual
Definition at line 139 of file DeepMimicCharController.cpp.
 {
     mValLog.Add(val);
 }
References cCircularBuffer< tVal, tAlloc >::Add(), and mValLog.
Referenced by cRLSceneSimChar::LogVal().
NeedNewAction()
bool cDeepMimicCharController::NeedNewAction () const virtual
Reimplemented from cCharController.
Definition at line 144 of file DeepMimicCharController.cpp.
 {
     return mNeedNewAction;
 }
References mNeedNewAction.
NewActionUpdate()
void cDeepMimicCharController::NewActionUpdate () protected virtual
Reimplemented in cCtController.
Definition at line 259 of file DeepMimicCharController.cpp.
 {
 }
Referenced by cCtController::NewActionUpdate(), PostUpdate(), and Reset().
ParseParams()
bool cDeepMimicCharController::ParseParams (const Json::Value & json) protected virtual
Reimplemented from cController.
Reimplemented in cCtController, and cCtPDController.
Definition at line 211 of file DeepMimicCharController.cpp.
 {
     bool succ = cCharController::ParseParams(json);
     mViewDistMin = json.get(gViewDistMinKey, mViewDistMin).asDouble();
     mViewDistMax = json.get(gViewDistMaxKey, mViewDistMax).asDouble();
     return succ;
 }
References Json::Value::asDouble(), Json::Value::get(), gViewDistMaxKey, gViewDistMinKey, mViewDistMax, mViewDistMin, and cController::ParseParams().
Referenced by cCtController::ParseParams().
PostProcessAction()
void cDeepMimicCharController::PostProcessAction (Eigen::VectorXd & out_action) const protected virtual
Definition at line 270 of file DeepMimicCharController.cpp.
 {
 }
Referenced by ApplyAction().
PostUpdate()
void cDeepMimicCharController::PostUpdate (double timestep) virtual
Reimplemented from cCharController.
Definition at line 62 of file DeepMimicCharController.cpp.
 {
     mNeedNewAction = CheckNeedNewAction(timestep);
     if (mNeedNewAction)
     {
         NewActionUpdate();
     }
 }
References CheckNeedNewAction(), mNeedNewAction, and NewActionUpdate().
RecordAction()
void cDeepMimicCharController::RecordAction (Eigen::VectorXd & out_action) const virtual
Reimplemented from cCharController.
Definition at line 188 of file DeepMimicCharController.cpp.
 {
     out_action = mAction;
 }
References mAction.
RecordGoal()
void cDeepMimicCharController::RecordGoal (Eigen::VectorXd & out_goal) const virtual
Reimplemented from cCharController.
Definition at line 177 of file DeepMimicCharController.cpp.
 {
     int goal_size = GetGoalSize();
     out_goal = std::numeric_limits<double>::quiet_NaN() * Eigen::VectorXd::Ones(goal_size);
 }
References cCharController::GetGoalSize().
RecordState()
void cDeepMimicCharController::RecordState (Eigen::VectorXd & out_state) virtual
Reimplemented from cCharController.
Reimplemented in cCtController.
Definition at line 156 of file DeepMimicCharController.cpp.
 {
     int state_size = GetStateSize();
     // fill with nans to make sure we don't forget to set anything
     out_state = std::numeric_limits<double>::quiet_NaN() * Eigen::VectorXd::Ones(state_size);
     Eigen::VectorXd ground;
     Eigen::VectorXd pose;
     Eigen::VectorXd vel;
     BuildStatePose(pose);
     BuildStateVel(vel);
     int pose_offset = GetStatePoseOffset();
     int pose_size = GetStatePoseSize();
     int vel_offset = GetStateVelOffset();
     int vel_size = GetStateVelSize();
     out_state.segment(pose_offset, pose_size) = pose;
     out_state.segment(vel_offset, vel_size) = vel;
 }
References BuildStatePose(), BuildStateVel(), GetStatePoseOffset(), GetStatePoseSize(), GetStateSize(), GetStateVelOffset(), and GetStateVelSize().
Referenced by cCtController::RecordState().
Reset()
void cDeepMimicCharController::Reset () virtual
Reimplemented from cController.
Reimplemented in cCtPDController.
Definition at line 42 of file DeepMimicCharController.cpp.
 {
     cCharController::Reset();
     ResetParams();
     NewActionUpdate();
 }
References NewActionUpdate(), cController::Reset(), and ResetParams().
Referenced by cCtPDController::Reset().
ResetParams()
void cDeepMimicCharController::ResetParams () protected virtual
Reimplemented in cCtController.
Definition at line 221 of file DeepMimicCharController.cpp.
 {
     mTime = 0;
     mNeedNewAction = true;
     mTau.setZero();
     mValLog.Clear();
     mPrevActionTime = mTime;
     mPrevActionCOM.setZero();
 }
References cCircularBuffer< tVal, tAlloc >::Clear(), mNeedNewAction, mPrevActionCOM, mPrevActionTime, mTau, mTime, and mValLog.
Referenced by Clear(), Init(), Reset(), and cCtController::ResetParams().
SetViewDistMax()
void cDeepMimicCharController::SetViewDistMax (double dist) virtual
Definition at line 91 of file DeepMimicCharController.cpp.
 {
     mViewDistMax = dist;
 }
References mViewDistMax.
Referenced by cCtController::cCtController(), and cDeepMimicCharController().
SetViewDistMin()
void cDeepMimicCharController::SetViewDistMin (double dist) virtual
Definition at line 86 of file DeepMimicCharController.cpp.
 {
     mViewDistMin = dist;
 }
References mViewDistMin.
Referenced by cDeepMimicCharController().
Update()
void cDeepMimicCharController::Update (double timestep) virtual
Reimplemented from cCharController.
Definition at line 55 of file DeepMimicCharController.cpp.
 {
     cCharController::Update(time_step);
     UpdateCalcTau(time_step, mTau);
     UpdateApplyTau(mTau);
 }
References mTau, cCharController::Update(), UpdateApplyTau(), and UpdateCalcTau().
UpdateApplyTau()
void cDeepMimicCharController::UpdateApplyTau (const Eigen::VectorXd & tau) virtual
Definition at line 80 of file DeepMimicCharController.cpp.
 {
     mTau = tau;
     mChar->ApplyControlForces(tau);
 }
References cSimCharacter::ApplyControlForces(), cController::mChar, and mTau.
Referenced by Update().
UpdateCalcTau()
void cDeepMimicCharController::UpdateCalcTau (double timestep, Eigen::VectorXd & out_tau) virtual
Reimplemented in cCtController.
Definition at line 71 of file DeepMimicCharController.cpp.
 {
     mTime += timestep;
     if (mNeedNewAction)
     {
         HandleNewAction();
     }
 }
References HandleNewAction(), mNeedNewAction, and mTime.
Referenced by Update(), and cCtController::UpdateCalcTau().
Member Data Documentation
mAction
Eigen::VectorXd cDeepMimicCharController::mAction protected
Definition at line 52 of file DeepMimicCharController.h.
Referenced by cCtVelController::ApplyAction(), ApplyAction(), cCtController::GetPhaseRate(), InitAction(), RecordAction(), and cCtController::UpdateBuildTau().
mNeedNewAction
bool cDeepMimicCharController::mNeedNewAction protected
Definition at line 51 of file DeepMimicCharController.h.
Referenced by HandleNewAction(), NeedNewAction(), PostUpdate(), ResetParams(), and UpdateCalcTau().
mPosDim
int cDeepMimicCharController::mPosDim protected
Definition at line 57 of file DeepMimicCharController.h.
Referenced by BuildStatePose(), BuildStateVel(), cDeepMimicCharController(), GetStatePoseSize(), GetStateVelSize(), and Init().
mPrevActionCOM
tVector cDeepMimicCharController::mPrevActionCOM protected
Definition at line 60 of file DeepMimicCharController.h.
Referenced by cDeepMimicCharController(), GetPrevActionCOM(), HandleNewAction(), and ResetParams().
mPrevActionTime
double cDeepMimicCharController::mPrevActionTime protected
Definition at line 59 of file DeepMimicCharController.h.
Referenced by cDeepMimicCharController(), GetPrevActionTime(), HandleNewAction(), ResetParams(), and cCtController::SetInitTime().
mTau
Eigen::VectorXd cDeepMimicCharController::mTau protected
Definition at line 53 of file DeepMimicCharController.h.
Referenced by GetTau(), InitTau(), ResetParams(), Update(), and UpdateApplyTau().
mTime
double cDeepMimicCharController::mTime protected
Definition at line 50 of file DeepMimicCharController.h.
Referenced by cDeepMimicCharController(), cCtController::CheckNeedNewAction(), cCtController::GetPhase(), GetTime(), HandleNewAction(), ResetParams(), cCtController::SetInitTime(), cCtController::UpdateCalcTau(), and UpdateCalcTau().
mValLog
cCircularBuffer<double> cDeepMimicCharController::mValLog protected
Definition at line 63 of file DeepMimicCharController.h.
Referenced by cDeepMimicCharController(), GetValLog(), LogVal(), and ResetParams().
mViewDistMax
double cDeepMimicCharController::mViewDistMax protected
Definition at line 56 of file DeepMimicCharController.h.
Referenced by GetViewBound(), GetViewDistMax(), ParseParams(), and SetViewDistMax().
mViewDistMin
double cDeepMimicCharController::mViewDistMin protected
Definition at line 55 of file DeepMimicCharController.h.
Referenced by GetViewDistMin(), ParseParams(), and SetViewDistMin().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/DeepMimicCharController.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/DeepMimicCharController.cpp