My Project: cRLSceneSimChar Class Reference
cRLSceneSimChar Class Reference abstract
#include <RLSceneSimChar.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cRLSceneSimChar ()
virtual ~cRLSceneSimChar ()
virtual void ParseArgs (const std::shared_ptr< cArgParser > &parser)
virtual void Init ()
virtual void Clear ()
virtual int GetNumAgents () const
virtual bool NeedNewAction (int agent_id) const
virtual void RecordState (int agent_id, Eigen::VectorXd &out_state) const
virtual void RecordGoal (int agent_id, Eigen::VectorXd &out_goal) const
virtual void SetAction (int agent_id, const Eigen::VectorXd &action)
virtual eActionSpace GetActionSpace (int agent_id) const
virtual int GetStateSize (int agent_id) const
virtual int GetGoalSize (int agent_id) const
virtual int GetActionSize (int agent_id) const
virtual int GetNumActions (int agent_id) const
virtual void BuildStateOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildGoalOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionBounds (int agent_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max) const
virtual void BuildStateNormGroups (int agent_id, Eigen::VectorXi &out_groups) const
virtual void BuildGoalNormGroups (int agent_id, Eigen::VectorXi &out_groups) const
virtual double CalcReward (int agent_id) const =0
virtual double GetRewardMin (int agent_id) const
virtual double GetRewardMax (int agent_id) const
virtual eTerminate CheckTerminate (int agent_id) const
virtual bool CheckValidEpisode () const
virtual void LogVal (int agent_id, double val)
virtual void SetSampleCount (int count)
virtual std::string GetName () const
Public Member Functions inherited from cRLScene
virtual ~cRLScene ()
virtual double GetRewardFail (int agent_id)
virtual double GetRewardSucc (int agent_id)
virtual bool IsEpisodeEnd () const
virtual void SetMode (eMode mode)
Public Member Functions inherited from cScene
virtual ~cScene ()
virtual void Reset ()
virtual void Draw ()
virtual void Keyboard (unsigned char key, double device_x, double device_y)
virtual void MouseClick (int button, int state, double device_x, double device_y)
virtual void MouseMove (double device_x, double device_y)
virtual void Reshape (int w, int h)
virtual void Shutdown ()
virtual bool IsDone () const
virtual double GetTime () const
virtual bool HasRandSeed () const
virtual unsigned long GetRandSeed () const
Public Member Functions inherited from cSceneSimChar
cSceneSimChar ()
virtual ~cSceneSimChar ()
virtual void Update (double time_elapsed)
virtual int GetNumChars () const
virtual const std::shared_ptr< cSimCharacter > & GetCharacter () const
virtual const std::shared_ptr< cSimCharacter > & GetCharacter (int char_id) const
virtual const std::shared_ptr< cWorld > & GetWorld () const
virtual tVector GetCharPos () const
virtual const std::shared_ptr< cGround > & GetGround () const
virtual const tVector & GetGravity () const
virtual bool LoadControlParams (const std::string &param_file, const std::shared_ptr< cSimCharacter > &out_char)
virtual void AddPerturb (const tPerturb &perturb)
virtual void ApplyRandForce (double min_force, double max_force, double min_dur, double max_dur, cSimObj *obj)
virtual void ApplyRandForce ()
virtual void ApplyRandForce (int char_id)
virtual void RayTest (const tVector &beg, const tVector &end, cWorld::tRayTestResult &out_result) const
virtual void SetGroundParamBlend (double lerp)
virtual int GetNumParamSets () const
virtual void OutputCharState (const std::string &out_file) const
virtual void OutputGround (const std::string &out_file) const
virtual void ResolveCharGroundIntersect ()
virtual void SpawnProjectile ()
virtual void SpawnBigProjectile ()
virtual int GetNumObjs () const
virtual const std::shared_ptr< cSimRigidBody > & GetObj (int id) const
virtual const tObjEntry & GetObjEntry (int id) const
virtual void SetRandSeed (unsigned long seed)
Protected Member Functions
virtual void ResetParams ()
virtual void ResetScene ()
virtual const std::shared_ptr< cCharController > & GetController () const
virtual const std::shared_ptr< cCharController > & GetController (int agent_id) const
virtual const cSimCharacter * GetAgentChar (int agent_id) const
virtual void PreUpdate (double timestep)
virtual void ResetTimers ()
virtual void NewActionUpdate (int agent_id)
virtual bool EnableFallEnd () const
virtual void RegisterAgents ()
virtual void RegisterAgent (const std::shared_ptr< cCharController > &ctrl, const std::shared_ptr< cSimCharacter > &character)
virtual void RegisterAgent (const std::shared_ptr< cCharController > &ctrl, const std::shared_ptr< cSimCharacter > &character, std::vector< int > &out_ids)
virtual void SetupTimerAnnealer (cAnnealer &out_annealer) const
virtual void UpdateTimerParams ()
Protected Member Functions inherited from cRLScene
cRLScene ()
Protected Member Functions inherited from cScene
cScene ()
virtual void InitTimers ()
virtual void UpdateTimers (double timestep)
Protected Member Functions inherited from cSceneSimChar
virtual bool ParseCharTypes (const std::shared_ptr< cArgParser > &parser, std::vector< cSimCharBuilder::eCharType > &out_types) const
virtual bool ParseCharParams (const std::shared_ptr< cArgParser > &parser, std::vector< cSimCharacter::tParams > &out_params) const
virtual bool ParseCharCtrlParams (const std::shared_ptr< cArgParser > &parser, std::vector< cCtrlBuilder::tCtrlParams > &out_params) const
virtual void BuildWorld ()
virtual bool BuildCharacters ()
virtual void BuildGround ()
virtual bool BuildController (const cCtrlBuilder::tCtrlParams &ctrl_params, std::shared_ptr< cCharController > &out_ctrl)
virtual void SetFallContacts (const std::vector< int > &fall_bodies, cSimCharacter &out_char) const
virtual void InitCharacterPos ()
virtual void InitCharacterPos (const std::shared_ptr< cSimCharacter > &out_char)
virtual void InitCharacterPosFixed (const std::shared_ptr< cSimCharacter > &out_char)
virtual void SetCharRandPlacement (const std::shared_ptr< cSimCharacter > &out_char)
virtual void CalcCharRandPlacement (const std::shared_ptr< cSimCharacter > &out_char, tVector &out_pos, tQuaternion &out_rot)
virtual void ResolveCharGroundIntersect (const std::shared_ptr< cSimCharacter > &out_char) const
virtual void UpdateWorld (double time_step)
virtual void UpdateCharacters (double time_step)
virtual void PostUpdateCharacters (double time_step)
virtual void UpdateGround (double time_elapsed)
virtual void UpdateRandPerturb (double time_step)
virtual void ResetCharacters ()
virtual void ResetWorld ()
virtual void ResetGround ()
virtual void PostUpdate (double timestep)
virtual int GetRandPerturbPartID (const std::shared_ptr< cSimCharacter > &character)
virtual void GetViewBound (tVector &out_min, tVector &out_max) const
virtual void ParseGroundParams (const std::shared_ptr< cArgParser > &parser, cGround::tParams &out_params) const
virtual void UpdateObjs (double timestep)
virtual void UpdateJoints (double timestep)
virtual void ClearJointForces ()
virtual void ClearObjs ()
virtual void CleanObjs ()
virtual int AddObj (const tObjEntry &obj_entry)
virtual void RemoveObj (int handle)
virtual void ClearJoints ()
virtual int AddJoint (const tJointEntry &joint_entry)
virtual void RemoveJoint (int handle)
virtual int GetNumJoints () const
virtual bool HasFallen (const cSimCharacter &sim_char) const
virtual void SpawnProjectile (double density, double min_size, double max_size, double min_speed, double max_speed, double y_offset, double life_time)
virtual void ResetRandPertrub ()
Protected Attributes
bool mEnableFallEnd
cAgentRegistry mAgentReg
cTimer::tParams mTimerParamsEnd
cAnnealer mTimerAnnealer
int mAnnealSamples
Protected Attributes inherited from cRLScene
eMode mMode
int mSampleCount
Protected Attributes inherited from cScene
cRand mRand
bool mHasRandSeed
unsigned long mRandSeed
std::shared_ptr< cArgParser > mArgParser
cTimer::tParams mTimerParams
cTimer mTimer
Protected Attributes inherited from cSceneSimChar
cWorld::tParams mWorldParams
std::vector< cSimCharacter::tParams > mCharParams
std::vector< cCtrlBuilder::tCtrlParams > mCtrlParams
bool mEnableContactFall
bool mEnableRandCharPlacement
std::vector< int > mFallContactBodies
std::shared_ptr< cWorld > mWorld
std::shared_ptr< cGround > mGround
std::vector< std::shared_ptr< cSimCharacter > > mChars
std::vector< cSimCharBuilder::eCharType > mCharTypes
cGround::tParams mGroundParams
tPerturbParams mPerturbParams
cIndexBuffer< tObjEntry, Eigen::aligned_allocator< tObjEntry > > mObjs
cIndexBuffer< tJointEntry > mJoints
Additional Inherited Members
Public Types inherited from cRLScene
enum eMode { eModeTrain, eModeTest, eModeMax }
enum eTerminate { eTerminateNull, eTerminateFail, eTerminateSucc, eTerminateMax }
Static Protected Attributes inherited from cSceneSimChar
static const double gGroundSpawnOffset = -1
Detailed Description
Definition at line 8 of file RLSceneSimChar.h.
Constructor & Destructor Documentation
cRLSceneSimChar()
cRLSceneSimChar::cRLSceneSimChar ()
Definition at line 3 of file RLSceneSimChar.cpp.
 {
     mEnableFallEnd = true;
     mAnnealSamples = gInvalidIdx;
 }
References gInvalidIdx, mAnnealSamples, and mEnableFallEnd.
~cRLSceneSimChar()
cRLSceneSimChar::~cRLSceneSimChar () virtual
Definition at line 9 of file RLSceneSimChar.cpp.
 {
 }
Member Function Documentation
BuildActionBounds()
void cRLSceneSimChar::BuildActionBounds (int agent_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) const virtual
Implements cRLScene.
Definition at line 124 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     ctrl->BuildActionBounds(out_min, out_max);
 }
References GetController().
BuildActionOffsetScale()
void cRLSceneSimChar::BuildActionOffsetScale (int agent_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const virtual
Implements cRLScene.
Definition at line 118 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     ctrl->BuildActionOffsetScale(out_offset, out_scale);
 }
References GetController().
BuildGoalNormGroups()
void cRLSceneSimChar::BuildGoalNormGroups (int agent_id, Eigen::VectorXi & out_groups) const virtual
Implements cRLScene.
Definition at line 136 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     ctrl->BuildGoalNormGroups(out_groups);
 }
References GetController().
BuildGoalOffsetScale()
void cRLSceneSimChar::BuildGoalOffsetScale (int agent_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const virtual
Implements cRLScene.
Definition at line 112 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     ctrl->BuildGoalOffsetScale(out_offset, out_scale);
 }
References GetController().
BuildStateNormGroups()
void cRLSceneSimChar::BuildStateNormGroups (int agent_id, Eigen::VectorXi & out_groups) const virtual
Implements cRLScene.
Definition at line 130 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     ctrl->BuildStateNormGroups(out_groups);
 }
References GetController().
BuildStateOffsetScale()
void cRLSceneSimChar::BuildStateOffsetScale (int agent_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const virtual
Implements cRLScene.
Definition at line 106 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     ctrl->BuildStateOffsetScale(out_offset, out_scale);
 }
References GetController().
CalcReward()
virtual double cRLSceneSimChar::CalcReward (int agent_id) const pure virtual
Implements cRLScene.
Implemented in cSceneImitate.
CheckTerminate()
cRLSceneSimChar::eTerminate cRLSceneSimChar::CheckTerminate (int agent_id) const virtual
Reimplemented from cRLScene.
Reimplemented in cSceneImitate.
Definition at line 152 of file RLSceneSimChar.cpp.
 {
     bool fail = false;
     if (EnableFallEnd())
     {
         const auto& character = GetAgentChar(agent_id);
         fail |= HasFallen(*character);
     }
     eTerminate terminated = (fail) ? eTerminateFail : eTerminateNull;
     return terminated;
 }
References EnableFallEnd(), cRLScene::eTerminateFail, cRLScene::eTerminateNull, GetAgentChar(), and cSceneSimChar::HasFallen().
Referenced by cSceneImitate::CheckTerminate().
CheckValidEpisode()
bool cRLSceneSimChar::CheckValidEpisode () const virtual
Reimplemented from cScene.
Definition at line 164 of file RLSceneSimChar.cpp.
 {
     for (int i = 0; i < GetNumChars(); ++i)
     {
         const auto& sim_char = GetCharacter(i);
         bool exp = sim_char->HasVelExploded();
         if (exp)
         {
             return false;
         }
     }
     return true;
 }
References cSceneSimChar::GetCharacter(), and cSceneSimChar::GetNumChars().
Clear()
void cRLSceneSimChar::Clear () virtual
Reimplemented from cRLScene.
Definition at line 39 of file RLSceneSimChar.cpp.
 {
     cRLScene::Clear();
     cSceneSimChar::Clear();
     mAgentReg.Clear();
 }
References cAgentRegistry::Clear(), cRLScene::Clear(), cSceneSimChar::Clear(), and mAgentReg.
EnableFallEnd()
bool cRLSceneSimChar::EnableFallEnd () const protected virtual
Definition at line 255 of file RLSceneSimChar.cpp.
 {
     return mEnableFallEnd;
 }
References mEnableFallEnd.
Referenced by CheckTerminate().
GetActionSize()
int cRLSceneSimChar::GetActionSize (int agent_id) const virtual
Implements cRLScene.
Definition at line 94 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     return ctrl->GetActionSize();
 }
References GetController().
GetActionSpace()
eActionSpace cRLSceneSimChar::GetActionSpace (int agent_id) const virtual
Implements cRLScene.
Definition at line 76 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     return ctrl->GetActionSpace();
 }
References GetController().
GetAgentChar()
const cSimCharacter * cRLSceneSimChar::GetAgentChar (int agent_id) const protected virtual
Definition at line 222 of file RLSceneSimChar.cpp.
 {
     return mAgentReg.GetChar(agent_id);
 }
References cAgentRegistry::GetChar(), and mAgentReg.
Referenced by cSceneImitate::CalcReward(), and CheckTerminate().
GetController() [1/2]
const std::shared_ptr< cCharController > & cRLSceneSimChar::GetController () const protected virtual
Definition at line 211 of file RLSceneSimChar.cpp.
 {
     const auto& character = GetCharacter();
     return character->GetController();
 }
References cSceneSimChar::GetCharacter().
Referenced by BuildActionBounds(), BuildActionOffsetScale(), BuildGoalNormGroups(), BuildGoalOffsetScale(), BuildStateNormGroups(), BuildStateOffsetScale(), GetActionSize(), GetActionSpace(), GetGoalSize(), GetNumActions(), GetStateSize(), LogVal(), NeedNewAction(), RecordGoal(), RecordState(), and SetAction().
GetController() [2/2]
const std::shared_ptr< cCharController > & cRLSceneSimChar::GetController (int agent_id) const protected virtual
Definition at line 217 of file RLSceneSimChar.cpp.
 {
     return mAgentReg.GetAgent(agent_id);
 }
References cAgentRegistry::GetAgent(), and mAgentReg.
GetGoalSize()
int cRLSceneSimChar::GetGoalSize (int agent_id) const virtual
Implements cRLScene.
Definition at line 88 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     return ctrl->GetGoalSize();
 }
References GetController().
GetName()
std::string cRLSceneSimChar::GetName () const virtual
Reimplemented from cSceneSimChar.
Reimplemented in cSceneImitate.
Definition at line 194 of file RLSceneSimChar.cpp.
 {
     return "RL Sim Character";
 }
GetNumActions()
int cRLSceneSimChar::GetNumActions (int agent_id) const virtual
Implements cRLScene.
Definition at line 100 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     return ctrl->GetNumActions();
 }
References GetController().
GetNumAgents()
int cRLSceneSimChar::GetNumAgents () const virtual
Implements cRLScene.
Definition at line 47 of file RLSceneSimChar.cpp.
 {
     return mAgentReg.GetNumAgents();
 }
References cAgentRegistry::GetNumAgents(), and mAgentReg.
Referenced by PreUpdate().
GetRewardMax()
double cRLSceneSimChar::GetRewardMax (int agent_id) const virtual
Implements cRLScene.
Definition at line 147 of file RLSceneSimChar.cpp.
 {
     return mAgentReg.GetAgent(agent_id)->GetRewardMax();
 }
References cAgentRegistry::GetAgent(), and mAgentReg.
GetRewardMin()
double cRLSceneSimChar::GetRewardMin (int agent_id) const virtual
Implements cRLScene.
Definition at line 142 of file RLSceneSimChar.cpp.
 {
     return mAgentReg.GetAgent(agent_id)->GetRewardMin();
 }
References cAgentRegistry::GetAgent(), and mAgentReg.
GetStateSize()
int cRLSceneSimChar::GetStateSize (int agent_id) const virtual
Implements cRLScene.
Definition at line 82 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     return ctrl->GetStateSize();
 }
References GetController().
Init()
void cRLSceneSimChar::Init () virtual
Reimplemented from cRLScene.
Reimplemented in cSceneImitate.
Definition at line 27 of file RLSceneSimChar.cpp.
 {
     cRLScene::Init();
     cSceneSimChar::Init();
     mAgentReg.Clear();
     RegisterAgents();
     mAgentReg.PrintInfo();
     SetupTimerAnnealer(mTimerAnnealer);
 }
References cAgentRegistry::Clear(), cRLScene::Init(), cSceneSimChar::Init(), mAgentReg, mTimerAnnealer, cAgentRegistry::PrintInfo(), RegisterAgents(), and SetupTimerAnnealer().
Referenced by cSceneImitate::Init().
LogVal()
void cRLSceneSimChar::LogVal (int agent_id, double val) virtual
Implements cRLScene.
Definition at line 178 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     cDeepMimicCharController* trl_ctrl = dynamic_cast<cDeepMimicCharController*>(ctrl.get());
     if (trl_ctrl != nullptr)
     {
         trl_ctrl->LogVal(val);
     }
 }
References GetController(), and cDeepMimicCharController::LogVal().
NeedNewAction()
bool cRLSceneSimChar::NeedNewAction (int agent_id) const virtual
Implements cRLScene.
Definition at line 52 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     return ctrl->NeedNewAction();
 }
References GetController().
NewActionUpdate()
void cRLSceneSimChar::NewActionUpdate (int agent_id) protected virtual
Definition at line 251 of file RLSceneSimChar.cpp.
 {
 }
Referenced by PreUpdate().
ParseArgs()
void cRLSceneSimChar::ParseArgs (const std::shared_ptr< cArgParser > & parser) virtual
Reimplemented from cSceneSimChar.
Reimplemented in cSceneImitate.
Definition at line 13 of file RLSceneSimChar.cpp.
 {
     cRLScene::ParseArgs(parser);
     cSceneSimChar::ParseArgs(parser);
     parser->ParseBool("enable_fall_end", mEnableFallEnd);
     parser->ParseInt("anneal_samples", mAnnealSamples);
     mTimerParamsEnd = mTimerParams;
     mArgParser->ParseDouble("time_end_lim_min", mTimerParamsEnd.mTimeMin);
     mArgParser->ParseDouble("time_end_lim_max", mTimerParamsEnd.mTimeMax);
     mArgParser->ParseDouble("time_end_lim_exp", mTimerParamsEnd.mTimeExp);
 }
References mAnnealSamples, cScene::mArgParser, mEnableFallEnd, cTimer::tParams::mTimeExp, cTimer::tParams::mTimeMax, cTimer::tParams::mTimeMin, cScene::mTimerParams, mTimerParamsEnd, cScene::ParseArgs(), and cSceneSimChar::ParseArgs().
Referenced by cSceneImitate::ParseArgs().
PreUpdate()
void cRLSceneSimChar::PreUpdate (double timestep) protected virtual
Reimplemented from cSceneSimChar.
Definition at line 227 of file RLSceneSimChar.cpp.
 {
     cSceneSimChar::PreUpdate(timestep);
     for (int a = 0; a < GetNumAgents(); ++a)
     {
         const auto& ctrl = mAgentReg.GetAgent(a);
         bool new_action = ctrl->NeedNewAction();
         if (new_action)
         {
             NewActionUpdate(a);
         }
     }
 }
References cAgentRegistry::GetAgent(), GetNumAgents(), mAgentReg, NewActionUpdate(), and cSceneSimChar::PreUpdate().
RecordGoal()
void cRLSceneSimChar::RecordGoal (int agent_id, Eigen::VectorXd & out_goal) const virtual
Implements cRLScene.
Definition at line 64 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     ctrl->RecordGoal(out_goal);
 }
References GetController().
RecordState()
void cRLSceneSimChar::RecordState (int agent_id, Eigen::VectorXd & out_state) const virtual
Implements cRLScene.
Definition at line 58 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     ctrl->RecordState(out_state);
 }
References GetController().
RegisterAgent() [1/2]
void cRLSceneSimChar::RegisterAgent (const std::shared_ptr< cCharController > & ctrl, const std::shared_ptr< cSimCharacter > & character) protected virtual
Definition at line 271 of file RLSceneSimChar.cpp.
 {
     std::vector<int> ids;
     RegisterAgent(ctrl, character, ids);
 }
Referenced by RegisterAgent(), and RegisterAgents().
RegisterAgent() [2/2]
void cRLSceneSimChar::RegisterAgent (const std::shared_ptr< cCharController > & ctrl, const std::shared_ptr< cSimCharacter > & character, std::vector< int > & out_ids) protected virtual
Definition at line 277 of file RLSceneSimChar.cpp.
 {
     if (ctrl != nullptr)
     {
         int id = mAgentReg.AddAgent(ctrl, character.get());
         out_ids.push_back(id);
         int num_ctrls = ctrl->NumChildren();
         for (int i = 0; i < num_ctrls; ++i)
         {
             const auto& child_ctrl = ctrl->GetChild(i);
             RegisterAgent(child_ctrl, character, out_ids);
         }
     }
 }
References cAgentRegistry::AddAgent(), mAgentReg, and RegisterAgent().
RegisterAgents()
void cRLSceneSimChar::RegisterAgents () protected virtual
Definition at line 260 of file RLSceneSimChar.cpp.
 {
     int num_chars = GetNumChars();
     for (int i = 0; i < num_chars; ++i)
     {
         const auto& character = GetCharacter(i);
         const auto& ctrl = character->GetController();
         RegisterAgent(ctrl, character);
     }
 }
References cSceneSimChar::GetCharacter(), cSceneSimChar::GetNumChars(), and RegisterAgent().
Referenced by Init().
ResetParams()
void cRLSceneSimChar::ResetParams () protected virtual
Reimplemented from cScene.
Definition at line 199 of file RLSceneSimChar.cpp.
 {
     cRLScene::ResetParams();
     cSceneSimChar::ResetParams();
 }
References cScene::ResetParams().
ResetScene()
void cRLSceneSimChar::ResetScene () protected virtual
Reimplemented from cSceneSimChar.
Definition at line 205 of file RLSceneSimChar.cpp.
 {
     cRLScene::ResetScene();
     cSceneSimChar::ResetScene();
 }
References cScene::ResetScene(), and cSceneSimChar::ResetScene().
ResetTimers()
void cRLSceneSimChar::ResetTimers () protected virtual
Reimplemented from cScene.
Definition at line 242 of file RLSceneSimChar.cpp.
 {
     cSceneSimChar::ResetTimers();
     if (mMode == eModeTest)
     {
         mTimer.SetMaxTime(mTimerParamsEnd.mTimeMax);
     }
 }
References cRLScene::eModeTest, cRLScene::mMode, cTimer::tParams::mTimeMax, cScene::mTimer, mTimerParamsEnd, cScene::ResetTimers(), and cTimer::SetMaxTime().
SetAction()
void cRLSceneSimChar::SetAction (int agent_id, const Eigen::VectorXd & action) virtual
Implements cRLScene.
Definition at line 70 of file RLSceneSimChar.cpp.
 {
     const auto& ctrl = GetController(agent_id);
     ctrl->ApplyAction(action);
 }
References GetController().
SetSampleCount()
void cRLSceneSimChar::SetSampleCount (int count) virtual
Reimplemented from cRLScene.
Definition at line 188 of file RLSceneSimChar.cpp.
 {
     cRLScene::SetSampleCount(count);
     UpdateTimerParams();
 }
References cRLScene::SetSampleCount(), and UpdateTimerParams().
SetupTimerAnnealer()
void cRLSceneSimChar::SetupTimerAnnealer (cAnnealer & out_annealer) const protected virtual
Definition at line 295 of file RLSceneSimChar.cpp.
 {
     cAnnealer::tParams params;
     params.mType = cAnnealer::eTypePow;
     params.mPow = 4.0;
     out_annealer.Init(params);
 }
References cAnnealer::eTypePow, cAnnealer::Init(), cAnnealer::tParams::mPow, and cAnnealer::tParams::mType.
Referenced by Init().
UpdateTimerParams()
void cRLSceneSimChar::UpdateTimerParams () protected virtual
Definition at line 303 of file RLSceneSimChar.cpp.
 {
     if (mAnnealSamples > 0)
     {
         double t = static_cast<double>(mSampleCount) / mAnnealSamples;
         double lerp = mTimerAnnealer.Eval(t);
         cTimer::tParams blend_params = mTimerParams.Blend(mTimerParamsEnd, lerp);
         mTimer.SetParams(blend_params);
     }
 }
References cTimer::tParams::Blend(), cAnnealer::Eval(), mAnnealSamples, cRLScene::mSampleCount, cScene::mTimer, mTimerAnnealer, cScene::mTimerParams, mTimerParamsEnd, and cTimer::SetParams().
Referenced by SetSampleCount().
Member Data Documentation
mAgentReg
cAgentRegistry cRLSceneSimChar::mAgentReg protected
Definition at line 54 of file RLSceneSimChar.h.
Referenced by Clear(), GetAgentChar(), GetController(), GetNumAgents(), GetRewardMax(), GetRewardMin(), Init(), PreUpdate(), and RegisterAgent().
mAnnealSamples
int cRLSceneSimChar::mAnnealSamples protected
Definition at line 57 of file RLSceneSimChar.h.
Referenced by cRLSceneSimChar(), ParseArgs(), and UpdateTimerParams().
mEnableFallEnd
bool cRLSceneSimChar::mEnableFallEnd protected
Definition at line 53 of file RLSceneSimChar.h.
Referenced by cRLSceneSimChar(), EnableFallEnd(), and ParseArgs().
mTimerAnnealer
cAnnealer cRLSceneSimChar::mTimerAnnealer protected
Definition at line 56 of file RLSceneSimChar.h.
Referenced by Init(), and UpdateTimerParams().
mTimerParamsEnd
cTimer::tParams cRLSceneSimChar::mTimerParamsEnd protected
Definition at line 55 of file RLSceneSimChar.h.
Referenced by ParseArgs(), ResetTimers(), and UpdateTimerParams().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/RLSceneSimChar.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/RLSceneSimChar.cpp