My Project: cTextureDesc Class Reference
cTextureDesc Class Reference
#include <TextureDesc.h>
Classes
struct tTexEntry
Public Member Functions
cTextureDesc (int width, int height, int channels, GLenum format, GLenum type, bool mipmaps)
cTextureDesc (int width, int height, int depth, int channels, GLenum format, GLenum type, bool mipmaps)
cTextureDesc (GLuint obj, GLuint tex, GLuint ds, int width, int height, int depth, int channels, GLenum format)
cTextureDesc (const std::string &filename, bool gen_mips=false)
virtual ~cTextureDesc ()
virtual void BindBuffer () const
virtual void UnbindBuffer () const
virtual bool CheckBoundBuffer () const
virtual void BindBuffer3DSlice (int slice) const
virtual void BindTex (GLint tex_slot) const
virtual void UnbindTex (GLint tex_slot) const
virtual GLuint GetObj () const
virtual GLuint GetTexture () const
virtual GLuint GetDepthStencil () const
virtual bool IsValid () const
virtual bool IsRenderBuffer () const
virtual int GetWidth () const
virtual int GetHeight () const
virtual int GetNumTexels () const
virtual int GetNumChannels () const
virtual void Reshape (int w, int h)
virtual void ReadPixels (std::vector< GLfloat > &out_data, GLenum format=GL_RGBA)
virtual void WritePixels (const std::vector< GLubyte > &data)
Protected Member Functions
cTextureDesc ()
virtual void PushTextureStack () const
virtual void PopTextureStack () const
Protected Attributes
int mWidth
int mHeight
int mDepth
int mChannels
GLenum mFormat
GLenum mType
bool mHasMips
GLuint mObject
GLuint mTexture
GLuint mDepthStencil
Static Protected Attributes
static const int gNumViewportParams = 4
static std::stack< tTexEntry > gTexStack = std::stack<cTextureDesc::tTexEntry>()
Detailed Description
Definition at line 10 of file TextureDesc.h.
Constructor & Destructor Documentation
cTextureDesc() [1/5]
cTextureDesc::cTextureDesc (int width, int height, int channels, GLenum format, GLenum type, bool mipmaps)
Definition at line 30 of file TextureDesc.cpp.
     : mWidth( width ),
         mHeight( height ),
         mDepth(1),
         mChannels( channels ),
         mFormat( format ),
         mType( type ),
         mHasMips( mipmaps )
 {
     cTextureUtil::CreateFrameBuffer(mObject, mTexture, mDepthStencil, mWidth, mHeight, mDepth,
                                     mChannels, mFormat, mType, mHasMips);
 }
References cTextureUtil::CreateFrameBuffer(), mChannels, mDepth, mDepthStencil, mFormat, mHasMips, mHeight, mObject, mTexture, mType, and mWidth.
cTextureDesc() [2/5]
cTextureDesc::cTextureDesc (int width, int height, int depth, int channels, GLenum format, GLenum type, bool mipmaps)
Definition at line 44 of file TextureDesc.cpp.
     : mWidth( width ),
       mHeight( height ),
       mDepth(depth),
       mChannels( channels ),
       mFormat( format ),
       mType( type ),
       mHasMips( mipmaps )
 {
     cTextureUtil::CreateFrameBuffer(mObject, mTexture, mDepthStencil, mWidth, mHeight, mDepth,
                                     mChannels, mFormat, mType, mHasMips);
 }
References cTextureUtil::CreateFrameBuffer(), mChannels, mDepth, mDepthStencil, mFormat, mHasMips, mHeight, mObject, mTexture, mType, and mWidth.
cTextureDesc() [3/5]
cTextureDesc::cTextureDesc (GLuint obj, GLuint tex, GLuint ds, int width, int height, int depth, int channels, GLenum format)
Definition at line 58 of file TextureDesc.cpp.
     : mWidth( width ),
       mHeight( height ),
       mDepth(depth),
       mChannels( channels ),
       mFormat( format ),
       mObject( obj ),
       mTexture( tex ),
       mDepthStencil( ds )
 {
 }
cTextureDesc() [4/5]
cTextureDesc::cTextureDesc (const std::string & filename, bool gen_mips = false)
Definition at line 71 of file TextureDesc.cpp.
                                                                    : cTextureDesc()
 {
     std::vector<unsigned char> image;
     unsigned width, height;
     unsigned error = lodepng::decode(image, width, height, filename);
     if (error == 0)
     {
         mWidth = width;
         mHeight = height;
         mDepth = 1;
         mChannels = GL_RGBA8;
         mType = GL_UNSIGNED_BYTE;
         mFormat = GL_RGBA;
         mHasMips = true;
         int num_mipmaps = (gen_mips) ? static_cast<int>(log2(std::min(mWidth, mHeight))) : 1;
         glGenTextures(1, &mTexture);
         glBindTexture(GL_TEXTURE_2D, mTexture);
         glTexStorage2D(GL_TEXTURE_2D, num_mipmaps, mChannels, mWidth, mHeight);
         glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, mWidth, mHeight, mFormat, mType, image.data());
         if (gen_mips)
         {
             glGenerateMipmap(GL_TEXTURE_2D);
             GLfloat max_aniso = 1.f;
             glGetFloatv(GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT, &max_aniso);
             glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAX_ANISOTROPY_EXT, max_aniso);
             glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
             glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
         }
         else
         {
             glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST_MIPMAP_NEAREST);
             glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST_MIPMAP_NEAREST);
         }
         glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
         glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
         glBindTexture(GL_TEXTURE_2D, 0);
     }
 }
References mChannels, mDepth, mFormat, mHasMips, mHeight, mTexture, mType, and mWidth.
~cTextureDesc()
cTextureDesc::~cTextureDesc () virtual
Definition at line 239 of file TextureDesc.cpp.
 {
     cTextureUtil::DeleteFrameBuffer( mObject, mTexture, mDepthStencil );
 }
References cTextureUtil::DeleteFrameBuffer(), mDepthStencil, mObject, and mTexture.
cTextureDesc() [5/5]
cTextureDesc::cTextureDesc () protected
Definition at line 16 of file TextureDesc.cpp.
 {
     mWidth = 0;
     mHeight = 0;
     mDepth = 0;
     mChannels = GL_RGBA8;
     mType = GL_UNSIGNED_BYTE;
     mFormat = GL_RGBA;
     mHasMips = false;
     mObject = -1;
     mTexture = -1;
     mDepthStencil = -1;
 }
References mChannels, mDepth, mDepthStencil, mFormat, mHasMips, mHeight, mObject, mTexture, mType, and mWidth.
Member Function Documentation
BindBuffer()
void cTextureDesc::BindBuffer () const virtual
Definition at line 116 of file TextureDesc.cpp.
 {
     if (IsRenderBuffer())
     {
         glBindFramebuffer(GL_FRAMEBUFFER, mObject);
         glViewport(0, 0, mWidth, mHeight);
         PushTextureStack();
     }
 }
References IsRenderBuffer(), mHeight, mObject, mWidth, and PushTextureStack().
Referenced by cDrawUtil::CopyTexture(), and ReadPixels().
BindBuffer3DSlice()
void cTextureDesc::BindBuffer3DSlice (int slice) const virtual
Definition at line 141 of file TextureDesc.cpp.
 {
     glBindFramebuffer(GL_FRAMEBUFFER, mObject);
     glFramebufferTexture3DEXT(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0,
                             GL_TEXTURE_3D, mObject, 0, slice);
     glViewport(0, 0, mWidth, mHeight);
     PushTextureStack();
 }
References mHeight, mObject, mWidth, and PushTextureStack().
BindTex()
void cTextureDesc::BindTex (GLint tex_slot) const virtual
Definition at line 150 of file TextureDesc.cpp.
 {
     glActiveTexture(tex_slot);
     glBindTexture(GL_TEXTURE_2D, GetTexture());
 }
References GetTexture().
Referenced by cDrawUtil::DrawTexQuad().
CheckBoundBuffer()
bool cTextureDesc::CheckBoundBuffer () const virtual
Definition at line 134 of file TextureDesc.cpp.
 {
     GLint curr_obj;
     glGetIntegerv(GL_FRAMEBUFFER_BINDING, &curr_obj);
     return curr_obj == mObject;
 }
References mObject.
Referenced by PopTextureStack().
GetDepthStencil()
GLuint cTextureDesc::GetDepthStencil () const virtual
Definition at line 172 of file TextureDesc.cpp.
 {
     return mDepthStencil;
 }
References mDepthStencil.
GetHeight()
int cTextureDesc::GetHeight () const virtual
Definition at line 192 of file TextureDesc.cpp.
 {
     return mHeight;
 }
References mHeight.
Referenced by GetNumTexels().
GetNumChannels()
int cTextureDesc::GetNumChannels () const virtual
Definition at line 202 of file TextureDesc.cpp.
 {
     int channels = cTextureUtil::GetNumChannels(mChannels);
     return channels;
 }
References cTextureUtil::GetNumChannels(), and mChannels.
Referenced by ReadPixels().
GetNumTexels()
int cTextureDesc::GetNumTexels () const virtual
Definition at line 197 of file TextureDesc.cpp.
 {
     return GetWidth() * GetHeight();
 }
References GetHeight(), and GetWidth().
Referenced by ReadPixels().
GetObj()
GLuint cTextureDesc::GetObj () const virtual
Definition at line 162 of file TextureDesc.cpp.
 {
     return mObject;
 }
References mObject.
GetTexture()
GLuint cTextureDesc::GetTexture () const virtual
Definition at line 167 of file TextureDesc.cpp.
 {
     return mTexture;
 }
References mTexture.
Referenced by BindTex().
GetWidth()
int cTextureDesc::GetWidth () const virtual
Definition at line 187 of file TextureDesc.cpp.
 {
     return mWidth;
 }
References mWidth.
Referenced by GetNumTexels().
IsRenderBuffer()
bool cTextureDesc::IsRenderBuffer () const virtual
Definition at line 182 of file TextureDesc.cpp.
 {
     return mObject != -1;
 }
References mObject.
Referenced by BindBuffer(), and UnbindBuffer().
IsValid()
bool cTextureDesc::IsValid () const virtual
Definition at line 177 of file TextureDesc.cpp.
 {
     return mTexture != -1;
 }
References mTexture.
PopTextureStack()
void cTextureDesc::PopTextureStack () const protected virtual
Definition at line 256 of file TextureDesc.cpp.
 {
     bool bound = CheckBoundBuffer();
     if (bound)
     {
         gTexStack.pop();
         if (!gTexStack.empty())
         {
             tTexEntry prev_entry = gTexStack.top();
             glBindFramebuffer(GL_FRAMEBUFFER, prev_entry.mTex);
             glViewport(prev_entry.mViewportParams[0], prev_entry.mViewportParams[1],
                 prev_entry.mViewportParams[2], prev_entry.mViewportParams[3]);
         }
     }
     else
     {
         throw std::runtime_error("Trying to pop unbound texture from stack.\n");
     }
 }
References CheckBoundBuffer(), gTexStack, cTextureDesc::tTexEntry::mTex, and cTextureDesc::tTexEntry::mViewportParams.
Referenced by UnbindBuffer().
PushTextureStack()
void cTextureDesc::PushTextureStack () const protected virtual
Definition at line 244 of file TextureDesc.cpp.
 {
     tTexEntry entry;
     entry.mTex = mObject;
     entry.mViewportParams[0] = 0;
     entry.mViewportParams[1] = 0;
     entry.mViewportParams[2] = mWidth;
     entry.mViewportParams[3] = mHeight;
     gTexStack.push(entry);
 }
References gTexStack, mHeight, mObject, cTextureDesc::tTexEntry::mTex, cTextureDesc::tTexEntry::mViewportParams, and mWidth.
Referenced by BindBuffer(), and BindBuffer3DSlice().
ReadPixels()
void cTextureDesc::ReadPixels (std::vector< GLfloat > & out_data, GLenum format = GL_RGBA) virtual
Definition at line 220 of file TextureDesc.cpp.
 {
     BindBuffer();
     int num_channels = GetNumChannels();
     int data_size = GetNumTexels() * num_channels;
     out_data.resize(data_size);
     glReadPixels(0, 0, mWidth, mHeight, format, GL_FLOAT, out_data.data());
     UnbindBuffer();
 }
References BindBuffer(), GetNumChannels(), GetNumTexels(), mHeight, mWidth, and UnbindBuffer().
Reshape()
void cTextureDesc::Reshape (int w, int h) virtual
Reimplemented in cShadowMap.
Definition at line 208 of file TextureDesc.cpp.
 {
     mWidth = std::max(1, w);
     mHeight = std::max(1, h);
     if (mObject != 0) // 0 indicates the device's frame buffer, so no need to resize it
     {
         cTextureUtil::DeleteFrameBuffer(mObject, mTexture, mDepthStencil);
         cTextureUtil::CreateFrameBuffer(mObject, mTexture, mDepthStencil, mWidth, mHeight,
                             mDepth, mChannels, mFormat, mType, mHasMips);
     }
 }
References cTextureUtil::CreateFrameBuffer(), cTextureUtil::DeleteFrameBuffer(), mChannels, mDepth, mDepthStencil, mFormat, mHasMips, mHeight, mObject, mTexture, mType, and mWidth.
UnbindBuffer()
void cTextureDesc::UnbindBuffer () const virtual
Definition at line 126 of file TextureDesc.cpp.
 {
     if (IsRenderBuffer())
     {
         PopTextureStack();
     }
 }
References IsRenderBuffer(), and PopTextureStack().
Referenced by cDrawUtil::CopyTexture(), and ReadPixels().
UnbindTex()
void cTextureDesc::UnbindTex (GLint tex_slot) const virtual
Definition at line 156 of file TextureDesc.cpp.
 {
     glActiveTexture(tex_slot);
     glBindTexture(GL_TEXTURE_2D, 0);
 }
Referenced by cDrawUtil::DrawTexQuad().
WritePixels()
void cTextureDesc::WritePixels (const std::vector< GLubyte > & data) virtual
Definition at line 232 of file TextureDesc.cpp.
 {
     glBindTexture(GL_TEXTURE_2D, mTexture);
     glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, mWidth, mHeight, mFormat, mType, data.data());
     glBindTexture(GL_TEXTURE_2D, 0);
 }
References mFormat, mHeight, mTexture, mType, and mWidth.
Member Data Documentation
gNumViewportParams
const int cTextureDesc::gNumViewportParams = 4 static protected
Definition at line 45 of file TextureDesc.h.
Referenced by cTextureDesc::tTexEntry::tTexEntry().
gTexStack
std::stack< cTextureDesc::tTexEntry > cTextureDesc::gTexStack = std::stack<cTextureDesc::tTexEntry>() static protected
Definition at line 52 of file TextureDesc.h.
Referenced by PopTextureStack(), and PushTextureStack().
mChannels
int cTextureDesc::mChannels protected
Definition at line 57 of file TextureDesc.h.
Referenced by cTextureDesc(), GetNumChannels(), and Reshape().
mDepth
int cTextureDesc::mDepth protected
Definition at line 56 of file TextureDesc.h.
Referenced by cTextureDesc(), and Reshape().
mDepthStencil
GLuint cTextureDesc::mDepthStencil protected
Definition at line 64 of file TextureDesc.h.
Referenced by cTextureDesc(), GetDepthStencil(), cShadowMap::Reshape(), Reshape(), and ~cTextureDesc().
mFormat
GLenum cTextureDesc::mFormat protected
Definition at line 58 of file TextureDesc.h.
Referenced by cTextureDesc(), Reshape(), and WritePixels().
mHasMips
bool cTextureDesc::mHasMips protected
Definition at line 60 of file TextureDesc.h.
Referenced by cTextureDesc(), and Reshape().
mHeight
int cTextureDesc::mHeight protected
Definition at line 55 of file TextureDesc.h.
Referenced by BindBuffer(), BindBuffer3DSlice(), cTextureDesc(), GetHeight(), cShadowMap::Init(), PushTextureStack(), ReadPixels(), cShadowMap::Reshape(), Reshape(), and WritePixels().
mObject
GLuint cTextureDesc::mObject protected
Definition at line 62 of file TextureDesc.h.
Referenced by BindBuffer(), BindBuffer3DSlice(), CheckBoundBuffer(), cTextureDesc(), GetObj(), cShadowMap::Init(), IsRenderBuffer(), PushTextureStack(), cShadowMap::Reshape(), Reshape(), and ~cTextureDesc().
mTexture
GLuint cTextureDesc::mTexture protected
Definition at line 63 of file TextureDesc.h.
Referenced by cTextureDesc(), GetTexture(), cShadowMap::Init(), IsValid(), cShadowMap::Reshape(), Reshape(), WritePixels(), and ~cTextureDesc().
mType
GLenum cTextureDesc::mType protected
Definition at line 59 of file TextureDesc.h.
Referenced by cTextureDesc(), Reshape(), and WritePixels().
mWidth
int cTextureDesc::mWidth protected
Definition at line 54 of file TextureDesc.h.
Referenced by BindBuffer(), BindBuffer3DSlice(), cTextureDesc(), GetWidth(), cShadowMap::Init(), PushTextureStack(), ReadPixels(), cShadowMap::Reshape(), Reshape(), and WritePixels().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/TextureDesc.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/TextureDesc.cpp