My Project: cCharController Class Reference
cCharController Class Reference abstract
#include <CharController.h>
Public Member Functions
virtual ~cCharController ()
virtual void Update (double time_step)
virtual void PostUpdate (double time_step)
virtual bool NeedNewAction () const
virtual void ApplyAction (const Eigen::VectorXd &action)
virtual void RecordState (Eigen::VectorXd &out_state)
virtual void RecordGoal (Eigen::VectorXd &out_goal) const
virtual void RecordAction (Eigen::VectorXd &out_action) const
virtual eActionSpace GetActionSpace () const =0
virtual int GetStateSize () const
virtual int GetGoalSize () const
virtual int GetActionSize () const
virtual int GetNumActions () const
virtual void HandlePoseReset ()
virtual void HandleVelReset ()
virtual void BuildStateOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildGoalOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionBounds (Eigen::VectorXd &out_min, Eigen::VectorXd &out_max) const
virtual void BuildStateNormGroups (Eigen::VectorXi &out_groups) const
virtual void BuildGoalNormGroups (Eigen::VectorXi &out_groups) const
virtual double GetRewardMin () const
virtual double GetRewardMax () const
virtual int NumChildren () const
virtual const std::shared_ptr< cCharController > & GetChild (int i) const
virtual std::string GetName () const =0
Public Member Functions inherited from cController
virtual ~cController ()
virtual void Init (cSimCharacter *character)
virtual void Reset ()
virtual void Clear ()
virtual bool IsValid () const
virtual bool LoadParams (const std::string &param_file)
virtual int GetNumOptParams () const
virtual void BuildOptParams (Eigen::VectorXd &out_params) const
virtual void SetOptParams (const Eigen::VectorXd &params)
virtual void SetOptParams (const Eigen::VectorXd &params, Eigen::VectorXd &out_params) const
virtual void FetchOptParamScale (Eigen::VectorXd &out_scale) const
virtual void OutputOptParams (const std::string &file, const Eigen::VectorXd &params) const
virtual void OutputOptParams (FILE *f, const Eigen::VectorXd &params) const
virtual void SetActive (bool active)
virtual bool IsActive () const
virtual void SetMode (eMode mode)
virtual const cSimCharacter * GetChar () const
Static Public Attributes
const static int gNormGroupSingle = 0
const static int gNormGroupNone = -1
Protected Member Functions
cCharController ()
Protected Member Functions inherited from cController
cController ()
virtual bool ParseParams (const Json::Value &json)
Additional Inherited Members
Public Types inherited from cController
enum eMode { eModeActive, eModeInactive, eModePassive, eModeMax }
Protected Attributes inherited from cController
cSimCharacter * mChar
eMode mMode
bool mValid
Detailed Description
Definition at line 7 of file CharController.h.
Constructor & Destructor Documentation
~cCharController()
cCharController::~cCharController () virtual
Definition at line 11 of file CharController.cpp.
 {
 }
cCharController()
cCharController::cCharController () protected
Definition at line 7 of file CharController.cpp.
 {
 }
Member Function Documentation
ApplyAction()
void cCharController::ApplyAction (const Eigen::VectorXd & action) virtual
Reimplemented in cCtPDController, cDeepMimicCharController, and cCtVelController.
Definition at line 29 of file CharController.cpp.
 {
 }
BuildActionBounds()
void cCharController::BuildActionBounds (Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) const virtual
Reimplemented in cCtController.
Definition at line 94 of file CharController.cpp.
 {
     int action_size = GetActionSize();
     out_min = -std::numeric_limits<double>::infinity() * Eigen::VectorXd::Ones(action_size);
     out_max = std::numeric_limits<double>::infinity() * Eigen::VectorXd::Ones(action_size);
 }
References GetActionSize().
BuildActionOffsetScale()
void cCharController::BuildActionOffsetScale (Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const virtual
Reimplemented in cCtController.
Definition at line 87 of file CharController.cpp.
 {
     int action_size = GetActionSize();
     out_offset = Eigen::VectorXd::Zero(action_size);
     out_scale = Eigen::VectorXd::Ones(action_size);
 }
References GetActionSize().
BuildGoalNormGroups()
void cCharController::BuildGoalNormGroups (Eigen::VectorXi & out_groups) const virtual
Definition at line 107 of file CharController.cpp.
 {
     int goal_size = GetGoalSize();
     out_groups = gNormGroupSingle * Eigen::VectorXi::Ones(goal_size);
 }
References GetGoalSize(), and gNormGroupSingle.
BuildGoalOffsetScale()
void cCharController::BuildGoalOffsetScale (Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const virtual
Definition at line 80 of file CharController.cpp.
 {
     int goal_size = GetGoalSize();
     out_offset = Eigen::VectorXd::Zero(goal_size);
     out_scale = Eigen::VectorXd::Ones(goal_size);
 }
References GetGoalSize().
BuildStateNormGroups()
void cCharController::BuildStateNormGroups (Eigen::VectorXi & out_groups) const virtual
Reimplemented in cCtController.
Definition at line 101 of file CharController.cpp.
 {
     int state_size = GetStateSize();
     out_groups = gNormGroupSingle * Eigen::VectorXi::Ones(state_size);
 }
References GetStateSize(), and gNormGroupSingle.
Referenced by cCtController::BuildStateNormGroups().
BuildStateOffsetScale()
void cCharController::BuildStateOffsetScale (Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const virtual
Reimplemented in cCtController.
Definition at line 73 of file CharController.cpp.
 {
     int state_size = GetStateSize();
     out_offset = Eigen::VectorXd::Zero(state_size);
     out_scale = Eigen::VectorXd::Ones(state_size);
 }
References GetStateSize().
Referenced by cCtController::BuildStateOffsetScale().
GetActionSize()
int cCharController::GetActionSize () const virtual
Reimplemented in cCtController.
Definition at line 55 of file CharController.cpp.
 {
     return 0;
 }
Referenced by cDeepMimicCharController::ApplyAction(), BuildActionBounds(), BuildActionOffsetScale(), and cDeepMimicCharController::InitAction().
GetActionSpace()
virtual eActionSpace cCharController::GetActionSpace () const pure virtual
Implemented in cDeepMimicCharController.
GetChild()
const std::shared_ptr< cCharController > & cCharController::GetChild (int i) const virtual
Definition at line 128 of file CharController.cpp.
 {
     return nullptr;
 }
GetGoalSize()
int cCharController::GetGoalSize () const virtual
Definition at line 50 of file CharController.cpp.
 {
     return 0;
 }
Referenced by BuildGoalNormGroups(), BuildGoalOffsetScale(), and cDeepMimicCharController::RecordGoal().
GetName()
virtual std::string cCharController::GetName () const pure virtual
Implemented in cCtController, cCtPDController, and cCtVelController.
GetNumActions()
int cCharController::GetNumActions () const virtual
Definition at line 60 of file CharController.cpp.
 {
     return 0;
 }
GetRewardMax()
double cCharController::GetRewardMax () const virtual
Reimplemented in cDeepMimicCharController.
Definition at line 118 of file CharController.cpp.
 {
     return std::numeric_limits<double>::infinity();
 }
GetRewardMin()
double cCharController::GetRewardMin () const virtual
Reimplemented in cDeepMimicCharController.
Definition at line 113 of file CharController.cpp.
 {
     return -std::numeric_limits<double>::infinity();
 }
GetStateSize()
int cCharController::GetStateSize () const virtual
Reimplemented in cDeepMimicCharController, and cCtController.
Definition at line 45 of file CharController.cpp.
 {
     return 0;
 }
Referenced by BuildStateNormGroups(), and BuildStateOffsetScale().
HandlePoseReset()
void cCharController::HandlePoseReset () virtual
Definition at line 65 of file CharController.cpp.
 {
 }
HandleVelReset()
void cCharController::HandleVelReset () virtual
Definition at line 69 of file CharController.cpp.
 {
 }
NeedNewAction()
bool cCharController::NeedNewAction () const virtual
Reimplemented in cDeepMimicCharController.
Definition at line 24 of file CharController.cpp.
 {
     return false;
 }
NumChildren()
int cCharController::NumChildren () const virtual
Definition at line 123 of file CharController.cpp.
 {
     return 0;
 }
PostUpdate()
void cCharController::PostUpdate (double time_step) virtual
Reimplemented in cDeepMimicCharController.
Definition at line 20 of file CharController.cpp.
 {
 }
RecordAction()
void cCharController::RecordAction (Eigen::VectorXd & out_action) const virtual
Reimplemented in cDeepMimicCharController.
Definition at line 41 of file CharController.cpp.
 {
 }
RecordGoal()
void cCharController::RecordGoal (Eigen::VectorXd & out_goal) const virtual
Reimplemented in cDeepMimicCharController.
Definition at line 37 of file CharController.cpp.
 {
 }
RecordState()
void cCharController::RecordState (Eigen::VectorXd & out_state) virtual
Reimplemented in cCtController, and cDeepMimicCharController.
Definition at line 33 of file CharController.cpp.
 {
 }
Update()
void cCharController::Update (double time_step) virtual
Reimplemented from cController.
Reimplemented in cDeepMimicCharController.
Definition at line 15 of file CharController.cpp.
 {
     cController::Update(time_step);
 }
References cController::Update().
Referenced by cDeepMimicCharController::Update().
Member Data Documentation
gNormGroupNone
const int cCharController::gNormGroupNone = -1 static
Definition at line 17 of file CharController.h.
Referenced by cCtController::BuildStateNormGroups().
gNormGroupSingle
const int cCharController::gNormGroupSingle = 0 static
Definition at line 16 of file CharController.h.
Referenced by BuildGoalNormGroups(), and BuildStateNormGroups().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/CharController.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/CharController.cpp