My Project: cKinTree Class Reference
cKinTree Class Reference
#include <KinTree.h>
Public Types
enum eJointType {
eJointTypeRevolute, eJointTypePlanar, eJointTypePrismatic, eJointTypeFixed,
eJointTypeSpherical, eJointTypeNone, eJointTypeMax
}
enum eJointDesc {
eJointDescType, eJointDescParent, eJointDescAttachX, eJointDescAttachY,
eJointDescAttachZ, eJointDescAttachThetaX, eJointDescAttachThetaY, eJointDescAttachThetaZ,
eJointDescLimLow0, eJointDescLimLow1, eJointDescLimLow2, eJointDescLimHigh0,
eJointDescLimHigh1, eJointDescLimHigh2, eJointDescTorqueLim, eJointDescForceLim,
eJointDescIsEndEffector, eJointDescDiffWeight, eJointDescParamOffset, eJointDescMax
}
enum eBodyParam {
eBodyParamShape, eBodyParamMass, eBodyParamColGroup, eBodyParamEnableFallContact,
eBodyParamAttachX, eBodyParamAttachY, eBodyParamAttachZ, eBodyParamAttachThetaX,
eBodyParamAttachThetaY, eBodyParamAttachThetaZ, eBodyParam0, eBodyParam1,
eBodyParam2, eBodyColorR, eBodyColorG, eBodyColorB,
eBodyColorA, eBodyParamMax
}
enum eDrawShape {
eDrawShapeShape, eDrawShapeParentJoint, eDrawShapeAttachX, eDrawShapeAttachY,
eDrawShapeAttachZ, eDrawShapeAttachThetaX, eDrawShapeAttachThetaY, eDrawShapeAttachThetaZ,
eDrawShapeParam0, eDrawShapeParam1, eDrawShapeParam2, eDrawShapeColorR,
eDrawShapeColorG, eDrawShapeColorB, eDrawShapeColorA, eDrawShapeMeshID,
eDrawShapeParamMax
}
typedef Eigen::Matrix< double, 1, eJointDescMax > tJointDesc
typedef Eigen::Matrix< double, 1, eBodyParamMax > tBodyDef
typedef Eigen::Matrix< double, 1, eDrawShapeParamMax > tDrawShapeDef
Static Public Member Functions
static bool HasValidRoot (const Eigen::MatrixXd &joint_mat)
static tVector GetRootPos (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state)
static void SetRootPos (const Eigen::MatrixXd &joint_mat, const tVector &pos, Eigen::VectorXd &out_state)
static tQuaternion GetRootRot (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state)
static void SetRootRot (const Eigen::MatrixXd &joint_mat, const tQuaternion &rot, Eigen::VectorXd &out_state)
static tVector GetRootVel (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &vel)
static void SetRootVel (const Eigen::MatrixXd &joint_mat, const tVector &vel, Eigen::VectorXd &out_vel)
static tVector GetRootAngVel (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &vel)
static void SetRootAngVel (const Eigen::MatrixXd &joint_mat, const tVector &ang_vel, Eigen::VectorXd &out_vel)
static tVector CalcJointWorldPos (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int joint_id)
static tVector LocalToWorldPos (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int parent_id, const tVector &attach_pt)
static tQuaternion CalcJointWorldRot (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int joint_id)
static void CalcJointWorldTheta (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int joint_id, tVector &out_axis, double &out_theta)
static tVector CalcJointWorldVel (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, const Eigen::VectorXd &vel, int joint_id)
static tVector CalcWorldVel (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, const Eigen::VectorXd &vel, int parent_id, const tVector &attach_pt)
static tVector CalcJointWorldAngularVel (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, const Eigen::VectorXd &vel, int joint_id)
static tVector CalcWorldAngularVel (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, const Eigen::VectorXd &vel, int parent_id, const tVector &attach_pt)
static int GetNumDof (const Eigen::MatrixXd &joint_mat)
static void ApplyStep (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &step, Eigen::VectorXd &out_pose)
static Eigen::VectorXi FindJointChain (const Eigen::MatrixXd &joint_mat, int joint_beg, int joint_end)
static bool IsAncestor (const Eigen::MatrixXd &joint_mat, int child_joint, int ancestor_joint, int &out_len)
static double CalcChainLength (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXi &chain)
static void CalcAABB (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, tVector &out_min, tVector &out_max)
static int GetParamOffset (const Eigen::MatrixXd &joint_mat, int joint_id)
static int GetParamSize (const Eigen::MatrixXd &joint_mat, int joint_id)
static int GetJointParamSize (eJointType joint_type)
static void GetJointParams (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int j, Eigen::VectorXd &out_params)
static void SetJointParams (const Eigen::MatrixXd &joint_mat, int j, const Eigen::VectorXd &params, Eigen::VectorXd &out_state)
static eJointType GetJointType (const Eigen::MatrixXd &joint_mat, int joint_id)
static int GetParent (const Eigen::MatrixXd &joint_mat, int joint_id)
static bool HasParent (const Eigen::MatrixXd &joint_mat, int joint_id)
static bool IsRoot (const Eigen::MatrixXd &joint_mat, int joint_id)
static bool IsJointActuated (const Eigen::MatrixXd &joint_mat, int joint_id)
static double GetTorqueLimit (const Eigen::MatrixXd &joint_mat, int joint_id)
static double GetForceLimit (const Eigen::MatrixXd &joint_mat, int joint_id)
static bool IsEndEffector (const Eigen::MatrixXd &joint_mat, int joint_id)
static tVector GetJointLimLow (const Eigen::MatrixXd &joint_mat, int joint_id)
static tVector GetJointLimHigh (const Eigen::MatrixXd &joint_mat, int joint_id)
static double GetJointDiffWeight (const Eigen::MatrixXd &joint_mat, int joint_id)
static double CalcLinkLength (const Eigen::MatrixXd &joint_mat, int joint_id)
static tVector GetAttachPt (const Eigen::MatrixXd &joint_mat, int joint_id)
static tVector GetAttachTheta (const Eigen::MatrixXd &joint_mat, int joint_id)
static void CalcMaxSubChainLengths (const Eigen::MatrixXd &joint_mat, Eigen::VectorXd &out_lengths)
static void CalcSubTreeMasses (const Eigen::MatrixXd &joint_mat, const Eigen::MatrixXd &body_defs, Eigen::VectorXd &out_masses)
static tMatrix BuildAttachTrans (const Eigen::MatrixXd &joint_mat, int joint_id)
static tMatrix ChildParentTrans (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int joint_id)
static tMatrix ParentChildTrans (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int joint_id)
static tMatrix JointWorldTrans (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int joint_id)
static tMatrix WorldJointTrans (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int joint_id)
static bool Load (const Json::Value &root, Eigen::MatrixXd &out_joint_mat)
static int GetNumJoints (const Eigen::MatrixXd &joint_mat)
static int GetRoot (const Eigen::MatrixXd &joint_mat)
static void FindChildren (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXi &out_children)
static bool LoadBodyDefs (const std::string &char_file, Eigen::MatrixXd &out_body_defs)
static bool ParseBodyDef (const Json::Value &root, tBodyDef &out_def)
static bool LoadDrawShapeDefs (const std::string &char_file, Eigen::MatrixXd &out_draw_defs)
static bool ParseDrawShapeDef (const Json::Value &root, tDrawShapeDef &out_def)
static cShape::eShape GetBodyShape (const Eigen::MatrixXd &body_defs, int part_id)
static tVector GetBodyAttachPt (const Eigen::MatrixXd &body_defs, int part_id)
static tVector GetBodyAttachTheta (const Eigen::MatrixXd &body_defs, int part_id)
static void GetBodyRotation (const Eigen::MatrixXd &body_defs, int part_id, tVector &out_axis, double &out_theta)
static double GetBodyMass (const Eigen::MatrixXd &body_defs, int part_id)
static int GetBodyColGroup (const Eigen::MatrixXd &body_defs, int part_id)
static bool GetBodyEnableFallContact (const Eigen::MatrixXd &body_defs, int part_id)
static void SetBodyEnableFallContact (int part_id, bool enable, Eigen::MatrixXd &out_body_defs)
static tVector GetBodySize (const Eigen::MatrixXd &body_defs, int part_id)
static tVector GetBodyColor (const Eigen::MatrixXd &body_defs, int part_id)
static double CalcTotalMass (const Eigen::MatrixXd &body_defs)
static bool IsValidBody (const Eigen::MatrixXd &body_defs, int part_id)
static tVector GetBodyLocalCoM (const Eigen::MatrixXd &body_defs, int part_id)
static int GetDrawShapeParentJoint (const tDrawShapeDef &shape)
static tVector GetDrawShapeAttachPt (const tDrawShapeDef &shape)
static tVector GetDrawShapeAttachTheta (const tDrawShapeDef &shape)
static void GetDrawShapeRotation (const tDrawShapeDef &shape, tVector &out_axis, double &out_theta)
static tVector GetDrawShapeColor (const tDrawShapeDef &shape)
static int GetDrawShapeMeshID (const tDrawShapeDef &shape)
static tVector CalcBodyPartPos (const Eigen::MatrixXd &joint_mat, const Eigen::MatrixXd &body_defs, const Eigen::VectorXd &state, int part_id)
static tVector CalcBodyPartVel (const Eigen::MatrixXd &joint_mat, const Eigen::MatrixXd &body_defs, const Eigen::VectorXd &state, const Eigen::VectorXd &vel, int part_id)
static void CalcBodyPartRotation (const Eigen::MatrixXd &joint_mat, const Eigen::MatrixXd &body_defs, const Eigen::VectorXd &state, int part_id, tVector &out_axis, double &out_theta)
static tMatrix BodyWorldTrans (const Eigen::MatrixXd &joint_mat, const Eigen::MatrixXd &body_defs, const Eigen::VectorXd &state, int part_id)
static tMatrix BodyJointTrans (const Eigen::MatrixXd &body_defs, int part_id)
static tJointDesc BuildJointDesc (eJointType joint_type, int parent_id, const tVector &attach_pt)
static tJointDesc BuildJointDesc ()
static tBodyDef BuildBodyDef ()
static tDrawShapeDef BuildDrawShapeDef ()
static void BuildDefaultPose (const Eigen::MatrixXd &joint_mat, Eigen::VectorXd &out_pose)
static void BuildDefaultVel (const Eigen::MatrixXd &joint_mat, Eigen::VectorXd &out_vel)
static void CalcPoseDiff (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose0, const Eigen::VectorXd &pose1, Eigen::VectorXd &out_diff)
static tVector CalcRootPosDiff (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose0, const Eigen::VectorXd &pose1)
static tQuaternion CalcRootRotDiff (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose0, const Eigen::VectorXd &pose1)
static double CalcPoseErr (const Eigen::MatrixXd &joint_mat, int joint_id, const Eigen::VectorXd &pose0, const Eigen::VectorXd &pose1)
static double CalcRootPosErr (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose0, const Eigen::VectorXd &pose1)
static double CalcRootRotErr (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose0, const Eigen::VectorXd &pose1)
static void CalcVelDiff (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &vel0, const Eigen::VectorXd &vel1, Eigen::VectorXd &out_diff)
static tVector CalcRootVelDiff (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose0, const Eigen::VectorXd &pose1)
static tVector CalcRootAngVelDiff (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose0, const Eigen::VectorXd &pose1)
static double CalcVelErr (const Eigen::MatrixXd &joint_mat, int joint_id, const Eigen::VectorXd &vel0, const Eigen::VectorXd &vel1)
static double CalcRootVelErr (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &vel0, const Eigen::VectorXd &vel1)
static double CalcRootAngVelErr (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &vel0, const Eigen::VectorXd &vel1)
static void CalcVel (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose0, const Eigen::VectorXd &pose1, double dt, Eigen::VectorXd &out_vel)
static void PostProcessPose (const Eigen::MatrixXd &joint_mat, Eigen::VectorXd &out_pose)
static void LerpPoses (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose0, const Eigen::VectorXd &pose1, double lerp, Eigen::VectorXd &out_pose)
static void VelToPoseDiff (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose, const Eigen::VectorXd &vel, Eigen::VectorXd &out_pose_diff)
static double CalcHeading (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose)
static tQuaternion CalcHeadingRot (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose)
static tMatrix BuildHeadingTrans (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose)
static tMatrix BuildOriginTrans (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &pose)
static void NormalizePoseHeading (const Eigen::MatrixXd &joint_mat, Eigen::VectorXd &out_pose)
static void NormalizePoseHeading (const Eigen::MatrixXd &joint_mat, Eigen::VectorXd &out_pose, Eigen::VectorXd &out_vel)
static void MirrorPoseStance (const Eigen::MatrixXd &joint_mat, const std::vector< int > mirror_joints0, const std::vector< int > mirror_joints1, Eigen::VectorXd &out_pose)
static std::string BuildJointMatJson (const Eigen::MatrixXd &joint_mat)
static std::string BuildJointJson (int id, const tJointDesc &joint_desc)
Static Public Attributes
static const int gInvalidJointID = -1
static const int gPosDim = 3
static const int gRotDim = 4
static const int gRootDim = gPosDim + gRotDim
Static Protected Member Functions
static bool ParseJoint (const Json::Value &root, tJointDesc &out_joint_desc)
static bool ParseJointType (const std::string &type_str, eJointType &out_joint_type)
static void PostProcessJointMat (Eigen::MatrixXd &out_joint_mat)
static tMatrix ChildParentTransRoot (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int joint_id)
static tMatrix ChildParentTransRevolute (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int joint_id)
static tMatrix ChildParentTransPlanar (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int joint_id)
static tMatrix ChildParentTransFixed (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int joint_id)
static tMatrix ChildParentTransPrismatic (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int joint_id)
static tMatrix ChildParentTransSpherical (const Eigen::MatrixXd &joint_mat, const Eigen::VectorXd &state, int joint_id)
static void BuildDefaultPoseRoot (const Eigen::MatrixXd &joint_mat, Eigen::VectorXd &out_pose)
static void BuildDefaultPoseRevolute (Eigen::VectorXd &out_pose)
static void BuildDefaultPosePrismatic (Eigen::VectorXd &out_pose)
static void BuildDefaultPosePlanar (Eigen::VectorXd &out_pose)
static void BuildDefaultPoseFixed (Eigen::VectorXd &out_pose)
static void BuildDefaultPoseSpherical (Eigen::VectorXd &out_pose)
static void BuildDefaultVelRoot (const Eigen::MatrixXd &joint_mat, Eigen::VectorXd &out_pose)
static void BuildDefaultVelRevolute (Eigen::VectorXd &out_pose)
static void BuildDefaultVelPrismatic (Eigen::VectorXd &out_pose)
static void BuildDefaultVelPlanar (Eigen::VectorXd &out_pose)
static void BuildDefaultVelFixed (Eigen::VectorXd &out_pose)
static void BuildDefaultVelSpherical (Eigen::VectorXd &out_pose)
static void CalcJointPoseDiff (const Eigen::MatrixXd &joint_mat, int joint_id, const Eigen::VectorXd &pose0, const Eigen::VectorXd &pose1, Eigen::VectorXd &out_diff)
static void CalcJointVelDiff (const Eigen::MatrixXd &joint_mat, int joint_id, const Eigen::VectorXd &vel0, const Eigen::VectorXd &vel1, Eigen::VectorXd &out_diff)
Detailed Description
Definition at line 9 of file KinTree.h.
Member Typedef Documentation
tBodyDef
typedef Eigen::Matrix<double, 1, eBodyParamMax> cKinTree::tBodyDef
Definition at line 70 of file KinTree.h.
tDrawShapeDef
typedef Eigen::Matrix<double, 1, eDrawShapeParamMax> cKinTree::tDrawShapeDef
Definition at line 92 of file KinTree.h.
tJointDesc
typedef Eigen::Matrix<double, 1, eJointDescMax> cKinTree::tJointDesc
Definition at line 47 of file KinTree.h.
Member Enumeration Documentation
eBodyParam
enum cKinTree::eBodyParam
Enumerator
eBodyParamShape
eBodyParamMass
eBodyParamColGroup
eBodyParamEnableFallContact
eBodyParamAttachX
eBodyParamAttachY
eBodyParamAttachZ
eBodyParamAttachThetaX
eBodyParamAttachThetaY
eBodyParamAttachThetaZ
eBodyParam0
eBodyParam1
eBodyParam2
eBodyColorR
eBodyColorG
eBodyColorB
eBodyColorA
eBodyParamMax
Definition at line 49 of file KinTree.h.
     {
         eBodyParamShape,
         eBodyParamMass,
         eBodyParamColGroup, // 0 collides with nothing and 1 collides with everything
         eBodyParamEnableFallContact,
         eBodyParamAttachX,
         eBodyParamAttachY,
         eBodyParamAttachZ,
         eBodyParamAttachThetaX, // Euler angles order XYZ
         eBodyParamAttachThetaY,
         eBodyParamAttachThetaZ,
         eBodyParam0,
         eBodyParam1,
         eBodyParam2,
         eBodyColorR,
         eBodyColorG,
         eBodyColorB,
         eBodyColorA,
         eBodyParamMax
     };
eDrawShape
enum cKinTree::eDrawShape
Enumerator
eDrawShapeShape
eDrawShapeParentJoint
eDrawShapeAttachX
eDrawShapeAttachY
eDrawShapeAttachZ
eDrawShapeAttachThetaX
eDrawShapeAttachThetaY
eDrawShapeAttachThetaZ
eDrawShapeParam0
eDrawShapeParam1
eDrawShapeParam2
eDrawShapeColorR
eDrawShapeColorG
eDrawShapeColorB
eDrawShapeColorA
eDrawShapeMeshID
eDrawShapeParamMax
Definition at line 72 of file KinTree.h.
     {
         eDrawShapeShape,
         eDrawShapeParentJoint,
         eDrawShapeAttachX,
         eDrawShapeAttachY,
         eDrawShapeAttachZ,
         eDrawShapeAttachThetaX, // Euler angles order XYZ
         eDrawShapeAttachThetaY,
         eDrawShapeAttachThetaZ,
         eDrawShapeParam0,
         eDrawShapeParam1,
         eDrawShapeParam2,
         eDrawShapeColorR,
         eDrawShapeColorG,
         eDrawShapeColorB,
         eDrawShapeColorA,
         eDrawShapeMeshID,
         eDrawShapeParamMax
     };
eJointDesc
enum cKinTree::eJointDesc
Enumerator
eJointDescType
eJointDescParent
eJointDescAttachX
eJointDescAttachY
eJointDescAttachZ
eJointDescAttachThetaX
eJointDescAttachThetaY
eJointDescAttachThetaZ
eJointDescLimLow0
eJointDescLimLow1
eJointDescLimLow2
eJointDescLimHigh0
eJointDescLimHigh1
eJointDescLimHigh2
eJointDescTorqueLim
eJointDescForceLim
eJointDescIsEndEffector
eJointDescDiffWeight
eJointDescParamOffset
eJointDescMax
Definition at line 24 of file KinTree.h.
     {
         eJointDescType,
         eJointDescParent,
         eJointDescAttachX,
         eJointDescAttachY,
         eJointDescAttachZ,
         eJointDescAttachThetaX, // euler angles order rot(Z) * rot(Y) * rot(X)
         eJointDescAttachThetaY,
         eJointDescAttachThetaZ,
         eJointDescLimLow0,
         eJointDescLimLow1,
         eJointDescLimLow2,
         eJointDescLimHigh0,
         eJointDescLimHigh1,
         eJointDescLimHigh2,
         eJointDescTorqueLim,
         eJointDescForceLim,
         eJointDescIsEndEffector,
         eJointDescDiffWeight,
         eJointDescParamOffset,
         eJointDescMax
     };
eJointType
enum cKinTree::eJointType
Enumerator
eJointTypeRevolute
eJointTypePlanar
eJointTypePrismatic
eJointTypeFixed
eJointTypeSpherical
eJointTypeNone
eJointTypeMax
Definition at line 13 of file KinTree.h.
     {
         eJointTypeRevolute,
         eJointTypePlanar,
         eJointTypePrismatic,
         eJointTypeFixed,
         eJointTypeSpherical,
         eJointTypeNone,
         eJointTypeMax
     };
Member Function Documentation
ApplyStep()
void cKinTree::ApplyStep (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & step, Eigen::VectorXd & out_pose) static
Definition at line 625 of file KinTree.cpp.
 {
     int root_id = GetRoot(joint_mat);
     int num_joints = cKinTree::GetNumJoints(joint_mat);
     out_pose += step;
 }
References GetNumJoints(), and GetRoot().
BodyJointTrans()
tMatrix cKinTree::BodyJointTrans (const Eigen::MatrixXd & body_defs, int part_id) static
Definition at line 1120 of file KinTree.cpp.
 {
     tVector attach_pt = GetBodyAttachPt(body_defs, part_id);
     tVector euler = GetBodyAttachTheta(body_defs, part_id);
     tVector com = GetBodyLocalCoM(body_defs, part_id);
     tMatrix rot = cMathUtil::RotateMat(euler);
     tMatrix trans = cMathUtil::TranslateMat(attach_pt + com);
     tMatrix m = trans * rot;
     return m;
 }
References GetBodyAttachPt(), GetBodyAttachTheta(), GetBodyLocalCoM(), cMathUtil::RotateMat(), and cMathUtil::TranslateMat().
Referenced by BodyWorldTrans(), cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildInertiaSpatialMat(), CalcBodyPartPos(), and cRBDUtil::CalcCoM().
BodyWorldTrans()
tMatrix cKinTree::BodyWorldTrans (const Eigen::MatrixXd & joint_mat, const Eigen::MatrixXd & body_defs, const Eigen::VectorXd & state, int part_id) static
Definition at line 1112 of file KinTree.cpp.
 {
     tMatrix body_trans = BodyJointTrans(body_defs, part_id);
     tMatrix joint_trans = JointWorldTrans(joint_mat, state, part_id);
     body_trans = joint_trans * body_trans;
     return body_trans;
 }
References BodyJointTrans(), and JointWorldTrans().
Referenced by CalcBodyPartRotation().
BuildAttachTrans()
tMatrix cKinTree::BuildAttachTrans (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 1034 of file KinTree.cpp.
 {
     // child to parent
     tVector attach_pt = GetAttachPt(joint_mat, joint_id);
     tVector attach_theta = GetAttachTheta(joint_mat, joint_id);
     tMatrix mat = cMathUtil::RotateMat(attach_theta);
     mat(0, 3) = attach_pt[0];
     mat(1, 3) = attach_pt[1];
     mat(2, 3) = attach_pt[2];
     return mat;
 }
References GetAttachPt(), GetAttachTheta(), and cMathUtil::RotateMat().
Referenced by ChildParentTransFixed(), ChildParentTransPlanar(), ChildParentTransPrismatic(), ChildParentTransRevolute(), ChildParentTransRoot(), and ChildParentTransSpherical().
BuildBodyDef()
cKinTree::tBodyDef cKinTree::BuildBodyDef () static
Definition at line 1170 of file KinTree.cpp.
 {
     tBodyDef def;
     def(eBodyParamShape) = static_cast<double>(cShape::eShapeNull);
     def(eBodyParamMass) = 0;
     def(eBodyParamColGroup) = gInvalidIdx;
     def(eBodyParamEnableFallContact) = 0;
     def(eBodyParamAttachX) = 0;
     def(eBodyParamAttachY) = 0;
     def(eBodyParamAttachZ) = 0;
     def(eBodyParamAttachThetaX) = 0;
     def(eBodyParamAttachThetaY) = 0;
     def(eBodyParamAttachThetaZ) = 0;
     def(eBodyParam0) = 0;
     def(eBodyParam1) = 0;
     def(eBodyParam2) = 0;
     def(eBodyColorR) = 0;
     def(eBodyColorG) = 0;
     def(eBodyColorB) = 0;
     def(eBodyColorA) = 1;
     return def;
 }
References eBodyColorA, eBodyColorB, eBodyColorG, eBodyColorR, eBodyParam0, eBodyParam1, eBodyParam2, eBodyParamAttachThetaX, eBodyParamAttachThetaY, eBodyParamAttachThetaZ, eBodyParamAttachX, eBodyParamAttachY, eBodyParamAttachZ, eBodyParamColGroup, eBodyParamEnableFallContact, eBodyParamMass, eBodyParamShape, cShape::eShapeNull, and gInvalidIdx.
Referenced by LoadBodyDefs().
BuildDefaultPose()
void cKinTree::BuildDefaultPose (const Eigen::MatrixXd & joint_mat, Eigen::VectorXd & out_pose) static
Definition at line 1215 of file KinTree.cpp.
 {
     int num_dof = GetNumDof(joint_mat);
     out_pose = Eigen::VectorXd::Zero(num_dof);
     int num_joints = GetNumJoints(joint_mat);
     int root_id = GetRoot(joint_mat);
     Eigen::VectorXd root_pose;
     BuildDefaultPoseRoot(joint_mat, root_pose);
     SetJointParams(joint_mat, root_id, root_pose, out_pose);
     for (int j = 1; j < num_joints; ++j)
     {
         eJointType joint_type = GetJointType(joint_mat, j);
         Eigen::VectorXd joint_pose;
         switch (joint_type)
         {
         case eJointTypeRevolute:
             BuildDefaultPoseRevolute(joint_pose);
             break;
         case eJointTypePrismatic:
             BuildDefaultPosePrismatic(joint_pose);
             break;
         case eJointTypePlanar:
             BuildDefaultPosePlanar(joint_pose);
             break;
         case eJointTypeFixed:
             BuildDefaultPoseFixed(joint_pose);
             break;
         case eJointTypeSpherical:
             BuildDefaultPoseSpherical(joint_pose);
             break;
         default:
             assert(false); // unsupported joint type
             break;
         }
         SetJointParams(joint_mat, j, joint_pose, out_pose);
     }
 }
References BuildDefaultPoseFixed(), BuildDefaultPosePlanar(), BuildDefaultPosePrismatic(), BuildDefaultPoseRevolute(), BuildDefaultPoseRoot(), BuildDefaultPoseSpherical(), eJointTypeFixed, eJointTypePlanar, eJointTypePrismatic, eJointTypeRevolute, eJointTypeSpherical, GetJointType(), GetNumDof(), GetNumJoints(), GetRoot(), and SetJointParams().
Referenced by cCharacter::InitDefaultState().
BuildDefaultPoseFixed()
void cKinTree::BuildDefaultPoseFixed (Eigen::VectorXd & out_pose) static protected
Definition at line 1909 of file KinTree.cpp.
 {
     int dim = GetJointParamSize(eJointTypeFixed);
     out_pose = Eigen::VectorXd::Zero(dim);
 }
References eJointTypeFixed, and GetJointParamSize().
Referenced by BuildDefaultPose().
BuildDefaultPosePlanar()
void cKinTree::BuildDefaultPosePlanar (Eigen::VectorXd & out_pose) static protected
Definition at line 1903 of file KinTree.cpp.
 {
     int dim = GetJointParamSize(eJointTypePlanar);
     out_pose = Eigen::VectorXd::Zero(dim);
 }
References eJointTypePlanar, and GetJointParamSize().
Referenced by BuildDefaultPose().
BuildDefaultPosePrismatic()
void cKinTree::BuildDefaultPosePrismatic (Eigen::VectorXd & out_pose) static protected
Definition at line 1897 of file KinTree.cpp.
 {
     int dim = GetJointParamSize(eJointTypePrismatic);
     out_pose = Eigen::VectorXd::Zero(dim);
 }
References eJointTypePrismatic, and GetJointParamSize().
Referenced by BuildDefaultPose().
BuildDefaultPoseRevolute()
void cKinTree::BuildDefaultPoseRevolute (Eigen::VectorXd & out_pose) static protected
Definition at line 1891 of file KinTree.cpp.
 {
     int dim = GetJointParamSize(eJointTypeRevolute);
     out_pose = Eigen::VectorXd::Zero(dim);
 }
References eJointTypeRevolute, and GetJointParamSize().
Referenced by BuildDefaultPose().
BuildDefaultPoseRoot()
void cKinTree::BuildDefaultPoseRoot (const Eigen::MatrixXd & joint_mat, Eigen::VectorXd & out_pose) static protected
Definition at line 1884 of file KinTree.cpp.
 {
     int dim = gRootDim;
     out_pose = Eigen::VectorXd::Zero(dim);
     out_pose(gPosDim) = 1;
 }
References gPosDim, and gRootDim.
Referenced by BuildDefaultPose().
BuildDefaultPoseSpherical()
void cKinTree::BuildDefaultPoseSpherical (Eigen::VectorXd & out_pose) static protected
Definition at line 1915 of file KinTree.cpp.
 {
     int dim = GetJointParamSize(eJointTypeSpherical);
     out_pose = Eigen::VectorXd::Zero(dim);
     out_pose(0) = 1;
 }
References eJointTypeSpherical, and GetJointParamSize().
Referenced by BuildDefaultPose().
BuildDefaultVel()
void cKinTree::BuildDefaultVel (const Eigen::MatrixXd & joint_mat, Eigen::VectorXd & out_vel) static
Definition at line 1257 of file KinTree.cpp.
 {
     int num_dof = GetNumDof(joint_mat);
     out_vel = Eigen::VectorXd::Zero(num_dof);
     int num_joints = GetNumJoints(joint_mat);
     int root_id = GetRoot(joint_mat);
     Eigen::VectorXd root_pose;
     BuildDefaultVelRoot(joint_mat, root_pose);
     SetJointParams(joint_mat, root_id, root_pose, out_vel);
     for (int j = 1; j < num_joints; ++j)
     {
         eJointType joint_type = GetJointType(joint_mat, j);
         Eigen::VectorXd joint_pose;
         switch (joint_type)
         {
         case eJointTypeRevolute:
             BuildDefaultVelRevolute(joint_pose);
             break;
         case eJointTypePrismatic:
             BuildDefaultVelPrismatic(joint_pose);
             break;
         case eJointTypePlanar:
             BuildDefaultVelPlanar(joint_pose);
             break;
         case eJointTypeFixed:
             BuildDefaultVelFixed(joint_pose);
             break;
         case eJointTypeSpherical:
             BuildDefaultVelSpherical(joint_pose);
             break;
         default:
             assert(false); // unsupported joint type
             break;
         }
         SetJointParams(joint_mat, j, joint_pose, out_vel);
     }
 }
References BuildDefaultVelFixed(), BuildDefaultVelPlanar(), BuildDefaultVelPrismatic(), BuildDefaultVelRevolute(), BuildDefaultVelRoot(), BuildDefaultVelSpherical(), eJointTypeFixed, eJointTypePlanar, eJointTypePrismatic, eJointTypeRevolute, eJointTypeSpherical, GetJointType(), GetNumDof(), GetNumJoints(), GetRoot(), and SetJointParams().
Referenced by cCharacter::InitDefaultState().
BuildDefaultVelFixed()
void cKinTree::BuildDefaultVelFixed (Eigen::VectorXd & out_pose) static protected
Definition at line 1947 of file KinTree.cpp.
 {
     int dim = GetJointParamSize(eJointTypeFixed);
     out_pose = Eigen::VectorXd::Zero(dim);
 }
References eJointTypeFixed, and GetJointParamSize().
Referenced by BuildDefaultVel().
BuildDefaultVelPlanar()
void cKinTree::BuildDefaultVelPlanar (Eigen::VectorXd & out_pose) static protected
Definition at line 1941 of file KinTree.cpp.
 {
     int dim = GetJointParamSize(eJointTypePlanar);
     out_pose = Eigen::VectorXd::Zero(dim);
 }
References eJointTypePlanar, and GetJointParamSize().
Referenced by BuildDefaultVel().
BuildDefaultVelPrismatic()
void cKinTree::BuildDefaultVelPrismatic (Eigen::VectorXd & out_pose) static protected
Definition at line 1935 of file KinTree.cpp.
 {
     int dim = GetJointParamSize(eJointTypePrismatic);
     out_pose = Eigen::VectorXd::Zero(dim);
 }
References eJointTypePrismatic, and GetJointParamSize().
Referenced by BuildDefaultVel().
BuildDefaultVelRevolute()
void cKinTree::BuildDefaultVelRevolute (Eigen::VectorXd & out_pose) static protected
Definition at line 1929 of file KinTree.cpp.
 {
     int dim = GetJointParamSize(eJointTypeRevolute);
     out_pose = Eigen::VectorXd::Zero(dim);
 }
References eJointTypeRevolute, and GetJointParamSize().
Referenced by BuildDefaultVel().
BuildDefaultVelRoot()
void cKinTree::BuildDefaultVelRoot (const Eigen::MatrixXd & joint_mat, Eigen::VectorXd & out_pose) static protected
Definition at line 1923 of file KinTree.cpp.
 {
     int dim = gRootDim;
     out_pose = Eigen::VectorXd::Zero(dim);
 }
References gRootDim.
Referenced by BuildDefaultVel().
BuildDefaultVelSpherical()
void cKinTree::BuildDefaultVelSpherical (Eigen::VectorXd & out_pose) static protected
Definition at line 1953 of file KinTree.cpp.
 {
     int dim = GetJointParamSize(eJointTypeSpherical);
     out_pose = Eigen::VectorXd::Zero(dim);
 }
References eJointTypeSpherical, and GetJointParamSize().
Referenced by BuildDefaultVel().
BuildDrawShapeDef()
cKinTree::tDrawShapeDef cKinTree::BuildDrawShapeDef () static
Definition at line 1193 of file KinTree.cpp.
 {
     tDrawShapeDef def;
     def(eDrawShapeShape) = static_cast<double>(cShape::eShapeNull);
     def(eDrawShapeParentJoint) = gInvalidIdx;
     def(eDrawShapeAttachX) = 0;
     def(eDrawShapeAttachY) = 0;
     def(eDrawShapeAttachZ) = 0;
     def(eDrawShapeAttachThetaX) = 0;
     def(eDrawShapeAttachThetaY) = 0;
     def(eDrawShapeAttachThetaZ) = 0;
     def(eDrawShapeParam0) = 0;
     def(eDrawShapeParam1) = 0;
     def(eDrawShapeParam2) = 0;
     def(eDrawShapeColorR) = 0;
     def(eDrawShapeColorG) = 0;
     def(eDrawShapeColorB) = 0;
     def(eDrawShapeColorA) = 1;
     def(eDrawShapeMeshID) = gInvalidIdx;
     return def;
 }
References eDrawShapeAttachThetaX, eDrawShapeAttachThetaY, eDrawShapeAttachThetaZ, eDrawShapeAttachX, eDrawShapeAttachY, eDrawShapeAttachZ, eDrawShapeColorA, eDrawShapeColorB, eDrawShapeColorG, eDrawShapeColorR, eDrawShapeMeshID, eDrawShapeParam0, eDrawShapeParam1, eDrawShapeParam2, eDrawShapeParentJoint, eDrawShapeShape, cShape::eShapeNull, and gInvalidIdx.
Referenced by LoadDrawShapeDefs().
BuildHeadingTrans()
tMatrix cKinTree::BuildHeadingTrans (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose) static
Definition at line 1637 of file KinTree.cpp.
 {
     double heading = CalcHeading(joint_mat, pose);
     tVector axis = tVector(0, 1, 0, 0);
     tMatrix mat = cMathUtil::RotateMat(axis, -heading);
     return mat;
 }
References CalcHeading(), and cMathUtil::RotateMat().
Referenced by BuildOriginTrans().
BuildJointDesc() [1/2]
cKinTree::tJointDesc cKinTree::BuildJointDesc () static
Definition at line 1144 of file KinTree.cpp.
 {
     tJointDesc desc;
     desc(eJointDescType) = static_cast<double>(eJointTypeRevolute);
     desc(eJointDescParent) = gInvalidIdx;
     desc(eJointDescAttachX) = 0;
     desc(eJointDescAttachY) = 0;
     desc(eJointDescAttachZ) = 0;
     desc(eJointDescAttachThetaX) = 0;
     desc(eJointDescAttachThetaY) = 0;
     desc(eJointDescAttachThetaZ) = 0;
     desc(eJointDescLimLow0) = 1;
     desc(eJointDescLimLow1) = 1;
     desc(eJointDescLimLow2) = 1;
     desc(eJointDescLimHigh0) = 0;
     desc(eJointDescLimHigh1) = 0;
     desc(eJointDescLimHigh2) = 0;
     desc(eJointDescIsEndEffector) = 0;
     desc(eJointDescTorqueLim) = std::numeric_limits<double>::infinity();
     desc(eJointDescForceLim) = std::numeric_limits<double>::infinity();
     desc(eJointDescDiffWeight) = 1;
     desc(eJointDescParamOffset) = 0;
     return desc;
 }
References eJointDescAttachThetaX, eJointDescAttachThetaY, eJointDescAttachThetaZ, eJointDescAttachX, eJointDescAttachY, eJointDescAttachZ, eJointDescDiffWeight, eJointDescForceLim, eJointDescIsEndEffector, eJointDescLimHigh0, eJointDescLimHigh1, eJointDescLimHigh2, eJointDescLimLow0, eJointDescLimLow1, eJointDescLimLow2, eJointDescParamOffset, eJointDescParent, eJointDescTorqueLim, eJointDescType, eJointTypeRevolute, and gInvalidIdx.
Referenced by BuildJointDesc(), cBVHReader::BuildJointMat(), and ParseJoint().
BuildJointDesc() [2/2]
cKinTree::tJointDesc cKinTree::BuildJointDesc (eJointType joint_type, int parent_id, const tVector & attach_pt) static
Definition at line 1132 of file KinTree.cpp.
 {
     tJointDesc desc = BuildJointDesc();
     desc(eJointDescType) = static_cast<double>(joint_type);
     desc(eJointDescParent) = parent_id;
     desc(eJointDescAttachX) = attach_pt[0];
     desc(eJointDescAttachY) = attach_pt[1];
     desc(eJointDescAttachZ) = attach_pt[2];
     return desc;
 }
References BuildJointDesc(), eJointDescAttachX, eJointDescAttachY, eJointDescAttachZ, eJointDescParent, and eJointDescType.
BuildJointJson()
std::string cKinTree::BuildJointJson (int id, const tJointDesc & joint_desc) static
Definition at line 1772 of file KinTree.cpp.
 {
     std::string json = "";
     json += "{\n";
     json += "\"ID\": " + std::to_string(id);
     for (int i = 0; i < eJointDescMax; ++i)
     {
         std::string param_name = gJointDescKeys[i];
         if (i == eJointDescType)
         {
             json += ",\n";
             int type_id = static_cast<int>(joint_desc[i]);
             std::string type_str = gJointTypeNames[type_id];
             json += "\"" + param_name + "\": \"" + type_str + "\"";
         }
         else if (i != eJointDescParamOffset)
         {
             double val = joint_desc[i];
             if (!std::isfinite(val) && (i == eJointDescTorqueLim || i == eJointDescForceLim))
             {
                 continue;
             }
             if (i != 0)
             {
                 json += ",\n";
             }
             json += "\"" + param_name + "\": " + std::to_string(val);
         }
     }
     json += "\n}";
     return json;
 }
References eJointDescForceLim, eJointDescMax, eJointDescParamOffset, eJointDescTorqueLim, eJointDescType, gJointDescKeys, gJointTypeNames, and isfinite.
Referenced by BuildJointMatJson().
BuildJointMatJson()
std::string cKinTree::BuildJointMatJson (const Eigen::MatrixXd & joint_mat) static
Definition at line 1749 of file KinTree.cpp.
 {
     std::string json = "";
     json += "{\n\"" + gJointsKey + "\":\n[\n";
     int num_joints = GetNumJoints(joint_mat);
     for (int j = 0; j < num_joints; ++j)
     {
         tJointDesc curr_desc = joint_mat.row(j);
         std::string joint_json = BuildJointJson(j, curr_desc);
         if (j != 0)
         {
             json += ",\n";
         }
         json += joint_json;
     }
     json += "\n]\n}";
     return json;
 }
References BuildJointJson(), GetNumJoints(), and gJointsKey.
BuildOriginTrans()
tMatrix cKinTree::BuildOriginTrans (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose) static
Definition at line 1645 of file KinTree.cpp.
 {
     // world to origin transform
     // origin is the point right under the root of the character on the xz plane with x-axis
     // aligned along the character's heading
     tVector origin = GetRootPos(joint_mat, pose);
     origin[1] = 0;
     tMatrix rot_mat = BuildHeadingTrans(joint_mat, pose);
     tMatrix trans_mat = cMathUtil::TranslateMat(-origin);
     tMatrix mat = rot_mat * trans_mat;
     return mat;
 }
References BuildHeadingTrans(), GetRootPos(), and cMathUtil::TranslateMat().
Referenced by cCharacter::BuildOriginTrans().
CalcAABB()
void cKinTree::CalcAABB (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, tVector & out_min, tVector & out_max) static
Definition at line 756 of file KinTree.cpp.
 {
     out_min[0] = std::numeric_limits<double>::infinity();
     out_min[1] = std::numeric_limits<double>::infinity();
     out_min[2] = std::numeric_limits<double>::infinity();
     out_max[0] = -std::numeric_limits<double>::infinity();
     out_max[1] = -std::numeric_limits<double>::infinity();
     out_max[2] = -std::numeric_limits<double>::infinity();
     for (int i = 0; i < GetNumJoints(joint_desc); ++i)
     {
         tVector pos = CalcJointWorldPos(joint_desc, state, i);
         out_min = out_min.cwiseMin(pos);
         out_max = out_max.cwiseMax(pos);
     }
 }
References CalcJointWorldPos(), and GetNumJoints().
Referenced by cCharacter::CalcAABB().
CalcBodyPartPos()
tVector cKinTree::CalcBodyPartPos (const Eigen::MatrixXd & joint_mat, const Eigen::MatrixXd & body_defs, const Eigen::VectorXd & state, int part_id) static
Definition at line 275 of file KinTree.cpp.
 {
     assert(IsValidBody(body_defs, part_id));
     tMatrix body_joint_trans = BodyJointTrans(body_defs, part_id);
     tMatrix joint_to_world_trans = JointWorldTrans(joint_mat, state, part_id);
     tVector attach_pt = joint_to_world_trans * body_joint_trans.col(3);
     attach_pt[3] = 0;
     return attach_pt;
 }
References BodyJointTrans(), IsValidBody(), and JointWorldTrans().
CalcBodyPartRotation()
void cKinTree::CalcBodyPartRotation (const Eigen::MatrixXd & joint_mat, const Eigen::MatrixXd & body_defs, const Eigen::VectorXd & state, int part_id, tVector & out_axis, double & out_theta) static
Definition at line 430 of file KinTree.cpp.
 {
     tMatrix mat = BodyWorldTrans(joint_mat, body_defs, state, part_id);
     cMathUtil::RotMatToAxisAngle(mat, out_axis, out_theta);
 }
References BodyWorldTrans(), and cMathUtil::RotMatToAxisAngle().
CalcBodyPartVel()
tVector cKinTree::CalcBodyPartVel (const Eigen::MatrixXd & joint_mat, const Eigen::MatrixXd & body_defs, const Eigen::VectorXd & state, const Eigen::VectorXd & vel, int part_id) static
Definition at line 286 of file KinTree.cpp.
 {
     tVector attach_pt = cKinTree::GetBodyAttachPt(body_defs, part_id);
     return CalcWorldVel(joint_mat, state, vel, part_id, attach_pt);
 }
References CalcWorldVel(), and GetBodyAttachPt().
CalcChainLength()
double cKinTree::CalcChainLength (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXi & chain) static
Definition at line 721 of file KinTree.cpp.
 {
     double len = 0;
     int num_joints = static_cast<int>(chain.size());
     for (int i = 1; i < num_joints; ++i)
     {
         int curr_id = chain(i);
         int prev_id = chain(i - 1);
         if (prev_id != gInvalidJointID)
         {
             int prev_parent = GetParent(joint_mat, prev_id);
             bool is_parent = (prev_parent == curr_id);
             if (is_parent)
             {
                 double curr_len = CalcLinkLength(joint_mat, prev_id);
                 len += curr_len;
             }
         }
         if (curr_id != gInvalidJointID)
         {
             int curr_parent = GetParent(joint_mat, curr_id);
             bool is_child = (curr_parent == prev_id);
             if (is_child)
             {
                 double curr_len = CalcLinkLength(joint_mat, curr_id);
                 len += curr_len;
             }
         }
     }
     return len;
 }
References CalcLinkLength(), GetParent(), and gInvalidJointID.
Referenced by cCharacter::CalcJointChainLength().
CalcHeading()
double cKinTree::CalcHeading (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose) static
Definition at line 1621 of file KinTree.cpp.
 {
     // heading is the direction of the root in the xz plane
     tVector ref_dir = tVector(1, 0, 0, 0);
     tQuaternion root_rot = cKinTree::GetRootRot(joint_mat, pose);
     tVector rot_dir = cMathUtil::QuatRotVec(root_rot, ref_dir);
     double heading = std::atan2(-rot_dir[2], rot_dir[0]);
     return heading;
 }
References GetRootRot(), and cMathUtil::QuatRotVec().
Referenced by BuildHeadingTrans(), cCharacter::CalcHeading(), CalcHeadingRot(), and NormalizePoseHeading().
CalcHeadingRot()
tQuaternion cKinTree::CalcHeadingRot (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose) static
Definition at line 1631 of file KinTree.cpp.
 {
     double heading = CalcHeading(joint_mat, pose);
     return cMathUtil::AxisAngleToQuaternion(tVector(0, 1, 0, 0), heading);
 }
References cMathUtil::AxisAngleToQuaternion(), and CalcHeading().
Referenced by cCharacter::CalcHeadingRot().
CalcJointPoseDiff()
void cKinTree::CalcJointPoseDiff (const Eigen::MatrixXd & joint_mat, int joint_id, const Eigen::VectorXd & pose0, const Eigen::VectorXd & pose1, Eigen::VectorXd & out_diff) static protected
Definition at line 1441 of file KinTree.cpp.
 {
     int param_offset = GetParamOffset(joint_mat, joint_id);
     int param_size = GetParamSize(joint_mat, joint_id);
     bool is_root = cKinTree::IsRoot(joint_mat, joint_id);
     if (is_root)
     {
         tVector root_pos_diff = CalcRootPosDiff(joint_mat, pose0, pose1);
         tQuaternion root_rot_diff = CalcRootRotDiff(joint_mat, pose0, pose1);
         out_diff.resize(gRootDim);
         out_diff.segment(0, gPosDim) = root_pos_diff.segment(0, gPosDim);
         out_diff.segment(gPosDim, gRotDim) = cMathUtil::QuatToVec(root_rot_diff);
     }
     else
     {
         eJointType joint_type = GetJointType(joint_mat, joint_id);
         switch (joint_type)
         {
         case eJointTypeSpherical:
         {
             tQuaternion q0 = cMathUtil::VecToQuat(pose0.segment(param_offset, param_size));
             tQuaternion q1 = cMathUtil::VecToQuat(pose1.segment(param_offset, param_size));
             tQuaternion q_diff = cMathUtil::QuatDiff(q0, q1);
             out_diff = cMathUtil::QuatToVec(q_diff);
             break;
         }
         default:
             out_diff = pose1.segment(param_offset, param_size) - pose0.segment(param_offset, param_size);
             break;
         }
     }
 }
References CalcRootPosDiff(), CalcRootRotDiff(), eJointTypeSpherical, GetJointType(), GetParamOffset(), GetParamSize(), gPosDim, gRootDim, gRotDim, IsRoot(), cMathUtil::QuatDiff(), cMathUtil::QuatToVec(), and cMathUtil::VecToQuat().
Referenced by CalcPoseDiff(), and CalcPoseErr().
CalcJointVelDiff()
void cKinTree::CalcJointVelDiff (const Eigen::MatrixXd & joint_mat, int joint_id, const Eigen::VectorXd & vel0, const Eigen::VectorXd & vel1, Eigen::VectorXd & out_diff) static protected
Definition at line 1475 of file KinTree.cpp.
 {
     int param_offset = GetParamOffset(joint_mat, joint_id);
     int param_size = GetParamSize(joint_mat, joint_id);
     out_diff = vel1.segment(param_offset, param_size) - vel0.segment(param_offset, param_size);
 }
References GetParamOffset(), and GetParamSize().
Referenced by CalcVelDiff(), and CalcVelErr().
CalcJointWorldAngularVel()
tVector cKinTree::CalcJointWorldAngularVel (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, const Eigen::VectorXd & vel, int joint_id) static
Definition at line 599 of file KinTree.cpp.
 {
     return CalcWorldAngularVel(joint_mat, state, vel, joint_id, tVector::Zero());
 }
References CalcWorldAngularVel().
CalcJointWorldPos()
tVector cKinTree::CalcJointWorldPos (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int joint_id) static
Definition at line 555 of file KinTree.cpp.
 {
     tVector pos = LocalToWorldPos(joint_mat, state, joint_id, tVector::Zero());
     return pos;
 }
References LocalToWorldPos().
Referenced by CalcAABB(), cCharacter::CalcJointPos(), and cSceneImitate::CalcRewardImitate().
CalcJointWorldRot()
tQuaternion cKinTree::CalcJointWorldRot (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int joint_id) static
Definition at line 572 of file KinTree.cpp.
 {
     tMatrix mat = JointWorldTrans(joint_mat, state, joint_id);
     return cMathUtil::RotMatToQuaternion(mat);
 }
References JointWorldTrans(), and cMathUtil::RotMatToQuaternion().
CalcJointWorldTheta()
void cKinTree::CalcJointWorldTheta (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int joint_id, tVector & out_axis, double & out_theta) static
Definition at line 578 of file KinTree.cpp.
 {
     tMatrix mat = JointWorldTrans(joint_mat, state, joint_id);
     cMathUtil::RotMatToAxisAngle(mat, out_axis, out_theta);
 }
References JointWorldTrans(), and cMathUtil::RotMatToAxisAngle().
Referenced by cCharacter::CalcJointWorldRotation().
CalcJointWorldVel()
tVector cKinTree::CalcJointWorldVel (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, const Eigen::VectorXd & vel, int joint_id) static
Definition at line 585 of file KinTree.cpp.
 {
     return CalcWorldVel(joint_mat, state, vel, joint_id, tVector::Zero());
 }
References CalcWorldVel().
Referenced by cCharacter::CalcJointVel().
CalcLinkLength()
double cKinTree::CalcLinkLength (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 905 of file KinTree.cpp.
 {
     tVector attach_pt = GetAttachPt(joint_mat, joint_id);
     bool is_root = IsRoot(joint_mat, joint_id);
     double len = (is_root) ? 0 : attach_pt.norm();
     return len;
 }
References GetAttachPt(), and IsRoot().
Referenced by CalcChainLength(), and CalcMaxSubChainLengths().
CalcMaxSubChainLengths()
void cKinTree::CalcMaxSubChainLengths (const Eigen::MatrixXd & joint_mat, Eigen::VectorXd & out_lengths) static
Definition at line 929 of file KinTree.cpp.
 {
     int num_joints = static_cast<int>(joint_mat.rows());
     out_lengths = Eigen::VectorXd::Zero(num_joints);
     for (int j = num_joints - 1; j >= 0; --j)
     {
         int parent_id = GetParent(joint_mat, j);
         if (parent_id != gInvalidJointID)
         {
             double curr_val = out_lengths(j);
             double len = CalcLinkLength(joint_mat, j);
             double& parent_val = out_lengths(parent_id);
             if (parent_val < len + curr_val)
             {
                 parent_val = len + curr_val;
             }
         }
     }
 }
References CalcLinkLength(), GetParent(), and gInvalidJointID.
CalcPoseDiff()
void cKinTree::CalcPoseDiff (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose0, const Eigen::VectorXd & pose1, Eigen::VectorXd & out_diff) static
Definition at line 1299 of file KinTree.cpp.
 {
     int num_joints = GetNumJoints(joint_mat);
     assert(out_diff.size() == pose0.size());
     assert(pose1.size() == pose0.size());
     out_diff.resize(pose1.size());
     for (int j = 0; j < num_joints; ++j)
     {
         Eigen::VectorXd curr_diff;
         CalcJointPoseDiff(joint_mat, j, pose0, pose1, curr_diff);
         int param_offset = GetParamOffset(joint_mat, j);
         int param_size = GetParamSize(joint_mat, j);
         out_diff.segment(param_offset, param_size) = curr_diff;
     }
 }
References CalcJointPoseDiff(), GetNumJoints(), GetParamOffset(), and GetParamSize().
CalcPoseErr()
double cKinTree::CalcPoseErr (const Eigen::MatrixXd & joint_mat, int joint_id, const Eigen::VectorXd & pose0, const Eigen::VectorXd & pose1) static
Definition at line 1331 of file KinTree.cpp.
 {
     bool is_root = IsRoot(joint_mat, joint_id);
     double err = 0;
     if (is_root)
     {
         double root_pos_err = CalcRootPosErr(joint_mat, pose0, pose1);
         double root_rot_err = CalcRootRotErr(joint_mat, pose0, pose1);
         err = root_pos_err + root_rot_err;
     }
     else
     {
         Eigen::VectorXd diff;
         CalcJointPoseDiff(joint_mat, joint_id, pose0, pose1, diff);
         eJointType joint_type = GetJointType(joint_mat, joint_id);
         switch (joint_type)
         {
         case eJointTypeSpherical:
         {
             tQuaternion dq = cMathUtil::VecToQuat(diff);
             double theta = cMathUtil::QuatTheta(dq);
             err = theta * theta;
             break;
         }
         default:
             err = diff.squaredNorm();
             break;
         }
     }
     return err;
 }
References CalcJointPoseDiff(), CalcRootPosErr(), CalcRootRotErr(), eJointTypeSpherical, GetJointType(), IsRoot(), cMathUtil::QuatTheta(), and cMathUtil::VecToQuat().
Referenced by cSceneImitate::CalcRewardImitate().
CalcRootAngVelDiff()
tVector cKinTree::CalcRootAngVelDiff (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose0, const Eigen::VectorXd & pose1) static
Definition at line 1402 of file KinTree.cpp.
 {
     tVector root_ang_vel0 = GetRootAngVel(joint_mat, pose0);
     tVector root_ang_vel1 = GetRootAngVel(joint_mat, pose1);
     return root_ang_vel1 - root_ang_vel0;
 }
References GetRootAngVel().
Referenced by CalcRootAngVelErr().
CalcRootAngVelErr()
double cKinTree::CalcRootAngVelErr (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & vel0, const Eigen::VectorXd & vel1) static
Definition at line 1434 of file KinTree.cpp.
 {
     tVector diff = CalcRootAngVelDiff(joint_mat, vel0, vel1);
     return diff.squaredNorm();
 }
References CalcRootAngVelDiff().
Referenced by cSceneImitate::CalcRewardImitate(), and CalcVelErr().
CalcRootPosDiff()
tVector cKinTree::CalcRootPosDiff (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose0, const Eigen::VectorXd & pose1) static
Definition at line 1317 of file KinTree.cpp.
 {
     tVector root_pos0 = GetRootPos(joint_mat, pose0);
     tVector root_pos1 = GetRootPos(joint_mat, pose1);
     return root_pos1 - root_pos0;
 }
References GetRootPos().
Referenced by CalcJointPoseDiff(), and CalcRootPosErr().
CalcRootPosErr()
double cKinTree::CalcRootPosErr (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose0, const Eigen::VectorXd & pose1) static
Definition at line 1364 of file KinTree.cpp.
 {
     tVector diff = CalcRootPosDiff(joint_mat, pose0, pose1);
     return diff.squaredNorm();
 }
References CalcRootPosDiff().
Referenced by CalcPoseErr().
CalcRootRotDiff()
tQuaternion cKinTree::CalcRootRotDiff (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose0, const Eigen::VectorXd & pose1) static
Definition at line 1324 of file KinTree.cpp.
 {
     tQuaternion root_rot0 = GetRootRot(joint_mat, pose0);
     tQuaternion root_rot1 = GetRootRot(joint_mat, pose1);
     return cMathUtil::QuatDiff(root_rot0, root_rot1);
 }
References GetRootRot(), and cMathUtil::QuatDiff().
Referenced by CalcJointPoseDiff(), and CalcRootRotErr().
CalcRootRotErr()
double cKinTree::CalcRootRotErr (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose0, const Eigen::VectorXd & pose1) static
Definition at line 1370 of file KinTree.cpp.
 {
     tQuaternion diff = CalcRootRotDiff(joint_mat, pose0, pose1);
     double theta = cMathUtil::QuatTheta(diff);
     return theta * theta;
 }
References CalcRootRotDiff(), and cMathUtil::QuatTheta().
Referenced by CalcPoseErr(), and cSceneImitate::CalcRewardImitate().
CalcRootVelDiff()
tVector cKinTree::CalcRootVelDiff (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose0, const Eigen::VectorXd & pose1) static
Definition at line 1395 of file KinTree.cpp.
 {
     tVector root_vel0 = GetRootVel(joint_mat, pose0);
     tVector root_vel1 = GetRootVel(joint_mat, pose1);
     return root_vel1 - root_vel0;
 }
References GetRootVel().
Referenced by CalcRootVelErr().
CalcRootVelErr()
double cKinTree::CalcRootVelErr (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & vel0, const Eigen::VectorXd & vel1) static
Definition at line 1428 of file KinTree.cpp.
 {
     tVector diff = CalcRootVelDiff(joint_mat, vel0, vel1);
     return diff.squaredNorm();
 }
References CalcRootVelDiff().
Referenced by CalcVelErr().
CalcSubTreeMasses()
void cKinTree::CalcSubTreeMasses (const Eigen::MatrixXd & joint_mat, const Eigen::MatrixXd & body_defs, Eigen::VectorXd & out_masses) static
Definition at line 951 of file KinTree.cpp.
 {
     int num_joints = static_cast<int>(joint_mat.rows());
     out_masses = Eigen::VectorXd::Zero(num_joints);
     for (int j = num_joints - 1; j >= 0; --j)
     {
         double& curr_val = out_masses(j);
         double mass = GetBodyMass(body_defs, j);
         curr_val += mass;
         int parent_id = GetParent(joint_mat, j);
         if (parent_id != gInvalidJointID)
         {
             double& parent_val = out_masses(parent_id);
             parent_val += curr_val;
         }
     }
 }
References GetBodyMass(), GetParent(), and gInvalidJointID.
CalcTotalMass()
double cKinTree::CalcTotalMass (const Eigen::MatrixXd & body_defs) static
Definition at line 356 of file KinTree.cpp.
 {
     double total_mass = 0;
     for (int i = 0; i < body_defs.rows(); ++i)
     {
         if (IsValidBody(body_defs, i))
         {
             double mass = cKinTree::GetBodyMass(body_defs, i);
             total_mass += mass;
         }
     }
     return total_mass;
 }
References GetBodyMass(), and IsValidBody().
Referenced by cRBDUtil::BuildCOMJacobian(), and cRBDUtil::BuildCOMVelProdAccAux().
CalcVel()
void cKinTree::CalcVel (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose0, const Eigen::VectorXd & pose1, double dt, Eigen::VectorXd & out_vel) static
Definition at line 1482 of file KinTree.cpp.
 {
     assert(pose0.size() == pose1.size());
     out_vel.resize(pose0.size());
     int num_joints = GetNumJoints(joint_mat);
     tVector root_pos0 = GetRootPos(joint_mat, pose0);
     tVector root_pos1 = GetRootPos(joint_mat, pose1);
     tVector root_vel = (root_pos1 - root_pos0) / dt;
     tQuaternion root_rot0 = GetRootRot(joint_mat, pose0);
     tQuaternion root_rot1 = GetRootRot(joint_mat, pose1);
     tVector root_rot_vel = cMathUtil::CalcQuaternionVel(root_rot0, root_rot1, dt);
     cKinTree::SetRootVel(joint_mat, root_vel, out_vel);
     cKinTree::SetRootAngVel(joint_mat, root_rot_vel, out_vel);
     for (int j = 1; j < num_joints; ++j)
     {
         int param_offset = GetParamOffset(joint_mat, j);
         int param_size = GetParamSize(joint_mat, j);
         eJointType joint_type = GetJointType(joint_mat, j);
         switch (joint_type)
         {
         case eJointTypeSpherical:
         {
             tQuaternion q0 = cMathUtil::VecToQuat(pose0.segment(param_offset, param_size));
             tQuaternion q1 = cMathUtil::VecToQuat(pose1.segment(param_offset, param_size));
             tVector rot_vel = cMathUtil::CalcQuaternionVelRel(q0, q1, dt);
             out_vel.segment(param_offset, param_size) = rot_vel.segment(0, param_size);
             break;
         }
         default:
             out_vel.segment(param_offset, param_size) = (pose1.segment(param_offset, param_size) - pose0.segment(param_offset, param_size)) / dt;
             break;
         }
     }
 }
References cMathUtil::CalcQuaternionVel(), cMathUtil::CalcQuaternionVelRel(), eJointTypeSpherical, GetJointType(), GetNumJoints(), GetParamOffset(), GetParamSize(), GetRootPos(), GetRootRot(), SetRootAngVel(), SetRootVel(), and cMathUtil::VecToQuat().
Referenced by cImpPDController::CalcControlForces(), and cKinCharacter::CalcFrameVel().
CalcVelDiff()
void cKinTree::CalcVelDiff (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & vel0, const Eigen::VectorXd & vel1, Eigen::VectorXd & out_diff) static
Definition at line 1378 of file KinTree.cpp.
 {
     int num_joints = GetNumJoints(joint_mat);
     assert(vel0.size() == vel1.size());
     out_diff.resize(vel0.size());
     for (int j = 0; j < num_joints; ++j)
     {
         Eigen::VectorXd curr_diff;
         CalcJointVelDiff(joint_mat, j, vel0, vel1, curr_diff);
         int param_offset = GetParamOffset(joint_mat, j);
         int param_size = GetParamSize(joint_mat, j);
         out_diff.segment(param_offset, param_size) = curr_diff;
     }
 }
References CalcJointVelDiff(), GetNumJoints(), GetParamOffset(), and GetParamSize().
CalcVelErr()
double cKinTree::CalcVelErr (const Eigen::MatrixXd & joint_mat, int joint_id, const Eigen::VectorXd & vel0, const Eigen::VectorXd & vel1) static
Definition at line 1409 of file KinTree.cpp.
 {
     bool is_root = IsRoot(joint_mat, joint_id);
     double err = 0;
     if (is_root)
     {
         double root_vel_err = CalcRootVelErr(joint_mat, vel0, vel1);
         double root_ang_vel_err = CalcRootAngVelErr(joint_mat, vel0, vel1);
         err = root_vel_err + root_ang_vel_err;
     }
     else
     {
         Eigen::VectorXd diff;
         CalcJointVelDiff(joint_mat, joint_id, vel0, vel1, diff);
         err = diff.squaredNorm();
     }
     return err;
 }
References CalcJointVelDiff(), CalcRootAngVelErr(), CalcRootVelErr(), and IsRoot().
Referenced by cSceneImitate::CalcRewardImitate().
CalcWorldAngularVel()
tVector cKinTree::CalcWorldAngularVel (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, const Eigen::VectorXd & vel, int parent_id, const tVector & attach_pt) static
Definition at line 604 of file KinTree.cpp.
 {
     cSpAlg::tSpVec sv = cRBDUtil::CalcWorldVel(joint_mat, state, vel, parent_id);
     tVector pos = cKinTree::LocalToWorldPos(joint_mat, state, parent_id, attach_pt);
     cSpAlg::tSpTrans world_to_pt = cSpAlg::BuildTrans(pos);
     sv = cSpAlg::ApplyTransM(world_to_pt, sv);
     return cSpAlg::GetOmega(sv);
 }
References cSpAlg::ApplyTransM(), cSpAlg::BuildTrans(), cRBDUtil::CalcWorldVel(), cSpAlg::GetOmega(), and LocalToWorldPos().
Referenced by CalcJointWorldAngularVel().
CalcWorldVel()
tVector cKinTree::CalcWorldVel (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, const Eigen::VectorXd & vel, int parent_id, const tVector & attach_pt) static
Definition at line 590 of file KinTree.cpp.
 {
     cSpAlg::tSpVec sv = cRBDUtil::CalcWorldVel(joint_mat, state, vel, parent_id);
     tVector pos = cKinTree::LocalToWorldPos(joint_mat, state, parent_id, attach_pt);
     cSpAlg::tSpTrans world_to_pt = cSpAlg::BuildTrans(pos);
     sv = cSpAlg::ApplyTransM(world_to_pt, sv);
     return cSpAlg::GetV(sv);
 }
References cSpAlg::ApplyTransM(), cSpAlg::BuildTrans(), cRBDUtil::CalcWorldVel(), cSpAlg::GetV(), and LocalToWorldPos().
Referenced by CalcBodyPartVel(), and CalcJointWorldVel().
ChildParentTrans()
tMatrix cKinTree::ChildParentTrans (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int joint_id) static
Definition at line 1046 of file KinTree.cpp.
 {
     tMatrix mat;
     eJointType j_type = GetJointType(joint_mat, joint_id);
     bool is_root = IsRoot(joint_mat, joint_id);
     if (is_root)
     {
         mat = ChildParentTransRoot(joint_mat, state, joint_id);
     }
     else
     {
         switch (j_type)
         {
         case eJointTypeRevolute:
             mat = ChildParentTransRevolute(joint_mat, state, joint_id);
             break;
         case eJointTypePrismatic:
             mat = ChildParentTransPrismatic(joint_mat, state, joint_id);
             break;
         case eJointTypePlanar:
             mat = ChildParentTransPlanar(joint_mat, state, joint_id);
             break;
         case eJointTypeFixed:
             mat = ChildParentTransFixed(joint_mat, state, joint_id);
             break;
         case eJointTypeSpherical:
             mat = ChildParentTransSpherical(joint_mat, state, joint_id);
             break;
         default:
             break;
         }
     }
     return mat;
 }
References ChildParentTransFixed(), ChildParentTransPlanar(), ChildParentTransPrismatic(), ChildParentTransRevolute(), ChildParentTransRoot(), ChildParentTransSpherical(), eJointTypeFixed, eJointTypePlanar, eJointTypePrismatic, eJointTypeRevolute, eJointTypeSpherical, GetJointType(), and IsRoot().
Referenced by cRBDUtil::BuildChildParentTransform(), cDrawKinTree::DrawTree(), JointWorldTrans(), ParentChildTrans(), and cRBDModel::UpdateChildParentMatArr().
ChildParentTransFixed()
tMatrix cKinTree::ChildParentTransFixed (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int joint_id) static protected
Definition at line 1849 of file KinTree.cpp.
 {
     tMatrix A = BuildAttachTrans(joint_mat, joint_id);
     tMatrix mat = A;
     return mat;
 }
References BuildAttachTrans().
Referenced by ChildParentTrans().
ChildParentTransPlanar()
tMatrix cKinTree::ChildParentTransPlanar (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int joint_id) static protected
Definition at line 1833 of file KinTree.cpp.
 {
     int param_offset = cKinTree::GetParamOffset(joint_mat, joint_id);
     double theta = state(param_offset + 2);
     tVector offset = tVector::Zero();
     offset[0] = state(param_offset);
     offset[1] = state(param_offset + 1);
     tMatrix A = BuildAttachTrans(joint_mat, joint_id);
     tMatrix R = cMathUtil::RotateMat(tVector(0, 0, 1, 0), theta);
     tMatrix T = cMathUtil::TranslateMat(offset);
     tMatrix mat = A * R * T;
     return mat;
 }
References BuildAttachTrans(), GetParamOffset(), cMathUtil::RotateMat(), and cMathUtil::TranslateMat().
Referenced by ChildParentTrans().
ChildParentTransPrismatic()
tMatrix cKinTree::ChildParentTransPrismatic (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int joint_id) static protected
Definition at line 1856 of file KinTree.cpp.
 {
     int param_offset = cKinTree::GetParamOffset(joint_mat, joint_id);
     tVector offset = tVector::Zero();
     offset[0] = state(param_offset);
     tMatrix A = BuildAttachTrans(joint_mat, joint_id);
     tMatrix T = cMathUtil::TranslateMat(offset);
     tMatrix mat = A * T;
     return mat;
 }
References BuildAttachTrans(), GetParamOffset(), and cMathUtil::TranslateMat().
Referenced by ChildParentTrans().
ChildParentTransRevolute()
tMatrix cKinTree::ChildParentTransRevolute (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int joint_id) static protected
Definition at line 1821 of file KinTree.cpp.
 {
     int param_offset = cKinTree::GetParamOffset(joint_mat, joint_id);
     double theta = state(param_offset);
     tMatrix A = BuildAttachTrans(joint_mat, joint_id);
     tMatrix R = cMathUtil::RotateMat(tVector(0, 0, 1, 0), theta);
     tMatrix mat = A * R;
     return mat;
 }
References BuildAttachTrans(), GetParamOffset(), and cMathUtil::RotateMat().
Referenced by ChildParentTrans().
ChildParentTransRoot()
tMatrix cKinTree::ChildParentTransRoot (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int joint_id) static protected
Definition at line 1808 of file KinTree.cpp.
 {
     tVector offset = GetRootPos(joint_mat, state);
     tQuaternion rot = GetRootRot(joint_mat, state);
     tMatrix A = BuildAttachTrans(joint_mat, joint_id);
     tMatrix R = cMathUtil::RotateMat(rot);
     tMatrix T = cMathUtil::TranslateMat(offset);
     tMatrix mat = A * T * R;
     return mat;
 }
References BuildAttachTrans(), GetRootPos(), GetRootRot(), cMathUtil::RotateMat(), and cMathUtil::TranslateMat().
Referenced by ChildParentTrans().
ChildParentTransSpherical()
tMatrix cKinTree::ChildParentTransSpherical (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int joint_id) static protected
Definition at line 1869 of file KinTree.cpp.
 {
     int param_offset = cKinTree::GetParamOffset(joint_mat, joint_id);
     int param_size = cKinTree::GetParamSize(joint_mat, joint_id);
     tQuaternion q = cMathUtil::VecToQuat(state.segment(param_offset, param_size));
     tMatrix A = BuildAttachTrans(joint_mat, joint_id);
     tMatrix R = cMathUtil::RotateMat(q);
     tMatrix mat = A * R;
     return mat;
 }
References BuildAttachTrans(), GetParamOffset(), GetParamSize(), cMathUtil::RotateMat(), and cMathUtil::VecToQuat().
Referenced by ChildParentTrans().
FindChildren()
void cKinTree::FindChildren (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXi & out_children) static
Definition at line 97 of file KinTree.cpp.
 {
     const int max_size = 128;
     int children_buffer[max_size];
     int num_children = 0;
     int num_joints = GetNumJoints(joint_desc);
     for (int i = 0; i < num_joints; ++i)
     {
         int parent = GetParent(joint_desc, i);
         if (parent == joint_id)
         {
             children_buffer[num_children] = i;
             ++num_children;
             if (num_children >= max_size)
             {
                 printf("Too many children, max = %i", max_size);
                 assert(false);
                 return;
             }
         }
     }
     out_children.resize(num_children);
     for (int i = 0; i < num_children; ++i)
     {
         out_children[i] = children_buffer[i];
     }
 }
References GetNumJoints(), and GetParent().
Referenced by cDrawKinTree::DrawTree().
FindJointChain()
Eigen::VectorXi cKinTree::FindJointChain (const Eigen::MatrixXd & joint_mat, int joint_beg, int joint_end) static
Definition at line 633 of file KinTree.cpp.
 {
     Eigen::VectorXi chain;
     const int max_length = 128;
     int chain_buffer[max_length];
     int buffer_idx = 0;
     if (joint_beg == joint_end)
     {
         Eigen::VectorXi chain(1);
         chain[0] = joint_beg;
     }
     int common_ancestor = gInvalidJointID;
     int curr_id = joint_beg;
     int end_len = 0;
     while (curr_id != gInvalidJointID)
     {
         chain_buffer[buffer_idx] = curr_id;
         ++buffer_idx;
         if (buffer_idx >= max_length)
         {
             printf("Exceeded maximum chain length %i\n", max_length);
             assert(false);
             return chain;
         }
         bool is_ancestor = IsAncestor(joint_mat, joint_end, curr_id, end_len);
         if (is_ancestor)
         {
             common_ancestor = curr_id;
             break;
         }
         else
         {
             curr_id = GetParent(joint_mat, curr_id);
         }
     }
     bool found = common_ancestor != gInvalidJointID;
     // tree should always connected?
     assert(found);
     if (found)
     {
         chain.resize(buffer_idx + end_len);
         for (int i = 0; i < buffer_idx; ++i)
         {
             chain[i] = chain_buffer[i];
         }
         int idx = buffer_idx;
         curr_id = joint_end;
         while (curr_id != common_ancestor)
         {
             chain[idx] = curr_id;
             curr_id = GetParent(joint_mat, curr_id);
             ++idx;
         }
         int num_flips = static_cast<int>(chain.size()) - buffer_idx;
         chain.block(buffer_idx, 0, num_flips, 1).reverseInPlace();
     }
     return chain;
 }
References GetParent(), gInvalidJointID, and IsAncestor().
Referenced by cCharacter::CalcJointChainLength().
GetAttachPt()
tVector cKinTree::GetAttachPt (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 913 of file KinTree.cpp.
 {
     tVector attach_pt = tVector(joint_mat(joint_id, cKinTree::eJointDescAttachX),
                                 joint_mat(joint_id, cKinTree::eJointDescAttachY),
                                 joint_mat(joint_id, cKinTree::eJointDescAttachZ), 0);
     return attach_pt;
 }
References eJointDescAttachX, eJointDescAttachY, and eJointDescAttachZ.
Referenced by BuildAttachTrans(), cSimCharacter::BuildJoints(), cSimCharacter::BuildMultiBody(), cSimCharacter::CalcJointPos(), cSimCharacter::CalcJointVel(), CalcLinkLength(), and cDrawKinTree::DrawTree().
GetAttachTheta()
tVector cKinTree::GetAttachTheta (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 921 of file KinTree.cpp.
 {
     tVector attach_theta = tVector(joint_mat(joint_id, cKinTree::eJointDescAttachThetaX),
                                     joint_mat(joint_id, cKinTree::eJointDescAttachThetaY),
                                     joint_mat(joint_id, cKinTree::eJointDescAttachThetaZ), 0);
     return attach_theta;
 }
References eJointDescAttachThetaX, eJointDescAttachThetaY, and eJointDescAttachThetaZ.
Referenced by BuildAttachTrans(), cSimCharacter::BuildJoints(), cSimCharacter::BuildMultiBody(), and cSimCharacter::BuildSimBody().
GetBodyAttachPt()
tVector cKinTree::GetBodyAttachPt (const Eigen::MatrixXd & body_defs, int part_id) static
Definition at line 298 of file KinTree.cpp.
 {
     const cKinTree::tBodyDef& def = body_defs.row(part_id);
     tVector attach_pt = tVector(def(eBodyParamAttachX), def(eBodyParamAttachY), def(eBodyParamAttachZ), 0);
     return attach_pt;
 }
References eBodyParamAttachX, eBodyParamAttachY, and eBodyParamAttachZ.
Referenced by BodyJointTrans(), cSimCharacter::BuildJoints(), cSimCharacter::BuildMultiBody(), CalcBodyPartVel(), cRBDUtil::CalcCoM(), cSimCharacter::CalcJointPos(), and cSimCharacter::CalcJointVel().
GetBodyAttachTheta()
tVector cKinTree::GetBodyAttachTheta (const Eigen::MatrixXd & body_defs, int part_id) static
Definition at line 305 of file KinTree.cpp.
 {
     tVector attach_theta = tVector(body_defs(part_id, eBodyParamAttachThetaX),
                                     body_defs(part_id, eBodyParamAttachThetaY),
                                     body_defs(part_id, eBodyParamAttachThetaZ), 0);
     return attach_theta;
 }
References eBodyParamAttachThetaX, eBodyParamAttachThetaY, and eBodyParamAttachThetaZ.
Referenced by BodyJointTrans(), cSimCharacter::BuildJoints(), cSimCharacter::BuildMultiBody(), and GetBodyRotation().
GetBodyColGroup()
int cKinTree::GetBodyColGroup (const Eigen::MatrixXd & body_defs, int part_id) static
Definition at line 325 of file KinTree.cpp.
 {
     int col_group = static_cast<int>(body_defs(part_id, eBodyParamColGroup));
     return col_group;
 }
References eBodyParamColGroup.
Referenced by cSimCharacter::GetPartColMask().
GetBodyColor()
tVector cKinTree::GetBodyColor (const Eigen::MatrixXd & body_defs, int part_id) static
Definition at line 349 of file KinTree.cpp.
 {
     const tBodyDef& def = body_defs.row(part_id);
     tVector col = tVector(def(eBodyColorR), def(eBodyColorG), def(eBodyColorB), def(eBodyColorA));
     return col;
 }
References eBodyColorA, eBodyColorB, eBodyColorG, and eBodyColorR.
Referenced by cSimCharacter::GetPartColor().
GetBodyEnableFallContact()
bool cKinTree::GetBodyEnableFallContact (const Eigen::MatrixXd & body_defs, int part_id) static
Definition at line 331 of file KinTree.cpp.
 {
     double fall_val = body_defs(part_id, eBodyParamEnableFallContact);
     return fall_val != 0;
 }
References eBodyParamEnableFallContact.
Referenced by cSimCharacter::EnableBodyPartFallContact().
GetBodyLocalCoM()
tVector cKinTree::GetBodyLocalCoM (const Eigen::MatrixXd & body_defs, int part_id) static
Definition at line 380 of file KinTree.cpp.
 {
     cShape::eShape shape = GetBodyShape(body_defs, part_id);
     tVector com = tVector::Zero();
     switch (shape)
     {
     case cShape::eShapeBox:
     case cShape::eShapeCapsule:
     case cShape::eShapeSphere:
     case cShape::eShapeCylinder:
         break;
     default:
         assert(false); // unsupported
         break;
     }
     return com;
 }
References cShape::eShapeBox, cShape::eShapeCapsule, cShape::eShapeCylinder, cShape::eShapeSphere, and GetBodyShape().
Referenced by BodyJointTrans(), and cRBDUtil::CalcCoM().
GetBodyMass()
double cKinTree::GetBodyMass (const Eigen::MatrixXd & body_defs, int part_id) static
Definition at line 319 of file KinTree.cpp.
 {
     double mass = body_defs(part_id, eBodyParamMass);
     return mass;
 }
References eBodyParamMass.
Referenced by cSimCharacter::BuildBodyLinks(), cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildCOMVelProdAccAux(), cRBDUtil::BuildMomentInertiaBox(), cRBDUtil::BuildMomentInertiaCapsule(), cRBDUtil::BuildMomentInertiaCylinder(), cRBDUtil::BuildMomentInertiaSphere(), cSimCharacter::BuildMultiBody(), cRBDUtil::CalcCoM(), CalcSubTreeMasses(), and CalcTotalMass().
GetBodyRotation()
void cKinTree::GetBodyRotation (const Eigen::MatrixXd & body_defs, int part_id, tVector & out_axis, double & out_theta) static
Definition at line 313 of file KinTree.cpp.
 {
     tVector theta = GetBodyAttachTheta(body_defs, part_id);
     cMathUtil::EulerToAxisAngle(theta, out_axis, out_theta);
 }
References cMathUtil::EulerToAxisAngle(), and GetBodyAttachTheta().
GetBodyShape()
cShape::eShape cKinTree::GetBodyShape (const Eigen::MatrixXd & body_defs, int part_id) static
Definition at line 292 of file KinTree.cpp.
 {
     cShape::eShape shape = static_cast<cShape::eShape>(static_cast<int>(body_defs(part_id, cKinTree::eBodyParamShape)));
     return shape;
 }
References eBodyParamShape.
Referenced by cRBDUtil::BuildMomentInertia(), cSimCharacter::BuildMultiBody(), GetBodyLocalCoM(), and IsValidBody().
GetBodySize()
tVector cKinTree::GetBodySize (const Eigen::MatrixXd & body_defs, int part_id) static
Definition at line 342 of file KinTree.cpp.
 {
     const tBodyDef& def = body_defs.row(part_id);
     tVector size = tVector(def(eBodyParam0), def(eBodyParam1), def(eBodyParam2), 0);
     return size;
 }
References eBodyParam0, eBodyParam1, and eBodyParam2.
Referenced by cSimCharacter::BuildMultiBody().
GetDrawShapeAttachPt()
tVector cKinTree::GetDrawShapeAttachPt (const tDrawShapeDef & shape) static
Definition at line 404 of file KinTree.cpp.
 {
     return tVector(shape[eDrawShapeAttachX], shape[eDrawShapeAttachY], shape[cKinTree::eDrawShapeAttachZ], 0);
 }
References eDrawShapeAttachX, eDrawShapeAttachY, and eDrawShapeAttachZ.
Referenced by cDrawCharacter::DrawShapeBox(), cDrawCharacter::DrawShapeCapsule(), cDrawCharacter::DrawShapeCylinder(), cDrawCharacter::DrawShapeMesh(), and cDrawCharacter::DrawShapeSphere().
GetDrawShapeAttachTheta()
tVector cKinTree::GetDrawShapeAttachTheta (const tDrawShapeDef & shape) static
Definition at line 409 of file KinTree.cpp.
 {
     return tVector(shape[eDrawShapeAttachThetaX], shape[eDrawShapeAttachThetaY], shape[eDrawShapeAttachThetaZ], 0);
 }
References eDrawShapeAttachThetaX, eDrawShapeAttachThetaY, and eDrawShapeAttachThetaZ.
Referenced by cDrawCharacter::DrawShapeBox(), cDrawCharacter::DrawShapeMesh(), and GetDrawShapeRotation().
GetDrawShapeColor()
tVector cKinTree::GetDrawShapeColor (const tDrawShapeDef & shape) static
Definition at line 420 of file KinTree.cpp.
 {
     return tVector(shape[eDrawShapeColorR], shape[eDrawShapeColorG], shape[eDrawShapeColorB], shape[cKinTree::eDrawShapeColorA]);
 }
References eDrawShapeColorA, eDrawShapeColorB, eDrawShapeColorG, and eDrawShapeColorR.
Referenced by cDrawCharacter::DrawShapeBox(), cDrawCharacter::DrawShapeCapsule(), cDrawCharacter::DrawShapeCylinder(), cDrawCharacter::DrawShapeMesh(), and cDrawCharacter::DrawShapeSphere().
GetDrawShapeMeshID()
int cKinTree::GetDrawShapeMeshID (const tDrawShapeDef & shape) static
Definition at line 425 of file KinTree.cpp.
 {
     return static_cast<int>(shape[eDrawShapeMeshID]);
 }
References eDrawShapeMeshID.
Referenced by cDrawCharacter::DrawCharShapes(), and cDrawCharacter::DrawPoseCharShapes().
GetDrawShapeParentJoint()
int cKinTree::GetDrawShapeParentJoint (const tDrawShapeDef & shape) static
Definition at line 399 of file KinTree.cpp.
 {
     return static_cast<int>(shape[eDrawShapeParentJoint]);
 }
References eDrawShapeParentJoint.
Referenced by cDrawCharacter::DrawCharShapes(), cDrawCharacter::DrawPoseCharShapes(), cDrawCharacter::DrawShapeBox(), cDrawCharacter::DrawShapeCapsule(), cDrawCharacter::DrawShapeCylinder(), cDrawCharacter::DrawShapeMesh(), and cDrawCharacter::DrawShapeSphere().
GetDrawShapeRotation()
void cKinTree::GetDrawShapeRotation (const tDrawShapeDef & shape, tVector & out_axis, double & out_theta) static
Definition at line 414 of file KinTree.cpp.
 {
     tVector theta = GetDrawShapeAttachTheta(shape);
     cMathUtil::EulerToAxisAngle(theta, out_axis, out_theta);
 }
References cMathUtil::EulerToAxisAngle(), and GetDrawShapeAttachTheta().
Referenced by cDrawCharacter::DrawShapeCapsule(), cDrawCharacter::DrawShapeCylinder(), and cDrawCharacter::DrawShapeSphere().
GetForceLimit()
double cKinTree::GetForceLimit (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 874 of file KinTree.cpp.
 {
     double force_lim = joint_mat(joint_id, cKinTree::eJointDescForceLim);
     return force_lim;
 }
References eJointDescForceLim.
Referenced by cCtCtrlUtil::BuildBoundsTorque(), cSimCharacter::BuildJoints(), and cCtCtrlUtil::BuildOffsetScaleTorque().
GetJointDiffWeight()
double cKinTree::GetJointDiffWeight (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 900 of file KinTree.cpp.
 {
     return joint_mat(joint_id, cKinTree::eJointDescDiffWeight);
 }
References eJointDescDiffWeight.
Referenced by cCharacter::GetJointDiffWeight().
GetJointLimHigh()
tVector cKinTree::GetJointLimHigh (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 893 of file KinTree.cpp.
 {
     return tVector(joint_mat(joint_id, cKinTree::eJointDescLimHigh0),
                     joint_mat(joint_id, cKinTree::eJointDescLimHigh1),
                     joint_mat(joint_id, cKinTree::eJointDescLimHigh2), 0);
 }
References eJointDescLimHigh0, eJointDescLimHigh1, and eJointDescLimHigh2.
Referenced by cCtCtrlUtil::BuildBoundsPDPlanar(), cCtCtrlUtil::BuildBoundsPDPrismatic(), cCtCtrlUtil::BuildBoundsPDRevolute(), cCtCtrlUtil::BuildBoundsPDSpherical(), cSimCharacter::BuildConstraints(), cSimCharacter::BuildJoints(), cCtCtrlUtil::BuildOffsetScalePDPlanar(), cCtCtrlUtil::BuildOffsetScalePDPrismatic(), cCtCtrlUtil::BuildOffsetScalePDRevolute(), and cCtCtrlUtil::BuildOffsetScalePDSpherical().
GetJointLimLow()
tVector cKinTree::GetJointLimLow (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 886 of file KinTree.cpp.
 {
     return tVector(joint_mat(joint_id, cKinTree::eJointDescLimLow0),
                     joint_mat(joint_id, cKinTree::eJointDescLimLow1),
                     joint_mat(joint_id, cKinTree::eJointDescLimLow2), 1);
 }
References eJointDescLimLow0, eJointDescLimLow1, and eJointDescLimLow2.
Referenced by cCtCtrlUtil::BuildBoundsPDPlanar(), cCtCtrlUtil::BuildBoundsPDPrismatic(), cCtCtrlUtil::BuildBoundsPDRevolute(), cCtCtrlUtil::BuildBoundsPDSpherical(), cSimCharacter::BuildConstraints(), cSimCharacter::BuildJoints(), cCtCtrlUtil::BuildOffsetScalePDPlanar(), cCtCtrlUtil::BuildOffsetScalePDPrismatic(), cCtCtrlUtil::BuildOffsetScalePDRevolute(), and cCtCtrlUtil::BuildOffsetScalePDSpherical().
GetJointParams()
void cKinTree::GetJointParams (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int j, Eigen::VectorXd & out_params) static
Definition at line 816 of file KinTree.cpp.
 {
     int offset = GetParamOffset(joint_mat, j);
     int dim = GetParamSize(joint_mat, j);
     if (dim > 0)
     {
         out_params = state.block(offset, 0, dim, 1);
     }
     else
     {
         out_params = Eigen::VectorXd::Zero(1);
     }
 }
References GetParamOffset(), and GetParamSize().
Referenced by cRBDUtil::BuildCjRoot(), cRBDUtil::BuildJacobianDot(), cRBDUtil::CalcVelProdAcc(), cRBDUtil::MultJacobianEndEff(), and cRBDUtil::SolveInvDyna().
GetJointParamSize()
int cKinTree::GetJointParamSize (eJointType joint_type) static
Definition at line 788 of file KinTree.cpp.
 {
     int size = 0;
     switch (joint_type)
     {
     case eJointTypeRevolute:
         size = 1;
         break;
     case eJointTypePrismatic:
         size = 1;
         break;
     case eJointTypePlanar:
         size = 3;
         break;
     case eJointTypeFixed:
         size = 0;
         break;
     case eJointTypeSpherical:
         size = 4;
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
     return size;
 }
References eJointTypeFixed, eJointTypePlanar, eJointTypePrismatic, eJointTypeRevolute, and eJointTypeSpherical.
Referenced by BuildDefaultPoseFixed(), BuildDefaultPosePlanar(), BuildDefaultPosePrismatic(), BuildDefaultPoseRevolute(), BuildDefaultPoseSpherical(), BuildDefaultVelFixed(), BuildDefaultVelPlanar(), BuildDefaultVelPrismatic(), BuildDefaultVelRevolute(), BuildDefaultVelSpherical(), cBVHReader::BuildJointPoseFixed(), cBVHReader::BuildJointPosePlanar(), cBVHReader::BuildJointPosePrismatic(), cBVHReader::BuildJointPoseRevolute(), cBVHReader::BuildJointPoseSpherical(), cRBDUtil::BuildJointSubspaceFixed(), cRBDUtil::BuildJointSubspacePlanar(), cRBDUtil::BuildJointSubspacePrismatic(), cRBDUtil::BuildJointSubspaceRevolute(), cRBDUtil::BuildJointSubspaceSpherical(), cBVHReader::tJointData::CalcPoseDim(), cSimBodyJoint::GetParamSize(), cSimJoint::GetParamSize(), and GetParamSize().
GetJointType()
cKinTree::eJointType cKinTree::GetJointType (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 838 of file KinTree.cpp.
 {
     eJointType type = static_cast<eJointType>(static_cast<int>(joint_mat(joint_id, cKinTree::eJointDescType)));
     return type;
 }
References eJointDescType.
Referenced by cCtCtrlUtil::BuildBoundsPD(), cCtCtrlUtil::BuildBoundsPDFixed(), cCtCtrlUtil::BuildBoundsPDPlanar(), cCtCtrlUtil::BuildBoundsPDPrismatic(), cCtCtrlUtil::BuildBoundsPDRevolute(), cCtCtrlUtil::BuildBoundsPDSpherical(), cCtCtrlUtil::BuildBoundsTorque(), cCtCtrlUtil::BuildBoundsVel(), cRBDUtil::BuildCj(), cSimCharacter::BuildConsFactor(), cSimCharacter::BuildConstraints(), BuildDefaultPose(), BuildDefaultVel(), cRBDUtil::BuildJointSubspace(), cSimCharacter::BuildMultiBody(), cCtCtrlUtil::BuildOffsetScalePD(), cCtCtrlUtil::BuildOffsetScalePDFixed(), cCtCtrlUtil::BuildOffsetScalePDPlanar(), cCtCtrlUtil::BuildOffsetScalePDPrismatic(), cCtCtrlUtil::BuildOffsetScalePDRevolute(), cCtCtrlUtil::BuildOffsetScalePDSpherical(), cCtCtrlUtil::BuildOffsetScaleTorque(), cCtCtrlUtil::BuildOffsetScaleVel(), CalcJointPoseDiff(), CalcPoseErr(), CalcVel(), ChildParentTrans(), cSimCharacter::FixedBase(), GetParamSize(), LerpPoses(), MirrorPoseStance(), PostProcessPose(), cSimCharacter::SetPose(), cSimCharacter::SetVel(), and VelToPoseDiff().
GetNumDof()
int cKinTree::GetNumDof (const Eigen::MatrixXd & joint_mat) static
Definition at line 618 of file KinTree.cpp.
 {
     int num_joints = GetNumJoints(joint_mat);
     int num_dof = cKinTree::GetParamOffset(joint_mat, num_joints - 1) + cKinTree::GetParamSize(joint_mat, num_joints - 1);
     return num_dof;
 }
References GetNumJoints(), GetParamOffset(), and GetParamSize().
Referenced by cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildCOMVelProdAccAux(), BuildDefaultPose(), BuildDefaultVel(), cRBDUtil::BuildEndEffectorJacobian(), cRBDUtil::BuildJacobianDot(), cSimCharacter::BuildPose(), cSimCharacter::BuildVel(), cRBDUtil::CalcGravityForce(), cRBDModel::GetNumDof(), cCharacter::GetNumDof(), and cRBDUtil::SolveInvDyna().
GetNumJoints()
int cKinTree::GetNumJoints (const Eigen::MatrixXd & joint_mat) static
Definition at line 613 of file KinTree.cpp.
 {
     return static_cast<int>(joint_mat.rows());
 }
Referenced by ApplyStep(), cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildCOMVelProdAccAux(), BuildDefaultPose(), BuildDefaultVel(), cRBDUtil::BuildJacobian(), cRBDUtil::BuildJacobianDot(), BuildJointMatJson(), CalcAABB(), cRBDUtil::CalcCoM(), cRBDUtil::CalcGravityForce(), CalcPoseDiff(), CalcVel(), CalcVelDiff(), cRBDUtil::CalcWorldJointTransforms(), FindChildren(), GetNumDof(), cRBDModel::GetNumJoints(), cCharacter::GetNumJoints(), LerpPoses(), MirrorPoseStance(), PostProcessJointMat(), PostProcessPose(), cRBDUtil::SolveInvDyna(), and VelToPoseDiff().
GetParamOffset()
int cKinTree::GetParamOffset (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 774 of file KinTree.cpp.
 {
     int offset = static_cast<int>(joint_mat(joint_id, eJointDescParamOffset));
     return offset;
 }
References eJointDescParamOffset.
Referenced by cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildEndEffectorJacobian(), cRBDUtil::BuildJacobian(), cRBDUtil::BuildJacobianDot(), cRBDUtil::BuildMassMat(), CalcJointPoseDiff(), CalcJointVelDiff(), CalcPoseDiff(), CalcVel(), CalcVelDiff(), cRBDUtil::CalcVelProdAcc(), ChildParentTransPlanar(), ChildParentTransPrismatic(), ChildParentTransRevolute(), ChildParentTransSpherical(), cRBDUtil::ExtractEndEffJacobian(), GetJointParams(), cRBDModel::GetJointSubspace(), GetNumDof(), cCharacter::GetParamOffset(), GetRootAngVel(), GetRootPos(), GetRootRot(), GetRootVel(), cRBDModel::InitJointSubspaceArr(), LerpPoses(), MirrorPoseStance(), cRBDUtil::MultJacobianEndEff(), PostProcessPose(), SetJointParams(), SetRootAngVel(), SetRootPos(), SetRootRot(), SetRootVel(), cRBDModel::UpdateJointSubspaceArr(), and VelToPoseDiff().
GetParamSize()
int cKinTree::GetParamSize (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 780 of file KinTree.cpp.
 {
     eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     bool is_root = cKinTree::IsRoot(joint_mat, joint_id);
     int size = (is_root) ? gRootDim : GetJointParamSize(joint_type);
     return size;
 }
References GetJointParamSize(), GetJointType(), gRootDim, and IsRoot().
Referenced by cCtCtrlUtil::BuildBoundsPDFixed(), cCtCtrlUtil::BuildBoundsPDPlanar(), cCtCtrlUtil::BuildBoundsPDPrismatic(), cCtCtrlUtil::BuildBoundsPDRevolute(), cCtCtrlUtil::BuildBoundsPDSpherical(), cCtCtrlUtil::BuildBoundsTorque(), cCtCtrlUtil::BuildBoundsVel(), cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildEndEffectorJacobian(), cRBDUtil::BuildJacobian(), cRBDUtil::BuildJacobianDot(), cRBDUtil::BuildMassMat(), cCtCtrlUtil::BuildOffsetScalePDFixed(), cCtCtrlUtil::BuildOffsetScalePDPlanar(), cCtCtrlUtil::BuildOffsetScalePDPrismatic(), cCtCtrlUtil::BuildOffsetScalePDRevolute(), cCtCtrlUtil::BuildOffsetScalePDSpherical(), cCtCtrlUtil::BuildOffsetScaleTorque(), cCtCtrlUtil::BuildOffsetScaleVel(), CalcJointPoseDiff(), CalcJointVelDiff(), CalcPoseDiff(), CalcVel(), CalcVelDiff(), cRBDUtil::CalcVelProdAcc(), ChildParentTransSpherical(), cRBDUtil::ExtractEndEffJacobian(), GetJointParams(), cRBDModel::GetJointSubspace(), GetNumDof(), cCharacter::GetParamSize(), cRBDModel::InitJointSubspaceArr(), LerpPoses(), MirrorPoseStance(), cRBDUtil::MultJacobianEndEff(), PostProcessJointMat(), SetJointParams(), cRBDModel::UpdateJointSubspaceArr(), and VelToPoseDiff().
GetParent()
int cKinTree::GetParent (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 844 of file KinTree.cpp.
 {
     int parent = static_cast<int>(joint_mat(joint_id, cKinTree::eJointDescParent));
     assert(parent < joint_id); // joints should always be ordered as such
                                 // since some algorithms will assume this ordering
     return parent;
 }
References eJointDescParent.
Referenced by cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildEndEffectorJacobian(), cRBDUtil::BuildJacobianDot(), cSimCharacter::BuildJoints(), cRBDUtil::BuildMassMat(), cSimCharacter::BuildMultiBody(), CalcChainLength(), cRBDUtil::CalcGravityForce(), cSimCharacter::CalcJointPos(), cSimCharacter::CalcJointVel(), cSimCharacter::CalcJointWorldRotation(), CalcMaxSubChainLengths(), CalcSubTreeMasses(), cRBDUtil::CalcVelProdAcc(), cRBDUtil::CalcWorldJointTransforms(), cRBDUtil::ExtractEndEffJacobian(), FindChildren(), FindJointChain(), cRBDModel::GetParent(), cCharacter::GetParentJoint(), HasParent(), IsAncestor(), JointWorldTrans(), cRBDUtil::MultJacobianEndEff(), and cRBDUtil::SolveInvDyna().
GetRoot()
int cKinTree::GetRoot (const Eigen::MatrixXd & joint_mat) static
Definition at line 91 of file KinTree.cpp.
 {
     // this should always be true right?
     return 0;
 }
Referenced by ApplyStep(), BuildDefaultPose(), BuildDefaultVel(), cDrawKinTree::Draw(), GetRootAngVel(), cCharacter::GetRootID(), GetRootPos(), GetRootRot(), GetRootVel(), HasValidRoot(), LerpPoses(), PostProcessJointMat(), PostProcessPose(), cSimCharacter::SetPose(), SetRootAngVel(), SetRootPos(), SetRootRot(), SetRootVel(), cSimCharacter::SetVel(), and VelToPoseDiff().
GetRootAngVel()
tVector cKinTree::GetRootAngVel (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & vel) static
Definition at line 539 of file KinTree.cpp.
 {
     int root_id = GetRoot(joint_mat);
     tVector ang_vel = tVector::Zero();
     int param_offset = GetParamOffset(joint_mat, root_id);
     ang_vel.segment(0, gRotDim) = vel.segment(param_offset + gPosDim, gRotDim);
     return ang_vel;
 }
References GetParamOffset(), GetRoot(), gPosDim, and gRotDim.
Referenced by cRBDUtil::BuildCjRoot(), cSceneImitate::CalcRewardImitate(), CalcRootAngVelDiff(), NormalizePoseHeading(), cKinCharacter::RotateOrigin(), cSimCharacter::SetRootTransform(), cSimCharacter::SetVel(), VelToPoseDiff(), and cCharacter::WriteState().
GetRootPos()
tVector cKinTree::GetRootPos (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state) static
Definition at line 492 of file KinTree.cpp.
 {
     int root_id = GetRoot(joint_mat);
     tVector pos = tVector::Zero();
     int param_offset = GetParamOffset(joint_mat, root_id);
     pos.segment(0, gPosDim) = state.segment(param_offset, gPosDim);
     return pos;
 }
References GetParamOffset(), GetRoot(), and gPosDim.
Referenced by BuildOriginTrans(), cKinCharacter::CalcCycleRootDelta(), cKinCharacter::CalcPose(), cSceneImitate::CalcRewardImitate(), CalcRootPosDiff(), CalcVel(), ChildParentTransRoot(), cCharacter::GetRootPos(), LerpPoses(), MirrorPoseStance(), cKinCharacter::MoveOrigin(), NormalizePoseHeading(), cSimCharacter::SetPose(), and cCharacter::WriteState().
GetRootRot()
tQuaternion cKinTree::GetRootRot (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state) static
Definition at line 508 of file KinTree.cpp.
 {
     int root_id = GetRoot(joint_mat);
     int param_offset = GetParamOffset(joint_mat, root_id);
     tQuaternion rot = cMathUtil::VecToQuat(state.segment(param_offset + gPosDim, gRotDim));
     return rot;
 }
References GetParamOffset(), GetRoot(), gPosDim, gRotDim, and cMathUtil::VecToQuat().
Referenced by cRBDUtil::BuildCjRoot(), cRBDUtil::BuildJointSubspaceRoot(), CalcHeading(), cKinCharacter::CalcPose(), cSceneImitate::CalcRewardImitate(), CalcRootRotDiff(), CalcVel(), ChildParentTransRoot(), cCharacter::GetRootRotation(), LerpPoses(), MirrorPoseStance(), NormalizePoseHeading(), cKinCharacter::RotateOrigin(), cSimCharacter::SetPose(), cSimCharacter::SetRootTransform(), VelToPoseDiff(), and cCharacter::WriteState().
GetRootVel()
tVector cKinTree::GetRootVel (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & vel) static
Definition at line 523 of file KinTree.cpp.
 {
     int root_id = GetRoot(joint_mat);
     tVector pos = tVector::Zero();
     int param_offset = GetParamOffset(joint_mat, root_id);
     pos.segment(0, gPosDim) = vel.segment(param_offset, gPosDim);
     return pos;
 }
References GetParamOffset(), GetRoot(), and gPosDim.
Referenced by cRBDUtil::BuildCjRoot(), cSceneImitate::CalcRewardImitate(), CalcRootVelDiff(), NormalizePoseHeading(), cKinCharacter::RotateOrigin(), cSimCharacter::SetRootTransform(), cSimCharacter::SetVel(), and cCharacter::WriteState().
GetTorqueLimit()
double cKinTree::GetTorqueLimit (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 868 of file KinTree.cpp.
 {
     double torque_lim = joint_mat(joint_id, cKinTree::eJointDescTorqueLim);
     return torque_lim;
 }
References eJointDescTorqueLim.
Referenced by cCtCtrlUtil::BuildBoundsTorque(), cSimCharacter::BuildJoints(), and cCtCtrlUtil::BuildOffsetScaleTorque().
HasParent()
bool cKinTree::HasParent (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 852 of file KinTree.cpp.
 {
     int parent = GetParent(joint_mat, joint_id);
     return parent != gInvalidJointID;
 }
References GetParent(), and gInvalidJointID.
Referenced by cRBDUtil::BuildMassMat(), cRBDUtil::CalcGravityForce(), cDrawKinTree::DrawTree(), IsRoot(), and cRBDUtil::SolveInvDyna().
HasValidRoot()
bool cKinTree::HasValidRoot (const Eigen::MatrixXd & joint_mat) static
Definition at line 486 of file KinTree.cpp.
 {
     int root = GetRoot(joint_desc);
     return root != gInvalidJointID;
 }
References GetRoot(), and gInvalidJointID.
IsAncestor()
bool cKinTree::IsAncestor (const Eigen::MatrixXd & joint_mat, int child_joint, int ancestor_joint, int & out_len) static
Definition at line 702 of file KinTree.cpp.
 {
     int curr_id = child_joint;
     out_len = 0;
     while (curr_id != gInvalidJointID)
     {
         if (curr_id == ancestor_joint)
         {
             return true;
         }
         else
         {
             curr_id = GetParent(joint_mat, curr_id);
             ++out_len;
         }
     }
     return false;
 }
References GetParent(), and gInvalidJointID.
Referenced by FindJointChain().
IsEndEffector()
bool cKinTree::IsEndEffector (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 880 of file KinTree.cpp.
 {
     double end_eff_val = joint_mat(joint_id, cKinTree::eJointDescIsEndEffector);
     return end_eff_val != 0;
 }
References eJointDescIsEndEffector.
Referenced by cCharacter::IsEndEffector().
IsJointActuated()
bool cKinTree::IsJointActuated (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 863 of file KinTree.cpp.
 {
     return !IsRoot(joint_mat, joint_id);
 }
References IsRoot().
IsRoot()
bool cKinTree::IsRoot (const Eigen::MatrixXd & joint_mat, int joint_id) static
Definition at line 858 of file KinTree.cpp.
 {
     return !HasParent(joint_mat, joint_id);
 }
References HasParent().
Referenced by cRBDUtil::BuildCj(), cSimCharacter::BuildConsFactor(), cSimCharacter::BuildJointPose(), cSimCharacter::BuildJoints(), cRBDUtil::BuildJointSubspace(), cSimCharacter::BuildJointVel(), cSimCharacter::BuildMultiBody(), CalcJointPoseDiff(), CalcLinkLength(), CalcPoseErr(), CalcVelErr(), ChildParentTrans(), GetParamSize(), cRBDUtil::IsConstJointSubspace(), IsJointActuated(), and MirrorPoseStance().
IsValidBody()
bool cKinTree::IsValidBody (const Eigen::MatrixXd & body_defs, int part_id) static
Definition at line 370 of file KinTree.cpp.
 {
     cShape::eShape shape = GetBodyShape(body_defs, part_id);
     if (shape != cShape::eShapeNull)
     {
         return true;
     }
     return false;
 }
References cShape::eShapeNull, and GetBodyShape().
Referenced by cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildCOMVelProdAccAux(), cRBDUtil::BuildMassMat(), cRBDUtil::BuildMomentInertia(), CalcBodyPartPos(), cRBDUtil::CalcCoM(), cRBDUtil::CalcGravityForce(), CalcTotalMass(), and cRBDUtil::SolveInvDyna().
JointWorldTrans()
tMatrix cKinTree::JointWorldTrans (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int joint_id) static
Definition at line 1090 of file KinTree.cpp.
 {
     tMatrix m = tMatrix::Identity();
     int curr_id = joint_id;
     assert(joint_id != gInvalidIdx); // invalid joint
     while (curr_id != gInvalidJointID)
     {
         tMatrix child_parent_mat = ChildParentTrans(joint_mat, state, curr_id);
         m = child_parent_mat * m;
         curr_id = GetParent(joint_mat, curr_id);
     }
     return m;
 }
References ChildParentTrans(), GetParent(), gInvalidIdx, and gInvalidJointID.
Referenced by BodyWorldTrans(), cCharacter::BuildJointWorldTrans(), CalcBodyPartPos(), cRBDUtil::CalcCoM(), CalcJointWorldRot(), CalcJointWorldTheta(), cDrawCharacter::DrawPoseCharShapes(), LocalToWorldPos(), and WorldJointTrans().
LerpPoses()
void cKinTree::LerpPoses (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose0, const Eigen::VectorXd & pose1, double lerp, Eigen::VectorXd & out_pose) static
Definition at line 1541 of file KinTree.cpp.
 {
     int num_joints = GetNumJoints(joint_mat);
     int root_id = GetRoot(joint_mat);
     int root_offset = GetParamOffset(joint_mat, root_id);
     out_pose.resize(pose0.size());
     assert(pose0.size() == pose1.size());
     tVector root_pos0 = GetRootPos(joint_mat, pose0);
     tVector root_pos1 = GetRootPos(joint_mat, pose1);
     tVector root_pos_lerp = (1 - lerp) * root_pos0 + lerp * root_pos1;
     tQuaternion root_rot0 = GetRootRot(joint_mat, pose0);
     tQuaternion root_rot1 = GetRootRot(joint_mat, pose1);
     assert(std::abs(root_rot0.norm() - 1) < 0.000001);
     assert(std::abs(root_rot1.norm() - 1) < 0.000001);
     tQuaternion root_rot_lerp = root_rot0.slerp(lerp, root_rot1);
     root_rot_lerp.normalize();
     cKinTree::SetRootPos(joint_mat, root_pos_lerp, out_pose);
     cKinTree::SetRootRot(joint_mat, root_rot_lerp, out_pose);
     for (int j = 1; j < num_joints; ++j)
     {
         eJointType joint_type = GetJointType(joint_mat, j);
         int offset = GetParamOffset(joint_mat, j);
         int size = GetParamSize(joint_mat, j);
         if (joint_type == eJointTypeSpherical)
         {
             tQuaternion rot0 = cMathUtil::VecToQuat(pose0.segment(offset, size));
             tQuaternion rot1 = cMathUtil::VecToQuat(pose1.segment(offset, size));
             assert(std::abs(rot0.norm() - 1) < 0.000001);
             assert(std::abs(rot1.norm() - 1) < 0.000001);
             tQuaternion rot_lerp = rot0.slerp(lerp, rot1);
             out_pose.segment(offset, size) = cMathUtil::QuatToVec(rot_lerp).segment(0, size);
         }
         else
         {
             out_pose.segment(offset, size) = (1 - lerp) * pose0.segment(offset, size) + lerp * pose1.segment(offset, size);
         }
     }
 }
References eJointTypeSpherical, GetJointType(), GetNumJoints(), GetParamOffset(), GetParamSize(), GetRoot(), GetRootPos(), GetRootRot(), cMathUtil::QuatToVec(), SetRootPos(), SetRootRot(), and cMathUtil::VecToQuat().
Referenced by cKinCharacter::BlendFrames().
Load()
bool cKinTree::Load (const Json::Value & root, Eigen::MatrixXd & out_joint_mat) static
Definition at line 436 of file KinTree.cpp.
 {
     bool succ = false;
     if (!root[gJointsKey].isNull())
     {
         Json::Value joints = root[gJointsKey];
         int num_joints = joints.size();
         out_joint_mat.resize(num_joints, eJointDescMax);
         for (int j = 0; j < num_joints; ++j)
         {
             tJointDesc curr_joint_desc = tJointDesc::Zero();
             Json::Value joint_json = joints.get(j, 0);
             succ = ParseJoint(joint_json, curr_joint_desc);
             if (succ)
             {
                 out_joint_mat.row(j) = curr_joint_desc;
             }
             else
             {
                 printf("Failed to parse joint %i\n", j);
                 return false;
             }
         }
         for (int j = 0; j < num_joints; ++j)
         {
             const auto& curr_desc = out_joint_mat.row(j);
             int parent_id = static_cast<int>(curr_desc(eJointDescParent));
             if (parent_id >= j)
             {
                 printf("Parent id must be < child id, parent id: %i, child id: %i\n", parent_id, j);
                 out_joint_mat.resize(0, 0);
                 assert(false);
                 return false;
             }
             out_joint_mat.row(j) = curr_desc;
         }
         PostProcessJointMat(out_joint_mat);
     }
     return succ;
 }
References eJointDescMax, eJointDescParent, Json::Value::get(), gJointsKey, ParseJoint(), PostProcessJointMat(), and Json::Value::size().
Referenced by cCharacter::LoadSkeleton().
LoadBodyDefs()
bool cKinTree::LoadBodyDefs (const std::string & char_file, Eigen::MatrixXd & out_body_defs) static
Definition at line 128 of file KinTree.cpp.
 {
     bool succ = true;
     std::string str;
     std::ifstream f_stream(char_file.c_str());
     Json::Value root;
     Json::Reader reader;
     succ = reader.parse(f_stream, root);
     f_stream.close();
     if (succ)
     {
         succ = false;
         if (!root[gBodyDefsKey].isNull())
         {
             Json::Value body_defs = root.get(gBodyDefsKey, 0);
             int num_bodies = body_defs.size();
             succ = true;
             out_body_defs.resize(num_bodies, eBodyParamMax);
             for (int b = 0; b < num_bodies; ++b)
             {
                 tBodyDef curr_def = BuildBodyDef();
                 Json::Value body_json = body_defs.get(b, 0);
                 bool succ_def = ParseBodyDef(body_json, curr_def);
                 if (succ)
                 {
                     out_body_defs.row(b) = curr_def;
                 }
                 else
                 {
                     succ = false;
                     break;
                 }
             }
         }
     }
     if (!succ)
     {
         printf("Failed to load body definition from %s\n", char_file.c_str());
         succ = false;
     }
     return succ;
 }
References BuildBodyDef(), eBodyParamMax, gBodyDefsKey, Json::Value::get(), Json::Reader::parse(), ParseBodyDef(), and Json::Value::size().
Referenced by cSimCharacter::LoadBodyDefs().
LoadDrawShapeDefs()
bool cKinTree::LoadDrawShapeDefs (const std::string & char_file, Eigen::MatrixXd & out_draw_defs) static
Definition at line 202 of file KinTree.cpp.
 {
     bool succ = true;
     std::string str;
     std::ifstream f_stream(char_file.c_str());
     Json::Value root;
     Json::Reader reader;
     succ = reader.parse(f_stream, root);
     f_stream.close();
     if (succ)
     {
         if (!root[gDrawShapeDefsKey].isNull())
         {
             Json::Value shape_defs = root.get(gDrawShapeDefsKey, 0);
             int num_shapes = shape_defs.size();
             succ = true;
             out_draw_defs.resize(num_shapes, eDrawShapeParamMax);
             for (int b = 0; b < num_shapes; ++b)
             {
                 tDrawShapeDef curr_def = BuildDrawShapeDef();
                 Json::Value shape_json = shape_defs.get(b, 0);
                 bool succ_def = ParseDrawShapeDef(shape_json, curr_def);
                 if (succ)
                 {
                     out_draw_defs.row(b) = curr_def;
                 }
                 else
                 {
                     succ = false;
                     break;
                 }
             }
         }
     }
     if (!succ)
     {
         printf("Failed to load draw shape definition from %s\n", char_file.c_str());
         assert(false);
     }
     return succ;
 }
References BuildDrawShapeDef(), eDrawShapeParamMax, gDrawShapeDefsKey, Json::Value::get(), Json::Reader::parse(), ParseDrawShapeDef(), and Json::Value::size().
Referenced by cCharacter::LoadDrawShapeDefs().
LocalToWorldPos()
tVector cKinTree::LocalToWorldPos (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int parent_id, const tVector & attach_pt) static
Definition at line 561 of file KinTree.cpp.
 {
     tMatrix local_to_world_trans = JointWorldTrans(joint_mat, state, parent_id);
     tVector pos = attach_pt;
     pos[3] = 1;
     pos = local_to_world_trans * pos;
     pos[3] = 0;
     return pos;
 }
References JointWorldTrans().
Referenced by CalcJointWorldPos(), CalcWorldAngularVel(), and CalcWorldVel().
MirrorPoseStance()
void cKinTree::MirrorPoseStance (const Eigen::MatrixXd & joint_mat, const std::vector< int > mirror_joints0, const std::vector< int > mirror_joints1, Eigen::VectorXd & out_pose) static
Definition at line 1691 of file KinTree.cpp.
 {
     // mirrors along xy plane
     assert(mirror_joints0.size() == mirror_joints1.size());
     int num_joints = cKinTree::GetNumJoints(joint_mat);
     tQuaternion root_rot = cKinTree::GetRootRot(joint_mat, out_pose);
     tVector root_pos = cKinTree::GetRootPos(joint_mat, out_pose);
     root_pos[2] *= -1;
     root_rot = cMathUtil::MirrorQuaternion(root_rot, cMathUtil::eAxisZ);
     cKinTree::SetRootRot(joint_mat, root_rot, out_pose);
     cKinTree::SetRootPos(joint_mat, root_pos, out_pose);
     for (int j = 0; j < num_joints; ++j)
     {
         cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, j);
         bool is_root = cKinTree::IsRoot(joint_mat, j);
         if (!is_root)
         {
             int param_offset = cKinTree::GetParamOffset(joint_mat, j);
             int param_size = cKinTree::GetParamSize(joint_mat, j);
             auto joint_params = out_pose.segment(param_offset, param_size);
             if (joint_type == cKinTree::eJointTypeRevolute
                 || joint_type == cKinTree::eJointTypeFixed)
             {
             }
             else if (joint_type == cKinTree::eJointTypeSpherical)
             {
                 tQuaternion quat = cMathUtil::VecToQuat(joint_params);
                 quat = cMathUtil::MirrorQuaternion(quat, cMathUtil::eAxisZ);
                 joint_params = cMathUtil::QuatToVec(quat);
             }
             else
             {
                 assert(false); // unsupported joint type
             }
         }
     }
     for (size_t i = 0; i < mirror_joints0.size(); ++i)
     {
         int id0 = mirror_joints0[i];
         int id1 = mirror_joints1[i];
         int offset0 = cKinTree::GetParamOffset(joint_mat, id0);
         int size0 = cKinTree::GetParamSize(joint_mat, id0);
         int offset1 = cKinTree::GetParamOffset(joint_mat, id1);
         int size1 = cKinTree::GetParamSize(joint_mat, id1);
         Eigen::VectorXd params0 = out_pose.segment(offset0, size0);
         Eigen::VectorXd params1 = out_pose.segment(offset1, size1);
         out_pose.segment(offset0, size0) = params1;
         out_pose.segment(offset1, size1) = params0;
     }
 }
References cMathUtil::eAxisZ, eJointTypeFixed, eJointTypeRevolute, eJointTypeSpherical, GetJointType(), GetNumJoints(), GetParamOffset(), GetParamSize(), GetRootPos(), GetRootRot(), IsRoot(), cMathUtil::MirrorQuaternion(), cMathUtil::QuatToVec(), SetRootPos(), SetRootRot(), and cMathUtil::VecToQuat().
Referenced by cKinCharacter::MirrorFrame().
NormalizePoseHeading() [1/2]
void cKinTree::NormalizePoseHeading (const Eigen::MatrixXd & joint_mat, Eigen::VectorXd & out_pose) static
Definition at line 1658 of file KinTree.cpp.
 {
     Eigen::VectorXd vel= Eigen::VectorXd::Zero(0);
     NormalizePoseHeading(joint_mat, out_pose, vel);
 }
NormalizePoseHeading() [2/2]
void cKinTree::NormalizePoseHeading (const Eigen::MatrixXd & joint_mat, Eigen::VectorXd & out_pose, Eigen::VectorXd & out_vel) static
Definition at line 1664 of file KinTree.cpp.
 {
     tVector root_pos = GetRootPos(joint_mat, out_pose);
     tQuaternion root_rot = GetRootRot(joint_mat, out_pose);
     root_pos[0] = 0;
     root_pos[2] = 0;
     double heading = CalcHeading(joint_mat, out_pose);
     tQuaternion heading_q = cMathUtil::AxisAngleToQuaternion(tVector(0, 1, 0, 0), -heading);
     root_rot = heading_q * root_rot;
     SetRootPos(joint_mat, root_pos, out_pose);
     SetRootRot(joint_mat, root_rot, out_pose);
     if (out_vel.size() > 0)
     {
         tVector root_vel = GetRootVel(joint_mat, out_vel);
         tVector root_ang_vel = GetRootAngVel(joint_mat, out_vel);
         root_vel = cMathUtil::QuatRotVec(heading_q, root_vel);
         root_ang_vel = cMathUtil::QuatRotVec(heading_q, root_ang_vel);
         SetRootVel(joint_mat, root_vel, out_vel);
         SetRootAngVel(joint_mat, root_ang_vel, out_vel);
     }
 }
References cMathUtil::AxisAngleToQuaternion(), CalcHeading(), GetRootAngVel(), GetRootPos(), GetRootRot(), GetRootVel(), cMathUtil::QuatRotVec(), SetRootAngVel(), SetRootPos(), SetRootRot(), and SetRootVel().
ParentChildTrans()
tMatrix cKinTree::ParentChildTrans (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int joint_id) static
Definition at line 1083 of file KinTree.cpp.
 {
     tMatrix mat = ChildParentTrans(joint_mat, state, joint_id);
     mat = cMathUtil::InvRigidMat(mat);
     return mat;
 }
References ChildParentTrans(), and cMathUtil::InvRigidMat().
ParseBodyDef()
bool cKinTree::ParseBodyDef (const Json::Value & root, cKinTree::tBodyDef & out_def) static
Definition at line 177 of file KinTree.cpp.
 {
     std::string shape_str = root.get(gBodyDescKeys[eBodyParamShape], "").asString();
     cShape::eShape shape;
     bool succ = cShape::ParseShape(shape_str, shape);
     if (succ)
     {
         out_def(eBodyParamShape) = static_cast<double>(static_cast<int>(shape));
     }
     for (int i = 0; i < eBodyParamMax; ++i)
     {
         const std::string& curr_key = gBodyDescKeys[i];
         if (!root[curr_key].isNull()
             && root[curr_key].isNumeric())
         {
             Json::Value json_val = root[curr_key];
             double val = json_val.asDouble();
             out_def(i) = val;
         }
     }
     return succ;
 }
References Json::Value::asDouble(), Json::Value::asString(), eBodyParamMax, eBodyParamShape, gBodyDescKeys, Json::Value::get(), and cShape::ParseShape().
Referenced by LoadBodyDefs().
ParseDrawShapeDef()
bool cKinTree::ParseDrawShapeDef (const Json::Value & root, tDrawShapeDef & out_def) static
Definition at line 250 of file KinTree.cpp.
 {
     std::string shape_str = root.get(gDrawShapeDescKeys[eDrawShapeShape], "").asString();
     cShape::eShape shape;
     bool succ = cShape::ParseShape(shape_str, shape);
     if (succ)
     {
         out_def(eDrawShapeShape) = static_cast<double>(static_cast<int>(shape));
     }
     for (int i = 0; i < eDrawShapeParamMax; ++i)
     {
         const std::string& curr_key = gDrawShapeDescKeys[i];
         if (!root[curr_key].isNull()
             && root[curr_key].isNumeric())
         {
             Json::Value json_val = root[curr_key];
             double val = json_val.asDouble();
             out_def(i) = val;
         }
     }
     return succ;
 }
References Json::Value::asDouble(), Json::Value::asString(), eDrawShapeParamMax, eDrawShapeShape, gDrawShapeDescKeys, Json::Value::get(), and cShape::ParseShape().
Referenced by LoadDrawShapeDefs().
ParseJoint()
bool cKinTree::ParseJoint (const Json::Value & root, tJointDesc & out_joint_desc) static protected
Definition at line 971 of file KinTree.cpp.
 {
     out_joint_desc = BuildJointDesc();
     eJointType joint_type = eJointTypeNone;
     const Json::Value& type_json = root[gJointDescKeys[eJointDescType]];
     if (type_json.isNull())
     {
         printf("No joint type specified\n");
     }
     else
     {
         std::string type_str = type_json.asString();
         ParseJointType(type_str, joint_type);
         out_joint_desc[eJointDescType] = static_cast<double>(static_cast<int>(joint_type));
     }
     for (int i = 0; i < eJointDescMax; ++i)
     {
         if (i != eJointDescType)
         {
             const std::string& key = gJointDescKeys[i];
             if (!root[key].isNull())
             {
                 out_joint_desc[i] = root[key].asDouble();
             }
         }
     }
     return true;
 }
References Json::Value::asDouble(), Json::Value::asString(), BuildJointDesc(), eJointDescMax, eJointDescType, eJointTypeNone, gJointDescKeys, Json::Value::isNull(), and ParseJointType().
Referenced by Load().
ParseJointType()
bool cKinTree::ParseJointType (const std::string & type_str, eJointType & out_joint_type) static protected
Definition at line 1001 of file KinTree.cpp.
 {
     for (int i = 0; i < eJointTypeMax; ++i)
     {
         const std::string& name = gJointTypeNames[i];
         if (type_str == name)
         {
             out_joint_type = static_cast<eJointType>(i);
             return true;
         }
     }
     printf("Unsupported joint type: %s\n", type_str.c_str());
     assert(false); // unsupported joint type
     return false;
 }
References eJointTypeMax, and gJointTypeNames.
Referenced by ParseJoint().
PostProcessJointMat()
void cKinTree::PostProcessJointMat (Eigen::MatrixXd & out_joint_mat) static protected
Definition at line 1017 of file KinTree.cpp.
 {
     int num_joints = GetNumJoints(out_joint_mat);
     int offset = 0;
     for (int j = 0; j < num_joints; ++j)
     {
         int curr_size = GetParamSize(out_joint_mat, j);
         out_joint_mat(j, eJointDescParamOffset) = offset;
         offset += curr_size;
     }
     int root_id = GetRoot(out_joint_mat);
     out_joint_mat(root_id, eJointDescAttachX) = 0;
     out_joint_mat(root_id, eJointDescAttachY) = 0;
     out_joint_mat(root_id, eJointDescAttachZ) = 0;
 }
References eJointDescAttachX, eJointDescAttachY, eJointDescAttachZ, eJointDescParamOffset, GetNumJoints(), GetParamSize(), and GetRoot().
Referenced by Load().
PostProcessPose()
void cKinTree::PostProcessPose (const Eigen::MatrixXd & joint_mat, Eigen::VectorXd & out_pose) static
Definition at line 1522 of file KinTree.cpp.
 {
     // mostly to normalize quaternions
     int num_joints = GetNumJoints(joint_mat);
     int root_id = GetRoot(joint_mat);
     int root_offset = GetParamOffset(joint_mat, root_id);
     out_pose.segment(root_offset + gPosDim, gRotDim).normalize();
     for (int j = 1; j < num_joints; ++j)
     {
         eJointType joint_type = GetJointType(joint_mat, j);
         if (joint_type == eJointTypeSpherical)
         {
             int offset = GetParamOffset(joint_mat, j);
             out_pose.segment(offset, gRotDim).normalize();
         }
     }
 }
References eJointTypeSpherical, GetJointType(), GetNumJoints(), GetParamOffset(), GetRoot(), gPosDim, and gRotDim.
Referenced by cImpPDController::CalcControlForces(), cKinCharacter::PostProcessFrame(), and cCharacter::ReadState().
SetBodyEnableFallContact()
void cKinTree::SetBodyEnableFallContact (int part_id, bool enable, Eigen::MatrixXd & out_body_defs) static
Definition at line 337 of file KinTree.cpp.
 {
     out_body_defs(part_id, eBodyParamEnableFallContact) = (enable) ? 1 : 0;
 }
References eBodyParamEnableFallContact.
Referenced by cSimCharacter::SetBodyPartFallContact().
SetJointParams()
void cKinTree::SetJointParams (const Eigen::MatrixXd & joint_mat, int j, const Eigen::VectorXd & params, Eigen::VectorXd & out_state) static
Definition at line 830 of file KinTree.cpp.
 {
     int offset = GetParamOffset(joint_mat, j);
     int dim = GetParamSize(joint_mat, j);
     assert(dim == params.size());
     out_state.block(offset, 0, dim, 1) = params;
 }
References GetParamOffset(), and GetParamSize().
Referenced by BuildDefaultPose(), BuildDefaultVel(), cRBDUtil::CalcGravityForce(), and cRBDUtil::SolveInvDyna().
SetRootAngVel()
void cKinTree::SetRootAngVel (const Eigen::MatrixXd & joint_mat, const tVector & ang_vel, Eigen::VectorXd & out_vel) static
Definition at line 548 of file KinTree.cpp.
 {
     int root_id = GetRoot(joint_mat);
     int param_offset = GetParamOffset(joint_mat, root_id);
     out_vel.segment(param_offset + gPosDim, gRotDim) = ang_vel.segment(0, gRotDim);
 }
References GetParamOffset(), GetRoot(), gPosDim, and gRotDim.
Referenced by CalcVel(), NormalizePoseHeading(), cKinCharacter::RotateOrigin(), cCharacter::SetRootAngVel(), cSimCharacter::SetRootTransform(), and cCharacter::WriteState().
SetRootPos()
void cKinTree::SetRootPos (const Eigen::MatrixXd & joint_mat, const tVector & pos, Eigen::VectorXd & out_state) static
Definition at line 501 of file KinTree.cpp.
 {
     int root_id = GetRoot(joint_mat);
     int param_offset = GetParamOffset(joint_mat, root_id);
     out_state.segment(param_offset, gPosDim) = pos.segment(0, gPosDim);
 }
References GetParamOffset(), GetRoot(), and gPosDim.
Referenced by cKinCharacter::CalcPose(), LerpPoses(), MirrorPoseStance(), cKinCharacter::MoveOrigin(), NormalizePoseHeading(), cCharacter::SetRootPos(), cCharacter::SetRootPos0(), cSimCharacter::SetRootTransform(), and cCharacter::WriteState().
SetRootRot()
void cKinTree::SetRootRot (const Eigen::MatrixXd & joint_mat, const tQuaternion & rot, Eigen::VectorXd & out_state) static
Definition at line 516 of file KinTree.cpp.
 {
     int root_id = GetRoot(joint_mat);
     int param_offset = GetParamOffset(joint_mat, root_id);
     out_state.segment(param_offset + gPosDim, gRotDim) = cMathUtil::QuatToVec(rot).segment(0, gRotDim);
 }
References GetParamOffset(), GetRoot(), gPosDim, gRotDim, and cMathUtil::QuatToVec().
Referenced by cKinCharacter::CalcPose(), LerpPoses(), MirrorPoseStance(), NormalizePoseHeading(), cKinCharacter::RotateOrigin(), cCharacter::SetRootRotation(), cSimCharacter::SetRootTransform(), VelToPoseDiff(), and cCharacter::WriteState().
SetRootVel()
void cKinTree::SetRootVel (const Eigen::MatrixXd & joint_mat, const tVector & vel, Eigen::VectorXd & out_vel) static
Definition at line 532 of file KinTree.cpp.
 {
     int root_id = GetRoot(joint_mat);
     int param_offset = GetParamOffset(joint_mat, root_id);
     out_vel.segment(param_offset, gPosDim) = vel.segment(0, gPosDim);
 }
References GetParamOffset(), GetRoot(), and gPosDim.
Referenced by CalcVel(), NormalizePoseHeading(), cKinCharacter::RotateOrigin(), cSimCharacter::SetRootTransform(), cCharacter::SetRootVel(), and cCharacter::WriteState().
VelToPoseDiff()
void cKinTree::VelToPoseDiff (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & pose, const Eigen::VectorXd & vel, Eigen::VectorXd & out_pose_diff) static
Definition at line 1586 of file KinTree.cpp.
 {
     out_pose_diff = vel;
     int num_joints = GetNumJoints(joint_mat);
     int root_id = GetRoot(joint_mat);
     int root_offset = GetParamOffset(joint_mat, root_id);
     tVector root_rot_vel = GetRootAngVel(joint_mat, vel);
     root_rot_vel[3] = 0;
     tQuaternion root_rot = GetRootRot(joint_mat, pose);
     tMatrix root_diff_mat = cMathUtil::BuildQuaternionDiffMat(root_rot);
     tVector root_diff = root_diff_mat * root_rot_vel;
     tQuaternion root_quat = cMathUtil::VecToQuat(root_diff);
     cKinTree::SetRootRot(joint_mat, root_quat, out_pose_diff);
     for (int j = 1; j < num_joints; ++j)
     {
         eJointType joint_type = GetJointType(joint_mat, j);
         int offset = GetParamOffset(joint_mat, j);
         int size = GetParamSize(joint_mat, j);
         if (joint_type == eJointTypeSpherical)
         {
             tQuaternion rot = cMathUtil::VecToQuat(pose.segment(offset, size));
             tVector rot_vel = vel.segment(offset, size);
             rot_vel[3] = 0;
             tMatrix diff_mat = cMathUtil::BuildQuaternionDiffMat(rot);
             tVector q_diff = diff_mat * rot_vel;
             out_pose_diff.segment(offset, size) = q_diff;
         }
     }
 }
References cMathUtil::BuildQuaternionDiffMat(), eJointTypeSpherical, GetJointType(), GetNumJoints(), GetParamOffset(), GetParamSize(), GetRoot(), GetRootAngVel(), GetRootRot(), SetRootRot(), and cMathUtil::VecToQuat().
Referenced by cImpPDController::CalcControlForces().
WorldJointTrans()
tMatrix cKinTree::WorldJointTrans (const Eigen::MatrixXd & joint_mat, const Eigen::VectorXd & state, int joint_id) static
Definition at line 1105 of file KinTree.cpp.
 {
     tMatrix m = JointWorldTrans(joint_mat, state, joint_id);
     m = cMathUtil::InvRigidMat(m);
     return m;
 }
References cMathUtil::InvRigidMat(), and JointWorldTrans().
Member Data Documentation
gInvalidJointID
const int cKinTree::gInvalidJointID = -1 static
Definition at line 94 of file KinTree.h.
Referenced by cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildEndEffectorJacobian(), cRBDUtil::BuildJacobianDot(), CalcChainLength(), cSimCharacter::CalcJointPos(), cSimCharacter::CalcJointVel(), cSimCharacter::CalcJointWorldRotation(), CalcMaxSubChainLengths(), CalcSubTreeMasses(), cRBDUtil::CalcVelProdAcc(), cRBDUtil::CalcWorldJointTransforms(), cPDController::Clear(), cDrawKinTree::DrawTree(), cRBDUtil::ExtractEndEffJacobian(), FindJointChain(), HasParent(), HasValidRoot(), IsAncestor(), JointWorldTrans(), and cRBDUtil::MultJacobianEndEff().
gPosDim
const int cKinTree::gPosDim = 3 static
Definition at line 95 of file KinTree.h.
Referenced by BuildDefaultPoseRoot(), cSimCharacter::BuildJointPose(), cBVHReader::BuildJointPoseRoot(), cRBDUtil::BuildJointSubspaceRoot(), cSimCharacter::BuildJointVel(), CalcJointPoseDiff(), cCtController::GetPosFeatureDim(), GetRootAngVel(), GetRootPos(), GetRootRot(), GetRootVel(), PostProcessPose(), SetRootAngVel(), SetRootPos(), SetRootRot(), and SetRootVel().
gRootDim
const int cKinTree::gRootDim = gPosDim + gRotDim static
Definition at line 97 of file KinTree.h.
Referenced by BuildDefaultPoseRoot(), BuildDefaultVelRoot(), cSimCharacter::BuildJointPose(), cBVHReader::BuildJointPoseRoot(), cRBDUtil::BuildJointSubspaceRoot(), cSimCharacter::BuildJointVel(), CalcJointPoseDiff(), cBVHReader::tJointData::CalcPoseDim(), and GetParamSize().
gRotDim
const int cKinTree::gRotDim = 4 static
Definition at line 96 of file KinTree.h.
Referenced by cBVHReader::BuildJointPoseRoot(), cBVHReader::BuildJointPoseSpherical(), cRBDUtil::BuildJointSubspaceRoot(), cSimCharacter::BuildJointVel(), CalcJointPoseDiff(), GetRootAngVel(), GetRootRot(), cCtController::GetRotFeatureDim(), PostProcessPose(), SetRootAngVel(), and SetRootRot().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/anim/KinTree.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/anim/KinTree.cpp