My Project: Json::Value::CZString Class Reference
Json::Value::CZString Class Reference
Classes
struct StringStorage
Public Types
enum DuplicationPolicy { noDuplication = 0, duplicate, duplicateOnCopy }
Public Member Functions
CZString (ArrayIndex index)
CZString (char const *str, unsigned length, DuplicationPolicy allocate)
CZString (CZString const &other)
~CZString ()
CZString & operator= (CZString other)
bool operator< (CZString const &other) const
bool operator== (CZString const &other) const
ArrayIndex index () const
char const * data () const
unsigned length () const
bool isStaticString () const
Private Member Functions
void swap (CZString &other)
Private Attributes
char const * cstr_
union {
ArrayIndex index_
StringStorage storage_
};
Detailed Description
Definition at line 222 of file value.h.
Member Enumeration Documentation
DuplicationPolicy
enum Json::Value::CZString::DuplicationPolicy
Enumerator
noDuplication
duplicate
duplicateOnCopy
Definition at line 224 of file value.h.
{
       noDuplication = 0,
       duplicate,
       duplicateOnCopy
     };
Constructor & Destructor Documentation
CZString() [1/3]
Json::Value::CZString::CZString (ArrayIndex index)
Definition at line 257 of file json_value.cpp.
 : cstr_(0), index_(aindex) {}
CZString() [2/3]
Json::Value::CZString::CZString (char const * str, unsigned length, DuplicationPolicy allocate)
Definition at line 259 of file json_value.cpp.
     : cstr_(str) {
   // allocate != duplicate
   storage_.policy_ = allocate & 0x3;
   storage_.length_ = ulength & 0x3FFFFFFF;
 }
References Json::Value::CZString::StringStorage::length_, Json::Value::CZString::StringStorage::policy_, and storage_.
CZString() [3/3]
Json::Value::CZString::CZString (CZString const & other)
Definition at line 266 of file json_value.cpp.
{
   cstr_ = (other.storage_.policy_ != noDuplication && other.cstr_ != 0
                  ? duplicateStringValue(other.cstr_, other.storage_.length_)
                  : other.cstr_);
   storage_.policy_ = static_cast<unsigned>(other.cstr_
                  ? (static_cast<DuplicationPolicy>(other.storage_.policy_) == noDuplication
                      ? noDuplication : duplicate)
                  : static_cast<DuplicationPolicy>(other.storage_.policy_)) & 3U;
   storage_.length_ = other.storage_.length_;
 }
References cstr_, Json::duplicateStringValue(), Json::Value::CZString::StringStorage::length_, Json::Value::CZString::StringStorage::policy_, and storage_.
~CZString()
Json::Value::CZString::~CZString ()
Definition at line 284 of file json_value.cpp.
{
   if (cstr_ && storage_.policy_ == duplicate) {
       releaseStringValue(const_cast<char*>(cstr_), storage_.length_ + 1u); //+1 for null terminating character for sake of completeness but not actually necessary
   }
 }
References Json::releaseStringValue().
Member Function Documentation
data()
const char * Json::Value::CZString::data () const
Definition at line 329 of file json_value.cpp.
 { return cstr_; }
Referenced by Json::ValueIteratorBase::index(), and Json::ValueIteratorBase::key().
index()
ArrayIndex Json::Value::CZString::index () const
Definition at line 326 of file json_value.cpp.
 { return index_; }
Referenced by Json::ValueIteratorBase::index(), and Json::ValueIteratorBase::key().
isStaticString()
bool Json::Value::CZString::isStaticString () const
Definition at line 331 of file json_value.cpp.
 { return storage_.policy_ == noDuplication; }
Referenced by Json::ValueIteratorBase::key().
length()
unsigned Json::Value::CZString::length () const
Definition at line 330 of file json_value.cpp.
 { return storage_.length_; }
Referenced by Json::ValueIteratorBase::key().
operator<()
bool Json::Value::CZString::operator< (CZString const & other) const
Definition at line 300 of file json_value.cpp.
{
   if (!cstr_) return index_ < other.index_;
   //return strcmp(cstr_, other.cstr_) < 0;
   // Assume both are strings.
   unsigned this_len = this->storage_.length_;
   unsigned other_len = other.storage_.length_;
   unsigned min_len = std::min<unsigned>(this_len, other_len);
   JSON_ASSERT(this->cstr_ && other.cstr_);
   int comp = memcmp(this->cstr_, other.cstr_, min_len);
   if (comp < 0) return true;
   if (comp > 0) return false;
   return (this_len < other_len);
 }
References cstr_, index_, JSON_ASSERT, Json::Value::CZString::StringStorage::length_, and storage_.
operator=()
Value::CZString & Json::Value::CZString::operator= (CZString other)
Definition at line 295 of file json_value.cpp.
{
   swap(other);
   return *this;
 }
References Json::Value::swap().
operator==()
bool Json::Value::CZString::operator== (CZString const & other) const
Definition at line 314 of file json_value.cpp.
{
   if (!cstr_) return index_ == other.index_;
   //return strcmp(cstr_, other.cstr_) == 0;
   // Assume both are strings.
   unsigned this_len = this->storage_.length_;
   unsigned other_len = other.storage_.length_;
   if (this_len != other_len) return false;
   JSON_ASSERT(this->cstr_ && other.cstr_);
   int comp = memcmp(this->cstr_, other.cstr_, this_len);
   return comp == 0;
 }
References cstr_, index_, JSON_ASSERT, Json::Value::CZString::StringStorage::length_, and storage_.
swap()
void Json::Value::CZString::swap (CZString & other) private
Definition at line 290 of file json_value.cpp.
{
   std::swap(cstr_, other.cstr_);
   std::swap(index_, other.index_);
 }
References cstr_, index_, and std::swap().
Member Data Documentation
@2
union { ... }
cstr_
char const* Json::Value::CZString::cstr_ private
Definition at line 253 of file value.h.
Referenced by CZString(), operator<(), operator==(), and swap().
index_
ArrayIndex Json::Value::CZString::index_
Definition at line 255 of file value.h.
Referenced by operator<(), operator==(), and swap().
storage_
StringStorage Json::Value::CZString::storage_
Definition at line 256 of file value.h.
Referenced by CZString(), operator<(), and operator==().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/json/value.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/json/json_value.cpp