My Project: cKinCharacter Class Reference
cKinCharacter Class Reference
#include <KinCharacter.h>
Classes
struct tParams
Public Member Functions
cKinCharacter ()
virtual ~cKinCharacter ()
virtual bool Init (const tParams &params)
virtual void Clear ()
virtual void Update (double time_step)
virtual void Reset ()
virtual bool LoadMotion (const std::string &motion_file)
virtual const cMotion & GetMotion () const
virtual double GetMotionDuration () const
virtual void SetMotionDuration (double dur)
virtual void SetTime (double time)
virtual double GetTime () const
virtual int GetCycle () const
virtual double GetPhase () const
virtual void Pose (double time)
virtual void BuildAcc (Eigen::VectorXd &out_acc) const
virtual bool HasMotion () const
virtual void SetRootPos (const tVector &pos)
virtual void SetRootRotation (const tQuaternion &q)
virtual const tVector & GetOriginPos () const
virtual void SetOriginPos (const tVector &origin)
virtual void MoveOrigin (const tVector &delta)
virtual const tQuaternion & GetOriginRot () const
virtual void SetOriginRot (const tQuaternion &rot)
virtual void RotateOrigin (const tQuaternion &rot)
virtual void CalcPose (double time, Eigen::VectorXd &out_pose) const
virtual void CalcVel (double time, Eigen::VectorXd &out_vel) const
virtual void CalcAcc (double time, Eigen::VectorXd &out_vel) const
virtual bool IsMotionOver () const
virtual void BlendFrames (const cMotion::tFrame *a, const cMotion::tFrame *b, double lerp, cMotion::tFrame *out_frame) const
virtual void MirrorFrame (const std::vector< int > *right_joints, const std::vector< int > *left_joints, cMotion::tFrame *out_frame) const
virtual void CalcFrameVel (const cMotion::tFrame *a, const cMotion::tFrame *b, double timestep, cMotion::tFrame *out_vel) const
virtual void PostProcessFrame (cMotion::tFrame *out_frame) const
virtual tVector GetCycleRootDelta () const
Public Member Functions inherited from cCharacter
virtual ~cCharacter ()
virtual void SetID (int id)
virtual int GetID () const
virtual bool Init (const std::string &char_file, bool load_draw_shapes)
virtual int GetNumDof () const
virtual const Eigen::MatrixXd & GetJointMat () const
virtual int GetNumJoints () const
virtual const Eigen::VectorXd & GetPose () const
virtual void SetPose (const Eigen::VectorXd &pose)
virtual const Eigen::VectorXd & GetPose0 () const
virtual void SetPose0 (const Eigen::VectorXd &pose)
virtual const Eigen::VectorXd & GetVel () const
virtual void SetVel (const Eigen::VectorXd &vel)
virtual const Eigen::VectorXd & GetVel0 () const
virtual void SetVel0 (const Eigen::VectorXd &vel)
virtual int GetRootID () const
virtual tVector GetRootPos () const
virtual void GetRootRotation (tVector &out_axis, double &out_theta) const
virtual tQuaternion GetRootRotation () const
virtual void SetRootPos0 (const tVector &pose)
virtual void RotateRoot (const tQuaternion &rot)
virtual void SetRootVel (const tVector &vel)
virtual void SetRootAngVel (const tVector &ang_vel)
virtual tQuaternion CalcHeadingRot () const
virtual double CalcHeading () const
virtual tMatrix BuildOriginTrans () const
virtual int GetParamOffset (int joint_id) const
virtual int GetParamSize (int joint_id) const
virtual bool IsEndEffector (int joint_id) const
virtual int GetParentJoint (int joint_id) const
virtual tVector CalcJointPos (int joint_id) const
virtual tVector CalcJointVel (int joint_id) const
virtual void CalcJointWorldRotation (int joint_id, tVector &out_axis, double &out_theta) const
virtual tQuaternion CalcJointWorldRotation (int joint_id) const
virtual double CalcJointChainLength (int joint_id)
virtual tMatrix BuildJointWorldTrans (int joint_id) const
virtual void CalcAABB (tVector &out_min, tVector &out_max) const
virtual int CalcNumEndEffectors () const
virtual double GetJointDiffWeight (int joint_id) const
virtual bool WriteState (const std::string &file) const
virtual bool WriteState (const std::string &file, const tMatrix &root_trans) const
virtual bool ReadState (const std::string &file)
virtual bool LoadSkeleton (const Json::Value &root)
virtual void InitDefaultState ()
virtual bool HasDrawShapes () const
virtual const Eigen::MatrixXd & GetDrawShapeDefs () const
virtual const std::shared_ptr< cDrawMesh > & GetMesh (int i) const
virtual int GetNumMeshes () const
Protected Member Functions
virtual void ResetParams ()
virtual tVector CalcCycleRootDelta () const
Protected Member Functions inherited from cCharacter
cCharacter ()
virtual bool ParseState (const Json::Value &root, Eigen::VectorXd &out_state) const
virtual std::string BuildStateJson (const Eigen::VectorXd &pose, const Eigen::VectorXd &vel) const
virtual bool LoadDrawShapeDefs (const std::string &char_file, Eigen::MatrixXd &out_draw_defs) const
virtual bool LoadMeshes (const std::string &char_file, std::vector< std::shared_ptr< cDrawMesh >> &out_meshes) const
Protected Attributes
double mTime
cMotion mMotion
tVector mCycleRootDelta
tVector mOrigin
tQuaternion mOriginRot
Protected Attributes inherited from cCharacter
int mID
Eigen::MatrixXd mJointMat
Eigen::VectorXd mPose
Eigen::VectorXd mVel
Eigen::VectorXd mPose0
Eigen::VectorXd mVel0
Eigen::MatrixXd mDrawShapeDefs
std::vector< std::shared_ptr< cDrawMesh > > mMeshes
Additional Inherited Members
Static Public Attributes inherited from cCharacter
static const std::string gSkeletonKey = "Skeleton"
Detailed Description
Definition at line 6 of file KinCharacter.h.
Constructor & Destructor Documentation
cKinCharacter()
cKinCharacter::cKinCharacter ()
Definition at line 17 of file KinCharacter.cpp.
 {
     mOrigin.setZero();
     mOriginRot.setIdentity();
     mCycleRootDelta.setZero();
 }
References mCycleRootDelta, mOrigin, and mOriginRot.
~cKinCharacter()
cKinCharacter::~cKinCharacter () virtual
Definition at line 24 of file KinCharacter.cpp.
 {
 }
Member Function Documentation
BlendFrames()
void cKinCharacter::BlendFrames (const cMotion::tFrame * a, const cMotion::tFrame * b, double lerp, cMotion::tFrame * out_frame) const virtual
Definition at line 377 of file KinCharacter.cpp.
 {
     cKinTree::LerpPoses(mJointMat, *a, *b, lerp, *out_frame);
 }
References cKinTree::LerpPoses(), and cCharacter::mJointMat.
Referenced by LoadMotion().
BuildAcc()
void cKinCharacter::BuildAcc (Eigen::VectorXd & out_acc) const virtual
Definition at line 190 of file KinCharacter.cpp.
 {
     CalcAcc(mTime, out_acc);
 }
References CalcAcc(), and mTime.
CalcAcc()
void cKinCharacter::CalcAcc (double time, Eigen::VectorXd & out_vel) const virtual
Definition at line 357 of file KinCharacter.cpp.
 {
     Eigen::VectorXd vel0;
     Eigen::VectorXd vel1;
     CalcVel(time - gDiffTimeStep, vel0);
     CalcVel(time, vel1);
     out_acc = (vel1 - vel0) / gDiffTimeStep;
 }
References CalcVel(), and gDiffTimeStep.
Referenced by BuildAcc().
CalcCycleRootDelta()
tVector cKinCharacter::CalcCycleRootDelta () const protected virtual
Definition at line 300 of file KinCharacter.cpp.
 {
     int num_frames = mMotion.GetNumFrames();
     Eigen::VectorXd frame_beg = mMotion.GetFrame(0);
     Eigen::VectorXd  frame_end = mMotion.GetFrame(num_frames - 1);
     tVector root_pos_beg = cKinTree::GetRootPos(mJointMat, frame_beg);
     tVector root_pos_end = cKinTree::GetRootPos(mJointMat, frame_end);
     tVector delta = root_pos_end - root_pos_beg;
     return delta;
 }
References cMotion::GetFrame(), cMotion::GetNumFrames(), cKinTree::GetRootPos(), cCharacter::mJointMat, and mMotion.
Referenced by LoadMotion().
CalcFrameVel()
void cKinCharacter::CalcFrameVel (const cMotion::tFrame * a, const cMotion::tFrame * b, double timestep, cMotion::tFrame * out_vel) const virtual
Definition at line 388 of file KinCharacter.cpp.
 {
     const auto& joint_mat = GetJointMat();
     cKinTree::CalcVel(joint_mat, *a, *b, timestep, *out_vel);
 }
References cKinTree::CalcVel(), and cCharacter::GetJointMat().
Referenced by LoadMotion().
CalcPose()
void cKinCharacter::CalcPose (double time, Eigen::VectorXd & out_pose) const virtual
Definition at line 313 of file KinCharacter.cpp.
 {
     tVector root_delta = tVector::Zero();
     tQuaternion root_delta_rot = tQuaternion::Identity();
     if (HasMotion())
     {
         mMotion.CalcFrame(time, out_pose);
         if (mMotion.EnableLoop())
         {
             int cycle_count = mMotion.CalcCycleCount(time);
             root_delta = cycle_count * mCycleRootDelta;
         }
     }
     else
     {
         out_pose = mPose0;
     }
     tVector root_pos = cKinTree::GetRootPos(mJointMat, out_pose);
     tQuaternion root_rot = cKinTree::GetRootRot(mJointMat, out_pose);
     root_delta_rot = mOriginRot * root_delta_rot;
     root_rot = root_delta_rot * root_rot;
     root_pos += root_delta;
     root_pos = cMathUtil::QuatRotVec(root_delta_rot, root_pos);
     root_pos += mOrigin;
     cKinTree::SetRootPos(mJointMat, root_pos, out_pose);
     cKinTree::SetRootRot(mJointMat, root_rot, out_pose);
 }
References cMotion::CalcCycleCount(), cMotion::CalcFrame(), cMotion::EnableLoop(), cKinTree::GetRootPos(), cKinTree::GetRootRot(), HasMotion(), mCycleRootDelta, cCharacter::mJointMat, mMotion, mOrigin, mOriginRot, cCharacter::mPose0, cMathUtil::QuatRotVec(), cKinTree::SetRootPos(), and cKinTree::SetRootRot().
Referenced by Pose().
CalcVel()
void cKinCharacter::CalcVel (double time, Eigen::VectorXd & out_vel) const virtual
Definition at line 345 of file KinCharacter.cpp.
 {
     if (HasMotion())
     {
         mMotion.CalcFrameVel(time, out_vel);
     }
     else
     {
         out_vel = Eigen::VectorXd::Zero(GetNumDof());
     }
 }
References cMotion::CalcFrameVel(), cCharacter::GetNumDof(), HasMotion(), and mMotion.
Referenced by CalcAcc(), and Pose().
Clear()
void cKinCharacter::Clear () virtual
Reimplemented from cCharacter.
Definition at line 65 of file KinCharacter.cpp.
 {
     cCharacter::Clear();
     mMotion.Clear();
 }
References cCharacter::Clear(), cMotion::Clear(), and mMotion.
GetCycle()
int cKinCharacter::GetCycle () const virtual
Definition at line 155 of file KinCharacter.cpp.
 {
     int cycle = 0;
     if (mMotion.EnableLoop())
     {
         double phase = mTime / mMotion.GetDuration();
         cycle = static_cast<int>(std::floor(phase));
     }
     return cycle;
 }
References cMotion::EnableLoop(), cMotion::GetDuration(), mMotion, and mTime.
GetCycleRootDelta()
tVector cKinCharacter::GetCycleRootDelta () const virtual
Definition at line 294 of file KinCharacter.cpp.
 {
     tVector delta = cMathUtil::QuatRotVec(mOriginRot, mCycleRootDelta);
     return delta;
 }
References mCycleRootDelta, mOriginRot, and cMathUtil::QuatRotVec().
GetMotion()
const cMotion & cKinCharacter::GetMotion () const virtual
Definition at line 126 of file KinCharacter.cpp.
 {
     return mMotion;
 }
References mMotion.
GetMotionDuration()
double cKinCharacter::GetMotionDuration () const virtual
Definition at line 131 of file KinCharacter.cpp.
 {
     if (mMotion.IsValid())
     {
         return mMotion.GetDuration();
     }
     return 0;
 }
References cMotion::GetDuration(), cMotion::IsValid(), and mMotion.
GetOriginPos()
const tVector & cKinCharacter::GetOriginPos () const virtual
Definition at line 214 of file KinCharacter.cpp.
 {
     return mOrigin;
 }
References mOrigin.
Referenced by cSceneImitate::CalcRewardImitate(), and cSceneImitate::SyncKinCharNewCycle().
GetOriginRot()
const tQuaternion & cKinCharacter::GetOriginRot () const virtual
Definition at line 239 of file KinCharacter.cpp.
 {
     return mOriginRot;
 }
References mOriginRot.
GetPhase()
double cKinCharacter::GetPhase () const virtual
Definition at line 166 of file KinCharacter.cpp.
 {
     double phase = mTime / mMotion.GetDuration();
     if (mMotion.EnableLoop())
     {
         phase -= static_cast<int>(phase);
         phase = (phase < 0) ? (1 + phase) : phase;
     }
     else
     {
         phase = cMathUtil::Clamp(phase, 0.0, 1.0);
     }
     return phase;
 }
References cMathUtil::Clamp(), cMotion::EnableLoop(), cMotion::GetDuration(), mMotion, and mTime.
GetTime()
double cKinCharacter::GetTime () const virtual
Definition at line 150 of file KinCharacter.cpp.
 {
     return mTime;
 }
References mTime.
HasMotion()
bool cKinCharacter::HasMotion () const virtual
Definition at line 195 of file KinCharacter.cpp.
 {
     return mMotion.IsValid();
 }
References cMotion::IsValid(), and mMotion.
Referenced by CalcPose(), CalcVel(), and IsMotionOver().
Init()
bool cKinCharacter::Init (const tParams & params) virtual
Definition at line 28 of file KinCharacter.cpp.
 {
     mID = params.mID;
     bool succ = cCharacter::Init(params.mCharFile, params.mLoadDrawShapes);
     if (succ)
     {
         if (params.mMotionFile != "")
         {
             LoadMotion(params.mMotionFile);
         }
         if (params.mStateFile != "")
         {
             bool succ_state = ReadState(params.mStateFile);
             if (!succ_state)
             {
                 printf("Failed to load character state from %s\n", params.mStateFile.c_str());
             }
             else
             {
                 mPose0 = mPose;
                 mVel0 = mVel;
                 SetPose(mPose);
                 SetVel(mVel);
             }
         }
         SetOriginPos(params.mOrigin);
     }
     else
     {
         printf("Failed to build character from char_file: %s\n", params.mCharFile.c_str());
     }
     return succ;
 }
References cCharacter::Init(), LoadMotion(), cKinCharacter::tParams::mCharFile, cKinCharacter::tParams::mID, cCharacter::mID, cKinCharacter::tParams::mLoadDrawShapes, cKinCharacter::tParams::mMotionFile, cKinCharacter::tParams::mOrigin, cCharacter::mPose, cCharacter::mPose0, cKinCharacter::tParams::mStateFile, cCharacter::mVel, cCharacter::mVel0, cCharacter::ReadState(), SetOriginPos(), cCharacter::SetPose(), and cCharacter::SetVel().
IsMotionOver()
bool cKinCharacter::IsMotionOver () const virtual
Definition at line 366 of file KinCharacter.cpp.
 {
     bool over = true;
     if (HasMotion())
     {
         over = mMotion.IsOver(mTime);
     }
     return over;
 }
References HasMotion(), cMotion::IsOver(), mMotion, and mTime.
LoadMotion()
bool cKinCharacter::LoadMotion (const std::string & motion_file) virtual
Definition at line 83 of file KinCharacter.cpp.
 {
     cMotion::tParams motion_params;
     motion_params.mMotionFile = motion_file;
     motion_params.mBlendFunc = std::bind(&cKinCharacter::BlendFrames, this,
                                             std::placeholders::_1, std::placeholders::_2, std::placeholders::_3,
                                             std::placeholders::_4);
     motion_params.mMirrorFunc = std::bind(&cKinCharacter::MirrorFrame, this,
                                             std::placeholders::_1, std::placeholders::_2, std::placeholders::_3);
     motion_params.mVelFunc = std::bind(&cKinCharacter::CalcFrameVel, this,
                                             std::placeholders::_1, std::placeholders::_2, std::placeholders::_3,
                                             std::placeholders::_4);
     motion_params.mPostProcessFunc = std::bind(&cKinCharacter::PostProcessFrame, this, std::placeholders::_1);
     bool succ = mMotion.Load(motion_params);
     if (succ)
     {
         int char_dof = GetNumDof();
         int motion_dof = mMotion.GetNumDof();
         if (char_dof != motion_dof)
         {
             printf("DOF mismatch, char dof: %i, motion dof: %i\n", char_dof, motion_dof);
             mMotion.Clear();
             succ = false;
         }
     }
     if (succ)
     {
         mCycleRootDelta = CalcCycleRootDelta();
         Pose(mTime);
         mPose0 = GetPose();
         mVel0 = GetVel();
     }
     if (!succ)
     {
         printf("Failed to load motion from: %s\n", motion_file.c_str());
     }
     return succ;
 }
References BlendFrames(), CalcCycleRootDelta(), CalcFrameVel(), cMotion::Clear(), cCharacter::GetNumDof(), cMotion::GetNumDof(), cCharacter::GetPose(), cCharacter::GetVel(), cMotion::Load(), cMotion::tParams::mBlendFunc, mCycleRootDelta, MirrorFrame(), cMotion::tParams::mMirrorFunc, mMotion, cMotion::tParams::mMotionFile, cCharacter::mPose0, cMotion::tParams::mPostProcessFunc, mTime, cCharacter::mVel0, cMotion::tParams::mVelFunc, Pose(), and PostProcessFrame().
Referenced by Init().
MirrorFrame()
void cKinCharacter::MirrorFrame (const std::vector< int > * right_joints, const std::vector< int > * left_joints, cMotion::tFrame * out_frame) const virtual
Definition at line 382 of file KinCharacter.cpp.
 {
     const auto& joint_mat = GetJointMat();
     cKinTree::MirrorPoseStance(joint_mat, *left_joints, *right_joints, *out_frame);
 }
References cCharacter::GetJointMat(), and cKinTree::MirrorPoseStance().
Referenced by LoadMotion().
MoveOrigin()
void cKinCharacter::MoveOrigin (const tVector & delta) virtual
Definition at line 226 of file KinCharacter.cpp.
 {
     mOrigin += delta;
     tVector root0 = cKinTree::GetRootPos(mJointMat, mPose0);
     root0 += delta;
     cKinTree::SetRootPos(mJointMat, root0, mPose0);
     tVector root = cKinTree::GetRootPos(mJointMat, mPose);
     root += delta;
     cKinTree::SetRootPos(mJointMat, root, mPose);
 }
References cKinTree::GetRootPos(), cCharacter::mJointMat, mOrigin, cCharacter::mPose, cCharacter::mPose0, and cKinTree::SetRootPos().
Referenced by SetOriginPos(), and SetRootPos().
Pose()
void cKinCharacter::Pose (double time) virtual
Definition at line 181 of file KinCharacter.cpp.
 {
     CalcPose(time, mPose);
     SetPose(mPose);
     CalcVel(time, mVel);
     SetVel(mVel);
 }
References CalcPose(), CalcVel(), cCharacter::mPose, cCharacter::mVel, cCharacter::SetPose(), and cCharacter::SetVel().
Referenced by LoadMotion(), and Update().
PostProcessFrame()
void cKinCharacter::PostProcessFrame (cMotion::tFrame * out_frame) const virtual
Definition at line 394 of file KinCharacter.cpp.
 {
     const auto& joint_mat = GetJointMat();
     cKinTree::PostProcessPose(joint_mat, *out_frame);
 }
References cCharacter::GetJointMat(), and cKinTree::PostProcessPose().
Referenced by LoadMotion().
Reset()
void cKinCharacter::Reset () virtual
Reimplemented from cCharacter.
Definition at line 78 of file KinCharacter.cpp.
 {
     cCharacter::Reset();
 }
References cCharacter::Reset().
ResetParams()
void cKinCharacter::ResetParams () protected virtual
Reimplemented from cCharacter.
Definition at line 288 of file KinCharacter.cpp.
 {
     cCharacter::ResetParams();
     mTime = 0;
 }
References mTime, and cCharacter::ResetParams().
RotateOrigin()
void cKinCharacter::RotateOrigin (const tQuaternion & rot) virtual
Definition at line 251 of file KinCharacter.cpp.
 {
     mOriginRot = rot * mOriginRot;
     mOriginRot.normalize();
     tVector root_pos = GetRootPos();
     tVector root_pos_delta = mOrigin - root_pos;
     root_pos_delta = cMathUtil::QuatRotVec(rot, root_pos_delta);
     mOrigin = root_pos + root_pos_delta;
     tQuaternion root_rot0 = cKinTree::GetRootRot(mJointMat, mPose0);
     root_rot0 = rot * root_rot0;
     root_rot0.normalize();
     cKinTree::SetRootRot(mJointMat, root_rot0, mPose0);
     tQuaternion root_rot = cKinTree::GetRootRot(mJointMat, mPose);
     root_rot = rot * root_rot;
     root_rot.normalize();
     cKinTree::SetRootRot(mJointMat, root_rot, mPose);
     tVector vel0 = cKinTree::GetRootVel(mJointMat, mVel0);
     vel0 = cMathUtil::QuatRotVec(rot, vel0);
     cKinTree::SetRootVel(mJointMat, vel0, mVel0);
     tVector vel = cKinTree::GetRootVel(mJointMat, mVel);
     vel = cMathUtil::QuatRotVec(rot, vel);
     cKinTree::SetRootVel(mJointMat, vel, mVel);
     tVector ang_vel0 = cKinTree::GetRootAngVel(mJointMat, mVel0);
     ang_vel0 = cMathUtil::QuatRotVec(rot, ang_vel0);
     cKinTree::SetRootAngVel(mJointMat, ang_vel0, mVel0);
     tVector ang_vel = cKinTree::GetRootAngVel(mJointMat, mVel);
     ang_vel = cMathUtil::QuatRotVec(rot, ang_vel);
     cKinTree::SetRootAngVel(mJointMat, ang_vel, mVel);
 }
References cKinTree::GetRootAngVel(), cCharacter::GetRootPos(), cKinTree::GetRootRot(), cKinTree::GetRootVel(), cCharacter::mJointMat, mOrigin, mOriginRot, cCharacter::mPose, cCharacter::mPose0, cCharacter::mVel, cCharacter::mVel0, cMathUtil::QuatRotVec(), cKinTree::SetRootAngVel(), cKinTree::SetRootRot(), and cKinTree::SetRootVel().
Referenced by SetOriginRot(), and SetRootRotation().
SetMotionDuration()
void cKinCharacter::SetMotionDuration (double dur) virtual
Definition at line 140 of file KinCharacter.cpp.
 {
     return mMotion.SetDuration(dur);
 }
References mMotion, and cMotion::SetDuration().
SetOriginPos()
void cKinCharacter::SetOriginPos (const tVector & origin) virtual
Definition at line 219 of file KinCharacter.cpp.
 {
     tVector delta = origin - mOrigin;
     MoveOrigin(delta);
     mOrigin = origin; // this is needed in canse of NaNs
 }
References mOrigin, and MoveOrigin().
Referenced by Init().
SetOriginRot()
void cKinCharacter::SetOriginRot (const tQuaternion & rot) virtual
Definition at line 244 of file KinCharacter.cpp.
 {
     tQuaternion delta_rot = cMathUtil::QuatDiff(mOriginRot, rot);
     RotateOrigin(delta_rot);
     mOriginRot = rot; // this is needed in case of NaNs
 }
References mOriginRot, cMathUtil::QuatDiff(), and RotateOrigin().
SetRootPos()
void cKinCharacter::SetRootPos (const tVector & pos) virtual
Reimplemented from cCharacter.
Definition at line 200 of file KinCharacter.cpp.
 {
     tVector root_pos = GetRootPos();
     tVector delta = pos - root_pos;
     MoveOrigin(delta);
 }
References cCharacter::GetRootPos(), and MoveOrigin().
Referenced by cSceneImitate::SyncKinCharNewCycle().
SetRootRotation()
void cKinCharacter::SetRootRotation (const tQuaternion & q) virtual
Reimplemented from cCharacter.
Definition at line 207 of file KinCharacter.cpp.
 {
     tQuaternion root_rot = GetRootRotation();
     tQuaternion dq = q * root_rot.conjugate();
     RotateOrigin(dq);
 }
References cCharacter::GetRootRotation(), and RotateOrigin().
SetTime()
void cKinCharacter::SetTime (double time) virtual
Definition at line 145 of file KinCharacter.cpp.
 {
     mTime = time;
 }
References mTime.
Update()
void cKinCharacter::Update (double time_step) virtual
Reimplemented from cCharacter.
Definition at line 71 of file KinCharacter.cpp.
 {
     cCharacter::Update(time_step);
     mTime += time_step;
     Pose(mTime);
 }
References mTime, Pose(), and cCharacter::Update().
Member Data Documentation
mCycleRootDelta
tVector cKinCharacter::mCycleRootDelta protected
Definition at line 75 of file KinCharacter.h.
Referenced by CalcPose(), cKinCharacter(), GetCycleRootDelta(), and LoadMotion().
mMotion
cMotion cKinCharacter::mMotion protected
Definition at line 73 of file KinCharacter.h.
Referenced by CalcCycleRootDelta(), CalcPose(), CalcVel(), Clear(), GetCycle(), GetMotion(), GetMotionDuration(), GetPhase(), HasMotion(), IsMotionOver(), LoadMotion(), and SetMotionDuration().
mOrigin
tVector cKinCharacter::mOrigin protected
Definition at line 76 of file KinCharacter.h.
Referenced by CalcPose(), cKinCharacter(), GetOriginPos(), MoveOrigin(), RotateOrigin(), and SetOriginPos().
mOriginRot
tQuaternion cKinCharacter::mOriginRot protected
Definition at line 77 of file KinCharacter.h.
Referenced by CalcPose(), cKinCharacter(), GetCycleRootDelta(), GetOriginRot(), RotateOrigin(), and SetOriginRot().
mTime
double cKinCharacter::mTime protected
Definition at line 72 of file KinCharacter.h.
Referenced by BuildAcc(), GetCycle(), GetPhase(), GetTime(), IsMotionOver(), LoadMotion(), ResetParams(), SetTime(), and Update().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/anim/KinCharacter.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/anim/KinCharacter.cpp