My Project: cPerturbManager Class Reference
cPerturbManager Class Reference
#include <PerturbManager.h>
Public Member Functions
cPerturbManager ()
virtual ~cPerturbManager ()
virtual void Update (double time_step)
virtual void Clear ()
virtual void AddPerturb (const tPerturb &perturb)
virtual int GetNumPerturbs () const
virtual const tPerturb & GetPerturb (int i) const
Protected Member Functions
virtual void UpdatePerturbs (double time_step)
Protected Attributes
tEigenArr< tPerturb > mPerturbs
Detailed Description
Definition at line 7 of file PerturbManager.h.
Constructor & Destructor Documentation
cPerturbManager()
cPerturbManager::cPerturbManager ()
Definition at line 3 of file PerturbManager.cpp.
 {
 }
~cPerturbManager()
cPerturbManager::~cPerturbManager () virtual
Definition at line 7 of file PerturbManager.cpp.
 {
 }
Member Function Documentation
AddPerturb()
void cPerturbManager::AddPerturb (const tPerturb & perturb) virtual
Definition at line 21 of file PerturbManager.cpp.
 {
     if (perturb.IsValid())
     {
         mPerturbs.push_back(perturb);
     }
 }
References tPerturb::IsValid(), and mPerturbs.
Referenced by cWorld::AddPerturb().
Clear()
void cPerturbManager::Clear () virtual
Definition at line 16 of file PerturbManager.cpp.
 {
     mPerturbs.clear();
 }
References mPerturbs.
Referenced by cWorld::Init(), and cWorld::Reset().
GetNumPerturbs()
int cPerturbManager::GetNumPerturbs () const virtual
Definition at line 29 of file PerturbManager.cpp.
 {
     return static_cast<int>(mPerturbs.size());
 }
References mPerturbs.
Referenced by cDrawWorld::DrawPerturbs(), and UpdatePerturbs().
GetPerturb()
const tPerturb & cPerturbManager::GetPerturb (int i) const virtual
Definition at line 34 of file PerturbManager.cpp.
 {
     return mPerturbs[i];
 }
References mPerturbs.
Referenced by cDrawWorld::DrawPerturbs().
Update()
void cPerturbManager::Update (double time_step) virtual
Definition at line 11 of file PerturbManager.cpp.
 {
     UpdatePerturbs(time_step);
 }
References UpdatePerturbs().
Referenced by cWorld::Update().
UpdatePerturbs()
void cPerturbManager::UpdatePerturbs (double time_step) protected virtual
Definition at line 39 of file PerturbManager.cpp.
 {
     int num_perturbs = GetNumPerturbs();
     int idx = 0;
     for (int i = 0; i < num_perturbs; ++i)
     {
         tPerturb& curr_perturb = mPerturbs[i];
         if (!curr_perturb.HasExpired())
         {
             curr_perturb.Update(time_step);
             mPerturbs[idx] = curr_perturb;
             ++idx;
         }
     }
     mPerturbs.resize(idx);
 }
References GetNumPerturbs(), tPerturb::HasExpired(), mPerturbs, and tPerturb::Update().
Referenced by Update().
Member Data Documentation
mPerturbs
tEigenArr<tPerturb> cPerturbManager::mPerturbs protected
Definition at line 21 of file PerturbManager.h.
Referenced by AddPerturb(), Clear(), GetNumPerturbs(), GetPerturb(), and UpdatePerturbs().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/PerturbManager.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/PerturbManager.cpp