My Project: cPDController Class Reference
cPDController Class Reference
#include <PDController.h>
Public Types
enum eParam {
eParamJointID, eParamKp, eParamKd, eParamTargetTheta0,
eParamTargetTheta1, eParamTargetTheta2, eParamTargetTheta3, eParamTargetTheta4,
eParamTargetTheta5, eParamTargetTheta6, eParamTargetVel0, eParamTargetVel1,
eParamTargetVel2, eParamTargetVel3, eParamTargetVel4, eParamTargetVel5,
eParamTargetVel6, eParamUseWorldCoord, eParamMax
}
typedef Eigen::Matrix< double, eParamMax, 1 > tParams
Public Types inherited from cController
enum eMode { eModeActive, eModeInactive, eModePassive, eModeMax }
Public Member Functions
cPDController ()
virtual ~cPDController ()
virtual void Init (cSimCharacter *character, const tParams &params)
virtual void Clear ()
virtual void Update (double time_step)
virtual void UpdateControlForce (double time_step, Eigen::VectorXd &out_tau)
virtual cSimBodyJoint & GetJoint ()
virtual const cSimBodyJoint & GetJoint () const
virtual double GetKp () const
virtual void SetKp (double kp)
virtual void SetKd (double kd)
virtual double GetKd () const
virtual double GetTorqueLimit () const
virtual double GetForceLimit () const
virtual void SetTargetTheta (const Eigen::VectorXd &theta)
virtual void SetTargetVel (const Eigen::VectorXd &vel)
virtual void SetUseWorldCoord (bool use)
virtual bool UseWorldCoord () const
virtual void GetTargetTheta (Eigen::VectorXd &out_theta) const
virtual void GetTargetVel (Eigen::VectorXd &out_vel) const
virtual bool IsActive () const
Public Member Functions inherited from cController
virtual ~cController ()
virtual void Init (cSimCharacter *character)
virtual void Reset ()
virtual bool IsValid () const
virtual bool LoadParams (const std::string &param_file)
virtual int GetNumOptParams () const
virtual void BuildOptParams (Eigen::VectorXd &out_params) const
virtual void SetOptParams (const Eigen::VectorXd &params)
virtual void SetOptParams (const Eigen::VectorXd &params, Eigen::VectorXd &out_params) const
virtual void FetchOptParamScale (Eigen::VectorXd &out_scale) const
virtual void OutputOptParams (const std::string &file, const Eigen::VectorXd &params) const
virtual void OutputOptParams (FILE *f, const Eigen::VectorXd &params) const
virtual void SetActive (bool active)
virtual void SetMode (eMode mode)
virtual const cSimCharacter * GetChar () const
Static Public Member Functions
static bool LoadParams (const std::string &file, Eigen::MatrixXd &out_buffer)
static bool LoadParams (const Json::Value &root, Eigen::MatrixXd &out_buffer)
static bool ParsePDParams (const Json::Value &root, tParams &out_params)
Protected Member Functions
virtual int GetJointDim () const
virtual int GetJointID () const
virtual void ApplyControlForces (const Eigen::VectorXd &tau)
virtual void CalcJointTau (double time_step, Eigen::VectorXd &out_joint_tau)
virtual void CalcJointTauRevolute (double time_step, Eigen::VectorXd &out_joint_tau)
virtual void CalcJointTauPlanar (double time_step, Eigen::VectorXd &out_joint_tau)
virtual void CalcJointTauPrismatic (double time_step, Eigen::VectorXd &out_joint_tau)
virtual void CalcJointTauFixed (double time_step, Eigen::VectorXd &out_joint_tau)
virtual void CalcJointTauSpherical (double time_step, Eigen::VectorXd &out_joint_tau)
virtual void PostProcessTargetPose (Eigen::VectorXd &out_pose) const
virtual void PostProcessTargetVel (Eigen::VectorXd &out_vel) const
Protected Member Functions inherited from cController
cController ()
virtual bool ParseParams (const Json::Value &json)
Protected Attributes
tParams mParams
Protected Attributes inherited from cController
cSimCharacter * mChar
eMode mMode
bool mValid
Detailed Description
Definition at line 7 of file PDController.h.
Member Typedef Documentation
tParams
typedef Eigen::Matrix<double, eParamMax, 1> cPDController::tParams
Definition at line 34 of file PDController.h.
Member Enumeration Documentation
eParam
enum cPDController::eParam
Enumerator
eParamJointID
eParamKp
eParamKd
eParamTargetTheta0
eParamTargetTheta1
eParamTargetTheta2
eParamTargetTheta3
eParamTargetTheta4
eParamTargetTheta5
eParamTargetTheta6
eParamTargetVel0
eParamTargetVel1
eParamTargetVel2
eParamTargetVel3
eParamTargetVel4
eParamTargetVel5
eParamTargetVel6
eParamUseWorldCoord
eParamMax
Definition at line 12 of file PDController.h.
     {
         eParamJointID,
         eParamKp,
         eParamKd,
         eParamTargetTheta0,
         eParamTargetTheta1,
         eParamTargetTheta2,
         eParamTargetTheta3,
         eParamTargetTheta4,
         eParamTargetTheta5,
         eParamTargetTheta6,
         eParamTargetVel0,
         eParamTargetVel1,
         eParamTargetVel2,
         eParamTargetVel3,
         eParamTargetVel4,
         eParamTargetVel5,
         eParamTargetVel6,
         eParamUseWorldCoord,
         eParamMax
     };
Constructor & Destructor Documentation
cPDController()
cPDController::cPDController ()
Definition at line 95 of file PDController.cpp.
     : cController()
 {
     Clear();
 }
References Clear().
~cPDController()
cPDController::~cPDController () virtual
Definition at line 101 of file PDController.cpp.
 {
 }
Member Function Documentation
ApplyControlForces()
void cPDController::ApplyControlForces (const Eigen::VectorXd & tau) protected virtual
Definition at line 291 of file PDController.cpp.
 {
     mChar->ApplyControlForces(tau);
 }
References cSimCharacter::ApplyControlForces(), and cController::mChar.
Referenced by Update().
CalcJointTau()
void cPDController::CalcJointTau (double time_step, Eigen::VectorXd & out_joint_tau) protected virtual
Definition at line 296 of file PDController.cpp.
 {
     const cSimBodyJoint& joint = GetJoint();
     cKinTree::eJointType joint_type = joint.GetType();
     switch (joint_type)
     {
     case cKinTree::eJointTypeRevolute:
         CalcJointTauRevolute(time_step, out_joint_tau);
         break;
     case cKinTree::eJointTypePlanar:
         CalcJointTauPlanar(time_step, out_joint_tau);
         break;
     case cKinTree::eJointTypePrismatic:
         CalcJointTauPrismatic(time_step, out_joint_tau);
         break;
     case cKinTree::eJointTypeFixed:
         CalcJointTauFixed(time_step, out_joint_tau);
         break;
     case cKinTree::eJointTypeSpherical:
         CalcJointTauSpherical(time_step, out_joint_tau);
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References CalcJointTauFixed(), CalcJointTauPlanar(), CalcJointTauPrismatic(), CalcJointTauRevolute(), CalcJointTauSpherical(), cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, GetJoint(), and cSimBodyJoint::GetType().
Referenced by UpdateControlForce().
CalcJointTauFixed()
void cPDController::CalcJointTauFixed (double time_step, Eigen::VectorXd & out_joint_tau) protected virtual
Definition at line 386 of file PDController.cpp.
 {
     int dim = GetJointDim();
     out_joint_tau = Eigen::VectorXd::Zero(dim);
 }
References GetJointDim().
Referenced by CalcJointTau().
CalcJointTauPlanar()
void cPDController::CalcJointTauPlanar (double time_step, Eigen::VectorXd & out_joint_tau) protected virtual
Definition at line 353 of file PDController.cpp.
 {
     assert(false); // unsupported
     int dim = GetJointDim();
     out_joint_tau = Eigen::VectorXd::Zero(dim);
 }
References GetJointDim().
Referenced by CalcJointTau().
CalcJointTauPrismatic()
void cPDController::CalcJointTauPrismatic (double time_step, Eigen::VectorXd & out_joint_tau) protected virtual
Definition at line 360 of file PDController.cpp.
 {
     const cSimBodyJoint& joint = GetJoint();
     double kp = GetKp();
     double kd = GetKd();
     Eigen::VectorXd tar_pose;
     Eigen::VectorXd tar_vel;
     GetTargetTheta(tar_pose);
     GetTargetVel(tar_vel);
     Eigen::VectorXd pose;
     Eigen::VectorXd vel;
     joint.BuildPose(pose);
     joint.BuildVel(vel);
     double theta_err = tar_pose[0] - pose[0];
     double vel_err = tar_vel[0] - vel[0];
     double t = kp * theta_err + kd * vel_err;
     int dim = GetJointDim();
     out_joint_tau = Eigen::VectorXd::Zero(dim);
     out_joint_tau(0) = t;
 }
References cSimBodyJoint::BuildPose(), cSimBodyJoint::BuildVel(), GetJoint(), GetJointDim(), GetKd(), GetKp(), GetTargetTheta(), and GetTargetVel().
Referenced by CalcJointTau().
CalcJointTauRevolute()
void cPDController::CalcJointTauRevolute (double time_step, Eigen::VectorXd & out_joint_tau) protected virtual
Definition at line 323 of file PDController.cpp.
 {
     const cSimBodyJoint& joint = GetJoint();
     double kp = GetKp();
     double kd = GetKd();
     Eigen::VectorXd tar_pose;
     Eigen::VectorXd tar_vel;
     GetTargetTheta(tar_pose);
     GetTargetVel(tar_vel);
     Eigen::VectorXd pose;
     joint.BuildPose(pose);
     double theta = pose[0];
     Eigen::VectorXd joint_vel;
     joint.BuildVel(joint_vel);
     double vel = joint_vel[0];
     double theta_err = tar_pose[0] - theta;
     double vel_err = tar_vel[0] - vel;
     double t = kp * theta_err + kd * vel_err;
     //std::cout << "Revolute: theta: " << theta << " theta err: " << theta_err << " vel_err: " << vel_err << std::endl;
     int dim = GetJointDim();
     out_joint_tau = Eigen::VectorXd::Zero(dim);
     out_joint_tau(0) = t;
 }
References cSimBodyJoint::BuildPose(), cSimBodyJoint::BuildVel(), GetJoint(), GetJointDim(), GetKd(), GetKp(), GetTargetTheta(), and GetTargetVel().
Referenced by CalcJointTau().
CalcJointTauSpherical()
void cPDController::CalcJointTauSpherical (double time_step, Eigen::VectorXd & out_joint_tau) protected virtual
Definition at line 392 of file PDController.cpp.
 {
     int dim = GetJointDim();
     out_joint_tau = Eigen::VectorXd::Zero(dim);
     const cSimBodyJoint& joint = GetJoint();
     Eigen::VectorXd tar_theta;
     Eigen::VectorXd tar_vel;
     GetTargetTheta(tar_theta);
     GetTargetVel(tar_vel);
     Eigen::VectorXd pose;
     Eigen::VectorXd vel;
     joint.BuildPose(pose);
     joint.BuildVel(vel);
     tQuaternion tar_q = cMathUtil::VecToQuat(tar_theta);
     tQuaternion q = cMathUtil::VecToQuat(pose);
     tQuaternion q_err = q.conjugate() * tar_q;
     double kp = GetKp();
     double kd = GetKd();
     tVector torque = tVector::Zero();
     tVector axis;
     double theta;
     cMathUtil::QuaternionToAxisAngle(q_err, axis, theta);
     torque = (kp * theta) * axis;
     torque.segment(0, 3) += kd * (tar_vel.segment(0, 3) - vel.segment(0, 3));
     out_joint_tau = torque;
 }
References cSimBodyJoint::BuildPose(), cSimBodyJoint::BuildVel(), GetJoint(), GetJointDim(), GetKd(), GetKp(), GetTargetTheta(), GetTargetVel(), cMathUtil::QuaternionToAxisAngle(), and cMathUtil::VecToQuat().
Referenced by CalcJointTau().
Clear()
void cPDController::Clear () virtual
Reimplemented from cController.
Definition at line 118 of file PDController.cpp.
 {
     cController::Clear();
     mParams.setZero();
     mParams[eParamJointID] = static_cast<double>(cKinTree::gInvalidJointID);
 }
References cController::Clear(), eParamJointID, cKinTree::gInvalidJointID, and mParams.
Referenced by cPDController().
GetForceLimit()
double cPDController::GetForceLimit () const virtual
Definition at line 178 of file PDController.cpp.
 {
     return GetJoint().GetForceLimit();
 }
References cSimBodyJoint::GetForceLimit(), and GetJoint().
GetJoint() [1/2]
cSimBodyJoint & cPDController::GetJoint () virtual
Definition at line 153 of file PDController.cpp.
 {
     return mChar->GetJoint(GetJointID());
 }
References cSimCharacter::GetJoint(), GetJointID(), and cController::mChar.
Referenced by CalcJointTau(), CalcJointTauPrismatic(), CalcJointTauRevolute(), CalcJointTauSpherical(), GetForceLimit(), cCtPDController::GetJointType(), GetTargetTheta(), GetTorqueLimit(), PostProcessTargetPose(), and PostProcessTargetVel().
GetJoint() [2/2]
const cSimBodyJoint & cPDController::GetJoint () const virtual
Definition at line 158 of file PDController.cpp.
 {
     return mChar->GetJoint(GetJointID());
 }
References cSimCharacter::GetJoint(), GetJointID(), and cController::mChar.
GetJointDim()
int cPDController::GetJointDim () const protected virtual
Definition at line 281 of file PDController.cpp.
 {
     return mChar->GetParamSize(GetJointID());
 }
References GetJointID(), cCharacter::GetParamSize(), and cController::mChar.
Referenced by CalcJointTauFixed(), CalcJointTauPlanar(), CalcJointTauPrismatic(), CalcJointTauRevolute(), CalcJointTauSpherical(), GetTargetTheta(), GetTargetVel(), Init(), PostProcessTargetPose(), PostProcessTargetVel(), SetTargetTheta(), and SetTargetVel().
GetJointID()
int cPDController::GetJointID () const protected virtual
Definition at line 286 of file PDController.cpp.
 {
     return static_cast<int>(mParams[eParamJointID]);
 }
References eParamJointID, and mParams.
Referenced by GetJoint(), GetJointDim(), and UpdateControlForce().
GetKd()
double cPDController::GetKd () const virtual
Definition at line 188 of file PDController.cpp.
 {
     return mParams[eParamKd];
 }
References eParamKd, and mParams.
Referenced by CalcJointTauPrismatic(), CalcJointTauRevolute(), CalcJointTauSpherical(), and cImpPDController::InitGains().
GetKp()
double cPDController::GetKp () const virtual
Definition at line 168 of file PDController.cpp.
 {
     return mParams[eParamKp];
 }
References eParamKp, and mParams.
Referenced by CalcJointTauPrismatic(), CalcJointTauRevolute(), CalcJointTauSpherical(), and cImpPDController::InitGains().
GetTargetTheta()
void cPDController::GetTargetTheta (Eigen::VectorXd & out_theta) const virtual
Definition at line 225 of file PDController.cpp.
 {
     const cSimBodyJoint& joint = GetJoint();
     cKinTree::eJointType joint_type = joint.GetType();
     out_theta = mParams.segment(eParamTargetTheta0, GetJointDim());
     if (UseWorldCoord() && joint_type == cKinTree::eJointTypeRevolute)
     {
         tVector axis_world;
         double theta_world;
         joint.CalcWorldRotation(axis_world, theta_world);
         Eigen::VectorXd pose;
         joint.BuildPose(pose);
         double theta_rel = pose[0];
         tVector axis_rel = joint.GetAxisRel();
         tVector axis_ref = joint.CalcAxisWorld();
         double theta_offset = axis_world.dot(axis_ref) * theta_world
                             - axis_rel.dot(axis_ref) * theta_rel;
         out_theta(0) -= theta_offset;
     }
     if (UseWorldCoord() && joint_type == cKinTree::eJointTypeSpherical)
     {
         Eigen::VectorXd pose;
         joint.BuildPose(pose);
         tQuaternion world_rot = joint.CalcWorldRotation();
         tQuaternion rel_rot = cMathUtil::VecToQuat(pose);
         tQuaternion tar_q = cMathUtil::VecToQuat(out_theta);
         tQuaternion diff = world_rot.conjugate() * tar_q; // diference between target world and world
         tar_q = rel_rot * diff; // Add this difference to current relative rotation
         out_theta = cMathUtil::QuatToVec(tar_q);
     }
     if (UseWorldCoord() && ((joint_type != cKinTree::eJointTypeRevolute) && (joint_type != cKinTree::eJointTypeSpherical)))
     {
         printf("Only revolute joints support world space targets\n");
         assert(false);
     }
 }
References cSimBodyJoint::BuildPose(), cSimBodyJoint::CalcAxisWorld(), cSimBodyJoint::CalcWorldRotation(), cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, eParamTargetTheta0, cSimBodyJoint::GetAxisRel(), GetJoint(), GetJointDim(), cSimBodyJoint::GetType(), mParams, cMathUtil::QuatToVec(), UseWorldCoord(), and cMathUtil::VecToQuat().
Referenced by cImpPDController::BuildTargetPose(), CalcJointTauPrismatic(), CalcJointTauRevolute(), CalcJointTauSpherical(), cExpPDController::GetTargetTheta(), and Init().
GetTargetVel()
void cPDController::GetTargetVel (Eigen::VectorXd & out_vel) const virtual
Definition at line 269 of file PDController.cpp.
 {
     out_vel = mParams.segment(eParamTargetVel0, GetJointDim());
 }
References eParamTargetVel0, GetJointDim(), and mParams.
Referenced by cImpPDController::BuildTargetVel(), CalcJointTauPrismatic(), CalcJointTauRevolute(), CalcJointTauSpherical(), and cExpPDController::GetTargetVel().
GetTorqueLimit()
double cPDController::GetTorqueLimit () const virtual
Definition at line 173 of file PDController.cpp.
 {
     return GetJoint().GetTorqueLimit();
 }
References GetJoint(), and cSimBodyJoint::GetTorqueLimit().
Init()
void cPDController::Init (cSimCharacter * character, const tParams & params) virtual
Definition at line 105 of file PDController.cpp.
 {
     cController::Init(character);
     mParams = params;
     int joint_dim = GetJointDim();
     Eigen::VectorXd target_pose0;
     GetTargetTheta(target_pose0);
     SetTargetTheta(target_pose0);
     mValid = true;
 }
References GetJointDim(), GetTargetTheta(), cController::Init(), mParams, cController::mValid, and SetTargetTheta().
Referenced by cExpPDController::Init().
IsActive()
bool cPDController::IsActive () const virtual
Reimplemented from cController.
Definition at line 275 of file PDController.cpp.
 {
     bool active = cController::IsActive();
     return active;
 }
References cController::IsActive().
Referenced by cImpPDController::CalcControlForces(), Update(), and UpdateControlForce().
LoadParams() [1/2]
bool cPDController::LoadParams (const Json::Value & root, Eigen::MatrixXd & out_buffer) static
Definition at line 50 of file PDController.cpp.
 {
     bool succ = true;
     int num_ctrls = root.size();
     out_buffer.resize(num_ctrls, eParamMax);
     for (int i = 0; i < num_ctrls; ++i)
     {
         tParams curr_params;
         const Json::Value& json_pd_ctrl = root.get(i, 0);
         bool succ_def = ParsePDParams(json_pd_ctrl, curr_params);
         if (succ_def)
         {
             int joint_id = i;
             curr_params[eParamJointID] = i;
             out_buffer.row(i) = curr_params;
         }
         else
         {
             succ = false;
             break;
         }
     }
     return succ;
 }
References eParamJointID, eParamMax, Json::Value::get(), ParsePDParams(), and Json::Value::size().
LoadParams() [2/2]
bool cPDController::LoadParams (const std::string & file, Eigen::MatrixXd & out_buffer) static
Definition at line 29 of file PDController.cpp.
 {
     std::ifstream f_stream(file);
     Json::Reader reader;
     Json::Value root;
     bool succ = reader.parse(f_stream, root);
     f_stream.close();
     if (succ)
     {
         succ &= LoadParams(root, out_buffer);
     }
     if (!succ)
     {
         printf("Failed to load PD controller parameters from %s\n", file.c_str());
     }
     return succ;
 }
References Json::Reader::parse().
Referenced by cCtPDController::SetupPDControllers().
ParsePDParams()
bool cPDController::ParsePDParams (const Json::Value & root, tParams & out_params) static
Definition at line 76 of file PDController.cpp.
 {
     bool succ = true;
     out_params.setZero();
     for (int i = 0; i < eParamMax; ++i)
     {
         const std::string& curr_key = gPDParamKeys[i];
         if (!root[curr_key].isNull() && root[curr_key].isNumeric())
         {
             Json::Value json_val = root[curr_key];
             double val = json_val.asDouble();
             out_params[i] = val;
         }
     }
     return succ;
 }
References Json::Value::asDouble(), eParamMax, and gPDParamKeys.
Referenced by LoadParams().
PostProcessTargetPose()
void cPDController::PostProcessTargetPose (Eigen::VectorXd & out_pose) const protected virtual
Definition at line 425 of file PDController.cpp.
 {
     const cSimBodyJoint& joint = GetJoint();
     int joint_dim = GetJointDim();
     assert(out_pose.size() == joint_dim);
     cKinTree::eJointType joint_type = joint.GetType();
     if (joint_type == cKinTree::eJointTypeSpherical)
     {
         if (out_pose.squaredNorm() == 0)
         {
             out_pose(0) = 1;
         }
         else
         {
             out_pose.normalize();
         }
     }
 }
References cKinTree::eJointTypeSpherical, GetJoint(), GetJointDim(), and cSimBodyJoint::GetType().
Referenced by SetTargetTheta().
PostProcessTargetVel()
void cPDController::PostProcessTargetVel (Eigen::VectorXd & out_vel) const protected virtual
Definition at line 445 of file PDController.cpp.
 {
     const cSimBodyJoint& joint = GetJoint();
     int joint_dim = GetJointDim();
     assert(out_vel.size() == joint_dim);
     cKinTree::eJointType joint_type = joint.GetType();
     if (joint_type == cKinTree::eJointTypeSpherical)
     {
         out_vel(joint_dim - 1) = 0;
     }
 }
References cKinTree::eJointTypeSpherical, GetJoint(), GetJointDim(), and cSimBodyJoint::GetType().
Referenced by SetTargetVel().
SetKd()
void cPDController::SetKd (double kd) virtual
Definition at line 183 of file PDController.cpp.
 {
     mParams[eParamKd] = kd;
 }
References eParamKd, and mParams.
Referenced by cExpPDController::SetKd().
SetKp()
void cPDController::SetKp (double kp) virtual
Definition at line 163 of file PDController.cpp.
 {
     mParams[eParamKp] = kp;
 }
References eParamKp, and mParams.
Referenced by cExpPDController::SetKp().
SetTargetTheta()
void cPDController::SetTargetTheta (const Eigen::VectorXd & theta) virtual
Definition at line 193 of file PDController.cpp.
 {
     int theta_size = static_cast<int>(theta.size());
     int joint_dim = GetJointDim();
     assert(theta_size == joint_dim);
     assert(theta_size < 7);
     Eigen::VectorXd theta_proc = theta;
     PostProcessTargetPose(theta_proc);
     mParams.segment(eParamTargetTheta0, theta_size) = theta_proc;
 }
References eParamTargetTheta0, GetJointDim(), mParams, and PostProcessTargetPose().
Referenced by Init(), and cExpPDController::SetTargetTheta().
SetTargetVel()
void cPDController::SetTargetVel (const Eigen::VectorXd & vel) virtual
Definition at line 204 of file PDController.cpp.
 {
     int vel_size = static_cast<int>(vel.size());
     int joint_dim = GetJointDim();
     assert(vel_size == joint_dim);
     assert(vel_size < 7);
     Eigen::VectorXd vel_proc = vel;
     PostProcessTargetVel(vel_proc);
     mParams.segment(eParamTargetVel0, vel_size) = vel_proc;
 }
References eParamTargetVel0, GetJointDim(), mParams, and PostProcessTargetVel().
Referenced by cExpPDController::SetTargetVel().
SetUseWorldCoord()
void cPDController::SetUseWorldCoord (bool use) virtual
Definition at line 215 of file PDController.cpp.
 {
     mParams[eParamUseWorldCoord] = (use) ? 1 : 0;
 }
References eParamUseWorldCoord, and mParams.
Referenced by cExpPDController::SetUseWorldCoord().
Update()
void cPDController::Update (double time_step) virtual
Reimplemented from cController.
Definition at line 126 of file PDController.cpp.
 {
     Eigen::VectorXd tau = Eigen::VectorXd::Zero(mChar->GetNumDof());
     UpdateControlForce(time_step, tau);
     if (IsActive())
     {
         ApplyControlForces(tau);
     }
 }
References ApplyControlForces(), cCharacter::GetNumDof(), IsActive(), cController::mChar, and UpdateControlForce().
UpdateControlForce()
void cPDController::UpdateControlForce (double time_step, Eigen::VectorXd & out_tau) virtual
Definition at line 136 of file PDController.cpp.
 {
     cController::Update(time_step);
     if (IsActive())
     {
         Eigen::VectorXd joint_tau;
         CalcJointTau(time_step, joint_tau);
         int joint_id = GetJointID();
         int param_offset = mChar->GetParamOffset(joint_id);
         int param_size = mChar->GetParamSize(joint_id);
         assert(param_size == joint_tau.size());
         out_tau.segment(param_offset, param_size) += joint_tau;
     }
 }
References CalcJointTau(), GetJointID(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), IsActive(), cController::mChar, and cController::Update().
Referenced by cExpPDController::CalcControlForces(), and Update().
UseWorldCoord()
bool cPDController::UseWorldCoord () const virtual
Definition at line 220 of file PDController.cpp.
 {
     return mParams[eParamUseWorldCoord] != 0;
 }
References eParamUseWorldCoord, and mParams.
Referenced by GetTargetTheta(), and cExpPDController::UseWorldCoord().
Member Data Documentation
mParams
tParams cPDController::mParams protected
Definition at line 68 of file PDController.h.
Referenced by Clear(), GetJointID(), GetKd(), GetKp(), GetTargetTheta(), GetTargetVel(), Init(), SetKd(), SetKp(), SetTargetTheta(), SetTargetVel(), SetUseWorldCoord(), and UseWorldCoord().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/PDController.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/PDController.cpp