My Project: cScene Class Reference
cScene Class Reference abstract
#include <Scene.h>
Public Member Functions
virtual ~cScene ()
virtual void ParseArgs (const std::shared_ptr< cArgParser > &parser)
virtual void Init ()
virtual void Clear ()
virtual void Reset ()
virtual void Update (double timestep)
virtual void Draw ()
virtual void Keyboard (unsigned char key, double device_x, double device_y)
virtual void MouseClick (int button, int state, double device_x, double device_y)
virtual void MouseMove (double device_x, double device_y)
virtual void Reshape (int w, int h)
virtual void Shutdown ()
virtual bool IsDone () const
virtual double GetTime () const
virtual bool HasRandSeed () const
virtual void SetRandSeed (unsigned long seed)
virtual unsigned long GetRandSeed () const
virtual bool IsEpisodeEnd () const
virtual bool CheckValidEpisode () const
virtual std::string GetName () const =0
Protected Member Functions
cScene ()
virtual void ResetParams ()
virtual void ResetScene ()
virtual void InitTimers ()
virtual void ResetTimers ()
virtual void UpdateTimers (double timestep)
Protected Attributes
cRand mRand
bool mHasRandSeed
unsigned long mRandSeed
std::shared_ptr< cArgParser > mArgParser
cTimer::tParams mTimerParams
cTimer mTimer
Detailed Description
Definition at line 12 of file Scene.h.
Constructor & Destructor Documentation
~cScene()
cScene::~cScene () virtual
Definition at line 10 of file Scene.cpp.
 {
 }
cScene()
cScene::cScene () protected
Definition at line 3 of file Scene.cpp.
 {
     mRand.Seed(cMathUtil::RandUint());
     mRandSeed = 0;
     mHasRandSeed = false;
 }
References mHasRandSeed, mRand, mRandSeed, cMathUtil::RandUint(), and cRand::Seed().
Member Function Documentation
CheckValidEpisode()
bool cScene::CheckValidEpisode () const virtual
Reimplemented in cRLSceneSimChar, cDrawRLScene, cDrawSceneSimChar, and cDrawSceneImitate.
Definition at line 109 of file Scene.cpp.
 {
     return true;
 }
Referenced by cDrawRLScene::CheckValidEpisode().
Clear()
void cScene::Clear () virtual
Reimplemented in cSceneSimChar, cRLScene, cSceneKinChar, cDrawSceneSimChar, cRLSceneSimChar, cDrawSceneKinChar, and cDrawSceneImitate.
Definition at line 37 of file Scene.cpp.
 {
     ResetParams();
 }
References ResetParams().
Referenced by cDrawSceneKinChar::Clear(), cDrawSceneSimChar::Clear(), cRLScene::Clear(), and cSceneSimChar::Clear().
Draw()
void cScene::Draw () virtual
Reimplemented in cDrawScene.
Definition at line 52 of file Scene.cpp.
 {
 }
GetName()
virtual std::string cScene::GetName () const pure virtual
Implemented in cSceneSimChar, cRLSceneSimChar, cDrawRLScene, cDrawScene, cDrawSceneSimChar, cSceneKinChar, cSceneImitate, cDrawSceneImitate, and cDrawSceneKinChar.
Referenced by cDrawRLScene::GetName().
GetRandSeed()
unsigned long cScene::GetRandSeed () const virtual
Definition at line 99 of file Scene.cpp.
 {
     return mRandSeed;
 }
References mRandSeed.
GetTime()
double cScene::GetTime () const virtual
Reimplemented in cDrawSceneSimChar, and cSceneKinChar.
Definition at line 82 of file Scene.cpp.
 {
     return mTimer.GetTime();
 }
References cTimer::GetTime(), and mTimer.
Referenced by cSceneSimChar::SpawnProjectile(), and cSceneSimChar::UpdateObjs().
HasRandSeed()
bool cScene::HasRandSeed () const virtual
Definition at line 87 of file Scene.cpp.
 {
     return mHasRandSeed;
 }
References mHasRandSeed.
Referenced by Init().
Init()
void cScene::Init () virtual
Reimplemented in cSceneSimChar, cRLScene, cDrawScene, cDrawSceneSimChar, cRLSceneSimChar, cSceneKinChar, cDrawSceneImitate, cDrawSceneKinChar, cSceneImitate, and cDrawRLScene.
Definition at line 26 of file Scene.cpp.
 {
     if (HasRandSeed())
     {
         SetRandSeed(mRandSeed);
     }
     InitTimers();
     ResetParams();
 }
References HasRandSeed(), InitTimers(), mRandSeed, ResetParams(), and SetRandSeed().
Referenced by cDrawScene::Init(), cRLScene::Init(), and cSceneSimChar::Init().
InitTimers()
void cScene::InitTimers () protected virtual
Definition at line 124 of file Scene.cpp.
 {
     mTimer.Init(mTimerParams);
 }
References cTimer::Init(), mTimer, and mTimerParams.
Referenced by Init().
IsDone()
bool cScene::IsDone () const virtual
Definition at line 77 of file Scene.cpp.
 {
     return false;
 }
IsEpisodeEnd()
bool cScene::IsEpisodeEnd () const virtual
Reimplemented in cRLScene, cDrawRLScene, cDrawSceneSimChar, and cDrawSceneImitate.
Definition at line 104 of file Scene.cpp.
 {
     return mTimer.IsEnd();
 }
References cTimer::IsEnd(), and mTimer.
Referenced by cRLScene::IsEpisodeEnd().
Keyboard()
void cScene::Keyboard (unsigned char key, double device_x, double device_y) virtual
Reimplemented in cDrawSceneSimChar, and cDrawSceneImitate.
Definition at line 56 of file Scene.cpp.
 {
 }
Referenced by cDrawSceneSimChar::Keyboard().
MouseClick()
void cScene::MouseClick (int button, int state, double device_x, double device_y) virtual
Reimplemented in cDrawSceneSimChar, and cDrawScene.
Definition at line 60 of file Scene.cpp.
 {
 }
Referenced by cDrawScene::MouseClick().
MouseMove()
void cScene::MouseMove (double device_x, double device_y) virtual
Reimplemented in cDrawSceneSimChar, and cDrawScene.
Definition at line 64 of file Scene.cpp.
 {
 }
Referenced by cDrawScene::MouseMove().
ParseArgs()
void cScene::ParseArgs (const std::shared_ptr< cArgParser > & parser) virtual
Reimplemented in cSceneSimChar, cDrawScene, cSceneKinChar, cRLSceneSimChar, and cSceneImitate.
Definition at line 14 of file Scene.cpp.
 {
     mArgParser = parser;
     std::string timer_type_str = "";
     mArgParser->ParseString("timer_type", timer_type_str);
     mTimerParams.mType = cTimer::ParseTypeStr(timer_type_str);
     mArgParser->ParseDouble("time_lim_min", mTimerParams.mTimeMin);
     mArgParser->ParseDouble("time_lim_max", mTimerParams.mTimeMax);
     mArgParser->ParseDouble("time_lim_exp", mTimerParams.mTimeExp);
 }
References mArgParser, cTimer::tParams::mTimeExp, cTimer::tParams::mTimeMax, cTimer::tParams::mTimeMin, mTimerParams, cTimer::tParams::mType, and cTimer::ParseTypeStr().
Referenced by cRLSceneSimChar::ParseArgs(), cSceneKinChar::ParseArgs(), cDrawScene::ParseArgs(), and cSceneSimChar::ParseArgs().
Reset()
void cScene::Reset () virtual
Reimplemented in cDrawScene, cSceneKinChar, and cDrawSceneKinChar.
Definition at line 42 of file Scene.cpp.
 {
     ResetScene();
 }
References ResetScene().
Referenced by cDrawScene::Reset().
ResetParams()
void cScene::ResetParams () protected virtual
Reimplemented in cDrawSceneSimChar, and cRLSceneSimChar.
Definition at line 114 of file Scene.cpp.
 {
     ResetTimers();
 }
References ResetTimers().
Referenced by Clear(), Init(), cRLSceneSimChar::ResetParams(), cDrawSceneSimChar::ResetParams(), and ResetScene().
ResetScene()
void cScene::ResetScene () protected virtual
Reimplemented in cSceneSimChar, cRLSceneSimChar, and cDrawSceneSimChar.
Definition at line 119 of file Scene.cpp.
 {
     ResetParams();
 }
References ResetParams().
Referenced by Reset(), cDrawSceneSimChar::ResetScene(), cRLSceneSimChar::ResetScene(), and cSceneSimChar::ResetScene().
ResetTimers()
void cScene::ResetTimers () protected virtual
Reimplemented in cRLSceneSimChar.
Definition at line 129 of file Scene.cpp.
 {
     mTimer.Reset();
 }
References mTimer, and cTimer::Reset().
Referenced by ResetParams(), and cRLSceneSimChar::ResetTimers().
Reshape()
void cScene::Reshape (int w, int h) virtual
Reimplemented in cDrawScene.
Definition at line 69 of file Scene.cpp.
 {
 }
Referenced by cDrawScene::Reshape().
SetRandSeed()
void cScene::SetRandSeed (unsigned long seed) virtual
Reimplemented in cSceneSimChar.
Definition at line 92 of file Scene.cpp.
 {
     mHasRandSeed = true;
     mRandSeed = seed;
     mRand.Seed(seed);
 }
References mHasRandSeed, mRand, mRandSeed, and cRand::Seed().
Referenced by Init(), and cSceneSimChar::SetRandSeed().
Shutdown()
void cScene::Shutdown () virtual
Definition at line 73 of file Scene.cpp.
 {
 }
Update()
void cScene::Update (double timestep) virtual
Reimplemented in cSceneSimChar, cSceneKinChar, cDrawSceneSimChar, and cDrawSceneKinChar.
Definition at line 47 of file Scene.cpp.
 {
     UpdateTimers(timestep);
 }
References UpdateTimers().
Referenced by cDrawSceneKinChar::Update(), cDrawSceneSimChar::Update(), and cSceneSimChar::Update().
UpdateTimers()
void cScene::UpdateTimers (double timestep) protected virtual
Definition at line 134 of file Scene.cpp.
 {
     mTimer.Update(timestep);
 }
References mTimer, and cTimer::Update().
Referenced by Update().
Member Data Documentation
mArgParser
std::shared_ptr<cArgParser> cScene::mArgParser protected
Definition at line 49 of file Scene.h.
Referenced by cRLSceneSimChar::ParseArgs(), ParseArgs(), cDrawSceneKinChar::SetupScene(), and cDrawSceneSimChar::SetupScene().
mHasRandSeed
bool cScene::mHasRandSeed protected
Definition at line 46 of file Scene.h.
Referenced by cSceneSimChar::BuildGround(), cScene(), HasRandSeed(), and SetRandSeed().
mRand
cRand cScene::mRand protected
Definition at line 45 of file Scene.h.
Referenced by cSceneSimChar::ApplyRandForce(), cScene(), cSceneSimChar::GetRandPerturbPartID(), cSceneImitate::ResetKinChar(), cSceneSimChar::ResetRandPertrub(), SetRandSeed(), and cSceneSimChar::SpawnProjectile().
mRandSeed
unsigned long cScene::mRandSeed protected
Definition at line 47 of file Scene.h.
Referenced by cSceneSimChar::BuildGround(), cScene(), GetRandSeed(), Init(), and SetRandSeed().
mTimer
cTimer cScene::mTimer protected
Definition at line 51 of file Scene.h.
Referenced by GetTime(), InitTimers(), IsEpisodeEnd(), ResetTimers(), cRLSceneSimChar::ResetTimers(), cSceneSimChar::tPerturbParams::tPerturbParams(), cRLSceneSimChar::UpdateTimerParams(), and UpdateTimers().
mTimerParams
cTimer::tParams cScene::mTimerParams protected
Definition at line 50 of file Scene.h.
Referenced by InitTimers(), cRLSceneSimChar::ParseArgs(), ParseArgs(), and cRLSceneSimChar::UpdateTimerParams().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/Scene.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/Scene.cpp