My Project: cTrajectory Class Reference
cTrajectory Class Reference
#include <Trajectory.h>
Public Types
enum eWrapMode { eWrapModeClamp, eWrapModeLoop, eWrapModeMax }
Public Member Functions
cTrajectory ()
virtual ~cTrajectory ()
virtual void Init (const Eigen::MatrixXd &anchors, eWrapMode mode)
virtual void Clear ()
virtual Eigen::VectorXd Eval (double t)
virtual int GetNumAnchors () const
virtual int GetDim () const
virtual int GetSize () const
virtual Eigen::VectorXd GetAnchor (int idx) const
virtual void SetAnchor (const Eigen::VectorXd &anchor, int idx)
virtual double PhaseToAnchor (double t) const
virtual double AnchorToPhase (int idx) const
virtual void Filter (double r)
virtual void Compress (double ratio)
virtual Eigen::VectorXd Unroll () const
virtual void SetUnrolled (const Eigen::VectorXd &unrolled_data, int dim)
Protected Member Functions
virtual double NormalizePhase (double t) const
virtual double GetPhaseStep () const
Protected Attributes
eWrapMode mWrapMode
Eigen::MatrixXd mAnchors
Detailed Description
Definition at line 5 of file Trajectory.h.
Member Enumeration Documentation
eWrapMode
enum cTrajectory::eWrapMode
Enumerator
eWrapModeClamp
eWrapModeLoop
eWrapModeMax
Definition at line 8 of file Trajectory.h.
     {
         eWrapModeClamp,
         eWrapModeLoop,
         eWrapModeMax,
     };
Constructor & Destructor Documentation
cTrajectory()
cTrajectory::cTrajectory ()
Definition at line 3 of file Trajectory.cpp.
 {
     mWrapMode = eWrapModeClamp;
     mAnchors.resize(0, 0);
 }
References eWrapModeClamp, mAnchors, and mWrapMode.
~cTrajectory()
cTrajectory::~cTrajectory () virtual
Definition at line 9 of file Trajectory.cpp.
 {
 }
Member Function Documentation
AnchorToPhase()
double cTrajectory::AnchorToPhase (int idx) const virtual
Definition at line 116 of file Trajectory.cpp.
 {
     int num_anchors = GetNumAnchors();
     double phase = static_cast<double>(idx) / (num_anchors - 1);
     return phase;
 }
References GetNumAnchors().
Referenced by Filter().
Clear()
void cTrajectory::Clear () virtual
Definition at line 20 of file Trajectory.cpp.
 {
     mAnchors.resize(0, 0);
 }
References mAnchors.
Referenced by Init().
Compress()
void cTrajectory::Compress (double ratio) virtual
Definition at line 154 of file Trajectory.cpp.
 {
     Filter(ratio / 2);
     int num_anchors = GetNumAnchors();
     int num_compressed_anchors = static_cast<int>(std::ceil(num_anchors * ratio));
     Eigen::MatrixXd new_anchors = Eigen::MatrixXd(GetDim(), num_compressed_anchors);
     for (int i = 0; i < num_compressed_anchors; ++i)
     {
         double curr_phase = i / (num_compressed_anchors - 1.0);
         Eigen::VectorXd curr_val = Eval(curr_phase);
         new_anchors.col(i) = curr_val;
     }
     mAnchors = new_anchors;
 }
References Eval(), Filter(), GetDim(), GetNumAnchors(), and mAnchors.
Eval()
Eigen::VectorXd cTrajectory::Eval (double t) virtual
Definition at line 25 of file Trajectory.cpp.
 {
     const int num_anchors = GetNumAnchors();
     double a_idx = PhaseToAnchor(t);
     int idx0 = static_cast<int>(a_idx);
     int idx1 = std::min(idx0 + 1, num_anchors - 1);
     double lerp = a_idx - idx0;
     Eigen::VectorXd x0 = GetAnchor(idx0);
     Eigen::VectorXd x1 = GetAnchor(idx1);
     Eigen::VectorXd output = (1 - lerp) * x0 + lerp * x1;
     return output;
 }
References GetAnchor(), GetNumAnchors(), and PhaseToAnchor().
Referenced by Compress(), and Filter().
Filter()
void cTrajectory::Filter (double r) virtual
Definition at line 123 of file Trajectory.cpp.
 {
     double phase_step = GetPhaseStep();
     int half_samples = static_cast<int>(2 * r / phase_step);
     int num_anchors = GetNumAnchors();
     Eigen::MatrixXd anchors = mAnchors;
     for (int i = 0; i < num_anchors; ++i)
     {
         double sum_weight = 0;
         double phase = AnchorToPhase(i);
         Eigen::VectorXd val = Eigen::VectorXd::Zero(GetDim());
         for (int s = -half_samples; s <= half_samples; ++s)
         {
             double d_phase = s * phase_step;
             double curr_phase = phase + d_phase;
             Eigen::VectorXd curr_val = Eval(curr_phase);
             double w = std::exp(-d_phase * d_phase / (r * r));
             sum_weight += w;
             val += w * curr_val;
         }
         val /= sum_weight;
         anchors.col(i) = val;
     }
     mAnchors = anchors;
 }
References AnchorToPhase(), Eval(), GetDim(), GetNumAnchors(), GetPhaseStep(), and mAnchors.
Referenced by Compress().
GetAnchor()
Eigen::VectorXd cTrajectory::GetAnchor (int idx) const virtual
Definition at line 55 of file Trajectory.cpp.
 {
     return mAnchors.col(idx);
 }
References mAnchors.
Referenced by Eval().
GetDim()
int cTrajectory::GetDim () const virtual
Definition at line 45 of file Trajectory.cpp.
 {
     return static_cast<int>(mAnchors.rows());
 }
References mAnchors.
Referenced by Compress(), Filter(), and Unroll().
GetNumAnchors()
int cTrajectory::GetNumAnchors () const virtual
Definition at line 40 of file Trajectory.cpp.
 {
     return static_cast<int>(mAnchors.cols());
 }
References mAnchors.
Referenced by AnchorToPhase(), Compress(), Eval(), Filter(), GetPhaseStep(), and PhaseToAnchor().
GetPhaseStep()
double cTrajectory::GetPhaseStep () const protected virtual
Definition at line 92 of file Trajectory.cpp.
 {
     int num_anchors = GetNumAnchors();
     double phase_step = 1.0 / (num_anchors - 1);
     return phase_step;
 }
References GetNumAnchors().
Referenced by Filter().
GetSize()
int cTrajectory::GetSize () const virtual
Definition at line 50 of file Trajectory.cpp.
 {
     return static_cast<int>(mAnchors.size());
 }
References mAnchors.
Init()
void cTrajectory::Init (const Eigen::MatrixXd & anchors, eWrapMode mode) virtual
Definition at line 13 of file Trajectory.cpp.
 {
     Clear();
     mWrapMode = mode;
     mAnchors = anchors;
 }
References Clear(), mAnchors, and mWrapMode.
NormalizePhase()
double cTrajectory::NormalizePhase (double t) const protected virtual
Definition at line 65 of file Trajectory.cpp.
 {
     double norm_t = 0;
     if (mWrapMode == eWrapModeClamp)
     {
         norm_t = cMathUtil::Clamp(t, 0.0, 1.0);
     }
     else if (mWrapMode == eWrapModeLoop)
     {
         norm_t = t - static_cast<int>(t);
         if (norm_t < 0)
         {
             norm_t = 1 + norm_t;
         }
         if (norm_t == 1)
         {
             norm_t = 0;
         }
     }
     else
     {
         assert(false); // unsupported wrap mode
     }
     return norm_t;
 }
References cMathUtil::Clamp(), eWrapModeClamp, eWrapModeLoop, and mWrapMode.
Referenced by PhaseToAnchor().
PhaseToAnchor()
double cTrajectory::PhaseToAnchor (double t) const virtual
Definition at line 99 of file Trajectory.cpp.
 {
     double norm_t = NormalizePhase(t);
     int num_anchors = GetNumAnchors();
     if (mWrapMode == eWrapModeLoop)
     {
         if (norm_t == 1)
         {
             norm_t = 0;
         }
     }
     double idx = norm_t * (num_anchors - 1);
     return idx;
 }
References eWrapModeLoop, GetNumAnchors(), mWrapMode, and NormalizePhase().
Referenced by Eval().
SetAnchor()
void cTrajectory::SetAnchor (const Eigen::VectorXd & anchor, int idx) virtual
Definition at line 60 of file Trajectory.cpp.
 {
     mAnchors.col(idx) = anchor;
 }
References mAnchors.
SetUnrolled()
void cTrajectory::SetUnrolled (const Eigen::VectorXd & unrolled_data, int dim) virtual
Definition at line 181 of file Trajectory.cpp.
 {
     assert(unrolled_data.size() % dim == 0);
     int num_anchors = static_cast<int>(unrolled_data.size()) / dim;
     mAnchors.resize(dim, num_anchors);
     for (int i = 0; i < num_anchors; ++i)
     {
         mAnchors.col(i) = unrolled_data.segment(i * dim, dim);
     }
 }
References mAnchors.
Unroll()
Eigen::VectorXd cTrajectory::Unroll () const virtual
Definition at line 169 of file Trajectory.cpp.
 {
     Eigen::VectorXd unrolled(mAnchors.size());
     int dim = GetDim();
     for (int i = 0; i < mAnchors.cols(); ++i)
     {
         unrolled.segment(i * dim, dim) = mAnchors.col(i);
     }
     //Eigen::VectorXd unrolled = Eigen::VectorXd::Map(mAnchors.data(), mAnchors.size());
     return unrolled;
 }
References GetDim(), and mAnchors.
Member Data Documentation
mAnchors
Eigen::MatrixXd cTrajectory::mAnchors protected
Definition at line 37 of file Trajectory.h.
Referenced by Clear(), Compress(), cTrajectory(), Filter(), GetAnchor(), GetDim(), GetNumAnchors(), GetSize(), Init(), SetAnchor(), SetUnrolled(), and Unroll().
mWrapMode
eWrapMode cTrajectory::mWrapMode protected
Definition at line 36 of file Trajectory.h.
Referenced by cTrajectory(), Init(), NormalizePhase(), and PhaseToAnchor().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/Trajectory.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/Trajectory.cpp