My Project: cSimJoint Class Reference
cSimJoint Class Reference
#include <SimJoint.h>
Classes
struct tParams
Public Member Functions
cSimJoint ()
virtual ~cSimJoint ()
virtual void Init (std::shared_ptr< cWorld > &world, const std::shared_ptr< cSimObj > &parent_link, const std::shared_ptr< cSimObj > &child_link, const tParams &params)
virtual bool IsValid () const
virtual int GetID () const
virtual void SetID (int id)
virtual cKinTree::eJointType GetType () const
virtual void CalcWorldRotation (tVector &out_axis, double &out_theta) const
virtual tQuaternion CalcWorldRotation () const
virtual tMatrix BuildWorldTrans () const
virtual void AddTau (const Eigen::VectorXd &tau)
virtual const cSpAlg::tSpVec & GetTau () const
virtual void ApplyTau ()
virtual void ClearTau ()
virtual tVector CalcWorldPos () const
virtual tVector CalcWorldPos (const tVector &local_pos) const
virtual tVector CalcWorldVel () const
virtual tVector CalcWorldVel (const tVector &local_pos) const
virtual tVector CalcWorldAngVel () const
virtual double GetTorqueLimit () const
virtual double GetForceLimit () const
virtual void SetTorqueLimit (double lim)
virtual void SetForceLimit (double lim)
virtual const tVector & GetParentPos () const
virtual const tVector & GetChildPos () const
virtual const tQuaternion & GetParentRot () const
virtual const tQuaternion & GetChildRot () const
virtual tMatrix BuildJointChildTrans () const
virtual tMatrix BuildJointParentTrans () const
virtual tVector CalcAxisWorld () const
virtual tVector GetAxisRel () const
virtual bool HasParent () const
virtual bool HasChild () const
virtual const std::shared_ptr< cSimObj > & GetParent () const
virtual const std::shared_ptr< cSimObj > & GetChild () const
virtual void ClampTotalTorque (tVector &out_torque) const
virtual void ClampTotalForce (tVector &out_force) const
virtual const tVector & GetLimLow () const
virtual const tVector & GetLimHigh () const
virtual bool HasJointLim () const
virtual bool EnableAdjacentCollision () const
virtual int GetParamSize () const
virtual void BuildPose (Eigen::VectorXd &out_pose) const
virtual void BuildVel (Eigen::VectorXd &out_vel) const
virtual bool HasMultBody () const
virtual void Bind ()
virtual void Unbind ()
virtual tVector GetTotalTorque () const
virtual tVector GetTotalForce () const
virtual const std::shared_ptr< btTypedConstraint > & GetCons () const
virtual const std::shared_ptr< btMultiBodyConstraint > & GetMultBodyCons () const
Protected Member Functions
virtual void RemoveFromWorld ()
virtual tVector CalcParentLocalPos (const tVector &local_pos) const
virtual tVector CalcChildLocalPos (const tVector &local_pos) const
virtual double GetPrismaticOffset () const
virtual void BuildConstraint (std::shared_ptr< cWorld > &world)
virtual void BuildConstraintRevolute (std::shared_ptr< cWorld > &world)
virtual void BuildConstraintPlanar (std::shared_ptr< cWorld > &world)
virtual void BuildConstraintPrismatic (std::shared_ptr< cWorld > &world)
virtual void BuildConstraintFixed (std::shared_ptr< cWorld > &world)
virtual void BuildConstraintSpherical (std::shared_ptr< cWorld > &world)
virtual void BuildPoseRevolute (Eigen::VectorXd &out_pose) const
virtual void BuildPosePlanar (Eigen::VectorXd &out_pose) const
virtual void BuildPosePristmatic (Eigen::VectorXd &out_pose) const
virtual void BuildPoseFixed (Eigen::VectorXd &out_pose) const
virtual void BuildPoseSpherical (Eigen::VectorXd &out_pose) const
virtual void BuildVelRevolute (Eigen::VectorXd &out_pose) const
virtual void BuildVelPlanar (Eigen::VectorXd &out_pose) const
virtual void BuildVelPristmatic (Eigen::VectorXd &out_pose) const
virtual void BuildVelFixed (Eigen::VectorXd &out_pose) const
virtual void BuildVelSpherical (Eigen::VectorXd &out_vel) const
virtual void SetTotalTorque (const tVector &torque)
virtual void SetTotalForce (const tVector &force)
virtual void ApplyTorque ()
virtual void ApplyForce ()
virtual tVector CalcLocalAngVel () const
virtual tVector CalcLocalLinVel () const
Protected Attributes
tParams mParams
std::shared_ptr< cWorld > mWorld
std::shared_ptr< cSimObj > mParent
std::shared_ptr< cSimObj > mChild
cSpAlg::tSpVec mTotalTau
tQuaternion mJoint2ParentQuat
tQuaternion mJoint2ChildQuat
std::shared_ptr< btTypedConstraint > mCons
std::shared_ptr< btMultiBodyConstraint > mMultBodyCons
Detailed Description
Definition at line 8 of file SimJoint.h.
Constructor & Destructor Documentation
cSimJoint()
cSimJoint::cSimJoint ()
Definition at line 25 of file SimJoint.cpp.
 {
 }
~cSimJoint()
cSimJoint::~cSimJoint () virtual
Definition at line 29 of file SimJoint.cpp.
 {
     RemoveFromWorld();
     mWorld.reset();
 }
References mWorld, and RemoveFromWorld().
Member Function Documentation
AddTau()
void cSimJoint::AddTau (const Eigen::VectorXd & tau) virtual
Definition at line 131 of file SimJoint.cpp.
 {
     switch (GetType())
     {
     case cKinTree::eJointTypeRevolute:
         mTotalTau[2] += tau[0];
         break;
     case cKinTree::eJointTypePlanar:
         mTotalTau[3] += tau[0];
         mTotalTau[4] += tau[1];
         mTotalTau[2] += tau[2];
         break;
     case cKinTree::eJointTypePrismatic:
         mTotalTau[3] += tau[0];
         break;
     case cKinTree::eJointTypeFixed:
         break;
     case cKinTree::eJointTypeSpherical:
         mTotalTau[0] += tau[0];
         mTotalTau[1] += tau[1];
         mTotalTau[2] += tau[2];
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, GetType(), and mTotalTau.
ApplyForce()
void cSimJoint::ApplyForce () protected virtual
Definition at line 874 of file SimJoint.cpp.
 {
     tVector force = GetTotalForce();
     ClampTotalForce(force);
     SetTotalForce(force);
     tMatrix trans = BuildWorldTrans();
     force = trans * force;
     if (HasParent())
     {
         tVector parent_pt = CalcParentLocalPos(tVector::Zero());
         mParent->ApplyForce(-force, parent_pt);
     }
     mChild->ApplyForce(force, GetChildPos());
 }
References BuildWorldTrans(), CalcParentLocalPos(), ClampTotalForce(), GetChildPos(), GetTotalForce(), HasParent(), mChild, mParent, and SetTotalForce().
Referenced by ApplyTau().
ApplyTau()
void cSimJoint::ApplyTau () virtual
Definition at line 164 of file SimJoint.cpp.
 {
     switch (mParams.mType)
     {
     case cKinTree::eJointTypeRevolute:
         ApplyTorque();
         break;
     case cKinTree::eJointTypePlanar:
         ApplyTorque();
         ApplyForce();
         break;
     case cKinTree::eJointTypePrismatic:
         ApplyForce();
         break;
     case cKinTree::eJointTypeFixed:
         break;
     case cKinTree::eJointTypeSpherical:
         ApplyTorque();
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References ApplyForce(), ApplyTorque(), cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, mParams, and cSimJoint::tParams::mType.
ApplyTorque()
void cSimJoint::ApplyTorque () protected virtual
Definition at line 858 of file SimJoint.cpp.
 {
     tVector torque = GetTotalTorque();
     ClampTotalTorque(torque);
     SetTotalTorque(torque);
     tMatrix trans = BuildWorldTrans();
     torque = trans * torque;
     if (HasParent())
     {
         mParent->ApplyTorque(-torque);
     }
     mChild->ApplyTorque(torque);
 }
References BuildWorldTrans(), ClampTotalTorque(), GetTotalTorque(), HasParent(), mChild, mParent, and SetTotalTorque().
Referenced by ApplyTau().
Bind()
void cSimJoint::Bind () virtual
Definition at line 430 of file SimJoint.cpp.
 {
     if (!IsValid())
     {
         BuildConstraint(mWorld);
     }
 }
References BuildConstraint(), IsValid(), and mWorld.
BuildConstraint()
void cSimJoint::BuildConstraint (std::shared_ptr< cWorld > & world) protected virtual
Definition at line 506 of file SimJoint.cpp.
 {
     switch (GetType())
     {
     case cKinTree::eJointTypeRevolute:
         BuildConstraintRevolute(world);
         break;
     case cKinTree::eJointTypePlanar:
         BuildConstraintPlanar(world);
         break;
     case cKinTree::eJointTypePrismatic:
         BuildConstraintPrismatic(world);
         break;
     case cKinTree::eJointTypeFixed:
         BuildConstraintFixed(world);
         break;
     case cKinTree::eJointTypeSpherical:
         BuildConstraintSpherical(world);
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
     assert(mCons != nullptr ^ mMultBodyCons != nullptr);
     mWorld->AddJoint(*this);
 }
References BuildConstraintFixed(), BuildConstraintPlanar(), BuildConstraintPrismatic(), BuildConstraintRevolute(), BuildConstraintSpherical(), cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, GetType(), mCons, mMultBodyCons, and mWorld.
Referenced by Bind(), and Init().
BuildConstraintFixed()
void cSimJoint::BuildConstraintFixed (std::shared_ptr< cWorld > & world) protected virtual
Definition at line 633 of file SimJoint.cpp.
 {
     btScalar scale = static_cast<btScalar>(world->GetScale());
     auto sim_link = dynamic_cast<const cSimBodyLink*>(mParent.get());
     if (sim_link == nullptr)
     {
         const tVector& euler0 = cMathUtil::QuaternionToEuler(GetParentRot());
         const tVector& euler1 = cMathUtil::QuaternionToEuler(GetChildRot());
         btTransform anchor0_t;
         anchor0_t.setIdentity();
         const tVector& parent_pos = GetParentPos();
         btVector3 anchor0 = scale * btVector3(static_cast<btScalar>(parent_pos[0]),
                                     static_cast<btScalar>(parent_pos[1]),
                                     static_cast<btScalar>(parent_pos[2]));
         anchor0_t.setOrigin(anchor0);
         anchor0_t.getBasis().setEulerZYX(static_cast<btScalar>(euler0[0]), static_cast<btScalar>(euler0[1]), static_cast<btScalar>(euler0[2]));
         btTransform anchor1_t;
         anchor1_t.setIdentity();
         const tVector& child_pos = GetChildPos();
         btVector3 anchor1 = scale * btVector3(static_cast<btScalar>(child_pos[0]),
                                     static_cast<btScalar>(child_pos[1]),
                                     static_cast<btScalar>(child_pos[2]));
         anchor1_t.setOrigin(anchor1);
         anchor1_t.getBasis().setEulerZYX(static_cast<btScalar>(euler1[0]), static_cast<btScalar>(euler1[1]), static_cast<btScalar>(euler1[2]));
         cSimRigidBody* parent = dynamic_cast<cSimRigidBody*>(mParent.get());
         cSimRigidBody* child = dynamic_cast<cSimRigidBody*>(mChild.get());
         btFixedConstraint* cons = nullptr;
         cons = new btFixedConstraint(*(parent->GetSimBody()), *(child->GetSimBody()), anchor0_t, anchor1_t);
         mCons = std::shared_ptr<btTypedConstraint>(cons);
     }
     else
     {
         assert(false); // unsupported
     }
 }
References GetChildPos(), GetChildRot(), GetParentPos(), GetParentRot(), cSimRigidBody::GetSimBody(), mChild, mCons, mParent, and cMathUtil::QuaternionToEuler().
Referenced by BuildConstraint().
BuildConstraintPlanar()
void cSimJoint::BuildConstraintPlanar (std::shared_ptr< cWorld > & world) protected virtual
Definition at line 578 of file SimJoint.cpp.
 {
     assert(false); // unsupported
 }
Referenced by BuildConstraint().
BuildConstraintPrismatic()
void cSimJoint::BuildConstraintPrismatic (std::shared_ptr< cWorld > & world) protected virtual
Definition at line 583 of file SimJoint.cpp.
 {
     btScalar scale = static_cast<btScalar>(world->GetScale());
     auto parent_sim_link = dynamic_cast<const cSimBodyLink*>(mParent.get());
     auto child_sim_link = dynamic_cast<const cSimBodyLink*>(mChild.get());
     if (parent_sim_link == nullptr)
     {
         const tVector& euler0 = cMathUtil::QuaternionToEuler(GetParentRot());
         const tVector& euler1 = cMathUtil::QuaternionToEuler(GetChildRot());
         btTransform anchor0_t;
         anchor0_t.setIdentity();
         const tVector& parent_pos = GetParentPos();
         btVector3 anchor0 = scale * btVector3(static_cast<btScalar>(parent_pos[0]),
                                     static_cast<btScalar>(parent_pos[1]),
                                     static_cast<btScalar>(parent_pos[2]));
         anchor0_t.setOrigin(anchor0);
         anchor0_t.getBasis().setEulerZYX(static_cast<btScalar>(euler0[0]), static_cast<btScalar>(euler0[1]), static_cast<btScalar>(euler0[2]));
         btTransform anchor1_t;
         anchor1_t.setIdentity();
         const tVector& child_pos = GetChildPos();
         btVector3 anchor1 = scale * btVector3(static_cast<btScalar>(child_pos[0]),
                                             static_cast<btScalar>(child_pos[1]),
                                             static_cast<btScalar>(child_pos[2]));
         anchor1_t.setOrigin(anchor1);
         anchor1_t.getBasis().setEulerZYX(static_cast<btScalar>(euler1[0]), static_cast<btScalar>(euler1[1]), static_cast<btScalar>(euler1[2]));
         btSliderConstraint* cons = nullptr;
         cSimRigidBody* parent = dynamic_cast<cSimRigidBody*>(mParent.get());
         cSimRigidBody* child = dynamic_cast<cSimRigidBody*>(mChild.get());
         cons = new btSliderConstraint(*(parent->GetSimBody()), *(child->GetSimBody()),
                                         anchor0_t, anchor1_t, true);
         cons->setLowerLinLimit(static_cast<btScalar>(scale * mParams.mLimLow[0]));
         cons->setUpperLinLimit(static_cast<btScalar>(scale * mParams.mLimHigh[0]));
         cons->setLowerAngLimit(0.0f);
         cons->setUpperAngLimit(0.0f);
         mCons = std::shared_ptr<btTypedConstraint>(cons);
     }
     else
     {
         assert(false); // unsupported
     }
 }
References GetChildPos(), GetChildRot(), GetParentPos(), GetParentRot(), cSimRigidBody::GetSimBody(), mChild, mCons, cSimJoint::tParams::mLimHigh, cSimJoint::tParams::mLimLow, mParams, mParent, and cMathUtil::QuaternionToEuler().
Referenced by BuildConstraint().
BuildConstraintRevolute()
void cSimJoint::BuildConstraintRevolute (std::shared_ptr< cWorld > & world) protected virtual
Definition at line 533 of file SimJoint.cpp.
 {
     btScalar scale = static_cast<btScalar>(world->GetScale());
     auto sim_link = dynamic_cast<const cSimBodyLink*>(mParent.get());
     if (sim_link == nullptr)
     {
         tVector euler0 = cMathUtil::QuaternionToEuler(GetParentRot());
         tVector euler1 = cMathUtil::QuaternionToEuler(GetChildRot());
         btTransform anchor0_t;
         anchor0_t.setIdentity();
         const tVector& parent_pos = GetParentPos();
         btVector3 anchor0 = scale * btVector3(static_cast<btScalar>(parent_pos[0]),
                                     static_cast<btScalar>(parent_pos[1]),
                                     static_cast<btScalar>(parent_pos[2]));
         anchor0_t.setOrigin(anchor0);
         anchor0_t.getBasis().setEulerZYX(static_cast<btScalar>(euler0[0]), static_cast<btScalar>(euler0[1]), static_cast<btScalar>(euler0[2]));
         btTransform anchor1_t;
         anchor1_t.setIdentity();
         const tVector& child_pos = GetChildPos();
         btVector3 anchor1 = scale * btVector3(static_cast<btScalar>(child_pos[0]),
                                     static_cast<btScalar>(child_pos[1]),
                                     static_cast<btScalar>(child_pos[2]));
         anchor1_t.setOrigin(anchor1);
         anchor1_t.getBasis().setEulerZYX(static_cast<btScalar>(euler1[0]), static_cast<btScalar>(euler1[1]), static_cast<btScalar>(euler1[2]));
         btHingeConstraint* cons = nullptr;
         cSimRigidBody* parent = dynamic_cast<cSimRigidBody*>(mParent.get());
         cSimRigidBody* child = dynamic_cast<cSimRigidBody*>(mChild.get());
         cons = new btHingeConstraint(*(parent->GetSimBody()), *(child->GetSimBody()),
                                     anchor0_t, anchor1_t);
         // bullet limits are flipped
         cons->setLimit(-static_cast<btScalar>(mParams.mLimHigh[0]), -static_cast<btScalar>(mParams.mLimLow[0]));
         mCons = std::shared_ptr<btTypedConstraint>(cons);
     }
     else
     {
         assert(false); // unsupported
     }
 }
References GetChildPos(), GetChildRot(), GetParentPos(), GetParentRot(), cSimRigidBody::GetSimBody(), mChild, mCons, cSimJoint::tParams::mLimHigh, cSimJoint::tParams::mLimLow, mParams, mParent, and cMathUtil::QuaternionToEuler().
Referenced by BuildConstraint().
BuildConstraintSpherical()
void cSimJoint::BuildConstraintSpherical (std::shared_ptr< cWorld > & world) protected virtual
Definition at line 674 of file SimJoint.cpp.
 {
     btScalar scale = static_cast<btScalar>(world->GetScale());
     auto parent_sim_link = dynamic_cast<const cSimBodyLink*>(mParent.get());
     auto child_sim_link = dynamic_cast<const cSimBodyLink*>(mChild.get());
     if (parent_sim_link == nullptr)
     {
         const tVector& euler0 = cMathUtil::QuaternionToEuler(GetParentRot());
         const tVector& euler1 = cMathUtil::QuaternionToEuler(GetChildRot());
         btTransform anchor0_t;
         anchor0_t.setIdentity();
         const tVector& parent_pos = GetParentPos();
         btVector3 anchor0 = scale * btVector3(static_cast<btScalar>(parent_pos[0]),
                                     static_cast<btScalar>(parent_pos[1]),
                                     static_cast<btScalar>(parent_pos[2]));
         anchor0_t.setOrigin(anchor0);
         anchor0_t.getBasis().setEulerZYX(static_cast<btScalar>(euler0[0]), static_cast<btScalar>(euler0[1]), static_cast<btScalar>(euler0[2]));
         btTransform anchor1_t;
         anchor1_t.setIdentity();
         const tVector& child_pos = GetChildPos();
         btVector3 anchor1 = scale * btVector3(static_cast<btScalar>(child_pos[0]),
                                     static_cast<btScalar>(child_pos[1]),
                                     static_cast<btScalar>(child_pos[2]));
         anchor1_t.setOrigin(anchor1);
         anchor1_t.getBasis().setEulerZYX(static_cast<btScalar>(euler1[0]), static_cast<btScalar>(euler1[1]), static_cast<btScalar>(euler1[2]));
         cSimRigidBody* parent = dynamic_cast<cSimRigidBody*>(mParent.get());
         cSimRigidBody* child = dynamic_cast<cSimRigidBody*>(mChild.get());
         btGeneric6DofSpring2Constraint* cons = nullptr;
         cons = new btGeneric6DofSpring2Constraint(*(parent->GetSimBody()), *(child->GetSimBody()), anchor0_t, anchor1_t);
         cons->setLinearUpperLimit(btVector3(0, 0, 0));
         cons->setLinearLowerLimit(btVector3(0, 0, 0));
         // bullet limits are flipped
         cons->setAngularUpperLimit(-btVector3(static_cast<btScalar>(mParams.mLimLow[0]),
                                                 static_cast<btScalar>(mParams.mLimLow[1]),
                                                 static_cast<btScalar>(mParams.mLimLow[2])));
         cons->setAngularLowerLimit(-btVector3(static_cast<btScalar>(mParams.mLimHigh[0]),
                                                 static_cast<btScalar>(mParams.mLimHigh[1]),
                                                 static_cast<btScalar>(mParams.mLimHigh[2])));
         mCons = std::shared_ptr<btTypedConstraint>(cons);
     }
     else if (child_sim_link == nullptr)
     {
         cSimBodyLink* parent_mult = dynamic_cast<cSimBodyLink*>(mParent.get());
         cSimRigidBody* child_rb = dynamic_cast<cSimRigidBody*>(mChild.get());
         assert(GetParentRot().isApprox(tQuaternion::Identity()));
         assert(GetChildRot().isApprox(tQuaternion::Identity()));
         const tVector& parent_pos = GetParentPos();
         const tVector& child_pos = GetChildPos();
         auto cons = new btMultiBodyPoint2Point(parent_mult->GetMultBody().get(), parent_mult->GetJointID(), child_rb->GetSimBody().get(),
                                                 btVector3(parent_pos[0], parent_pos[1], parent_pos[2]),
                                                 btVector3(child_pos[0], child_pos[1], child_pos[2]));
         mMultBodyCons = std::shared_ptr<btMultiBodyConstraint>(cons);
     }
 }
References GetChildPos(), GetChildRot(), cSimBodyLink::GetJointID(), cSimBodyLink::GetMultBody(), GetParentPos(), GetParentRot(), cSimRigidBody::GetSimBody(), mChild, mCons, cSimJoint::tParams::mLimHigh, cSimJoint::tParams::mLimLow, mMultBodyCons, mParams, mParent, and cMathUtil::QuaternionToEuler().
Referenced by BuildConstraint().
BuildJointChildTrans()
tMatrix cSimJoint::BuildJointChildTrans () const virtual
Definition at line 53 of file SimJoint.cpp.
 {
     return cMathUtil::TranslateMat(GetChildPos()) * cMathUtil::RotateMat(GetChildRot());
 }
References GetChildPos(), GetChildRot(), cMathUtil::RotateMat(), and cMathUtil::TranslateMat().
Referenced by BuildWorldTrans().
BuildJointParentTrans()
tMatrix cSimJoint::BuildJointParentTrans () const virtual
Definition at line 58 of file SimJoint.cpp.
 {
     return cMathUtil::TranslateMat(GetParentPos()) * cMathUtil::RotateMat(GetParentRot());
 }
References GetParentPos(), GetParentRot(), cMathUtil::RotateMat(), and cMathUtil::TranslateMat().
Referenced by BuildWorldTrans().
BuildPose()
void cSimJoint::BuildPose (Eigen::VectorXd & out_pose) const virtual
Definition at line 358 of file SimJoint.cpp.
 {
     if (IsValid())
     {
         switch (mParams.mType)
         {
         case cKinTree::eJointTypeRevolute:
             BuildPoseRevolute(out_pose);
             break;
         case cKinTree::eJointTypePlanar:
             BuildPosePlanar(out_pose);
             break;
         case cKinTree::eJointTypePrismatic:
             BuildPosePristmatic(out_pose);
             break;
         case cKinTree::eJointTypeFixed:
             BuildPoseFixed(out_pose);
             break;
         case cKinTree::eJointTypeSpherical:
             BuildPoseSpherical(out_pose);
             break;
         default:
             assert(false); // unsupported joint type
             break;
         }
     }
     else
     {
         int param_size = GetParamSize();
         out_pose = Eigen::VectorXd::Zero(param_size);
     }
 }
References BuildPoseFixed(), BuildPosePlanar(), BuildPosePristmatic(), BuildPoseRevolute(), BuildPoseSpherical(), cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, GetParamSize(), IsValid(), mParams, and cSimJoint::tParams::mType.
BuildPoseFixed()
void cSimJoint::BuildPoseFixed (Eigen::VectorXd & out_pose) const protected virtual
Definition at line 763 of file SimJoint.cpp.
 {
     int param_size = GetParamSize();
     out_pose = Eigen::VectorXd::Zero(param_size);
 }
References GetParamSize().
Referenced by BuildPose().
BuildPosePlanar()
void cSimJoint::BuildPosePlanar (Eigen::VectorXd & out_pose) const protected virtual
Definition at line 748 of file SimJoint.cpp.
 {
     int param_size = GetParamSize();
     out_pose.resize(param_size);
     assert(false); // unsupported
 }
References GetParamSize().
Referenced by BuildPose().
BuildPosePristmatic()
void cSimJoint::BuildPosePristmatic (Eigen::VectorXd & out_pose) const protected virtual
Definition at line 755 of file SimJoint.cpp.
 {
     int param_size = GetParamSize();
     out_pose.resize(param_size);
     double delta = GetPrismaticOffset();
     out_pose[0] = delta;
 }
References GetParamSize(), and GetPrismaticOffset().
Referenced by BuildPose().
BuildPoseRevolute()
void cSimJoint::BuildPoseRevolute (Eigen::VectorXd & out_pose) const protected virtual
Definition at line 739 of file SimJoint.cpp.
 {
     int param_size = GetParamSize();
     out_pose.resize(param_size);
     btHingeConstraint* hinge = reinterpret_cast<btHingeConstraint*>(mCons.get());
     double theta = -hinge->getHingeAngle();
     out_pose[0] = theta;
 }
References GetParamSize(), and mCons.
Referenced by BuildPose().
BuildPoseSpherical()
void cSimJoint::BuildPoseSpherical (Eigen::VectorXd & out_pose) const protected virtual
Definition at line 769 of file SimJoint.cpp.
 {
     int param_size = GetParamSize();
     tVector euler = tVector::Zero();
     if (HasMultBody())
     {
         assert(false); // unsupported
     }
     else
     {
         btGeneric6DofSpring2Constraint* sphere = reinterpret_cast<btGeneric6DofSpring2Constraint*>(mCons.get());
         euler = tVector(-sphere->getAngle(0), -sphere->getAngle(1), -sphere->getAngle(2), 0);
     }
     tQuaternion q = cMathUtil::EulerToQuaternion(euler);
     bool flip = (q.w() < 0);
     out_pose.resize(param_size);
     out_pose[0] = (flip) ? -q.w() : q.w();
     out_pose[1] = (flip) ? -q.x() : q.x();
     out_pose[2] = (flip) ? -q.y() : q.y();
     out_pose[3] = (flip) ? -q.z() : q.z();
 }
References cMathUtil::EulerToQuaternion(), GetParamSize(), HasMultBody(), and mCons.
Referenced by BuildPose().
BuildVel()
void cSimJoint::BuildVel (Eigen::VectorXd & out_vel) const virtual
Definition at line 391 of file SimJoint.cpp.
 {
     if (IsValid())
     {
         switch (mParams.mType)
         {
         case cKinTree::eJointTypeRevolute:
             BuildVelRevolute(out_vel);
             break;
         case cKinTree::eJointTypePlanar:
             BuildVelPlanar(out_vel);
             break;
         case cKinTree::eJointTypePrismatic:
             BuildVelPristmatic(out_vel);
             break;
         case cKinTree::eJointTypeFixed:
             BuildVelFixed(out_vel);
             break;
         case cKinTree::eJointTypeSpherical:
             BuildVelSpherical(out_vel);
             break;
         default:
             assert(false); // unsupported joint type
             break;
         }
     }
     else
     {
         int param_size = GetParamSize();
         out_vel = Eigen::VectorXd::Zero(param_size);
     }
 }
References BuildVelFixed(), BuildVelPlanar(), BuildVelPristmatic(), BuildVelRevolute(), BuildVelSpherical(), cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, GetParamSize(), IsValid(), mParams, and cSimJoint::tParams::mType.
BuildVelFixed()
void cSimJoint::BuildVelFixed (Eigen::VectorXd & out_pose) const protected virtual
Definition at line 818 of file SimJoint.cpp.
 {
     int param_size = GetParamSize();
     out_pose.resize(param_size);
 }
References GetParamSize().
Referenced by BuildVel().
BuildVelPlanar()
void cSimJoint::BuildVelPlanar (Eigen::VectorXd & out_pose) const protected virtual
Definition at line 802 of file SimJoint.cpp.
 {
     int param_size = GetParamSize();
     out_pose = std::numeric_limits<double>::quiet_NaN() * Eigen::VectorXd::Ones(param_size);
     assert(false); // unsupported
 }
References GetParamSize().
Referenced by BuildVel().
BuildVelPristmatic()
void cSimJoint::BuildVelPristmatic (Eigen::VectorXd & out_pose) const protected virtual
Definition at line 809 of file SimJoint.cpp.
 {
     assert(mParams.mType == cKinTree::eJointTypePrismatic);
     int param_size = GetParamSize();
     out_pose.resize(param_size);
     tVector vel = CalcLocalLinVel();
     out_pose[0] = vel[0];
 }
References CalcLocalLinVel(), cKinTree::eJointTypePrismatic, GetParamSize(), mParams, and cSimJoint::tParams::mType.
Referenced by BuildVel().
BuildVelRevolute()
void cSimJoint::BuildVelRevolute (Eigen::VectorXd & out_pose) const protected virtual
Definition at line 794 of file SimJoint.cpp.
 {
     int param_size = GetParamSize();
     out_pose.resize(param_size);
     tVector vel = CalcLocalAngVel();
     out_pose[0] = vel[2];
 }
References CalcLocalAngVel(), and GetParamSize().
Referenced by BuildVel().
BuildVelSpherical()
void cSimJoint::BuildVelSpherical (Eigen::VectorXd & out_vel) const protected virtual
Definition at line 824 of file SimJoint.cpp.
 {
     int param_size = GetParamSize();
     out_vel.resize(param_size);
     tVector vel = CalcLocalAngVel();
     out_vel.segment(0, param_size) = vel.segment(0, param_size);
 }
References CalcLocalAngVel(), and GetParamSize().
Referenced by BuildVel().
BuildWorldTrans()
tMatrix cSimJoint::BuildWorldTrans () const virtual
Definition at line 115 of file SimJoint.cpp.
 {
     tMatrix mat = tMatrix::Identity();
     if (HasChild())
     {
         mat = mChild->GetWorldTransform();
         mat = mat * BuildJointChildTrans();
     }
     else
     {
         mat = mParent->GetWorldTransform();
         mat = mat * BuildJointParentTrans();
     }
     return mat;
 }
References BuildJointChildTrans(), BuildJointParentTrans(), HasChild(), mChild, and mParent.
Referenced by ApplyForce(), ApplyTorque(), CalcAxisWorld(), CalcLocalAngVel(), CalcLocalLinVel(), CalcWorldPos(), and CalcWorldRotation().
CalcAxisWorld()
tVector cSimJoint::CalcAxisWorld () const virtual
Definition at line 63 of file SimJoint.cpp.
 {
     tVector axis_rel = GetAxisRel();
     axis_rel[3] = 0;
     tMatrix trans = BuildWorldTrans();
     tVector axis = trans * axis_rel;
     return axis;
 }
References BuildWorldTrans(), and GetAxisRel().
CalcChildLocalPos()
tVector cSimJoint::CalcChildLocalPos (const tVector & local_pos) const protected virtual
Definition at line 477 of file SimJoint.cpp.
 {
     tVector child_pos = cMathUtil::QuatRotVec(GetChildRot(), local_pos);
     child_pos += GetChildPos();
     return child_pos;
 }
References GetChildPos(), GetChildRot(), and cMathUtil::QuatRotVec().
Referenced by CalcWorldVel().
CalcLocalAngVel()
tVector cSimJoint::CalcLocalAngVel () const protected virtual
Definition at line 891 of file SimJoint.cpp.
 {
     tVector ang_velp = tVector::Zero();
     if (HasParent())
     {
         ang_velp = mParent->GetAngularVelocity();
     }
     tVector ang_velc = mChild->GetAngularVelocity();
     tVector vel = ang_velc - ang_velp;
     vel[3] = 0;
     tMatrix trans = BuildWorldTrans();
     vel = trans.transpose() * vel;
     vel[3] = 0;
     return vel;
 }
References BuildWorldTrans(), HasParent(), mChild, and mParent.
Referenced by BuildVelRevolute(), and BuildVelSpherical().
CalcLocalLinVel()
tVector cSimJoint::CalcLocalLinVel () const protected virtual
Definition at line 909 of file SimJoint.cpp.
 {
     tVector velp = tVector::Zero();
     if (HasParent())
     {
         tVector parent_pt = CalcParentLocalPos(tVector::Zero());
         velp = mParent->GetLinearVelocity(parent_pt);
     }
     tVector velc = mChild->GetLinearVelocity(GetChildPos());
     tVector delta_vel = velc - velp;
     delta_vel[3] = 0;
     tMatrix trans = BuildWorldTrans();
     delta_vel = trans.transpose() * delta_vel;
     delta_vel[3] = 0;
     return delta_vel;
 }
References BuildWorldTrans(), CalcParentLocalPos(), GetChildPos(), HasParent(), mChild, and mParent.
Referenced by BuildVelPristmatic().
CalcParentLocalPos()
tVector cSimJoint::CalcParentLocalPos (const tVector & local_pos) const protected virtual
Definition at line 462 of file SimJoint.cpp.
 {
     cKinTree::eJointType joint_type = GetType();
     tVector pt = local_pos;
     if (joint_type == cKinTree::eJointTypePrismatic)
     {
         double delta = GetPrismaticOffset();
         pt[0] += delta;
     }
     tVector parent_pos = cMathUtil::QuatRotVec(GetParentRot(), pt);
     parent_pos += GetParentPos();
     return parent_pos;
 }
References cKinTree::eJointTypePrismatic, GetParentPos(), GetParentRot(), GetPrismaticOffset(), GetType(), and cMathUtil::QuatRotVec().
Referenced by ApplyForce(), CalcLocalLinVel(), and CalcWorldVel().
CalcWorldAngVel()
tVector cSimJoint::CalcWorldAngVel () const virtual
Definition at line 248 of file SimJoint.cpp.
 {
     if (HasChild())
     {
         return mChild->GetAngularVelocity();
     }
     else
     {
         return mParent->GetAngularVelocity();
     }
 }
References HasChild(), mChild, and mParent.
CalcWorldPos() [1/2]
tVector cSimJoint::CalcWorldPos () const virtual
Definition at line 194 of file SimJoint.cpp.
 {
     tVector world_pos;
     if (HasChild())
     {
         world_pos = mChild->LocalToWorldPos(GetChildPos());
     }
     else
     {
         assert(GetType() != cKinTree::eJointTypePrismatic
             && GetType() != cKinTree::eJointTypePlanar);
         world_pos = mParent->LocalToWorldPos(GetParentPos());
     }
     return world_pos;
 }
References cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, GetChildPos(), GetParentPos(), GetType(), HasChild(), mChild, and mParent.
CalcWorldPos() [2/2]
tVector cSimJoint::CalcWorldPos (const tVector & local_pos) const virtual
Definition at line 210 of file SimJoint.cpp.
 {
     tVector world_pos = local_pos;
     world_pos[3] = 1;
     tMatrix trans = BuildWorldTrans();
     world_pos = trans * world_pos;
     world_pos[3] = 0;
     return world_pos;
 }
References BuildWorldTrans().
CalcWorldRotation() [1/2]
tQuaternion cSimJoint::CalcWorldRotation () const virtual
Definition at line 102 of file SimJoint.cpp.
 {
     tMatrix mat = BuildWorldTrans();
     tQuaternion q = cMathUtil::RotMatToQuaternion(mat);
     return q;
 }
References BuildWorldTrans(), and cMathUtil::RotMatToQuaternion().
CalcWorldRotation() [2/2]
void cSimJoint::CalcWorldRotation (tVector & out_axis, double & out_theta) const virtual
Definition at line 109 of file SimJoint.cpp.
 {
     tMatrix mat = BuildWorldTrans();
     cMathUtil::RotMatToAxisAngle(mat, out_axis, out_theta);
 }
References BuildWorldTrans(), and cMathUtil::RotMatToAxisAngle().
CalcWorldVel() [1/2]
tVector cSimJoint::CalcWorldVel () const virtual
Definition at line 220 of file SimJoint.cpp.
 {
     if (HasChild())
     {
         tVector pos = GetChildPos();
         return mChild->GetLinearVelocity(pos);
     }
     else
     {
         tVector pos = GetParentPos();
         return mParent->GetLinearVelocity(pos);
     }
 }
References GetChildPos(), GetParentPos(), HasChild(), mChild, and mParent.
CalcWorldVel() [2/2]
tVector cSimJoint::CalcWorldVel (const tVector & local_pos) const virtual
Definition at line 234 of file SimJoint.cpp.
 {
     if (HasChild())
     {
         tVector pt = CalcChildLocalPos(local_pos);
         return mChild->GetLinearVelocity(pt);
     }
     else
     {
         tVector pt = CalcParentLocalPos(local_pos);
         return mParent->GetLinearVelocity(pt);
     }
 }
References CalcChildLocalPos(), CalcParentLocalPos(), HasChild(), mChild, and mParent.
ClampTotalForce()
void cSimJoint::ClampTotalForce (tVector & out_force) const virtual
Definition at line 320 of file SimJoint.cpp.
 {
     double mag = out_force.norm();
     double force_lim = GetForceLimit();
     if (mag > force_lim)
     {
         out_force *= force_lim / mag;
     }
 }
References GetForceLimit().
Referenced by ApplyForce().
ClampTotalTorque()
void cSimJoint::ClampTotalTorque (tVector & out_torque) const virtual
Definition at line 310 of file SimJoint.cpp.
 {
     double mag = out_torque.norm();
     double torque_lim = GetTorqueLimit();
     if (mag > torque_lim)
     {
         out_torque *= torque_lim / mag;
     }
 }
References GetTorqueLimit().
Referenced by ApplyTorque().
ClearTau()
void cSimJoint::ClearTau () virtual
Definition at line 189 of file SimJoint.cpp.
 {
     mTotalTau.setZero();
 }
References mTotalTau.
EnableAdjacentCollision()
bool cSimJoint::EnableAdjacentCollision () const virtual
Definition at line 348 of file SimJoint.cpp.
 {
     return mParams.mEnableAdjacentCollision;
 }
References cSimJoint::tParams::mEnableAdjacentCollision, and mParams.
Referenced by cWorld::AddJoint().
GetAxisRel()
tVector cSimJoint::GetAxisRel () const virtual
Definition at line 72 of file SimJoint.cpp.
 {
     return tVector(0, 0, 1, 0);
 }
Referenced by CalcAxisWorld().
GetChild()
const std::shared_ptr< cSimObj > & cSimJoint::GetChild () const virtual
Definition at line 305 of file SimJoint.cpp.
 {
     return mChild;
 }
References mChild.
GetChildPos()
const tVector & cSimJoint::GetChildPos () const virtual
Definition at line 285 of file SimJoint.cpp.
 {
     return mParams.mChildPos;
 }
References cSimJoint::tParams::mChildPos, and mParams.
Referenced by ApplyForce(), BuildConstraintFixed(), BuildConstraintPrismatic(), BuildConstraintRevolute(), BuildConstraintSpherical(), BuildJointChildTrans(), CalcChildLocalPos(), CalcLocalLinVel(), CalcWorldPos(), and CalcWorldVel().
GetChildRot()
const tQuaternion & cSimJoint::GetChildRot () const virtual
Definition at line 295 of file SimJoint.cpp.
 {
     return mParams.mChildRot;
 }
References cSimJoint::tParams::mChildRot, and mParams.
Referenced by BuildConstraintFixed(), BuildConstraintPrismatic(), BuildConstraintRevolute(), BuildConstraintSpherical(), BuildJointChildTrans(), and CalcChildLocalPos().
GetCons()
const std::shared_ptr< btTypedConstraint > & cSimJoint::GetCons () const virtual
Definition at line 843 of file SimJoint.cpp.
 {
     return mCons;
 }
References mCons.
Referenced by cWorld::AddJoint(), and cWorld::RemoveJoint().
GetForceLimit()
double cSimJoint::GetForceLimit () const virtual
Definition at line 265 of file SimJoint.cpp.
 {
     return mParams.mForceLimit;
 }
References cSimJoint::tParams::mForceLimit, and mParams.
Referenced by ClampTotalForce().
GetID()
int cSimJoint::GetID () const virtual
Definition at line 87 of file SimJoint.cpp.
 {
     return mParams.mID;
 }
References cSimJoint::tParams::mID, and mParams.
GetLimHigh()
const tVector & cSimJoint::GetLimHigh () const virtual
Definition at line 335 of file SimJoint.cpp.
 {
     return mParams.mLimHigh;
 }
References cSimJoint::tParams::mLimHigh, and mParams.
GetLimLow()
const tVector & cSimJoint::GetLimLow () const virtual
Definition at line 330 of file SimJoint.cpp.
 {
     return mParams.mLimLow;
 }
References cSimJoint::tParams::mLimLow, and mParams.
GetMultBodyCons()
const std::shared_ptr< btMultiBodyConstraint > & cSimJoint::GetMultBodyCons () const virtual
Definition at line 848 of file SimJoint.cpp.
 {
     return mMultBodyCons;
 }
References mMultBodyCons.
Referenced by cWorld::AddJoint(), and cWorld::RemoveJoint().
GetParamSize()
int cSimJoint::GetParamSize () const virtual
Definition at line 353 of file SimJoint.cpp.
 {
     return cKinTree::GetJointParamSize(GetType());
 }
References cKinTree::GetJointParamSize(), and GetType().
Referenced by BuildPose(), BuildPoseFixed(), BuildPosePlanar(), BuildPosePristmatic(), BuildPoseRevolute(), BuildPoseSpherical(), BuildVel(), BuildVelFixed(), BuildVelPlanar(), BuildVelPristmatic(), BuildVelRevolute(), and BuildVelSpherical().
GetParent()
const std::shared_ptr< cSimObj > & cSimJoint::GetParent () const virtual
Definition at line 300 of file SimJoint.cpp.
 {
     return mParent;
 }
References mParent.
GetParentPos()
const tVector & cSimJoint::GetParentPos () const virtual
Definition at line 280 of file SimJoint.cpp.
 {
     return mParams.mParentPos;
 }
References mParams, and cSimJoint::tParams::mParentPos.
Referenced by BuildConstraintFixed(), BuildConstraintPrismatic(), BuildConstraintRevolute(), BuildConstraintSpherical(), BuildJointParentTrans(), CalcParentLocalPos(), CalcWorldPos(), and CalcWorldVel().
GetParentRot()
const tQuaternion & cSimJoint::GetParentRot () const virtual
Definition at line 290 of file SimJoint.cpp.
 {
     return mParams.mParentRot;
 }
References mParams, and cSimJoint::tParams::mParentRot.
Referenced by BuildConstraintFixed(), BuildConstraintPrismatic(), BuildConstraintRevolute(), BuildConstraintSpherical(), BuildJointParentTrans(), and CalcParentLocalPos().
GetPrismaticOffset()
double cSimJoint::GetPrismaticOffset () const protected virtual
Definition at line 484 of file SimJoint.cpp.
 {
     assert(mParams.mType == cKinTree::eJointTypePrismatic);
     double scale = mWorld->GetScale();
     double delta = 0;
     if (HasMultBody())
     {
         //const btMultiBodySliderConstraint* prismatic = reinterpret_cast<const btMultiBodySliderConstraint*>(mMultBodyCons.get());
         //delta = prismatic->getPosition(0);
         //delta /= scale;
         assert(false); // unsupported
     }
     else
     {
         const btSliderConstraint* prismatic = reinterpret_cast<const btSliderConstraint*>(mCons.get());
         delta = prismatic->getLinearPos();
         delta /= scale;
     }
     return delta;
 }
References cKinTree::eJointTypePrismatic, HasMultBody(), mCons, mParams, cSimJoint::tParams::mType, and mWorld.
Referenced by BuildPosePristmatic(), and CalcParentLocalPos().
GetTau()
const cSpAlg::tSpVec & cSimJoint::GetTau () const virtual
Definition at line 159 of file SimJoint.cpp.
 {
     return mTotalTau;
 }
References mTotalTau.
GetTorqueLimit()
double cSimJoint::GetTorqueLimit () const virtual
Definition at line 260 of file SimJoint.cpp.
 {
     return mParams.mTorqueLimit;
 }
References mParams, and cSimJoint::tParams::mTorqueLimit.
Referenced by ClampTotalTorque().
GetTotalForce()
tVector cSimJoint::GetTotalForce () const virtual
Definition at line 837 of file SimJoint.cpp.
 {
     tVector force = cSpAlg::GetV(mTotalTau);
     return force;
 }
References cSpAlg::GetV(), and mTotalTau.
Referenced by ApplyForce().
GetTotalTorque()
tVector cSimJoint::GetTotalTorque () const virtual
Definition at line 446 of file SimJoint.cpp.
 {
     tVector torque = cSpAlg::GetOmega(mTotalTau);
     return torque;
 }
References cSpAlg::GetOmega(), and mTotalTau.
Referenced by ApplyTorque().
GetType()
cKinTree::eJointType cSimJoint::GetType () const virtual
Definition at line 97 of file SimJoint.cpp.
 {
     return mParams.mType;
 }
References mParams, and cSimJoint::tParams::mType.
Referenced by AddTau(), BuildConstraint(), CalcParentLocalPos(), CalcWorldPos(), and GetParamSize().
HasChild()
bool cSimJoint::HasChild () const virtual
Definition at line 82 of file SimJoint.cpp.
 {
     return mChild != nullptr;
 }
References mChild.
Referenced by BuildWorldTrans(), CalcWorldAngVel(), CalcWorldPos(), and CalcWorldVel().
HasJointLim()
bool cSimJoint::HasJointLim () const virtual
Definition at line 340 of file SimJoint.cpp.
 {
     return (mParams.mLimLow[0] <= mParams.mLimLow[0]
         || mParams.mLimLow[1] <= mParams.mLimLow[1]
         || mParams.mLimLow[2] <= mParams.mLimLow[2]
         || mParams.mLimLow[3] <= mParams.mLimLow[3]);
 }
References cSimJoint::tParams::mLimLow, and mParams.
HasMultBody()
bool cSimJoint::HasMultBody () const virtual
Definition at line 424 of file SimJoint.cpp.
 {
     assert(mCons == nullptr || mMultBodyCons == nullptr);
     return mMultBodyCons != nullptr;
 }
References mCons, and mMultBodyCons.
Referenced by BuildPoseSpherical(), and GetPrismaticOffset().
HasParent()
bool cSimJoint::HasParent () const virtual
Definition at line 77 of file SimJoint.cpp.
 {
     return mParent != nullptr;
 }
References mParent.
Referenced by ApplyForce(), ApplyTorque(), CalcLocalAngVel(), and CalcLocalLinVel().
Init()
void cSimJoint::Init (std::shared_ptr< cWorld > & world, const std::shared_ptr< cSimObj > & parent_link, const std::shared_ptr< cSimObj > & child_link, const tParams & params) virtual
Definition at line 35 of file SimJoint.cpp.
 {
     RemoveFromWorld();
     mParent = parent;
     mChild = child;
     mParams = params;
     mWorld = world;
     BuildConstraint(mWorld);
     assert(IsValid());
 }
References BuildConstraint(), IsValid(), mChild, mParams, mParent, mWorld, and RemoveFromWorld().
IsValid()
bool cSimJoint::IsValid () const virtual
Definition at line 48 of file SimJoint.cpp.
 {
     return mCons != nullptr || mMultBodyCons != nullptr;
 }
References mCons, and mMultBodyCons.
Referenced by Bind(), BuildPose(), BuildVel(), Init(), and Unbind().
RemoveFromWorld()
void cSimJoint::RemoveFromWorld () protected virtual
Definition at line 452 of file SimJoint.cpp.
 {
     if (mWorld != nullptr)
     {
         mWorld->RemoveJoint(*this);
         mCons.reset();
         mMultBodyCons.reset();
     }
 }
References mCons, mMultBodyCons, and mWorld.
Referenced by Init(), Unbind(), and ~cSimJoint().
SetForceLimit()
void cSimJoint::SetForceLimit (double lim) virtual
Definition at line 275 of file SimJoint.cpp.
 {
     mParams.mForceLimit = lim;
 }
References cSimJoint::tParams::mForceLimit, and mParams.
SetID()
void cSimJoint::SetID (int id) virtual
Definition at line 92 of file SimJoint.cpp.
 {
     mParams.mID = id;
 }
References cSimJoint::tParams::mID, and mParams.
SetTorqueLimit()
void cSimJoint::SetTorqueLimit (double lim) virtual
Definition at line 270 of file SimJoint.cpp.
 {
     mParams.mTorqueLimit = lim;
 }
References mParams, and cSimJoint::tParams::mTorqueLimit.
SetTotalForce()
void cSimJoint::SetTotalForce (const tVector & force) protected virtual
Definition at line 853 of file SimJoint.cpp.
 {
     cSpAlg::SetV(force, mTotalTau);
 }
References mTotalTau, and cSpAlg::SetV().
Referenced by ApplyForce().
SetTotalTorque()
void cSimJoint::SetTotalTorque (const tVector & torque) protected virtual
Definition at line 832 of file SimJoint.cpp.
 {
     cSpAlg::SetOmega(torque, mTotalTau);
 }
References mTotalTau, and cSpAlg::SetOmega().
Referenced by ApplyTorque().
Unbind()
void cSimJoint::Unbind () virtual
Definition at line 438 of file SimJoint.cpp.
 {
     if (IsValid())
     {
         RemoveFromWorld();
     }
 }
References IsValid(), and RemoveFromWorld().
Member Data Documentation
mChild
std::shared_ptr<cSimObj> cSimJoint::mChild protected
Definition at line 104 of file SimJoint.h.
Referenced by ApplyForce(), ApplyTorque(), BuildConstraintFixed(), BuildConstraintPrismatic(), BuildConstraintRevolute(), BuildConstraintSpherical(), BuildWorldTrans(), CalcLocalAngVel(), CalcLocalLinVel(), CalcWorldAngVel(), CalcWorldPos(), CalcWorldVel(), GetChild(), HasChild(), and Init().
mCons
std::shared_ptr<btTypedConstraint> cSimJoint::mCons protected
Definition at line 111 of file SimJoint.h.
Referenced by BuildConstraint(), BuildConstraintFixed(), BuildConstraintPrismatic(), BuildConstraintRevolute(), BuildConstraintSpherical(), BuildPoseRevolute(), BuildPoseSpherical(), GetCons(), GetPrismaticOffset(), HasMultBody(), IsValid(), and RemoveFromWorld().
mJoint2ChildQuat
tQuaternion cSimJoint::mJoint2ChildQuat protected
Definition at line 109 of file SimJoint.h.
mJoint2ParentQuat
tQuaternion cSimJoint::mJoint2ParentQuat protected
Definition at line 108 of file SimJoint.h.
mMultBodyCons
std::shared_ptr<btMultiBodyConstraint> cSimJoint::mMultBodyCons protected
Definition at line 112 of file SimJoint.h.
Referenced by BuildConstraint(), BuildConstraintSpherical(), GetMultBodyCons(), HasMultBody(), IsValid(), and RemoveFromWorld().
mParams
tParams cSimJoint::mParams protected
Definition at line 101 of file SimJoint.h.
Referenced by ApplyTau(), BuildConstraintPrismatic(), BuildConstraintRevolute(), BuildConstraintSpherical(), BuildPose(), BuildVel(), BuildVelPristmatic(), EnableAdjacentCollision(), GetChildPos(), GetChildRot(), GetForceLimit(), GetID(), GetLimHigh(), GetLimLow(), GetParentPos(), GetParentRot(), GetPrismaticOffset(), GetTorqueLimit(), GetType(), HasJointLim(), Init(), SetForceLimit(), SetID(), and SetTorqueLimit().
mParent
std::shared_ptr<cSimObj> cSimJoint::mParent protected
Definition at line 103 of file SimJoint.h.
Referenced by ApplyForce(), ApplyTorque(), BuildConstraintFixed(), BuildConstraintPrismatic(), BuildConstraintRevolute(), BuildConstraintSpherical(), BuildWorldTrans(), CalcLocalAngVel(), CalcLocalLinVel(), CalcWorldAngVel(), CalcWorldPos(), CalcWorldVel(), GetParent(), HasParent(), and Init().
mTotalTau
cSpAlg::tSpVec cSimJoint::mTotalTau protected
Definition at line 107 of file SimJoint.h.
Referenced by AddTau(), ClearTau(), GetTau(), GetTotalForce(), GetTotalTorque(), SetTotalForce(), and SetTotalTorque().
mWorld
std::shared_ptr<cWorld> cSimJoint::mWorld protected
Definition at line 102 of file SimJoint.h.
Referenced by Bind(), BuildConstraint(), GetPrismaticOffset(), Init(), RemoveFromWorld(), and ~cSimJoint().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimJoint.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimJoint.cpp