My Project: cRLScene Class Reference
cRLScene Class Reference abstract
#include <RLScene.h>
Public Types
enum eMode { eModeTrain, eModeTest, eModeMax }
enum eTerminate { eTerminateNull, eTerminateFail, eTerminateSucc, eTerminateMax }
Public Member Functions
virtual ~cRLScene ()
virtual void Init ()
virtual void Clear ()
virtual int GetNumAgents () const =0
virtual bool NeedNewAction (int agent_id) const =0
virtual void RecordState (int agent_id, Eigen::VectorXd &out_state) const =0
virtual void RecordGoal (int agent_id, Eigen::VectorXd &out_goal) const =0
virtual void SetAction (int agent_id, const Eigen::VectorXd &action)=0
virtual eActionSpace GetActionSpace (int agent_id) const =0
virtual int GetStateSize (int agent_id) const =0
virtual int GetGoalSize (int agent_id) const =0
virtual int GetActionSize (int agent_id) const =0
virtual int GetNumActions (int agent_id) const =0
virtual void BuildStateOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const =0
virtual void BuildGoalOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const =0
virtual void BuildActionOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const =0
virtual void BuildActionBounds (int agent_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max) const =0
virtual void BuildStateNormGroups (int agent_id, Eigen::VectorXi &out_groups) const =0
virtual void BuildGoalNormGroups (int agent_id, Eigen::VectorXi &out_groups) const =0
virtual double CalcReward (int agent_id) const =0
virtual double GetRewardMin (int agent_id) const =0
virtual double GetRewardMax (int agent_id) const =0
virtual double GetRewardFail (int agent_id)
virtual double GetRewardSucc (int agent_id)
virtual bool IsEpisodeEnd () const
virtual eTerminate CheckTerminate (int agent_id) const
virtual void SetSampleCount (int count)
virtual void SetMode (eMode mode)
virtual void LogVal (int agent_id, double val)=0
Public Member Functions inherited from cScene
virtual ~cScene ()
virtual void ParseArgs (const std::shared_ptr< cArgParser > &parser)
virtual void Reset ()
virtual void Update (double timestep)
virtual void Draw ()
virtual void Keyboard (unsigned char key, double device_x, double device_y)
virtual void MouseClick (int button, int state, double device_x, double device_y)
virtual void MouseMove (double device_x, double device_y)
virtual void Reshape (int w, int h)
virtual void Shutdown ()
virtual bool IsDone () const
virtual double GetTime () const
virtual bool HasRandSeed () const
virtual void SetRandSeed (unsigned long seed)
virtual unsigned long GetRandSeed () const
virtual bool CheckValidEpisode () const
virtual std::string GetName () const =0
Protected Member Functions
cRLScene ()
Protected Member Functions inherited from cScene
cScene ()
virtual void ResetParams ()
virtual void ResetScene ()
virtual void InitTimers ()
virtual void ResetTimers ()
virtual void UpdateTimers (double timestep)
Protected Attributes
eMode mMode
int mSampleCount
Protected Attributes inherited from cScene
cRand mRand
bool mHasRandSeed
unsigned long mRandSeed
std::shared_ptr< cArgParser > mArgParser
cTimer::tParams mTimerParams
cTimer mTimer
Detailed Description
Definition at line 8 of file RLScene.h.
Member Enumeration Documentation
eMode
enum cRLScene::eMode
Enumerator
eModeTrain
eModeTest
eModeMax
Definition at line 11 of file RLScene.h.
     {
         eModeTrain,
         eModeTest,
         eModeMax
     };
eTerminate
enum cRLScene::eTerminate
Enumerator
eTerminateNull
eTerminateFail
eTerminateSucc
eTerminateMax
Definition at line 18 of file RLScene.h.
     {
         eTerminateNull,
         eTerminateFail,
         eTerminateSucc,
         eTerminateMax
     };
Constructor & Destructor Documentation
~cRLScene()
cRLScene::~cRLScene () virtual
Definition at line 9 of file RLScene.cpp.
 {
 }
cRLScene()
cRLScene::cRLScene () protected
Definition at line 3 of file RLScene.cpp.
 {
     mMode = eModeTrain;
     mSampleCount = 0;
 }
References eModeTrain, mMode, and mSampleCount.
Member Function Documentation
BuildActionBounds()
virtual void cRLScene::BuildActionBounds (int agent_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::BuildActionBounds().
BuildActionOffsetScale()
virtual void cRLScene::BuildActionOffsetScale (int agent_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::BuildActionOffsetScale().
BuildGoalNormGroups()
virtual void cRLScene::BuildGoalNormGroups (int agent_id, Eigen::VectorXi & out_groups) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::BuildGoalNormGroups().
BuildGoalOffsetScale()
virtual void cRLScene::BuildGoalOffsetScale (int agent_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::BuildGoalOffsetScale().
BuildStateNormGroups()
virtual void cRLScene::BuildStateNormGroups (int agent_id, Eigen::VectorXi & out_groups) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::BuildStateNormGroups().
BuildStateOffsetScale()
virtual void cRLScene::BuildStateOffsetScale (int agent_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::BuildStateOffsetScale().
CalcReward()
virtual double cRLScene::CalcReward (int agent_id) const pure virtual
Implemented in cRLSceneSimChar, cDrawRLScene, and cSceneImitate.
Referenced by cDrawRLScene::CalcReward().
CheckTerminate()
cRLScene::eTerminate cRLScene::CheckTerminate (int agent_id) const virtual
Reimplemented in cRLSceneSimChar, cDrawRLScene, and cSceneImitate.
Definition at line 52 of file RLScene.cpp.
 {
     return eTerminateNull;
 }
References eTerminateNull.
Referenced by cDrawRLScene::CheckTerminate(), and IsEpisodeEnd().
Clear()
void cRLScene::Clear () virtual
Reimplemented from cScene.
Reimplemented in cRLSceneSimChar, and cDrawSceneImitate.
Definition at line 19 of file RLScene.cpp.
 {
     cScene::Clear();
     mSampleCount = 0;
 }
References cScene::Clear(), and mSampleCount.
Referenced by cDrawSceneImitate::Clear(), and cRLSceneSimChar::Clear().
GetActionSize()
virtual int cRLScene::GetActionSize (int agent_id) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::GetActionSize().
GetActionSpace()
virtual eActionSpace cRLScene::GetActionSpace (int agent_id) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::GetActionSpace().
GetGoalSize()
virtual int cRLScene::GetGoalSize (int agent_id) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::GetGoalSize().
GetNumActions()
virtual int cRLScene::GetNumActions (int agent_id) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::GetNumActions().
GetNumAgents()
virtual int cRLScene::GetNumAgents () const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::GetNumAgents(), and IsEpisodeEnd().
GetRewardFail()
double cRLScene::GetRewardFail (int agent_id) virtual
Reimplemented in cDrawRLScene.
Definition at line 26 of file RLScene.cpp.
 {
     return GetRewardMin(agent_id);
 }
References GetRewardMin().
Referenced by cDrawRLScene::GetRewardFail().
GetRewardMax()
virtual double cRLScene::GetRewardMax (int agent_id) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::GetRewardMax(), and GetRewardSucc().
GetRewardMin()
virtual double cRLScene::GetRewardMin (int agent_id) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by GetRewardFail(), and cDrawRLScene::GetRewardMin().
GetRewardSucc()
double cRLScene::GetRewardSucc (int agent_id) virtual
Reimplemented in cDrawRLScene.
Definition at line 31 of file RLScene.cpp.
 {
     return GetRewardMax(agent_id);
 }
References GetRewardMax().
Referenced by cDrawRLScene::GetRewardSucc().
GetStateSize()
virtual int cRLScene::GetStateSize (int agent_id) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::GetStateSize().
Init()
void cRLScene::Init () virtual
Reimplemented from cScene.
Reimplemented in cRLSceneSimChar, cDrawSceneImitate, cSceneImitate, and cDrawRLScene.
Definition at line 13 of file RLScene.cpp.
 {
     cScene::Init();
     mSampleCount = 0;
 }
References cScene::Init(), and mSampleCount.
Referenced by cDrawRLScene::Init(), cDrawSceneImitate::Init(), and cRLSceneSimChar::Init().
IsEpisodeEnd()
bool cRLScene::IsEpisodeEnd () const virtual
Reimplemented from cScene.
Reimplemented in cDrawRLScene, and cDrawSceneImitate.
Definition at line 36 of file RLScene.cpp.
 {
     bool is_end = cScene::IsEpisodeEnd();
     eTerminate termin = eTerminateNull;
     for (int i = 0; i < GetNumAgents(); ++i)
     {
         termin = CheckTerminate(i);
         if (termin != eTerminateNull)
         {
             is_end = true;
             break;
         }
     }
     return is_end;
 }
References CheckTerminate(), eTerminateNull, GetNumAgents(), and cScene::IsEpisodeEnd().
Referenced by cDrawRLScene::IsEpisodeEnd().
LogVal()
virtual void cRLScene::LogVal (int agent_id, double val) pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::LogVal().
NeedNewAction()
virtual bool cRLScene::NeedNewAction (int agent_id) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::NeedNewAction().
RecordGoal()
virtual void cRLScene::RecordGoal (int agent_id, Eigen::VectorXd & out_goal) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::RecordGoal().
RecordState()
virtual void cRLScene::RecordState (int agent_id, Eigen::VectorXd & out_state) const pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::RecordState().
SetAction()
virtual void cRLScene::SetAction (int agent_id, const Eigen::VectorXd & action) pure virtual
Implemented in cRLSceneSimChar, and cDrawRLScene.
Referenced by cDrawRLScene::SetAction().
SetMode()
void cRLScene::SetMode (eMode mode) virtual
Reimplemented in cDrawRLScene.
Definition at line 62 of file RLScene.cpp.
 {
     mMode = mode;
 }
References mMode.
Referenced by cDrawRLScene::SetMode().
SetSampleCount()
void cRLScene::SetSampleCount (int count) virtual
Reimplemented in cRLSceneSimChar, and cDrawRLScene.
Definition at line 57 of file RLScene.cpp.
 {
     mSampleCount = count;
 }
References mSampleCount.
Referenced by cDrawRLScene::SetSampleCount(), and cRLSceneSimChar::SetSampleCount().
Member Data Documentation
mMode
eMode cRLScene::mMode protected
Definition at line 65 of file RLScene.h.
Referenced by cRLScene(), cRLSceneSimChar::ResetTimers(), and SetMode().
mSampleCount
int cRLScene::mSampleCount protected
Definition at line 66 of file RLScene.h.
Referenced by Clear(), cRLScene(), Init(), SetSampleCount(), and cRLSceneSimChar::UpdateTimerParams().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/RLScene.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/RLScene.cpp