My Project: cRBDModel Class Reference
cRBDModel Class Reference
#include <RBDModel.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cRBDModel ()
~cRBDModel ()
virtual void Init (const Eigen::MatrixXd &joint_mat, const Eigen::MatrixXd &body_defs, const tVector &gravity)
virtual void Update (const Eigen::VectorXd &pose, const Eigen::VectorXd &vel)
virtual int GetNumDof () const
virtual int GetNumJoints () const
virtual const tVector & GetGravity () const
virtual const Eigen::MatrixXd & GetJointMat () const
virtual const Eigen::MatrixXd & GetBodyDefs () const
virtual const Eigen::VectorXd & GetPose () const
virtual const Eigen::VectorXd & GetVel () const
virtual int GetParent (int j) const
virtual const Eigen::MatrixXd & GetMassMat () const
virtual const Eigen::VectorXd & GetBiasForce () const
virtual Eigen::MatrixXd & GetInertiaBuffer ()
virtual tMatrix GetChildParentMat (int j) const
virtual tMatrix GetParentChildMat (int j) const
virtual cSpAlg::tSpTrans GetSpChildParentTrans (int j) const
virtual cSpAlg::tSpTrans GetSpParentChildTrans (int j) const
virtual tMatrix GetWorldJointMat (int j) const
virtual tMatrix GetJointWorldMat (int j) const
virtual cSpAlg::tSpTrans GetSpWorldJointTrans (int j) const
virtual cSpAlg::tSpTrans GetSpJointWorldTrans (int j) const
virtual const Eigen::Block< const Eigen::MatrixXd > GetJointSubspace (int j) const
virtual tVector CalcJointWorldPos (int j) const
Protected Member Functions
virtual void SetPose (const Eigen::VectorXd &pose)
virtual void SetVel (const Eigen::VectorXd &vel)
virtual void InitJointSubspaceArr ()
virtual void UpdateJointSubspaceArr ()
virtual void UpdateChildParentMatArr ()
virtual void UpdateSpWorldTrans ()
virtual void UpdateMassMat ()
virtual void UpdateBiasForce ()
Protected Attributes
tVector mGravity
Eigen::MatrixXd mJointMat
Eigen::MatrixXd mBodyDefs
Eigen::VectorXd mPose
Eigen::VectorXd mVel
Eigen::MatrixXd mJointSubspaceArr
Eigen::MatrixXd mChildParentMatArr
Eigen::MatrixXd mSpWorldJointTransArr
Eigen::MatrixXd mMassMat
Eigen::VectorXd mBiasForce
Eigen::MatrixXd mInertiaBuffer
Detailed Description
Definition at line 8 of file RBDModel.h.
Constructor & Destructor Documentation
cRBDModel()
cRBDModel::cRBDModel ()
Definition at line 5 of file RBDModel.cpp.
 {
 }
~cRBDModel()
cRBDModel::~cRBDModel ()
Definition at line 9 of file RBDModel.cpp.
 {
 }
Member Function Documentation
CalcJointWorldPos()
tVector cRBDModel::CalcJointWorldPos (int j) const virtual
Definition at line 166 of file RBDModel.cpp.
 {
     cSpAlg::tSpTrans world_joint_trans = GetSpWorldJointTrans(j);
     tVector r = cSpAlg::GetRad(world_joint_trans);
     return r;
 }
References cSpAlg::GetRad(), and GetSpWorldJointTrans().
GetBiasForce()
const Eigen::VectorXd & cRBDModel::GetBiasForce () const virtual
Definition at line 93 of file RBDModel.cpp.
 {
     return mBiasForce;
 }
References mBiasForce.
GetBodyDefs()
const Eigen::MatrixXd & cRBDModel::GetBodyDefs () const virtual
Definition at line 68 of file RBDModel.cpp.
 {
     return mBodyDefs;
 }
References mBodyDefs.
Referenced by cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildCOMVelProdAccAux(), cRBDUtil::BuildMassMat(), cRBDUtil::CalcCoM(), cRBDUtil::CalcGravityForce(), and cRBDUtil::SolveInvDyna().
GetChildParentMat()
tMatrix cRBDModel::GetChildParentMat (int j) const virtual
Definition at line 103 of file RBDModel.cpp.
 {
     assert(j >= 0 && j < GetNumJoints());
     tMatrix trans;
     int r = static_cast<int>(trans.rows());
     int c = static_cast<int>(trans.cols());
     trans = mChildParentMatArr.block(j * r, 0, r, c);
     return trans;
 }
References GetNumJoints(), and mChildParentMatArr.
Referenced by GetParentChildMat(), and GetSpChildParentTrans().
GetGravity()
const tVector & cRBDModel::GetGravity () const virtual
Definition at line 58 of file RBDModel.cpp.
 {
     return mGravity;
 }
References mGravity.
Referenced by cRBDUtil::BuildCOMVelProdAccAux(), cRBDUtil::CalcGravityForce(), cRBDUtil::CalcVelProdAcc(), and cRBDUtil::SolveInvDyna().
GetInertiaBuffer()
Eigen::MatrixXd & cRBDModel::GetInertiaBuffer () virtual
Definition at line 98 of file RBDModel.cpp.
 {
     return mInertiaBuffer;
 }
References mInertiaBuffer.
GetJointMat()
const Eigen::MatrixXd & cRBDModel::GetJointMat () const virtual
Definition at line 63 of file RBDModel.cpp.
 {
     return mJointMat;
 }
References mJointMat.
Referenced by cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildCOMVelProdAccAux(), cRBDUtil::BuildEndEffectorJacobian(), cRBDUtil::BuildJacobian(), cRBDUtil::BuildJacobianDot(), cRBDUtil::BuildMassMat(), cRBDUtil::CalcCoM(), cRBDUtil::CalcGravityForce(), cRBDUtil::CalcJointWorldVel(), cRBDUtil::CalcVelProdAcc(), cRBDUtil::CalcWorldJointTransforms(), cRBDUtil::CalcWorldVel(), and cRBDUtil::SolveInvDyna().
GetJointSubspace()
const Eigen::Block< const Eigen::MatrixXd > cRBDModel::GetJointSubspace (int j) const virtual
Definition at line 157 of file RBDModel.cpp.
 {
     assert(j >= 0 && j < GetNumJoints());
     int offset = cKinTree::GetParamOffset(mJointMat, j);
     int dim = cKinTree::GetParamSize(mJointMat, j);
     int r = static_cast<int>(mJointSubspaceArr.rows());
     return mJointSubspaceArr.block(0, offset, r, dim);
 }
References GetNumJoints(), cKinTree::GetParamOffset(), cKinTree::GetParamSize(), mJointMat, and mJointSubspaceArr.
Referenced by cRBDUtil::BuildEndEffectorJacobian(), cRBDUtil::BuildJacobian(), cRBDUtil::BuildJacobianDot(), cRBDUtil::BuildMassMat(), cRBDUtil::CalcGravityForce(), and cRBDUtil::SolveInvDyna().
GetJointWorldMat()
tMatrix cRBDModel::GetJointWorldMat (int j) const virtual
Definition at line 138 of file RBDModel.cpp.
 {
     cSpAlg::tSpTrans trans = GetSpJointWorldTrans(j);
     return cSpAlg::TransToMat(trans);
 }
References GetSpJointWorldTrans(), and cSpAlg::TransToMat().
GetMassMat()
const Eigen::MatrixXd & cRBDModel::GetMassMat () const virtual
Definition at line 88 of file RBDModel.cpp.
 {
     return mMassMat;
 }
References mMassMat.
GetNumDof()
int cRBDModel::GetNumDof () const virtual
Definition at line 48 of file RBDModel.cpp.
 {
     return cKinTree::GetNumDof(mJointMat);
 }
References cKinTree::GetNumDof(), and mJointMat.
Referenced by cRBDUtil::BuildBiasForce(), cRBDUtil::BuildJacobian(), cRBDUtil::BuildMassMat(), cRBDUtil::CalcCoMPos(), Init(), InitJointSubspaceArr(), and cRBDUtil::SolveForDyna().
GetNumJoints()
int cRBDModel::GetNumJoints () const virtual
Definition at line 53 of file RBDModel.cpp.
 {
     return cKinTree::GetNumJoints(mJointMat);
 }
References cKinTree::GetNumJoints(), and mJointMat.
Referenced by cRBDUtil::BuildMassMat(), GetChildParentMat(), GetJointSubspace(), GetSpWorldJointTrans(), Init(), InitJointSubspaceArr(), UpdateChildParentMatArr(), and UpdateJointSubspaceArr().
GetParent()
int cRBDModel::GetParent (int j) const virtual
Definition at line 83 of file RBDModel.cpp.
 {
     return cKinTree::GetParent(mJointMat, j);
 }
References cKinTree::GetParent(), and mJointMat.
GetParentChildMat()
tMatrix cRBDModel::GetParentChildMat (int j) const virtual
Definition at line 113 of file RBDModel.cpp.
 {
     tMatrix child_parent_trans = GetChildParentMat(j);
     tMatrix parent_child_trans = cMathUtil::InvRigidMat(child_parent_trans);
     return parent_child_trans;
 }
References GetChildParentMat(), and cMathUtil::InvRigidMat().
Referenced by GetSpParentChildTrans().
GetPose()
const Eigen::VectorXd & cRBDModel::GetPose () const virtual
Definition at line 73 of file RBDModel.cpp.
 {
     return mPose;
 }
References mPose.
Referenced by cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildCOMVelProdAccAux(), cRBDUtil::BuildEndEffectorJacobian(), cRBDUtil::BuildJacobian(), cRBDUtil::BuildJacobianDot(), cRBDUtil::BuildMassMat(), cRBDUtil::CalcCoM(), cRBDUtil::CalcGravityForce(), cRBDUtil::CalcJointWorldVel(), cRBDUtil::CalcVelProdAcc(), cRBDUtil::CalcWorldJointTransforms(), cRBDUtil::CalcWorldVel(), and cRBDUtil::SolveInvDyna().
GetSpChildParentTrans()
cSpAlg::tSpTrans cRBDModel::GetSpChildParentTrans (int j) const virtual
Definition at line 120 of file RBDModel.cpp.
 {
     tMatrix mat = GetChildParentMat(j);
     return cSpAlg::MatToTrans(mat);
 }
References GetChildParentMat(), and cSpAlg::MatToTrans().
Referenced by cRBDUtil::BuildMassMat(), cRBDUtil::CalcGravityForce(), and cRBDUtil::SolveInvDyna().
GetSpJointWorldTrans()
cSpAlg::tSpTrans cRBDModel::GetSpJointWorldTrans (int j) const virtual
Definition at line 151 of file RBDModel.cpp.
 {
     cSpAlg::tSpTrans world_joint_trans = GetSpWorldJointTrans(j);
     return cSpAlg::InvTrans(world_joint_trans);
 }
References GetSpWorldJointTrans(), and cSpAlg::InvTrans().
Referenced by GetJointWorldMat().
GetSpParentChildTrans()
cSpAlg::tSpTrans cRBDModel::GetSpParentChildTrans (int j) const virtual
Definition at line 126 of file RBDModel.cpp.
 {
     tMatrix mat = GetParentChildMat(j);
     return cSpAlg::MatToTrans(mat);
 }
References GetParentChildMat(), and cSpAlg::MatToTrans().
Referenced by cRBDUtil::BuildEndEffectorJacobian(), cRBDUtil::CalcWorldJointTransforms(), and cRBDUtil::SolveInvDyna().
GetSpWorldJointTrans()
cSpAlg::tSpTrans cRBDModel::GetSpWorldJointTrans (int j) const virtual
Definition at line 144 of file RBDModel.cpp.
 {
     assert(j >= 0 && j < GetNumJoints());
     cSpAlg::tSpTrans trans = cSpAlg::GetTrans(mSpWorldJointTransArr, j);
     return trans;
 }
References GetNumJoints(), cSpAlg::GetTrans(), and mSpWorldJointTransArr.
Referenced by cRBDUtil::BuildCOMJacobian(), cRBDUtil::BuildJacobian(), cRBDUtil::BuildJacobianDot(), cRBDUtil::CalcCoM(), cRBDUtil::CalcGravityForce(), CalcJointWorldPos(), cRBDUtil::CalcVelProdAcc(), GetSpJointWorldTrans(), GetWorldJointMat(), and cRBDUtil::SolveInvDyna().
GetVel()
const Eigen::VectorXd & cRBDModel::GetVel () const virtual
Definition at line 78 of file RBDModel.cpp.
 {
     return mVel;
 }
References mVel.
Referenced by cRBDUtil::BuildCOMVelProdAccAux(), cRBDUtil::BuildJacobianDot(), cRBDUtil::CalcCoM(), cRBDUtil::CalcJointWorldVel(), cRBDUtil::CalcVelProdAcc(), cRBDUtil::CalcWorldVel(), and cRBDUtil::SolveInvDyna().
GetWorldJointMat()
tMatrix cRBDModel::GetWorldJointMat (int j) const virtual
Definition at line 132 of file RBDModel.cpp.
 {
     cSpAlg::tSpTrans trans = GetSpWorldJointTrans(j);
     return cSpAlg::TransToMat(trans);
 }
References GetSpWorldJointTrans(), and cSpAlg::TransToMat().
Init()
void cRBDModel::Init (const Eigen::MatrixXd & joint_mat, const Eigen::MatrixXd & body_defs, const tVector & gravity) virtual
Definition at line 13 of file RBDModel.cpp.
 {
     assert(joint_mat.rows() == body_defs.rows());
     mGravity = gravity;
     mJointMat = joint_mat;
     mBodyDefs = body_defs;
     int num_dofs = GetNumDof();
     int num_joints = GetNumJoints();
     const int svs = cSpAlg::gSpVecSize;
     mPose = Eigen::VectorXd::Zero(num_dofs);
     mVel = Eigen::VectorXd::Zero(num_dofs);
     tMatrix trans_mat;
     InitJointSubspaceArr();
     mChildParentMatArr = Eigen::MatrixXd::Zero(num_joints * trans_mat.rows(), trans_mat.cols());
     mSpWorldJointTransArr = Eigen::MatrixXd::Zero(num_joints * cSpAlg::gSVTransRows, cSpAlg::gSVTransCols);
     mMassMat = Eigen::MatrixXd::Zero(num_dofs, num_dofs);
     mBiasForce = Eigen::VectorXd::Zero(num_dofs);
     mInertiaBuffer = Eigen::MatrixXd::Zero(num_joints * svs, svs);
 }
References GetNumDof(), GetNumJoints(), cSpAlg::gSpVecSize, cSpAlg::gSVTransCols, cSpAlg::gSVTransRows, InitJointSubspaceArr(), mBiasForce, mBodyDefs, mChildParentMatArr, mGravity, mInertiaBuffer, mJointMat, mMassMat, mPose, mSpWorldJointTransArr, and mVel.
InitJointSubspaceArr()
void cRBDModel::InitJointSubspaceArr () protected virtual
Definition at line 183 of file RBDModel.cpp.
 {
     int num_dofs = GetNumDof();
     int num_joints = GetNumJoints();
     mJointSubspaceArr = Eigen::MatrixXd(cSpAlg::gSpVecSize, num_dofs);
     for (int j = 0; j < num_joints; ++j)
     {
         int offset = cKinTree::GetParamOffset(mJointMat, j);
         int dim = cKinTree::GetParamSize(mJointMat, j);
         int r = static_cast<int>(mJointSubspaceArr.rows());
         mJointSubspaceArr.block(0, offset, r, dim) = cRBDUtil::BuildJointSubspace(mJointMat, mPose, j);
     }
 }
References cRBDUtil::BuildJointSubspace(), GetNumDof(), GetNumJoints(), cKinTree::GetParamOffset(), cKinTree::GetParamSize(), cSpAlg::gSpVecSize, mJointMat, mJointSubspaceArr, and mPose.
Referenced by Init().
SetPose()
void cRBDModel::SetPose (const Eigen::VectorXd & pose) protected virtual
Definition at line 173 of file RBDModel.cpp.
 {
     mPose = pose;
 }
References mPose.
Referenced by Update().
SetVel()
void cRBDModel::SetVel (const Eigen::VectorXd & vel) protected virtual
Definition at line 178 of file RBDModel.cpp.
 {
     mVel = vel;
 }
References mVel.
Referenced by Update().
Update()
void cRBDModel::Update (const Eigen::VectorXd & pose, const Eigen::VectorXd & vel) virtual
Definition at line 36 of file RBDModel.cpp.
 {
     SetPose(pose);
     SetVel(vel);
     UpdateJointSubspaceArr();
     UpdateChildParentMatArr();
     UpdateSpWorldTrans();
     UpdateMassMat();
     UpdateBiasForce();
 }
References SetPose(), SetVel(), UpdateBiasForce(), UpdateChildParentMatArr(), UpdateJointSubspaceArr(), UpdateMassMat(), and UpdateSpWorldTrans().
UpdateBiasForce()
void cRBDModel::UpdateBiasForce () protected virtual
Definition at line 235 of file RBDModel.cpp.
 {
     cRBDUtil::BuildBiasForce(*this, mBiasForce);
 }
References cRBDUtil::BuildBiasForce(), and mBiasForce.
Referenced by Update().
UpdateChildParentMatArr()
void cRBDModel::UpdateChildParentMatArr () protected virtual
Definition at line 213 of file RBDModel.cpp.
 {
     int num_joints = GetNumJoints();
     for (int j = 0; j < num_joints; ++j)
     {
         tMatrix child_parent_trans = cKinTree::ChildParentTrans(mJointMat, mPose, j);
         int r = static_cast<int>(child_parent_trans.rows());
         int c = static_cast<int>(child_parent_trans.cols());
         mChildParentMatArr.block(j * r, 0, r, c) = child_parent_trans;
     }
 }
References cKinTree::ChildParentTrans(), GetNumJoints(), mChildParentMatArr, mJointMat, and mPose.
Referenced by Update().
UpdateJointSubspaceArr()
void cRBDModel::UpdateJointSubspaceArr () protected virtual
Definition at line 197 of file RBDModel.cpp.
 {
     int num_joints = GetNumJoints();
     for (int j = 0; j < num_joints; ++j)
     {
         bool const_subspace = cRBDUtil::IsConstJointSubspace(mJointMat, j);
         if (!const_subspace)
         {
             int offset = cKinTree::GetParamOffset(mJointMat, j);
             int dim = cKinTree::GetParamSize(mJointMat, j);
             int r = static_cast<int>(mJointSubspaceArr.rows());
             mJointSubspaceArr.block(0, offset, r, dim) = cRBDUtil::BuildJointSubspace(mJointMat, mPose, j);
         }
     }
 }
References cRBDUtil::BuildJointSubspace(), GetNumJoints(), cKinTree::GetParamOffset(), cKinTree::GetParamSize(), cRBDUtil::IsConstJointSubspace(), mJointMat, mJointSubspaceArr, and mPose.
Referenced by Update().
UpdateMassMat()
void cRBDModel::UpdateMassMat () protected virtual
Definition at line 230 of file RBDModel.cpp.
 {
     cRBDUtil::BuildMassMat(*this, mInertiaBuffer, mMassMat);
 }
References cRBDUtil::BuildMassMat(), mInertiaBuffer, and mMassMat.
Referenced by Update().
UpdateSpWorldTrans()
void cRBDModel::UpdateSpWorldTrans () protected virtual
Definition at line 225 of file RBDModel.cpp.
 {
     cRBDUtil::CalcWorldJointTransforms(*this, mSpWorldJointTransArr);
 }
References cRBDUtil::CalcWorldJointTransforms(), and mSpWorldJointTransArr.
Referenced by Update().
Member Data Documentation
mBiasForce
Eigen::VectorXd cRBDModel::mBiasForce protected
Definition at line 56 of file RBDModel.h.
Referenced by GetBiasForce(), Init(), and UpdateBiasForce().
mBodyDefs
Eigen::MatrixXd cRBDModel::mBodyDefs protected
Definition at line 48 of file RBDModel.h.
Referenced by GetBodyDefs(), and Init().
mChildParentMatArr
Eigen::MatrixXd cRBDModel::mChildParentMatArr protected
Definition at line 53 of file RBDModel.h.
Referenced by GetChildParentMat(), Init(), and UpdateChildParentMatArr().
mGravity
tVector cRBDModel::mGravity protected
Definition at line 46 of file RBDModel.h.
Referenced by GetGravity(), and Init().
mInertiaBuffer
Eigen::MatrixXd cRBDModel::mInertiaBuffer protected
Definition at line 57 of file RBDModel.h.
Referenced by GetInertiaBuffer(), Init(), and UpdateMassMat().
mJointMat
Eigen::MatrixXd cRBDModel::mJointMat protected
Definition at line 47 of file RBDModel.h.
Referenced by GetJointMat(), GetJointSubspace(), GetNumDof(), GetNumJoints(), GetParent(), Init(), InitJointSubspaceArr(), UpdateChildParentMatArr(), and UpdateJointSubspaceArr().
mJointSubspaceArr
Eigen::MatrixXd cRBDModel::mJointSubspaceArr protected
Definition at line 52 of file RBDModel.h.
Referenced by GetJointSubspace(), InitJointSubspaceArr(), and UpdateJointSubspaceArr().
mMassMat
Eigen::MatrixXd cRBDModel::mMassMat protected
Definition at line 55 of file RBDModel.h.
Referenced by GetMassMat(), Init(), and UpdateMassMat().
mPose
Eigen::VectorXd cRBDModel::mPose protected
Definition at line 49 of file RBDModel.h.
Referenced by GetPose(), Init(), InitJointSubspaceArr(), SetPose(), UpdateChildParentMatArr(), and UpdateJointSubspaceArr().
mSpWorldJointTransArr
Eigen::MatrixXd cRBDModel::mSpWorldJointTransArr protected
Definition at line 54 of file RBDModel.h.
Referenced by GetSpWorldJointTrans(), Init(), and UpdateSpWorldTrans().
mVel
Eigen::VectorXd cRBDModel::mVel protected
Definition at line 50 of file RBDModel.h.
Referenced by GetVel(), Init(), and SetVel().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/RBDModel.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/RBDModel.cpp