My Project: cIndexManager Class Reference
cIndexManager Class Reference
#include <IndexManager.h>
Public Member Functions
cIndexManager ()
cIndexManager (int size)
virtual ~cIndexManager ()
virtual int GetSize () const
virtual int GetNumUsed () const
virtual void Reset ()
virtual void Clear ()
virtual void Resize (int size)
virtual int RequestIndex ()
virtual void FreeIndex (int idx)
virtual bool IsFree (int idx) const
virtual bool IsFull () const
Static Public Attributes
static const int gInvalidIndex = -1
Protected Attributes
int mFirstFree
std::vector< int > mIndices
std::vector< int > mPos
Detailed Description
Definition at line 6 of file IndexManager.h.
Constructor & Destructor Documentation
cIndexManager() [1/2]
cIndexManager::cIndexManager ()
Definition at line 6 of file IndexManager.cpp.
 {
     mFirstFree = 0;
 }
References mFirstFree.
cIndexManager() [2/2]
cIndexManager::cIndexManager (int size)
Definition at line 11 of file IndexManager.cpp.
 {
     mFirstFree = 0;
     Resize(size);
 }
References mFirstFree, and Resize().
~cIndexManager()
cIndexManager::~cIndexManager () virtual
Definition at line 17 of file IndexManager.cpp.
 {
 }
Member Function Documentation
Clear()
void cIndexManager::Clear () virtual
Definition at line 41 of file IndexManager.cpp.
 {
     mIndices.clear();
     mPos.clear();
     mFirstFree = 0;
 }
References mFirstFree, mIndices, and mPos.
Referenced by cAgentRegistry::Clear().
FreeIndex()
void cIndexManager::FreeIndex (int idx) virtual
Reimplemented in cIndexManagerMT.
Definition at line 93 of file IndexManager.cpp.
 {
     if(!IsFree(idx))
     {
         --mFirstFree;
         int pos = mPos[idx];
         int swap_idx = mIndices[mFirstFree];
         mIndices[mFirstFree] = idx;
         mIndices[pos] = swap_idx;
         mPos[swap_idx] = pos;
         mPos[idx] = mFirstFree;
     }
     else
     {
         assert(false); // trying to free an unused index
     }
 }
References IsFree(), mFirstFree, mIndices, and mPos.
Referenced by cIndexManagerMT::FreeIndex().
GetNumUsed()
int cIndexManager::GetNumUsed () const virtual
Definition at line 26 of file IndexManager.cpp.
 {
     return mFirstFree;
 }
References mFirstFree.
Referenced by cAgentRegistry::GetNumAgents().
GetSize()
int cIndexManager::GetSize () const virtual
Definition at line 21 of file IndexManager.cpp.
 {
     return static_cast<int>(mIndices.size());
 }
References mIndices.
Referenced by cAgentRegistry::AddAgent(), IsFull(), Reset(), and Resize().
IsFree()
bool cIndexManager::IsFree (int idx) const virtual
Definition at line 113 of file IndexManager.cpp.
 {
     return mPos[idx] >= mFirstFree;
 }
References mFirstFree, and mPos.
Referenced by FreeIndex().
IsFull()
bool cIndexManager::IsFull () const virtual
Definition at line 119 of file IndexManager.cpp.
 {
     return mFirstFree >= GetSize();
 }
References GetSize(), and mFirstFree.
Referenced by cAgentRegistry::AddAgent(), and RequestIndex().
RequestIndex()
int cIndexManager::RequestIndex () virtual
Reimplemented in cIndexManagerMT.
Definition at line 81 of file IndexManager.cpp.
 {
     if (IsFull())
     {
         return gInvalidIndex;
     }
     int idx = mIndices[mFirstFree];
     ++mFirstFree;
     return idx;
 }
References gInvalidIndex, IsFull(), mFirstFree, and mIndices.
Referenced by cAgentRegistry::AddAgent(), and cIndexManagerMT::RequestIndex().
Reset()
void cIndexManager::Reset () virtual
Definition at line 31 of file IndexManager.cpp.
 {
     for (int i = 0; i < GetSize(); ++i)
     {
         mIndices[i] = i;
         mPos[i] = i;
     }
     mFirstFree = 0;
 }
References GetSize(), mFirstFree, mIndices, and mPos.
Resize()
void cIndexManager::Resize (int size) virtual
Definition at line 48 of file IndexManager.cpp.
 {
     int curr_size = GetSize();
     if (size < curr_size)
     {
         int curr_pos = 0;
         for (int i = 0; i < GetSize(); ++i)
         {
             int curr_idx = mIndices[i];
             if (curr_idx < size)
             {
                 mIndices[curr_pos] = curr_idx;
                 mPos[curr_idx] = curr_pos;
                 if (i == mFirstFree)
                 {
                     mFirstFree = curr_pos;
                 }
                 ++curr_pos;
             }
         }
     }
     mIndices.resize(size);
     mPos.resize(size);
     for (int i = curr_size; i < GetSize(); ++i)
     {
         mIndices[i] = i;
         mPos[i] = i;
     }
 }
References GetSize(), mFirstFree, mIndices, and mPos.
Referenced by cAgentRegistry::AddAgent(), and cIndexManager().
Member Data Documentation
gInvalidIndex
const int cIndexManager::gInvalidIndex = -1 static
Definition at line 9 of file IndexManager.h.
Referenced by RequestIndex(), and cIndexManagerMT::RequestIndex().
mFirstFree
int cIndexManager::mFirstFree protected
Definition at line 27 of file IndexManager.h.
Referenced by cIndexManager(), Clear(), FreeIndex(), GetNumUsed(), IsFree(), IsFull(), RequestIndex(), Reset(), and Resize().
mIndices
std::vector<int> cIndexManager::mIndices protected
Definition at line 28 of file IndexManager.h.
Referenced by Clear(), FreeIndex(), GetSize(), RequestIndex(), Reset(), and Resize().
mPos
std::vector<int> cIndexManager::mPos protected
Definition at line 29 of file IndexManager.h.
Referenced by Clear(), FreeIndex(), IsFree(), Reset(), and Resize().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/IndexManager.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/IndexManager.cpp