My Project: cObjTracer Class Reference
cObjTracer Class Reference
#include <ObjTracer.h>
Classes
struct tParams
struct tTrace
Public Types
enum eTraceType { eTracePos, eTraceCOM, eTraceContact, eTrceMax }
Public Member Functions
cObjTracer ()
virtual ~cObjTracer ()
virtual void Init (double sample_period)
virtual void Update (double time_step)
virtual void Reset ()
virtual void Clear ()
virtual int AddTrace (const tParams &params)
virtual int GetNumTraces () const
virtual void SetTraceColIdx (int handle, int col_idx)
virtual void Draw () const
Protected Member Functions
virtual void ResetTimer ()
virtual void BuildTrace (const tParams &params, tTrace &out_trace) const
virtual void ResetTrace (tTrace &out_trace) const
virtual void UpdateTrace (tTrace &out_trace) const
virtual void UpdateTracePos (tTrace &out_trace) const
virtual void UpdateTraceCOM (tTrace &out_trace) const
virtual void UpdateTraceContact (tTrace &out_trace) const
virtual const tTrace & GetTrace (int handle) const
virtual tTrace & GetTrace (int handle)
virtual void DrawTrace (const tTrace &trace) const
virtual void DrawTracePos (const tTrace &trace) const
virtual void DrawTraceContact (const tTrace &trace) const
virtual void SetTraceColIdx (int idx, tTrace &out_trace) const
Protected Attributes
cTimer mTimer
tEigenArr< tTrace > mTraces
Detailed Description
Definition at line 7 of file ObjTracer.h.
Member Enumeration Documentation
eTraceType
enum cObjTracer::eTraceType
Enumerator
eTracePos
eTraceCOM
eTraceContact
eTrceMax
Definition at line 10 of file ObjTracer.h.
     {
         eTracePos,
         eTraceCOM,
         eTraceContact,
         eTrceMax
     };
Constructor & Destructor Documentation
cObjTracer()
cObjTracer::cObjTracer ()
Definition at line 24 of file ObjTracer.cpp.
 {
 }
~cObjTracer()
cObjTracer::~cObjTracer () virtual
Definition at line 28 of file ObjTracer.cpp.
 {
 }
Member Function Documentation
AddTrace()
int cObjTracer::AddTrace (const tParams & params) virtual
Definition at line 74 of file ObjTracer.cpp.
 {
     int handle = gInvalidIdx;
     if (params.IsValid())
     {
         tTrace trace;
         BuildTrace(params, trace);
         handle = GetNumTraces();
         mTraces.push_back(trace);
     }
     else
     {
         assert(false); // invalid trace parameters
     }
     return handle;
 }
References BuildTrace(), GetNumTraces(), gInvalidIdx, cObjTracer::tParams::IsValid(), and mTraces.
Referenced by cDrawSceneSimChar::AddCharTrace().
BuildTrace()
void cObjTracer::BuildTrace (const tParams & params, tTrace & out_trace) const protected virtual
Definition at line 116 of file ObjTracer.cpp.
 {
     out_trace.mParams = params;
     out_trace.mInContact = false;
     out_trace.mSampleBuffer.Reserve(params.mBufferSize);
 }
References cObjTracer::tParams::mBufferSize, cObjTracer::tTrace::mInContact, cObjTracer::tTrace::mParams, cObjTracer::tTrace::mSampleBuffer, and cCircularBuffer< tVal, tAlloc >::Reserve().
Referenced by AddTrace().
Clear()
void cObjTracer::Clear () virtual
Definition at line 68 of file ObjTracer.cpp.
 {
     ResetTimer();
     mTraces.clear();
 }
References mTraces, and ResetTimer().
Referenced by cDrawSceneSimChar::Clear(), and Init().
Draw()
void cObjTracer::Draw () const virtual
Definition at line 103 of file ObjTracer.cpp.
 {
     for (int i = 0; i < GetNumTraces(); ++i)
     {
         DrawTrace(mTraces[i]);
     }
 }
References DrawTrace(), GetNumTraces(), and mTraces.
Referenced by cDrawSceneSimChar::DrawTrace().
DrawTrace()
void cObjTracer::DrawTrace (const tTrace & trace) const protected virtual
Definition at line 196 of file ObjTracer.cpp.
 {
     cDrawUtil::SetLineWidth(3);
     switch (trace.mParams.mType)
     {
     case eTracePos:
     case eTraceCOM:
         DrawTracePos(trace);
         break;
     case eTraceContact:
         DrawTraceContact(trace);
         break;
     default:
         printf("Unsupported trace type\n");
         assert(false);
     }
 }
References DrawTraceContact(), DrawTracePos(), eTraceCOM, eTraceContact, eTracePos, cObjTracer::tTrace::mParams, cObjTracer::tParams::mType, and cDrawUtil::SetLineWidth().
Referenced by Draw().
DrawTraceContact()
void cObjTracer::DrawTraceContact (const tTrace & trace) const protected virtual
Definition at line 233 of file ObjTracer.cpp.
 {
     const double marker_size = gMarkerSize;
     int shape_idx = trace.mParams.mShapeIdx;
     shape_idx = shape_idx % gNumEndEffMarkers;
     for (int i = 0; i < static_cast<int>(trace.mSampleBuffer.GetSize()); ++i)
     {
         const auto& pos = trace.mSampleBuffer[i];
         int curr_col_idx = static_cast<int>(pos[3]);
         assert(curr_col_idx < trace.mParams.mColors.size());
         const tVector& col = trace.mParams.mColors[curr_col_idx];
         cDrawUtil::SetColor(col);
         switch (shape_idx)
         {
         case 0:
             cDrawUtil::DrawRect(pos, tVector(marker_size, marker_size, 0, 0));
             break;
         case 1:
             cDrawUtil::DrawTriangle(pos, 1.25 * marker_size);
             break;
         case 2:
             cDrawUtil::DrawCross(pos, marker_size);
             break;
         case 3:
             cDrawUtil::DrawDisk(pos, 0.5 * marker_size);
             break;
         default:
             assert(false);
             break;
         }
     }
 }
References cDrawUtil::DrawCross(), cDrawUtil::DrawDisk(), cDrawUtil::DrawRect(), cDrawUtil::DrawTriangle(), cCircularBuffer< tVal, tAlloc >::GetSize(), gMarkerSize, gNumEndEffMarkers, cObjTracer::tParams::mColors, cObjTracer::tTrace::mParams, cObjTracer::tTrace::mSampleBuffer, cObjTracer::tParams::mShapeIdx, and cDrawUtil::SetColor().
Referenced by DrawTrace().
DrawTracePos()
void cObjTracer::DrawTracePos (const tTrace & trace) const protected virtual
Definition at line 214 of file ObjTracer.cpp.
 {
     if (trace.mSampleBuffer.GetSize() > 1)
     {
         glBegin(GL_LINE_STRIP);
         for (size_t i = 0; i < trace.mSampleBuffer.GetSize(); ++i)
         {
             const tVector& vert0 = trace.mSampleBuffer[i];
             int curr_col_idx = static_cast<int>(vert0[3]);
             assert(curr_col_idx < trace.mParams.mColors.size());
             const tVector& col = trace.mParams.mColors[curr_col_idx];
             cDrawUtil::SetColor(col);
             glVertex3d(vert0[0], vert0[1], vert0[2]);
         }
         glEnd();
     }
 }
References cCircularBuffer< tVal, tAlloc >::GetSize(), cObjTracer::tParams::mColors, cObjTracer::tTrace::mParams, cObjTracer::tTrace::mSampleBuffer, and cDrawUtil::SetColor().
Referenced by DrawTrace().
GetNumTraces()
int cObjTracer::GetNumTraces () const virtual
Definition at line 98 of file ObjTracer.cpp.
 {
     return static_cast<int>(mTraces.size());
 }
References mTraces.
Referenced by AddTrace(), Draw(), GetTrace(), Reset(), and Update().
GetTrace() [1/2]
cObjTracer::tTrace & cObjTracer::GetTrace (int handle) protected virtual
Definition at line 190 of file ObjTracer.cpp.
 {
     assert(handle >= 0 && handle < GetNumTraces());
     return mTraces[handle];
 }
References GetNumTraces(), and mTraces.
GetTrace() [2/2]
const cObjTracer::tTrace & cObjTracer::GetTrace (int handle) const protected virtual
Definition at line 184 of file ObjTracer.cpp.
 {
     assert(handle >= 0 && handle < GetNumTraces());
     return mTraces[handle];
 }
References GetNumTraces(), and mTraces.
Referenced by SetTraceColIdx().
Init()
void cObjTracer::Init (double sample_period) virtual
Definition at line 33 of file ObjTracer.cpp.
 {
     Clear();
     cTimer::tParams timer_params;
     timer_params.mType = cTimer::eTypeUniform;
     timer_params.mTimeMin = sample_period;
     timer_params.mTimeMax = sample_period;
     mTimer.Init(timer_params);
 }
References Clear(), cTimer::eTypeUniform, cTimer::Init(), cTimer::tParams::mTimeMax, cTimer::tParams::mTimeMin, mTimer, and cTimer::tParams::mType.
Referenced by cDrawSceneSimChar::InitTracer().
Reset()
void cObjTracer::Reset () virtual
Definition at line 59 of file ObjTracer.cpp.
 {
     ResetTimer();
     for (int i = 0; i < GetNumTraces(); ++i)
     {
         ResetTrace(mTraces[i]);
     }
 }
References GetNumTraces(), mTraces, ResetTimer(), and ResetTrace().
Referenced by cDrawSceneSimChar::ResetScene(), and cDrawSceneSimChar::ToggleTrace().
ResetTimer()
void cObjTracer::ResetTimer () protected virtual
Definition at line 111 of file ObjTracer.cpp.
 {
     mTimer.Reset();
 }
References mTimer, and cTimer::Reset().
Referenced by Clear(), Reset(), and Update().
ResetTrace()
void cObjTracer::ResetTrace (tTrace & out_trace) const protected virtual
Definition at line 123 of file ObjTracer.cpp.
 {
     out_trace.mInContact = false;
     SetTraceColIdx(0, out_trace);
     out_trace.mSampleBuffer.Clear();
 }
References cCircularBuffer< tVal, tAlloc >::Clear(), cObjTracer::tTrace::mInContact, cObjTracer::tTrace::mSampleBuffer, and SetTraceColIdx().
Referenced by Reset().
SetTraceColIdx() [1/2]
void cObjTracer::SetTraceColIdx (int handle, int col_idx) virtual
Definition at line 92 of file ObjTracer.cpp.
 {
     tTrace& trace = GetTrace(handle);
     SetTraceColIdx(col_idx, trace);
 }
References GetTrace().
Referenced by ResetTrace().
SetTraceColIdx() [2/2]
void cObjTracer::SetTraceColIdx (int idx, tTrace & out_trace) const protected virtual
Definition at line 269 of file ObjTracer.cpp.
 {
     int num_cols = static_cast<int>(out_trace.mParams.mColors.size());
     idx = idx % num_cols;
     out_trace.mColIdx = idx;
 }
References cObjTracer::tTrace::mColIdx, cObjTracer::tParams::mColors, and cObjTracer::tTrace::mParams.
Update()
void cObjTracer::Update (double time_step) virtual
Definition at line 44 of file ObjTracer.cpp.
 {
     mTimer.Update(time_step);
     for (int i = 0; i < GetNumTraces(); ++i)
     {
         UpdateTrace(mTraces[i]);
     }
     if (mTimer.IsEnd())
     {
         ResetTimer();
     }
 }
References GetNumTraces(), cTimer::IsEnd(), mTimer, mTraces, ResetTimer(), cTimer::Update(), and UpdateTrace().
Referenced by cDrawSceneSimChar::UpdateTracer().
UpdateTrace()
void cObjTracer::UpdateTrace (tTrace & out_trace) const protected virtual
Definition at line 130 of file ObjTracer.cpp.
 {
     switch (out_trace.mParams.mType)
     {
     case eTracePos:
         UpdateTracePos(out_trace);
         break;
     case eTraceCOM:
         UpdateTraceCOM(out_trace);
         break;
     case eTraceContact:
         UpdateTraceContact(out_trace);
         break;
     default:
         printf("Unsupported trace type\n");
         assert(false);
     }
     out_trace.mInContact = out_trace.mParams.mObj->IsInContact();
 }
References eTraceCOM, eTraceContact, eTracePos, cObjTracer::tTrace::mInContact, cObjTracer::tParams::mObj, cObjTracer::tTrace::mParams, cObjTracer::tParams::mType, UpdateTraceCOM(), UpdateTraceContact(), and UpdateTracePos().
Referenced by Update().
UpdateTraceCOM()
void cObjTracer::UpdateTraceCOM (tTrace & out_trace) const protected virtual
Definition at line 160 of file ObjTracer.cpp.
 {
     if (mTimer.IsEnd())
     {
         tVector pos = out_trace.mParams.mObj->CalcCOM();
         pos[3] = out_trace.mColIdx;
         out_trace.mSampleBuffer.Add(pos);
     }
 }
References cCircularBuffer< tVal, tAlloc >::Add(), cTimer::IsEnd(), cObjTracer::tTrace::mColIdx, cObjTracer::tParams::mObj, cObjTracer::tTrace::mParams, cObjTracer::tTrace::mSampleBuffer, and mTimer.
Referenced by UpdateTrace().
UpdateTraceContact()
void cObjTracer::UpdateTraceContact (tTrace & out_trace) const protected virtual
Definition at line 170 of file ObjTracer.cpp.
 {
     const auto& obj = out_trace.mParams.mObj;
     bool contact = obj->IsInContact();
     bool prev_contact = out_trace.mInContact;
     if (contact && !prev_contact)
     {
         const auto& pts = obj->GetContactPts();
         tVector pos = pts[0].mPos;
         pos[3] = out_trace.mColIdx;
         out_trace.mSampleBuffer.Add(pos);
     }
 }
References cCircularBuffer< tVal, tAlloc >::Add(), cObjTracer::tTrace::mColIdx, cObjTracer::tTrace::mInContact, cObjTracer::tParams::mObj, cObjTracer::tTrace::mParams, and cObjTracer::tTrace::mSampleBuffer.
Referenced by UpdateTrace().
UpdateTracePos()
void cObjTracer::UpdateTracePos (tTrace & out_trace) const protected virtual
Definition at line 150 of file ObjTracer.cpp.
 {
     if (mTimer.IsEnd())
     {
         tVector pos = out_trace.mParams.mObj->LocalToWorldPos(out_trace.mParams.mLocalPos);
         pos[3] = out_trace.mColIdx;
         out_trace.mSampleBuffer.Add(pos);
     }
 }
References cCircularBuffer< tVal, tAlloc >::Add(), cTimer::IsEnd(), cObjTracer::tTrace::mColIdx, cObjTracer::tParams::mLocalPos, cObjTracer::tParams::mObj, cObjTracer::tTrace::mParams, cObjTracer::tTrace::mSampleBuffer, and mTimer.
Referenced by UpdateTrace().
Member Data Documentation
mTimer
cTimer cObjTracer::mTimer protected
Definition at line 56 of file ObjTracer.h.
Referenced by Init(), ResetTimer(), Update(), UpdateTraceCOM(), and UpdateTracePos().
mTraces
tEigenArr<tTrace> cObjTracer::mTraces protected
Definition at line 57 of file ObjTracer.h.
Referenced by AddTrace(), Clear(), Draw(), GetNumTraces(), GetTrace(), Reset(), and Update().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/ObjTracer.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/ObjTracer.cpp