My Project: cSimBodyJoint Class Reference
cSimBodyJoint Class Reference
#include <SimBodyJoint.h>
Classes
struct tParams
Public Member Functions
cSimBodyJoint ()
virtual ~cSimBodyJoint ()
virtual void Init (std::shared_ptr< cWorld > &world, const std::shared_ptr< cMultiBody > &multbody, const std::shared_ptr< cSimBodyLink > &parent, const std::shared_ptr< cSimBodyLink > &child, const tParams &params)
virtual void Clear ()
virtual bool IsValid () const
virtual cKinTree::eJointType GetType () const
virtual void CalcWorldRotation (tVector &out_axis, double &out_theta) const
virtual tQuaternion CalcWorldRotation () const
virtual tMatrix BuildWorldTrans () const
virtual bool IsRoot () const
virtual void AddTau (const Eigen::VectorXd &tau)
virtual const cSpAlg::tSpVec & GetTau () const
virtual void ApplyTau ()
virtual void ClearTau ()
virtual tVector CalcWorldPos () const
virtual tVector CalcWorldPos (const tVector &local_pos) const
virtual tVector CalcWorldVel () const
virtual tVector CalcWorldVel (const tVector &local_pos) const
virtual tVector CalcWorldAngVel () const
virtual double GetTorqueLimit () const
virtual double GetForceLimit () const
virtual void SetTorqueLimit (double lim)
virtual void SetForceLimit (double lim)
virtual tVector GetParentPos () const
virtual tVector GetChildPos () const
virtual tMatrix BuildJointChildTrans () const
virtual tMatrix BuildJointParentTrans () const
virtual tVector CalcAxisWorld () const
virtual tVector GetAxisRel () const
virtual bool HasParent () const
virtual bool HasChild () const
virtual const std::shared_ptr< cSimBodyLink > & GetParent () const
virtual const std::shared_ptr< cSimBodyLink > & GetChild () const
virtual void ClampTotalTorque (tVector &out_torque) const
virtual void ClampTotalForce (tVector &out_force) const
virtual const tVector & GetLimLow () const
virtual const tVector & GetLimHigh () const
virtual bool HasJointLim () const
virtual int GetParamSize () const
virtual void BuildPose (Eigen::VectorXd &out_pose) const
virtual void BuildVel (Eigen::VectorXd &out_vel) const
virtual void SetPose (const Eigen::VectorXd &pose)
virtual void SetVel (const Eigen::VectorXd &vel)
virtual tVector GetTotalTorque () const
virtual tVector GetTotalForce () const
Protected Member Functions
virtual cKinTree::eJointType FetchJointType () const
virtual tVector CalcParentLocalPos (const tVector &local_pos) const
virtual tVector CalcChildLocalPos (const tVector &local_pos) const
virtual void SetTotalTorque (const tVector &torque)
virtual void SetTotalForce (const tVector &force)
virtual void ApplyTauRevolute ()
virtual void ApplyTauPlanar ()
virtual void ApplyTauPrismatic ()
virtual void ApplyTauSpherical ()
Protected Attributes
cKinTree::eJointType mType
tParams mParams
std::shared_ptr< cWorld > mWorld
std::shared_ptr< cMultiBody > mMultBody
std::shared_ptr< cSimBodyLink > mParent
std::shared_ptr< cSimBodyLink > mChild
cSpAlg::tSpVec mTotalTau
Detailed Description
Definition at line 7 of file SimBodyJoint.h.
Constructor & Destructor Documentation
cSimBodyJoint()
cSimBodyJoint::cSimBodyJoint ()
Definition at line 20 of file SimBodyJoint.cpp.
 {
 }
~cSimBodyJoint()
cSimBodyJoint::~cSimBodyJoint () virtual
Definition at line 24 of file SimBodyJoint.cpp.
 {
     Clear();
 }
References Clear().
Member Function Documentation
AddTau()
void cSimBodyJoint::AddTau (const Eigen::VectorXd & tau) virtual
Definition at line 128 of file SimBodyJoint.cpp.
 {
     switch (GetType())
     {
     case cKinTree::eJointTypeRevolute:
         mTotalTau[2] += tau[0];
         break;
     case cKinTree::eJointTypePlanar:
         mTotalTau[3] += tau[0];
         mTotalTau[4] += tau[1];
         mTotalTau[2] += tau[2];
         break;
     case cKinTree::eJointTypePrismatic:
         mTotalTau[3] += tau[0];
         break;
     case cKinTree::eJointTypeFixed:
         break;
     case cKinTree::eJointTypeSpherical:
         mTotalTau[0] += tau[0];
         mTotalTau[1] += tau[1];
         mTotalTau[2] += tau[2];
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, GetType(), and mTotalTau.
Referenced by cSimCharacter::ApplyControlForces().
ApplyTau()
void cSimBodyJoint::ApplyTau () virtual
Definition at line 161 of file SimBodyJoint.cpp.
 {
     switch (GetType())
     {
     case cKinTree::eJointTypeRevolute:
         ApplyTauRevolute();
         break;
     case cKinTree::eJointTypePlanar:
         ApplyTauPlanar();
         break;
     case cKinTree::eJointTypePrismatic:
         ApplyTauPrismatic();
         break;
     case cKinTree::eJointTypeFixed:
         break;
     case cKinTree::eJointTypeSpherical:
         ApplyTauSpherical();
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References ApplyTauPlanar(), ApplyTauPrismatic(), ApplyTauRevolute(), ApplyTauSpherical(), cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, and GetType().
Referenced by cSimCharacter::UpdateJoints().
ApplyTauPlanar()
void cSimBodyJoint::ApplyTauPlanar () protected virtual
Definition at line 647 of file SimBodyJoint.cpp.
 {
     tVector torque = GetTotalTorque();
     ClampTotalTorque(torque);
     SetTotalTorque(torque);
     tVector force = GetTotalForce();
     ClampTotalForce(force);
     SetTotalForce(force);
     const auto& link = mMultBody->getLink(mParams.mID);
     cSpAlg::tSpTrans trans = cSpAlg::MatToTrans(BuildJointChildTrans());
     cSpAlg::tSpVec sv = cSpAlg::BuildSV(torque, force);
     sv = cSpAlg::ApplyTransF(trans, sv);
     force = cSpAlg::GetV(sv);
     torque = cSpAlg::GetOmega(sv);
     double world_scale = mWorld->GetScale();
     btScalar bt_data[] = { static_cast<btScalar>(world_scale * world_scale * link.getAxisTop(0).dot(btVector3(torque[0], torque[1], torque[2]))),
                             static_cast<btScalar>(world_scale * link.getAxisBottom(1).dot(btVector3(force[0], force[1], force[2]))),
                             static_cast<btScalar>(world_scale * link.getAxisBottom(2).dot(btVector3(force[0], force[1], force[2]))) };
     mMultBody->addJointTorqueMultiDof(mParams.mID, bt_data);
 }
References cSpAlg::ApplyTransF(), BuildJointChildTrans(), cSpAlg::BuildSV(), ClampTotalForce(), ClampTotalTorque(), cSpAlg::GetOmega(), GetTotalForce(), GetTotalTorque(), cSpAlg::GetV(), cSpAlg::MatToTrans(), cSimBodyJoint::tParams::mID, mMultBody, mParams, mWorld, SetTotalForce(), and SetTotalTorque().
Referenced by ApplyTau().
ApplyTauPrismatic()
void cSimBodyJoint::ApplyTauPrismatic () protected virtual
Definition at line 672 of file SimBodyJoint.cpp.
 {
     tVector force = GetTotalForce();
     ClampTotalForce(force);
     SetTotalForce(force);
     double world_scale = mWorld->GetScale();
     btScalar bt_data[] = { static_cast<btScalar>(world_scale * force[0]) };
     mMultBody->addJointTorqueMultiDof(mParams.mID, bt_data);
 }
References ClampTotalForce(), GetTotalForce(), cSimBodyJoint::tParams::mID, mMultBody, mParams, mWorld, and SetTotalForce().
Referenced by ApplyTau().
ApplyTauRevolute()
void cSimBodyJoint::ApplyTauRevolute () protected virtual
Definition at line 636 of file SimBodyJoint.cpp.
 {
     tVector torque = GetTotalTorque();
     ClampTotalTorque(torque);
     SetTotalTorque(torque);
     double world_scale = mWorld->GetScale();
     btScalar bt_data[] = { static_cast<btScalar>(world_scale * world_scale * torque[2]) };
     mMultBody->addJointTorqueMultiDof(mParams.mID, bt_data);
 }
References ClampTotalTorque(), GetTotalTorque(), cSimBodyJoint::tParams::mID, mMultBody, mParams, mWorld, and SetTotalTorque().
Referenced by ApplyTau().
ApplyTauSpherical()
void cSimBodyJoint::ApplyTauSpherical () protected virtual
Definition at line 683 of file SimBodyJoint.cpp.
 {
     tVector torque = GetTotalTorque();
     ClampTotalTorque(torque);
     SetTotalTorque(torque);
     double world_scale = mWorld->GetScale();
     torque = cMathUtil::QuatRotVec(mParams.mChildRot, torque);
     btScalar bt_data[] = { static_cast<btScalar>(world_scale * world_scale * torque[0]),
                             static_cast<btScalar>(world_scale * world_scale * torque[1]),
                             static_cast<btScalar>(world_scale * world_scale * torque[2]) };
     mMultBody->addJointTorqueMultiDof(mParams.mID, bt_data);
 }
References ClampTotalTorque(), GetTotalTorque(), cSimBodyJoint::tParams::mChildRot, cSimBodyJoint::tParams::mID, mMultBody, mParams, mWorld, cMathUtil::QuatRotVec(), and SetTotalTorque().
Referenced by ApplyTau().
BuildJointChildTrans()
tMatrix cSimBodyJoint::BuildJointChildTrans () const virtual
Definition at line 279 of file SimBodyJoint.cpp.
 {
     return cMathUtil::TranslateMat(mParams.mChildPos) * cMathUtil::RotateMat(mParams.mChildRot);
 }
References cSimBodyJoint::tParams::mChildPos, cSimBodyJoint::tParams::mChildRot, mParams, cMathUtil::RotateMat(), and cMathUtil::TranslateMat().
Referenced by ApplyTauPlanar(), BuildVel(), BuildWorldTrans(), and SetVel().
BuildJointParentTrans()
tMatrix cSimBodyJoint::BuildJointParentTrans () const virtual
Definition at line 284 of file SimBodyJoint.cpp.
 {
     return cMathUtil::TranslateMat(mParams.mParentPos) * cMathUtil::RotateMat(mParams.mParentRot);
 }
References mParams, cSimBodyJoint::tParams::mParentPos, cSimBodyJoint::tParams::mParentRot, cMathUtil::RotateMat(), and cMathUtil::TranslateMat().
Referenced by BuildWorldTrans().
BuildPose()
void cSimBodyJoint::BuildPose (Eigen::VectorXd & out_pose) const virtual
Definition at line 342 of file SimBodyJoint.cpp.
 {
     const btScalar* data = mMultBody->getJointPosMultiDof(mParams.mID);
     double world_scale = mWorld->GetScale();
     int param_size = GetParamSize();
     out_pose.resize(param_size);
     switch (GetType())
     {
     case cKinTree::eJointTypeRevolute:
         out_pose[0] = cMathUtil::NormalizeAngle(data[0]);
         break;
     case cKinTree::eJointTypePlanar:
     {
         const auto& link = mMultBody->getLink(mParams.mID);
         btVector3 bt_axis1 = link.getAxisBottom(1);
         btVector3 bt_axis2 = link.getAxisBottom(2);
         tVector axis1 = tVector(bt_axis1[0], bt_axis1[1], bt_axis1[2], 0);
         tVector axis2 = tVector(bt_axis2[0], bt_axis2[1], bt_axis2[2], 0);
         tVector pos = axis2 * (data[2] / world_scale) + axis1 * (data[1] / world_scale);
         pos = cMathUtil::QuatRotVec(mParams.mChildRot.conjugate(), pos);
         out_pose[0] = pos[0];
         out_pose[1] = pos[1];
         out_pose[2] = cMathUtil::NormalizeAngle(data[0]);
         break;
     }
     case cKinTree::eJointTypePrismatic:
         out_pose[0] = data[0] / world_scale;
         break;
     case cKinTree::eJointTypeFixed:
         break;
     case cKinTree::eJointTypeSpherical:
     {
         tQuaternion q = tQuaternion(data[3], data[0], data[1], data[2]);
         q = mParams.mChildRot.conjugate() * q * mParams.mChildRot;
         bool flip = (q.w() < 0);
         out_pose[0] = (flip) ? -q.w() : q.w();
         out_pose[1] = (flip) ? -q.x() : q.x();
         out_pose[2] = (flip) ? -q.y() : q.y();
         out_pose[3] = (flip) ? -q.z() : q.z();
         break;
     }
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, GetParamSize(), GetType(), cSimBodyJoint::tParams::mChildRot, cSimBodyJoint::tParams::mID, mMultBody, mParams, mWorld, cMathUtil::NormalizeAngle(), and cMathUtil::QuatRotVec().
Referenced by cSimCharacter::BuildJointPose(), cPDController::CalcJointTauPrismatic(), cPDController::CalcJointTauRevolute(), cPDController::CalcJointTauSpherical(), and cPDController::GetTargetTheta().
BuildVel()
void cSimBodyJoint::BuildVel (Eigen::VectorXd & out_vel) const virtual
Definition at line 391 of file SimBodyJoint.cpp.
 {
     const btScalar* data = mMultBody->getJointVelMultiDof(mParams.mID);
     double world_scale = mWorld->GetScale();
     int param_size = GetParamSize();
     out_vel.resize(param_size);
     switch (GetType())
     {
     case cKinTree::eJointTypeRevolute:
         out_vel[0] = data[0];
         break;
     case cKinTree::eJointTypePlanar:
     {
         const auto& link = mMultBody->getLink(mParams.mID);
         tMatrix body_to_joint = cMathUtil::InvRigidMat(BuildJointChildTrans());
         const btVector3& axis0 = link.getAxisTop(0);
         const btVector3& axis1 = link.getAxisBottom(1);
         const btVector3& axis2 = link.getAxisBottom(2);
         tVector lin_vel = (data[2] / world_scale) * tVector(axis2[0], axis2[1], axis2[2], 0)
                         + (data[1] / world_scale) * tVector(axis1[0], axis1[1], axis1[2], 0);
         tVector ang_vel = data[0] * tVector(axis0[0], axis0[1], axis0[2], 0);
         cSpAlg::tSpTrans trans = cSpAlg::MatToTrans(body_to_joint);
         cSpAlg::tSpVec sv = cSpAlg::BuildSV(ang_vel, lin_vel);
         sv = cSpAlg::ApplyTransM(trans, sv);
         lin_vel = cSpAlg::GetV(sv);
         ang_vel = cSpAlg::GetOmega(sv);
         out_vel[0] = lin_vel[0];
         out_vel[1] = lin_vel[1];
         out_vel[2] = ang_vel[2];
         break;
     }
     case cKinTree::eJointTypePrismatic:
         out_vel[0] = data[0] / world_scale;
         break;
     case cKinTree::eJointTypeFixed:
         break;
     case cKinTree::eJointTypeSpherical:
     {
         tVector ang_vel = tVector(data[0], data[1], data[2], 0);
         ang_vel = cMathUtil::QuatRotVec(mParams.mChildRot.conjugate(), ang_vel);
         out_vel[0] = ang_vel[0];
         out_vel[1] = ang_vel[1];
         out_vel[2] = ang_vel[2];
         out_vel[3] = 0;
         break;
     }
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References cSpAlg::ApplyTransM(), BuildJointChildTrans(), cSpAlg::BuildSV(), cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, cSpAlg::GetOmega(), GetParamSize(), GetType(), cSpAlg::GetV(), cMathUtil::InvRigidMat(), cSpAlg::MatToTrans(), cSimBodyJoint::tParams::mChildRot, cSimBodyJoint::tParams::mID, mMultBody, mParams, mWorld, and cMathUtil::QuatRotVec().
Referenced by cSimCharacter::BuildJointVel(), cPDController::CalcJointTauPrismatic(), cPDController::CalcJointTauRevolute(), and cPDController::CalcJointTauSpherical().
BuildWorldTrans()
tMatrix cSimBodyJoint::BuildWorldTrans () const virtual
Definition at line 106 of file SimBodyJoint.cpp.
 {
     tMatrix mat = tMatrix::Identity();
     if (HasChild())
     {
         mat = mChild->GetWorldTransform();
         mat = mat * BuildJointChildTrans();
     }
     else
     {
         mat = mParent->GetWorldTransform();
         mat = mat * BuildJointParentTrans();
     }
     return mat;
 }
References BuildJointChildTrans(), BuildJointParentTrans(), HasChild(), mChild, and mParent.
Referenced by cSimCharacter::BuildJointWorldTrans(), CalcAxisWorld(), CalcWorldPos(), CalcWorldRotation(), and cSimCharacter::GetWorldTransform().
CalcAxisWorld()
tVector cSimBodyJoint::CalcAxisWorld () const virtual
Definition at line 64 of file SimBodyJoint.cpp.
 {
     tVector axis_rel = GetAxisRel();
     axis_rel[3] = 0;
     tMatrix trans = BuildWorldTrans();
     tVector axis = trans * axis_rel;
     return axis;
 }
References BuildWorldTrans(), and GetAxisRel().
Referenced by cPDController::GetTargetTheta().
CalcChildLocalPos()
tVector cSimBodyJoint::CalcChildLocalPos (const tVector & local_pos) const protected virtual
Definition at line 580 of file SimBodyJoint.cpp.
 {
     tVector child_pos = cMathUtil::QuatRotVec(mParams.mChildRot, local_pos);
     child_pos += mParams.mChildPos;
     return child_pos;
 }
References cSimBodyJoint::tParams::mChildPos, cSimBodyJoint::tParams::mChildRot, mParams, and cMathUtil::QuatRotVec().
Referenced by CalcWorldVel().
CalcParentLocalPos()
tVector cSimBodyJoint::CalcParentLocalPos (const tVector & local_pos) const protected virtual
Definition at line 550 of file SimBodyJoint.cpp.
 {
     cKinTree::eJointType joint_type = GetType();
     tVector pt = local_pos;
     double world_scale = mWorld->GetScale();
     const btScalar* data = mMultBody->getJointPosMultiDof(mParams.mID);
     if (joint_type == cKinTree::eJointTypePrismatic)
     {
         double delta = data[0] / world_scale;
         pt[0] -= delta;
     }
     else if (joint_type == cKinTree::eJointTypePlanar)
     {
         const auto& link = mMultBody->getLink(mParams.mID);
         btVector3 bt_axis1 = link.getAxisBottom(1);
         btVector3 bt_axis2 = link.getAxisBottom(2);
         tVector axis1 = tVector(bt_axis1[0], bt_axis1[1], bt_axis1[2], 0);
         tVector axis2 = tVector(bt_axis2[0], bt_axis2[1], bt_axis2[2], 0);
         tVector pos = axis2 * (data[2] / world_scale) + axis1 * (data[1] / world_scale);
         pos = cMathUtil::QuatRotVec(mParams.mChildRot.conjugate(), pos);
         pt[0] += pos[0];
         pt[1] += pos[1];
     }
     tVector parent_pos = cMathUtil::QuatRotVec(mParams.mParentRot, pt);
     parent_pos += mParams.mParentPos;
     return parent_pos;
 }
References cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, GetType(), cSimBodyJoint::tParams::mChildRot, cSimBodyJoint::tParams::mID, mMultBody, mParams, cSimBodyJoint::tParams::mParentPos, cSimBodyJoint::tParams::mParentRot, mWorld, and cMathUtil::QuatRotVec().
Referenced by CalcWorldVel().
CalcWorldAngVel()
tVector cSimBodyJoint::CalcWorldAngVel () const virtual
Definition at line 237 of file SimBodyJoint.cpp.
 {
     if (HasChild())
     {
         return mChild->GetAngularVelocity();
     }
     else
     {
         return mParent->GetAngularVelocity();
     }
 }
References HasChild(), mChild, and mParent.
Referenced by cSimCharacter::GetRootAngVel().
CalcWorldPos() [1/2]
tVector cSimBodyJoint::CalcWorldPos () const virtual
Definition at line 190 of file SimBodyJoint.cpp.
 {
     tMatrix trans = BuildWorldTrans();
     tVector world_pos = tVector(trans(0, 3), trans(1, 3), trans(2, 3), 0);
     return world_pos;
 }
References BuildWorldTrans().
Referenced by cSimCharacter::CalcJointPos(), cDrawSimCharacter::DrawTorque(), and cSimCharacter::GetRootPos().
CalcWorldPos() [2/2]
tVector cSimBodyJoint::CalcWorldPos (const tVector & local_pos) const virtual
Definition at line 197 of file SimBodyJoint.cpp.
 {
     tVector world_pos = local_pos;
     world_pos[3] = 1;
     tMatrix trans = BuildWorldTrans();
     world_pos = trans * world_pos;
     world_pos[3] = 0;
     return world_pos;
 }
References BuildWorldTrans().
CalcWorldRotation() [1/2]
tQuaternion cSimBodyJoint::CalcWorldRotation () const virtual
Definition at line 93 of file SimBodyJoint.cpp.
 {
     tMatrix mat = BuildWorldTrans();
     tQuaternion q = cMathUtil::RotMatToQuaternion(mat);
     return q;
 }
References BuildWorldTrans(), and cMathUtil::RotMatToQuaternion().
CalcWorldRotation() [2/2]
void cSimBodyJoint::CalcWorldRotation (tVector & out_axis, double & out_theta) const virtual
Definition at line 100 of file SimBodyJoint.cpp.
 {
     tMatrix mat = BuildWorldTrans();
     cMathUtil::RotMatToAxisAngle(mat, out_axis, out_theta);
 }
References BuildWorldTrans(), and cMathUtil::RotMatToAxisAngle().
Referenced by cSimCharacter::GetRootRotation(), cPDController::GetTargetTheta(), and cSimCharacter::SetVel().
CalcWorldVel() [1/2]
tVector cSimBodyJoint::CalcWorldVel () const virtual
Definition at line 208 of file SimBodyJoint.cpp.
 {
     if (HasChild())
     {
         tVector anchor = GetChildPos();
         return mChild->GetLinearVelocity(anchor);
     }
     else
     {
         tVector anchor = GetParentPos();
         return mParent->GetLinearVelocity(anchor);
     }
 }
References GetChildPos(), GetParentPos(), HasChild(), mChild, and mParent.
Referenced by cSimCharacter::CalcJointVel(), and cSimCharacter::GetRootVel().
CalcWorldVel() [2/2]
tVector cSimBodyJoint::CalcWorldVel (const tVector & local_pos) const virtual
Definition at line 222 of file SimBodyJoint.cpp.
 {
     if (HasChild())
     {
         tVector pt = CalcChildLocalPos(local_pos);
         return mChild->GetLinearVelocity(pt);
     }
     else
     {
         tVector pt = CalcParentLocalPos(local_pos);
         return mParent->GetLinearVelocity(pt);
     }
 }
References CalcChildLocalPos(), CalcParentLocalPos(), HasChild(), mChild, and mParent.
ClampTotalForce()
void cSimBodyJoint::ClampTotalForce (tVector & out_force) const virtual
Definition at line 309 of file SimBodyJoint.cpp.
 {
     double mag = out_force.norm();
     double force_lim = GetForceLimit();
     if (mag > force_lim)
     {
         out_force *= force_lim / mag;
     }
 }
References GetForceLimit().
Referenced by ApplyTauPlanar(), and ApplyTauPrismatic().
ClampTotalTorque()
void cSimBodyJoint::ClampTotalTorque (tVector & out_torque) const virtual
Definition at line 299 of file SimBodyJoint.cpp.
 {
     double mag = out_torque.norm();
     double torque_lim = GetTorqueLimit();
     if (mag > torque_lim)
     {
         out_torque *= torque_lim / mag;
     }
 }
References GetTorqueLimit().
Referenced by ApplyTauPlanar(), ApplyTauRevolute(), and ApplyTauSpherical().
Clear()
void cSimBodyJoint::Clear () virtual
Definition at line 49 of file SimBodyJoint.cpp.
 {
     mType = cKinTree::eJointTypeNone;
     mParams = tParams();
     mWorld.reset();
     mParent.reset();
     mChild.reset();
     ClearTau();
 }
References ClearTau(), cKinTree::eJointTypeNone, mChild, mParams, mParent, mType, and mWorld.
Referenced by Init(), and ~cSimBodyJoint().
ClearTau()
void cSimBodyJoint::ClearTau () virtual
Definition at line 185 of file SimBodyJoint.cpp.
 {
     mTotalTau.setZero();
 }
References mTotalTau.
Referenced by Clear(), and cSimCharacter::ClearJointTorques().
FetchJointType()
cKinTree::eJointType cSimBodyJoint::FetchJointType () const protected virtual
Definition at line 592 of file SimBodyJoint.cpp.
 {
     btMultibodyLink::eFeatherstoneJointType bt_type = mMultBody->getLink(mParams.mID).m_jointType;
     cKinTree::eJointType joint_type = cKinTree::eJointTypeNone;
     bool is_root = IsRoot();
     if (is_root && !mMultBody->hasFixedBase())
     {
         joint_type = cKinTree::eJointTypeNone;
     }
     else
     {
         switch (bt_type)
         {
         case btMultibodyLink::eRevolute:
             joint_type = cKinTree::eJointTypeRevolute;
             break;
         case btMultibodyLink::ePrismatic:
             joint_type = cKinTree::eJointTypePrismatic;
             break;
         case btMultibodyLink::eSpherical:
             joint_type = cKinTree::eJointTypeSpherical;
             break;
         case btMultibodyLink::ePlanar:
             joint_type = cKinTree::eJointTypePlanar;
             break;
         case btMultibodyLink::eFixed:
             joint_type = cKinTree::eJointTypeFixed;
             break;
         default:
             assert(false); // unsupported joint type
             break;
         }
     }
     return joint_type;
 }
References cKinTree::eJointTypeFixed, cKinTree::eJointTypeNone, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, IsRoot(), cSimBodyJoint::tParams::mID, mMultBody, and mParams.
Referenced by Init().
GetAxisRel()
tVector cSimBodyJoint::GetAxisRel () const virtual
Definition at line 73 of file SimBodyJoint.cpp.
 {
     return tVector(0, 0, 1, 0);
 }
Referenced by CalcAxisWorld(), and cPDController::GetTargetTheta().
GetChild()
const std::shared_ptr< cSimBodyLink > & cSimBodyJoint::GetChild () const virtual
Definition at line 294 of file SimBodyJoint.cpp.
 {
     return mChild;
 }
References mChild.
GetChildPos()
tVector cSimBodyJoint::GetChildPos () const virtual
Definition at line 274 of file SimBodyJoint.cpp.
 {
     return mParams.mChildPos;
 }
References cSimBodyJoint::tParams::mChildPos, and mParams.
Referenced by CalcWorldVel().
GetForceLimit()
double cSimBodyJoint::GetForceLimit () const virtual
Definition at line 254 of file SimBodyJoint.cpp.
 {
     return mParams.mForceLimit;
 }
References cSimBodyJoint::tParams::mForceLimit, and mParams.
Referenced by ClampTotalForce(), and cPDController::GetForceLimit().
GetLimHigh()
const tVector & cSimBodyJoint::GetLimHigh () const virtual
Definition at line 324 of file SimBodyJoint.cpp.
 {
     return mParams.mLimHigh;
 }
References cSimBodyJoint::tParams::mLimHigh, and mParams.
GetLimLow()
const tVector & cSimBodyJoint::GetLimLow () const virtual
Definition at line 319 of file SimBodyJoint.cpp.
 {
     return mParams.mLimLow;
 }
References cSimBodyJoint::tParams::mLimLow, and mParams.
GetParamSize()
int cSimBodyJoint::GetParamSize () const virtual
Definition at line 337 of file SimBodyJoint.cpp.
 {
     return cKinTree::GetJointParamSize(GetType());
 }
References cKinTree::GetJointParamSize(), and GetType().
Referenced by BuildPose(), and BuildVel().
GetParent()
const std::shared_ptr< cSimBodyLink > & cSimBodyJoint::GetParent () const virtual
Definition at line 289 of file SimBodyJoint.cpp.
 {
     return mParent;
 }
References mParent.
GetParentPos()
tVector cSimBodyJoint::GetParentPos () const virtual
Definition at line 269 of file SimBodyJoint.cpp.
 {
     return mParams.mParentPos;
 }
References mParams, and cSimBodyJoint::tParams::mParentPos.
Referenced by CalcWorldVel().
GetTau()
const cSpAlg::tSpVec & cSimBodyJoint::GetTau () const virtual
Definition at line 156 of file SimBodyJoint.cpp.
 {
     return mTotalTau;
 }
References mTotalTau.
GetTorqueLimit()
double cSimBodyJoint::GetTorqueLimit () const virtual
Definition at line 249 of file SimBodyJoint.cpp.
 {
     return mParams.mTorqueLimit;
 }
References mParams, and cSimBodyJoint::tParams::mTorqueLimit.
Referenced by ClampTotalTorque(), and cPDController::GetTorqueLimit().
GetTotalForce()
tVector cSimBodyJoint::GetTotalForce () const virtual
Definition at line 630 of file SimBodyJoint.cpp.
 {
     tVector force = cSpAlg::GetV(mTotalTau);
     return force;
 }
References cSpAlg::GetV(), and mTotalTau.
Referenced by ApplyTauPlanar(), and ApplyTauPrismatic().
GetTotalTorque()
tVector cSimBodyJoint::GetTotalTorque () const virtual
Definition at line 544 of file SimBodyJoint.cpp.
 {
     tVector torque = cSpAlg::GetOmega(mTotalTau);
     return torque;
 }
References cSpAlg::GetOmega(), and mTotalTau.
Referenced by ApplyTauPlanar(), ApplyTauRevolute(), ApplyTauSpherical(), and cDrawSimCharacter::DrawTorque().
GetType()
cKinTree::eJointType cSimBodyJoint::GetType () const virtual
Definition at line 88 of file SimBodyJoint.cpp.
 {
     return mType;
 }
References mType.
Referenced by AddTau(), ApplyTau(), BuildPose(), BuildVel(), cPDController::CalcJointTau(), CalcParentLocalPos(), cCtPDController::GetJointType(), GetParamSize(), cPDController::GetTargetTheta(), cPDController::PostProcessTargetPose(), cPDController::PostProcessTargetVel(), SetPose(), and SetVel().
HasChild()
bool cSimBodyJoint::HasChild () const virtual
Definition at line 83 of file SimBodyJoint.cpp.
 {
     return mChild != nullptr;
 }
References mChild.
Referenced by BuildWorldTrans(), CalcWorldAngVel(), CalcWorldVel(), and Init().
HasJointLim()
bool cSimBodyJoint::HasJointLim () const virtual
Definition at line 329 of file SimBodyJoint.cpp.
 {
     return (mParams.mLimLow[0] <= mParams.mLimLow[0]
             || mParams.mLimLow[1] <= mParams.mLimLow[1]
             || mParams.mLimLow[2] <= mParams.mLimLow[2]
             || mParams.mLimLow[3] <= mParams.mLimLow[3]);
 }
References cSimBodyJoint::tParams::mLimLow, and mParams.
HasParent()
bool cSimBodyJoint::HasParent () const virtual
Definition at line 78 of file SimBodyJoint.cpp.
 {
     return mParent != nullptr;
 }
References mParent.
Init()
void cSimBodyJoint::Init (std::shared_ptr< cWorld > & world, const std::shared_ptr< cMultiBody > & multbody, const std::shared_ptr< cSimBodyLink > & parent, const std::shared_ptr< cSimBodyLink > & child, const tParams & params) virtual
Definition at line 29 of file SimBodyJoint.cpp.
 {
     Clear();
     mWorld = world;
     mMultBody = multbody;
     mParent = parent;
     mChild = child;
     mParams = params;
     mType = FetchJointType();
     if (!HasChild())
     {
         assert(mType == cKinTree::eJointTypeFixed);
     }
     assert(IsValid());
 }
References Clear(), cKinTree::eJointTypeFixed, FetchJointType(), HasChild(), IsValid(), mChild, mMultBody, mParams, mParent, mType, and mWorld.
Referenced by cSimCharacter::BuildJoints().
IsRoot()
bool cSimBodyJoint::IsRoot () const virtual
Definition at line 122 of file SimBodyJoint.cpp.
 {
     return mParams.mID == 0;
 }
References cSimBodyJoint::tParams::mID, and mParams.
Referenced by FetchJointType().
IsValid()
bool cSimBodyJoint::IsValid () const virtual
Definition at line 59 of file SimBodyJoint.cpp.
 {
     return(mWorld != nullptr) && (mChild != nullptr || mParent != nullptr);
 }
References mChild, mParent, and mWorld.
Referenced by cSimCharacter::ApplyControlForces(), cCtController::BuildActionBounds(), cCtController::BuildActionOffsetScale(), cSimCharacter::BuildJointWorldTrans(), cSimCharacter::CalcJointPos(), cSimCharacter::CalcJointVel(), cSimCharacter::ClearJointTorques(), cDrawSimCharacter::DrawTorque(), cExpPDController::Init(), Init(), and cSimCharacter::UpdateJoints().
SetForceLimit()
void cSimBodyJoint::SetForceLimit (double lim) virtual
Definition at line 264 of file SimBodyJoint.cpp.
 {
     mParams.mForceLimit = lim;
 }
References cSimBodyJoint::tParams::mForceLimit, and mParams.
SetPose()
void cSimBodyJoint::SetPose (const Eigen::VectorXd & pose) virtual
Definition at line 447 of file SimBodyJoint.cpp.
 {
     btScalar data[7];
     double world_scale = mWorld->GetScale();
     switch (GetType())
     {
     case cKinTree::eJointTypeRevolute:
         data[0] = pose[0];
         break;
     case cKinTree::eJointTypePlanar:
     {
         tVector pos = cMathUtil::QuatRotVec(mParams.mChildRot, tVector(pose[0], pose[1], 0, 0));
         const auto& link = mMultBody->getLink(mParams.mID);
         data[2] = link.getAxisBottom(2).dot(btVector3(pos[0], pos[1], pos[2])) * world_scale;
         data[1] = link.getAxisBottom(1).dot(btVector3(pos[0], pos[1], pos[2])) * world_scale;
         data[0] = pose[2];
         break;
     }
     case cKinTree::eJointTypePrismatic:
         data[0] = pose[0] * world_scale;
         break;
     case cKinTree::eJointTypeFixed:
         break;
     case cKinTree::eJointTypeSpherical:
     {
         tQuaternion q = cMathUtil::VecToQuat(pose);
         q = mParams.mChildRot * q * mParams.mChildRot.conjugate();
         data[0] = q.x();
         data[1] = q.y();
         data[2] = q.z();
         data[3] = q.w();
         break;
     }
     case cKinTree::eJointTypeNone:
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
     mMultBody->setJointPosMultiDof(mParams.mID, data);
 }
References cKinTree::eJointTypeFixed, cKinTree::eJointTypeNone, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, GetType(), cSimBodyJoint::tParams::mChildRot, cSimBodyJoint::tParams::mID, mMultBody, mParams, mWorld, cMathUtil::QuatRotVec(), and cMathUtil::VecToQuat().
Referenced by cSimCharacter::SetPose().
SetTorqueLimit()
void cSimBodyJoint::SetTorqueLimit (double lim) virtual
Definition at line 259 of file SimBodyJoint.cpp.
 {
     mParams.mTorqueLimit = lim;
 }
References mParams, and cSimBodyJoint::tParams::mTorqueLimit.
SetTotalForce()
void cSimBodyJoint::SetTotalForce (const tVector & force) protected virtual
Definition at line 697 of file SimBodyJoint.cpp.
 {
     cSpAlg::SetV(force, mTotalTau);
 }
References mTotalTau, and cSpAlg::SetV().
Referenced by ApplyTauPlanar(), and ApplyTauPrismatic().
SetTotalTorque()
void cSimBodyJoint::SetTotalTorque (const tVector & torque) protected virtual
Definition at line 587 of file SimBodyJoint.cpp.
 {
     cSpAlg::SetOmega(torque, mTotalTau);
 }
References mTotalTau, and cSpAlg::SetOmega().
Referenced by ApplyTauPlanar(), ApplyTauRevolute(), and ApplyTauSpherical().
SetVel()
void cSimBodyJoint::SetVel (const Eigen::VectorXd & vel) virtual
Definition at line 492 of file SimBodyJoint.cpp.
 {
     btScalar data[7];
     double world_scale = mWorld->GetScale();
     switch (GetType())
     {
     case cKinTree::eJointTypeRevolute:
         data[0] = vel[0];
         break;
     case cKinTree::eJointTypePlanar:
     {
         tMatrix joint_to_body = BuildJointChildTrans();
         const auto& link = mMultBody->getLink(mParams.mID);
         tVector lin_vel = tVector(vel[0], vel[1], 0, 0);
         tVector ang_vel = tVector(0, 0, vel[2], 0);
         cSpAlg::tSpTrans trans = cSpAlg::MatToTrans(joint_to_body);
         cSpAlg::tSpVec sv = cSpAlg::BuildSV(ang_vel, lin_vel);
         sv = cSpAlg::ApplyTransM(trans, sv);
         lin_vel = cSpAlg::GetV(sv);
         data[2] = link.getAxisBottom(2).dot(btVector3(lin_vel[0], lin_vel[1], lin_vel[2])) * world_scale;
         data[1] = link.getAxisBottom(1).dot(btVector3(lin_vel[0], lin_vel[1], lin_vel[2])) * world_scale;
         data[0] = ang_vel[2];
         break;
     }
     case cKinTree::eJointTypePrismatic:
         data[0] = vel[0] * world_scale;
         break;
     case cKinTree::eJointTypeFixed:
         break;
     case cKinTree::eJointTypeSpherical:
     {
         tVector ang_vel = tVector(vel[0], vel[1], vel[2], 0);
         ang_vel = cMathUtil::QuatRotVec(mParams.mChildRot, ang_vel);
         data[0] = ang_vel[0];
         data[1] = ang_vel[1];
         data[2] = ang_vel[2];
         data[3] = 0;
         break;
     }
     case cKinTree::eJointTypeNone:
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
     mMultBody->setJointVelMultiDof(mParams.mID, data);
 }
References cSpAlg::ApplyTransM(), BuildJointChildTrans(), cSpAlg::BuildSV(), cKinTree::eJointTypeFixed, cKinTree::eJointTypeNone, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, GetType(), cSpAlg::GetV(), cSpAlg::MatToTrans(), cSimBodyJoint::tParams::mChildRot, cSimBodyJoint::tParams::mID, mMultBody, mParams, mWorld, and cMathUtil::QuatRotVec().
Referenced by cSimCharacter::SetVel().
Member Data Documentation
mChild
std::shared_ptr<cSimBodyLink> cSimBodyJoint::mChild protected
Definition at line 96 of file SimBodyJoint.h.
Referenced by BuildWorldTrans(), CalcWorldAngVel(), CalcWorldVel(), Clear(), GetChild(), HasChild(), Init(), and IsValid().
mMultBody
std::shared_ptr<cMultiBody> cSimBodyJoint::mMultBody protected
Definition at line 94 of file SimBodyJoint.h.
Referenced by ApplyTauPlanar(), ApplyTauPrismatic(), ApplyTauRevolute(), ApplyTauSpherical(), BuildPose(), BuildVel(), CalcParentLocalPos(), FetchJointType(), Init(), SetPose(), and SetVel().
mParams
tParams cSimBodyJoint::mParams protected
Definition at line 92 of file SimBodyJoint.h.
Referenced by ApplyTauPlanar(), ApplyTauPrismatic(), ApplyTauRevolute(), ApplyTauSpherical(), BuildJointChildTrans(), BuildJointParentTrans(), BuildPose(), BuildVel(), CalcChildLocalPos(), CalcParentLocalPos(), Clear(), FetchJointType(), GetChildPos(), GetForceLimit(), GetLimHigh(), GetLimLow(), GetParentPos(), GetTorqueLimit(), HasJointLim(), Init(), IsRoot(), SetForceLimit(), SetPose(), SetTorqueLimit(), and SetVel().
mParent
std::shared_ptr<cSimBodyLink> cSimBodyJoint::mParent protected
Definition at line 95 of file SimBodyJoint.h.
Referenced by BuildWorldTrans(), CalcWorldAngVel(), CalcWorldVel(), Clear(), GetParent(), HasParent(), Init(), and IsValid().
mTotalTau
cSpAlg::tSpVec cSimBodyJoint::mTotalTau protected
Definition at line 99 of file SimBodyJoint.h.
Referenced by AddTau(), ClearTau(), GetTau(), GetTotalForce(), GetTotalTorque(), SetTotalForce(), and SetTotalTorque().
mType
cKinTree::eJointType cSimBodyJoint::mType protected
Definition at line 91 of file SimBodyJoint.h.
Referenced by Clear(), GetType(), and Init().
mWorld
std::shared_ptr<cWorld> cSimBodyJoint::mWorld protected
Definition at line 93 of file SimBodyJoint.h.
Referenced by ApplyTauPlanar(), ApplyTauPrismatic(), ApplyTauRevolute(), ApplyTauSpherical(), BuildPose(), BuildVel(), CalcParentLocalPos(), Clear(), Init(), IsValid(), SetPose(), and SetVel().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimBodyJoint.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimBodyJoint.cpp