My Project: cSimSphere Class Reference
cSimSphere Class Reference
#include <SimSphere.h>
Classes
struct tParams
Public Member Functions
cSimSphere ()
virtual ~cSimSphere ()
virtual void Init (const std::shared_ptr< cWorld > &world, const tParams &params)
virtual double GetRadius () const
virtual tVector GetSize () const
virtual cShape::eShape GetShape () const
Public Member Functions inherited from cSimRigidBody
virtual ~cSimRigidBody ()
virtual void SetPos (const tVector &pos)
virtual void SetRotation (const tVector &axis, double theta)
virtual void SetRotation (const tQuaternion &q)
virtual tVector GetLinearVelocity () const
virtual tVector GetLinearVelocity (const tVector &local_pos) const
virtual void SetLinearVelocity (const tVector &vel)
virtual tVector GetAngularVelocity () const
virtual void SetAngularVelocity (const tVector &vel)
virtual void SetDamping (double linear_damping, double angular_damping)
virtual double GetMass () const
virtual void ApplyForce (const tVector &force)
virtual void ApplyForce (const tVector &force, const tVector &local_pos)
virtual void ApplyTorque (const tVector &torque)
virtual void ClearForces ()
virtual void SetKinematicObject (bool is_kin)
virtual bool IsKinematicObject () const
virtual void DisableDeactivation ()
virtual void Constrain (const tVector &linear_factor, const tVector &angular_factor)
virtual bool HasSimBody () const
virtual const std::unique_ptr< btRigidBody > & GetSimBody () const
Public Member Functions inherited from cSimObj
virtual ~cSimObj ()
virtual tVector GetPos () const
virtual void GetRotation (tVector &out_axis, double &out_theta) const
virtual tQuaternion GetRotation () const
virtual tMatrix GetWorldTransform () const
virtual tMatrix GetLocalTransform () const
virtual tVector WorldToLocalPos (const tVector &world_pos) const
virtual tVector LocalToWorldPos (const tVector &local_pos) const
virtual tMatrix3 GetLocalToWorldRotMat () const
virtual tVector CalcCOM () const
virtual tVector CalcCOMVel () const
virtual void RegisterContact ()
virtual void RegisterContact (int contact_flags, int filter_flags)
virtual void UpdateContact (int contact_flags, int filter_flags)
virtual const cContactManager::tContactHandle & GetContactHandle () const
virtual bool IsInContact () const
virtual const tEigenArr< cContactManager::tContactPt > & GetContactPts () const
virtual short GetColGroup () const
virtual void SetColGroup (short col_group)
virtual short GetColMask () const
virtual void SetColMask (short col_mask)
virtual eType GetType () const
virtual void CalcAABB (tVector &out_min, tVector &out_max) const
virtual const btCollisionShape * GetCollisionShape () const
Additional Inherited Members
Public Types inherited from cSimObj
enum eType { eTypeDynamic, eTypeStatic, eTypeMax }
Protected Member Functions inherited from cSimRigidBody
cSimRigidBody ()
virtual void Init (const std::shared_ptr< cWorld > &world)
virtual void AddToWorld (const std::shared_ptr< cWorld > &world)
virtual void RemoveFromWorld ()
virtual const btCollisionObject * GetCollisionObject () const
virtual btCollisionObject * GetCollisionObject ()
virtual int GetNumConstraints () const
virtual cWorld::tConstraintHandle GetConstraint (int c) const
Protected Member Functions inherited from cSimObj
cSimObj ()
virtual const std::shared_ptr< cWorld > & GetWorld () const
Protected Attributes inherited from cSimRigidBody
std::unique_ptr< btRigidBody > mSimBody
Protected Attributes inherited from cSimObj
std::shared_ptr< cWorld > mWorld
std::unique_ptr< btCollisionShape > mColShape
cContactManager::tContactHandle mContactHandle
bool mEnableContactFall
eType mType
short mColGroup
short mColMask
Detailed Description
Definition at line 5 of file SimSphere.h.
Constructor & Destructor Documentation
cSimSphere()
cSimSphere::cSimSphere ()
Definition at line 15 of file SimSphere.cpp.
 {
 }
~cSimSphere()
cSimSphere::~cSimSphere () virtual
Definition at line 19 of file SimSphere.cpp.
 {
 }
Member Function Documentation
GetRadius()
double cSimSphere::GetRadius () const virtual
Definition at line 42 of file SimSphere.cpp.
 {
     tVector size = GetSize();
     return 0.5 * size[0];
 }
References GetSize().
GetShape()
cShape::eShape cSimSphere::GetShape () const virtual
Reimplemented from cSimObj.
Definition at line 53 of file SimSphere.cpp.
 {
     return cShape::eShapeSphere;
 }
References cShape::eShapeSphere.
GetSize()
tVector cSimSphere::GetSize () const virtual
Implements cSimObj.
Definition at line 48 of file SimSphere.cpp.
 {
     return mWorld->GetSizeSphere(*this);
 }
References cSimObj::mWorld.
Referenced by GetRadius().
Init()
void cSimSphere::Init (const std::shared_ptr< cWorld > & world, const tParams & params) virtual
Definition at line 23 of file SimSphere.cpp.
 {
     mType = params.mType;
     btScalar mass = (params.mType == eTypeDynamic) ? static_cast<btScalar>(params.mMass) : 0;
     mColShape = std::unique_ptr<btCollisionShape>(world->BuildSphereShape(params.mRadius));
     btVector3 inertia(0, 0, 0);
     mColShape->calculateLocalInertia(mass, inertia);
     btRigidBody::btRigidBodyConstructionInfo cons_info(mass, this, mColShape.get(), inertia);
     mSimBody = std::unique_ptr<btRigidBody>(new btRigidBody(cons_info));
     mSimBody->setFriction(static_cast<btScalar>(params.mFriction));
     cSimRigidBody::Init(world);
     SetPos(params.mPos);
     SetLinearVelocity(params.mVel);
     SetRotation(params.mAxis, params.mTheta);
 }
References cSimObj::eTypeDynamic, cSimRigidBody::Init(), cSimSphere::tParams::mAxis, cSimObj::mColShape, cSimSphere::tParams::mFriction, cSimSphere::tParams::mMass, cSimSphere::tParams::mPos, cSimSphere::tParams::mRadius, cSimRigidBody::mSimBody, cSimSphere::tParams::mTheta, cSimSphere::tParams::mType, cSimObj::mType, cSimSphere::tParams::mVel, cSimRigidBody::SetLinearVelocity(), cSimRigidBody::SetPos(), and cSimRigidBody::SetRotation().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimSphere.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimSphere.cpp