My Project: cMatrixStack Class Reference
cMatrixStack Class Reference
#include <MatrixStack.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cMatrixStack (size_t capacity)
virtual ~cMatrixStack ()
virtual void Clear ()
virtual const tMatrix & GetMatrix () const
virtual void Push ()
virtual void Push (const tMatrix &mat)
virtual void Pop ()
virtual size_t GetCapacity () const
virtual size_t GetSize () const
virtual void SetIdentity ()
virtual void SetMatrix (const tMatrix &mat)
virtual void MultMatrix (const tMatrix &mat)
virtual void Translate (const tVector &trans)
virtual void Scale (const tVector &scale)
virtual void Rotate (double theta, const tVector &axis)
Protected Attributes
int mStackHead
tMatrix mCurrMat
std::vector< tMatrix, Eigen::aligned_allocator< tMatrix > > mMatStack
Detailed Description
Definition at line 6 of file MatrixStack.h.
Constructor & Destructor Documentation
cMatrixStack()
cMatrixStack::cMatrixStack (size_t capacity)
Definition at line 3 of file MatrixStack.cpp.
 {
     Clear();
     mMatStack.resize(capacity);
 }
References Clear(), and mMatStack.
~cMatrixStack()
cMatrixStack::~cMatrixStack () virtual
Definition at line 9 of file MatrixStack.cpp.
 {
 }
Member Function Documentation
Clear()
void cMatrixStack::Clear () virtual
Definition at line 13 of file MatrixStack.cpp.
 {
     mStackHead = 0;
     SetIdentity();
 }
References mStackHead, and SetIdentity().
Referenced by cMatrixStack(), and cDrawUtil::InitDrawUtil().
GetCapacity()
size_t cMatrixStack::GetCapacity () const virtual
Definition at line 46 of file MatrixStack.cpp.
 {
     return mMatStack.size();
 }
References mMatStack.
GetMatrix()
const tMatrix & cMatrixStack::GetMatrix () const virtual
Definition at line 19 of file MatrixStack.cpp.
 {
     return mCurrMat;
 }
References mCurrMat.
Referenced by cDrawUtil::LoadShaderUniforms().
GetSize()
size_t cMatrixStack::GetSize () const virtual
Definition at line 51 of file MatrixStack.cpp.
 {
     return mStackHead;
 }
References mStackHead.
MultMatrix()
void cMatrixStack::MultMatrix (const tMatrix & mat) virtual
Definition at line 66 of file MatrixStack.cpp.
 {
     mCurrMat = mCurrMat * mat;
 }
References mCurrMat.
Referenced by cDrawUtil::MultMatrixProj(), and cDrawUtil::MultMatrixView().
Pop()
void cMatrixStack::Pop () virtual
Definition at line 38 of file MatrixStack.cpp.
 {
     assert(mStackHead > 0);
     mCurrMat = mMatStack[mStackHead - 1];
     mStackHead = std::max(mStackHead - 1, 0);
 }
References mCurrMat, mMatStack, and mStackHead.
Referenced by cDrawUtil::PopMatrixProj(), and cDrawUtil::PopMatrixView().
Push() [1/2]
void cMatrixStack::Push () virtual
Definition at line 24 of file MatrixStack.cpp.
 {
     assert(mStackHead < mMatStack.size());
     mMatStack[mStackHead] = mCurrMat;
     mStackHead = std::min(mStackHead + 1, static_cast<int>(mMatStack.size()));
 }
References mCurrMat, mMatStack, and mStackHead.
Referenced by Push(), cDrawUtil::PushMatrixProj(), and cDrawUtil::PushMatrixView().
Push() [2/2]
void cMatrixStack::Push (const tMatrix & mat) virtual
Definition at line 32 of file MatrixStack.cpp.
 {
     Push();
     SetMatrix(mat);
 }
References Push(), and SetMatrix().
Rotate()
void cMatrixStack::Rotate (double theta, const tVector & axis) virtual
Definition at line 83 of file MatrixStack.cpp.
 {
     tMatrix rot_mat = cMathUtil::RotateMat(axis, theta);
     mCurrMat.block(0, 0, 3, 3) = mCurrMat.block(0, 0, 3, 3) * rot_mat.block(0, 0, 3, 3);
 }
References mCurrMat, and cMathUtil::RotateMat().
Referenced by cDrawUtil::Rotate().
Scale()
void cMatrixStack::Scale (const tVector & scale) virtual
Definition at line 76 of file MatrixStack.cpp.
 {
     mCurrMat.col(0) *= scale[0];
     mCurrMat.col(1) *= scale[1];
     mCurrMat.col(2) *= scale[2];
 }
References mCurrMat.
Referenced by cDrawUtil::Scale().
SetIdentity()
void cMatrixStack::SetIdentity () virtual
Definition at line 56 of file MatrixStack.cpp.
 {
     mCurrMat.setIdentity();
 }
References mCurrMat.
Referenced by Clear(), cDrawUtil::LoadIdentityProj(), and cDrawUtil::LoadIdentityView().
SetMatrix()
void cMatrixStack::SetMatrix (const tMatrix & mat) virtual
Definition at line 61 of file MatrixStack.cpp.
 {
     mCurrMat = mat;
 }
References mCurrMat.
Referenced by cDrawUtil::LoadMatrixProj(), cDrawUtil::LoadMatrixView(), and Push().
Translate()
void cMatrixStack::Translate (const tVector & trans) virtual
Definition at line 71 of file MatrixStack.cpp.
 {
     mCurrMat.block(0, 3, 3, 1) += mCurrMat.block(0, 0, 3, 3) * trans.segment(0, 3);
 }
References mCurrMat.
Referenced by cDrawUtil::Translate().
Member Data Documentation
mCurrMat
tMatrix cMatrixStack::mCurrMat protected
Definition at line 33 of file MatrixStack.h.
Referenced by GetMatrix(), MultMatrix(), Pop(), Push(), Rotate(), Scale(), SetIdentity(), SetMatrix(), and Translate().
mMatStack
std::vector<tMatrix, Eigen::aligned_allocator<tMatrix> > cMatrixStack::mMatStack protected
Definition at line 34 of file MatrixStack.h.
Referenced by cMatrixStack(), GetCapacity(), Pop(), and Push().
mStackHead
int cMatrixStack::mStackHead protected
Definition at line 32 of file MatrixStack.h.
Referenced by Clear(), GetSize(), Pop(), and Push().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/MatrixStack.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/MatrixStack.cpp