My Project: cDrawPerturb Class Reference
cDrawPerturb Class Reference
#include <DrawPerturb.h>
Static Public Member Functions
static void DrawForce (const tVector &pos, const tVector &force)
static void DrawTorque (const tVector &pos, const tVector &torque)
static void Draw (const tPerturb &perturb)
Static Public Attributes
static const double gForceScale = 0.005
static const double gTorqueScale = 0.00075
Static Protected Member Functions
static void DrawForce (const tPerturb &perturb)
static void DrawTorque (const tPerturb &perturb)
Detailed Description
Definition at line 5 of file DrawPerturb.h.
Member Function Documentation
Draw()
void cDrawPerturb::Draw (const tPerturb & perturb) static
Definition at line 45 of file DrawPerturb.cpp.
 {
     tPerturb::ePerturb type = perturb.mType;
     switch (type)
     {
     case tPerturb::ePerturbForce:
         DrawForce(perturb);
         break;
     case tPerturb::ePerturbTorque:
         DrawTorque(perturb);
         break;
     default:
         break;
     }
 }
References DrawForce(), DrawTorque(), tPerturb::ePerturbForce, tPerturb::ePerturbTorque, and tPerturb::mType.
Referenced by cDrawWorld::DrawPerturbs().
DrawForce() [1/2]
void cDrawPerturb::DrawForce (const tPerturb & perturb) static protected
Definition at line 61 of file DrawPerturb.cpp.
 {
     tVector pos = perturb.mObj->LocalToWorldPos(perturb.mLocalPos);
     const tVector& force = perturb.mPerturb;
     DrawForce(pos, force);
 }
References DrawForce(), cSimObj::LocalToWorldPos(), tPerturb::mLocalPos, tPerturb::mObj, and tPerturb::mPerturb.
DrawForce() [2/2]
void cDrawPerturb::DrawForce (const tVector & pos, const tVector & force) static
Definition at line 8 of file DrawPerturb.cpp.
 {
     const double len_scale = gForceScale;
     const double arrow_size = 0.1;
     tVector pos1 = pos + force * len_scale;
     cDrawUtil::SetColor(tVector(1, 0, 0, 0.5));
     cDrawUtil::DrawArrow3D(pos, pos1, arrow_size);
 }
References cDrawUtil::DrawArrow3D(), gForceScale, and cDrawUtil::SetColor().
Referenced by Draw(), and DrawForce().
DrawTorque() [1/2]
void cDrawPerturb::DrawTorque (const tPerturb & perturb) static protected
Definition at line 68 of file DrawPerturb.cpp.
 {
     tVector pos = perturb.mObj->LocalToWorldPos(perturb.mLocalPos);
     const tVector& torque = perturb.mPerturb;
     DrawTorque(pos, torque);
 }
References DrawTorque(), cSimObj::LocalToWorldPos(), tPerturb::mLocalPos, tPerturb::mObj, and tPerturb::mPerturb.
DrawTorque() [2/2]
void cDrawPerturb::DrawTorque (const tVector & pos, const tVector & torque) static
Definition at line 18 of file DrawPerturb.cpp.
 {
     const double torque_scale = gTorqueScale;
     const tVector color0 = tVector(1, 0, 0, 0.25);
     const tVector color1 = tVector(0, 1, 1, 0.25);
     tVector col;
     if (torque[2] < 0)
     {
         col = color0;
     }
     else
     {
         col = color1;
     }
     double mag = torque.norm();
     double r = mag * torque_scale;
     cDrawUtil::SetColor(tVector(col[0], col[1], col[2], col[3]));
     cDrawUtil::PushMatrixView();
     cDrawUtil::Translate(pos);
     cDrawUtil::DrawDisk(r);
     cDrawUtil::PopMatrixView();
 }
References cDrawUtil::DrawDisk(), gTorqueScale, cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixView(), cDrawUtil::SetColor(), and cDrawUtil::Translate().
Referenced by Draw(), cDrawSimCharacter::DrawTorque(), and DrawTorque().
Member Data Documentation
gForceScale
const double cDrawPerturb::gForceScale = 0.005 static
Definition at line 8 of file DrawPerturb.h.
Referenced by cDrawSceneSimChar::ApplyUIForce(), and DrawForce().
gTorqueScale
const double cDrawPerturb::gTorqueScale = 0.00075 static
Definition at line 9 of file DrawPerturb.h.
Referenced by DrawTorque().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/DrawPerturb.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/DrawPerturb.cpp