My Project: cSimRigidBody Class Reference
cSimRigidBody Class Reference
#include <SimRigidBody.h>
Public Member Functions
virtual ~cSimRigidBody ()
virtual void SetPos (const tVector &pos)
virtual void SetRotation (const tVector &axis, double theta)
virtual void SetRotation (const tQuaternion &q)
virtual tVector GetLinearVelocity () const
virtual tVector GetLinearVelocity (const tVector &local_pos) const
virtual void SetLinearVelocity (const tVector &vel)
virtual tVector GetAngularVelocity () const
virtual void SetAngularVelocity (const tVector &vel)
virtual void SetDamping (double linear_damping, double angular_damping)
virtual double GetMass () const
virtual void ApplyForce (const tVector &force)
virtual void ApplyForce (const tVector &force, const tVector &local_pos)
virtual void ApplyTorque (const tVector &torque)
virtual void ClearForces ()
virtual void SetKinematicObject (bool is_kin)
virtual bool IsKinematicObject () const
virtual void DisableDeactivation ()
virtual void Constrain (const tVector &linear_factor, const tVector &angular_factor)
virtual bool HasSimBody () const
virtual const std::unique_ptr< btRigidBody > & GetSimBody () const
Public Member Functions inherited from cSimObj
virtual ~cSimObj ()
virtual tVector GetPos () const
virtual void GetRotation (tVector &out_axis, double &out_theta) const
virtual tQuaternion GetRotation () const
virtual tMatrix GetWorldTransform () const
virtual tMatrix GetLocalTransform () const
virtual tVector WorldToLocalPos (const tVector &world_pos) const
virtual tVector LocalToWorldPos (const tVector &local_pos) const
virtual tMatrix3 GetLocalToWorldRotMat () const
virtual tVector CalcCOM () const
virtual tVector CalcCOMVel () const
virtual void RegisterContact ()
virtual void RegisterContact (int contact_flags, int filter_flags)
virtual void UpdateContact (int contact_flags, int filter_flags)
virtual const cContactManager::tContactHandle & GetContactHandle () const
virtual bool IsInContact () const
virtual const tEigenArr< cContactManager::tContactPt > & GetContactPts () const
virtual short GetColGroup () const
virtual void SetColGroup (short col_group)
virtual short GetColMask () const
virtual void SetColMask (short col_mask)
virtual eType GetType () const
virtual cShape::eShape GetShape () const
virtual tVector GetSize () const =0
virtual void CalcAABB (tVector &out_min, tVector &out_max) const
virtual const btCollisionShape * GetCollisionShape () const
Protected Member Functions
cSimRigidBody ()
virtual void Init (const std::shared_ptr< cWorld > &world)
virtual void AddToWorld (const std::shared_ptr< cWorld > &world)
virtual void RemoveFromWorld ()
virtual const btCollisionObject * GetCollisionObject () const
virtual btCollisionObject * GetCollisionObject ()
virtual int GetNumConstraints () const
virtual cWorld::tConstraintHandle GetConstraint (int c) const
Protected Member Functions inherited from cSimObj
cSimObj ()
virtual const std::shared_ptr< cWorld > & GetWorld () const
Protected Attributes
std::unique_ptr< btRigidBody > mSimBody
Protected Attributes inherited from cSimObj
std::shared_ptr< cWorld > mWorld
std::unique_ptr< btCollisionShape > mColShape
cContactManager::tContactHandle mContactHandle
bool mEnableContactFall
eType mType
short mColGroup
short mColMask
Additional Inherited Members
Public Types inherited from cSimObj
enum eType { eTypeDynamic, eTypeStatic, eTypeMax }
Detailed Description
Definition at line 5 of file SimRigidBody.h.
Constructor & Destructor Documentation
~cSimRigidBody()
cSimRigidBody::~cSimRigidBody () virtual
Definition at line 7 of file SimRigidBody.cpp.
 {
     RemoveFromWorld();
 }
References RemoveFromWorld().
cSimRigidBody()
cSimRigidBody::cSimRigidBody () protected
Definition at line 3 of file SimRigidBody.cpp.
 {
 }
Member Function Documentation
AddToWorld()
void cSimRigidBody::AddToWorld (const std::shared_ptr< cWorld > & world) protected virtual
Definition at line 201 of file SimRigidBody.cpp.
 {
     if (mWorld != nullptr)
     {
         RemoveFromWorld();
     }
     mWorld = world;
     mWorld->AddRigidBody(*this);
 }
References cSimObj::mWorld, and RemoveFromWorld().
Referenced by Init().
ApplyForce() [1/2]
void cSimRigidBody::ApplyForce (const tVector & force) virtual
Implements cSimObj.
Definition at line 104 of file SimRigidBody.cpp.
 {
     ApplyForce(force, tVector::Zero());
 }
ApplyForce() [2/2]
void cSimRigidBody::ApplyForce (const tVector & force, const tVector & local_pos) virtual
Implements cSimObj.
Definition at line 109 of file SimRigidBody.cpp.
 {
     auto& body = GetSimBody();
     btVector3 bt_force = btVector3(static_cast<btScalar>(force[0]),
                                     static_cast<btScalar>(force[1]),
                                     static_cast<btScalar>(force[2]));
     btScalar scale = static_cast<btScalar>(mWorld->GetScale());
     tMatrix3 rot_mat = GetLocalToWorldRotMat();
     tVector rel_pos = tVector::Zero();
     rel_pos.segment(0, 3) = rot_mat * local_pos.segment(0, 3);
     btVector3 bt_pos = btVector3(static_cast<btScalar>(rel_pos[0]),
                                 static_cast<btScalar>(rel_pos[1]),
                                 static_cast<btScalar>(rel_pos[2]));
     bt_force *= scale;
     bt_pos *= scale;
     body->applyForce(bt_force, bt_pos);
 }
References cSimObj::GetLocalToWorldRotMat(), GetSimBody(), and cSimObj::mWorld.
ApplyTorque()
void cSimRigidBody::ApplyTorque (const tVector & torque) virtual
Implements cSimObj.
Definition at line 130 of file SimRigidBody.cpp.
 {
     auto& body = GetSimBody();
     btScalar scale = static_cast<btScalar>(mWorld->GetScale());
     body->applyTorque(scale * scale * btVector3(static_cast<btScalar>(torque[0]),
                                         static_cast<btScalar>(torque[1]),
                                         static_cast<btScalar>(torque[2])));
 }
References GetSimBody(), and cSimObj::mWorld.
ClearForces()
void cSimRigidBody::ClearForces () virtual
Implements cSimObj.
Definition at line 139 of file SimRigidBody.cpp.
 {
     mSimBody->clearForces();
 }
References mSimBody.
Constrain()
void cSimRigidBody::Constrain (const tVector & linear_factor, const tVector & angular_factor) virtual
Definition at line 168 of file SimRigidBody.cpp.
 {
     mWorld->Constrain(*this, linear_factor, angular_factor);
 }
References cSimObj::mWorld.
DisableDeactivation()
void cSimRigidBody::DisableDeactivation () virtual
Definition at line 163 of file SimRigidBody.cpp.
 {
     mSimBody->setActivationState(DISABLE_DEACTIVATION);
 }
References mSimBody.
Referenced by Init().
GetAngularVelocity()
tVector cSimRigidBody::GetAngularVelocity () const virtual
Implements cSimObj.
Definition at line 79 of file SimRigidBody.cpp.
 {
     auto& body = GetSimBody();
     const btVector3& vel = body->getAngularVelocity();
     return tVector(vel[0], vel[1], vel[2], 0);
 }
References GetSimBody().
GetCollisionObject() [1/2]
btCollisionObject * cSimRigidBody::GetCollisionObject () protected virtual
Implements cSimObj.
Definition at line 188 of file SimRigidBody.cpp.
 {
     return mSimBody.get();
 }
References mSimBody.
GetCollisionObject() [2/2]
const btCollisionObject * cSimRigidBody::GetCollisionObject () const protected virtual
Implements cSimObj.
Definition at line 183 of file SimRigidBody.cpp.
 {
     return mSimBody.get();
 }
References mSimBody.
GetConstraint()
cWorld::tConstraintHandle cSimRigidBody::GetConstraint (int c) const protected virtual
Definition at line 235 of file SimRigidBody.cpp.
 {
     cWorld::tConstraintHandle handle;
     handle.mCons = mSimBody->getConstraintRef(c);
     return handle;
 }
References cWorld::tConstraintHandle::mCons, and mSimBody.
Referenced by RemoveFromWorld().
GetLinearVelocity() [1/2]
tVector cSimRigidBody::GetLinearVelocity () const virtual
Implements cSimObj.
Definition at line 45 of file SimRigidBody.cpp.
 {
     auto& body = GetSimBody();
     const btVector3& bt_vel = body->getLinearVelocity();
     tVector vel = tVector(bt_vel[0], bt_vel[1], bt_vel[2], 0);
     vel /= mWorld->GetScale();
     return vel;
 }
References GetSimBody(), and cSimObj::mWorld.
GetLinearVelocity() [2/2]
tVector cSimRigidBody::GetLinearVelocity (const tVector & local_pos) const virtual
Implements cSimObj.
Definition at line 54 of file SimRigidBody.cpp.
 {
     auto& body = GetSimBody();
     double scale = mWorld->GetScale();
     tMatrix3 rot_mat = GetLocalToWorldRotMat();
     tVector rel_pos = tVector::Zero();
     rel_pos.segment(0, 3) = rot_mat * local_pos.segment(0, 3);
     btVector3 bt_vel = body->getVelocityInLocalPoint(static_cast<btScalar>(scale) * btVector3(static_cast<btScalar>(rel_pos[0]),
                                                 static_cast<btScalar>(rel_pos[1]),
                                                 static_cast<btScalar>(rel_pos[2])));
     tVector vel = tVector(bt_vel[0], bt_vel[1], bt_vel[2], 0);
     vel /= scale;
     return vel;
 }
References cSimObj::GetLocalToWorldRotMat(), GetSimBody(), and cSimObj::mWorld.
GetMass()
double cSimRigidBody::GetMass () const virtual
Definition at line 99 of file SimRigidBody.cpp.
 {
     return 1 / mSimBody->getInvMass();
 }
References mSimBody.
GetNumConstraints()
int cSimRigidBody::GetNumConstraints () const protected virtual
Definition at line 230 of file SimRigidBody.cpp.
 {
     return mSimBody->getNumConstraintRefs();
 }
References mSimBody.
Referenced by RemoveFromWorld().
GetSimBody()
const std::unique_ptr< btRigidBody > & cSimRigidBody::GetSimBody () const virtual
Definition at line 178 of file SimRigidBody.cpp.
 {
     return mSimBody;
 }
References mSimBody.
Referenced by cWorld::AddRigidBody(), ApplyForce(), ApplyTorque(), cSimJoint::BuildConstraintFixed(), cSimJoint::BuildConstraintPrismatic(), cSimJoint::BuildConstraintRevolute(), cSimJoint::BuildConstraintSpherical(), cWorld::Constrain(), GetAngularVelocity(), GetLinearVelocity(), cWorld::RemoveRigidBody(), SetAngularVelocity(), SetDamping(), SetLinearVelocity(), SetPos(), and SetRotation().
HasSimBody()
bool cSimRigidBody::HasSimBody () const virtual
Definition at line 173 of file SimRigidBody.cpp.
 {
     return mSimBody != nullptr;
 }
References mSimBody.
Init()
void cSimRigidBody::Init (const std::shared_ptr< cWorld > & world) protected virtual
Definition at line 193 of file SimRigidBody.cpp.
 {
     RemoveFromWorld();
     mSimBody->setUserPointer(this);
     AddToWorld(world);
     DisableDeactivation();
 }
References AddToWorld(), DisableDeactivation(), mSimBody, and RemoveFromWorld().
Referenced by cSimPlane::Init(), cSimBox::Init(), cSimSphere::Init(), cSimCapsule::Init(), cSimCylinder::Init(), and cGround::Init().
IsKinematicObject()
bool cSimRigidBody::IsKinematicObject () const virtual
Definition at line 158 of file SimRigidBody.cpp.
 {
     return mSimBody->isKinematicObject();
 }
References mSimBody.
RemoveFromWorld()
void cSimRigidBody::RemoveFromWorld () protected virtual
Definition at line 212 of file SimRigidBody.cpp.
 {
     if (mWorld != nullptr && mSimBody != nullptr)
     {
         int num_cons = GetNumConstraints();
         for (int c = num_cons - 1; c >= 0; --c)
         {
             cWorld::tConstraintHandle cons = GetConstraint(c);
             mWorld->RemoveConstraint(cons);
         }
         mWorld->RemoveRigidBody(*this);
         mWorld.reset();
         mSimBody.reset();
         mColShape.reset();
     }
 }
References GetConstraint(), GetNumConstraints(), cSimObj::mColShape, mSimBody, and cSimObj::mWorld.
Referenced by AddToWorld(), Init(), and ~cSimRigidBody().
SetAngularVelocity()
void cSimRigidBody::SetAngularVelocity (const tVector & vel) virtual
Implements cSimObj.
Definition at line 86 of file SimRigidBody.cpp.
 {
     auto& body = GetSimBody();
     body->setAngularVelocity(btVector3(static_cast<btScalar>(vel[0]), static_cast<btScalar>(vel[1]),
                             static_cast<btScalar>(vel[2])));
 }
References GetSimBody().
SetDamping()
void cSimRigidBody::SetDamping (double linear_damping, double angular_damping) virtual
Definition at line 93 of file SimRigidBody.cpp.
 {
     const std::unique_ptr<btRigidBody>& body = GetSimBody();
     body->setDamping(static_cast<btScalar>(linear_damping), static_cast<btScalar>(angular_damping));
 }
References GetSimBody().
Referenced by cWorld::AddRigidBody().
SetKinematicObject()
void cSimRigidBody::SetKinematicObject (bool is_kin) virtual
Definition at line 144 of file SimRigidBody.cpp.
 {
     int col_flags = mSimBody->getCollisionFlags();
     if (is_kin)
     {
         col_flags |= btCollisionObject::CF_KINEMATIC_OBJECT;
     }
     else
     {
         col_flags &= ~btCollisionObject::CF_KINEMATIC_OBJECT;
     }
     mSimBody->setCollisionFlags(col_flags);
 }
References mSimBody.
SetLinearVelocity()
void cSimRigidBody::SetLinearVelocity (const tVector & vel) virtual
Implements cSimObj.
Definition at line 70 of file SimRigidBody.cpp.
 {
     auto& body = GetSimBody();
     btScalar scale = static_cast<btScalar>(mWorld->GetScale());
     body->setLinearVelocity(scale * btVector3(static_cast<btScalar>(vel[0]),
                                         static_cast<btScalar>(vel[1]),
                                         static_cast<btScalar>(vel[2])));
 }
References GetSimBody(), and cSimObj::mWorld.
Referenced by cSimBox::Init(), cSimSphere::Init(), and cSimCylinder::Init().
SetPos()
void cSimRigidBody::SetPos (const tVector & pos) virtual
Reimplemented from cSimObj.
Definition at line 12 of file SimRigidBody.cpp.
 {
     cSimObj::SetPos(pos);
     const auto& body = GetSimBody();
     if (body->isKinematicObject())
     {
         btMotionState* motion_state = body->getMotionState();
         btTransform trans = body->getWorldTransform();
         motion_state->setWorldTransform(trans);
     }
 }
References GetSimBody(), and cSimObj::SetPos().
Referenced by cSimBox::Init(), cSimSphere::Init(), cSimCylinder::Init(), and cSimCapsule::Init().
SetRotation() [1/2]
void cSimRigidBody::SetRotation (const tQuaternion & q) virtual
Reimplemented from cSimObj.
Definition at line 30 of file SimRigidBody.cpp.
 {
     cSimObj::SetRotation(q);
     const auto& body = GetSimBody();
     if (body->isKinematicObject())
     {
         btMotionState* motion_state = body->getMotionState();
         btTransform trans = body->getWorldTransform();
         motion_state->setWorldTransform(trans);
     }
     body->updateInertiaTensor();
 }
References GetSimBody(), and cSimObj::SetRotation().
SetRotation() [2/2]
void cSimRigidBody::SetRotation (const tVector & axis, double theta) virtual
Reimplemented from cSimObj.
Definition at line 25 of file SimRigidBody.cpp.
 {
     cSimObj::SetRotation(axis, theta);
 }
References cSimObj::SetRotation().
Referenced by cSimBox::Init(), cSimSphere::Init(), cSimCylinder::Init(), and cSimCapsule::Init().
Member Data Documentation
mSimBody
std::unique_ptr<btRigidBody> cSimRigidBody::mSimBody protected
Definition at line 37 of file SimRigidBody.h.
Referenced by ClearForces(), DisableDeactivation(), GetCollisionObject(), GetConstraint(), GetMass(), GetNumConstraints(), GetSimBody(), HasSimBody(), cGroundPlane::Init(), cSimPlane::Init(), cSimSphere::Init(), cSimBox::Init(), cSimCylinder::Init(), cSimCapsule::Init(), Init(), IsKinematicObject(), RemoveFromWorld(), and SetKinematicObject().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimRigidBody.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimRigidBody.cpp