My Project: cFileUtil Class Reference
cFileUtil Class Reference
#include <FileUtil.h>
Static Public Member Functions
static FILE * OpenFile (const std::string &file_name, const char *mode)
static FILE * OpenFile (const char *file_name, const char *mode)
static void CloseFile (FILE *&f)
static void ClearFile (const std::string &file_name)
static void CreateFile (const std::string &file_name)
static void DeleteFile (const char *file_name)
static std::string RemoveExtension (const std::string &filename)
static void DeleteFile (const std::string &filename)
static long int GetFileSize (const std::string &filename)
static std::string GetExtension (const std::string &filename)
static std::string GetFilename (const std::string &path)
static void FilterFilesByExtension (std::vector< std::string > &files, const std::string &ext)
static bool ExistsFile (const std::string &file_name)
static void FindLine (std::ifstream &f_stream, int line)
static std::string ReadTextFile (const std::string &path)
static bool ReadTable (const std::string &filename, std::vector< std::vector< double >> &out_buffer)
static bool ReadMatrix (const std::string &filename, Eigen::MatrixXd &out_mat)
static bool WriteMatrix (const Eigen::MatrixXd &mat, const std::string &out_filename)
static bool AppendText (const std::string &str, const std::string &out_filename)
Static Private Member Functions
static std::string ReadTextFile (FILE *f)
Detailed Description
Definition at line 8 of file FileUtil.h.
Member Function Documentation
AppendText()
bool cFileUtil::AppendText (const std::string & str, const std::string & out_filename) static
Definition at line 351 of file FileUtil.cpp.
 {
     std::ofstream out_stream(out_filename, std::ios_base::app);
     bool succ = !out_stream.fail();
     if (succ)
     {
         out_stream << str;
     }
     out_stream.close();
     return succ;
 }
ClearFile()
void cFileUtil::ClearFile (const std::string & file_name) static
Definition at line 34 of file FileUtil.cpp.
 {
     FILE* f = OpenFile(file_name, "w");
     CloseFile(f);
 }
References CloseFile(), and OpenFile().
Referenced by CreateFile().
CloseFile()
void cFileUtil::CloseFile (FILE *& f) static
Definition at line 25 of file FileUtil.cpp.
 {
     if (f != nullptr)
     {
         fclose(f);
         f = nullptr;
     }
 }
Referenced by ClearFile(), GetFileSize(), cArgParser::LoadFile(), cMotion::Output(), cController::OutputOptParams(), WriteMatrix(), and cCharacter::WriteState().
CreateFile()
void cFileUtil::CreateFile (const std::string & file_name) static
Definition at line 40 of file FileUtil.cpp.
 {
     ClearFile(file_name);
 }
References ClearFile().
DeleteFile() [1/2]
void cFileUtil::DeleteFile (const char * file_name) static
Definition at line 45 of file FileUtil.cpp.
 {
     bool succc = remove(file_name) == 0;
     if (!succc)
     {
         printf("Failed to delete %s!\n", file_name);
         assert(false); // failed to open file
     }
 }
DeleteFile() [2/2]
void cFileUtil::DeleteFile (const std::string & filename) static
Definition at line 68 of file FileUtil.cpp.
 {
     int err = remove(filename.c_str());
     if (err != 0)
     {
         printf("Failed to delete %s!\n", filename.c_str());
         assert(false);
     }
 }
ExistsFile()
bool cFileUtil::ExistsFile (const std::string & file_name) static
Definition at line 148 of file FileUtil.cpp.
 {
     FILE* f = nullptr;
     f = fopen(file_name.c_str(), "r");
     if (f != nullptr)
     {
         fclose(f);
         return true;
     }
     return false;
 }
FilterFilesByExtension()
void cFileUtil::FilterFilesByExtension (std::vector< std::string > & files, const std::string & ext) static
Definition at line 132 of file FileUtil.cpp.
 {
     size_t i = 0;
     for (size_t j = 0; j < files.size(); ++j)
     {
         const std::string& curr_f = files[j];
         std::string curr_ext = GetExtension(curr_f);
         if (curr_ext == ext)
         {
             files[i] = curr_f;
             ++i;
         }
     }
     files.resize(i);
 }
References GetExtension().
FindLine()
void cFileUtil::FindLine (std::ifstream & f_stream, int line) static
Definition at line 161 of file FileUtil.cpp.
 {
     f_stream.seekg(std::ios::beg);
     std::string str;
     int l = 0;
     while(std::getline(f_stream, str))
     {
         if (l == line - 1)
         {
             return;
         }
         ++l;
     }
     throw "Failed to find line in file stream\n";
 }
GetExtension()
std::string cFileUtil::GetExtension (const std::string & filename) static
Definition at line 93 of file FileUtil.cpp.
 {
     // remove leading '.'
     size_t dot_idx = 0;
     for (dot_idx; dot_idx < filename.size(); ++dot_idx)
     {
         if (filename[dot_idx] != '.')
         {
             break;
         }
     }
     std::string str = filename.substr(dot_idx);
     size_t pos = str.find_last_of(".");
     if (pos == std::string::npos)
     {
         return "";
     }
     return str.substr(pos + 1);
 }
Referenced by FilterFilesByExtension().
GetFilename()
std::string cFileUtil::GetFilename (const std::string & path) static
Definition at line 114 of file FileUtil.cpp.
 {
     int idx = 0;
     for (int i = static_cast<int>(path.size()) - 1; i >= 0; --i)
     {
         char curr_char = path[i];
         if (curr_char == '\\' || curr_char == '/')
         {
             idx = i + 1;
             break;
         }
     }
     std::string filename = path.substr(idx, path.size() - idx);
     filename = cFileUtil::RemoveExtension(filename);
     return filename;
 }
References RemoveExtension().
GetFileSize()
long int cFileUtil::GetFileSize (const std::string & filename) static
Definition at line 78 of file FileUtil.cpp.
 {
     // returns size in bytes
     FILE* f = OpenFile(filename.c_str(), "rb");
     if (f != NULL)
     {
         fseek(f, 0, SEEK_END);
         long int f_size = ftell(f);
         CloseFile(f);
         return f_size;
     }
     return 0;
 }
References CloseFile(), and OpenFile().
OpenFile() [1/2]
FILE * cFileUtil::OpenFile (const char * file_name, const char * mode) static
Definition at line 13 of file FileUtil.cpp.
 {
     FILE* f = nullptr;
     f = fopen(path, mode);
     if (f == nullptr)
     {
         printf("Failed to open %s!\n", path);
         assert(false); // failed to open file
     }
     return f;
 }
OpenFile() [2/2]
FILE * cFileUtil::OpenFile (const std::string & file_name, const char * mode) static
Definition at line 8 of file FileUtil.cpp.
 {
     return OpenFile(file_name.c_str(), mode);
 }
Referenced by ClearFile(), GetFileSize(), cArgParser::LoadFile(), cMotion::Output(), cController::OutputOptParams(), ReadTextFile(), WriteMatrix(), and cCharacter::WriteState().
ReadMatrix()
bool cFileUtil::ReadMatrix (const std::string & filename, Eigen::MatrixXd & out_mat) static
Definition at line 300 of file FileUtil.cpp.
 {
     std::vector<std::vector<double>> data;
     cFileUtil::ReadTable(filename, data);
     bool succ = false;
     if (data.size() > 0 && data[0].size() > 0)
     {
         int n = static_cast<int>(data.size());
         int m = static_cast<int>(data[0].size());
         out_mat.resize(n, m);
         for (int i = 0; i < n; ++i)
         {
             auto curr_row = data[i];
             int curr_m = static_cast<int>(curr_row.size());
             assert(curr_m == m);
             for (int j = 0; j < m; ++j)
             {
                 out_mat(i, j) = curr_row[j];
             }
         }
         succ = true;
     }
     return succ;
 }
References ReadTable().
ReadTable()
bool cFileUtil::ReadTable (const std::string & filename, std::vector< std::vector< double >> & out_buffer) static
Definition at line 247 of file FileUtil.cpp.
 {
     std::fstream f_stream(filename);
     out_buffer.clear();
     const char delims[] = " ,\t";
     std::string str;
     std::vector<char> char_array;
     bool succ = true;
     while (std::getline(f_stream, str))
     {
         if (str.size() > 0)
         {
             std::vector<double> curr_array;
             char_array = std::vector<char>(str.begin(), str.end());
             char_array.push_back(0);
             char* p_char = NULL;
             p_char = strtok(&char_array[0], delims);
             while (p_char != nullptr)
             {
                 std::string curr_tok(p_char);
                 if (curr_tok.size() >= 2)
                 {
                     if (curr_tok[0] == '/' && curr_tok[1] == '/')
                     {
                         break;
                     }
                 }
                 double val = std::atof(p_char);
                 curr_array.push_back(val);
                 p_char = strtok(NULL, delims);
             }
             if (curr_array.size() > 0)
             {
                 out_buffer.push_back(curr_array);
             }
         }
     }
     if (!succ)
     {
         out_buffer.clear();
     }
     return succ;
 }
Referenced by ReadMatrix().
ReadTextFile() [1/2]
std::string cFileUtil::ReadTextFile (const std::string & path) static
Definition at line 178 of file FileUtil.cpp.
 {
     FILE *file = OpenFile(path.c_str(), "rb");
     std::string text = ReadTextFile(file);
     fclose(file);
     return text;
 }
References OpenFile().
ReadTextFile() [2/2]
std::string cFileUtil::ReadTextFile (FILE * f) static private
Definition at line 366 of file FileUtil.cpp.
 {
     if (!f)
     {
         return std::string("");
     }
     fseek(f, 0, SEEK_END);
     long size = ftell(f);
     fseek(f, 0, SEEK_SET);
     std::string text;
     std::unique_ptr<char> buffer(new char[size + 1]);
     buffer.get()[size] = 0;
     if (fread(buffer.get(), 1, size, f) == (unsigned long)size)
     {
         text = buffer.get();
     }
     buffer.reset();
     return text;
 }
RemoveExtension()
std::string cFileUtil::RemoveExtension (const std::string & filename) static
Definition at line 56 of file FileUtil.cpp.
 {
     size_t first_not_dot = filename.find_first_not_of('.');
     size_t last_dot = filename.find_last_of(".");
     if (last_dot == std::string::npos
         || last_dot <= first_not_dot)
     {
         return filename;
     }
     return filename.substr(0, last_dot);
 }
Referenced by GetFilename().
WriteMatrix()
bool cFileUtil::WriteMatrix (const Eigen::MatrixXd & mat, const std::string & out_filename) static
Definition at line 327 of file FileUtil.cpp.
 {
     FILE* f = cFileUtil::OpenFile(out_filename, "w");
     bool succ = f != nullptr;
     if (succ)
     {
         for (int i = 0; i < mat.rows(); ++i)
         {
             for (int j = 0; j < mat.cols(); ++j)
             {
                 if (j != 0)
                 {
                     fprintf(f, ",");
                 }
                 fprintf(f, "%20.10f", mat(i, j));
             }
             fprintf(f, "\n");
         }
         cFileUtil::CloseFile(f);
     }
     return succ;
 }
References CloseFile(), and OpenFile().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/FileUtil.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/FileUtil.cpp