My Project: Json::Path Class Reference
Json::Path Class Reference
Experimental and untested: represents a "path" to access a node.
#include <value.h>
Public Member Functions
Path (const JSONCPP_STRING &path, const PathArgument &a1=PathArgument(), const PathArgument &a2=PathArgument(), const PathArgument &a3=PathArgument(), const PathArgument &a4=PathArgument(), const PathArgument &a5=PathArgument())
const Value & resolve (const Value &root) const
Value resolve (const Value &root, const Value &defaultValue) const
Value & make (Value &root) const
Private Types
typedef std::vector< const PathArgument * > InArgs
typedef std::vector< PathArgument > Args
Private Member Functions
void makePath (const JSONCPP_STRING &path, const InArgs &in)
void addPathInArg (const JSONCPP_STRING &path, const InArgs &in, InArgs::const_iterator &itInArg, PathArgument::Kind kind)
void invalidPath (const JSONCPP_STRING &path, int location)
Private Attributes
Args args_
Detailed Description
Experimental and untested: represents a "path" to access a node.
Syntax:
"." => root node
".[n]" => elements at index 'n' of root node (an array value)
".name" => member named 'name' of root node (an object value)
".name1.name2.name3"
".[0][1][2].name1[3]"
".%" => member name is provided as parameter
".[%]" => index is provied as parameter
Definition at line 659 of file value.h.
Member Typedef Documentation
Args
typedef std::vector<PathArgument> Json::Path::Args private
Definition at line 676 of file value.h.
InArgs
typedef std::vector<const PathArgument*> Json::Path::InArgs private
Definition at line 675 of file value.h.
Constructor & Destructor Documentation
Path()
Json::Path::Path (const JSONCPP_STRING & path, const PathArgument & a1 = PathArgument(), const PathArgument & a2 = PathArgument(), const PathArgument & a3 = PathArgument(), const PathArgument & a4 = PathArgument(), const PathArgument & a5 = PathArgument())
Definition at line 1502 of file json_value.cpp.
{
   InArgs in;
   in.reserve(5);
   in.push_back(&a1);
   in.push_back(&a2);
   in.push_back(&a3);
   in.push_back(&a4);
   in.push_back(&a5);
   makePath(path, in);
 }
References makePath().
Member Function Documentation
addPathInArg()
void Json::Path::addPathInArg (const JSONCPP_STRING & path, const InArgs & in, InArgs::const_iterator & itInArg, PathArgument::Kind kind) private
Definition at line 1549 of file json_value.cpp.
{
   if (itInArg == in.end()) {
     // Error: missing argument %d
   } else if ((*itInArg)->kind_ != kind) {
     // Error: bad argument type
   } else {
     args_.push_back(**itInArg++);
   }
 }
References args_.
Referenced by makePath().
invalidPath()
void Json::Path::invalidPath (const JSONCPP_STRING & path, int location) private
Definition at line 1562 of file json_value.cpp.
{
   // Error: invalid path.
 }
Referenced by makePath().
make()
Value & Json::Path::make (Value & root) const
Creates the "path" to access the specified node and returns a reference on the node.
Definition at line 1611 of file json_value.cpp.
{
   Value* node = &root;
   for (Args::const_iterator it = args_.begin(); it != args_.end(); ++it) {
     const PathArgument& arg = *it;
     if (arg.kind_ == PathArgument::kindIndex) {
       if (!node->isArray()) {
         // Error: node is not an array at position ...
       }
       node = &((*node)[arg.index_]);
     } else if (arg.kind_ == PathArgument::kindKey) {
       if (!node->isObject()) {
         // Error: node is not an object at position...
       }
       node = &((*node)[arg.key_]);
     }
   }
   return *node;
 }
References args_, Json::PathArgument::index_, Json::Value::isArray(), Json::Value::isObject(), Json::PathArgument::key_, Json::PathArgument::kind_, Json::PathArgument::kindIndex, and Json::PathArgument::kindKey.
makePath()
void Json::Path::makePath (const JSONCPP_STRING & path, const InArgs & in) private
Definition at line 1518 of file json_value.cpp.
{
   const char* current = path.c_str();
   const char* end = current + path.length();
   InArgs::const_iterator itInArg = in.begin();
   while (current != end) {
     if (*current == '[') {
       ++current;
       if (*current == '%')
         addPathInArg(path, in, itInArg, PathArgument::kindIndex);
       else {
         ArrayIndex index = 0;
         for (; current != end && *current >= '0' && *current <= '9'; ++current)
           index = index * 10 + ArrayIndex(*current - '0');
         args_.push_back(index);
       }
       if (current == end || *++current != ']')
         invalidPath(path, int(current - path.c_str()));
     } else if (*current == '%') {
       addPathInArg(path, in, itInArg, PathArgument::kindKey);
       ++current;
     } else if (*current == '.' || *current == ']') {
       ++current;
     } else {
       const char* beginName = current;
       while (current != end && !strchr("[.", *current))
         ++current;
       args_.push_back(JSONCPP_STRING(beginName, current));
     }
   }
 }
References addPathInArg(), args_, invalidPath(), JSONCPP_STRING, Json::PathArgument::kindIndex, and Json::PathArgument::kindKey.
Referenced by Path().
resolve() [1/2]
const Value & Json::Path::resolve (const Value & root) const
Definition at line 1566 of file json_value.cpp.
{
   const Value* node = &root;
   for (Args::const_iterator it = args_.begin(); it != args_.end(); ++it) {
     const PathArgument& arg = *it;
     if (arg.kind_ == PathArgument::kindIndex) {
       if (!node->isArray() || !node->isValidIndex(arg.index_)) {
         // Error: unable to resolve path (array value expected at position...
         return Value::null;
       }
       node = &((*node)[arg.index_]);
     } else if (arg.kind_ == PathArgument::kindKey) {
       if (!node->isObject()) {
         // Error: unable to resolve path (object value expected at position...)
         return Value::null;
       }
       node = &((*node)[arg.key_]);
       if (node == &Value::nullSingleton()) {
         // Error: unable to resolve path (object has no member named '' at
         // position...)
         return Value::null;
       }
     }
   }
   return *node;
 }
References args_, Json::PathArgument::index_, Json::Value::isArray(), Json::Value::isObject(), Json::Value::isValidIndex(), Json::PathArgument::key_, Json::PathArgument::kind_, Json::PathArgument::kindIndex, Json::PathArgument::kindKey, Json::Value::null, and Json::Value::nullSingleton().
resolve() [2/2]
Value Json::Path::resolve (const Value & root, const Value & defaultValue) const
Definition at line 1592 of file json_value.cpp.
{
   const Value* node = &root;
   for (Args::const_iterator it = args_.begin(); it != args_.end(); ++it) {
     const PathArgument& arg = *it;
     if (arg.kind_ == PathArgument::kindIndex) {
       if (!node->isArray() || !node->isValidIndex(arg.index_))
         return defaultValue;
       node = &((*node)[arg.index_]);
     } else if (arg.kind_ == PathArgument::kindKey) {
       if (!node->isObject())
         return defaultValue;
       node = &((*node)[arg.key_]);
       if (node == &Value::nullSingleton())
         return defaultValue;
     }
   }
   return *node;
 }
References args_, Json::PathArgument::index_, Json::Value::isArray(), Json::Value::isObject(), Json::Value::isValidIndex(), Json::PathArgument::key_, Json::PathArgument::kind_, Json::PathArgument::kindIndex, Json::PathArgument::kindKey, and Json::Value::nullSingleton().
Member Data Documentation
args_
Args Json::Path::args_ private
Definition at line 685 of file value.h.
Referenced by addPathInArg(), make(), makePath(), and resolve().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/json/value.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/json/json_value.cpp