My Project: cSimBodyLink Class Reference
cSimBodyLink Class Reference
#include <SimBodyLink.h>
Classes
struct tParams
Public Member Functions
cSimBodyLink ()
virtual ~cSimBodyLink ()
virtual void Init (const std::shared_ptr< cWorld > &world, const std::shared_ptr< cMultiBody > &mult_body, const tParams &params)
virtual tVector GetSize () const
virtual tVector GetLinearVelocity () const
virtual tVector GetLinearVelocity (const tVector &local_pos) const
virtual void SetLinearVelocity (const tVector &vel)
virtual tVector GetAngularVelocity () const
virtual void SetAngularVelocity (const tVector &vel)
virtual double GetMass () const
virtual double GetFriction () const
virtual void SetFriction (double friction)
virtual void ApplyForce (const tVector &force)
virtual void ApplyForce (const tVector &force, const tVector &local_pos)
virtual void ApplyTorque (const tVector &torque)
virtual void ClearForces ()
virtual cShape::eShape GetShape () const
virtual void UpdateVel (const tVector &lin_vel, const tVector &ang_vel)
virtual const std::shared_ptr< cMultiBody > & GetMultBody () const
virtual int GetJointID () const
Public Member Functions inherited from cSimObj
virtual ~cSimObj ()
virtual tVector GetPos () const
virtual void SetPos (const tVector &pos)
virtual void GetRotation (tVector &out_axis, double &out_theta) const
virtual tQuaternion GetRotation () const
virtual void SetRotation (const tVector &axis, double theta)
virtual void SetRotation (const tQuaternion &q)
virtual tMatrix GetWorldTransform () const
virtual tMatrix GetLocalTransform () const
virtual tVector WorldToLocalPos (const tVector &world_pos) const
virtual tVector LocalToWorldPos (const tVector &local_pos) const
virtual tMatrix3 GetLocalToWorldRotMat () const
virtual tVector CalcCOM () const
virtual tVector CalcCOMVel () const
virtual void RegisterContact ()
virtual void RegisterContact (int contact_flags, int filter_flags)
virtual void UpdateContact (int contact_flags, int filter_flags)
virtual const cContactManager::tContactHandle & GetContactHandle () const
virtual bool IsInContact () const
virtual const tEigenArr< cContactManager::tContactPt > & GetContactPts () const
virtual short GetColGroup () const
virtual void SetColGroup (short col_group)
virtual short GetColMask () const
virtual void SetColMask (short col_mask)
virtual eType GetType () const
virtual void CalcAABB (tVector &out_min, tVector &out_max) const
virtual const btCollisionShape * GetCollisionShape () const
Protected Member Functions
virtual void InitSize (tVector &out_size) const
virtual cShape::eShape FetchObjShape () const
virtual void RemoveFromWorld ()
virtual const btCollisionObject * GetCollisionObject () const
virtual btCollisionObject * GetCollisionObject ()
Protected Member Functions inherited from cSimObj
cSimObj ()
virtual const std::shared_ptr< cWorld > & GetWorld () const
Protected Attributes
std::shared_ptr< cMultiBody > mMultBody
std::unique_ptr< btMultiBodyLinkCollider > mColObj
int mJointID
double mMass
tVector mSize
cShape::eShape mObjShape
tVector mLinVel
tVector mAngVel
Protected Attributes inherited from cSimObj
std::shared_ptr< cWorld > mWorld
std::unique_ptr< btCollisionShape > mColShape
cContactManager::tContactHandle mContactHandle
bool mEnableContactFall
eType mType
short mColGroup
short mColMask
Additional Inherited Members
Public Types inherited from cSimObj
enum eType { eTypeDynamic, eTypeStatic, eTypeMax }
Detailed Description
Definition at line 5 of file SimBodyLink.h.
Constructor & Destructor Documentation
cSimBodyLink()
cSimBodyLink::cSimBodyLink ()
Definition at line 10 of file SimBodyLink.cpp.
 {
     mMass = 0;
     mJointID = gInvalidIdx;
     mSize.setZero();
     mObjShape = cShape::eShapeNull;
     mLinVel.setZero();
     mAngVel.setZero();
 }
References cShape::eShapeNull, gInvalidIdx, mAngVel, mJointID, mLinVel, mMass, mObjShape, and mSize.
~cSimBodyLink()
cSimBodyLink::~cSimBodyLink () virtual
Definition at line 20 of file SimBodyLink.cpp.
 {
     RemoveFromWorld();
 }
References RemoveFromWorld().
Member Function Documentation
ApplyForce() [1/2]
void cSimBodyLink::ApplyForce (const tVector & force) virtual
Implements cSimObj.
Definition at line 97 of file SimBodyLink.cpp.
 {
     btScalar scale = static_cast<btScalar>(mWorld->GetScale());
     mMultBody->addLinkForce(mJointID, scale * btVector3(force[0], force[1], force[2]));
 }
References mJointID, mMultBody, and cSimObj::mWorld.
Referenced by ApplyForce().
ApplyForce() [2/2]
void cSimBodyLink::ApplyForce (const tVector & force, const tVector & local_pos) virtual
Implements cSimObj.
Definition at line 103 of file SimBodyLink.cpp.
 {
     btScalar scale = static_cast<btScalar>(mWorld->GetScale());
     tMatrix world_mat = GetWorldTransform();
     tVector world_pos = world_mat * local_pos;
     tVector torque = world_pos.cross3(force);
     ApplyForce(force);
     ApplyTorque(torque);
 }
References ApplyForce(), ApplyTorque(), cSimObj::GetWorldTransform(), and cSimObj::mWorld.
ApplyTorque()
void cSimBodyLink::ApplyTorque (const tVector & torque) virtual
Implements cSimObj.
Definition at line 114 of file SimBodyLink.cpp.
 {
     btScalar scale = static_cast<btScalar>(mWorld->GetScale());
     mMultBody->addLinkTorque(mJointID, scale * scale * btVector3(torque[0], torque[1], torque[2]));
 }
References mJointID, mMultBody, and cSimObj::mWorld.
Referenced by ApplyForce().
ClearForces()
void cSimBodyLink::ClearForces () virtual
Implements cSimObj.
Definition at line 120 of file SimBodyLink.cpp.
 {
     mMultBody->clearForcesAndTorques();
 }
References mMultBody.
FetchObjShape()
cShape::eShape cSimBodyLink::FetchObjShape () const protected virtual
Definition at line 180 of file SimBodyLink.cpp.
 {
     cShape::eShape obj_shape = cShape::eShapeNull;
     int shape_type = mColShape->getShapeType();
     switch (shape_type)
     {
     case BOX_SHAPE_PROXYTYPE:
         obj_shape = cShape::eShapeBox;
         break;
     case CAPSULE_SHAPE_PROXYTYPE:
         obj_shape = cShape::eShapeCapsule;
         break;
     case SPHERE_SHAPE_PROXYTYPE:
         obj_shape = cShape::eShapeSphere;
         break;
     case CYLINDER_SHAPE_PROXYTYPE:
         obj_shape = cShape::eShapeCylinder;
         break;
     default:
         printf("Unsupported object shape\n");
         assert(false);
         break;
     }
     return obj_shape;
 }
References cShape::eShapeBox, cShape::eShapeCapsule, cShape::eShapeCylinder, cShape::eShapeNull, cShape::eShapeSphere, and cSimObj::mColShape.
Referenced by Init().
GetAngularVelocity()
tVector cSimBodyLink::GetAngularVelocity () const virtual
Implements cSimObj.
Definition at line 72 of file SimBodyLink.cpp.
 {
     return mAngVel;
 }
References mAngVel.
Referenced by GetLinearVelocity().
GetCollisionObject() [1/2]
btCollisionObject * cSimBodyLink::GetCollisionObject () protected virtual
Implements cSimObj.
Definition at line 151 of file SimBodyLink.cpp.
 {
     return mColObj.get();
 }
References mColObj.
GetCollisionObject() [2/2]
const btCollisionObject * cSimBodyLink::GetCollisionObject () const protected virtual
Implements cSimObj.
Definition at line 146 of file SimBodyLink.cpp.
 {
     return mColObj.get();
 }
References mColObj.
Referenced by RemoveFromWorld().
GetFriction()
double cSimBodyLink::GetFriction () const virtual
Definition at line 87 of file SimBodyLink.cpp.
 {
     return mColObj->getFriction();
 }
References mColObj.
GetJointID()
int cSimBodyLink::GetJointID () const virtual
Definition at line 141 of file SimBodyLink.cpp.
 {
     return mJointID;
 }
References mJointID.
Referenced by cSimJoint::BuildConstraintSpherical().
GetLinearVelocity() [1/2]
tVector cSimBodyLink::GetLinearVelocity () const virtual
Implements cSimObj.
Definition at line 52 of file SimBodyLink.cpp.
 {
     return mLinVel;
 }
References mLinVel.
Referenced by GetLinearVelocity().
GetLinearVelocity() [2/2]
tVector cSimBodyLink::GetLinearVelocity (const tVector & local_pos) const virtual
Implements cSimObj.
Definition at line 57 of file SimBodyLink.cpp.
 {
     tVector ang_vel = GetAngularVelocity();
     tVector lin_vel = GetLinearVelocity();
     tQuaternion rot = GetRotation();
     tVector world_pos = cMathUtil::QuatRotVec(rot, local_pos);
     tVector vel = lin_vel + ang_vel.cross3(world_pos);
     return vel;
 }
References GetAngularVelocity(), GetLinearVelocity(), cSimObj::GetRotation(), and cMathUtil::QuatRotVec().
GetMass()
double cSimBodyLink::GetMass () const virtual
Definition at line 82 of file SimBodyLink.cpp.
 {
     return mMass;
 }
References mMass.
GetMultBody()
const std::shared_ptr< cMultiBody > & cSimBodyLink::GetMultBody () const virtual
Definition at line 136 of file SimBodyLink.cpp.
 {
     return mMultBody;
 }
References mMultBody.
Referenced by cSimJoint::BuildConstraintSpherical().
GetShape()
cShape::eShape cSimBodyLink::GetShape () const virtual
Reimplemented from cSimObj.
Definition at line 125 of file SimBodyLink.cpp.
 {
     return mObjShape;
 }
References mObjShape.
GetSize()
tVector cSimBodyLink::GetSize () const virtual
Implements cSimObj.
Definition at line 47 of file SimBodyLink.cpp.
 {
     return mSize;
 }
References mSize.
Init()
void cSimBodyLink::Init (const std::shared_ptr< cWorld > & world, const std::shared_ptr< cMultiBody > & mult_body, const tParams & params) virtual
Definition at line 25 of file SimBodyLink.cpp.
 {
     RemoveFromWorld();
     mJointID = params.mJointID;
     mMass = params.mMass;
     mWorld = world;
     mMultBody = mult_body;
     mType = eTypeDynamic;
     mLinVel.setZero();
     mAngVel.setZero();
     mColObj = std::unique_ptr<btMultiBodyLinkCollider>(mMultBody->getLink(mJointID).m_collider);
     mColObj->setUserPointer(this);
     mColShape = std::unique_ptr<btCollisionShape>(mColObj->getCollisionShape());
     mObjShape = FetchObjShape();
     InitSize(mSize);
 }
References cSimObj::eTypeDynamic, FetchObjShape(), InitSize(), mAngVel, mColObj, cSimObj::mColShape, cSimBodyLink::tParams::mJointID, mJointID, mLinVel, cSimBodyLink::tParams::mMass, mMass, mMultBody, mObjShape, mSize, cSimObj::mType, cSimObj::mWorld, and RemoveFromWorld().
InitSize()
void cSimBodyLink::InitSize (tVector & out_size) const protected virtual
Definition at line 156 of file SimBodyLink.cpp.
 {
     out_size.setZero();
     switch (mObjShape)
     {
     case cShape::eShapeBox:
         out_size = mWorld->GetSizeBox(*this);
         break;
     case cShape::eShapeCapsule:
         out_size = mWorld->GetSizeCapsule(*this);
         break;
     case cShape::eShapeSphere:
         out_size = mWorld->GetSizeSphere(*this);
         break;
     case cShape::eShapeCylinder:
         out_size = mWorld->GetSizeCylinder(*this);
         break;
     default:
         printf("Unsupported body link shape\n");
         assert(false);
         break;
     }
 }
References cShape::eShapeBox, cShape::eShapeCapsule, cShape::eShapeCylinder, cShape::eShapeSphere, mObjShape, and cSimObj::mWorld.
Referenced by Init().
RemoveFromWorld()
void cSimBodyLink::RemoveFromWorld () protected virtual
Definition at line 206 of file SimBodyLink.cpp.
 {
     if (mWorld != nullptr && mColObj != nullptr)
     {
         mWorld->RemoveCollisionObject(GetCollisionObject());
         mWorld.reset();
         mColShape.reset();
         mColObj.reset();
     }
 }
References GetCollisionObject(), mColObj, cSimObj::mColShape, and cSimObj::mWorld.
Referenced by Init(), and ~cSimBodyLink().
SetAngularVelocity()
void cSimBodyLink::SetAngularVelocity (const tVector & vel) virtual
Implements cSimObj.
Definition at line 77 of file SimBodyLink.cpp.
 {
     assert(false); // unsupported
 }
SetFriction()
void cSimBodyLink::SetFriction (double friction) virtual
Definition at line 92 of file SimBodyLink.cpp.
 {
     mColObj->setFriction(friction);
 }
References mColObj.
SetLinearVelocity()
void cSimBodyLink::SetLinearVelocity (const tVector & vel) virtual
Implements cSimObj.
Definition at line 67 of file SimBodyLink.cpp.
 {
     assert(false); // unsupported
 }
UpdateVel()
void cSimBodyLink::UpdateVel (const tVector & lin_vel, const tVector & ang_vel) virtual
Definition at line 130 of file SimBodyLink.cpp.
 {
     mLinVel = lin_vel;
     mAngVel = ang_vel;
 }
References mAngVel, and mLinVel.
Member Data Documentation
mAngVel
tVector cSimBodyLink::mAngVel protected
Definition at line 54 of file SimBodyLink.h.
Referenced by cSimBodyLink(), GetAngularVelocity(), Init(), and UpdateVel().
mColObj
std::unique_ptr<btMultiBodyLinkCollider> cSimBodyLink::mColObj protected
Definition at line 46 of file SimBodyLink.h.
Referenced by GetCollisionObject(), GetFriction(), Init(), RemoveFromWorld(), and SetFriction().
mJointID
int cSimBodyLink::mJointID protected
Definition at line 48 of file SimBodyLink.h.
Referenced by ApplyForce(), ApplyTorque(), cSimBodyLink(), GetJointID(), and Init().
mLinVel
tVector cSimBodyLink::mLinVel protected
Definition at line 53 of file SimBodyLink.h.
Referenced by cSimBodyLink(), GetLinearVelocity(), Init(), and UpdateVel().
mMass
double cSimBodyLink::mMass protected
Definition at line 49 of file SimBodyLink.h.
Referenced by cSimBodyLink(), GetMass(), and Init().
mMultBody
std::shared_ptr<cMultiBody> cSimBodyLink::mMultBody protected
Definition at line 45 of file SimBodyLink.h.
Referenced by ApplyForce(), ApplyTorque(), ClearForces(), GetMultBody(), and Init().
mObjShape
cShape::eShape cSimBodyLink::mObjShape protected
Definition at line 51 of file SimBodyLink.h.
Referenced by cSimBodyLink(), GetShape(), Init(), and InitSize().
mSize
tVector cSimBodyLink::mSize protected
Definition at line 50 of file SimBodyLink.h.
Referenced by cSimBodyLink(), GetSize(), and Init().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimBodyLink.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/SimBodyLink.cpp