My Project: cAgentRegistry Class Reference
cAgentRegistry Class Reference
#include <AgentRegistry.h>
Public Member Functions
cAgentRegistry ()
virtual ~cAgentRegistry ()
virtual void Clear ()
virtual int GetNumAgents () const
virtual int AddAgent (const std::shared_ptr< cCharController > &agent, cSimCharacter *character)
virtual const std::shared_ptr< cCharController > & GetAgent (int id) const
virtual cSimCharacter * GetChar (int id) const
virtual void PrintInfo () const
Protected Attributes
cIndexManager mIDManager
std::vector< std::shared_ptr< cCharController > > mAgents
std::vector< cSimCharacter * > mChars
Detailed Description
Definition at line 6 of file AgentRegistry.h.
Constructor & Destructor Documentation
cAgentRegistry()
cAgentRegistry::cAgentRegistry ()
Definition at line 3 of file AgentRegistry.cpp.
 {
 }
~cAgentRegistry()
cAgentRegistry::~cAgentRegistry () virtual
Definition at line 7 of file AgentRegistry.cpp.
 {
 }
Member Function Documentation
AddAgent()
int cAgentRegistry::AddAgent (const std::shared_ptr< cCharController > & agent, cSimCharacter * character) virtual
Definition at line 23 of file AgentRegistry.cpp.
 {
     if (mIDManager.IsFull())
     {
         int curr_size = mIDManager.GetSize();
         mIDManager.Resize(curr_size + 1);
     }
     int num_agents = static_cast<int>(mAgents.size());
     int id = mIDManager.RequestIndex();
     if (id >= num_agents)
     {
         assert(id == num_agents);
         mAgents.push_back(agent);
         mChars.push_back(character);
     }
     else
     {
         mAgents[id] = agent;
         mChars[id] = character;
     }
     return id;
 }
References cIndexManager::GetSize(), cIndexManager::IsFull(), mAgents, mChars, mIDManager, cIndexManager::RequestIndex(), and cIndexManager::Resize().
Referenced by cRLSceneSimChar::RegisterAgent().
Clear()
void cAgentRegistry::Clear () virtual
Definition at line 11 of file AgentRegistry.cpp.
 {
     mIDManager.Clear();
     mAgents.clear();
     mChars.clear();
 }
References cIndexManager::Clear(), mAgents, mChars, and mIDManager.
Referenced by cRLSceneSimChar::Clear(), and cRLSceneSimChar::Init().
GetAgent()
const std::shared_ptr< cCharController > & cAgentRegistry::GetAgent (int id) const virtual
Definition at line 47 of file AgentRegistry.cpp.
 {
     return mAgents[id];
 }
References mAgents.
Referenced by cRLSceneSimChar::GetController(), cRLSceneSimChar::GetRewardMax(), cRLSceneSimChar::GetRewardMin(), cRLSceneSimChar::PreUpdate(), and PrintInfo().
GetChar()
cSimCharacter * cAgentRegistry::GetChar (int id) const virtual
Definition at line 52 of file AgentRegistry.cpp.
 {
     return mChars[id];
 }
References mChars.
Referenced by cRLSceneSimChar::GetAgentChar().
GetNumAgents()
int cAgentRegistry::GetNumAgents () const virtual
Definition at line 18 of file AgentRegistry.cpp.
 {
     return mIDManager.GetNumUsed();
 }
References cIndexManager::GetNumUsed(), and mIDManager.
Referenced by cRLSceneSimChar::GetNumAgents(), and PrintInfo().
PrintInfo()
void cAgentRegistry::PrintInfo () const virtual
Definition at line 57 of file AgentRegistry.cpp.
 {
     int num_agents = GetNumAgents();
     printf("\n");
     printf("Agent Registry\n");
     printf("Num Agents: %i\n", num_agents);
     for (int i = 0; i < num_agents; ++i)
     {
         const auto& agent = GetAgent(i);
         std::string name = agent->GetName();
         printf("Agent %i: %s\n", i, name.c_str());
     }
     printf("\n");
 }
References GetAgent(), and GetNumAgents().
Referenced by cRLSceneSimChar::Init().
Member Data Documentation
mAgents
std::vector<std::shared_ptr<cCharController> > cAgentRegistry::mAgents protected
Definition at line 23 of file AgentRegistry.h.
Referenced by AddAgent(), Clear(), and GetAgent().
mChars
std::vector<cSimCharacter*> cAgentRegistry::mChars protected
Definition at line 24 of file AgentRegistry.h.
Referenced by AddAgent(), Clear(), and GetChar().
mIDManager
cIndexManager cAgentRegistry::mIDManager protected
Definition at line 22 of file AgentRegistry.h.
Referenced by AddAgent(), Clear(), and GetNumAgents().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/AgentRegistry.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/AgentRegistry.cpp