My Project: cShadowMap Class Reference
cShadowMap Class Reference
#include <ShadowMap.h>
Public Member Functions
cShadowMap (void)
~cShadowMap (void)
bool Init (unsigned int WindowWidth, unsigned int WindowHeight)
void Reshape (int w, int h)
Public Member Functions inherited from cTextureDesc
cTextureDesc (int width, int height, int channels, GLenum format, GLenum type, bool mipmaps)
cTextureDesc (int width, int height, int depth, int channels, GLenum format, GLenum type, bool mipmaps)
cTextureDesc (GLuint obj, GLuint tex, GLuint ds, int width, int height, int depth, int channels, GLenum format)
cTextureDesc (const std::string &filename, bool gen_mips=false)
virtual ~cTextureDesc ()
virtual void BindBuffer () const
virtual void UnbindBuffer () const
virtual bool CheckBoundBuffer () const
virtual void BindBuffer3DSlice (int slice) const
virtual void BindTex (GLint tex_slot) const
virtual void UnbindTex (GLint tex_slot) const
virtual GLuint GetObj () const
virtual GLuint GetTexture () const
virtual GLuint GetDepthStencil () const
virtual bool IsValid () const
virtual bool IsRenderBuffer () const
virtual int GetWidth () const
virtual int GetHeight () const
virtual int GetNumTexels () const
virtual int GetNumChannels () const
virtual void ReadPixels (std::vector< GLfloat > &out_data, GLenum format=GL_RGBA)
virtual void WritePixels (const std::vector< GLubyte > &data)
Additional Inherited Members
Protected Member Functions inherited from cTextureDesc
cTextureDesc ()
virtual void PushTextureStack () const
virtual void PopTextureStack () const
Protected Attributes inherited from cTextureDesc
int mWidth
int mHeight
int mDepth
int mChannels
GLenum mFormat
GLenum mType
bool mHasMips
GLuint mObject
GLuint mTexture
GLuint mDepthStencil
Static Protected Attributes inherited from cTextureDesc
static const int gNumViewportParams = 4
static std::stack< tTexEntry > gTexStack = std::stack<cTextureDesc::tTexEntry>()
Detailed Description
Definition at line 5 of file ShadowMap.h.
Constructor & Destructor Documentation
cShadowMap()
cShadowMap::cShadowMap (void)
Definition at line 3 of file ShadowMap.cpp.
 {
 }
~cShadowMap()
cShadowMap::~cShadowMap (void)
Definition at line 66 of file ShadowMap.cpp.
 {
 }
Member Function Documentation
Init()
bool cShadowMap::Init (unsigned int WindowWidth, unsigned int WindowHeight)
Definition at line 7 of file ShadowMap.cpp.
 {
     mWidth = width;
     mHeight = height;
     glEnable(GL_TEXTURE_2D);
     // depth buffer
     glGenTextures(1, &mTexture);
     glBindTexture(GL_TEXTURE_2D, mTexture);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_BORDER);
     float border_color[4] = { 1.f, 1.f, 1.f, 1.f };
     glTexParameterfv(GL_TEXTURE_2D, GL_TEXTURE_BORDER_COLOR, border_color);
     glTexImage2D(GL_TEXTURE_2D, 0, GL_DEPTH_COMPONENT16, width, height,
         0, GL_DEPTH_COMPONENT, GL_FLOAT, 0);
     // linked depth stencil and render texture
     glGenFramebuffers(1, &mObject);
     glBindFramebuffer(GL_FRAMEBUFFER, mObject);
     glFramebufferTexture(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, mTexture, 0);
     //Intel OpenGL driver crashes when using GL_NONE for glDrawBuffer on Linux, so use a workaround
 #ifdef _WIN32
     glDrawBuffer(GL_NONE);
 #else
     GLenum drawBuffers[2] = { GL_COLOR_ATTACHMENT0,0 };
     glDrawBuffers(1, drawBuffers);
 #endif
     GLenum status;
     if ((status = glCheckFramebufferStatus(GL_FRAMEBUFFER)) != GL_FRAMEBUFFER_COMPLETE) {
         printf("texture is incomplete/n");
     }
     glBindTexture(GL_TEXTURE_2D, 0);
     glBindFramebuffer(GL_FRAMEBUFFER, 0);
     return true;
 }
References cTextureDesc::mHeight, cTextureDesc::mObject, cTextureDesc::mTexture, and cTextureDesc::mWidth.
Referenced by Reshape().
Reshape()
void cShadowMap::Reshape (int w, int h) virtual
Reimplemented from cTextureDesc.
Definition at line 55 of file ShadowMap.cpp.
 {
     mWidth = std::max(1, w);
     mHeight = std::max(1, h);
     if (mObject != 0) // 0 indicates the device's frame buffer, so no need to resize it
     {
         cTextureUtil::DeleteFrameBuffer(mObject, mTexture, mDepthStencil);
         Init(w, h);
     }
 }
References cTextureUtil::DeleteFrameBuffer(), Init(), cTextureDesc::mDepthStencil, cTextureDesc::mHeight, cTextureDesc::mObject, cTextureDesc::mTexture, and cTextureDesc::mWidth.
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/ShadowMap.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/ShadowMap.cpp