My Project: cSceneImitate Class Reference
cSceneImitate Class Reference
#include <SceneImitate.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cSceneImitate ()
virtual ~cSceneImitate ()
virtual void ParseArgs (const std::shared_ptr< cArgParser > &parser)
virtual void Init ()
virtual const std::shared_ptr< cKinCharacter > & GetKinChar () const
virtual void EnableRandRotReset (bool enable)
virtual bool EnabledRandRotReset () const
virtual double CalcReward (int agent_id) const
virtual eTerminate CheckTerminate (int agent_id) const
virtual std::string GetName () const
Public Member Functions inherited from cRLSceneSimChar
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cRLSceneSimChar ()
virtual ~cRLSceneSimChar ()
virtual void Clear ()
virtual int GetNumAgents () const
virtual bool NeedNewAction (int agent_id) const
virtual void RecordState (int agent_id, Eigen::VectorXd &out_state) const
virtual void RecordGoal (int agent_id, Eigen::VectorXd &out_goal) const
virtual void SetAction (int agent_id, const Eigen::VectorXd &action)
virtual eActionSpace GetActionSpace (int agent_id) const
virtual int GetStateSize (int agent_id) const
virtual int GetGoalSize (int agent_id) const
virtual int GetActionSize (int agent_id) const
virtual int GetNumActions (int agent_id) const
virtual void BuildStateOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildGoalOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionOffsetScale (int agent_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionBounds (int agent_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max) const
virtual void BuildStateNormGroups (int agent_id, Eigen::VectorXi &out_groups) const
virtual void BuildGoalNormGroups (int agent_id, Eigen::VectorXi &out_groups) const
virtual double GetRewardMin (int agent_id) const
virtual double GetRewardMax (int agent_id) const
virtual bool CheckValidEpisode () const
virtual void LogVal (int agent_id, double val)
virtual void SetSampleCount (int count)
Public Member Functions inherited from cRLScene
virtual ~cRLScene ()
virtual double GetRewardFail (int agent_id)
virtual double GetRewardSucc (int agent_id)
virtual bool IsEpisodeEnd () const
virtual void SetMode (eMode mode)
Public Member Functions inherited from cScene
virtual ~cScene ()
virtual void Reset ()
virtual void Draw ()
virtual void Keyboard (unsigned char key, double device_x, double device_y)
virtual void MouseClick (int button, int state, double device_x, double device_y)
virtual void MouseMove (double device_x, double device_y)
virtual void Reshape (int w, int h)
virtual void Shutdown ()
virtual bool IsDone () const
virtual double GetTime () const
virtual bool HasRandSeed () const
virtual unsigned long GetRandSeed () const
Public Member Functions inherited from cSceneSimChar
cSceneSimChar ()
virtual ~cSceneSimChar ()
virtual void Update (double time_elapsed)
virtual int GetNumChars () const
virtual const std::shared_ptr< cSimCharacter > & GetCharacter () const
virtual const std::shared_ptr< cSimCharacter > & GetCharacter (int char_id) const
virtual const std::shared_ptr< cWorld > & GetWorld () const
virtual tVector GetCharPos () const
virtual const std::shared_ptr< cGround > & GetGround () const
virtual const tVector & GetGravity () const
virtual bool LoadControlParams (const std::string &param_file, const std::shared_ptr< cSimCharacter > &out_char)
virtual void AddPerturb (const tPerturb &perturb)
virtual void ApplyRandForce (double min_force, double max_force, double min_dur, double max_dur, cSimObj *obj)
virtual void ApplyRandForce ()
virtual void ApplyRandForce (int char_id)
virtual void RayTest (const tVector &beg, const tVector &end, cWorld::tRayTestResult &out_result) const
virtual void SetGroundParamBlend (double lerp)
virtual int GetNumParamSets () const
virtual void OutputCharState (const std::string &out_file) const
virtual void OutputGround (const std::string &out_file) const
virtual void SpawnProjectile ()
virtual void SpawnBigProjectile ()
virtual int GetNumObjs () const
virtual const std::shared_ptr< cSimRigidBody > & GetObj (int id) const
virtual const tObjEntry & GetObjEntry (int id) const
virtual void SetRandSeed (unsigned long seed)
Protected Member Functions
virtual bool BuildCharacters ()
virtual void CalcJointWeights (const std::shared_ptr< cSimCharacter > &character, Eigen::VectorXd &out_weights) const
virtual bool BuildController (const cCtrlBuilder::tCtrlParams &ctrl_params, std::shared_ptr< cCharController > &out_ctrl)
virtual void BuildKinChar ()
virtual bool BuildKinCharacter (int id, std::shared_ptr< cKinCharacter > &out_char) const
virtual void UpdateCharacters (double timestep)
virtual void UpdateKinChar (double timestep)
virtual void ResetCharacters ()
virtual void ResetKinChar ()
virtual void SyncCharacters ()
virtual bool EnableSyncChar () const
virtual void InitCharacterPosFixed (const std::shared_ptr< cSimCharacter > &out_char)
virtual void InitJointWeights ()
virtual void ResolveCharGroundIntersect ()
virtual void ResolveCharGroundIntersect (const std::shared_ptr< cSimCharacter > &out_char) const
virtual void SyncKinCharRoot ()
virtual void SyncKinCharNewCycle (const cSimCharacter &sim_char, cKinCharacter &out_kin_char) const
virtual double GetKinTime () const
virtual bool CheckKinNewCycle (double timestep) const
virtual bool HasFallen (const cSimCharacter &sim_char) const
virtual bool CheckRootRotFail (const cSimCharacter &sim_char) const
virtual bool CheckRootRotFail (const cSimCharacter &sim_char, const cKinCharacter &kin_char) const
virtual double CalcRandKinResetTime ()
virtual double CalcRewardImitate (const cSimCharacter &sim_char, const cKinCharacter &ref_char) const
Protected Member Functions inherited from cRLSceneSimChar
virtual void ResetParams ()
virtual void ResetScene ()
virtual const std::shared_ptr< cCharController > & GetController () const
virtual const std::shared_ptr< cCharController > & GetController (int agent_id) const
virtual const cSimCharacter * GetAgentChar (int agent_id) const
virtual void PreUpdate (double timestep)
virtual void ResetTimers ()
virtual void NewActionUpdate (int agent_id)
virtual bool EnableFallEnd () const
virtual void RegisterAgents ()
virtual void RegisterAgent (const std::shared_ptr< cCharController > &ctrl, const std::shared_ptr< cSimCharacter > &character)
virtual void RegisterAgent (const std::shared_ptr< cCharController > &ctrl, const std::shared_ptr< cSimCharacter > &character, std::vector< int > &out_ids)
virtual void SetupTimerAnnealer (cAnnealer &out_annealer) const
virtual void UpdateTimerParams ()
Protected Member Functions inherited from cRLScene
cRLScene ()
Protected Member Functions inherited from cScene
cScene ()
virtual void InitTimers ()
virtual void UpdateTimers (double timestep)
Protected Member Functions inherited from cSceneSimChar
virtual bool ParseCharTypes (const std::shared_ptr< cArgParser > &parser, std::vector< cSimCharBuilder::eCharType > &out_types) const
virtual bool ParseCharParams (const std::shared_ptr< cArgParser > &parser, std::vector< cSimCharacter::tParams > &out_params) const
virtual bool ParseCharCtrlParams (const std::shared_ptr< cArgParser > &parser, std::vector< cCtrlBuilder::tCtrlParams > &out_params) const
virtual void BuildWorld ()
virtual void BuildGround ()
virtual void SetFallContacts (const std::vector< int > &fall_bodies, cSimCharacter &out_char) const
virtual void InitCharacterPos ()
virtual void InitCharacterPos (const std::shared_ptr< cSimCharacter > &out_char)
virtual void SetCharRandPlacement (const std::shared_ptr< cSimCharacter > &out_char)
virtual void CalcCharRandPlacement (const std::shared_ptr< cSimCharacter > &out_char, tVector &out_pos, tQuaternion &out_rot)
virtual void UpdateWorld (double time_step)
virtual void PostUpdateCharacters (double time_step)
virtual void UpdateGround (double time_elapsed)
virtual void UpdateRandPerturb (double time_step)
virtual void ResetWorld ()
virtual void ResetGround ()
virtual void PostUpdate (double timestep)
virtual int GetRandPerturbPartID (const std::shared_ptr< cSimCharacter > &character)
virtual void GetViewBound (tVector &out_min, tVector &out_max) const
virtual void ParseGroundParams (const std::shared_ptr< cArgParser > &parser, cGround::tParams &out_params) const
virtual void UpdateObjs (double timestep)
virtual void UpdateJoints (double timestep)
virtual void ClearJointForces ()
virtual void ClearObjs ()
virtual void CleanObjs ()
virtual int AddObj (const tObjEntry &obj_entry)
virtual void RemoveObj (int handle)
virtual void ClearJoints ()
virtual int AddJoint (const tJointEntry &joint_entry)
virtual void RemoveJoint (int handle)
virtual int GetNumJoints () const
virtual void SpawnProjectile (double density, double min_size, double max_size, double min_speed, double max_speed, double y_offset, double life_time)
virtual void ResetRandPertrub ()
Protected Attributes
std::string mMotionFile
std::shared_ptr< cKinCharacter > mKinChar
Eigen::VectorXd mJointWeights
bool mEnableRandRotReset
bool mSyncCharRootPos
bool mSyncCharRootRot
bool mEnableRootRotFail
double mHoldEndFrame
Protected Attributes inherited from cRLSceneSimChar
bool mEnableFallEnd
cAgentRegistry mAgentReg
cTimer::tParams mTimerParamsEnd
cAnnealer mTimerAnnealer
int mAnnealSamples
Protected Attributes inherited from cRLScene
eMode mMode
int mSampleCount
Protected Attributes inherited from cScene
cRand mRand
bool mHasRandSeed
unsigned long mRandSeed
std::shared_ptr< cArgParser > mArgParser
cTimer::tParams mTimerParams
cTimer mTimer
Protected Attributes inherited from cSceneSimChar
cWorld::tParams mWorldParams
std::vector< cSimCharacter::tParams > mCharParams
std::vector< cCtrlBuilder::tCtrlParams > mCtrlParams
bool mEnableContactFall
bool mEnableRandCharPlacement
std::vector< int > mFallContactBodies
std::shared_ptr< cWorld > mWorld
std::shared_ptr< cGround > mGround
std::vector< std::shared_ptr< cSimCharacter > > mChars
std::vector< cSimCharBuilder::eCharType > mCharTypes
cGround::tParams mGroundParams
tPerturbParams mPerturbParams
cIndexBuffer< tObjEntry, Eigen::aligned_allocator< tObjEntry > > mObjs
cIndexBuffer< tJointEntry > mJoints
Additional Inherited Members
Public Types inherited from cRLScene
enum eMode { eModeTrain, eModeTest, eModeMax }
enum eTerminate { eTerminateNull, eTerminateFail, eTerminateSucc, eTerminateMax }
Static Protected Attributes inherited from cSceneSimChar
static const double gGroundSpawnOffset = -1
Detailed Description
Definition at line 6 of file SceneImitate.h.
Constructor & Destructor Documentation
cSceneImitate()
cSceneImitate::cSceneImitate ()
Definition at line 136 of file SceneImitate.cpp.
 {
     mEnableRandRotReset = false;
     mSyncCharRootPos = true;
     mSyncCharRootRot = false;
     mMotionFile = "";
     mEnableRootRotFail = false;
     mHoldEndFrame = 0;
 }
References mEnableRandRotReset, mEnableRootRotFail, mHoldEndFrame, mMotionFile, mSyncCharRootPos, and mSyncCharRootRot.
~cSceneImitate()
cSceneImitate::~cSceneImitate () virtual
Definition at line 146 of file SceneImitate.cpp.
 {
 }
Member Function Documentation
BuildCharacters()
bool cSceneImitate::BuildCharacters () protected virtual
Reimplemented from cSceneSimChar.
Definition at line 230 of file SceneImitate.cpp.
 {
     bool succ = cRLSceneSimChar::BuildCharacters();
     if (EnableSyncChar())
     {
         SyncCharacters();
     }
     return succ;
 }
References cSceneSimChar::BuildCharacters(), EnableSyncChar(), and SyncCharacters().
BuildController()
bool cSceneImitate::BuildController (const cCtrlBuilder::tCtrlParams & ctrl_params, std::shared_ptr< cCharController > & out_ctrl) protected virtual
Reimplemented from cSceneSimChar.
Definition at line 254 of file SceneImitate.cpp.
 {
     bool succ = cSceneSimChar::BuildController(ctrl_params, out_ctrl);
     if (succ)
     {
         auto ct_ctrl = dynamic_cast<cCtController*>(out_ctrl.get());
         if (ct_ctrl != nullptr)
         {
             const auto& kin_char = GetKinChar();
             double cycle_dur = kin_char->GetMotionDuration();
             ct_ctrl->SetCyclePeriod(cycle_dur);
         }
     }
     return succ;
 }
References cSceneSimChar::BuildController(), and GetKinChar().
BuildKinChar()
void cSceneImitate::BuildKinChar () protected virtual
Definition at line 270 of file SceneImitate.cpp.
 {
     bool succ = BuildKinCharacter(0, mKinChar);
     if (!succ)
     {
         printf("Failed to build kin character\n");
         assert(false);
     }
 }
References BuildKinCharacter(), and mKinChar.
Referenced by Init().
BuildKinCharacter()
bool cSceneImitate::BuildKinCharacter (int id, std::shared_ptr< cKinCharacter > & out_char) const protected virtual
Definition at line 280 of file SceneImitate.cpp.
 {
     auto kin_char = std::shared_ptr<cKinCharacter>(new cKinCharacter());
     const cSimCharacter::tParams& sim_char_params = mCharParams[0];
     cKinCharacter::tParams kin_char_params;
     kin_char_params.mID = id;
     kin_char_params.mCharFile = sim_char_params.mCharFile;
     kin_char_params.mOrigin = sim_char_params.mInitPos;
     kin_char_params.mLoadDrawShapes = false;
     kin_char_params.mMotionFile = mMotionFile;
     bool succ = kin_char->Init(kin_char_params);
     if (succ)
     {
         out_char = kin_char;
     }
     return succ;
 }
References cKinCharacter::tParams::mCharFile, cSimCharacter::tParams::mCharFile, cSceneSimChar::mCharParams, cKinCharacter::tParams::mID, cSimCharacter::tParams::mInitPos, cKinCharacter::tParams::mLoadDrawShapes, cKinCharacter::tParams::mMotionFile, mMotionFile, and cKinCharacter::tParams::mOrigin.
Referenced by BuildKinChar().
CalcJointWeights()
void cSceneImitate::CalcJointWeights (const std::shared_ptr< cSimCharacter > & character, Eigen::VectorXd & out_weights) const protected virtual
Definition at line 240 of file SceneImitate.cpp.
 {
     int num_joints = character->GetNumJoints();
     out_weights = Eigen::VectorXd::Ones(num_joints);
     for (int j = 0; j < num_joints; ++j)
     {
         double curr_w = character->GetJointDiffWeight(j);
         out_weights[j] = curr_w;
     }
     double sum = out_weights.lpNorm<1>();
     out_weights /= sum;
 }
Referenced by InitJointWeights().
CalcRandKinResetTime()
double cSceneImitate::CalcRandKinResetTime () protected virtual
Definition at line 494 of file SceneImitate.cpp.
 {
     const auto& kin_char = GetKinChar();
     double dur = kin_char->GetMotionDuration();
     double rand_time = cMathUtil::RandDouble(0, dur);
     return rand_time;
 }
References GetKinChar(), and cMathUtil::RandDouble().
Referenced by ResetKinChar().
CalcReward()
double cSceneImitate::CalcReward (int agent_id) const virtual
Implements cRLSceneSimChar.
Definition at line 170 of file SceneImitate.cpp.
 {
     const cSimCharacter* sim_char = GetAgentChar(agent_id);
     bool fallen = HasFallen(*sim_char);
     double r = 0;
     int max_id = 0;
     if (!fallen)
     {
         r = CalcRewardImitate(*sim_char, *mKinChar);
     }
     return r;
 }
References CalcRewardImitate(), cRLSceneSimChar::GetAgentChar(), HasFallen(), and mKinChar.
CalcRewardImitate()
double cSceneImitate::CalcRewardImitate (const cSimCharacter & sim_char, const cKinCharacter & ref_char) const protected virtual
Definition at line 7 of file SceneImitate.cpp.
 {
     double pose_w = 0.5;
     double vel_w = 0.05;
     double end_eff_w = 0.15;
     double root_w = 0.2;
     double com_w = 0.1;
     double total_w = pose_w + vel_w + end_eff_w + root_w + com_w;
     pose_w /= total_w;
     vel_w /= total_w;
     end_eff_w /= total_w;
     root_w /= total_w;
     com_w /= total_w;
     const double pose_scale = 2;
     const double vel_scale = 0.1;
     const double end_eff_scale = 40;
     const double root_scale = 5;
     const double com_scale = 10;
     const double err_scale = 1;
     const auto& joint_mat = sim_char.GetJointMat();
     const auto& body_defs = sim_char.GetBodyDefs();
     double reward = 0;
     const Eigen::VectorXd& pose0 = sim_char.GetPose();
     const Eigen::VectorXd& vel0 = sim_char.GetVel();
     const Eigen::VectorXd& pose1 = kin_char.GetPose();
     const Eigen::VectorXd& vel1 = kin_char.GetVel();
     tMatrix origin_trans = sim_char.BuildOriginTrans();
     tMatrix kin_origin_trans = kin_char.BuildOriginTrans();
     tVector com0_world = sim_char.CalcCOM();
     tVector com_vel0_world = sim_char.CalcCOMVel();
     tVector com1_world;
     tVector com_vel1_world;
     cRBDUtil::CalcCoM(joint_mat, body_defs, pose1, vel1, com1_world, com_vel1_world);
     int root_id = sim_char.GetRootID();
     tVector root_pos0 = cKinTree::GetRootPos(joint_mat, pose0);
     tVector root_pos1 = cKinTree::GetRootPos(joint_mat, pose1);
     tQuaternion root_rot0 = cKinTree::GetRootRot(joint_mat, pose0);
     tQuaternion root_rot1 = cKinTree::GetRootRot(joint_mat, pose1);
     tVector root_vel0 = cKinTree::GetRootVel(joint_mat, vel0);
     tVector root_vel1 = cKinTree::GetRootVel(joint_mat, vel1);
     tVector root_ang_vel0 = cKinTree::GetRootAngVel(joint_mat, vel0);
     tVector root_ang_vel1 = cKinTree::GetRootAngVel(joint_mat, vel1);
     double pose_err = 0;
     double vel_err = 0;
     double end_eff_err = 0;
     double root_err = 0;
     double com_err = 0;
     double heading_err = 0;
     int num_end_effs = 0;
     int num_joints = sim_char.GetNumJoints();
     assert(num_joints == mJointWeights.size());
     double root_rot_w = mJointWeights[root_id];
     pose_err += root_rot_w * cKinTree::CalcRootRotErr(joint_mat, pose0, pose1);
     vel_err += root_rot_w * cKinTree::CalcRootAngVelErr(joint_mat, vel0, vel1);
     for (int j = root_id + 1; j < num_joints; ++j)
     {
         double w = mJointWeights[j];
         double curr_pose_err = cKinTree::CalcPoseErr(joint_mat, j, pose0, pose1);
         double curr_vel_err = cKinTree::CalcVelErr(joint_mat, j, vel0, vel1);
         pose_err += w * curr_pose_err;
         vel_err += w * curr_vel_err;
         bool is_end_eff = sim_char.IsEndEffector(j);
         if (is_end_eff)
         {
             tVector pos0 = sim_char.CalcJointPos(j);
             tVector pos1 = cKinTree::CalcJointWorldPos(joint_mat, pose1, j);
             double ground_h0 = mGround->SampleHeight(pos0);
             double ground_h1 = kin_char.GetOriginPos()[1];
             tVector pos_rel0 = pos0 - root_pos0;
             tVector pos_rel1 = pos1 - root_pos1;
             pos_rel0[1] = pos0[1] - ground_h0;
             pos_rel1[1] = pos1[1] - ground_h1;
             pos_rel0 = origin_trans * pos_rel0;
             pos_rel1 = kin_origin_trans * pos_rel1;
             double curr_end_err = (pos_rel1 - pos_rel0).squaredNorm();
             end_eff_err += curr_end_err;
             ++num_end_effs;
         }
     }
     if (num_end_effs > 0)
     {
         end_eff_err /= num_end_effs;
     }
     double root_ground_h0 = mGround->SampleHeight(sim_char.GetRootPos());
     double root_ground_h1 = kin_char.GetOriginPos()[1];
     root_pos0[1] -= root_ground_h0;
     root_pos1[1] -= root_ground_h1;
     double root_pos_err = (root_pos0 - root_pos1).squaredNorm();
     double root_rot_err = cMathUtil::QuatDiffTheta(root_rot0, root_rot1);
     root_rot_err *= root_rot_err;
     double root_vel_err = (root_vel1 - root_vel0).squaredNorm();
     double root_ang_vel_err = (root_ang_vel1 - root_ang_vel0).squaredNorm();
     root_err = root_pos_err
             + 0.1 * root_rot_err
             + 0.01 * root_vel_err
             + 0.001 * root_ang_vel_err;
     com_err = 0.1 * (com_vel1_world - com_vel0_world).squaredNorm();
     double pose_reward = exp(-err_scale * pose_scale * pose_err);
     double vel_reward = exp(-err_scale * vel_scale * vel_err);
     double end_eff_reward = exp(-err_scale * end_eff_scale * end_eff_err);
     double root_reward = exp(-err_scale * root_scale * root_err);
     double com_reward = exp(-err_scale * com_scale * com_err);
     reward = pose_w * pose_reward + vel_w * vel_reward + end_eff_w * end_eff_reward
         + root_w * root_reward + com_w * com_reward;
     return reward;
 }
References cCharacter::BuildOriginTrans(), cRBDUtil::CalcCoM(), cSimCharacter::CalcCOM(), cSimCharacter::CalcCOMVel(), cSimCharacter::CalcJointPos(), cKinTree::CalcJointWorldPos(), cKinTree::CalcPoseErr(), cKinTree::CalcRootAngVelErr(), cKinTree::CalcRootRotErr(), cKinTree::CalcVelErr(), cSimCharacter::GetBodyDefs(), cCharacter::GetJointMat(), cCharacter::GetNumJoints(), cKinCharacter::GetOriginPos(), cCharacter::GetPose(), cKinTree::GetRootAngVel(), cCharacter::GetRootID(), cSimCharacter::GetRootPos(), cKinTree::GetRootPos(), cKinTree::GetRootRot(), cKinTree::GetRootVel(), cCharacter::GetVel(), cCharacter::IsEndEffector(), cSceneSimChar::mGround, mJointWeights, and cMathUtil::QuatDiffTheta().
Referenced by CalcReward().
CheckKinNewCycle()
bool cSceneImitate::CheckKinNewCycle (double timestep) const protected virtual
Definition at line 452 of file SceneImitate.cpp.
 {
     bool new_cycle = false;
     const auto& kin_char = GetKinChar();
     if (kin_char->GetMotion().EnableLoop())
     {
         double cycle_dur = kin_char->GetMotionDuration();
         double time = GetKinTime();
         new_cycle = cMathUtil::CheckNextInterval(timestep, time, cycle_dur);
     }
     return new_cycle;
 }
References cMathUtil::CheckNextInterval(), GetKinChar(), and GetKinTime().
CheckRootRotFail() [1/2]
bool cSceneImitate::CheckRootRotFail (const cSimCharacter & sim_char) const protected virtual
Definition at line 477 of file SceneImitate.cpp.
 {
     const auto& kin_char = GetKinChar();
     bool fail = CheckRootRotFail(sim_char, *kin_char);
     return fail;
 }
References GetKinChar().
Referenced by HasFallen().
CheckRootRotFail() [2/2]
bool cSceneImitate::CheckRootRotFail (const cSimCharacter & sim_char, const cKinCharacter & kin_char) const protected virtual
Definition at line 484 of file SceneImitate.cpp.
 {
     const double threshold = 0.5 * M_PI;
     tQuaternion sim_rot = sim_char.GetRootRotation();
     tQuaternion kin_rot = kin_char.GetRootRotation();
     double rot_diff = cMathUtil::QuatDiffTheta(sim_rot, kin_rot);
     return rot_diff > threshold;
 }
References cCharacter::GetRootRotation(), cSimCharacter::GetRootRotation(), and cMathUtil::QuatDiffTheta().
CheckTerminate()
cSceneImitate::eTerminate cSceneImitate::CheckTerminate (int agent_id) const virtual
Reimplemented from cRLSceneSimChar.
Definition at line 200 of file SceneImitate.cpp.
 {
     eTerminate terminated = cRLSceneSimChar::CheckTerminate(agent_id);
     if (terminated == eTerminateNull)
     {
         bool end_motion = false;
         const auto& kin_char = GetKinChar();
         const cMotion& motion = kin_char->GetMotion();
         if (motion.GetLoop() == cMotion::eLoopNone)
         {
             double dur = motion.GetDuration();
             double kin_time = kin_char->GetTime();
             end_motion = kin_time > dur + mHoldEndFrame;
         }
         else
         {
             end_motion = kin_char->IsMotionOver();
         }
         terminated = (end_motion) ? eTerminateFail : terminated;
     }
     return terminated;
 }
References cRLSceneSimChar::CheckTerminate(), cMotion::eLoopNone, cRLScene::eTerminateFail, cRLScene::eTerminateNull, cMotion::GetDuration(), GetKinChar(), cMotion::GetLoop(), and mHoldEndFrame.
EnabledRandRotReset()
bool cSceneImitate::EnabledRandRotReset () const virtual
Definition at line 194 of file SceneImitate.cpp.
 {
     bool enable = mEnableRandRotReset;
     return enable;
 }
References mEnableRandRotReset.
Referenced by ResetKinChar().
EnableRandRotReset()
void cSceneImitate::EnableRandRotReset (bool enable) virtual
Definition at line 189 of file SceneImitate.cpp.
 {
     mEnableRandRotReset = enable;
 }
References mEnableRandRotReset.
EnableSyncChar()
bool cSceneImitate::EnableSyncChar () const protected virtual
Definition at line 370 of file SceneImitate.cpp.
 {
     const auto& kin_char = GetKinChar();
     return kin_char->HasMotion();
 }
References GetKinChar().
Referenced by BuildCharacters(), ResetCharacters(), and ResolveCharGroundIntersect().
GetKinChar()
const std::shared_ptr< cKinCharacter > & cSceneImitate::GetKinChar () const virtual
Definition at line 184 of file SceneImitate.cpp.
 {
     return mKinChar;
 }
References mKinChar.
Referenced by BuildController(), CalcRandKinResetTime(), CheckKinNewCycle(), CheckRootRotFail(), CheckTerminate(), EnableSyncChar(), cDrawSceneImitate::GetKinChar(), GetKinTime(), ResetKinChar(), SyncCharacters(), SyncKinCharRoot(), and UpdateKinChar().
GetKinTime()
double cSceneImitate::GetKinTime () const protected virtual
Definition at line 446 of file SceneImitate.cpp.
 {
     const auto& kin_char = GetKinChar();
     return kin_char->GetTime();
 }
References GetKinChar().
Referenced by CheckKinNewCycle(), and SyncCharacters().
GetName()
std::string cSceneImitate::GetName () const virtual
Reimplemented from cRLSceneSimChar.
Definition at line 225 of file SceneImitate.cpp.
 {
     return "Imitate";
 }
HasFallen()
bool cSceneImitate::HasFallen (const cSimCharacter & sim_char) const protected virtual
Reimplemented from cSceneSimChar.
Definition at line 466 of file SceneImitate.cpp.
 {
     bool fallen = cRLSceneSimChar::HasFallen(sim_char);
     if (mEnableRootRotFail)
     {
         fallen |= CheckRootRotFail(sim_char);
     }
     return fallen;
 }
References CheckRootRotFail(), cSceneSimChar::HasFallen(), and mEnableRootRotFail.
Referenced by CalcReward().
Init()
void cSceneImitate::Init () virtual
Reimplemented from cRLSceneSimChar.
Definition at line 161 of file SceneImitate.cpp.
 {
     mKinChar.reset();
     BuildKinChar();
     cRLSceneSimChar::Init();
     InitJointWeights();
 }
References BuildKinChar(), cRLSceneSimChar::Init(), InitJointWeights(), and mKinChar.
InitCharacterPosFixed()
void cSceneImitate::InitCharacterPosFixed (const std::shared_ptr< cSimCharacter > & out_char) protected virtual
Reimplemented from cSceneSimChar.
Definition at line 376 of file SceneImitate.cpp.
 {
     // nothing to see here
 }
InitJointWeights()
void cSceneImitate::InitJointWeights () protected virtual
Definition at line 381 of file SceneImitate.cpp.
 {
     CalcJointWeights(GetCharacter(), mJointWeights);
 }
References CalcJointWeights(), cSceneSimChar::GetCharacter(), and mJointWeights.
Referenced by Init().
ParseArgs()
void cSceneImitate::ParseArgs (const std::shared_ptr< cArgParser > & parser) virtual
Reimplemented from cRLSceneSimChar.
Definition at line 150 of file SceneImitate.cpp.
 {
     cRLSceneSimChar::ParseArgs(parser);
     parser->ParseString("motion_file", mMotionFile);
     parser->ParseBool("enable_rand_rot_reset", mEnableRandRotReset);
     parser->ParseBool("sync_char_root_pos", mSyncCharRootPos);
     parser->ParseBool("sync_char_root_rot", mSyncCharRootRot);
     parser->ParseBool("enable_root_rot_fail", mEnableRootRotFail);
     parser->ParseDouble("hold_end_frame", mHoldEndFrame);
 }
References mEnableRandRotReset, mEnableRootRotFail, mHoldEndFrame, mMotionFile, mSyncCharRootPos, mSyncCharRootRot, and cRLSceneSimChar::ParseArgs().
ResetCharacters()
void cSceneImitate::ResetCharacters () protected virtual
Reimplemented from cSceneSimChar.
Definition at line 320 of file SceneImitate.cpp.
 {
     cRLSceneSimChar::ResetCharacters();
     ResetKinChar();
     if (EnableSyncChar())
     {
         SyncCharacters();
     }
 }
References EnableSyncChar(), cSceneSimChar::ResetCharacters(), ResetKinChar(), and SyncCharacters().
ResetKinChar()
void cSceneImitate::ResetKinChar () protected virtual
Definition at line 331 of file SceneImitate.cpp.
 {
     double rand_time = CalcRandKinResetTime();
     const cSimCharacter::tParams& char_params = mCharParams[0];
     const auto& kin_char = GetKinChar();
     kin_char->Reset();
     kin_char->SetOriginRot(tQuaternion::Identity());
     kin_char->SetOriginPos(char_params.mInitPos); // reset origin
     kin_char->SetTime(rand_time);
     kin_char->Pose(rand_time);
     if (EnabledRandRotReset())
     {
         double rand_theta = mRand.RandDouble(-M_PI, M_PI);
         kin_char->RotateOrigin(cMathUtil::EulerToQuaternion(tVector(0, rand_theta, 0, 0)));
     }
 }
References CalcRandKinResetTime(), EnabledRandRotReset(), cMathUtil::EulerToQuaternion(), GetKinChar(), cSceneSimChar::mCharParams, cSimCharacter::tParams::mInitPos, cScene::mRand, and cRand::RandDouble().
Referenced by ResetCharacters().
ResolveCharGroundIntersect() [1/2]
void cSceneImitate::ResolveCharGroundIntersect () protected virtual
Reimplemented from cSceneSimChar.
Definition at line 386 of file SceneImitate.cpp.
 {
     cRLSceneSimChar::ResolveCharGroundIntersect();
     if (EnableSyncChar())
     {
         SyncKinCharRoot();
     }
 }
References EnableSyncChar(), cSceneSimChar::ResolveCharGroundIntersect(), and SyncKinCharRoot().
ResolveCharGroundIntersect() [2/2]
void cSceneImitate::ResolveCharGroundIntersect (const std::shared_ptr< cSimCharacter > & out_char) const protected virtual
Reimplemented from cSceneSimChar.
Definition at line 396 of file SceneImitate.cpp.
 {
     cRLSceneSimChar::ResolveCharGroundIntersect(out_char);
 }
References cSceneSimChar::ResolveCharGroundIntersect().
SyncCharacters()
void cSceneImitate::SyncCharacters () protected virtual
Definition at line 351 of file SceneImitate.cpp.
 {
     const auto& kin_char = GetKinChar();
     const Eigen::VectorXd& pose = kin_char->GetPose();
     const Eigen::VectorXd& vel = kin_char->GetVel();
     const auto& sim_char = GetCharacter();
     sim_char->SetPose(pose);
     sim_char->SetVel(vel);
     const auto& ctrl = sim_char->GetController();
     auto ct_ctrl = dynamic_cast<cCtController*>(ctrl.get());
     if (ct_ctrl != nullptr)
     {
         double kin_time = GetKinTime();
         ct_ctrl->SetInitTime(kin_time);
     }
 }
References cSceneSimChar::GetCharacter(), GetKinChar(), and GetKinTime().
Referenced by BuildCharacters(), and ResetCharacters().
SyncKinCharNewCycle()
void cSceneImitate::SyncKinCharNewCycle (const cSimCharacter & sim_char, cKinCharacter & out_kin_char) const protected virtual
Definition at line 420 of file SceneImitate.cpp.
 {
     if (mSyncCharRootRot)
     {
         double sim_heading = sim_char.CalcHeading();
         double kin_heading = out_kin_char.CalcHeading();
         tQuaternion drot = cMathUtil::AxisAngleToQuaternion(tVector(0, 1, 0, 0), sim_heading - kin_heading);
         out_kin_char.RotateRoot(drot);
     }
     if (mSyncCharRootPos)
     {
         tVector sim_root_pos = sim_char.GetRootPos();
         tVector kin_root_pos = out_kin_char.GetRootPos();
         kin_root_pos[0] = sim_root_pos[0];
         kin_root_pos[2] = sim_root_pos[2];
         tVector origin = out_kin_char.GetOriginPos();
         double dh = kin_root_pos[1] - origin[1];
         double ground_h = mGround->SampleHeight(kin_root_pos);
         kin_root_pos[1] = ground_h + dh;
         out_kin_char.SetRootPos(kin_root_pos);
     }
 }
References cMathUtil::AxisAngleToQuaternion(), cCharacter::CalcHeading(), cKinCharacter::GetOriginPos(), cCharacter::GetRootPos(), cSimCharacter::GetRootPos(), cSceneSimChar::mGround, mSyncCharRootPos, mSyncCharRootRot, cCharacter::RotateRoot(), and cKinCharacter::SetRootPos().
Referenced by UpdateKinChar().
SyncKinCharRoot()
void cSceneImitate::SyncKinCharRoot () protected virtual
Definition at line 401 of file SceneImitate.cpp.
 {
     const auto& sim_char = GetCharacter();
     tVector sim_root_pos = sim_char->GetRootPos();
     double sim_heading = sim_char->CalcHeading();
     const auto& kin_char = GetKinChar();
     double kin_heading = kin_char->CalcHeading();
     tQuaternion drot = tQuaternion::Identity();
     if (mSyncCharRootRot)
     {
         drot = cMathUtil::AxisAngleToQuaternion(tVector(0, 1, 0, 0), sim_heading - kin_heading);
     }
     kin_char->RotateRoot(drot);
     kin_char->SetRootPos(sim_root_pos);
 }
References cMathUtil::AxisAngleToQuaternion(), cSceneSimChar::GetCharacter(), GetKinChar(), and mSyncCharRootRot.
Referenced by ResolveCharGroundIntersect().
UpdateCharacters()
void cSceneImitate::UpdateCharacters (double timestep) protected virtual
Reimplemented from cSceneSimChar.
Definition at line 300 of file SceneImitate.cpp.
 {
     UpdateKinChar(timestep);
     cRLSceneSimChar::UpdateCharacters(timestep);
 }
References cSceneSimChar::UpdateCharacters(), and UpdateKinChar().
UpdateKinChar()
void cSceneImitate::UpdateKinChar (double timestep) protected virtual
Definition at line 306 of file SceneImitate.cpp.
 {
     const auto& kin_char = GetKinChar();
     double prev_phase = kin_char->GetPhase();
     kin_char->Update(timestep);
     double curr_phase = kin_char->GetPhase();
     if (curr_phase < prev_phase)
     {
         const auto& sim_char = GetCharacter();
         SyncKinCharNewCycle(*sim_char, *kin_char);
     }
 }
References cSceneSimChar::GetCharacter(), GetKinChar(), and SyncKinCharNewCycle().
Referenced by UpdateCharacters().
Member Data Documentation
mEnableRandRotReset
bool cSceneImitate::mEnableRandRotReset protected
Definition at line 32 of file SceneImitate.h.
Referenced by cSceneImitate(), EnabledRandRotReset(), EnableRandRotReset(), and ParseArgs().
mEnableRootRotFail
bool cSceneImitate::mEnableRootRotFail protected
Definition at line 35 of file SceneImitate.h.
Referenced by cSceneImitate(), HasFallen(), and ParseArgs().
mHoldEndFrame
double cSceneImitate::mHoldEndFrame protected
Definition at line 36 of file SceneImitate.h.
Referenced by CheckTerminate(), cSceneImitate(), and ParseArgs().
mJointWeights
Eigen::VectorXd cSceneImitate::mJointWeights protected
Definition at line 31 of file SceneImitate.h.
Referenced by CalcRewardImitate(), and InitJointWeights().
mKinChar
std::shared_ptr<cKinCharacter> cSceneImitate::mKinChar protected
Definition at line 29 of file SceneImitate.h.
Referenced by BuildKinChar(), CalcReward(), GetKinChar(), and Init().
mMotionFile
std::string cSceneImitate::mMotionFile protected
Definition at line 28 of file SceneImitate.h.
Referenced by BuildKinCharacter(), cSceneImitate(), and ParseArgs().
mSyncCharRootPos
bool cSceneImitate::mSyncCharRootPos protected
Definition at line 33 of file SceneImitate.h.
Referenced by cSceneImitate(), ParseArgs(), and SyncKinCharNewCycle().
mSyncCharRootRot
bool cSceneImitate::mSyncCharRootRot protected
Definition at line 34 of file SceneImitate.h.
Referenced by cSceneImitate(), ParseArgs(), SyncKinCharNewCycle(), and SyncKinCharRoot().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/SceneImitate.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/SceneImitate.cpp