My Project: cController Class Reference
cController Class Reference
#include <Controller.h>
Public Types
enum eMode { eModeActive, eModeInactive, eModePassive, eModeMax }
Public Member Functions
virtual ~cController ()
virtual void Init (cSimCharacter *character)
virtual void Reset ()
virtual void Clear ()
virtual void Update (double time_step)
virtual bool IsValid () const
virtual bool LoadParams (const std::string &param_file)
virtual int GetNumOptParams () const
virtual void BuildOptParams (Eigen::VectorXd &out_params) const
virtual void SetOptParams (const Eigen::VectorXd &params)
virtual void SetOptParams (const Eigen::VectorXd &params, Eigen::VectorXd &out_params) const
virtual void FetchOptParamScale (Eigen::VectorXd &out_scale) const
virtual void OutputOptParams (const std::string &file, const Eigen::VectorXd &params) const
virtual void OutputOptParams (FILE *f, const Eigen::VectorXd &params) const
virtual void SetActive (bool active)
virtual bool IsActive () const
virtual void SetMode (eMode mode)
virtual const cSimCharacter * GetChar () const
Protected Member Functions
cController ()
virtual bool ParseParams (const Json::Value &json)
Protected Attributes
cSimCharacter * mChar
eMode mMode
bool mValid
Detailed Description
Definition at line 9 of file Controller.h.
Member Enumeration Documentation
eMode
enum cController::eMode
Enumerator
eModeActive
eModeInactive
eModePassive
eModeMax
Definition at line 12 of file Controller.h.
     {
         eModeActive,
         eModeInactive,
         eModePassive,
         eModeMax
     };
Constructor & Destructor Documentation
~cController()
cController::~cController () virtual
Definition at line 10 of file Controller.cpp.
 {
 }
cController()
cController::cController () protected
Definition at line 5 of file Controller.cpp.
 {
     mChar = nullptr;
 }
References mChar.
Member Function Documentation
BuildOptParams()
void cController::BuildOptParams (Eigen::VectorXd & out_params) const virtual
Definition at line 73 of file Controller.cpp.
 {
 }
Clear()
void cController::Clear () virtual
Reimplemented in cPDController, cImpPDController, cExpPDController, cCtPDController, and cDeepMimicCharController.
Definition at line 29 of file Controller.cpp.
 {
     mValid = false;
     mChar = nullptr;
     SetMode(eModeActive);
 }
References eModeActive, mChar, mValid, and SetMode().
Referenced by cDeepMimicCharController::Clear(), cExpPDController::Clear(), cPDController::Clear(), and Init().
FetchOptParamScale()
void cController::FetchOptParamScale (Eigen::VectorXd & out_scale) const virtual
Definition at line 86 of file Controller.cpp.
 {
 }
GetChar()
const cSimCharacter * cController::GetChar () const virtual
Definition at line 119 of file Controller.cpp.
 {
     return mChar;
 }
References mChar.
GetNumOptParams()
int cController::GetNumOptParams () const virtual
Definition at line 68 of file Controller.cpp.
 {
     return 0;
 }
Init()
void cController::Init (cSimCharacter * character) virtual
Definition at line 16 of file Controller.cpp.
 {
     assert(character != nullptr);
     Clear();
     mChar = character;
 }
References Clear(), and mChar.
Referenced by cDeepMimicCharController::Init(), cExpPDController::Init(), and cPDController::Init().
IsActive()
bool cController::IsActive () const virtual
Reimplemented in cPDController.
Definition at line 109 of file Controller.cpp.
 {
     return mMode != eModeInactive;
 }
References eModeInactive, and mMode.
Referenced by cPDController::IsActive().
IsValid()
bool cController::IsValid () const virtual
Definition at line 41 of file Controller.cpp.
 {
     return mValid;
 }
References mValid.
Referenced by cImpPDController::BuildTargetPose(), cImpPDController::BuildTargetVel(), cExpPDController::CalcControlForces(), cImpPDController::CalcControlForces(), cImpPDController::InitGains(), and cExpPDController::IsValidPDCtrl().
LoadParams()
bool cController::LoadParams (const std::string & param_file) virtual
Definition at line 46 of file Controller.cpp.
 {
     std::ifstream f_stream(param_file);
     Json::Reader reader;
     Json::Value root;
     bool succ = reader.parse(f_stream, root);
     f_stream.close();
     if (succ)
     {
         succ &= ParseParams(root);
     }
     if (!succ)
     {
         printf("Failed to load params from %s\n", param_file.c_str());
         assert(false);
     }
     return succ;
 }
References Json::Reader::parse(), and ParseParams().
Referenced by cDeepMimicCharController::Init().
OutputOptParams() [1/2]
void cController::OutputOptParams (const std::string & file, const Eigen::VectorXd & params) const virtual
Definition at line 90 of file Controller.cpp.
 {
     FILE* f = cFileUtil::OpenFile(file, "w");
     if (f != nullptr)
     {
         OutputOptParams(f, params);
         cFileUtil::CloseFile(f);
     }
 }
References cFileUtil::CloseFile(), and cFileUtil::OpenFile().
OutputOptParams() [2/2]
void cController::OutputOptParams (FILE * f, const Eigen::VectorXd & params) const virtual
Definition at line 100 of file Controller.cpp.
 {
 }
ParseParams()
bool cController::ParseParams (const Json::Value & json) protected virtual
Reimplemented in cDeepMimicCharController, cCtController, and cCtPDController.
Definition at line 124 of file Controller.cpp.
 {
     return true;
 }
Referenced by LoadParams(), and cDeepMimicCharController::ParseParams().
Reset()
void cController::Reset () virtual
Reimplemented in cExpPDController, cCtPDController, and cDeepMimicCharController.
Definition at line 23 of file Controller.cpp.
 {
     SetMode(eModeActive);
 }
References eModeActive, and SetMode().
Referenced by cDeepMimicCharController::Reset(), and cExpPDController::Reset().
SetActive()
void cController::SetActive (bool active) virtual
Definition at line 104 of file Controller.cpp.
 {
     SetMode((active) ? eModeActive : eModeInactive);
 }
References eModeActive, eModeInactive, and SetMode().
SetMode()
void cController::SetMode (eMode mode) virtual
Definition at line 114 of file Controller.cpp.
 {
     mMode = mode;
 }
References mMode.
Referenced by Clear(), Reset(), and SetActive().
SetOptParams() [1/2]
void cController::SetOptParams (const Eigen::VectorXd & params) virtual
Definition at line 77 of file Controller.cpp.
 {
 }
SetOptParams() [2/2]
void cController::SetOptParams (const Eigen::VectorXd & params, Eigen::VectorXd & out_params) const virtual
Definition at line 81 of file Controller.cpp.
 {
     out_params = params;
 }
Update()
void cController::Update (double time_step) virtual
Reimplemented in cDeepMimicCharController, cPDController, cCharController, and cExpPDController.
Definition at line 36 of file Controller.cpp.
 {
     // *whistle whistle*....nothing to see here
 }
Referenced by cCharController::Update(), cExpPDController::UpdateControlForce(), cImpPDController::UpdateControlForce(), and cPDController::UpdateControlForce().
Member Data Documentation
mChar
cSimCharacter* cController::mChar protected
Definition at line 45 of file Controller.h.
Referenced by cCtVelController::ApplyAction(), cExpPDController::ApplyControlForces(), cPDController::ApplyControlForces(), cCtController::BuildActionBounds(), cCtController::BuildActionOffsetScale(), cCtVelController::BuildJointActionBounds(), cCtPDController::BuildJointActionBounds(), cCtController::BuildJointActionBounds(), cCtVelController::BuildJointActionOffsetScale(), cCtPDController::BuildJointActionOffsetScale(), cCtController::BuildJointActionOffsetScale(), cCtController::BuildStatePose(), cDeepMimicCharController::BuildStatePose(), cCtController::BuildStateVel(), cDeepMimicCharController::BuildStateVel(), cImpPDController::BuildTargetPose(), cImpPDController::BuildTargetVel(), cImpPDController::CalcControlForces(), cController(), Clear(), cCtController::GetActionCtrlSize(), GetChar(), cPDController::GetJoint(), cPDController::GetJointDim(), cExpPDController::GetNumDof(), cExpPDController::GetNumJoints(), cCtController::GetStatePoseSize(), cDeepMimicCharController::GetStatePoseSize(), cCtController::GetStateVelSize(), cDeepMimicCharController::GetStateVelSize(), cDeepMimicCharController::GetViewBound(), cDeepMimicCharController::HandleNewAction(), cExpPDController::Init(), Init(), cImpPDController::InitGains(), cDeepMimicCharController::InitTau(), cImpPDController::SetKd(), cImpPDController::SetKp(), cCtPDController::SetPDTargets(), cCtPDController::SetupPDControllers(), cPDController::Update(), cDeepMimicCharController::UpdateApplyTau(), cCtController::UpdateBuildTau(), cPDController::UpdateControlForce(), cCtPDController::UpdatePDCtrls(), and cImpPDController::UpdateRBDModel().
mMode
eMode cController::mMode protected
Definition at line 46 of file Controller.h.
Referenced by IsActive(), and SetMode().
mValid
bool cController::mValid protected
Definition at line 47 of file Controller.h.
Referenced by Clear(), cDeepMimicCharController::Init(), cExpPDController::Init(), cPDController::Init(), IsValid(), and cCtPDController::SetupPDControllers().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/Controller.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/Controller.cpp