My Project: cArgParser Class Reference
cArgParser Class Reference
#include <ArgParser.h>
Public Member Functions
cArgParser ()
cArgParser (const std::vector< std::string > &args)
cArgParser (const std::string &file)
virtual ~cArgParser ()
virtual void Clear ()
virtual void LoadArgs (const std::vector< std::string > &arg_strs)
virtual bool LoadFile (const std::string &file)
virtual int GetNumArgs () const
virtual bool ParseString (const std::string &key, std::string &out) const
virtual bool ParseStrings (const std::string &key, std::vector< std::string > &out) const
virtual bool ParseInt (const std::string &key, int &out) const
virtual bool ParseInts (const std::string &key, std::vector< int > &out) const
virtual bool ParseDouble (const std::string &key, double &out) const
virtual bool ParseDoubles (const std::string &key, std::vector< double > &out) const
virtual bool ParseBool (const std::string &key, bool &out) const
virtual bool ParseBools (const std::string &key, std::vector< bool > &out) const
virtual bool ParseVector (const std::string &key, tVector &out) const
Protected Member Functions
virtual bool IsComment (const std::string &str) const
virtual bool IsKey (const std::string &str) const
virtual bool ParseBool (const std::string &str) const
Protected Attributes
std::map< std::string, std::vector< std::string > > mTable
Detailed Description
Definition at line 8 of file ArgParser.h.
Constructor & Destructor Documentation
cArgParser() [1/3]
cArgParser::cArgParser ()
Definition at line 13 of file ArgParser.cpp.
 {
 }
cArgParser() [2/3]
cArgParser::cArgParser (const std::vector< std::string > & args)
Definition at line 21 of file ArgParser.cpp.
 {
     LoadArgs(args);
 }
References LoadArgs().
cArgParser() [3/3]
cArgParser::cArgParser (const std::string & file)
Definition at line 26 of file ArgParser.cpp.
 {
     LoadFile(file);
 }
References LoadFile().
~cArgParser()
cArgParser::~cArgParser () virtual
Definition at line 17 of file ArgParser.cpp.
 {
 }
Member Function Documentation
Clear()
void cArgParser::Clear () virtual
Definition at line 75 of file ArgParser.cpp.
 {
     mTable.clear();
 }
References mTable.
GetNumArgs()
int cArgParser::GetNumArgs () const virtual
Definition at line 285 of file ArgParser.cpp.
 {
     return static_cast<int>(mTable.size());
 }
References mTable.
IsComment()
bool cArgParser::IsComment (const std::string & str) const protected virtual
Definition at line 258 of file ArgParser.cpp.
 {
     bool is_comment = false;
     if (str.size() > 0)
     {
         is_comment = str[0] == gCommentStart;
     }
     return is_comment;
 }
References gCommentStart.
Referenced by LoadArgs(), and LoadFile().
IsKey()
bool cArgParser::IsKey (const std::string & str) const protected virtual
Definition at line 268 of file ArgParser.cpp.
 {
     size_t len = str.size();
     if (len < 3)
     {
         return false;
     }
     else
     {
         if (str[0] == gKeyStart && str[1] == gKeyStart)
         {
             return true;
         }
     }
     return false;
 }
References gKeyStart.
Referenced by LoadArgs().
LoadArgs()
void cArgParser::LoadArgs (const std::vector< std::string > & arg_strs) virtual
Definition at line 31 of file ArgParser.cpp.
 {
     std::vector<std::string> vals;
     std::string curr_key = "";
     for (size_t i = 0; i < arg_strs.size(); ++i)
     {
         const std::string& str = arg_strs[i];
         if (!IsComment(str))
         {
             bool is_key = IsKey(str);
             if (is_key)
             {
                 if (curr_key != "")
                 {
                     bool in_table = mTable.find(curr_key) != mTable.end();
                     if (!in_table)
                     {
                         mTable[curr_key] = vals;
                         curr_key = "";
                     }
                 }
                 vals.clear();
                 curr_key = str.substr(2, str.size());
             }
             else
             {
                 vals.push_back(str);
             }
         }
     }
     if (curr_key != "")
     {
         bool in_table = mTable.find(curr_key) != mTable.end();
         if (!in_table)
         {
             mTable[curr_key] = vals;
         }
         curr_key = "";
     }
     vals.clear();
 }
References IsComment(), IsKey(), and mTable.
Referenced by cArgParser(), and LoadFile().
LoadFile()
bool cArgParser::LoadFile (const std::string & file) virtual
Definition at line 80 of file ArgParser.cpp.
 {
     FILE* file_ptr = cFileUtil::OpenFile(file.c_str(), "r");
     bool succ = (file_ptr != nullptr);
     std::ifstream file_stream(file.c_str());
     std::string line_str;
     std::string str_buffer = "";
     std::vector<std::string> arg_strs;
     const std::string delims = " \t\n\r,";
     while (std::getline(file_stream, line_str))
     {
         if (line_str.size() > 0 && !IsComment(line_str))
         {
             for (size_t i = 0; i < line_str.size(); ++i)
             {
                 char curr_char = line_str[i];
                 if (delims.find_first_of(curr_char) != std::string::npos)
                 {
                     if (str_buffer != "")
                     {
                         arg_strs.push_back(str_buffer);
                         str_buffer = "";
                     }
                 }
                 else
                 {
                     str_buffer += curr_char;
                 }
             }
             // dump everything else out
             if (str_buffer != "")
             {
                 arg_strs.push_back(str_buffer);
                 str_buffer = "";
             }
         }
     }
     cFileUtil::CloseFile(file_ptr);
     LoadArgs(arg_strs);
     return succ;
 }
References cFileUtil::CloseFile(), IsComment(), LoadArgs(), and cFileUtil::OpenFile().
Referenced by cArgParser().
ParseBool() [1/2]
bool cArgParser::ParseBool (const std::string & key, bool & out) const virtual
Definition at line 212 of file ArgParser.cpp.
 {
     auto it = mTable.find(key);
     if (it != mTable.end())
     {
         const auto& vals = it->second;
         out = ParseBool(vals[0]);
         return true;
     }
     return false;
 }
References mTable.
Referenced by ParseBools().
ParseBool() [2/2]
bool cArgParser::ParseBool (const std::string & str) const protected virtual
Definition at line 290 of file ArgParser.cpp.
 {
     bool val = false;
     if (str == "true" || str == "1"
         || str == "True" || str == "T"
         || str == "t")
     {
         val = true;
     }
     return val;
 }
ParseBools()
bool cArgParser::ParseBools (const std::string & key, std::vector< bool > & out) const virtual
Definition at line 224 of file ArgParser.cpp.
 {
     auto it = mTable.find(key);
     if (it != mTable.end())
     {
         const auto& vals = it->second;
         size_t num_vals = vals.size();
         out.clear();
         out.reserve(num_vals);
         for (int i = 0; i < num_vals; ++i)
         {
             out.push_back(ParseBool(vals[i]));
         }
         return true;
     }
     return false;
 }
References mTable, and ParseBool().
ParseDouble()
bool cArgParser::ParseDouble (const std::string & key, double & out) const virtual
Definition at line 182 of file ArgParser.cpp.
 {
     auto it = mTable.find(key);
     if (it != mTable.end())
     {
         const auto& vals = it->second;
         out = std::atof(vals[0].c_str());
         return true;
     }
     return false;
 }
References mTable.
ParseDoubles()
bool cArgParser::ParseDoubles (const std::string & key, std::vector< double > & out) const virtual
Definition at line 194 of file ArgParser.cpp.
 {
     auto it = mTable.find(key);
     if (it != mTable.end())
     {
         const auto& vals = it->second;
         size_t num_vals = vals.size();
         out.clear();
         out.reserve(num_vals);
         for (int i = 0; i < num_vals; ++i)
         {
             out.push_back(std::atof(vals[i].c_str()));
         }
         return true;
     }
     return false;
 }
References mTable.
ParseInt()
bool cArgParser::ParseInt (const std::string & key, int & out) const virtual
Definition at line 152 of file ArgParser.cpp.
 {
     auto it = mTable.find(key);
     if (it != mTable.end())
     {
         const auto& vals = it->second;
         out = std::atoi(vals[0].c_str());
         return true;
     }
     return false;
 }
References mTable.
ParseInts()
bool cArgParser::ParseInts (const std::string & key, std::vector< int > & out) const virtual
Definition at line 164 of file ArgParser.cpp.
 {
     auto it = mTable.find(key);
     if (it != mTable.end())
     {
         const auto& vals = it->second;
         size_t num_vals = vals.size();
         out.clear();
         out.reserve(num_vals);
         for (int i = 0; i < num_vals; ++i)
         {
             out.push_back(std::atoi(vals[i].c_str()));
         }
         return true;
     }
     return false;
 }
References mTable.
ParseString()
bool cArgParser::ParseString (const std::string & key, std::string & out) const virtual
Definition at line 128 of file ArgParser.cpp.
 {
     auto it = mTable.find(key);
     if (it != mTable.end())
     {
         const auto& vals = it->second;
         out = vals[0];
         return true;
     }
     return false;
 }
References mTable.
ParseStrings()
bool cArgParser::ParseStrings (const std::string & key, std::vector< std::string > & out) const virtual
Definition at line 140 of file ArgParser.cpp.
 {
     auto it = mTable.find(key);
     if (it != mTable.end())
     {
         const auto& vals = it->second;
         out = vals;
         return true;
     }
     return false;
 }
References mTable.
ParseVector()
bool cArgParser::ParseVector (const std::string & key, tVector & out) const virtual
Definition at line 242 of file ArgParser.cpp.
 {
     auto it = mTable.find(key);
     if (it != mTable.end())
     {
         const auto& vals = it->second;
         size_t num_vals = std::min(vals.size(), static_cast<size_t>(out.size()));
         for (int i = 0; i < num_vals; ++i)
         {
             out[i] = std::atof(vals[i].c_str());
         }
         return true;
     }
     return false;
 }
References mTable.
Member Data Documentation
mTable
std::map<std::string, std::vector<std::string> > cArgParser::mTable protected
Definition at line 32 of file ArgParser.h.
Referenced by Clear(), GetNumArgs(), LoadArgs(), ParseBool(), ParseBools(), ParseDouble(), ParseDoubles(), ParseInt(), ParseInts(), ParseString(), ParseStrings(), and ParseVector().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/ArgParser.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/ArgParser.cpp