My Project: cRenderState Class Reference
cRenderState Class Reference
#include <RenderState.h>
Public Member Functions
cRenderState ()
~cRenderState ()
void BindVAO ()
void BindVBO (unsigned int i, GLenum target=GL_ARRAY_BUFFER)
void BindIBO (unsigned int i)
void SetNextBufferData (std::size_t num_bytes, unsigned char *data)
void SetBufferData (unsigned int i, std::size_t num_bytes, unsigned char *data=NULL)
void SetAttributeData (tAttribInfo &info)
void SetAttributeData (unsigned int mAttribNumber, unsigned int mNumComp, unsigned int mDataOffset, unsigned int mDataStride)
GLuint operator[] (unsigned int i)
void MakeClean ()
Private Attributes
int mDirty
GLuint mVaoID
std::vector< GLuint > mVboIDs
std::vector< GLuint > mBytes
Detailed Description
A cRenderState object stores a collection of GPU vertex buffer objects to be used to render a single mesh at a time. It also stores all of the associated state setup for those buffers, such as attribute stride and offset within a vertex array object.
Definition at line 37 of file RenderState.h.
Constructor & Destructor Documentation
cRenderState()
cRenderState::cRenderState () inline
Definition at line 40 of file RenderState.h.
     {
         glGenVertexArrays(1, &mVaoID);
     }
References mVaoID.
~cRenderState()
cRenderState::~cRenderState () inline
Definition at line 44 of file RenderState.h.
     {
         glDeleteVertexArrays(1, &mVaoID);
         if (!mVboIDs.empty())
             glDeleteBuffers(static_cast<GLsizei>(mVboIDs.size()), &mVboIDs[0]);
     }
References mVaoID, and mVboIDs.
Member Function Documentation
BindIBO()
void cRenderState::BindIBO (unsigned int i) inline
Definition at line 60 of file RenderState.h.
     { BindVBO(i, GL_ELEMENT_ARRAY_BUFFER); }
References BindVBO().
Referenced by cIBuffer::SyncBuffer().
BindVAO()
void cRenderState::BindVAO () inline
Definition at line 51 of file RenderState.h.
     {
         glBindVertexArray(mVaoID);
     }
References mVaoID.
Referenced by cDrawMesh::Draw(), cDrawMesh::Init(), and cDrawMesh::SyncGPU().
BindVBO()
void cRenderState::BindVBO (unsigned int i, GLenum target = GL_ARRAY_BUFFER) inline
Definition at line 55 of file RenderState.h.
     {
         glBindBuffer(target, operator[](i));
     }
Referenced by BindIBO(), and SetBufferData().
MakeClean()
void cRenderState::MakeClean () inline
Definition at line 102 of file RenderState.h.
     { mDirty = 0; }
References mDirty.
operator[]()
GLuint cRenderState::operator[] (unsigned int i) inline
Definition at line 90 of file RenderState.h.
     {
         if (i >= mVboIDs.size())
         {
             mVboIDs.resize(i+1, 0);
             mBytes.resize(i+1, 0);
         }
         if (mVboIDs[i] == 0)
             glGenBuffers(1, &mVboIDs[i]);
         return mVboIDs[i];
     }
References mBytes, and mVboIDs.
SetAttributeData() [1/2]
void cRenderState::SetAttributeData (tAttribInfo & info) inline
Definition at line 80 of file RenderState.h.
     { SetAttributeData(info.mAttribNumber, info.mNumComp, info.mDataOffset, info.mDataStride); }
References tAttribInfo::mAttribNumber, tAttribInfo::mDataOffset, tAttribInfo::mDataStride, and tAttribInfo::mNumComp.
Referenced by cVertexBuffer::SyncBuffer().
SetAttributeData() [2/2]
void cRenderState::SetAttributeData (unsigned int mAttribNumber, unsigned int mNumComp, unsigned int mDataOffset, unsigned int mDataStride) inline
Definition at line 83 of file RenderState.h.
     {
         glEnableVertexAttribArray(mAttribNumber);
         glVertexAttribPointer(mAttribNumber, mNumComp, GL_FLOAT, GL_FALSE,
                               mDataStride, (GLvoid *) mDataOffset);
     }
SetBufferData()
void cRenderState::SetBufferData (unsigned int i, std::size_t num_bytes, unsigned char * data = NULL) inline
Definition at line 69 of file RenderState.h.
     {
         BindVBO(i);
         if (mBytes[i] < num_bytes)
         {
             mBytes[i] = static_cast<unsigned int>(num_bytes);
             glBufferData(GL_ARRAY_BUFFER, num_bytes, data, GL_STATIC_DRAW); // Static, because all changes happen in the edit mesh
         }
         else
             glBufferSubData(GL_ARRAY_BUFFER, 0, num_bytes, data);
     }
References BindVBO(), and mBytes.
Referenced by SetNextBufferData(), cIBuffer::SyncBuffer(), and cVertexBuffer::SyncBuffer().
SetNextBufferData()
void cRenderState::SetNextBufferData (std::size_t num_bytes, unsigned char * data) inline
Definition at line 64 of file RenderState.h.
     {
         SetBufferData(mDirty++, num_bytes, data);
     }
References mDirty, and SetBufferData().
Member Data Documentation
mBytes
std::vector<GLuint> cRenderState::mBytes private
Definition at line 110 of file RenderState.h.
Referenced by operator[](), and SetBufferData().
mDirty
int cRenderState::mDirty private
Definition at line 106 of file RenderState.h.
Referenced by MakeClean(), and SetNextBufferData().
mVaoID
GLuint cRenderState::mVaoID private
Definition at line 108 of file RenderState.h.
Referenced by BindVAO(), cRenderState(), and ~cRenderState().
mVboIDs
std::vector<GLuint> cRenderState::mVboIDs private
Definition at line 109 of file RenderState.h.
Referenced by operator[](), and ~cRenderState().
The documentation for this class was generated from the following file:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/RenderState.h