My Project: cMathUtil Class Reference
cMathUtil Class Reference
#include <MathUtil.h>
Public Types
enum eAxis { eAxisX, eAxisY, eAxisZ, eAxisMax }
Static Public Member Functions
static int Clamp (int val, int min, int max)
static void Clamp (const Eigen::VectorXd &min, const Eigen::VectorXd &max, Eigen::VectorXd &out_vec)
static double Clamp (double val, double min, double max)
static double Saturate (double val)
static double Lerp (double t, double val0, double val1)
static double NormalizeAngle (double theta)
static double RandDouble ()
static double RandDouble (double min, double max)
static double RandDoubleNorm (double mean, double stdev)
static double RandDoubleExp (double lambda)
static double RandDoubleSeed (double seed)
static int RandInt ()
static int RandInt (int min, int max)
static int RandUint ()
static int RandUint (unsigned int min, unsigned int max)
static int RandIntExclude (int min, int max, int exc)
static void SeedRand (unsigned long int seed)
static int RandSign ()
static bool FlipCoin (double p=0.5)
static double SmoothStep (double t)
static tMatrix TranslateMat (const tVector &trans)
static tMatrix ScaleMat (double scale)
static tMatrix ScaleMat (const tVector &scale)
static tMatrix RotateMat (const tVector &euler)
static tMatrix RotateMat (const tVector &axis, double theta)
static tMatrix RotateMat (const tQuaternion &q)
static tMatrix CrossMat (const tVector &a)
static tMatrix InvRigidMat (const tMatrix &mat)
static tVector GetRigidTrans (const tMatrix &mat)
static tVector InvEuler (const tVector &euler)
static void RotMatToAxisAngle (const tMatrix &mat, tVector &out_axis, double &out_theta)
static tVector RotMatToEuler (const tMatrix &mat)
static tQuaternion RotMatToQuaternion (const tMatrix &mat)
static void EulerToAxisAngle (const tVector &euler, tVector &out_axis, double &out_theta)
static tVector AxisAngleToEuler (const tVector &axis, double theta)
static tMatrix DirToRotMat (const tVector &dir, const tVector &up)
static void DeltaRot (const tVector &axis0, double theta0, const tVector &axis1, double theta1, tVector &out_axis, double &out_theta)
static tMatrix DeltaRot (const tMatrix &R0, const tMatrix &R1)
static tQuaternion EulerToQuaternion (const tVector &euler)
static tVector QuaternionToEuler (const tQuaternion &q)
static tQuaternion AxisAngleToQuaternion (const tVector &axis, double theta)
static void QuaternionToAxisAngle (const tQuaternion &q, tVector &out_axis, double &out_theta)
static tMatrix BuildQuaternionDiffMat (const tQuaternion &q)
static tVector CalcQuaternionVel (const tQuaternion &q0, const tQuaternion &q1, double dt)
static tVector CalcQuaternionVelRel (const tQuaternion &q0, const tQuaternion &q1, double dt)
static tQuaternion VecToQuat (const tVector &v)
static tVector QuatToVec (const tQuaternion &q)
static tQuaternion QuatDiff (const tQuaternion &q0, const tQuaternion &q1)
static double QuatDiffTheta (const tQuaternion &q0, const tQuaternion &q1)
static double QuatTheta (const tQuaternion &dq)
static tQuaternion VecDiffQuat (const tVector &v0, const tVector &v1)
static tVector QuatRotVec (const tQuaternion &q, const tVector &dir)
static tQuaternion MirrorQuaternion (const tQuaternion &q, eAxis axis)
static double Sign (double val)
static int Sign (int val)
static double AddAverage (double avg0, int count0, double avg1, int count1)
static tVector AddAverage (const tVector &avg0, int count0, const tVector &avg1, int count1)
static void AddAverage (const Eigen::VectorXd &avg0, int count0, const Eigen::VectorXd &avg1, int count1, Eigen::VectorXd &out_result)
static void CalcSoftmax (const Eigen::VectorXd &vals, double temp, Eigen::VectorXd &out_prob)
static double EvalGaussian (const Eigen::VectorXd &mean, const Eigen::VectorXd &covar, const Eigen::VectorXd &sample)
static double EvalGaussian (double mean, double covar, double sample)
static double CalcGaussianPartition (const Eigen::VectorXd &covar)
static double EvalGaussianLogp (double mean, double covar, double sample)
static double EvalGaussianLogp (const Eigen::VectorXd &mean, const Eigen::VectorXd &covar, const Eigen::VectorXd &sample)
static double Sigmoid (double x)
static double Sigmoid (double x, double gamma, double bias)
static int SampleDiscreteProb (const Eigen::VectorXd &probs)
static tVector CalcBarycentric (const tVector &p, const tVector &a, const tVector &b, const tVector &c)
static bool ContainsAABB (const tVector &pt, const tVector &aabb_min, const tVector &aabb_max)
static bool ContainsAABB (const tVector &aabb_min0, const tVector &aabb_max0, const tVector &aabb_min1, const tVector &aabb_max1)
static bool ContainsAABBXZ (const tVector &pt, const tVector &aabb_min, const tVector &aabb_max)
static bool ContainsAABBXZ (const tVector &aabb_min0, const tVector &aabb_max0, const tVector &aabb_min1, const tVector &aabb_max1)
static void CalcAABBIntersection (const tVector &aabb_min0, const tVector &aabb_max0, const tVector &aabb_min1, const tVector &aabb_max1, tVector &out_min, tVector &out_max)
static void CalcAABBUnion (const tVector &aabb_min0, const tVector &aabb_max0, const tVector &aabb_min1, const tVector &aabb_max1, tVector &out_min, tVector &out_max)
static bool IntersectAABB (const tVector &aabb_min0, const tVector &aabb_max0, const tVector &aabb_min1, const tVector &aabb_max1)
static bool IntersectAABBXZ (const tVector &aabb_min0, const tVector &aabb_max0, const tVector &aabb_min1, const tVector &aabb_max1)
static bool CheckNextInterval (double delta, double curr_val, double int_size)
static tVector SampleRandPt (const tVector &bound_min, const tVector &bound_max)
static tVector SampleRandPtBias (const tVector &bound_min, const tVector &bound_max)
static tVector SampleRandPtBias (const tVector &bound_min, const tVector &bound_max, const tVector &focus)
static void QuatSwingTwistDecomposition (const tQuaternion &q, const tVector &dir, tQuaternion &out_swing, tQuaternion &out_twist)
static tQuaternion ProjectQuat (const tQuaternion &q, const tVector &dir)
static void ButterworthFilter (double dt, double cutoff, Eigen::VectorXd &out_x)
Static Private Member Functions
template<typename T >
static T SignAux (T val)
Static Private Attributes
static cRand gRand = cRand()
Detailed Description
Definition at line 29 of file MathUtil.h.
Member Enumeration Documentation
eAxis
enum cMathUtil::eAxis
Enumerator
eAxisX
eAxisY
eAxisZ
eAxisMax
Definition at line 32 of file MathUtil.h.
     {
         eAxisX,
         eAxisY,
         eAxisZ,
         eAxisMax
     };
Member Function Documentation
AddAverage() [1/3]
void cMathUtil::AddAverage (const Eigen::VectorXd & avg0, int count0, const Eigen::VectorXd & avg1, int count1, Eigen::VectorXd & out_result) static
Definition at line 580 of file MathUtil.cpp.
 {
     double total = count0 + count1;
     out_result = (count0 / total) * avg0 + (count1 / total) * avg1;
 }
AddAverage() [2/3]
tVector cMathUtil::AddAverage (const tVector & avg0, int count0, const tVector & avg1, int count1) static
Definition at line 574 of file MathUtil.cpp.
 {
     double total = count0 + count1;
     return (count0 / total) * avg0 + (count1 / total) * avg1 ;
 }
AddAverage() [3/3]
double cMathUtil::AddAverage (double avg0, int count0, double avg1, int count1) static
Definition at line 568 of file MathUtil.cpp.
 {
     double total = count0 + count1;
     return (count0 / total) * avg0 + (count1 / total) * avg1;
 }
AxisAngleToEuler()
tVector cMathUtil::AxisAngleToEuler (const tVector & axis, double theta) static
Definition at line 361 of file MathUtil.cpp.
 {
     tQuaternion q = AxisAngleToQuaternion(axis, theta);
     return QuaternionToEuler(q);
 }
References AxisAngleToQuaternion(), and QuaternionToEuler().
AxisAngleToQuaternion()
tQuaternion cMathUtil::AxisAngleToQuaternion (const tVector & axis, double theta) static
Definition at line 435 of file MathUtil.cpp.
 {
     // axis must be normalized
     double c = std::cos(theta / 2);
     double s = std::sin(theta / 2);
     tQuaternion q;
     q.w() = c;
     q.x() = s * axis[0];
     q.y() = s * axis[1];
     q.z() = s * axis[2];
     return q;
 }
Referenced by AxisAngleToEuler(), cSimCharacter::CalcHeadingRot(), cKinTree::CalcHeadingRot(), cCharacter::CalcJointWorldRotation(), cCtPDController::ConvertActionToTargetPose(), EulerToQuaternion(), cKinTree::NormalizePoseHeading(), cCamera::RotatePos(), cSimCharacter::SetRootRotation(), cSimObj::SetRotation(), cSceneImitate::SyncKinCharNewCycle(), and cSceneImitate::SyncKinCharRoot().
BuildQuaternionDiffMat()
tMatrix cMathUtil::BuildQuaternionDiffMat (const tQuaternion & q) static
Definition at line 468 of file MathUtil.cpp.
 {
     tMatrix mat;
     mat << -0.5 * q.x(), -0.5 * q.y(), -0.5 * q.z(), 0,
         0.5 * q.w(), -0.5 * q.z(), 0.5 * q.y(), 0,
         0.5 * q.z(), 0.5 * q.w(), -0.5 * q.x(), 0,
         -0.5 * q.y(), 0.5 * q.x(), 0.5 * q.w(), 0;
     return mat;
 }
Referenced by cRBDUtil::BuildCjRoot(), and cKinTree::VelToPoseDiff().
ButterworthFilter()
void cMathUtil::ButterworthFilter (double dt, double cutoff, Eigen::VectorXd & out_x) static
Definition at line 854 of file MathUtil.cpp.
 {
     double sampling_rate = 1 / dt;
     int n = static_cast<int>(out_x.size());
     double wc = std::tan(cutoff * M_PI / sampling_rate);
     double k1 = std::sqrt(2) * wc;
     double k2 = wc * wc;
     double a = k2 / (1 + k1 + k2);
     double b = 2 * a;
     double c = a;
     double k3 = b / k2;
     double d = -2 * a + k3;
     double e = 1 - (2 * a) - k3;
     double xm2 = out_x[0];
     double xm1 = out_x[0];
     double ym2 = out_x[0];
     double ym1 = out_x[0];
     for (int s = 0; s < n; ++s)
     {
         double x = out_x[s];
         double y = a * x + b * xm1 + c * xm2 + d * ym1 + e * ym2;
         out_x[s] = y;
         xm2 = xm1;
         xm1 = x;
         ym2 = ym1;
         ym1 = y;
     }
     double yp2 = out_x[n - 1];
     double yp1 = out_x[n - 1];
     double zp2 = out_x[n - 1];
     double zp1 = out_x[n - 1];
     for (int t = n - 1; t >= 0; --t)
     {
         double y = out_x[t];
         double z = a * y + b * yp1 + c * yp2 + d * zp1 + e * zp2;
         out_x[t] = z;
         yp2 = yp1;
         yp1 = y;
         zp2 = zp1;
         zp1 = z;
     }
 }
Referenced by cMotion::FilterFrameVel().
CalcAABBIntersection()
void cMathUtil::CalcAABBIntersection (const tVector & aabb_min0, const tVector & aabb_max0, const tVector & aabb_min1, const tVector & aabb_max1, tVector & out_min, tVector & out_max) static
Definition at line 730 of file MathUtil.cpp.
 {
     out_min = aabb_min0.cwiseMax(aabb_min1);
     out_max = aabb_max0.cwiseMin(aabb_max1);
     if (out_min[0] > out_max[0])
     {
         out_min[0] = 0;
         out_max[0] = 0;
     }
     if (out_min[1] > out_max[1])
     {
         out_min[1] = 0;
         out_max[1] = 0;
     }
     if (out_min[2] > out_max[2])
     {
         out_min[2] = 0;
         out_max[2] = 0;
     }
 }
CalcAABBUnion()
void cMathUtil::CalcAABBUnion (const tVector & aabb_min0, const tVector & aabb_max0, const tVector & aabb_min1, const tVector & aabb_max1, tVector & out_min, tVector & out_max) static
Definition at line 752 of file MathUtil.cpp.
 {
     out_min = aabb_min0.cwiseMin(aabb_min1);
     out_max = aabb_max0.cwiseMax(aabb_max1);
 }
CalcBarycentric()
tVector cMathUtil::CalcBarycentric (const tVector & p, const tVector & a, const tVector & b, const tVector & c) static
Definition at line 687 of file MathUtil.cpp.
 {
     tVector v0 = b - a;
     tVector v1 = c - a;
     tVector v2 = p - a;
     double d00 = v0.dot(v0);
     double d01 = v0.dot(v1);
     double d11 = v1.dot(v1);
     double d20 = v2.dot(v0);
     double d21 = v2.dot(v1);
     double denom = d00 * d11 - d01 * d01;
     double v = (d11 * d20 - d01 * d21) / denom;
     double w = (d00 * d21 - d01 * d20) / denom;
     double u = 1.0f - v - w;
     return tVector(u, v, w, 0);
 }
CalcGaussianPartition()
double cMathUtil::CalcGaussianPartition (const Eigen::VectorXd & covar) static
Definition at line 626 of file MathUtil.cpp.
 {
     int data_size = static_cast<int>(covar.size());
     double det = covar.prod();
     double partition = std::sqrt(std::pow(2 * M_PI, data_size) * det);
     return partition;
 }
Referenced by EvalGaussian().
CalcQuaternionVel()
tVector cMathUtil::CalcQuaternionVel (const tQuaternion & q0, const tQuaternion & q1, double dt) static
Definition at line 478 of file MathUtil.cpp.
 {
     tQuaternion q_diff = cMathUtil::QuatDiff(q0, q1);
     tVector axis;
     double theta;
     QuaternionToAxisAngle(q_diff, axis, theta);
     return (theta / dt) * axis;
 }
References QuatDiff(), and QuaternionToAxisAngle().
Referenced by cKinTree::CalcVel().
CalcQuaternionVelRel()
tVector cMathUtil::CalcQuaternionVelRel (const tQuaternion & q0, const tQuaternion & q1, double dt) static
Definition at line 487 of file MathUtil.cpp.
 {
     // calculate relative rotational velocity in the coordinate frame of q0
     tQuaternion q_diff = q0.conjugate() * q1;
     tVector axis;
     double theta;
     QuaternionToAxisAngle(q_diff, axis, theta);
     return (theta / dt) * axis;
 }
References QuaternionToAxisAngle().
Referenced by cKinTree::CalcVel().
CalcSoftmax()
void cMathUtil::CalcSoftmax (const Eigen::VectorXd & vals, double temp, Eigen::VectorXd & out_prob) static
Definition at line 586 of file MathUtil.cpp.
 {
     assert(out_prob.size() == vals.size());
     int num_vals = static_cast<int>(vals.size());
     double sum = 0;
     double max_val = vals.maxCoeff();
     for (int i = 0; i < num_vals; ++i)
     {
         double val = vals[i];
         val = std::exp((val - max_val) / temp);
         out_prob[i] = val;
         sum += val;
     }
     out_prob /= sum;
 }
CheckNextInterval()
bool cMathUtil::CheckNextInterval (double delta, double curr_val, double int_size) static
Definition at line 783 of file MathUtil.cpp.
 {
     double pad = 0.001 * delta;
     int curr_count = static_cast<int>(std::floor((curr_val + pad) / int_size));
     int prev_count = static_cast<int>(std::floor((curr_val + pad - delta) / int_size));
     bool new_action = (curr_count != prev_count);
     return new_action;
 }
Referenced by cSceneImitate::CheckKinNewCycle(), and cCtController::CheckNeedNewAction().
Clamp() [1/3]
void cMathUtil::Clamp (const Eigen::VectorXd & min, const Eigen::VectorXd & max, Eigen::VectorXd & out_vec) static
Definition at line 11 of file MathUtil.cpp.
 {
     out_vec = out_vec.cwiseMin(max).cwiseMax(min);
 }
Clamp() [2/3]
double cMathUtil::Clamp (double val, double min, double max) static
Definition at line 16 of file MathUtil.cpp.
 {
     return std::max(min, std::min(val, max));
 }
Clamp() [3/3]
int cMathUtil::Clamp (int val, int min, int max) static
Definition at line 6 of file MathUtil.cpp.
 {
     return std::max(min, std::min(val, max));
 }
Referenced by cGround::CalcBlendParams(), cMotion::CalcCycleCount(), cGraphUtil::DrawBarPlot(), cDrawSimCharacter::DrawInfoValLog(), EulerToAxisAngle(), cAnnealer::Eval(), cKinCharacter::GetPhase(), cTrajectory::NormalizePhase(), RotMatToAxisAngle(), and Saturate().
ContainsAABB() [1/2]
bool cMathUtil::ContainsAABB (const tVector & aabb_min0, const tVector & aabb_max0, const tVector & aabb_min1, const tVector & aabb_max1) static
Definition at line 713 of file MathUtil.cpp.
 {
     return ContainsAABB(aabb_min0, aabb_min1, aabb_max1) && ContainsAABB(aabb_max0, aabb_min1, aabb_max1);
 }
References ContainsAABB().
ContainsAABB() [2/2]
bool cMathUtil::ContainsAABB (const tVector & pt, const tVector & aabb_min, const tVector & aabb_max) static
Definition at line 706 of file MathUtil.cpp.
 {
     bool contains = pt[0] >= aabb_min[0] && pt[1] >= aabb_min[1] && pt[2] >= aabb_min[2]
                     && pt[0] <= aabb_max[0] && pt[1] <= aabb_max[1] && pt[2] <= aabb_max[2];
     return contains;
 }
Referenced by ContainsAABB(), and cSceneSimChar::HasFallen().
ContainsAABBXZ() [1/2]
bool cMathUtil::ContainsAABBXZ (const tVector & aabb_min0, const tVector & aabb_max0, const tVector & aabb_min1, const tVector & aabb_max1) static
Definition at line 725 of file MathUtil.cpp.
 {
     return ContainsAABBXZ(aabb_min0, aabb_min1, aabb_max1) && ContainsAABBXZ(aabb_max0, aabb_min1, aabb_max1);
 }
References ContainsAABBXZ().
ContainsAABBXZ() [2/2]
bool cMathUtil::ContainsAABBXZ (const tVector & pt, const tVector & aabb_min, const tVector & aabb_max) static
Definition at line 718 of file MathUtil.cpp.
 {
     bool contains = pt[0] >= aabb_min[0] && pt[2] >= aabb_min[2]
         && pt[0] <= aabb_max[0] && pt[2] <= aabb_max[2];
     return contains;
 }
Referenced by ContainsAABBXZ().
CrossMat()
tMatrix cMathUtil::CrossMat (const tVector & a) static
Definition at line 224 of file MathUtil.cpp.
 {
     tMatrix m;
     m << 0,     -a[2],  a[1],   0,
          a[2],  0,      -a[0],  0,
          -a[1], a[0],   0,      0,
          0,     0,      0,      1;
     return m;
 }
Referenced by cSpAlg::BuildSpatialMatF(), and cSpAlg::BuildSpatialMatM().
DeltaRot() [1/2]
tMatrix cMathUtil::DeltaRot (const tMatrix & R0, const tMatrix & R1) static
Definition at line 398 of file MathUtil.cpp.
 {
     return R1 * R0.transpose();
 }
DeltaRot() [2/2]
void cMathUtil::DeltaRot (const tVector & axis0, double theta0, const tVector & axis1, double theta1, tVector & out_axis, double & out_theta) static
Definition at line 389 of file MathUtil.cpp.
 {
     tMatrix R0 = RotateMat(axis0, theta0);
     tMatrix R1 = RotateMat(axis1, theta1);
     tMatrix M = DeltaRot(R0, R1);
     RotMatToAxisAngle(M, out_axis, out_theta);
 }
References RotateMat(), and RotMatToAxisAngle().
DirToRotMat()
tMatrix cMathUtil::DirToRotMat (const tVector & dir, const tVector & up) static
Definition at line 367 of file MathUtil.cpp.
 {
     tVector x = up.cross3(dir);
     double x_norm = x.norm();
     if (x_norm == 0)
     {
         x_norm = 1;
         x = (dir.dot(up) >= 0) ? tVector(1, 0, 0, 0) : tVector(-1, 0, 0, 0);
     }
     x /= x_norm;
     tVector y = dir.cross3(x).normalized();
     tVector z = dir;
     tMatrix mat = tMatrix::Identity();
     mat.block(0, 0, 3, 1) = x.segment(0, 3);
     mat.block(0, 1, 3, 1) = y.segment(0, 3);
     mat.block(0, 2, 3, 1) = z.segment(0, 3);
     return mat;
 }
Referenced by cDrawKinTree::DrawTree().
EulerToAxisAngle()
void cMathUtil::EulerToAxisAngle (const tVector & euler, tVector & out_axis, double & out_theta) static
Definition at line 327 of file MathUtil.cpp.
 {
     double x = euler[0];
     double y = euler[1];
     double z = euler[2];
     double x_s = std::sin(x);
     double x_c = std::cos(x);
     double y_s = std::sin(y);
     double y_c = std::cos(y);
     double z_s = std::sin(z);
     double z_c = std::cos(z);
     double c = (y_c * z_c + x_s * y_s * z_s + x_c * z_c + x_c * y_c - 1) * 0.5;
     c = Clamp(c, -1.0, 1.0);
     out_theta = std::acos(c);
     if (std::abs(out_theta) < 0.00001)
     {
         out_axis = tVector(0, 0, 1, 0);
     }
     else
     {
         double m21 = x_s * y_c - x_c * y_s * z_s + x_s * z_c;
         double m02 = x_c * y_s * z_c + x_s * z_s + y_s;
         double m10 = y_c * z_s - x_s * y_s * z_c + x_c * z_s;
         double denom = std::sqrt(m21 * m21 + m02 * m02 + m10 * m10);
         out_axis[0] = m21 / denom;
         out_axis[1] = m02 / denom;
         out_axis[2] = m10 / denom;
         out_axis[3] = 0;
     }
 }
References Clamp().
Referenced by EulerToQuaternion(), cKinTree::GetBodyRotation(), cKinTree::GetDrawShapeRotation(), and cDrawUtil::Rotate().
EulerToQuaternion()
tQuaternion cMathUtil::EulerToQuaternion (const tVector & euler) static
Definition at line 403 of file MathUtil.cpp.
 {
     tVector axis;
     double theta;
     EulerToAxisAngle(euler, axis, theta);
     return AxisAngleToQuaternion(axis, theta);
 }
References AxisAngleToQuaternion(), and EulerToAxisAngle().
Referenced by cSimCharacter::BuildMultiBody(), cSimJoint::BuildPoseSpherical(), cSimCharacter::BuildSimBody(), and cSceneImitate::ResetKinChar().
EvalGaussian() [1/2]
double cMathUtil::EvalGaussian (const Eigen::VectorXd & mean, const Eigen::VectorXd & covar, const Eigen::VectorXd & sample) static
Definition at line 603 of file MathUtil.cpp.
 {
     assert(mean.size() == covar.size());
     assert(sample.size() == covar.size());
     Eigen::VectorXd diff = sample - mean;
     double exp_val = diff.dot(diff.cwiseQuotient(covar));
     double likelihood = std::exp(-0.5 * exp_val);
     double partition = CalcGaussianPartition(covar);
     likelihood /= partition;
     return likelihood;
 }
References CalcGaussianPartition().
EvalGaussian() [2/2]
double cMathUtil::EvalGaussian (double mean, double covar, double sample) static
Definition at line 617 of file MathUtil.cpp.
 {
     double diff = sample - mean;
     double exp_val = diff * diff / covar;
     double norm = 1 / std::sqrt(2 * M_PI * covar);
     double likelihood = norm * std::exp(-0.5 * exp_val);
     return likelihood;
 }
EvalGaussianLogp() [1/2]
double cMathUtil::EvalGaussianLogp (const Eigen::VectorXd & mean, const Eigen::VectorXd & covar, const Eigen::VectorXd & sample) static
Definition at line 634 of file MathUtil.cpp.
 {
     int data_size = static_cast<int>(covar.size());
     Eigen::VectorXd diff = sample - mean;
     double logp = -0.5 * diff.dot(diff.cwiseQuotient(covar));
     double det = covar.prod();
     logp += -0.5 * (data_size * std::log(2 * M_PI) + std::log(det));
     return logp;
 }
EvalGaussianLogp() [2/2]
double cMathUtil::EvalGaussianLogp (double mean, double covar, double sample) static
Definition at line 646 of file MathUtil.cpp.
 {
     double diff = sample - mean;
     double logp = -0.5 * diff * diff / covar;
     logp += -0.5 * (std::log(2 * M_PI) + std::log(covar));
     return logp;
 }
FlipCoin()
bool cMathUtil::FlipCoin (double p = 0.5) static
Definition at line 116 of file MathUtil.cpp.
 {
     return gRand.FlipCoin(p);
 }
References cRand::FlipCoin(), and gRand.
GetRigidTrans()
tVector cMathUtil::GetRigidTrans (const tMatrix & mat) static
Definition at line 243 of file MathUtil.cpp.
 {
     return tVector(mat(0, 3), mat(1, 3), mat(2, 3), 0);
 }
Referenced by cSimCharacter::BuildJoints().
IntersectAABB()
bool cMathUtil::IntersectAABB (const tVector & aabb_min0, const tVector & aabb_max0, const tVector & aabb_min1, const tVector & aabb_max1) static
Definition at line 759 of file MathUtil.cpp.
 {
     tVector center0 = 0.5 * (aabb_max0 + aabb_min0);
     tVector center1 = 0.5 * (aabb_max1 + aabb_min1);
     tVector size0 = aabb_max0 - aabb_min0;
     tVector size1 = aabb_max1 - aabb_min1;
     tVector test_len = 0.5 * (size0 + size1);
     tVector delta = center1 - center0;
     bool overlap = (std::abs(delta[0]) <= test_len[0]) && (std::abs(delta[1]) <= test_len[1]) && (std::abs(delta[2]) <= test_len[2]);
     return overlap;
 }
IntersectAABBXZ()
bool cMathUtil::IntersectAABBXZ (const tVector & aabb_min0, const tVector & aabb_max0, const tVector & aabb_min1, const tVector & aabb_max1) static
Definition at line 771 of file MathUtil.cpp.
 {
     tVector center0 = 0.5 * (aabb_max0 + aabb_min0);
     tVector center1 = 0.5 * (aabb_max1 + aabb_min1);
     tVector size0 = aabb_max0 - aabb_min0;
     tVector size1 = aabb_max1 - aabb_min1;
     tVector test_len = 0.5 * (size0 + size1);
     tVector delta = center1 - center0;
     bool overlap = (std::abs(delta[0]) <= test_len[0]) && (std::abs(delta[2]) <= test_len[2]);
     return overlap;
 }
InvEuler()
tVector cMathUtil::InvEuler (const tVector & euler) static
Definition at line 248 of file MathUtil.cpp.
 {
     tMatrix inv_mat = cMathUtil::RotateMat(tVector(1, 0, 0, 0), -euler[0])
                     * cMathUtil::RotateMat(tVector(0, 1, 0, 0), -euler[1])
                     * cMathUtil::RotateMat(tVector(0, 0, 1, 0), -euler[2]);
     tVector inv_euler = cMathUtil::RotMatToEuler(inv_mat);
     return inv_euler;
 }
References RotateMat(), and RotMatToEuler().
InvRigidMat()
tMatrix cMathUtil::InvRigidMat (const tMatrix & mat) static
Definition at line 234 of file MathUtil.cpp.
 {
     tMatrix inv_mat = tMatrix::Zero();
     inv_mat.block(0, 0, 3, 3) = mat.block(0, 0, 3, 3).transpose();
     inv_mat.col(3) = -inv_mat * mat.col(3);
     inv_mat(3, 3) = 1;
     return inv_mat;
 }
Referenced by cSimCharacter::BuildJoints(), cSimBodyJoint::BuildVel(), cCamera::BuildWorldViewMatrix(), cDrawCharacter::DrawHeading(), cSimObj::GetLocalTransform(), cRBDModel::GetParentChildMat(), cKinTree::ParentChildTrans(), and cKinTree::WorldJointTrans().
Lerp()
double cMathUtil::Lerp (double t, double val0, double val1) static
Definition at line 26 of file MathUtil.cpp.
 {
     return (1 - t) * val0 + t * val1;
 }
Referenced by cTimer::tParams::Blend().
MirrorQuaternion()
tQuaternion cMathUtil::MirrorQuaternion (const tQuaternion & q, eAxis axis) static
Definition at line 548 of file MathUtil.cpp.
 {
     tQuaternion mirror_q;
     mirror_q.w() = q.w();
     mirror_q.x() = (axis == eAxisX) ? q.x() : -q.x();
     mirror_q.y() = (axis == eAxisY) ? q.y() : -q.y();
     mirror_q.z() = (axis == eAxisZ) ? q.z() : -q.z();
     return mirror_q;
 }
References eAxisX, eAxisY, and eAxisZ.
Referenced by cCtController::BuildStatePose(), cCtController::BuildStateVel(), cCtPDController::ConvertActionToTargetPose(), and cKinTree::MirrorPoseStance().
NormalizeAngle()
double cMathUtil::NormalizeAngle (double theta) static
Definition at line 31 of file MathUtil.cpp.
 {
     // normalizes theta to be between [-pi, pi]
     double norm_theta = fmod(theta, 2 * M_PI);
     if (norm_theta > M_PI)
     {
         norm_theta = -2 * M_PI + norm_theta;
     }
     else if (norm_theta < -M_PI)
     {
         norm_theta = 2 * M_PI + norm_theta;
     }
     return norm_theta;
 }
Referenced by cSimBodyJoint::BuildPose(), QuaternionToAxisAngle(), and QuatTheta().
ProjectQuat()
tQuaternion cMathUtil::ProjectQuat (const tQuaternion & q, const tVector & dir) static
Definition at line 832 of file MathUtil.cpp.
 {
     assert(std::abs(dir.norm() - 1) < 0.00001);
     tVector ref_axis = tVector::Zero();
     int min_idx = 0;
     dir.cwiseAbs().minCoeff(&min_idx);
     ref_axis[min_idx] = 1;
     tVector rot_dir0 = dir.cross3(ref_axis);
     tVector rot_dir1 = cMathUtil::QuatRotVec(q, rot_dir0);
     rot_dir1 -= rot_dir1.dot(dir) * dir;
     double dir1_norm = rot_dir1.norm();
     tQuaternion p_rot = tQuaternion::Identity();
     if (dir1_norm > 0.0001)
     {
         rot_dir1 /= dir1_norm;
         p_rot = cMathUtil::VecDiffQuat(rot_dir0, rot_dir1);
     }
     return p_rot;
 }
References QuatRotVec(), and VecDiffQuat().
QuatDiff()
tQuaternion cMathUtil::QuatDiff (const tQuaternion & q0, const tQuaternion & q1) static
Definition at line 507 of file MathUtil.cpp.
 {
     return q1 * q0.conjugate();
 }
Referenced by cKinTree::CalcJointPoseDiff(), CalcQuaternionVel(), cKinTree::CalcRootRotDiff(), QuatDiffTheta(), and cKinCharacter::SetOriginRot().
QuatDiffTheta()
double cMathUtil::QuatDiffTheta (const tQuaternion & q0, const tQuaternion & q1) static
Definition at line 512 of file MathUtil.cpp.
 {
     tQuaternion dq = QuatDiff(q0, q1);
     return QuatTheta(dq);
 }
References QuatDiff(), and QuatTheta().
Referenced by cSceneImitate::CalcRewardImitate(), and cSceneImitate::CheckRootRotFail().
QuaternionToAxisAngle()
void cMathUtil::QuaternionToAxisAngle (const tQuaternion & q, tVector & out_axis, double & out_theta) static
Definition at line 448 of file MathUtil.cpp.
 {
     out_theta = 0;
     out_axis = tVector(0, 0, 1, 0);
     tQuaternion q1 = q;
     if (q1.w() > 1)
     {
         q1.normalize();
     }
     double sin_theta = std::sqrt(1 - q1.w() * q1.w());
     if (sin_theta > 0.000001)
     {
         out_theta = 2 * std::acos(q1.w());
         out_theta = cMathUtil::NormalizeAngle(out_theta);
         out_axis = tVector(q1.x(), q1.y(), q1.z(), 0) / sin_theta;
     }
 }
References NormalizeAngle().
Referenced by cPDController::CalcJointTauSpherical(), CalcQuaternionVel(), CalcQuaternionVelRel(), cCharacter::GetRootRotation(), cSimCharacter::GetRootRotation(), and cDrawUtil::Rotate().
QuaternionToEuler()
tVector cMathUtil::QuaternionToEuler (const tQuaternion & q) static
Definition at line 411 of file MathUtil.cpp.
 {
     double sinr = 2.0 * (q.w() * q.x() + q.y() * q.z());
     double cosr = 1.0 - 2.0 * (q.x() * q.x() + q.y() * q.y());
     double x = std::atan2(sinr, cosr);
     double sinp = 2.0 * (q.w() * q.y() - q.z() * q.x());
     double y = 0;
     if (fabs(sinp) >= 1)
     {
         y = copysign(M_PI / 2, sinp); // use 90 degrees if out of range
     }
     else
     {
         y = asin(sinp);
     }
     double siny = 2.0 * (q.w() * q.z() + q.x() * q.y());
     double cosy = 1.0 - 2.0 * (q.y() * q.y() + q.z() * q.z());
     double z = std::atan2(siny, cosy);
     return tVector(x, y, z, 0);
 }
Referenced by AxisAngleToEuler(), cSimJoint::BuildConstraintFixed(), cSimJoint::BuildConstraintPrismatic(), cSimJoint::BuildConstraintRevolute(), cSimJoint::BuildConstraintSpherical(), and cSimCharacter::SetPose().
QuatRotVec()
tVector cMathUtil::QuatRotVec (const tQuaternion & q, const tVector & dir) static
Definition at line 541 of file MathUtil.cpp.
 {
     tVector rot_dir = tVector::Zero();
     rot_dir.segment(0, 3)  = q * dir.segment(0, 3);
     return rot_dir;
 }
Referenced by cSimBodyJoint::ApplyTauSpherical(), cSimCharacter::BuildMultiBody(), cSimBodyJoint::BuildPose(), cCtController::BuildStatePose(), cCtController::BuildStateVel(), cSimBodyJoint::BuildVel(), cSimBodyJoint::CalcChildLocalPos(), cSimJoint::CalcChildLocalPos(), cKinTree::CalcHeading(), cSimCharacter::CalcHeadingRot(), cSimBodyJoint::CalcParentLocalPos(), cSimJoint::CalcParentLocalPos(), cKinCharacter::CalcPose(), cKinCharacter::GetCycleRootDelta(), cSimBodyLink::GetLinearVelocity(), cKinTree::NormalizePoseHeading(), ProjectQuat(), cKinCharacter::RotateOrigin(), cCamera::RotatePos(), cSimBodyJoint::SetPose(), cSimCharacter::SetRootTransform(), cSimCharacter::SetVel(), cSimBodyJoint::SetVel(), and cSimCharacter::UpdateLinkVel().
QuatSwingTwistDecomposition()
void cMathUtil::QuatSwingTwistDecomposition (const tQuaternion & q, const tVector & dir, tQuaternion & out_swing, tQuaternion & out_twist) static
Definition at line 819 of file MathUtil.cpp.
 {
     assert(std::abs(dir.norm() - 1) < 0.000001);
     assert(std::abs(q.norm() - 1) < 0.000001);
     tVector q_axis = tVector(q.x(), q.y(), q.z(), 0);
     double p = q_axis.dot(dir);
     tVector twist_axis = p * dir;
     out_twist = tQuaternion(q.w(), twist_axis[0], twist_axis[1], twist_axis[2]);
     out_twist.normalize();
     out_swing = q * out_twist.conjugate();
 }
QuatTheta()
double cMathUtil::QuatTheta (const tQuaternion & dq) static
Definition at line 518 of file MathUtil.cpp.
 {
     double theta = 0;
     tQuaternion q1 = dq;
     if (q1.w() > 1)
     {
         q1.normalize();
     }
     double sin_theta = std::sqrt(1 - q1.w() * q1.w());
     if (sin_theta > 0.0001)
     {
         theta = 2 * std::acos(q1.w());
         theta = cMathUtil::NormalizeAngle(theta);
     }
     return theta;
 }
References NormalizeAngle().
Referenced by cKinTree::CalcPoseErr(), cKinTree::CalcRootRotErr(), and QuatDiffTheta().
QuatToVec()
tVector cMathUtil::QuatToVec (const tQuaternion & q) static
Definition at line 502 of file MathUtil.cpp.
 {
     return tVector(q.w(), q.x(), q.y(), q.z());
 }
Referenced by cBVHReader::BuildJointPoseRoot(), cBVHReader::BuildJointPoseSpherical(), cCtController::BuildStatePose(), cKinTree::CalcJointPoseDiff(), cCtPDController::ConvertActionToTargetPose(), cPDController::GetTargetTheta(), cKinTree::LerpPoses(), cKinTree::MirrorPoseStance(), cSimCharacter::SetPose(), and cKinTree::SetRootRot().
RandDouble() [1/2]
double cMathUtil::RandDouble () static
Definition at line 46 of file MathUtil.cpp.
 {
     return RandDouble(0, 1);
 }
Referenced by cSceneImitate::CalcRandKinResetTime(), cTimer::Reset(), SampleDiscreteProb(), SampleRandPt(), and SampleRandPtBias().
RandDouble() [2/2]
double cMathUtil::RandDouble (double min, double max) static
Definition at line 51 of file MathUtil.cpp.
 {
     return gRand.RandDouble(min, max);
 }
References gRand, and cRand::RandDouble().
RandDoubleExp()
double cMathUtil::RandDoubleExp (double lambda) static
Definition at line 61 of file MathUtil.cpp.
 {
     return gRand.RandDoubleExp(lambda);
 }
References gRand, and cRand::RandDoubleExp().
Referenced by cTimer::Reset().
RandDoubleNorm()
double cMathUtil::RandDoubleNorm (double mean, double stdev) static
Definition at line 56 of file MathUtil.cpp.
 {
     return gRand.RandDoubleNorm(mean, stdev);
 }
References gRand, and cRand::RandDoubleNorm().
RandDoubleSeed()
double cMathUtil::RandDoubleSeed (double seed) static
Definition at line 66 of file MathUtil.cpp.
 {
     unsigned int int_seed = *reinterpret_cast<unsigned int*>(&seed);
     std::default_random_engine rand_gen(int_seed);
     std::uniform_real_distribution<double> dist;
     return dist(rand_gen);
 }
RandInt() [1/2]
int cMathUtil::RandInt () static
Definition at line 74 of file MathUtil.cpp.
 {
     return gRand.RandInt();
 }
References gRand, and cRand::RandInt().
RandInt() [2/2]
int cMathUtil::RandInt (int min, int max) static
Definition at line 79 of file MathUtil.cpp.
 {
     return gRand.RandInt(min, max);
 }
References gRand, and cRand::RandInt().
RandIntExclude()
int cMathUtil::RandIntExclude (int min, int max, int exc) static
Definition at line 94 of file MathUtil.cpp.
 {
     return gRand.RandIntExclude(min, max, exc);
 }
References gRand, and cRand::RandIntExclude().
RandSign()
int cMathUtil::RandSign () static
Definition at line 105 of file MathUtil.cpp.
 {
     return gRand.RandSign();
 }
References gRand, and cRand::RandSign().
RandUint() [1/2]
int cMathUtil::RandUint () static
Definition at line 84 of file MathUtil.cpp.
 {
     return gRand.RandUint();
 }
References gRand, and cRand::RandUint().
Referenced by cGround::cGround(), and cScene::cScene().
RandUint() [2/2]
int cMathUtil::RandUint (unsigned int min, unsigned int max) static
Definition at line 89 of file MathUtil.cpp.
 {
     return gRand.RandUint(min, max);
 }
References gRand, and cRand::RandUint().
RotateMat() [1/3]
tMatrix cMathUtil::RotateMat (const tQuaternion & q) static
Definition at line 192 of file MathUtil.cpp.
 {
     tMatrix mat = tMatrix::Identity();
     double sqw = q.w() * q.w();
     double sqx = q.x()*  q.x();
     double sqy = q.y() * q.y();
     double sqz = q.z() * q.z();
     double invs = 1 / (sqx + sqy + sqz + sqw);
     mat(0, 0) = (sqx - sqy - sqz + sqw) * invs;
     mat(1, 1) = (-sqx + sqy - sqz + sqw) * invs;
     mat(2, 2) = (-sqx - sqy + sqz + sqw) * invs;
     double tmp1 = q.x()*q.y();
     double tmp2 = q.z()*q.w();
     mat(1, 0) = 2.0 * (tmp1 + tmp2) * invs;
     mat(0, 1) = 2.0 * (tmp1 - tmp2) * invs;
     tmp1 = q.x()*q.z();
     tmp2 = q.y()*q.w();
     mat(2, 0) = 2.0 * (tmp1 - tmp2) * invs;
     mat(0, 2) = 2.0 * (tmp1 + tmp2) * invs;
     tmp1 = q.y()*q.z();
     tmp2 = q.x()*q.w();
     mat(2, 1) = 2.0 * (tmp1 + tmp2) * invs;
     mat(1, 2) = 2.0 * (tmp1 - tmp2) * invs;
     return mat;
 }
RotateMat() [2/3]
tMatrix cMathUtil::RotateMat (const tVector & axis, double theta) static
Definition at line 173 of file MathUtil.cpp.
 {
     assert(std::abs(axis.squaredNorm() - 1) < 0.0001);
     double c = std::cos(theta);
     double s = std::sin(theta);
     double x = axis[0];
     double y = axis[1];
     double z = axis[2];
     tMatrix mat;
     mat <<  c + x * x * (1 - c),        x * y * (1 - c) - z * s,    x * z * (1 - c) + y * s,    0,
             y * x * (1 - c) + z * s,    c + y * y * (1 - c),        y * z * (1 - c) - x * s,    0,
             z * x * (1 - c) - y * s,    z * y * (1 - c) + x * s,    c + z * z * (1 - c),        0,
             0,                          0,                          0,                          1;
     return mat;
 }
RotateMat() [3/3]
tMatrix cMathUtil::RotateMat (const tVector & euler) static
Definition at line 144 of file MathUtil.cpp.
 {
     double x = euler[0];
     double y = euler[1];
     double z = euler[2];
     double x_s = std::sin(x);
     double x_c = std::cos(x);
     double y_s = std::sin(y);
     double y_c = std::cos(y);
     double z_s = std::sin(z);
     double z_c = std::cos(z);
     tMatrix mat = tMatrix::Identity();
     mat(0, 0) = y_c * z_c;
     mat(1, 0) = y_c * z_s;
     mat(2, 0) = -y_s;
     mat(0, 1) = x_s * y_s * z_c - x_c * z_s;
     mat(1, 1) = x_s * y_s * z_s + x_c * z_c;
     mat(2, 1) = x_s * y_c;
     mat(0, 2) = x_c * y_s * z_c + x_s * z_s;
     mat(1, 2) = x_c * y_s * z_s - x_s * z_c;
     mat(2, 2) = x_c * y_c;
     return mat;
 }
Referenced by cKinTree::BodyJointTrans(), cKinTree::BuildAttachTrans(), cKinTree::BuildHeadingTrans(), cSimBodyJoint::BuildJointChildTrans(), cSimJoint::BuildJointChildTrans(), cSimBodyJoint::BuildJointParentTrans(), cSimJoint::BuildJointParentTrans(), cSimCharacter::BuildJoints(), cRBDUtil::BuildJointSubspaceRoot(), cKinTree::ChildParentTransPlanar(), cKinTree::ChildParentTransRevolute(), cKinTree::ChildParentTransRoot(), cKinTree::ChildParentTransSpherical(), DeltaRot(), cDrawUtil::DrawArrow3D(), cBVHReader::getRotationForFrame(), InvEuler(), cCamera::MouseMove(), and cMatrixStack::Rotate().
RotMatToAxisAngle()
void cMathUtil::RotMatToAxisAngle (const tMatrix & mat, tVector & out_axis, double & out_theta) static
Definition at line 257 of file MathUtil.cpp.
 {
     double c = (mat(0, 0) + mat(1, 1) + mat(2, 2) - 1) * 0.5;
     c = cMathUtil::Clamp(c, -1.0, 1.0);
     out_theta = std::acos(c);
     if (std::abs(out_theta) < 0.00001)
     {
         out_axis = tVector(0, 0, 1, 0);
     }
     else
     {
         double m21 = mat(2, 1) - mat(1, 2);
         double m02 = mat(0, 2) - mat(2, 0);
         double m10 = mat(1, 0) - mat(0, 1);
         double denom = std::sqrt(m21 * m21 + m02 * m02 + m10 * m10);
         out_axis[0] = m21 / denom;
         out_axis[1] = m02 / denom;
         out_axis[2] = m10 / denom;
         out_axis[3] = 0;
     }
 }
References Clamp().
Referenced by cKinTree::CalcBodyPartRotation(), cKinTree::CalcJointWorldTheta(), cSimBodyJoint::CalcWorldRotation(), cSimJoint::CalcWorldRotation(), and DeltaRot().
RotMatToEuler()
tVector cMathUtil::RotMatToEuler (const tMatrix & mat) static
Definition at line 280 of file MathUtil.cpp.
 {
     tVector euler;
     euler[0] = std::atan2(mat(2, 1), mat(2, 2));
     euler[1] = std::atan2(-mat(2, 0), std::sqrt(mat(2, 1) * mat(2, 1) + mat(2, 2) * mat(2, 2)));
     euler[2] = std::atan2(mat(1, 0), mat(0, 0));
     euler[3] = 0;
     return euler;
 }
Referenced by InvEuler().
RotMatToQuaternion()
tQuaternion cMathUtil::RotMatToQuaternion (const tMatrix & mat) static
Definition at line 290 of file MathUtil.cpp.
 {
     double tr = mat(0, 0) + mat(1, 1) + mat(2, 2);
     tQuaternion q;
     if (tr > 0) {
         double S = sqrt(tr + 1.0) * 2; // S=4*qw
         q.w() = 0.25 * S;
         q.x() = (mat(2, 1) - mat(1, 2)) / S;
         q.y() = (mat(0, 2) - mat(2, 0)) / S;
         q.z() = (mat(1, 0) - mat(0, 1)) / S;
     }
     else if ((mat(0, 0) > mat(1, 1) && (mat(0, 0) > mat(2, 2)))) {
         double S = sqrt(1.0 + mat(0, 0) - mat(1, 1) - mat(2, 2)) * 2; // S=4*qx
         q.w() = (mat(2, 1) - mat(1, 2)) / S;
         q.x() = 0.25 * S;
         q.y() = (mat(0, 1) + mat(1, 0)) / S;
         q.z() = (mat(0, 2) + mat(2, 0)) / S;
     }
     else if (mat(1, 1) > mat(2, 2)) {
         double S = sqrt(1.0 + mat(1, 1) - mat(0, 0) - mat(2, 2)) * 2; // S=4*qy
         q.w() = (mat(0, 2) - mat(2, 0)) / S;
         q.x() = (mat(0, 1) + mat(1, 0)) / S;
         q.y() = 0.25 * S;
         q.z() = (mat(1, 2) + mat(2, 1)) / S;
     }
     else {
         double S = sqrt(1.0 + mat(2, 2) - mat(0, 0) - mat(1, 1)) * 2; // S=4*qz
         q.w() = (mat(1, 0) - mat(0, 1)) / S;
         q.x() = (mat(0, 2) + mat(2, 0)) / S;
         q.y() = (mat(1, 2) + mat(2, 1)) / S;
         q.z() = 0.25 * S;
     }
     return q;
 }
Referenced by cBVHReader::BuildJointPoseRoot(), cBVHReader::BuildJointPoseSpherical(), cSimCharacter::BuildJoints(), cCtController::BuildStatePose(), cCtController::BuildStateVel(), cKinTree::CalcJointWorldRot(), cSimBodyJoint::CalcWorldRotation(), cSimJoint::CalcWorldRotation(), and cCharacter::WriteState().
SampleDiscreteProb()
int cMathUtil::SampleDiscreteProb (const Eigen::VectorXd & probs) static
Definition at line 666 of file MathUtil.cpp.
 {
     assert(std::abs(probs.sum() - 1) < 0.00001);
     double rand = RandDouble();
     int rand_idx = gInvalidIdx;
     int num_probs = static_cast<int>(probs.size());
     for (int i = 0; i < num_probs; ++i)
     {
         double curr_prob = probs[i];
         rand -= curr_prob;
         if (rand <= 0)
         {
             rand_idx = i;
             break;
         }
     }
     return rand_idx;
 }
References gInvalidIdx, and RandDouble().
SampleRandPt()
tVector cMathUtil::SampleRandPt (const tVector & bound_min, const tVector & bound_max) static
Definition at line 792 of file MathUtil.cpp.
 {
     tVector pt = tVector(RandDouble(bound_min[0], bound_max[0]),
                         RandDouble(bound_min[1], bound_max[1]),
                         RandDouble(bound_min[2], bound_max[2]), 0);
     return pt;
 }
References RandDouble().
Referenced by SampleRandPtBias().
SampleRandPtBias() [1/2]
tVector cMathUtil::SampleRandPtBias (const tVector & bound_min, const tVector & bound_max) static
Definition at line 800 of file MathUtil.cpp.
 {
     return SampleRandPtBias(bound_min, bound_max, 0.5 * (bound_max + bound_min));
 }
SampleRandPtBias() [2/2]
tVector cMathUtil::SampleRandPtBias (const tVector & bound_min, const tVector & bound_max, const tVector & focus) static
Definition at line 805 of file MathUtil.cpp.
 {
     double t = RandDouble(0, 1);
     tVector size = bound_max - bound_min;
     tVector new_min = focus + (t * 0.5) * size;
     tVector new_max = focus - (t * 0.5) * size;
     tVector offset = (bound_min - new_min).cwiseMax(0);
     offset += (bound_max - new_max).cwiseMin(0);
     new_min += offset;
     new_max += offset;
     return SampleRandPt(new_min, new_max);
 }
References RandDouble(), and SampleRandPt().
Saturate()
double cMathUtil::Saturate (double val) static
Definition at line 21 of file MathUtil.cpp.
 {
     return Clamp(val, 0.0, 1.0);
 }
References Clamp().
Referenced by cMotion::BlendFrames().
ScaleMat() [1/2]
tMatrix cMathUtil::ScaleMat (const tVector & scale) static
Definition at line 135 of file MathUtil.cpp.
 {
     tMatrix mat = tMatrix::Identity();
     mat(0, 0) = scale[0];
     mat(1, 1) = scale[1];
     mat(2, 2) = scale[2];
     return mat;
 }
ScaleMat() [2/2]
tMatrix cMathUtil::ScaleMat (double scale) static
Definition at line 130 of file MathUtil.cpp.
 {
     return ScaleMat(tVector::Ones() * scale);
 }
SeedRand()
void cMathUtil::SeedRand (unsigned long int seed) static
Definition at line 99 of file MathUtil.cpp.
 {
     gRand.Seed(seed);
     srand(gRand.RandInt());
 }
References gRand, cRand::RandInt(), and cRand::Seed().
Referenced by cDeepMimicCore::SeedRand().
Sigmoid() [1/2]
double cMathUtil::Sigmoid (double x) static
Definition at line 654 of file MathUtil.cpp.
 {
     return Sigmoid(x, 1, 0);
 }
Sigmoid() [2/2]
double cMathUtil::Sigmoid (double x, double gamma, double bias) static
Definition at line 659 of file MathUtil.cpp.
 {
     double exp = -gamma * (x + bias);
     double val = 1 / (1 + std::exp(exp));
     return val;
 }
Sign() [1/2]
double cMathUtil::Sign (double val) static
Definition at line 558 of file MathUtil.cpp.
 {
     return SignAux<double>(val);
 }
Referenced by cDrawScene::UpdateCameraTracking().
Sign() [2/2]
int cMathUtil::Sign (int val) static
Definition at line 563 of file MathUtil.cpp.
 {
     return SignAux<int>(val);
 }
SignAux()
template<typename T > static T cMathUtil::SignAux (T val) inline static private
Definition at line 149 of file MathUtil.h.
     {
         return (T(0) < val) - (val < T(0));
     }
SmoothStep()
double cMathUtil::SmoothStep (double t) static
Definition at line 110 of file MathUtil.cpp.
 {
     double val = t * t * t * (t * (t * 6 - 15) + 10);
     return val;
 }
TranslateMat()
tMatrix cMathUtil::TranslateMat (const tVector & trans) static
Definition at line 121 of file MathUtil.cpp.
 {
     tMatrix mat = tMatrix::Identity();
     mat(0, 3) = trans[0];
     mat(1, 3) = trans[1];
     mat(2, 3) = trans[2];
     return mat;
 }
Referenced by cKinTree::BodyJointTrans(), cSimBodyJoint::BuildJointChildTrans(), cSimJoint::BuildJointChildTrans(), cSimBodyJoint::BuildJointParentTrans(), cSimJoint::BuildJointParentTrans(), cSimCharacter::BuildJoints(), cKinTree::BuildOriginTrans(), cKinTree::ChildParentTransPlanar(), cKinTree::ChildParentTransPrismatic(), cKinTree::ChildParentTransRoot(), and cBVHReader::parseJoint().
VecDiffQuat()
tQuaternion cMathUtil::VecDiffQuat (const tVector & v0, const tVector & v1) static
Definition at line 536 of file MathUtil.cpp.
 {
     return tQuaternion::FromTwoVectors(v0.segment(0, 3), v1.segment(0, 3));
 }
Referenced by cDrawUtil::DrawArrow3D(), and ProjectQuat().
VecToQuat()
tQuaternion cMathUtil::VecToQuat (const tVector & v) static
Definition at line 497 of file MathUtil.cpp.
 {
     return tQuaternion(v[0], v[1], v[2], v[3]);
 }
Referenced by cRBDUtil::BuildCjRoot(), cKinTree::CalcJointPoseDiff(), cPDController::CalcJointTauSpherical(), cKinTree::CalcPoseErr(), cKinTree::CalcVel(), cKinTree::ChildParentTransSpherical(), cKinTree::GetRootRot(), cPDController::GetTargetTheta(), cKinTree::LerpPoses(), cKinTree::MirrorPoseStance(), cSimBodyJoint::SetPose(), and cKinTree::VelToPoseDiff().
Member Data Documentation
gRand
cRand cMathUtil::gRand = cRand() static private
Definition at line 146 of file MathUtil.h.
Referenced by FlipCoin(), RandDouble(), RandDoubleExp(), RandDoubleNorm(), RandInt(), RandIntExclude(), RandSign(), RandUint(), and SeedRand().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/MathUtil.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/MathUtil.cpp