My Project: cCtController Class Reference
cCtController Class Reference
#include <CtController.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cCtController ()
virtual ~cCtController ()
virtual void SetUpdateRate (double rate)
virtual double GetUpdateRate () const
virtual void UpdateCalcTau (double timestep, Eigen::VectorXd &out_tau)
virtual double GetCyclePeriod () const
virtual void SetCyclePeriod (double period)
virtual void SetInitTime (double time)
virtual double GetPhase () const
virtual int GetStateSize () const
virtual int GetActionSize () const
virtual void BuildStateOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionBounds (Eigen::VectorXd &out_min, Eigen::VectorXd &out_max) const
virtual void BuildActionOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildStateNormGroups (Eigen::VectorXi &out_groups) const
virtual void RecordState (Eigen::VectorXd &out_state)
virtual std::string GetName () const
Public Member Functions inherited from cDeepMimicCharController
virtual EIGEN_MAKE_ALIGNED_OPERATOR_NEW ~cDeepMimicCharController ()
virtual void Init (cSimCharacter *character, const std::string &param_file)
virtual void Reset ()
virtual void Clear ()
virtual void Update (double timestep)
virtual void PostUpdate (double timestep)
virtual void UpdateApplyTau (const Eigen::VectorXd &tau)
virtual bool NeedNewAction () const
virtual void ApplyAction (const Eigen::VectorXd &action)
virtual void RecordGoal (Eigen::VectorXd &out_goal) const
virtual void RecordAction (Eigen::VectorXd &out_action) const
virtual eActionSpace GetActionSpace () const
virtual double GetRewardMin () const
virtual double GetRewardMax () const
virtual void SetViewDistMin (double dist)
virtual void SetViewDistMax (double dist)
virtual double GetViewDistMin () const
virtual double GetViewDistMax () const
virtual void GetViewBound (tVector &out_min, tVector &out_max) const
virtual double GetPrevActionTime () const
virtual const tVector & GetPrevActionCOM () const
virtual double GetTime () const
virtual const Eigen::VectorXd & GetTau () const
virtual const cCircularBuffer< double > & GetValLog () const
virtual void LogVal (double val)
Public Member Functions inherited from cCharController
virtual ~cCharController ()
virtual int GetGoalSize () const
virtual int GetNumActions () const
virtual void HandlePoseReset ()
virtual void HandleVelReset ()
virtual void BuildGoalOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildGoalNormGroups (Eigen::VectorXi &out_groups) const
virtual int NumChildren () const
virtual const std::shared_ptr< cCharController > & GetChild (int i) const
Public Member Functions inherited from cController
virtual ~cController ()
virtual void Init (cSimCharacter *character)
virtual bool IsValid () const
virtual bool LoadParams (const std::string &param_file)
virtual int GetNumOptParams () const
virtual void BuildOptParams (Eigen::VectorXd &out_params) const
virtual void SetOptParams (const Eigen::VectorXd &params)
virtual void SetOptParams (const Eigen::VectorXd &params, Eigen::VectorXd &out_params) const
virtual void FetchOptParamScale (Eigen::VectorXd &out_scale) const
virtual void OutputOptParams (const std::string &file, const Eigen::VectorXd &params) const
virtual void OutputOptParams (FILE *f, const Eigen::VectorXd &params) const
virtual void SetActive (bool active)
virtual bool IsActive () const
virtual void SetMode (eMode mode)
virtual const cSimCharacter * GetChar () const
Protected Member Functions
virtual void ResetParams ()
virtual int GetPosFeatureDim () const
virtual int GetRotFeatureDim () const
virtual bool ParseParams (const Json::Value &json)
virtual void UpdateBuildTau (double time_step, Eigen::VectorXd &out_tau)
virtual bool CheckNeedNewAction (double timestep) const
virtual void NewActionUpdate ()
virtual int GetStatePoseSize () const
virtual int GetStateVelSize () const
virtual int GetStatePoseOffset () const
virtual int GetStatePhaseSize () const
virtual int GetStatePhaseOffset () const
virtual int GetActionPhaseOffset () const
virtual int GetActionPhaseSize () const
virtual int GetActionCtrlOffset () const
virtual int GetActionCtrlSize () const
virtual void BuildStatePhaseOffsetScale (Eigen::VectorXd &phase_offset, Eigen::VectorXd &phase_scale) const
virtual void BuildStatePose (Eigen::VectorXd &out_pose) const
virtual void BuildStateVel (Eigen::VectorXd &out_vel) const
virtual void BuildStatePhase (Eigen::VectorXd &out_phase) const
virtual void BuildJointActionBounds (int joint_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max) const
virtual void BuildJointActionOffsetScale (int joint_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual bool FlipStance () const
virtual int RetargetJointID (int joint_id) const
virtual double GetPhaseRate () const
Protected Member Functions inherited from cDeepMimicCharController
cDeepMimicCharController ()
virtual void InitResources ()
virtual void InitAction ()
virtual void InitTau ()
virtual int GetPosDim () const
virtual void HandleNewAction ()
virtual void PostProcessAction (Eigen::VectorXd &out_action) const
virtual int GetStateVelOffset () const
Protected Member Functions inherited from cCharController
cCharController ()
Protected Member Functions inherited from cController
cController ()
Protected Attributes
double mUpdateRate
double mCyclePeriod
bool mEnablePhaseInput
bool mEnablePhaseAction
bool mRecordWorldRootPos
bool mRecordWorldRootRot
double mPhaseOffset
double mInitTimeOffset
Eigen::VectorXd mActionBoundMin
Eigen::VectorXd mActionBoundMax
Protected Attributes inherited from cDeepMimicCharController
double mTime
bool mNeedNewAction
Eigen::VectorXd mAction
Eigen::VectorXd mTau
double mViewDistMin
double mViewDistMax
int mPosDim
double mPrevActionTime
tVector mPrevActionCOM
cCircularBuffer< double > mValLog
Protected Attributes inherited from cController
cSimCharacter * mChar
eMode mMode
bool mValid
Additional Inherited Members
Public Types inherited from cController
enum eMode { eModeActive, eModeInactive, eModePassive, eModeMax }
Static Public Attributes inherited from cCharController
const static int gNormGroupSingle = 0
const static int gNormGroupNone = -1
Detailed Description
Definition at line 6 of file CtController.h.
Constructor & Destructor Documentation
cCtController()
cCtController::cCtController ()
Definition at line 6 of file CtController.cpp.
                              : cDeepMimicCharController()
 {
     mUpdateRate = 30.0;
     mCyclePeriod = 1;
     mEnablePhaseInput = false;
     mEnablePhaseAction = false;
     mRecordWorldRootPos = false;
     mRecordWorldRootRot = false;
     SetViewDistMax(1);
     mPhaseOffset = 0;
     mInitTimeOffset = 0;
 }
References mCyclePeriod, mEnablePhaseAction, mEnablePhaseInput, mInitTimeOffset, mPhaseOffset, mRecordWorldRootPos, mRecordWorldRootRot, mUpdateRate, and cDeepMimicCharController::SetViewDistMax().
~cCtController()
cCtController::~cCtController () virtual
Definition at line 20 of file CtController.cpp.
 {
 }
Member Function Documentation
BuildActionBounds()
void cCtController::BuildActionBounds (Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) const virtual
Reimplemented from cCharController.
Definition at line 89 of file CtController.cpp.
 {
     int action_size = GetActionSize();
     out_min = Eigen::VectorXd::Zero(action_size);
     out_max = Eigen::VectorXd::Zero(action_size);
     int root_id = mChar->GetRootID();
     int root_size = mChar->GetParamSize(root_id);
     int num_joints = mChar->GetNumJoints();
     int ctrl_offset = GetActionCtrlOffset();
     if (mEnablePhaseAction)
     {
         int phase_offset = GetActionPhaseOffset();
         out_min[phase_offset] = -5;
         out_max[phase_offset] = 5;
     }
     for (int j = root_id + 1; j < num_joints; ++j)
     {
         const cSimBodyJoint& joint = mChar->GetJoint(j);
         if (joint.IsValid())
         {
             int param_offset = mChar->GetParamOffset(j);
             int param_size = mChar->GetParamSize(j);
             if (param_size > 0)
             {
                 Eigen::VectorXd lim_min;
                 Eigen::VectorXd lim_max;
                 BuildJointActionBounds(j, lim_min, lim_max);
                 assert(lim_min.size() == param_size);
                 assert(lim_max.size() == param_size);
                 param_offset -= root_size;
                 param_offset += ctrl_offset;
                 out_min.segment(param_offset, param_size) = lim_min;
                 out_max.segment(param_offset, param_size) = lim_max;
             }
         }
     }
 }
References BuildJointActionBounds(), GetActionCtrlOffset(), GetActionPhaseOffset(), GetActionSize(), cSimCharacter::GetJoint(), cCharacter::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), cCharacter::GetRootID(), cSimBodyJoint::IsValid(), cController::mChar, and mEnablePhaseAction.
BuildActionOffsetScale()
void cCtController::BuildActionOffsetScale (Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const virtual
Reimplemented from cCharController.
Definition at line 229 of file CtController.cpp.
 {
     int action_size = GetActionSize();
     out_offset = Eigen::VectorXd::Zero(action_size);
     out_scale = Eigen::VectorXd::Ones(action_size);
     int root_id = mChar->GetRootID();
     int root_size = mChar->GetParamSize(mChar->GetRootID());
     int num_joints = mChar->GetNumJoints();
     int ctrl_offset = GetActionCtrlOffset();
     if (mEnablePhaseAction)
     {
         int phase_offset = GetActionPhaseOffset();
         out_offset[phase_offset] = -1 / mCyclePeriod;
         out_scale[phase_offset] = 1;
     }
     for (int j = root_id + 1; j < num_joints; ++j)
     {
         const cSimBodyJoint& joint = mChar->GetJoint(j);
         if (joint.IsValid())
         {
             int param_offset = mChar->GetParamOffset(j);
             int param_size = mChar->GetParamSize(j);
             if (param_size > 0)
             {
                 Eigen::VectorXd curr_offset;
                 Eigen::VectorXd curr_scale;
                 BuildJointActionOffsetScale(j, curr_offset, curr_scale);
                 assert(curr_offset.size() == param_size);
                 assert(curr_scale.size() == param_size);
                 param_offset -= root_size;
                 param_offset += ctrl_offset;
                 out_offset.segment(param_offset, param_size) = curr_offset;
                 out_scale.segment(param_offset, param_size) = curr_scale;
             }
         }
     }
 }
References BuildJointActionOffsetScale(), GetActionCtrlOffset(), GetActionPhaseOffset(), GetActionSize(), cSimCharacter::GetJoint(), cCharacter::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), cCharacter::GetRootID(), cSimBodyJoint::IsValid(), cController::mChar, mCyclePeriod, and mEnablePhaseAction.
BuildJointActionBounds()
void cCtController::BuildJointActionBounds (int joint_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) const protected virtual
Reimplemented in cCtPDController, and cCtVelController.
Definition at line 536 of file CtController.cpp.
 {
     const Eigen::MatrixXd& joint_mat = mChar->GetJointMat();
     cCtCtrlUtil::BuildBoundsTorque(joint_mat, joint_id, out_min, out_max);
 }
References cCtCtrlUtil::BuildBoundsTorque(), cCharacter::GetJointMat(), and cController::mChar.
Referenced by BuildActionBounds().
BuildJointActionOffsetScale()
void cCtController::BuildJointActionOffsetScale (int joint_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const protected virtual
Reimplemented in cCtPDController, and cCtVelController.
Definition at line 542 of file CtController.cpp.
 {
     const Eigen::MatrixXd& joint_mat = mChar->GetJointMat();
     cCtCtrlUtil::BuildOffsetScaleTorque(joint_mat, joint_id, out_offset, out_scale);
 }
References cCtCtrlUtil::BuildOffsetScaleTorque(), cCharacter::GetJointMat(), and cController::mChar.
Referenced by BuildActionOffsetScale().
BuildStateNormGroups()
void cCtController::BuildStateNormGroups (Eigen::VectorXi & out_groups) const virtual
Reimplemented from cCharController.
Definition at line 272 of file CtController.cpp.
 {
     cDeepMimicCharController::BuildStateNormGroups(out_groups);
     if (mEnablePhaseInput)
     {
         int phase_group = gNormGroupNone;
         int phase_offset = GetStatePhaseOffset();
         int phase_size = GetStatePhaseSize();
         out_groups.segment(phase_offset, phase_size) = phase_group * Eigen::VectorXi::Ones(phase_size);
     }
 }
References cCharController::BuildStateNormGroups(), GetStatePhaseOffset(), GetStatePhaseSize(), cCharController::gNormGroupNone, and mEnablePhaseInput.
BuildStateOffsetScale()
void cCtController::BuildStateOffsetScale (Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const virtual
Reimplemented from cCharController.
Definition at line 72 of file CtController.cpp.
 {
     cDeepMimicCharController::BuildStateOffsetScale(out_offset, out_scale);
     if (mEnablePhaseInput)
     {
         Eigen::VectorXd phase_offset;
         Eigen::VectorXd phase_scale;
         BuildStatePhaseOffsetScale(phase_offset, phase_scale);
         int phase_idx = GetStatePhaseOffset();
         int phase_size = GetStatePhaseSize();
         out_offset.segment(phase_idx, phase_size) = phase_offset;
         out_scale.segment(phase_idx, phase_size) = phase_scale;
     }
 }
References cCharController::BuildStateOffsetScale(), BuildStatePhaseOffsetScale(), GetStatePhaseOffset(), GetStatePhaseSize(), and mEnablePhaseInput.
BuildStatePhase()
void cCtController::BuildStatePhase (Eigen::VectorXd & out_phase) const protected virtual
Definition at line 529 of file CtController.cpp.
 {
     double phase = GetPhase();
     out_phase = Eigen::VectorXd::Zero(GetStatePhaseSize());
     out_phase[0] = phase;
 }
References GetPhase(), and GetStatePhaseSize().
Referenced by RecordState().
BuildStatePhaseOffsetScale()
void cCtController::BuildStatePhaseOffsetScale (Eigen::VectorXd & phase_offset, Eigen::VectorXd & phase_scale) const protected virtual
Definition at line 359 of file CtController.cpp.
 {
     double offset = -0.5;
     double scale = 2;
     int phase_size = GetStatePhaseSize();
     phase_offset = offset * Eigen::VectorXd::Ones(phase_size);
     phase_scale = scale * Eigen::VectorXd::Ones(phase_size);
 }
References GetStatePhaseSize().
Referenced by BuildStateOffsetScale().
BuildStatePose()
void cCtController::BuildStatePose (Eigen::VectorXd & out_pose) const protected virtual
Reimplemented from cDeepMimicCharController.
Definition at line 368 of file CtController.cpp.
 {
     tMatrix origin_trans = mChar->BuildOriginTrans();
     tQuaternion origin_quat = cMathUtil::RotMatToQuaternion(origin_trans);
     bool flip_stance = FlipStance();
     if (flip_stance)
     {
         origin_trans.row(2) *= -1; // reflect z
     }
     tVector root_pos = mChar->GetRootPos();
     tVector root_pos_rel = root_pos;
     root_pos_rel[3] = 1;
     root_pos_rel = origin_trans * root_pos_rel;
     root_pos_rel[3] = 0;
     out_pose = Eigen::VectorXd::Zero(GetStatePoseSize());
     out_pose[0] = root_pos_rel[1];
     int num_parts = mChar->GetNumBodyParts();
     int root_id = mChar->GetRootID();
     int pos_dim = GetPosFeatureDim();
     int rot_dim = GetRotFeatureDim();
     tQuaternion mirror_inv_origin_quat = origin_quat.conjugate();
     mirror_inv_origin_quat = cMathUtil::MirrorQuaternion(mirror_inv_origin_quat, cMathUtil::eAxisZ);
     int idx = 1;
     for (int i = 0; i < num_parts; ++i)
     {
         int part_id = RetargetJointID(i);
         if (mChar->IsValidBodyPart(part_id))
         {
             const auto& curr_part = mChar->GetBodyPart(part_id);
             tVector curr_pos = curr_part->GetPos();
             if (mRecordWorldRootPos && i == root_id)
             {
                 if (flip_stance)
                 {
                     curr_pos = cMathUtil::QuatRotVec(origin_quat, curr_pos);
                     curr_pos[2] = -curr_pos[2];
                     curr_pos = cMathUtil::QuatRotVec(mirror_inv_origin_quat, curr_pos);
                 }
             }
             else
             {
                 curr_pos[3] = 1;
                 curr_pos = origin_trans * curr_pos;
                 curr_pos -= root_pos_rel;
                 curr_pos[3] = 0;
             }
             out_pose.segment(idx, pos_dim) = curr_pos.segment(0, pos_dim);
             idx += pos_dim;
             tQuaternion curr_quat = curr_part->GetRotation();
             if (mRecordWorldRootRot && i == root_id)
             {
                 if (flip_stance)
                 {
                     curr_quat = origin_quat * curr_quat;
                     curr_quat = cMathUtil::MirrorQuaternion(curr_quat, cMathUtil::eAxisZ);
                     curr_quat = mirror_inv_origin_quat * curr_quat;
                 }
             }
             else
             {
                 curr_quat = origin_quat * curr_quat;
                 if (flip_stance)
                 {
                     curr_quat = cMathUtil::MirrorQuaternion(curr_quat, cMathUtil::eAxisZ);
                 }
             }
             if (curr_quat.w() < 0)
             {
                 curr_quat.w() *= -1;
                 curr_quat.x() *= -1;
                 curr_quat.y() *= -1;
                 curr_quat.z() *= -1;
             }
             out_pose.segment(idx, rot_dim) = cMathUtil::QuatToVec(curr_quat).segment(0, rot_dim);
             idx += rot_dim;
         }
     }
 }
References cCharacter::BuildOriginTrans(), cMathUtil::eAxisZ, FlipStance(), cSimCharacter::GetBodyPart(), cSimCharacter::GetNumBodyParts(), GetPosFeatureDim(), cCharacter::GetRootID(), cSimCharacter::GetRootPos(), GetRotFeatureDim(), GetStatePoseSize(), cSimCharacter::IsValidBodyPart(), cController::mChar, cMathUtil::MirrorQuaternion(), mRecordWorldRootPos, mRecordWorldRootRot, cMathUtil::QuatRotVec(), cMathUtil::QuatToVec(), RetargetJointID(), and cMathUtil::RotMatToQuaternion().
BuildStateVel()
void cCtController::BuildStateVel (Eigen::VectorXd & out_vel) const protected virtual
Reimplemented from cDeepMimicCharController.
Definition at line 458 of file CtController.cpp.
 {
     int num_parts = mChar->GetNumBodyParts();
     tMatrix origin_trans = mChar->BuildOriginTrans();
     tQuaternion origin_quat = cMathUtil::RotMatToQuaternion(origin_trans);
     bool flip_stance = FlipStance();
     if (flip_stance)
     {
         origin_trans.row(2) *= -1; // reflect z
     }
     int pos_dim = GetPosFeatureDim();
     int rot_dim = GetRotFeatureDim();
     out_vel = Eigen::VectorXd::Zero(GetStateVelSize());
     tQuaternion mirror_inv_origin_quat = origin_quat.conjugate();
     mirror_inv_origin_quat = cMathUtil::MirrorQuaternion(mirror_inv_origin_quat, cMathUtil::eAxisZ);
     int idx = 0;
     for (int i = 0; i < num_parts; ++i)
     {
         int part_id = RetargetJointID(i);
         int root_id = mChar->GetRootID();
         const auto& curr_part = mChar->GetBodyPart(part_id);
         tVector curr_vel = curr_part->GetLinearVelocity();
         if (mRecordWorldRootRot && i == root_id)
         {
             if (flip_stance)
             {
                 curr_vel = cMathUtil::QuatRotVec(origin_quat, curr_vel);
                 curr_vel[2] = -curr_vel[2];
                 curr_vel = cMathUtil::QuatRotVec(mirror_inv_origin_quat, curr_vel);
             }
         }
         else
         {
             curr_vel = origin_trans * curr_vel;
         }
         out_vel.segment(idx, pos_dim) = curr_vel.segment(0, pos_dim);
         idx += pos_dim;
         tVector curr_ang_vel = curr_part->GetAngularVelocity();
         if (mRecordWorldRootRot && i == root_id)
         {
             if (flip_stance)
             {
                 curr_ang_vel = cMathUtil::QuatRotVec(origin_quat, curr_ang_vel);
                 curr_ang_vel[2] = -curr_ang_vel[2];
                 curr_ang_vel = -curr_ang_vel;
                 curr_ang_vel = cMathUtil::QuatRotVec(mirror_inv_origin_quat, curr_ang_vel);
             }
         }
         else
         {
             curr_ang_vel = origin_trans * curr_ang_vel;
             if (flip_stance)
             {
                 curr_ang_vel = -curr_ang_vel;
             }
         }
         out_vel.segment(idx, rot_dim - 1) = curr_ang_vel.segment(0, rot_dim - 1);
         idx += rot_dim - 1;
     }
 }
References cCharacter::BuildOriginTrans(), cMathUtil::eAxisZ, FlipStance(), cSimCharacter::GetBodyPart(), cSimCharacter::GetNumBodyParts(), GetPosFeatureDim(), cCharacter::GetRootID(), GetRotFeatureDim(), GetStateVelSize(), cController::mChar, cMathUtil::MirrorQuaternion(), mRecordWorldRootRot, cMathUtil::QuatRotVec(), RetargetJointID(), and cMathUtil::RotMatToQuaternion().
CheckNeedNewAction()
bool cCtController::CheckNeedNewAction (double timestep) const protected virtual
Reimplemented from cDeepMimicCharController.
Definition at line 216 of file CtController.cpp.
 {
     double curr_time = mTime;
     curr_time += mInitTimeOffset;
     bool new_action = cMathUtil::CheckNextInterval(timestep, curr_time, 1 / mUpdateRate);
     return new_action;
 }
References cMathUtil::CheckNextInterval(), mInitTimeOffset, cDeepMimicCharController::mTime, and mUpdateRate.
FlipStance()
bool cCtController::FlipStance () const protected virtual
Definition at line 548 of file CtController.cpp.
 {
     return false;
 }
Referenced by BuildStatePose(), BuildStateVel(), and cCtPDController::ConvertActionToTargetPose().
GetActionCtrlOffset()
int cCtController::GetActionCtrlOffset () const protected virtual
Definition at line 346 of file CtController.cpp.
 {
     return GetActionPhaseSize();
 }
References GetActionPhaseSize().
Referenced by cCtVelController::ApplyAction(), BuildActionBounds(), BuildActionOffsetScale(), cCtPDController::SetPDTargets(), and UpdateBuildTau().
GetActionCtrlSize()
int cCtController::GetActionCtrlSize () const protected virtual
Definition at line 351 of file CtController.cpp.
 {
     int ctrl_size = mChar->GetNumDof();
     int root_size = mChar->GetParamSize(mChar->GetRootID());
     ctrl_size -= root_size;
     return ctrl_size;
 }
References cCharacter::GetNumDof(), cCharacter::GetParamSize(), cCharacter::GetRootID(), and cController::mChar.
Referenced by GetActionSize().
GetActionPhaseOffset()
int cCtController::GetActionPhaseOffset () const protected virtual
Definition at line 336 of file CtController.cpp.
 {
     return 0;
 }
Referenced by BuildActionBounds(), BuildActionOffsetScale(), and GetPhaseRate().
GetActionPhaseSize()
int cCtController::GetActionPhaseSize () const protected virtual
Definition at line 341 of file CtController.cpp.
 {
     return (mEnablePhaseAction) ? 1 : 0;
 }
References mEnablePhaseAction.
Referenced by GetActionCtrlOffset(), and GetActionSize().
GetActionSize()
int cCtController::GetActionSize () const virtual
Reimplemented from cCharController.
Definition at line 64 of file CtController.cpp.
 {
     int a_size = 0;
     a_size += GetActionPhaseSize();
     a_size += GetActionCtrlSize();
     return a_size;
 }
References GetActionCtrlSize(), and GetActionPhaseSize().
Referenced by BuildActionBounds(), and BuildActionOffsetScale().
GetCyclePeriod()
double cCtController::GetCyclePeriod () const virtual
Definition at line 151 of file CtController.cpp.
 {
     return mCyclePeriod;
 }
References mCyclePeriod.
GetName()
std::string cCtController::GetName () const virtual
Implements cCharController.
Reimplemented in cCtPDController, and cCtVelController.
Definition at line 299 of file CtController.cpp.
 {
     return "ct";
 }
GetPhase()
double cCtController::GetPhase () const virtual
Definition at line 169 of file CtController.cpp.
 {
     double phase = mTime / mCyclePeriod;
     phase += mPhaseOffset;
     phase = std::fmod(phase, 1.0);
     phase = (phase < 0) ? (1 + phase) : phase;
     return phase;
 }
References mCyclePeriod, mPhaseOffset, and cDeepMimicCharController::mTime.
Referenced by BuildStatePhase().
GetPhaseRate()
double cCtController::GetPhaseRate () const protected virtual
Definition at line 558 of file CtController.cpp.
 {
     assert(mEnablePhaseAction);
     double phase_rate = 0;
     if (mEnablePhaseAction)
     {
         int phase_offset = GetActionPhaseOffset();
         phase_rate = mAction[phase_offset];
     }
     return phase_rate;
 }
References GetActionPhaseOffset(), cDeepMimicCharController::mAction, and mEnablePhaseAction.
Referenced by UpdateCalcTau().
GetPosFeatureDim()
int cCtController::GetPosFeatureDim () const protected virtual
Definition at line 139 of file CtController.cpp.
 {
     int pos_dim = cKinTree::gPosDim;
     return pos_dim;
 }
References cKinTree::gPosDim.
Referenced by BuildStatePose(), BuildStateVel(), GetStatePoseSize(), and GetStateVelSize().
GetRotFeatureDim()
int cCtController::GetRotFeatureDim () const protected virtual
Definition at line 145 of file CtController.cpp.
 {
     int rot_dim = cKinTree::gRotDim;
     return rot_dim;
 }
References cKinTree::gRotDim.
Referenced by BuildStatePose(), BuildStateVel(), GetStatePoseSize(), and GetStateVelSize().
GetStatePhaseOffset()
int cCtController::GetStatePhaseOffset () const protected virtual
Definition at line 331 of file CtController.cpp.
 {
     return 0;
 }
Referenced by BuildStateNormGroups(), BuildStateOffsetScale(), and RecordState().
GetStatePhaseSize()
int cCtController::GetStatePhaseSize () const protected virtual
Definition at line 326 of file CtController.cpp.
 {
     return (mEnablePhaseInput) ? 1 : 0;
 }
References mEnablePhaseInput.
Referenced by BuildStateNormGroups(), BuildStateOffsetScale(), BuildStatePhase(), BuildStatePhaseOffsetScale(), GetStatePoseOffset(), GetStateSize(), and RecordState().
GetStatePoseOffset()
int cCtController::GetStatePoseOffset () const protected virtual
Reimplemented from cDeepMimicCharController.
Definition at line 321 of file CtController.cpp.
 {
     return cDeepMimicCharController::GetStatePoseOffset() + GetStatePhaseSize();
 }
References GetStatePhaseSize(), and cDeepMimicCharController::GetStatePoseOffset().
GetStatePoseSize()
int cCtController::GetStatePoseSize () const protected virtual
Reimplemented from cDeepMimicCharController.
Definition at line 304 of file CtController.cpp.
 {
     int pos_dim = GetPosFeatureDim();
     int rot_dim = GetRotFeatureDim();
     int size = mChar->GetNumBodyParts() * (pos_dim + rot_dim) + 1; // +1 for root y
     return size;
 }
References cSimCharacter::GetNumBodyParts(), GetPosFeatureDim(), GetRotFeatureDim(), and cController::mChar.
Referenced by BuildStatePose().
GetStateSize()
int cCtController::GetStateSize () const virtual
Reimplemented from cDeepMimicCharController.
Definition at line 57 of file CtController.cpp.
 {
     int state_size = cDeepMimicCharController::GetStateSize();
     state_size += GetStatePhaseSize();
     return state_size;
 }
References GetStatePhaseSize(), and cDeepMimicCharController::GetStateSize().
GetStateVelSize()
int cCtController::GetStateVelSize () const protected virtual
Reimplemented from cDeepMimicCharController.
Definition at line 313 of file CtController.cpp.
 {
     int pos_dim = GetPosFeatureDim();
     int rot_dim = GetRotFeatureDim();
     int size = mChar->GetNumBodyParts() * (pos_dim + rot_dim - 1);
     return size;
 }
References cSimCharacter::GetNumBodyParts(), GetPosFeatureDim(), GetRotFeatureDim(), and cController::mChar.
Referenced by BuildStateVel().
GetUpdateRate()
double cCtController::GetUpdateRate () const virtual
Definition at line 29 of file CtController.cpp.
 {
     return mUpdateRate;
 }
References mUpdateRate.
NewActionUpdate()
void cCtController::NewActionUpdate () protected virtual
Reimplemented from cDeepMimicCharController.
Definition at line 224 of file CtController.cpp.
 {
     cDeepMimicCharController::NewActionUpdate();
 }
References cDeepMimicCharController::NewActionUpdate().
ParseParams()
bool cCtController::ParseParams (const Json::Value & json) protected virtual
Reimplemented from cDeepMimicCharController.
Reimplemented in cCtPDController.
Definition at line 178 of file CtController.cpp.
 {
     bool succ = cDeepMimicCharController::ParseParams(json);
     mUpdateRate = json.get("QueryRate", mUpdateRate).asDouble();
     mCyclePeriod = json.get("CyclePeriod", mCyclePeriod).asDouble();
     mEnablePhaseInput = json.get("EnablePhaseInput", mEnablePhaseInput).asBool();
     mEnablePhaseAction = json.get("EnablePhaseAction", mEnablePhaseAction).asBool();
     mRecordWorldRootPos = json.get("RecordWorldRootPos", mRecordWorldRootPos).asBool();
     mRecordWorldRootRot = json.get("RecordWorldRootRot", mRecordWorldRootRot).asBool();
     return succ;
 }
References Json::Value::asBool(), Json::Value::asDouble(), Json::Value::get(), mCyclePeriod, mEnablePhaseAction, mEnablePhaseInput, mRecordWorldRootPos, mRecordWorldRootRot, mUpdateRate, and cDeepMimicCharController::ParseParams().
Referenced by cCtPDController::ParseParams().
RecordState()
void cCtController::RecordState (Eigen::VectorXd & out_state) virtual
Reimplemented from cDeepMimicCharController.
Definition at line 285 of file CtController.cpp.
 {
     Eigen::VectorXd phase_state;
     cDeepMimicCharController::RecordState(out_state);
     if (mEnablePhaseInput)
     {
         int phase_offset = GetStatePhaseOffset();
         int phase_size = GetStatePhaseSize();
         BuildStatePhase(phase_state);
         out_state.segment(phase_offset, phase_size) = phase_state;
     }
 }
References BuildStatePhase(), GetStatePhaseOffset(), GetStatePhaseSize(), mEnablePhaseInput, and cDeepMimicCharController::RecordState().
ResetParams()
void cCtController::ResetParams () protected virtual
Reimplemented from cDeepMimicCharController.
Definition at line 132 of file CtController.cpp.
 {
     cDeepMimicCharController::ResetParams();
     mPhaseOffset = 0;
     mInitTimeOffset = 0;
 }
References mInitTimeOffset, mPhaseOffset, and cDeepMimicCharController::ResetParams().
RetargetJointID()
int cCtController::RetargetJointID (int joint_id) const protected virtual
Definition at line 553 of file CtController.cpp.
 {
     return joint_id;
 }
Referenced by BuildStatePose(), BuildStateVel(), cCtPDController::SetPDTargets(), and UpdateBuildTau().
SetCyclePeriod()
void cCtController::SetCyclePeriod (double period) virtual
Definition at line 156 of file CtController.cpp.
 {
     mCyclePeriod = period;
 }
References mCyclePeriod.
SetInitTime()
void cCtController::SetInitTime (double time) virtual
Definition at line 161 of file CtController.cpp.
 {
     mTime = time;
     mPrevActionTime = time;
     mPhaseOffset = 0;
     mInitTimeOffset = -mTime;
 }
References mInitTimeOffset, mPhaseOffset, cDeepMimicCharController::mPrevActionTime, and cDeepMimicCharController::mTime.
SetUpdateRate()
void cCtController::SetUpdateRate (double rate) virtual
Definition at line 24 of file CtController.cpp.
 {
     mUpdateRate = rate;
 }
References mUpdateRate.
UpdateBuildTau()
void cCtController::UpdateBuildTau (double time_step, Eigen::VectorXd & out_tau) protected virtual
Reimplemented in cCtPDController.
Definition at line 192 of file CtController.cpp.
 {
     out_tau = Eigen::VectorXd::Zero(mChar->GetNumDof());
     int root_id = mChar->GetRootID();
     int root_size = mChar->GetParamSize(root_id);
     int num_joints = mChar->GetNumJoints();
     int ctrl_offset = GetActionCtrlOffset();
     for (int j = root_id + 1; j < num_joints; ++j)
     {
         int retarget_joint = RetargetJointID(j);
         int param_offset = mChar->GetParamOffset(j);
         int param_size = mChar->GetParamSize(j);
         int retarget_offset = mChar->GetParamOffset(retarget_joint);
         int retarget_size = mChar->GetParamSize(retarget_joint);
         assert(param_size == retarget_size);
         retarget_offset -= root_size;
         retarget_offset += ctrl_offset;
         out_tau.segment(param_offset, param_size) = mAction.segment(retarget_offset, retarget_size);
     }
 }
References GetActionCtrlOffset(), cCharacter::GetNumDof(), cCharacter::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), cCharacter::GetRootID(), cDeepMimicCharController::mAction, cController::mChar, and RetargetJointID().
Referenced by UpdateCalcTau().
UpdateCalcTau()
void cCtController::UpdateCalcTau (double timestep, Eigen::VectorXd & out_tau) virtual
Reimplemented from cDeepMimicCharController.
Definition at line 34 of file CtController.cpp.
 {
     // use unnormalized phase
     double prev_phase = 0;
     if (mEnablePhaseAction)
     {
         prev_phase = mTime / mCyclePeriod;
         prev_phase += mPhaseOffset;
     }
     cDeepMimicCharController::UpdateCalcTau(timestep, out_tau);
     if (mEnablePhaseAction)
     {
         double phase_rate = GetPhaseRate();
         double tar_phase = prev_phase + timestep * phase_rate;
         mPhaseOffset = tar_phase - mTime / mCyclePeriod;
         mPhaseOffset = std::fmod(mPhaseOffset, 1.0);
     }
     UpdateBuildTau(timestep, out_tau);
 }
References GetPhaseRate(), mCyclePeriod, mEnablePhaseAction, mPhaseOffset, cDeepMimicCharController::mTime, UpdateBuildTau(), and cDeepMimicCharController::UpdateCalcTau().
Member Data Documentation
mActionBoundMax
Eigen::VectorXd cCtController::mActionBoundMax protected
Definition at line 49 of file CtController.h.
mActionBoundMin
Eigen::VectorXd cCtController::mActionBoundMin protected
Definition at line 48 of file CtController.h.
mCyclePeriod
double cCtController::mCyclePeriod protected
Definition at line 39 of file CtController.h.
Referenced by BuildActionOffsetScale(), cCtController(), GetCyclePeriod(), GetPhase(), ParseParams(), SetCyclePeriod(), and UpdateCalcTau().
mEnablePhaseAction
bool cCtController::mEnablePhaseAction protected
Definition at line 41 of file CtController.h.
Referenced by BuildActionBounds(), BuildActionOffsetScale(), cCtController(), GetActionPhaseSize(), GetPhaseRate(), ParseParams(), and UpdateCalcTau().
mEnablePhaseInput
bool cCtController::mEnablePhaseInput protected
Definition at line 40 of file CtController.h.
Referenced by BuildStateNormGroups(), BuildStateOffsetScale(), cCtController(), GetStatePhaseSize(), ParseParams(), and RecordState().
mInitTimeOffset
double cCtController::mInitTimeOffset protected
Definition at line 46 of file CtController.h.
Referenced by cCtController(), CheckNeedNewAction(), ResetParams(), and SetInitTime().
mPhaseOffset
double cCtController::mPhaseOffset protected
Definition at line 45 of file CtController.h.
Referenced by cCtController(), GetPhase(), ResetParams(), SetInitTime(), and UpdateCalcTau().
mRecordWorldRootPos
bool cCtController::mRecordWorldRootPos protected
Definition at line 42 of file CtController.h.
Referenced by BuildStatePose(), cCtController(), and ParseParams().
mRecordWorldRootRot
bool cCtController::mRecordWorldRootRot protected
Definition at line 43 of file CtController.h.
Referenced by BuildStatePose(), BuildStateVel(), cCtController(), and ParseParams().
mUpdateRate
double cCtController::mUpdateRate protected
Definition at line 38 of file CtController.h.
Referenced by cCtController(), CheckNeedNewAction(), GetUpdateRate(), ParseParams(), and SetUpdateRate().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/CtController.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/CtController.cpp