My Project: cGround Class Reference
cGround Class Reference
#include <Ground.h>
Classes
struct tParams
Public Types
enum eClass { eClassPlane, eClassMax, eClassInvalid }
enum eType { eTypePlane, eTypeMax }
Public Types inherited from cSimObj
enum eType { eTypeDynamic, eTypeStatic, eTypeMax }
Public Member Functions
virtual ~cGround ()
virtual void Init (const std::shared_ptr< cWorld > &world, const tParams &params)
virtual void Update (double time_elapsed, const tVector &bound_min, const tVector &bound_max)
virtual void Clear ()
virtual double SampleHeight (const tVector &pos) const
virtual double SampleHeight (const tVector &pos, bool &out_valid_sample) const
virtual void SampleHeight (const Eigen::MatrixXd &pos, Eigen::VectorXd &out_h) const
virtual void SampleHeightVel (const tVector &pos, double &out_h, tVector &out_vel, bool &out_valid_sample) const
virtual eClass GetGroundClass () const
virtual void SetBlendParams (const Eigen::VectorXd &params)
virtual void SetParamBlend (double blend)
virtual size_t GetUpdateCount () const
virtual void SeedRand (unsigned long seed)
virtual void SamplePlacement (const tVector &origin, tVector &out_pos, tQuaternion &out_rot)
virtual tVector GetSize () const
virtual double GetVertSpacingX () const
virtual double GetVertSpacingZ () const
virtual bool Output (const std::string &out_file) const
Public Member Functions inherited from cSimRigidBody
virtual ~cSimRigidBody ()
virtual void SetPos (const tVector &pos)
virtual void SetRotation (const tVector &axis, double theta)
virtual void SetRotation (const tQuaternion &q)
virtual tVector GetLinearVelocity () const
virtual tVector GetLinearVelocity (const tVector &local_pos) const
virtual void SetLinearVelocity (const tVector &vel)
virtual tVector GetAngularVelocity () const
virtual void SetAngularVelocity (const tVector &vel)
virtual void SetDamping (double linear_damping, double angular_damping)
virtual double GetMass () const
virtual void ApplyForce (const tVector &force)
virtual void ApplyForce (const tVector &force, const tVector &local_pos)
virtual void ApplyTorque (const tVector &torque)
virtual void ClearForces ()
virtual void SetKinematicObject (bool is_kin)
virtual bool IsKinematicObject () const
virtual void DisableDeactivation ()
virtual void Constrain (const tVector &linear_factor, const tVector &angular_factor)
virtual bool HasSimBody () const
virtual const std::unique_ptr< btRigidBody > & GetSimBody () const
Public Member Functions inherited from cSimObj
virtual ~cSimObj ()
virtual tVector GetPos () const
virtual void GetRotation (tVector &out_axis, double &out_theta) const
virtual tQuaternion GetRotation () const
virtual tMatrix GetWorldTransform () const
virtual tMatrix GetLocalTransform () const
virtual tVector WorldToLocalPos (const tVector &world_pos) const
virtual tVector LocalToWorldPos (const tVector &local_pos) const
virtual tMatrix3 GetLocalToWorldRotMat () const
virtual tVector CalcCOM () const
virtual tVector CalcCOMVel () const
virtual void RegisterContact ()
virtual void RegisterContact (int contact_flags, int filter_flags)
virtual void UpdateContact (int contact_flags, int filter_flags)
virtual const cContactManager::tContactHandle & GetContactHandle () const
virtual bool IsInContact () const
virtual const tEigenArr< cContactManager::tContactPt > & GetContactPts () const
virtual short GetColGroup () const
virtual void SetColGroup (short col_group)
virtual short GetColMask () const
virtual void SetColMask (short col_mask)
virtual eType GetType () const
virtual cShape::eShape GetShape () const
virtual void CalcAABB (tVector &out_min, tVector &out_max) const
virtual const btCollisionShape * GetCollisionShape () const
Static Public Member Functions
static eClass GetClassFromType (eType ground_type)
static void ParseType (const std::string &str, eType &out_type)
Static Public Attributes
static const std::string gTypeKey = "Type"
static const std::string gGroundWidthKey = "GroundWidth"
static const std::string gVertSpacingXKey = "VertSpacingX"
static const std::string gVertSpacingZKey = "VertSpacingZ"
static const std::string gParamsKey = "Params"
Protected Member Functions
cGround ()
virtual void SetupRandGen ()
virtual void CalcBlendParams (double blend, Eigen::VectorXd &out_params) const
virtual int GetNumParamSets () const
virtual int GetBlendParamSize () const
virtual void FlagUpdate ()
Protected Member Functions inherited from cSimRigidBody
cSimRigidBody ()
virtual void Init (const std::shared_ptr< cWorld > &world)
virtual void AddToWorld (const std::shared_ptr< cWorld > &world)
virtual void RemoveFromWorld ()
virtual const btCollisionObject * GetCollisionObject () const
virtual btCollisionObject * GetCollisionObject ()
virtual int GetNumConstraints () const
virtual cWorld::tConstraintHandle GetConstraint (int c) const
Protected Member Functions inherited from cSimObj
cSimObj ()
virtual const std::shared_ptr< cWorld > & GetWorld () const
Protected Attributes
cRand mRand
tParams mParams
Eigen::VectorXd mBlendParams
size_t mUpdateCount
double mTime
Protected Attributes inherited from cSimRigidBody
std::unique_ptr< btRigidBody > mSimBody
Protected Attributes inherited from cSimObj
std::shared_ptr< cWorld > mWorld
std::unique_ptr< btCollisionShape > mColShape
cContactManager::tContactHandle mContactHandle
bool mEnableContactFall
eType mType
short mColGroup
short mColMask
Detailed Description
Definition at line 5 of file Ground.h.
Member Enumeration Documentation
eClass
enum cGround::eClass
Enumerator
eClassPlane
eClassMax
eClassInvalid
Definition at line 10 of file Ground.h.
     {
         eClassPlane,
         eClassMax,
         eClassInvalid
     };
eType
enum cGround::eType
Enumerator
eTypePlane
eTypeMax
Definition at line 17 of file Ground.h.
     {
         eTypePlane,
         eTypeMax
     };
Constructor & Destructor Documentation
~cGround()
cGround::~cGround () virtual
Definition at line 73 of file Ground.cpp.
 {
 }
cGround()
cGround::cGround () protected
Definition at line 66 of file Ground.cpp.
 {
     SeedRand(cMathUtil::RandUint());
     mType = eTypeStatic;
     mUpdateCount = 0;
 }
References cSimObj::eTypeStatic, cSimObj::mType, mUpdateCount, cMathUtil::RandUint(), and SeedRand().
Member Function Documentation
CalcBlendParams()
void cGround::CalcBlendParams (double blend, Eigen::VectorXd & out_params) const protected virtual
Definition at line 189 of file Ground.cpp.
 {
     int num_params = GetNumParamSets();
     if (num_params > 0)
     {
         blend = cMathUtil::Clamp(blend, 0.0, num_params - 1.0);
         int idx0 = static_cast<int>(blend);
         int idx1 = std::min(idx0 + 1, num_params - 1);
         blend -= idx0;
         auto params0 = mParams.mParamArr.row(idx0);
         auto params1 = mParams.mParamArr.row(idx1);
         int blend_param_size = GetBlendParamSize();
         assert(params0.size() == blend_param_size);
         assert(params1.size() == blend_param_size);
         Eigen::VectorXd blend_params = (1 - blend) * params0 + blend * params1;
         out_params = blend_params;
     }
 }
References cMathUtil::Clamp(), GetBlendParamSize(), GetNumParamSets(), cGround::tParams::mParamArr, and mParams.
Referenced by SetParamBlend().
Clear()
void cGround::Clear () virtual
Reimplemented in cGroundPlane.
Definition at line 95 of file Ground.cpp.
 {
     mUpdateCount = 0;
     mTime = 0;
 }
References mTime, and mUpdateCount.
Referenced by cGroundPlane::Clear().
FlagUpdate()
void cGround::FlagUpdate () protected virtual
Definition at line 223 of file Ground.cpp.
 {
     ++mUpdateCount;
 }
References mUpdateCount.
Referenced by Init(), and cGroundPlane::Update().
GetBlendParamSize()
int cGround::GetBlendParamSize () const protected virtual
Definition at line 218 of file Ground.cpp.
 {
     return 0;
 }
Referenced by CalcBlendParams(), and SetBlendParams().
GetClassFromType()
cGround::eClass cGround::GetClassFromType (eType ground_type) static
Definition at line 29 of file Ground.cpp.
 {
     eClass ground_class = eClassInvalid;
     switch (ground_type)
     {
         case eTypePlane:
             ground_class = eClassPlane;
             break;
         default:
             ground_class = eClassInvalid;
             break;
     }
     return ground_class;
 }
References eClassInvalid, eClassPlane, and eTypePlane.
Referenced by cGroundBuilder::BuildGround(), and cGroundBuilder::ParseParamsJason().
GetGroundClass()
cGround::eClass cGround::GetGroundClass () const virtual
Reimplemented in cGroundPlane.
Definition at line 126 of file Ground.cpp.
 {
     return eClassInvalid;
 }
References eClassInvalid.
Referenced by cDrawGround::BuildMesh().
GetNumParamSets()
int cGround::GetNumParamSets () const protected virtual
Definition at line 213 of file Ground.cpp.
 {
     return static_cast<int>(mParams.mParamArr.rows());
 }
References cGround::tParams::mParamArr, and mParams.
Referenced by CalcBlendParams().
GetSize()
tVector cGround::GetSize () const virtual
Implements cSimObj.
Definition at line 161 of file Ground.cpp.
 {
     return tVector::Zero();
 }
GetUpdateCount()
size_t cGround::GetUpdateCount () const virtual
Definition at line 144 of file Ground.cpp.
 {
     return mUpdateCount;
 }
References mUpdateCount.
GetVertSpacingX()
double cGround::GetVertSpacingX () const virtual
Definition at line 166 of file Ground.cpp.
 {
     return mParams.mVertSpacingX;
 }
References mParams, and cGround::tParams::mVertSpacingX.
GetVertSpacingZ()
double cGround::GetVertSpacingZ () const virtual
Definition at line 171 of file Ground.cpp.
 {
     return mParams.mVertSpacingZ;
 }
References mParams, and cGround::tParams::mVertSpacingZ.
Init()
void cGround::Init (const std::shared_ptr< cWorld > & world, const tParams & params) virtual
Reimplemented in cGroundPlane.
Definition at line 77 of file Ground.cpp.
 {
     mParams = params;
     SetupRandGen();
     cSimRigidBody::Init(world);
     UpdateContact(cWorld::eContactFlagEnvironment, cWorld::eContactFlagAll);
     SetParamBlend(params.mBlend);
     mUpdateCount = 0;
     mTime = 0;
     FlagUpdate();
 }
References cWorld::eContactFlagAll, cWorld::eContactFlagEnvironment, FlagUpdate(), cSimRigidBody::Init(), cGround::tParams::mBlend, mParams, mTime, mUpdateCount, SetParamBlend(), SetupRandGen(), and cSimObj::UpdateContact().
Referenced by cGroundPlane::Init().
Output()
bool cGround::Output (const std::string & out_file) const virtual
Definition at line 176 of file Ground.cpp.
 {
     return false;
 }
ParseType()
void cGround::ParseType (const std::string & str, eType & out_type) static
Definition at line 44 of file Ground.cpp.
 {
     bool valid = false;
     for (int i = 0; i < eTypeMax; ++i)
     {
         const std::string& curr_name = gGroundTypeNames[i];
         if (curr_name == str)
         {
             out_type = static_cast<eType>(i);
             valid = true;
             break;
         }
     }
     if (!valid)
     {
         printf("Invalid ground Type%s\n", str.c_str());
         assert(false);
     }
 }
References eTypeMax, and gGroundTypeNames.
Referenced by cGroundBuilder::ParseParamsJson().
SampleHeight() [1/3]
void cGround::SampleHeight (const Eigen::MatrixXd & pos, Eigen::VectorXd & out_h) const virtual
Reimplemented in cGroundPlane.
Definition at line 113 of file Ground.cpp.
 {
     int num_pos = static_cast<int>(pos.rows());
     out_h = Eigen::VectorXd::Zero(num_pos);
 }
SampleHeight() [2/3]
double cGround::SampleHeight (const tVector & pos) const virtual
Reimplemented in cGroundPlane.
Definition at line 101 of file Ground.cpp.
 {
     bool dummy_valid = true;
     return SampleHeight(pos, dummy_valid);
 }
Referenced by cGroundPlane::SampleHeight(), SampleHeightVel(), and SamplePlacement().
SampleHeight() [3/3]
double cGround::SampleHeight (const tVector & pos, bool & out_valid_sample) const virtual
Reimplemented in cGroundPlane.
Definition at line 107 of file Ground.cpp.
 {
     out_valid_sample = true;
     return 0;
 }
SampleHeightVel()
void cGround::SampleHeightVel (const tVector & pos, double & out_h, tVector & out_vel, bool & out_valid_sample) const virtual
Definition at line 119 of file Ground.cpp.
 {
     out_h = SampleHeight(pos, out_valid_sample);
     out_vel.setZero();
 }
References SampleHeight().
SamplePlacement()
void cGround::SamplePlacement (const tVector & origin, tVector & out_pos, tQuaternion & out_rot) virtual
Definition at line 154 of file Ground.cpp.
 {
     out_pos.setZero();
     out_pos[1] = SampleHeight(out_pos);
     out_rot.setIdentity();
 }
References SampleHeight().
SeedRand()
void cGround::SeedRand (unsigned long seed) virtual
Definition at line 149 of file Ground.cpp.
 {
     mRand.Seed(seed);
 }
References mRand, and cRand::Seed().
Referenced by cGround(), and SetupRandGen().
SetBlendParams()
void cGround::SetBlendParams (const Eigen::VectorXd & params) virtual
Definition at line 131 of file Ground.cpp.
 {
     int blend_param_size = GetBlendParamSize();
     assert(params.size() == blend_param_size);
     mBlendParams = params;
 }
References GetBlendParamSize(), and mBlendParams.
SetParamBlend()
void cGround::SetParamBlend (double blend) virtual
Definition at line 138 of file Ground.cpp.
 {
     mParams.mBlend = blend;
     CalcBlendParams(blend, mBlendParams);
 }
References CalcBlendParams(), cGround::tParams::mBlend, mBlendParams, and mParams.
Referenced by Init().
SetupRandGen()
void cGround::SetupRandGen () protected virtual
Definition at line 181 of file Ground.cpp.
 {
     if (mParams.mHasRandSeed)
     {
         SeedRand(mParams.mRandSeed);
     }
 }
References cGround::tParams::mHasRandSeed, mParams, cGround::tParams::mRandSeed, and SeedRand().
Referenced by Init().
Update()
void cGround::Update (double time_elapsed, const tVector & bound_min, const tVector & bound_max) virtual
Reimplemented in cGroundPlane.
Definition at line 90 of file Ground.cpp.
 {
     mTime += time_elapsed;
 }
References mTime.
Referenced by cGroundPlane::Update().
Member Data Documentation
gGroundWidthKey
const std::string cGround::gGroundWidthKey = "GroundWidth" static
Definition at line 45 of file Ground.h.
Referenced by cGroundBuilder::ParseParamsJson().
gParamsKey
const std::string cGround::gParamsKey = "Params" static
Definition at line 48 of file Ground.h.
Referenced by cGroundBuilder::ParseParamsJson().
gTypeKey
const std::string cGround::gTypeKey = "Type" static
Definition at line 44 of file Ground.h.
Referenced by cGroundBuilder::ParseParamsJson().
gVertSpacingXKey
const std::string cGround::gVertSpacingXKey = "VertSpacingX" static
Definition at line 46 of file Ground.h.
Referenced by cGroundBuilder::ParseParamsJson().
gVertSpacingZKey
const std::string cGround::gVertSpacingZKey = "VertSpacingZ" static
Definition at line 47 of file Ground.h.
Referenced by cGroundBuilder::ParseParamsJson().
mBlendParams
Eigen::VectorXd cGround::mBlendParams protected
Definition at line 82 of file Ground.h.
Referenced by SetBlendParams(), and SetParamBlend().
mParams
tParams cGround::mParams protected
Definition at line 81 of file Ground.h.
Referenced by CalcBlendParams(), GetNumParamSets(), GetVertSpacingX(), GetVertSpacingZ(), cGroundPlane::Init(), Init(), SetParamBlend(), and SetupRandGen().
mRand
cRand cGround::mRand protected
Definition at line 80 of file Ground.h.
Referenced by SeedRand().
mTime
double cGround::mTime protected
Definition at line 84 of file Ground.h.
Referenced by Clear(), Init(), and Update().
mUpdateCount
size_t cGround::mUpdateCount protected
Definition at line 83 of file Ground.h.
Referenced by cGround(), Clear(), FlagUpdate(), GetUpdateCount(), and Init().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/Ground.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/Ground.cpp