My Project: cShader Class Reference
cShader Class Reference
#include <Shader.h>
Classes
struct tShaderEntry
Public Types
enum eUniform { eUniformModelViewMatrix, eUniformProjectionMatrix, eUniformColor, eUniformMax }
Public Member Functions
cShader (void)
~cShader (void)
virtual void Clear ()
virtual bool BuildShader (const std::string &vs_filename, const std::string &ps_filename)
virtual void GetAttributeHandle (GLuint &attribute_handle, const std::string &attribute_name)
virtual void GetUniformHandle (GLuint &uniform_handle, const std::string &uniform_name, bool check_valid=false)
virtual void Bind () const
virtual void Unbind () const
virtual void SetUniform2 (GLuint handle, const tVector &data) const
virtual void SetUniform3 (GLuint handle, const tVector &data) const
virtual void SetUniform4 (GLuint handle, const tVector &data) const
virtual void SetUniformMat (GLuint handle, const tMatrix &data) const
virtual bool HasUniform (eUniform unif) const
virtual void SetUniform4 (eUniform unif, const tVector &data) const
virtual void SetUniformMat (eUniform unif, const tMatrix &data) const
virtual bool CheckBoundShader () const
virtual GLuint GetProg () const
Static Public Member Functions
static const cShader * GetBoundShader ()
Protected Member Functions
virtual GLuint LoadShader (const std::string &filename, GLenum shader_type)
virtual GLuint CreateShader (GLuint &vsh_handle, GLuint &psh_handle)
virtual void RecordUniformHandles ()
virtual void PushShaderStack () const
virtual void PopShaderStack () const
Protected Attributes
GLuint mProg
GLuint mUniformHandles [eUniformMax]
Static Protected Attributes
static std::stack< tShaderEntry > gShaderStack = std::stack<tShaderEntry>()
Detailed Description
Definition at line 11 of file Shader.h.
Member Enumeration Documentation
eUniform
enum cShader::eUniform
Enumerator
eUniformModelViewMatrix
eUniformProjectionMatrix
eUniformColor
eUniformMax
Definition at line 14 of file Shader.h.
     {
         eUniformModelViewMatrix,
         eUniformProjectionMatrix,
         eUniformColor,
         eUniformMax
     };
Constructor & Destructor Documentation
cShader()
cShader::cShader (void)
Definition at line 29 of file Shader.cpp.
 {
     mProg = gInvalidIdx;
 }
References gInvalidIdx, and mProg.
~cShader()
cShader::~cShader (void)
Definition at line 34 of file Shader.cpp.
 {
     Clear();
 }
References Clear().
Member Function Documentation
Bind()
void cShader::Bind () const virtual
Definition at line 168 of file Shader.cpp.
 {
     PushShaderStack();
 }
References PushShaderStack().
Referenced by cDrawUtil::BindCopyMeshProg(), cDrawUtil::BindDefaultProg(), and cDrawUtil::CopyTexture().
BuildShader()
bool cShader::BuildShader (const std::string & vs_filename, const std::string & ps_filename) virtual
Definition at line 48 of file Shader.cpp.
 {
     Clear();
     GLuint vs = LoadShader(vs_filename, GL_VERTEX_SHADER);
     GLuint ps = LoadShader(ps_filename, GL_FRAGMENT_SHADER);
     mProg = CreateShader(vs, ps);
     bool succ = mProg != gInvalidIdx;
     if (succ)
     {
         RecordUniformHandles();
     }
     return succ;
 }
References Clear(), CreateShader(), gInvalidIdx, LoadShader(), mProg, and RecordUniformHandles().
Referenced by cDrawUtil::BuildShaders().
CheckBoundShader()
bool cShader::CheckBoundShader () const virtual
Definition at line 229 of file Shader.cpp.
 {
     GLint prog;
     glGetIntegerv(GL_CURRENT_PROGRAM, &prog);
     return prog == mProg;
 }
References mProg.
Referenced by PopShaderStack().
Clear()
void cShader::Clear () virtual
Definition at line 39 of file Shader.cpp.
 {
     if (mProg != gInvalidIdx)
     {
         glDeleteProgram(mProg);
         mProg = gInvalidIdx;
     }
 }
References gInvalidIdx, and mProg.
Referenced by BuildShader(), and ~cShader().
CreateShader()
GLuint cShader::CreateShader (GLuint & vsh_handle, GLuint & psh_handle) protected virtual
Definition at line 104 of file Shader.cpp.
 {
     GLuint shader_program;
     GLint valid_status;
     shader_program = glCreateProgram();
     glAttachShader(shader_program, vsh_handle);
     glAttachShader(shader_program, psh_handle);
     glLinkProgram(shader_program);
     glGetProgramiv(shader_program, GL_LINK_STATUS, &valid_status);
     // valid program
     glGetProgramiv(shader_program, GL_LINK_STATUS, &valid_status);
     if (!valid_status)
     {
         std::cout << "shader linking failed\n";
     }
     else
     {
         glValidateProgram(shader_program);
         glGetProgramiv(shader_program, GL_VALIDATE_STATUS, &valid_status);
         if (!valid_status)
         {
             std::cout << "shader validation failed\n";
         }
     }
     if (!valid_status)
     {
         shader_program = gInvalidIdx;
     }
     return shader_program;
 }
References gInvalidIdx.
Referenced by BuildShader().
GetAttributeHandle()
void cShader::GetAttributeHandle (GLuint & attribute_handle, const std::string & attribute_name) virtual
Definition at line 150 of file Shader.cpp.
 {
     attribute_handle = glGetAttribLocation(mProg, attribute_name.c_str());
     if (attribute_handle == gInvalidIdx)
     {
         std::cout << "can't find shader attribute " << attribute_name.c_str() << std::endl;
     }
 }
References gInvalidIdx, and mProg.
GetBoundShader()
const cShader * cShader::GetBoundShader () static
Definition at line 18 of file Shader.cpp.
 {
     const cShader* shader = nullptr;
     if (!gShaderStack.empty())
     {
         const tShaderEntry& prev_entry = gShaderStack.top();
         shader = prev_entry.mShader;
     }
     return shader;
 }
References gShaderStack, and cShader::tShaderEntry::mShader.
Referenced by cDrawUtil::LoadShaderUniforms().
GetProg()
GLuint cShader::GetProg () const virtual
Definition at line 236 of file Shader.cpp.
 {
     return mProg;
 }
References mProg.
Referenced by PopShaderStack().
GetUniformHandle()
void cShader::GetUniformHandle (GLuint & uniform_handle, const std::string & uniform_name, bool check_valid = false) virtual
Definition at line 159 of file Shader.cpp.
 {
     uniform_handle = glGetUniformLocation(mProg, uniform_name.c_str());
     if (check_valid && uniform_handle == gInvalidIdx)
     {
         std::cout << "can't find shader uniform parameter " << uniform_name.c_str() << std::endl;
     }
 }
References gInvalidIdx, and mProg.
Referenced by RecordUniformHandles().
HasUniform()
bool cShader::HasUniform (eUniform unif) const virtual
Definition at line 212 of file Shader.cpp.
 {
     return mUniformHandles[unif] != gInvalidIdx;
 }
References gInvalidIdx, and mUniformHandles.
Referenced by cDrawUtil::LoadShaderUniforms().
LoadShader()
GLuint cShader::LoadShader (const std::string & filename, GLenum shader_type) protected virtual
Definition at line 65 of file Shader.cpp.
 {
     GLuint shader_handle = glCreateShader(shader_type);
     //read shader file
     std::ifstream shader_file(filename.c_str());
     std::cout << "Compiling shader: " << filename.c_str() << std::endl;
     std::string shader_code((std::istreambuf_iterator<char>(shader_file)),
         (std::istreambuf_iterator<char>()));
     const char* shader_code_str = shader_code.c_str();
     glShaderSource(shader_handle, 1, &shader_code_str, NULL);
     glCompileShader(shader_handle);
     // Check the compile status
     GLint compiled;
     glGetShaderiv(shader_handle, GL_COMPILE_STATUS, &compiled);
     if (!compiled)
     {
         std::cout << "shader compilation failed: " << filename.c_str() << std::endl;
         // get log string length
         GLint max_len = 0;
         glGetShaderiv(shader_handle, GL_INFO_LOG_LENGTH, &max_len);
         char* error_log = new char[max_len];
         glGetShaderInfoLog(shader_handle, max_len, &max_len, error_log);
         std::cout << error_log << std::endl;
         delete[] error_log;
         glDeleteShader(shader_handle);
         shader_handle = gInvalidIdx;
     }
     return shader_handle;
 }
References gInvalidIdx.
Referenced by BuildShader().
PopShaderStack()
void cShader::PopShaderStack () const protected virtual
Definition at line 250 of file Shader.cpp.
 {
     bool bound = CheckBoundShader();
     if (bound)
     {
         gShaderStack.pop();
         if (!gShaderStack.empty())
         {
             const tShaderEntry& prev_entry = gShaderStack.top();
             const cShader* prev_shader = prev_entry.mShader;
             GLuint prev_prog = prev_shader->GetProg();
             glUseProgram(prev_prog);
         }
         else
         {
             glUseProgram(0);
         }
     }
     else
     {
         throw std::runtime_error("Trying to pop unbound shader from stack.\n");
     }
 }
References CheckBoundShader(), GetProg(), gShaderStack, and cShader::tShaderEntry::mShader.
Referenced by Unbind().
PushShaderStack()
void cShader::PushShaderStack () const protected virtual
Definition at line 241 of file Shader.cpp.
 {
     glUseProgram(mProg);
     tShaderEntry entry;
     entry.mShader = this;
     gShaderStack.push(entry);
 }
References gShaderStack, mProg, and cShader::tShaderEntry::mShader.
Referenced by Bind().
RecordUniformHandles()
void cShader::RecordUniformHandles () protected virtual
Definition at line 139 of file Shader.cpp.
 {
     for (int i = 0; i < eUniformMax; ++i)
     {
         const std::string& name = gUniformNames[i];
         GLuint handle = gInvalidIdx;
         GetUniformHandle(handle, name, false);
         mUniformHandles[i] = handle;
     }
 }
References eUniformMax, GetUniformHandle(), gInvalidIdx, gUniformNames, and mUniformHandles.
Referenced by BuildShader().
SetUniform2()
void cShader::SetUniform2 (GLuint handle, const tVector & data) const virtual
Definition at line 178 of file Shader.cpp.
 {
     float f_data[] = { static_cast<float>(data[0]),
                         static_cast<float>(data[1]) };
     glProgramUniform2fv(mProg, handle, 1, f_data);
 }
References mProg.
SetUniform3()
void cShader::SetUniform3 (GLuint handle, const tVector & data) const virtual
Definition at line 185 of file Shader.cpp.
 {
     float f_data[] = { static_cast<float>(data[0]),
                       static_cast<float>(data[1]),
                       static_cast<float>(data[2]) };
     glProgramUniform3fv(mProg, handle, 1, f_data);
 }
References mProg.
SetUniform4() [1/2]
void cShader::SetUniform4 (eUniform unif, const tVector & data) const virtual
Definition at line 217 of file Shader.cpp.
 {
     GLuint handle = mUniformHandles[unif];
     SetUniform4(handle, data);
 }
References mUniformHandles, and SetUniform4().
SetUniform4() [2/2]
void cShader::SetUniform4 (GLuint handle, const tVector & data) const virtual
Definition at line 193 of file Shader.cpp.
 {
     float f_data[] = { static_cast<float>(data[0]),
                       static_cast<float>(data[1]),
                       static_cast<float>(data[2]),
                       static_cast<float>(data[3]) };
     glProgramUniform4fv(mProg, handle, 1, f_data);
 }
References mProg.
Referenced by cDrawUtil::LoadShaderUniforms(), and SetUniform4().
SetUniformMat() [1/2]
void cShader::SetUniformMat (eUniform unif, const tMatrix & data) const virtual
Definition at line 223 of file Shader.cpp.
 {
     GLuint handle = mUniformHandles[unif];
     SetUniformMat(handle, data);
 }
References mUniformHandles, and SetUniformMat().
SetUniformMat() [2/2]
void cShader::SetUniformMat (GLuint handle, const tMatrix & data) const virtual
Definition at line 202 of file Shader.cpp.
 {
     float f_data[] = {
         static_cast<float>(data(0, 0)), static_cast<float>(data(1, 0)), static_cast<float>(data(2, 0)), static_cast<float>(data(3, 0)),
         static_cast<float>(data(0, 1)), static_cast<float>(data(1, 1)), static_cast<float>(data(2, 1)), static_cast<float>(data(3, 1)),
         static_cast<float>(data(0, 2)), static_cast<float>(data(1, 2)), static_cast<float>(data(2, 2)), static_cast<float>(data(3, 2)),
         static_cast<float>(data(0, 3)), static_cast<float>(data(1, 3)), static_cast<float>(data(2, 3)), static_cast<float>(data(3, 3)) };
     glProgramUniformMatrix4fv(mProg, handle, 1, false, f_data);
 }
References mProg.
Referenced by cDrawUtil::LoadShaderUniforms(), and SetUniformMat().
Unbind()
void cShader::Unbind () const virtual
Definition at line 173 of file Shader.cpp.
 {
     PopShaderStack();
 }
References PopShaderStack().
Referenced by cDrawUtil::CopyTexture(), cDrawUtil::UnbindCopyMeshProg(), and cDrawUtil::UnbindDefaultProg().
Member Data Documentation
gShaderStack
std::stack< cShader::tShaderEntry > cShader::gShaderStack = std::stack<tShaderEntry>() static protected
Definition at line 55 of file Shader.h.
Referenced by GetBoundShader(), PopShaderStack(), and PushShaderStack().
mProg
GLuint cShader::mProg protected
Definition at line 57 of file Shader.h.
Referenced by BuildShader(), CheckBoundShader(), Clear(), cShader(), GetAttributeHandle(), GetProg(), GetUniformHandle(), PushShaderStack(), SetUniform2(), SetUniform3(), SetUniform4(), and SetUniformMat().
mUniformHandles
GLuint cShader::mUniformHandles[eUniformMax] protected
Definition at line 58 of file Shader.h.
Referenced by HasUniform(), RecordUniformHandles(), SetUniform4(), and SetUniformMat().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/Shader.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/Shader.cpp