My Project: cDeepMimicCore Class Reference
cDeepMimicCore Class Reference
#include <DeepMimicCore.h>
Public Member Functions
cDeepMimicCore (bool enable_draw)
virtual ~cDeepMimicCore ()
virtual void SeedRand (int seed)
virtual void ParseArgs (const std::vector< std::string > &args)
virtual void Init ()
virtual void Update (double timestep)
virtual void Reset ()
virtual double GetTime () const
virtual std::string GetName () const
virtual bool EnableDraw () const
virtual void Draw ()
virtual void Keyboard (int key, int x, int y)
virtual void MouseClick (int button, int state, int x, int y)
virtual void MouseMove (int x, int y)
virtual void Reshape (int w, int h)
virtual void Shutdown ()
virtual bool IsDone () const
virtual cDrawScene * GetDrawScene () const
virtual void SetPlaybackSpeed (double speed)
virtual void SetUpdatesPerSec (double updates_per_sec)
virtual int GetWinWidth () const
virtual int GetWinHeight () const
virtual int GetNumUpdateSubsteps () const
virtual bool IsRLScene () const
virtual int GetNumAgents () const
virtual bool NeedNewAction (int agent_id) const
virtual std::vector< double > RecordState (int agent_id) const
virtual std::vector< double > RecordGoal (int agent_id) const
virtual void SetAction (int agent_id, const std::vector< double > &action)
virtual void LogVal (int agent_id, double val)
virtual int GetActionSpace (int agent_id) const
virtual int GetStateSize (int agent_id) const
virtual int GetGoalSize (int agent_id) const
virtual int GetActionSize (int agent_id) const
virtual int GetNumActions (int agent_id) const
virtual std::vector< double > BuildStateOffset (int agent_id) const
virtual std::vector< double > BuildStateScale (int agent_id) const
virtual std::vector< double > BuildGoalOffset (int agent_id) const
virtual std::vector< double > BuildGoalScale (int agent_id) const
virtual std::vector< double > BuildActionOffset (int agent_id) const
virtual std::vector< double > BuildActionScale (int agent_id) const
virtual std::vector< double > BuildActionBoundMin (int agent_id) const
virtual std::vector< double > BuildActionBoundMax (int agent_id) const
virtual std::vector< int > BuildStateNormGroups (int agent_id) const
virtual std::vector< int > BuildGoalNormGroups (int agent_id) const
virtual double CalcReward (int agent_id) const
virtual double GetRewardMin (int agent_id) const
virtual double GetRewardMax (int agent_id) const
virtual double GetRewardFail (int agent_id)
virtual double GetRewardSucc (int agent_id)
virtual bool IsEpisodeEnd () const
virtual bool CheckValidEpisode () const
virtual int CheckTerminate (int agent_id) const
virtual void SetMode (int mode)
virtual void SetSampleCount (int count)
Protected Member Functions
virtual void SetupScene ()
virtual void ClearScene ()
virtual int GetCurrTime () const
virtual void InitFrameBuffer ()
virtual void CalcDeviceCoord (int pixel_x, int pixel_y, double &out_device_x, double &out_device_y) const
virtual double GetAspectRatio ()
virtual void CopyFrame (cTextureDesc &src) const
virtual const std::shared_ptr< cRLScene > & GetRLScene () const
virtual void ConvertVector (const Eigen::VectorXd &in_vec, std::vector< double > &out_vec) const
virtual void ConvertVector (const Eigen::VectorXi &in_vec, std::vector< int > &out_vec) const
virtual void ConvertVector (const std::vector< double > &in_vec, Eigen::VectorXd &out_vec) const
virtual void ConvertVector (const std::vector< int > &in_vec, Eigen::VectorXi &out_vec) const
Protected Attributes
unsigned long int mRandSeed
std::shared_ptr< cArgParser > mArgParser
std::shared_ptr< cScene > mScene
std::shared_ptr< cRLScene > mRLScene
std::shared_ptr< cTextureDesc > mDefaultFrameBuffer
int mNumUpdateSubsteps
double mPlaybackSpeed
double mUpdatesPerSec
Detailed Description
Definition at line 9 of file DeepMimicCore.h.
Constructor & Destructor Documentation
cDeepMimicCore()
cDeepMimicCore::cDeepMimicCore (bool enable_draw)
Definition at line 6 of file DeepMimicCore.cpp.
 {
     mArgParser = std::shared_ptr<cArgParser>(new cArgParser());
     cDrawUtil::EnableDraw(enable_draw);
     mNumUpdateSubsteps = 1;
     mPlaybackSpeed = 1;
     mUpdatesPerSec = 0;
 }
References cDrawUtil::EnableDraw(), mArgParser, mNumUpdateSubsteps, mPlaybackSpeed, and mUpdatesPerSec.
~cDeepMimicCore()
cDeepMimicCore::~cDeepMimicCore () virtual
Definition at line 16 of file DeepMimicCore.cpp.
 {
 }
Member Function Documentation
BuildActionBoundMax()
std::vector< double > cDeepMimicCore::BuildActionBoundMax (int agent_id) const virtual
Definition at line 404 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         Eigen::VectorXd bound_min;
         Eigen::VectorXd bound_max;
         rl_scene->BuildActionBounds(agent_id, bound_min, bound_max);
         std::vector<double> out_max;
         ConvertVector(bound_max, out_max);
         return out_max;
     }
     return std::vector<double>(0);
 }
References ConvertVector(), and GetRLScene().
BuildActionBoundMin()
std::vector< double > cDeepMimicCore::BuildActionBoundMin (int agent_id) const virtual
Definition at line 388 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         Eigen::VectorXd bound_min;
         Eigen::VectorXd bound_max;
         rl_scene->BuildActionBounds(agent_id, bound_min, bound_max);
         std::vector<double> out_min;
         ConvertVector(bound_min, out_min);
         return out_min;
     }
     return std::vector<double>(0);
 }
References ConvertVector(), and GetRLScene().
BuildActionOffset()
std::vector< double > cDeepMimicCore::BuildActionOffset (int agent_id) const virtual
Definition at line 356 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         Eigen::VectorXd offset;
         Eigen::VectorXd scale;
         rl_scene->BuildActionOffsetScale(agent_id, offset, scale);
         std::vector<double> out_offset;
         ConvertVector(offset, out_offset);
         return out_offset;
     }
     return std::vector<double>(0);
 }
References ConvertVector(), and GetRLScene().
BuildActionScale()
std::vector< double > cDeepMimicCore::BuildActionScale (int agent_id) const virtual
Definition at line 372 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         Eigen::VectorXd offset;
         Eigen::VectorXd scale;
         rl_scene->BuildActionOffsetScale(agent_id, offset, scale);
         std::vector<double> out_scale;
         ConvertVector(scale, out_scale);
         return out_scale;
     }
     return std::vector<double>(0);
 }
References ConvertVector(), and GetRLScene().
BuildGoalNormGroups()
std::vector< int > cDeepMimicCore::BuildGoalNormGroups (int agent_id) const virtual
Definition at line 435 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         Eigen::VectorXi groups;
         rl_scene->BuildGoalNormGroups(agent_id, groups);
         std::vector<int> out_groups;
         ConvertVector(groups, out_groups);
         return out_groups;
     }
     return std::vector<int>(0);
 }
References ConvertVector(), and GetRLScene().
BuildGoalOffset()
std::vector< double > cDeepMimicCore::BuildGoalOffset (int agent_id) const virtual
Definition at line 324 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         Eigen::VectorXd offset;
         Eigen::VectorXd scale;
         rl_scene->BuildGoalOffsetScale(agent_id, offset, scale);
         std::vector<double> out_offset;
         ConvertVector(offset, out_offset);
         return out_offset;
     }
     return std::vector<double>(0);
 }
References ConvertVector(), and GetRLScene().
BuildGoalScale()
std::vector< double > cDeepMimicCore::BuildGoalScale (int agent_id) const virtual
Definition at line 340 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         Eigen::VectorXd offset;
         Eigen::VectorXd scale;
         rl_scene->BuildGoalOffsetScale(agent_id, offset, scale);
         std::vector<double> out_scale;
         ConvertVector(scale, out_scale);
         return out_scale;
     }
     return std::vector<double>(0);
 }
References ConvertVector(), and GetRLScene().
BuildStateNormGroups()
std::vector< int > cDeepMimicCore::BuildStateNormGroups (int agent_id) const virtual
Definition at line 420 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         Eigen::VectorXi groups;
         rl_scene->BuildStateNormGroups(agent_id, groups);
         std::vector<int> out_groups;
         ConvertVector(groups, out_groups);
         return out_groups;
     }
     return std::vector<int>(0);
 }
References ConvertVector(), and GetRLScene().
BuildStateOffset()
std::vector< double > cDeepMimicCore::BuildStateOffset (int agent_id) const virtual
Definition at line 292 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         Eigen::VectorXd offset;
         Eigen::VectorXd scale;
         rl_scene->BuildStateOffsetScale(agent_id, offset, scale);
         std::vector<double> out_offset;
         ConvertVector(offset, out_offset);
         return out_offset;
     }
     return std::vector<double>(0);
 }
References ConvertVector(), and GetRLScene().
BuildStateScale()
std::vector< double > cDeepMimicCore::BuildStateScale (int agent_id) const virtual
Definition at line 308 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         Eigen::VectorXd offset;
         Eigen::VectorXd scale;
         rl_scene->BuildStateOffsetScale(agent_id, offset, scale);
         std::vector<double> out_scale;
         ConvertVector(scale, out_scale);
         return out_scale;
     }
     return std::vector<double>(0);
 }
References ConvertVector(), and GetRLScene().
CalcDeviceCoord()
void cDeepMimicCore::CalcDeviceCoord (int pixel_x, int pixel_y, double & out_device_x, double & out_device_y) const protected virtual
Definition at line 582 of file DeepMimicCore.cpp.
 {
     double w = GetWinWidth();
     double h = GetWinHeight();
     out_device_x = static_cast<double>(pixel_x) / w;
     out_device_y = static_cast<double>(pixel_y) / h;
     out_device_x = (out_device_x - 0.5f) * 2.f;
     out_device_y = (out_device_y - 0.5f) * -2.f;
 }
References GetWinHeight(), and GetWinWidth().
Referenced by Keyboard(), MouseClick(), and MouseMove().
CalcReward()
double cDeepMimicCore::CalcReward (int agent_id) const virtual
Definition at line 450 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         return rl_scene->CalcReward(agent_id);
     }
     return 0;
 }
References GetRLScene().
CheckTerminate()
int cDeepMimicCore::CheckTerminate (int agent_id) const virtual
Definition at line 510 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     cRLScene::eTerminate terminated = cRLScene::eTerminateNull;
     if (rl_scene != nullptr)
     {
         terminated = rl_scene->CheckTerminate(agent_id);
     }
     return static_cast<int>(terminated);
 }
References cRLScene::eTerminateNull, and GetRLScene().
CheckValidEpisode()
bool cDeepMimicCore::CheckValidEpisode () const virtual
Definition at line 505 of file DeepMimicCore.cpp.
 {
     return mScene->CheckValidEpisode();
 }
References mScene.
ClearScene()
void cDeepMimicCore::ClearScene () protected virtual
Definition at line 567 of file DeepMimicCore.cpp.
 {
     mScene = nullptr;
 }
References mScene.
Referenced by SetupScene().
ConvertVector() [1/4]
void cDeepMimicCore::ConvertVector (const Eigen::VectorXd & in_vec, std::vector< double > & out_vec) const protected virtual
Definition at line 609 of file DeepMimicCore.cpp.
 {
     int size = static_cast<int>(in_vec.size());
     out_vec.resize(size);
     std::memcpy(out_vec.data(), in_vec.data(), size * sizeof(double));
 }
Referenced by BuildActionBoundMax(), BuildActionBoundMin(), BuildActionOffset(), BuildActionScale(), BuildGoalNormGroups(), BuildGoalOffset(), BuildGoalScale(), BuildStateNormGroups(), BuildStateOffset(), BuildStateScale(), RecordGoal(), RecordState(), and SetAction().
ConvertVector() [2/4]
void cDeepMimicCore::ConvertVector (const Eigen::VectorXi & in_vec, std::vector< int > & out_vec) const protected virtual
Definition at line 616 of file DeepMimicCore.cpp.
 {
     int size = static_cast<int>(in_vec.size());
     out_vec.resize(size);
     std::memcpy(out_vec.data(), in_vec.data(), size * sizeof(int));
 }
ConvertVector() [3/4]
void cDeepMimicCore::ConvertVector (const std::vector< double > & in_vec, Eigen::VectorXd & out_vec) const protected virtual
Definition at line 623 of file DeepMimicCore.cpp.
 {
     int size = static_cast<int>(in_vec.size());
     out_vec.resize(size);
     std::memcpy(out_vec.data(), in_vec.data(), size * sizeof(double));
 }
ConvertVector() [4/4]
void cDeepMimicCore::ConvertVector (const std::vector< int > & in_vec, Eigen::VectorXi & out_vec) const protected virtual
Definition at line 630 of file DeepMimicCore.cpp.
 {
     int size = static_cast<int>(in_vec.size());
     out_vec.resize(size);
     std::memcpy(out_vec.data(), in_vec.data(), size * sizeof(int));
 }
CopyFrame()
void cDeepMimicCore::CopyFrame (cTextureDesc & src) const protected virtual
Definition at line 599 of file DeepMimicCore.cpp.
 {
     cDrawUtil::CopyTexture(src);
 }
References cDrawUtil::CopyTexture().
Draw()
void cDeepMimicCore::Draw () virtual
Definition at line 82 of file DeepMimicCore.cpp.
 {
     if (EnableDraw())
     {
         mDefaultFrameBuffer->BindBuffer();
         mScene->Draw();
         mDefaultFrameBuffer->UnbindBuffer();
     }
 }
References EnableDraw(), mDefaultFrameBuffer, and mScene.
EnableDraw()
bool cDeepMimicCore::EnableDraw () const virtual
Definition at line 77 of file DeepMimicCore.cpp.
 {
     return cDrawUtil::EnableDraw();
 }
References cDrawUtil::EnableDraw().
Referenced by Draw(), Init(), and SetupScene().
GetActionSize()
int cDeepMimicCore::GetActionSize (int agent_id) const virtual
Definition at line 272 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         return rl_scene->GetActionSize(agent_id);
     }
     return 0;
 }
References GetRLScene().
GetActionSpace()
int cDeepMimicCore::GetActionSpace (int agent_id) const virtual
Definition at line 241 of file DeepMimicCore.cpp.
 {
     eActionSpace action_space = eActionSpaceNull;
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         action_space = rl_scene->GetActionSpace(agent_id);
     }
     return static_cast<int>(action_space);
 }
References eActionSpaceNull, and GetRLScene().
GetAspectRatio()
double cDeepMimicCore::GetAspectRatio () protected virtual
Definition at line 593 of file DeepMimicCore.cpp.
 {
     double aspect_ratio = static_cast<double>(GetWinWidth()) / GetWinHeight();
     return aspect_ratio;
 }
References GetWinHeight(), and GetWinWidth().
GetCurrTime()
int cDeepMimicCore::GetCurrTime () const protected virtual
Definition at line 572 of file DeepMimicCore.cpp.
 {
     return glutGet(GLUT_ELAPSED_TIME);
 }
GetDrawScene()
cDrawScene * cDeepMimicCore::GetDrawScene () const virtual
Definition at line 135 of file DeepMimicCore.cpp.
 {
     return dynamic_cast<cDrawScene*>(mScene.get());
 }
References mScene.
GetGoalSize()
int cDeepMimicCore::GetGoalSize (int agent_id) const virtual
Definition at line 262 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         return rl_scene->GetGoalSize(agent_id);
     }
     return 0;
 }
References GetRLScene().
GetName()
std::string cDeepMimicCore::GetName () const virtual
Definition at line 72 of file DeepMimicCore.cpp.
 {
     return mScene->GetName();
 }
References mScene.
GetNumActions()
int cDeepMimicCore::GetNumActions (int agent_id) const virtual
Definition at line 282 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         return rl_scene->GetNumActions(agent_id);
     }
     return 0;
 }
References GetRLScene().
GetNumAgents()
int cDeepMimicCore::GetNumAgents () const virtual
Definition at line 171 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         return rl_scene->GetNumAgents();
     }
     return 0;
 }
References GetRLScene().
GetNumUpdateSubsteps()
int cDeepMimicCore::GetNumUpdateSubsteps () const virtual
Definition at line 160 of file DeepMimicCore.cpp.
 {
     return mNumUpdateSubsteps;
 }
References mNumUpdateSubsteps.
GetRewardFail()
double cDeepMimicCore::GetRewardFail (int agent_id) virtual
Definition at line 480 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         return rl_scene->GetRewardFail(agent_id);
     }
     return 0;
 }
References GetRLScene().
GetRewardMax()
double cDeepMimicCore::GetRewardMax (int agent_id) const virtual
Definition at line 470 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         return rl_scene->GetRewardMax(agent_id);
     }
     return 0;
 }
References GetRLScene().
GetRewardMin()
double cDeepMimicCore::GetRewardMin (int agent_id) const virtual
Definition at line 460 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         return rl_scene->GetRewardMin(agent_id);
     }
     return 0;
 }
References GetRLScene().
GetRewardSucc()
double cDeepMimicCore::GetRewardSucc (int agent_id) virtual
Definition at line 490 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         return rl_scene->GetRewardSucc(agent_id);
     }
     return 0;
 }
References GetRLScene().
GetRLScene()
const std::shared_ptr< cRLScene > & cDeepMimicCore::GetRLScene () const protected virtual
Definition at line 604 of file DeepMimicCore.cpp.
 {
     return mRLScene;
 }
References mRLScene.
Referenced by BuildActionBoundMax(), BuildActionBoundMin(), BuildActionOffset(), BuildActionScale(), BuildGoalNormGroups(), BuildGoalOffset(), BuildGoalScale(), BuildStateNormGroups(), BuildStateOffset(), BuildStateScale(), CalcReward(), CheckTerminate(), GetActionSize(), GetActionSpace(), GetGoalSize(), GetNumActions(), GetNumAgents(), GetRewardFail(), GetRewardMax(), GetRewardMin(), GetRewardSucc(), GetStateSize(), IsRLScene(), LogVal(), NeedNewAction(), RecordGoal(), RecordState(), SetAction(), SetMode(), and SetSampleCount().
GetStateSize()
int cDeepMimicCore::GetStateSize (int agent_id) const virtual
Definition at line 252 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         return rl_scene->GetStateSize(agent_id);
     }
     return 0;
 }
References GetRLScene().
GetTime()
double cDeepMimicCore::GetTime () const virtual
Definition at line 67 of file DeepMimicCore.cpp.
 {
     return mScene->GetTime();
 }
References mScene.
GetWinHeight()
int cDeepMimicCore::GetWinHeight () const virtual
Definition at line 155 of file DeepMimicCore.cpp.
 {
     return mDefaultFrameBuffer->GetHeight();
 }
References mDefaultFrameBuffer.
Referenced by CalcDeviceCoord(), and GetAspectRatio().
GetWinWidth()
int cDeepMimicCore::GetWinWidth () const virtual
Definition at line 150 of file DeepMimicCore.cpp.
 {
     return mDefaultFrameBuffer->GetWidth();
 }
References mDefaultFrameBuffer.
Referenced by CalcDeviceCoord(), and GetAspectRatio().
Init()
void cDeepMimicCore::Init () virtual
Definition at line 46 of file DeepMimicCore.cpp.
 {
     if (EnableDraw())
     {
         cDrawUtil::InitDrawUtil();
         InitFrameBuffer();
     }
     SetupScene();
 }
References EnableDraw(), cDrawUtil::InitDrawUtil(), InitFrameBuffer(), and SetupScene().
InitFrameBuffer()
void cDeepMimicCore::InitFrameBuffer () protected virtual
Definition at line 577 of file DeepMimicCore.cpp.
 {
     mDefaultFrameBuffer = std::unique_ptr<cTextureDesc>(new cTextureDesc(0, 0, 0, 1, 1, 1, GL_RGBA, GL_RGBA));
 }
References mDefaultFrameBuffer.
Referenced by Init().
IsDone()
bool cDeepMimicCore::IsDone () const virtual
Definition at line 130 of file DeepMimicCore.cpp.
 {
     return mScene->IsDone();
 }
References mScene.
IsEpisodeEnd()
bool cDeepMimicCore::IsEpisodeEnd () const virtual
Definition at line 500 of file DeepMimicCore.cpp.
 {
     return mScene->IsEpisodeEnd();
 }
References mScene.
IsRLScene()
bool cDeepMimicCore::IsRLScene () const virtual
Definition at line 165 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     return rl_scene != nullptr;
 }
References GetRLScene().
Keyboard()
void cDeepMimicCore::Keyboard (int key, int x, int y) virtual
Definition at line 92 of file DeepMimicCore.cpp.
 {
     char c = static_cast<char>(key);
     double device_x = 0;
     double device_y = 0;
     CalcDeviceCoord(x, y, device_x, device_y);
     mScene->Keyboard(c, device_x, device_y);
 }
References CalcDeviceCoord(), and mScene.
LogVal()
void cDeepMimicCore::LogVal (int agent_id, double val) virtual
Definition at line 232 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         rl_scene->LogVal(agent_id, val);
     }
 }
References GetRLScene().
MouseClick()
void cDeepMimicCore::MouseClick (int button, int state, int x, int y) virtual
Definition at line 101 of file DeepMimicCore.cpp.
 {
     double device_x = 0;
     double device_y = 0;
     CalcDeviceCoord(x, y, device_x, device_y);
     mScene->MouseClick(button, state, device_x, device_y);
 }
References CalcDeviceCoord(), and mScene.
MouseMove()
void cDeepMimicCore::MouseMove (int x, int y) virtual
Definition at line 109 of file DeepMimicCore.cpp.
 {
     double device_x = 0;
     double device_y = 0;
     CalcDeviceCoord(x, y, device_x, device_y);
     mScene->MouseMove(device_x, device_y);
 }
References CalcDeviceCoord(), and mScene.
NeedNewAction()
bool cDeepMimicCore::NeedNewAction (int agent_id) const virtual
Definition at line 181 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         return rl_scene->NeedNewAction(agent_id);
     }
     return false;
 }
References GetRLScene().
ParseArgs()
void cDeepMimicCore::ParseArgs (const std::vector< std::string > & args) virtual
Definition at line 25 of file DeepMimicCore.cpp.
 {
     mArgParser->LoadArgs(args);
     std::string arg_file = "";
     mArgParser->ParseString("arg_file", arg_file);
     if (arg_file != "")
     {
         // append the args from the file to the ones from the commandline
         // this allows the cmd args to overwrite the file args
         bool succ = mArgParser->LoadFile(arg_file);
         if (!succ)
         {
             printf("Failed to load args from: %s\n", arg_file.c_str());
             assert(false);
         }
     }
     mArgParser->ParseInt("num_update_substeps", mNumUpdateSubsteps);
 }
References mArgParser, and mNumUpdateSubsteps.
RecordGoal()
std::vector< double > cDeepMimicCore::RecordGoal (int agent_id) const virtual
Definition at line 206 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         Eigen::VectorXd goal;
         rl_scene->RecordGoal(agent_id, goal);
         std::vector<double> out_goal;
         ConvertVector(goal, out_goal);
         return out_goal;
     }
     return std::vector<double>(0);
 }
References ConvertVector(), and GetRLScene().
RecordState()
std::vector< double > cDeepMimicCore::RecordState (int agent_id) const virtual
Definition at line 191 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         Eigen::VectorXd state;
         rl_scene->RecordState(agent_id, state);
         std::vector<double> out_state;
         ConvertVector(state, out_state);
         return out_state;
     }
     return std::vector<double>(0);
 }
References ConvertVector(), and GetRLScene().
Reset()
void cDeepMimicCore::Reset () virtual
Definition at line 61 of file DeepMimicCore.cpp.
 {
     mScene->Reset();
     mUpdatesPerSec = 0;
 }
References mScene, and mUpdatesPerSec.
Reshape()
void cDeepMimicCore::Reshape (int w, int h) virtual
Definition at line 117 of file DeepMimicCore.cpp.
 {
     mScene->Reshape(w, h);
     mDefaultFrameBuffer->Reshape(w, h);
     glViewport(0, 0, w, h);
     glutPostRedisplay();
 }
References mDefaultFrameBuffer, and mScene.
SeedRand()
void cDeepMimicCore::SeedRand (int seed) virtual
Definition at line 20 of file DeepMimicCore.cpp.
 {
     cMathUtil::SeedRand(seed);
 }
References cMathUtil::SeedRand().
SetAction()
void cDeepMimicCore::SetAction (int agent_id, const std::vector< double > & action) virtual
Definition at line 221 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         Eigen::VectorXd in_action;
         ConvertVector(action, in_action);
         rl_scene->SetAction(agent_id, in_action);
     }
 }
References ConvertVector(), and GetRLScene().
SetMode()
void cDeepMimicCore::SetMode (int mode) virtual
Definition at line 521 of file DeepMimicCore.cpp.
 {
     assert(mode >= 0 && mode < cRLScene::eModeMax);
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         rl_scene->SetMode(static_cast<cRLScene::eMode>(mode));
     }
 }
References cRLScene::eModeMax, and GetRLScene().
SetPlaybackSpeed()
void cDeepMimicCore::SetPlaybackSpeed (double speed) virtual
Definition at line 140 of file DeepMimicCore.cpp.
 {
     mPlaybackSpeed = speed;
 }
References mPlaybackSpeed.
SetSampleCount()
void cDeepMimicCore::SetSampleCount (int count) virtual
Definition at line 531 of file DeepMimicCore.cpp.
 {
     const auto& rl_scene = GetRLScene();
     if (rl_scene != nullptr)
     {
         rl_scene->SetSampleCount(count);
     }
 }
References GetRLScene().
SetUpdatesPerSec()
void cDeepMimicCore::SetUpdatesPerSec (double updates_per_sec) virtual
Definition at line 145 of file DeepMimicCore.cpp.
 {
     mUpdatesPerSec = updates_per_sec;
 }
References mUpdatesPerSec.
SetupScene()
void cDeepMimicCore::SetupScene () protected virtual
Definition at line 540 of file DeepMimicCore.cpp.
 {
     ClearScene();
     std::string scene_name = "";
     mArgParser->ParseString("scene", scene_name);
     mScene = nullptr;
     mRLScene = nullptr;
     if (EnableDraw())
     {
         cSceneBuilder::BuildDrawScene(scene_name, mScene);
     }
     else
     {
         cSceneBuilder::BuildScene(scene_name, mScene);
     }
     if (mScene != nullptr)
     {
         mRLScene = std::dynamic_pointer_cast<cRLScene>(mScene);
         mScene->ParseArgs(mArgParser);
         mScene->Init();
         printf("Loaded scene: %s\n", mScene->GetName().c_str());
     }
 }
References cSceneBuilder::BuildDrawScene(), cSceneBuilder::BuildScene(), ClearScene(), EnableDraw(), mArgParser, mRLScene, and mScene.
Referenced by Init().
Shutdown()
void cDeepMimicCore::Shutdown () virtual
Definition at line 125 of file DeepMimicCore.cpp.
 {
     mScene->Shutdown();
 }
References mScene.
Update()
void cDeepMimicCore::Update (double timestep) virtual
Definition at line 56 of file DeepMimicCore.cpp.
 {
     mScene->Update(timestep);
 }
References mScene.
Member Data Documentation
mArgParser
std::shared_ptr<cArgParser> cDeepMimicCore::mArgParser protected
Definition at line 85 of file DeepMimicCore.h.
Referenced by cDeepMimicCore(), ParseArgs(), and SetupScene().
mDefaultFrameBuffer
std::shared_ptr<cTextureDesc> cDeepMimicCore::mDefaultFrameBuffer protected
Definition at line 89 of file DeepMimicCore.h.
Referenced by Draw(), GetWinHeight(), GetWinWidth(), InitFrameBuffer(), and Reshape().
mNumUpdateSubsteps
int cDeepMimicCore::mNumUpdateSubsteps protected
Definition at line 91 of file DeepMimicCore.h.
Referenced by cDeepMimicCore(), GetNumUpdateSubsteps(), and ParseArgs().
mPlaybackSpeed
double cDeepMimicCore::mPlaybackSpeed protected
Definition at line 94 of file DeepMimicCore.h.
Referenced by cDeepMimicCore(), and SetPlaybackSpeed().
mRandSeed
unsigned long int cDeepMimicCore::mRandSeed protected
Definition at line 83 of file DeepMimicCore.h.
mRLScene
std::shared_ptr<cRLScene> cDeepMimicCore::mRLScene protected
Definition at line 87 of file DeepMimicCore.h.
Referenced by GetRLScene(), and SetupScene().
mScene
std::shared_ptr<cScene> cDeepMimicCore::mScene protected
Definition at line 86 of file DeepMimicCore.h.
Referenced by CheckValidEpisode(), ClearScene(), Draw(), GetDrawScene(), GetName(), GetTime(), IsDone(), IsEpisodeEnd(), Keyboard(), MouseClick(), MouseMove(), Reset(), Reshape(), SetupScene(), Shutdown(), and Update().
mUpdatesPerSec
double cDeepMimicCore::mUpdatesPerSec protected
Definition at line 95 of file DeepMimicCore.h.
Referenced by cDeepMimicCore(), Reset(), and SetUpdatesPerSec().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/DeepMimicCore.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/DeepMimicCore.cpp