My Project: cGroundPlane Class Reference
cGroundPlane Class Reference
#include <GroundPlane.h>
Public Member Functions
cGroundPlane ()
virtual ~cGroundPlane ()
virtual void Init (const std::shared_ptr< cWorld > &world, const tParams &params)
virtual void Update (double time_elapsed, const tVector &bound_min, const tVector &bound_max)
virtual void Clear ()
virtual double SampleHeight (const tVector &pos) const
virtual double SampleHeight (const tVector &pos, bool &out_valid_sample) const
virtual void SampleHeight (const Eigen::MatrixXd &pos, Eigen::VectorXd &out_h) const
virtual const tVector & GetPrevCenter () const
virtual eClass GetGroundClass () const
virtual void CalcAABB (tVector &out_min, tVector &out_max) const
Public Member Functions inherited from cGround
virtual ~cGround ()
virtual void SampleHeightVel (const tVector &pos, double &out_h, tVector &out_vel, bool &out_valid_sample) const
virtual void SetBlendParams (const Eigen::VectorXd &params)
virtual void SetParamBlend (double blend)
virtual size_t GetUpdateCount () const
virtual void SeedRand (unsigned long seed)
virtual void SamplePlacement (const tVector &origin, tVector &out_pos, tQuaternion &out_rot)
virtual tVector GetSize () const
virtual double GetVertSpacingX () const
virtual double GetVertSpacingZ () const
virtual bool Output (const std::string &out_file) const
Public Member Functions inherited from cSimRigidBody
virtual ~cSimRigidBody ()
virtual void SetPos (const tVector &pos)
virtual void SetRotation (const tVector &axis, double theta)
virtual void SetRotation (const tQuaternion &q)
virtual tVector GetLinearVelocity () const
virtual tVector GetLinearVelocity (const tVector &local_pos) const
virtual void SetLinearVelocity (const tVector &vel)
virtual tVector GetAngularVelocity () const
virtual void SetAngularVelocity (const tVector &vel)
virtual void SetDamping (double linear_damping, double angular_damping)
virtual double GetMass () const
virtual void ApplyForce (const tVector &force)
virtual void ApplyForce (const tVector &force, const tVector &local_pos)
virtual void ApplyTorque (const tVector &torque)
virtual void ClearForces ()
virtual void SetKinematicObject (bool is_kin)
virtual bool IsKinematicObject () const
virtual void DisableDeactivation ()
virtual void Constrain (const tVector &linear_factor, const tVector &angular_factor)
virtual bool HasSimBody () const
virtual const std::unique_ptr< btRigidBody > & GetSimBody () const
Public Member Functions inherited from cSimObj
virtual ~cSimObj ()
virtual tVector GetPos () const
virtual void GetRotation (tVector &out_axis, double &out_theta) const
virtual tQuaternion GetRotation () const
virtual tMatrix GetWorldTransform () const
virtual tMatrix GetLocalTransform () const
virtual tVector WorldToLocalPos (const tVector &world_pos) const
virtual tVector LocalToWorldPos (const tVector &local_pos) const
virtual tMatrix3 GetLocalToWorldRotMat () const
virtual tVector CalcCOM () const
virtual tVector CalcCOMVel () const
virtual void RegisterContact ()
virtual void RegisterContact (int contact_flags, int filter_flags)
virtual void UpdateContact (int contact_flags, int filter_flags)
virtual const cContactManager::tContactHandle & GetContactHandle () const
virtual bool IsInContact () const
virtual const tEigenArr< cContactManager::tContactPt > & GetContactPts () const
virtual short GetColGroup () const
virtual void SetColGroup (short col_group)
virtual short GetColMask () const
virtual void SetColMask (short col_mask)
virtual eType GetType () const
virtual cShape::eShape GetShape () const
virtual const btCollisionShape * GetCollisionShape () const
Static Public Member Functions
static EIGEN_MAKE_ALIGNED_OPERATOR_NEW bool ParseParamsJson (const Json::Value &json, Eigen::VectorXd &out_params)
Static Public Member Functions inherited from cGround
static eClass GetClassFromType (eType ground_type)
static void ParseType (const std::string &str, eType &out_type)
Protected Attributes
tVector mPrevCenter
Protected Attributes inherited from cGround
cRand mRand
tParams mParams
Eigen::VectorXd mBlendParams
size_t mUpdateCount
double mTime
Protected Attributes inherited from cSimRigidBody
std::unique_ptr< btRigidBody > mSimBody
Protected Attributes inherited from cSimObj
std::shared_ptr< cWorld > mWorld
std::unique_ptr< btCollisionShape > mColShape
cContactManager::tContactHandle mContactHandle
bool mEnableContactFall
eType mType
short mColGroup
short mColMask
Additional Inherited Members
Public Types inherited from cGround
enum eClass { eClassPlane, eClassMax, eClassInvalid }
enum eType { eTypePlane, eTypeMax }
Public Types inherited from cSimObj
enum eType { eTypeDynamic, eTypeStatic, eTypeMax }
Static Public Attributes inherited from cGround
static const std::string gTypeKey = "Type"
static const std::string gGroundWidthKey = "GroundWidth"
static const std::string gVertSpacingXKey = "VertSpacingX"
static const std::string gVertSpacingZKey = "VertSpacingZ"
static const std::string gParamsKey = "Params"
Protected Member Functions inherited from cGround
cGround ()
virtual void SetupRandGen ()
virtual void CalcBlendParams (double blend, Eigen::VectorXd &out_params) const
virtual int GetNumParamSets () const
virtual int GetBlendParamSize () const
virtual void FlagUpdate ()
Protected Member Functions inherited from cSimRigidBody
cSimRigidBody ()
virtual void Init (const std::shared_ptr< cWorld > &world)
virtual void AddToWorld (const std::shared_ptr< cWorld > &world)
virtual void RemoveFromWorld ()
virtual const btCollisionObject * GetCollisionObject () const
virtual btCollisionObject * GetCollisionObject ()
virtual int GetNumConstraints () const
virtual cWorld::tConstraintHandle GetConstraint (int c) const
Protected Member Functions inherited from cSimObj
cSimObj ()
virtual const std::shared_ptr< cWorld > & GetWorld () const
Detailed Description
Definition at line 5 of file GroundPlane.h.
Constructor & Destructor Documentation
cGroundPlane()
cGroundPlane::cGroundPlane ()
Definition at line 9 of file GroundPlane.cpp.
 {
     mPrevCenter.setZero();
 }
References mPrevCenter.
~cGroundPlane()
cGroundPlane::~cGroundPlane () virtual
Definition at line 14 of file GroundPlane.cpp.
 {
 }
Member Function Documentation
CalcAABB()
void cGroundPlane::CalcAABB (tVector & out_min, tVector & out_max) const virtual
Reimplemented from cSimObj.
Definition at line 90 of file GroundPlane.cpp.
 {
     out_min = -std::numeric_limits<double>::infinity() * tVector::Ones();
     out_max = std::numeric_limits<double>::infinity() * tVector::Ones();
 }
Clear()
void cGroundPlane::Clear () virtual
Reimplemented from cGround.
Definition at line 52 of file GroundPlane.cpp.
 {
     cGround::Clear();
     mPrevCenter.setZero();
 }
References cGround::Clear(), and mPrevCenter.
GetGroundClass()
cGroundPlane::eClass cGroundPlane::GetGroundClass () const virtual
Reimplemented from cGround.
Definition at line 85 of file GroundPlane.cpp.
 {
     return eClassPlane;
 }
References cGround::eClassPlane.
GetPrevCenter()
const tVector & cGroundPlane::GetPrevCenter () const virtual
Definition at line 80 of file GroundPlane.cpp.
 {
     return mPrevCenter;
 }
References mPrevCenter.
Referenced by cDrawGround::BuildMeshPlane().
Init()
void cGroundPlane::Init (const std::shared_ptr< cWorld > & world, const tParams & params) virtual
Reimplemented from cGround.
Definition at line 18 of file GroundPlane.cpp.
 {
     mParams = params;
     mPrevCenter.setZero();
     btVector3 normal = btVector3(0, 1, 0);
     btVector3 origin = btVector3(static_cast<btScalar>(params.mOrigin[0]),
                                 static_cast<btScalar>(params.mOrigin[1]),
                                 static_cast<btScalar>(params.mOrigin[2]));
     normal.normalize();
     btScalar w = normal.dot(origin);
     mColShape = std::unique_ptr<btCollisionShape>(new btStaticPlaneShape(normal, w));
     btRigidBody::btRigidBodyConstructionInfo cons_info(0, this, mColShape.get(), btVector3(0, 0, 0));
     mSimBody = std::unique_ptr<btRigidBody>(new btRigidBody(cons_info));
     mSimBody->setFriction(static_cast<btScalar>(params.mFriction));
     cGround::Init(world, params);
 }
References cGround::Init(), cSimObj::mColShape, cGround::tParams::mFriction, cGround::tParams::mOrigin, cGround::mParams, mPrevCenter, and cSimRigidBody::mSimBody.
ParseParamsJson()
bool cGroundPlane::ParseParamsJson (const Json::Value & json, Eigen::VectorXd & out_params) static
Definition at line 3 of file GroundPlane.cpp.
 {
     out_params.resize(0);
     return true;
 }
Referenced by cGroundBuilder::ParseParamsJason().
SampleHeight() [1/3]
void cGroundPlane::SampleHeight (const Eigen::MatrixXd & pos, Eigen::VectorXd & out_h) const virtual
Reimplemented from cGround.
Definition at line 73 of file GroundPlane.cpp.
 {
     double h = SampleHeight(tVector::Zero());
     int num_pos = static_cast<int>(pos.rows());
     out_h = Eigen::VectorXd::Ones(num_pos) * h;
 }
References SampleHeight().
SampleHeight() [2/3]
double cGroundPlane::SampleHeight (const tVector & pos) const virtual
Reimplemented from cGround.
Definition at line 58 of file GroundPlane.cpp.
 {
     return cGround::SampleHeight(pos);
 }
References cGround::SampleHeight().
Referenced by SampleHeight().
SampleHeight() [3/3]
double cGroundPlane::SampleHeight (const tVector & pos, bool & out_valid_sample) const virtual
Reimplemented from cGround.
Definition at line 63 of file GroundPlane.cpp.
 {
     const btStaticPlaneShape* shape = reinterpret_cast<btStaticPlaneShape*>(mColShape.get());
     btVector3 n = shape->getPlaneNormal();
     btScalar c = shape->getPlaneConstant();
     out_valid_sample = true;
     return n[1] * c;
 }
References cSimObj::mColShape.
Update()
void cGroundPlane::Update (double time_elapsed, const tVector & bound_min, const tVector & bound_max) virtual
Reimplemented from cGround.
Definition at line 38 of file GroundPlane.cpp.
 {
     const double dist_threshold = 100;
     cGround::Update(time_elapsed, bound_min, bound_max);
     tVector new_center = 0.5 * (bound_max + bound_min);
     tVector delta = new_center - mPrevCenter;
     double dist_sq = delta.squaredNorm();
     if (dist_sq > dist_threshold)
     {
         mPrevCenter = new_center;
         FlagUpdate();
     }
 }
References cGround::FlagUpdate(), mPrevCenter, and cGround::Update().
Member Data Documentation
mPrevCenter
tVector cGroundPlane::mPrevCenter protected
Definition at line 29 of file GroundPlane.h.
Referenced by cGroundPlane(), Clear(), GetPrevCenter(), Init(), and Update().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/GroundPlane.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/GroundPlane.cpp