My Project: cSceneKinChar Class Reference
cSceneKinChar Class Reference
#include <SceneKinChar.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cSceneKinChar ()
virtual ~cSceneKinChar ()
virtual void Init ()
virtual void ParseArgs (const std::shared_ptr< cArgParser > &parser)
virtual void Reset ()
virtual void Clear ()
virtual void Update (double time_elapsed)
virtual const std::shared_ptr< cKinCharacter > & GetCharacter () const
virtual tVector GetCharPos () const
virtual double GetTime () const
virtual std::string GetName () const
Public Member Functions inherited from cScene
virtual ~cScene ()
virtual void Draw ()
virtual void Keyboard (unsigned char key, double device_x, double device_y)
virtual void MouseClick (int button, int state, double device_x, double device_y)
virtual void MouseMove (double device_x, double device_y)
virtual void Reshape (int w, int h)
virtual void Shutdown ()
virtual bool IsDone () const
virtual bool HasRandSeed () const
virtual void SetRandSeed (unsigned long seed)
virtual unsigned long GetRandSeed () const
virtual bool IsEpisodeEnd () const
virtual bool CheckValidEpisode () const
Protected Member Functions
virtual void ParseCharParams (const std::shared_ptr< cArgParser > &parser, cKinCharacter::tParams &out_params) const
virtual bool BuildCharacters ()
virtual bool BuildCharacter (const cKinCharacter::tParams &params, std::shared_ptr< cKinCharacter > &out_char) const
virtual void ResetCharacters ()
virtual void UpdateCharacters (double timestep)
Protected Member Functions inherited from cScene
cScene ()
virtual void ResetParams ()
virtual void ResetScene ()
virtual void InitTimers ()
virtual void ResetTimers ()
virtual void UpdateTimers (double timestep)
Protected Attributes
cKinCharacter::tParams mCharParams
std::shared_ptr< cKinCharacter > mChar
Protected Attributes inherited from cScene
cRand mRand
bool mHasRandSeed
unsigned long mRandSeed
std::shared_ptr< cArgParser > mArgParser
cTimer::tParams mTimerParams
cTimer mTimer
Detailed Description
Definition at line 8 of file SceneKinChar.h.
Constructor & Destructor Documentation
cSceneKinChar()
cSceneKinChar::cSceneKinChar ()
Definition at line 3 of file SceneKinChar.cpp.
 {
 }
~cSceneKinChar()
cSceneKinChar::~cSceneKinChar () virtual
Definition at line 7 of file SceneKinChar.cpp.
 {
 }
Member Function Documentation
BuildCharacter()
bool cSceneKinChar::BuildCharacter (const cKinCharacter::tParams & params, std::shared_ptr< cKinCharacter > & out_char) const protected virtual
Definition at line 96 of file SceneKinChar.cpp.
 {
     out_char = std::shared_ptr<cKinCharacter>(new cKinCharacter());
     bool succ = out_char->Init(params);
     return succ;
 }
Referenced by BuildCharacters().
BuildCharacters()
bool cSceneKinChar::BuildCharacters () protected virtual
Definition at line 83 of file SceneKinChar.cpp.
 {
     mChar.reset();
     auto& params = mCharParams;
     params.mID = 0;
     params.mLoadDrawShapes = true;
     bool succ = BuildCharacter(params, mChar);
     return succ;
 }
References BuildCharacter(), mChar, mCharParams, and cKinCharacter::tParams::mID.
Referenced by Init().
Clear()
void cSceneKinChar::Clear () virtual
Reimplemented from cScene.
Definition at line 27 of file SceneKinChar.cpp.
 {
     mChar.reset();
 }
References mChar.
GetCharacter()
const std::shared_ptr< cKinCharacter > & cSceneKinChar::GetCharacter () const virtual
Definition at line 37 of file SceneKinChar.cpp.
 {
     return mChar;
 }
References mChar.
Referenced by GetCharPos(), and GetTime().
GetCharPos()
tVector cSceneKinChar::GetCharPos () const virtual
Definition at line 42 of file SceneKinChar.cpp.
 {
     return GetCharacter()->GetRootPos();
 }
References GetCharacter().
GetName()
std::string cSceneKinChar::GetName () const virtual
Implements cScene.
Definition at line 52 of file SceneKinChar.cpp.
 {
     return "Kinematic Char";
 }
GetTime()
double cSceneKinChar::GetTime () const virtual
Reimplemented from cScene.
Definition at line 47 of file SceneKinChar.cpp.
 {
     return GetCharacter()->GetTime();
 }
References GetCharacter().
Init()
void cSceneKinChar::Init () virtual
Reimplemented from cScene.
Definition at line 11 of file SceneKinChar.cpp.
 {
     bool succ = BuildCharacters();
 }
References BuildCharacters().
ParseArgs()
void cSceneKinChar::ParseArgs (const std::shared_ptr< cArgParser > & parser) virtual
Reimplemented from cScene.
Definition at line 16 of file SceneKinChar.cpp.
 {
     cScene::ParseArgs(parser);
     ParseCharParams(parser, mCharParams);
 }
References mCharParams, cScene::ParseArgs(), and ParseCharParams().
ParseCharParams()
void cSceneKinChar::ParseCharParams (const std::shared_ptr< cArgParser > & parser, cKinCharacter::tParams & out_params) const protected virtual
Definition at line 57 of file SceneKinChar.cpp.
 {
     std::string char_file = "";
     std::string motion_file = "";
     std::string state_file = "";
     double init_pos_xs = 0;
     bool succ = parser->ParseString("character_file", char_file);
     if (succ)
     {
         parser->ParseString("state_file", state_file);
         parser->ParseString("motion_file", motion_file);
         parser->ParseDouble("char_init_pos_x", init_pos_xs);
         out_params.mCharFile = char_file;
         out_params.mMotionFile = motion_file;
         out_params.mStateFile = state_file;
         out_params.mOrigin[0] = init_pos_xs;
     }
     else
     {
         printf("No character file provided\n");
     }
 }
References cKinCharacter::tParams::mCharFile, cKinCharacter::tParams::mMotionFile, cKinCharacter::tParams::mOrigin, and cKinCharacter::tParams::mStateFile.
Referenced by ParseArgs().
Reset()
void cSceneKinChar::Reset () virtual
Reimplemented from cScene.
Definition at line 22 of file SceneKinChar.cpp.
 {
     ResetCharacters();
 }
References ResetCharacters().
ResetCharacters()
void cSceneKinChar::ResetCharacters () protected virtual
Definition at line 103 of file SceneKinChar.cpp.
 {
     mChar->Reset();
 }
References mChar.
Referenced by Reset().
Update()
void cSceneKinChar::Update (double time_elapsed) virtual
Reimplemented from cScene.
Definition at line 32 of file SceneKinChar.cpp.
 {
     UpdateCharacters(time_elapsed);
 }
References UpdateCharacters().
UpdateCharacters()
void cSceneKinChar::UpdateCharacters (double timestep) protected virtual
Definition at line 108 of file SceneKinChar.cpp.
 {
     mChar->Update(timestep);
 }
References mChar.
Referenced by Update().
Member Data Documentation
mChar
std::shared_ptr<cKinCharacter> cSceneKinChar::mChar protected
Definition at line 31 of file SceneKinChar.h.
Referenced by BuildCharacters(), Clear(), GetCharacter(), ResetCharacters(), and UpdateCharacters().
mCharParams
cKinCharacter::tParams cSceneKinChar::mCharParams protected
Definition at line 30 of file SceneKinChar.h.
Referenced by BuildCharacters(), and ParseArgs().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/SceneKinChar.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/SceneKinChar.cpp