My Project: Json Namespace Reference
Json Namespace Reference
JSON (JavaScript Object Notation).
Namespaces
anonymous_namespace{json_writer.cpp}
Classes
struct BuiltStyledStreamWriter
class CharReader
class CharReaderBuilder
Build a CharReader implementation.
struct CommentStyle
Scoped enums are not available until C++11.
class Exception
class FastWriter
Outputs a Value in JSON format without formatting (not human friendly).
class Features
Configuration passed to reader and writer. This configuration object can be used to force the Reader or Writer to behave in a standard conforming way.
class LogicError
class OurCharReader
class OurFeatures
class OurReader
class Path
Experimental and untested: represents a "path" to access a node.
class PathArgument
Experimental and untested: represents an element of the "path" to access a node.
class Reader
Unserialize a JSON document into a Value.
class RuntimeError
class SecureAllocator
class StaticString
Lightweight wrapper to tag static string.
class StreamWriter
class StreamWriterBuilder
Build a StreamWriter implementation.
class StyledStreamWriter
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
class StyledWriter
Writes a Value in JSON format in a human friendly way.
class Value
Represents a JSON value.
class ValueConstIterator
const iterator for object and array value.
class ValueIterator
Iterator for object and array value.
class ValueIteratorBase
base class for Value iterators.
class Writer
Abstract class for writers.
Typedefs
typedef int Int
typedef unsigned int UInt
typedef int64_t Int64
typedef uint64_t UInt64
typedef Int64 LargestInt
typedef UInt64 LargestUInt
typedef unsigned int ArrayIndex
typedef std::auto_ptr< CharReader > CharReaderPtr
typedef char UIntToStringBuffer[uintToStringBufferSize]
typedef std::auto_ptr< StreamWriter > StreamWriterPtr
Enumerations
enum { uintToStringBufferSize = 3 * sizeof(LargestUInt) + 1 }
enum ValueType {
nullValue = 0, intValue, uintValue, realValue,
stringValue, booleanValue, arrayValue, objectValue
}
Type of the value held by a Value object.
enum CommentPlacement { commentBefore = 0, commentAfterOnSameLine, commentAfter, numberOfCommentPlacement }
Functions
template<typename T , typename U >
bool operator== (const SecureAllocator< T > &, const SecureAllocator< U > &)
template<typename T , typename U >
bool operator!= (const SecureAllocator< T > &, const SecureAllocator< U > &)
static bool containsNewLine (Reader::Location begin, Reader::Location end)
static JSONCPP_STRING normalizeEOL (Reader::Location begin, Reader::Location end)
static void getValidReaderKeys (std::set< JSONCPP_STRING > *valid_keys)
bool parseFromStream (CharReader::Factory const &fact, JSONCPP_ISTREAM &sin, Value *root, JSONCPP_STRING *errs)
JSONCPP_ISTREAM & operator>> (JSONCPP_ISTREAM &, Value &)
Read from 'sin' into 'root'.
static char getDecimalPoint ()
static JSONCPP_STRING codePointToUTF8 (unsigned int cp)
Converts a unicode code-point to UTF-8.
static bool isControlCharacter (char ch)
Returns true if ch is a control character (in range [1,31]).
static void uintToString (LargestUInt value, char *&current)
static void fixNumericLocale (char *begin, char *end)
static void fixNumericLocaleInput (char *begin, char *end)
template<typename T , typename U >
static bool InRange (double d, T min, U max)
static char * duplicateStringValue (const char *value, size_t length)
static char * duplicateAndPrefixStringValue (const char *value, unsigned int length)
static void decodePrefixedString (bool isPrefixed, char const *prefixed, unsigned *length, char const **value)
static void releasePrefixedStringValue (char *value)
static void releaseStringValue (char *value, unsigned)
JSONCPP_NORETURN void throwRuntimeError (JSONCPP_STRING const &msg)
used internally
JSONCPP_NORETURN void throwLogicError (JSONCPP_STRING const &msg)
used internally
static bool IsIntegral (double d)
static bool containsControlCharacter (const char *str)
static bool containsControlCharacter0 (const char *str, unsigned len)
JSONCPP_STRING valueToString (LargestInt value)
JSONCPP_STRING valueToString (LargestUInt value)
JSONCPP_STRING valueToString (Int value)
JSONCPP_STRING valueToString (UInt value)
JSONCPP_STRING valueToString (double value)
JSONCPP_STRING valueToString (bool value)
JSONCPP_STRING valueToQuotedString (const char *value)
static char const * strnpbrk (char const *s, char const *accept, size_t n)
static JSONCPP_STRING valueToQuotedStringN (const char *value, unsigned length)
static void getValidWriterKeys (std::set< JSONCPP_STRING > *valid_keys)
JSONCPP_STRING writeString (StreamWriter::Factory const &factory, Value const &root)
Write into stringstream, then return string, for convenience. A StreamWriter will be created from the factory, used, and then deleted.
JSONCPP_OSTREAM & operator<< (JSONCPP_OSTREAM &, const Value &root)
Output using the StyledStreamWriter.
bool JSON_API parseFromStream (CharReader::Factory const &, JSONCPP_ISTREAM &, Value *root, std::string *errs)
Variables
static const double maxUInt64AsDouble = 18446744073709551615.0
Detailed Description
JSON (JavaScript Object Notation).
Typedef Documentation
ArrayIndex
typedef unsigned int Json::ArrayIndex
Definition at line 23 of file forwards.h.
CharReaderPtr
typedef std::auto_ptr<CharReader> Json::CharReaderPtr
Definition at line 60 of file json_reader.cpp.
Int
typedef int Json::Int
Definition at line 150 of file config.h.
Int64
typedef int64_t Json::Int64
Definition at line 162 of file config.h.
LargestInt
typedef Int64 Json::LargestInt
Definition at line 165 of file config.h.
LargestUInt
typedef UInt64 Json::LargestUInt
Definition at line 166 of file config.h.
StreamWriterPtr
typedef std::auto_ptr<StreamWriter> Json::StreamWriterPtr
Definition at line 81 of file json_writer.cpp.
UInt
typedef unsigned int Json::UInt
Definition at line 151 of file config.h.
UInt64
typedef uint64_t Json::UInt64
Definition at line 163 of file config.h.
UIntToStringBuffer
typedef char Json::UIntToStringBuffer[uintToStringBufferSize]
Definition at line 74 of file json_tool.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
uintToStringBufferSize
Constant that specify the size of the buffer that must be passed to uintToString.
Definition at line 67 of file json_tool.h.
      {
   uintToStringBufferSize = 3 * sizeof(LargestUInt) + 1
 };
CommentPlacement
enum Json::CommentPlacement
Enumerator
commentBefore
a comment placed on the line before a value
commentAfterOnSameLine
a comment just after a value on the same line
commentAfter
a comment on the line after a value (only make sense for
numberOfCommentPlacement
root value)
Definition at line 104 of file value.h.
                       {
   commentBefore = 0,
   commentAfterOnSameLine,
   commentAfter,
   numberOfCommentPlacement
 };
ValueType
enum Json::ValueType
Type of the value held by a Value object.
Enumerator
nullValue
'null' value
intValue
signed integer value
uintValue
unsigned integer value
realValue
double value
stringValue
UTF-8 string value.
booleanValue
bool value
arrayValue
array value (ordered list)
objectValue
object value (collection of name/value pairs).
Definition at line 93 of file value.h.
                {
   nullValue = 0,
   intValue,
   uintValue,
   realValue,
   stringValue,
   booleanValue,
   arrayValue,
   objectValue
 };
Function Documentation
codePointToUTF8()
static JSONCPP_STRING Json::codePointToUTF8 (unsigned int cp) inline static
Converts a unicode code-point to UTF-8.
Definition at line 36 of file json_tool.h.
{
   JSONCPP_STRING result;
   // based on description from http://en.wikipedia.org/wiki/UTF-8
   if (cp <= 0x7f) {
     result.resize(1);
     result[0] = static_cast<char>(cp);
   } else if (cp <= 0x7FF) {
     result.resize(2);
     result[1] = static_cast<char>(0x80 | (0x3f & cp));
     result[0] = static_cast<char>(0xC0 | (0x1f & (cp >> 6)));
   } else if (cp <= 0xFFFF) {
     result.resize(3);
     result[2] = static_cast<char>(0x80 | (0x3f & cp));
     result[1] = static_cast<char>(0x80 | (0x3f & (cp >> 6)));
     result[0] = static_cast<char>(0xE0 | (0xf & (cp >> 12)));
   } else if (cp <= 0x10FFFF) {
     result.resize(4);
     result[3] = static_cast<char>(0x80 | (0x3f & cp));
     result[2] = static_cast<char>(0x80 | (0x3f & (cp >> 6)));
     result[1] = static_cast<char>(0x80 | (0x3f & (cp >> 12)));
     result[0] = static_cast<char>(0xF0 | (0x7 & (cp >> 18)));
   }
   return result;
 }
References JSONCPP_STRING.
Referenced by Json::Reader::decodeString(), and Json::OurReader::decodeString().
containsControlCharacter()
static bool Json::containsControlCharacter (const char * str) static
Definition at line 84 of file json_writer.cpp.
{
   while (*str) {
     if (isControlCharacter(*(str++)))
       return true;
   }
   return false;
 }
References isControlCharacter().
Referenced by valueToQuotedString().
containsControlCharacter0()
static bool Json::containsControlCharacter0 (const char * str, unsigned len) static
Definition at line 92 of file json_writer.cpp.
{
   char const* end = str + len;
   while (end != str) {
     if (isControlCharacter(*str) || 0==*str)
       return true;
     ++str;
   }
   return false;
 }
References isControlCharacter().
Referenced by valueToQuotedStringN().
containsNewLine()
static bool Json::containsNewLine (Reader::Location begin, Reader::Location end) static
Definition at line 84 of file json_reader.cpp.
{
   for (; begin < end; ++begin)
     if (*begin == '\n' || *begin == '\r')
       return true;
   return false;
 }
Referenced by Json::Reader::readComment(), and Json::OurReader::readComment().
decodePrefixedString()
static void Json::decodePrefixedString (bool isPrefixed, char const * prefixed, unsigned * length, char const ** value) inline static
Definition at line 139 of file json_value.cpp.
 {
   if (!isPrefixed) {
     *length = static_cast<unsigned>(strlen(prefixed));
     *value = prefixed;
   } else {
     *length = *reinterpret_cast<unsigned const*>(prefixed);
     *value = prefixed + sizeof(unsigned);
   }
 }
Referenced by Json::Value::asCString(), Json::Value::asString(), Json::Value::getString(), Json::Value::operator<(), Json::Value::operator==(), and Json::Value::Value().
duplicateAndPrefixStringValue()
static char* Json::duplicateAndPrefixStringValue (const char * value, unsigned int length) inline static
Definition at line 118 of file json_value.cpp.
 {
   // Avoid an integer overflow in the call to malloc below by limiting length
   // to a sane value.
   JSON_ASSERT_MESSAGE(length <= static_cast<unsigned>(Value::maxInt) - sizeof(unsigned) - 1U,
                       "in Json::Value::duplicateAndPrefixStringValue(): "
                       "length too big for prefixing");
   unsigned actualLength = length + static_cast<unsigned>(sizeof(unsigned)) + 1U;
   char* newString = static_cast<char*>(malloc(actualLength));
   if (newString == 0) {
     throwRuntimeError(
         "in Json::Value::duplicateAndPrefixStringValue(): "
         "Failed to allocate string value buffer");
   }
   *reinterpret_cast<unsigned*>(newString) = length;
   memcpy(newString + sizeof(unsigned), value, length);
   newString[actualLength - 1U] = 0; // to avoid buffer over-run accidents by users later
   return newString;
 }
References JSON_ASSERT_MESSAGE, Json::Value::maxInt, and throwRuntimeError().
Referenced by Json::Value::Value().
duplicateStringValue()
static char* Json::duplicateStringValue (const char * value, size_t length) inline static
Duplicates the specified string value.
Parameters
value Pointer to the string to duplicate. Must be zero-terminated if length is "unknown".
length Length of the value. if equals to unknown, then it will be computed using strlen(value).
Returns
Pointer on the duplicate instance of string.
Definition at line 97 of file json_value.cpp.
 {
   // Avoid an integer overflow in the call to malloc below by limiting length
   // to a sane value.
   if (length >= static_cast<size_t>(Value::maxInt))
     length = Value::maxInt - 1;
   char* newString = static_cast<char*>(malloc(length + 1));
   if (newString == NULL) {
     throwRuntimeError(
         "in Json::Value::duplicateStringValue(): "
         "Failed to allocate string value buffer");
   }
   memcpy(newString, value, length);
   newString[length] = 0;
   return newString;
 }
References Json::Value::maxInt, and throwRuntimeError().
Referenced by Json::Value::CZString::CZString(), and Json::Value::CommentInfo::setComment().
fixNumericLocale()
static void Json::fixNumericLocale (char * begin, char * end) inline static
Change ',' to '.' everywhere in buffer.
We had a sophisticated way, but it did not work in WinCE.
See also
https://github.com/open-source-parsers/jsoncpp/pull/9
Definition at line 94 of file json_tool.h.
{
   while (begin < end) {
     if (*begin == ',') {
       *begin = '.';
     }
     ++begin;
   }
 }
Referenced by Json::anonymous_namespace{json_writer.cpp}::valueToString().
fixNumericLocaleInput()
static void Json::fixNumericLocaleInput (char * begin, char * end) inline static
Definition at line 103 of file json_tool.h.
{
   char decimalPoint = getDecimalPoint();
   if (decimalPoint != '\0' && decimalPoint != '.') {
     while (begin < end) {
       if (*begin == '.') {
         *begin = decimalPoint;
       }
       ++begin;
     }
   }
 }
References getDecimalPoint().
Referenced by Json::OurReader::decodeDouble().
getDecimalPoint()
static char Json::getDecimalPoint () static
Definition at line 26 of file json_tool.h.
{
 #ifdef JSONCPP_NO_LOCALE_SUPPORT
   return '\0';
 #else
   struct lconv* lc = localeconv();
   return lc ? *(lc->decimal_point) : '\0';
 #endif
 }
Referenced by fixNumericLocaleInput().
getValidReaderKeys()
static void Json::getValidReaderKeys (std::set< JSONCPP_STRING > * valid_keys) static
Definition at line 1938 of file json_reader.cpp.
 {
   valid_keys->clear();
   valid_keys->insert("collectComments");
   valid_keys->insert("allowComments");
   valid_keys->insert("strictRoot");
   valid_keys->insert("allowDroppedNullPlaceholders");
   valid_keys->insert("allowNumericKeys");
   valid_keys->insert("allowSingleQuotes");
   valid_keys->insert("stackLimit");
   valid_keys->insert("failIfExtra");
   valid_keys->insert("rejectDupKeys");
   valid_keys->insert("allowSpecialFloats");
 }
Referenced by Json::CharReaderBuilder::validate().
getValidWriterKeys()
static void Json::getValidWriterKeys (std::set< JSONCPP_STRING > * valid_keys) static
Definition at line 1166 of file json_writer.cpp.
 {
   valid_keys->clear();
   valid_keys->insert("indentation");
   valid_keys->insert("commentStyle");
   valid_keys->insert("enableYAMLCompatibility");
   valid_keys->insert("dropNullPlaceholders");
   valid_keys->insert("useSpecialFloats");
   valid_keys->insert("precision");
 }
Referenced by Json::StreamWriterBuilder::validate().
InRange()
template<typename T , typename U > static bool Json::InRange (double d, T min, U max) inline static
Definition at line 69 of file json_value.cpp.
{
   // The casts can lose precision, but we are looking only for
   // an approximate range. Might fail on edge cases though. ~cdunn
   //return d >= static_cast<double>(min) && d <= static_cast<double>(max);
   return d >= min && d <= max;
 }
Referenced by Json::Value::asInt(), Json::Value::asInt64(), Json::Value::asUInt(), Json::Value::asUInt64(), and Json::Value::isConvertibleTo().
isControlCharacter()
static bool Json::isControlCharacter (char ch) inline static
Returns true if ch is a control character (in range [1,31]).
Definition at line 65 of file json_tool.h.
 { return ch > 0 && ch <= 0x1F; }
Referenced by containsControlCharacter(), containsControlCharacter0(), valueToQuotedString(), and valueToQuotedStringN().
IsIntegral()
static bool Json::IsIntegral (double d) static
Definition at line 1271 of file json_value.cpp.
{
   double integral_part;
   return modf(d, &integral_part) == 0.0;
 }
Referenced by Json::Value::isInt(), Json::Value::isInt64(), Json::Value::isIntegral(), Json::Value::isUInt(), and Json::Value::isUInt64().
normalizeEOL()
static JSONCPP_STRING Json::normalizeEOL (Reader::Location begin, Reader::Location end) static
Definition at line 373 of file json_reader.cpp.
{
   JSONCPP_STRING normalized;
   normalized.reserve(static_cast<size_t>(end - begin));
   Reader::Location current = begin;
   while (current != end) {
     char c = *current++;
     if (c == '\r') {
       if (current != end && *current == '\n')
          // convert dos EOL
          ++current;
       // convert Mac EOL
       normalized += '\n';
     } else {
       normalized += c;
     }
   }
   return normalized;
 }
References JSONCPP_STRING, and Json::Reader::Location.
Referenced by Json::Reader::addComment(), and Json::OurReader::addComment().
operator!=()
template<typename T , typename U > bool Json::operator!= (const SecureAllocator< T > & , const SecureAllocator< U > &)
Definition at line 90 of file allocator.h.
{
     return false;
 }
operator<<()
JSON_API JSONCPP_OSTREAM & Json::operator<< (JSONCPP_OSTREAM & , const Value & root)
Output using the StyledStreamWriter.
See also
Json::operator>>()
Definition at line 1217 of file json_writer.cpp.
{
   StreamWriterBuilder builder;
   StreamWriterPtr const writer(builder.newStreamWriter());
   writer->write(root, &sout);
   return sout;
 }
References Json::StreamWriterBuilder::newStreamWriter().
operator==()
template<typename T , typename U > bool Json::operator== (const SecureAllocator< T > & , const SecureAllocator< U > &)
Definition at line 85 of file allocator.h.
{
     return true;
 }
operator>>()
JSON_API JSONCPP_ISTREAM & Json::operator>> (JSONCPP_ISTREAM & , Value &)
Read from 'sin' into 'root'.
Always keep comments from the input JSON.
This can be used to read a file into a particular sub-object. For example:
Json::Value root;
cin >> root["dir"]["file"];
cout << root;
Result:
{
"dir": {
    "file": {
    // The input stream JSON would be nested here.
    }
}
}
Exceptions
std::exception on parse error.
See also
Json::operator<<()
Definition at line 2022 of file json_reader.cpp.
{
   CharReaderBuilder b;
   JSONCPP_STRING errs;
   bool ok = parseFromStream(b, sin, &root, &errs);
   if (!ok) {
     fprintf(stderr,
             "Error from reader: %s",
             errs.c_str());
     throwRuntimeError(errs);
   }
   return sin;
 }
References JSONCPP_STRING, parseFromStream(), and throwRuntimeError().
parseFromStream() [1/2]
bool JSON_API Json::parseFromStream (CharReader::Factory const & , JSONCPP_ISTREAM & , Value * root, std::string * errs)
Consume entire stream and use its begin/end. Someday we might have a real StreamReader, but for now this is convenient.
parseFromStream() [2/2]
bool Json::parseFromStream (CharReader::Factory const & fact, JSONCPP_ISTREAM & sin, Value * root, JSONCPP_STRING * errs)
Definition at line 2008 of file json_reader.cpp.
 {
   JSONCPP_OSTRINGSTREAM ssin;
   ssin << sin.rdbuf();
   JSONCPP_STRING doc = ssin.str();
   char const* begin = doc.data();
   char const* end = begin + doc.size();
   // Note that we do not actually need a null-terminator.
   CharReaderPtr const reader(fact.newCharReader());
   return reader->parse(begin, end, root, errs);
 }
References JSONCPP_OSTRINGSTREAM, JSONCPP_STRING, and Json::CharReader::Factory::newCharReader().
Referenced by operator>>().
releasePrefixedStringValue()
static void Json::releasePrefixedStringValue (char * value) inline static
Free the string duplicated by duplicateStringValue()/duplicateAndPrefixStringValue().
Definition at line 169 of file json_value.cpp.
{
   free(value);
 }
Referenced by Json::Value::~Value().
releaseStringValue()
static void Json::releaseStringValue (char * value, unsigned) inline static
Definition at line 172 of file json_value.cpp.
{
   free(value);
 }
Referenced by Json::Value::CommentInfo::setComment(), Json::Value::CommentInfo::~CommentInfo(), and Json::Value::CZString::~CZString().
strnpbrk()
static char const* Json::strnpbrk (char const * s, char const * accept, size_t n) static
Definition at line 243 of file json_writer.cpp.
{
   assert((s || !n) && accept);
   char const* const end = s + n;
   for (char const* cur = s; cur < end; ++cur) {
     int const c = *cur;
     for (char const* a = accept; *a; ++a) {
       if (*a == c) {
         return cur;
       }
     }
   }
   return NULL;
 }
Referenced by valueToQuotedStringN().
throwLogicError()
JSONCPP_NORETURN void Json::throwLogicError (JSONCPP_STRING const & msg)
used internally
Definition at line 212 of file json_value.cpp.
 {
   throw LogicError(msg);
 }
throwRuntimeError()
JSONCPP_NORETURN void Json::throwRuntimeError (JSONCPP_STRING const & msg)
used internally
Definition at line 208 of file json_value.cpp.
 {
   throw RuntimeError(msg);
 }
Referenced by duplicateAndPrefixStringValue(), duplicateStringValue(), Json::StreamWriterBuilder::newStreamWriter(), operator>>(), Json::OurReader::readObject(), Json::Reader::readValue(), Json::OurReader::readValue(), and Json::ValueIterator::ValueIterator().
uintToString()
static void Json::uintToString (LargestUInt value, char *& current) inline static
Converts an unsigned integer to string.
Parameters
value Unsigned interger to convert to string
current Input/Output string buffer. Must have at least uintToStringBufferSize chars free.
Definition at line 81 of file json_tool.h.
{
   *--current = 0;
   do {
     *--current = static_cast<char>(value % 10U + static_cast<unsigned>('0'));
     value /= 10;
   } while (value != 0);
 }
Referenced by valueToString().
valueToQuotedString()
JSONCPP_STRING JSON_API Json::valueToQuotedString (const char * value)
Definition at line 180 of file json_writer.cpp.
{
   if (value == NULL)
     return "";
   // Not sure how to handle unicode...
   if (strpbrk(value, "\"\\\b\f\n\r\t") == NULL &&
       !containsControlCharacter(value))
     return JSONCPP_STRING("\"") + value + "\"";
   // We have to walk value and escape any special characters.
   // Appending to JSONCPP_STRING is not efficient, but this should be rare.
   // (Note: forward slashes are *not* rare, but I am not escaping them.)
   JSONCPP_STRING::size_type maxsize =
       strlen(value) * 2 + 3; // allescaped+quotes+NULL
   JSONCPP_STRING result;
   result.reserve(maxsize); // to avoid lots of mallocs
   result += "\"";
   for (const char* c = value; *c != 0; ++c) {
     switch (*c) {
     case '\"':
       result += "\\\"";
       break;
     case '\\':
       result += "\\\\";
       break;
     case '\b':
       result += "\\b";
       break;
     case '\f':
       result += "\\f";
       break;
     case '\n':
       result += "\\n";
       break;
     case '\r':
       result += "\\r";
       break;
     case '\t':
       result += "\\t";
       break;
     // case '/':
     // Even though \/ is considered a legal escape in JSON, a bare
     // slash is also legal, so I see no reason to escape it.
     // (I hope I am not misunderstanding something.
     // blep notes: actually escaping \/ may be useful in javascript to avoid </
     // sequence.
     // Should add a flag to allow this compatibility mode and prevent this
     // sequence from occurring.
     default:
       if (isControlCharacter(*c)) {
         JSONCPP_OSTRINGSTREAM oss;
         oss << "\\u" << std::hex << std::uppercase << std::setfill('0')
             << std::setw(4) << static_cast<int>(*c);
         result += oss.str();
       } else {
         result += *c;
       }
       break;
     }
   }
   result += "\"";
   return result;
 }
References containsControlCharacter(), isControlCharacter(), JSONCPP_OSTRINGSTREAM, and JSONCPP_STRING.
Referenced by Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
valueToQuotedStringN()
static JSONCPP_STRING Json::valueToQuotedStringN (const char * value, unsigned length) static
Definition at line 257 of file json_writer.cpp.
{
   if (value == NULL)
     return "";
   // Not sure how to handle unicode...
   if (strnpbrk(value, "\"\\\b\f\n\r\t", length) == NULL &&
       !containsControlCharacter0(value, length))
     return JSONCPP_STRING("\"") + value + "\"";
   // We have to walk value and escape any special characters.
   // Appending to JSONCPP_STRING is not efficient, but this should be rare.
   // (Note: forward slashes are *not* rare, but I am not escaping them.)
   JSONCPP_STRING::size_type maxsize =
       length * 2 + 3; // allescaped+quotes+NULL
   JSONCPP_STRING result;
   result.reserve(maxsize); // to avoid lots of mallocs
   result += "\"";
   char const* end = value + length;
   for (const char* c = value; c != end; ++c) {
     switch (*c) {
     case '\"':
       result += "\\\"";
       break;
     case '\\':
       result += "\\\\";
       break;
     case '\b':
       result += "\\b";
       break;
     case '\f':
       result += "\\f";
       break;
     case '\n':
       result += "\\n";
       break;
     case '\r':
       result += "\\r";
       break;
     case '\t':
       result += "\\t";
       break;
     // case '/':
     // Even though \/ is considered a legal escape in JSON, a bare
     // slash is also legal, so I see no reason to escape it.
     // (I hope I am not misunderstanding something.)
     // blep notes: actually escaping \/ may be useful in javascript to avoid </
     // sequence.
     // Should add a flag to allow this compatibility mode and prevent this
     // sequence from occurring.
     default:
       if ((isControlCharacter(*c)) || (*c == 0)) {
         JSONCPP_OSTRINGSTREAM oss;
         oss << "\\u" << std::hex << std::uppercase << std::setfill('0')
             << std::setw(4) << static_cast<int>(*c);
         result += oss.str();
       } else {
         result += *c;
       }
       break;
     }
   }
   result += "\"";
   return result;
 }
References containsControlCharacter0(), isControlCharacter(), JSONCPP_OSTRINGSTREAM, JSONCPP_STRING, and strnpbrk().
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
valueToString() [1/6]
JSONCPP_STRING JSON_API Json::valueToString (bool value)
Definition at line 178 of file json_writer.cpp.
 { return value ? "true" : "false"; }
valueToString() [2/6]
JSONCPP_STRING JSON_API Json::valueToString (double value)
Definition at line 176 of file json_writer.cpp.
 { return valueToString(value, false, 17); }
References valueToString().
valueToString() [3/6]
JSONCPP_STRING JSON_API Json::valueToString (Int value)
Definition at line 128 of file json_writer.cpp.
{
   return valueToString(LargestInt(value));
 }
References valueToString().
valueToString() [4/6]
JSONCPP_STRING JSON_API Json::valueToString (LargestInt value)
Definition at line 102 of file json_writer.cpp.
{
   UIntToStringBuffer buffer;
   char* current = buffer + sizeof(buffer);
   if (value == Value::minLargestInt) {
     uintToString(LargestUInt(Value::maxLargestInt) + 1, current);
     *--current = '-';
   } else if (value < 0) {
     uintToString(LargestUInt(-value), current);
     *--current = '-';
   } else {
     uintToString(LargestUInt(value), current);
   }
   assert(current >= buffer);
   return current;
 }
References Json::Value::maxLargestInt, Json::Value::minLargestInt, and uintToString().
Referenced by Json::Value::asString(), valueToString(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
valueToString() [5/6]
JSONCPP_STRING JSON_API Json::valueToString (LargestUInt value)
Definition at line 118 of file json_writer.cpp.
{
   UIntToStringBuffer buffer;
   char* current = buffer + sizeof(buffer);
   uintToString(value, current);
   assert(current >= buffer);
   return current;
 }
References uintToString().
valueToString() [6/6]
JSONCPP_STRING JSON_API Json::valueToString (UInt value)
Definition at line 132 of file json_writer.cpp.
{
   return valueToString(LargestUInt(value));
 }
References valueToString().
writeString()
JSONCPP_STRING JSON_API Json::writeString (StreamWriter::Factory const & builder, Value const & root)
Write into stringstream, then return string, for convenience. A StreamWriter will be created from the factory, used, and then deleted.
Definition at line 1210 of file json_writer.cpp.
{
   JSONCPP_OSTRINGSTREAM sout;
   StreamWriterPtr const writer(builder.newStreamWriter());
   writer->write(root, &sout);
   return sout.str();
 }
References JSONCPP_OSTRINGSTREAM, and Json::StreamWriter::Factory::newStreamWriter().
Variable Documentation
maxUInt64AsDouble
const double Json::maxUInt64AsDouble = 18446744073709551615.0 static
Definition at line 61 of file json_value.cpp.
Referenced by Json::Value::isIntegral(), and Json::Value::isUInt64().