My Project: std Namespace Reference
std Namespace Reference
Functions
template<>
void swap (Json::Value &a, Json::Value &b)
Specialize std::swap() for Json::Value.
Function Documentation
swap()
template<> void std::swap (Json::Value & a, Json::Value & b) inline
Specialize std::swap() for Json::Value.
Definition at line 861 of file value.h.
 { a.swap(b); }
References Json::Value::swap().
Referenced by Json::Reader::parse(), Json::Value::CZString::swap(), Json::Value::swap(), and Json::Value::swapPayload().