My Project: lodepng::ExtractZlib::HuffmanTree Struct Reference
lodepng::ExtractZlib::HuffmanTree Struct Reference
Public Member Functions
int makeFromLengths (const std::vector< unsigned long > &bitlen, unsigned long maxbitlen)
int decode (bool &decoded, unsigned long &result, size_t &treepos, unsigned long bit) const
Public Attributes
std::vector< unsigned long > tree2d
Detailed Description
Definition at line 320 of file lodepng_util.cpp.
Member Function Documentation
decode()
int lodepng::ExtractZlib::HuffmanTree::decode (bool & decoded, unsigned long & result, size_t & treepos, unsigned long bit) const inline
Definition at line 359 of file lodepng_util.cpp.
     { //Decodes a symbol from the tree
       unsigned long numcodes = (unsigned long)tree2d.size() / 2;
       if(treepos >= numcodes) return 11; //error: you appeared outside the codetree
       result = tree2d[2 * treepos + bit];
       decoded = (result < numcodes);
       treepos = decoded ? 0 : result - numcodes;
       return 0;
     }
References tree2d.
Referenced by lodepng::ExtractZlib::huffmanDecodeSymbol().
makeFromLengths()
int lodepng::ExtractZlib::HuffmanTree::makeFromLengths (const std::vector< unsigned long > & bitlen, unsigned long maxbitlen) inline
Definition at line 322 of file lodepng_util.cpp.
     { //make tree given the lengths
       unsigned long numcodes = (unsigned long)(bitlen.size()), treepos = 0, nodefilled = 0;
       std::vector<unsigned long> tree1d(numcodes), blcount(maxbitlen + 1, 0), nextcode(maxbitlen + 1, 0);
       //count number of instances of each code length
       for(unsigned long bits = 0; bits < numcodes; bits++) blcount[bitlen[bits]]++;
       for(unsigned long bits = 1; bits <= maxbitlen; bits++)
       {
         nextcode[bits] = (nextcode[bits - 1] + blcount[bits - 1]) << 1;
       }
       //generate all the codes
       for(unsigned long n = 0; n < numcodes; n++) if(bitlen[n] != 0) tree1d[n] = nextcode[bitlen[n]]++;
       tree2d.clear(); tree2d.resize(numcodes * 2, 32767); //32767 here means the tree2d isn't filled there yet
       for(unsigned long n = 0; n < numcodes; n++) //the codes
       for(unsigned long i = 0; i < bitlen[n]; i++) //the bits for this code
       {
         unsigned long bit = (tree1d[n] >> (bitlen[n] - i - 1)) & 1;
         if(treepos > numcodes - 2) return 55;
         if(tree2d[2 * treepos + bit] == 32767) //not yet filled in
         {
           if(i + 1 == bitlen[n])
           {
             //last bit
             tree2d[2 * treepos + bit] = n;
             treepos = 0;
           }
           else
           {
             //addresses are encoded as values > numcodes
             tree2d[2 * treepos + bit] = ++nodefilled + numcodes;
             treepos = nodefilled;
           }
         }
         else treepos = tree2d[2 * treepos + bit] - numcodes; //subtract numcodes from address to get address value
       }
       return 0;
     }
References tree2d.
Referenced by lodepng::ExtractZlib::generateFixedTrees(), and lodepng::ExtractZlib::getTreeInflateDynamic().
Member Data Documentation
tree2d
std::vector<unsigned long> lodepng::ExtractZlib::HuffmanTree::tree2d
Definition at line 369 of file lodepng_util.cpp.
Referenced by decode(), and makeFromLengths().
The documentation for this struct was generated from the following file:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/lodepng/lodepng_util.cpp