My Project: lodepng::ExtractPNG Struct Reference
lodepng::ExtractPNG Struct Reference
Public Member Functions
ExtractPNG (std::vector< ZlibBlockInfo > *info)
void decode (const unsigned char *in, size_t size)
void readPngHeader (const unsigned char *in, size_t inlength)
unsigned long readBitFromReversedStream (size_t &bitp, const unsigned char *bits)
unsigned long readBitsFromReversedStream (size_t &bitp, const unsigned char *bits, unsigned long nbits)
void setBitOfReversedStream (size_t &bitp, unsigned char *bits, unsigned long bit)
unsigned long read32bitInt (const unsigned char *buffer)
Public Attributes
std::vector< ZlibBlockInfo > * zlibinfo
int error
Detailed Description
Definition at line 577 of file lodepng_util.cpp.
Constructor & Destructor Documentation
ExtractPNG()
lodepng::ExtractPNG::ExtractPNG (std::vector< ZlibBlockInfo > * info) inline
Definition at line 580 of file lodepng_util.cpp.
 : zlibinfo(info) {};
Member Function Documentation
decode()
void lodepng::ExtractPNG::decode (const unsigned char * in, size_t size) inline
Definition at line 582 of file lodepng_util.cpp.
   {
     error = 0;
     if(size == 0 || in == 0) { error = 48; return; } //the given data is empty
     readPngHeader(&in[0], size); if(error) return;
     size_t pos = 33; //first byte of the first chunk after the header
     std::vector<unsigned char> idat; //the data from idat chunks
     bool IEND = false;
     //loop through the chunks, ignoring unknown chunks and stopping at IEND chunk.
     //IDAT data is put at the start of the in buffer
     while(!IEND)
     {
       //error: size of the in buffer too small to contain next chunk
       if(pos + 8 >= size) { error = 30; return; }
       size_t chunkLength = read32bitInt(&in[pos]); pos += 4;
       if(chunkLength > 2147483647) { error = 63; return; }
       //error: size of the in buffer too small to contain next chunk
       if(pos + chunkLength >= size) { error = 35; return; }
       //IDAT chunk, containing compressed image data
       if(in[pos + 0] == 'I' && in[pos + 1] == 'D' && in[pos + 2] == 'A' && in[pos + 3] == 'T')
       {
         idat.insert(idat.end(), &in[pos + 4], &in[pos + 4 + chunkLength]);
         pos += (4 + chunkLength);
       }
       else if(in[pos + 0] == 'I' && in[pos + 1] == 'E' && in[pos + 2] == 'N' && in[pos + 3] == 'D')
       {
           pos += 4;
           IEND = true;
       }
       else //it's not an implemented chunk type, so ignore it: skip over the data
       {
         pos += (chunkLength + 4); //skip 4 letters and uninterpreted data of unimplemented chunk
       }
       pos += 4; //step over CRC (which is ignored)
     }
     std::vector<unsigned char> out; //now the out buffer will be filled
     ExtractZlib zlib(zlibinfo); //decompress with the Zlib decompressor
     error = zlib.decompress(out, idat);
     if(error) return; //stop if the zlib decompressor returned an error
   }
References lodepng::ExtractZlib::decompress(), error, read32bitInt(), readPngHeader(), and zlibinfo.
Referenced by lodepng::extractZlibInfo().
read32bitInt()
unsigned long lodepng::ExtractPNG::read32bitInt (const unsigned char * buffer) inline
Definition at line 652 of file lodepng_util.cpp.
   {
     return (unsigned int)((buffer[0] << 24u) | (buffer[1] << 16u) | (buffer[2] << 8u) | buffer[3]);
   }
Referenced by decode().
readBitFromReversedStream()
unsigned long lodepng::ExtractPNG::readBitFromReversedStream (size_t & bitp, const unsigned char * bits) inline
Definition at line 633 of file lodepng_util.cpp.
   {
     unsigned long result = (bits[bitp >> 3] >> (7 - (bitp & 0x7))) & 1;
     bitp++;
     return result;
   }
Referenced by readBitsFromReversedStream().
readBitsFromReversedStream()
unsigned long lodepng::ExtractPNG::readBitsFromReversedStream (size_t & bitp, const unsigned char * bits, unsigned long nbits) inline
Definition at line 640 of file lodepng_util.cpp.
   {
     unsigned long result = 0;
     for(size_t i = nbits - 1; i < nbits; i--) result += ((readBitFromReversedStream(bitp, bits)) << i);
     return result;
   }
References readBitFromReversedStream().
readPngHeader()
void lodepng::ExtractPNG::readPngHeader (const unsigned char * in, size_t inlength) inline
Definition at line 624 of file lodepng_util.cpp.
   {
     if(inlength < 29) { error = 27; return; } //error: the data length is smaller than the length of the header
     if(in[0] != 137 || in[1] != 80 || in[2] != 78 || in[3] != 71
     || in[4] != 13 || in[5] != 10 || in[6] != 26 || in[7] != 10) { error = 28; return; } //no PNG signature
     //error: it doesn't start with a IHDR chunk!
     if(in[12] != 'I' || in[13] != 'H' || in[14] != 'D' || in[15] != 'R') { error = 29; return; }
   }
References error.
Referenced by decode().
setBitOfReversedStream()
void lodepng::ExtractPNG::setBitOfReversedStream (size_t & bitp, unsigned char * bits, unsigned long bit) inline
Definition at line 647 of file lodepng_util.cpp.
   {
     bits[bitp >> 3] |=  (bit << (7 - (bitp & 0x7))); bitp++;
   }
Member Data Documentation
error
int lodepng::ExtractPNG::error
Definition at line 580 of file lodepng_util.cpp.
Referenced by decode(), lodepng::extractZlibInfo(), and readPngHeader().
zlibinfo
std::vector<ZlibBlockInfo>* lodepng::ExtractPNG::zlibinfo
Definition at line 579 of file lodepng_util.cpp.
Referenced by decode().
The documentation for this struct was generated from the following file:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/lodepng/lodepng_util.cpp