My Project: lodepng::ExtractZlib Struct Reference
lodepng::ExtractZlib Struct Reference
Classes
struct HuffmanTree
Public Member Functions
ExtractZlib (std::vector< ZlibBlockInfo > *info)
unsigned long readBitFromStream (size_t &bitp, const unsigned char *bits)
unsigned long readBitsFromStream (size_t &bitp, const unsigned char *bits, size_t nbits)
void inflate (std::vector< unsigned char > &out, const std::vector< unsigned char > &in, size_t inpos=0)
void generateFixedTrees (HuffmanTree &tree, HuffmanTree &treeD)
unsigned long huffmanDecodeSymbol (const unsigned char *in, size_t &bp, const HuffmanTree &tree, size_t inlength)
void getTreeInflateDynamic (HuffmanTree &tree, HuffmanTree &treeD, const unsigned char *in, size_t &bp, size_t inlength)
void inflateHuffmanBlock (std::vector< unsigned char > &out, const unsigned char *in, size_t &bp, size_t &pos, size_t inlength, unsigned long btype)
void inflateNoCompression (std::vector< unsigned char > &out, const unsigned char *in, size_t &bp, size_t &pos, size_t inlength)
int decompress (std::vector< unsigned char > &out, const std::vector< unsigned char > &in)
Public Attributes
std::vector< ZlibBlockInfo > * zlibinfo
int error
HuffmanTree codetree
HuffmanTree codetreeD
HuffmanTree codelengthcodetree
Detailed Description
Definition at line 300 of file lodepng_util.cpp.
Constructor & Destructor Documentation
ExtractZlib()
lodepng::ExtractZlib::ExtractZlib (std::vector< ZlibBlockInfo > * info) inline
Definition at line 303 of file lodepng_util.cpp.
 : zlibinfo(info) {};
Member Function Documentation
decompress()
int lodepng::ExtractZlib::decompress (std::vector< unsigned char > & out, const std::vector< unsigned char > & in) inline
Definition at line 562 of file lodepng_util.cpp.
   {
     if(in.size() < 2) { return 53; } //error, size of zlib data too small
     //error: 256 * in[0] + in[1] must be a multiple of 31, the FCHECK value is supposed to be made that way
     if((in[0] * 256 + in[1]) % 31 != 0) { return 24; }
     unsigned long CM = in[0] & 15, CINFO = (in[0] >> 4) & 15, FDICT = (in[1] >> 5) & 1;
     //error: only compression method 8: inflate with sliding window of 32k is supported by the PNG spec
     if(CM != 8 || CINFO > 7) { return 25; }
     //error: the PNG spec says about the zlib stream: "The additional flags shall not specify a preset dictionary."
     if(FDICT != 0) { return 26; }
     inflate(out, in, 2);
     return error; //note: adler32 checksum was skipped and ignored
   }
References error, and inflate().
Referenced by lodepng::ExtractPNG::decode().
generateFixedTrees()
void lodepng::ExtractZlib::generateFixedTrees (HuffmanTree & tree, HuffmanTree & treeD) inline
Definition at line 395 of file lodepng_util.cpp.
   {
     std::vector<unsigned long> bitlen(288, 8), bitlenD(32, 5);;
     for(size_t i = 144; i <= 255; i++) bitlen[i] = 9;
     for(size_t i = 256; i <= 279; i++) bitlen[i] = 7;
     tree.makeFromLengths(bitlen, 15);
     treeD.makeFromLengths(bitlenD, 15);
   }
References lodepng::ExtractZlib::HuffmanTree::makeFromLengths().
Referenced by inflateHuffmanBlock().
getTreeInflateDynamic()
void lodepng::ExtractZlib::getTreeInflateDynamic (HuffmanTree & tree, HuffmanTree & treeD, const unsigned char * in, size_t & bp, size_t inlength) inline
Definition at line 419 of file lodepng_util.cpp.
   {
     size_t bpstart = bp;
     //get the tree of a deflated block with dynamic tree, the tree itself is also Huffman compressed with a known tree
     std::vector<unsigned long> bitlen(288, 0), bitlenD(32, 0);
     if(bp >> 3 >= inlength - 2) { error = 49; return; } //the bit pointer is or will go past the memory
     size_t HLIT =  readBitsFromStream(bp, in, 5) + 257; //number of literal/length codes + 257
     size_t HDIST = readBitsFromStream(bp, in, 5) + 1; //number of dist codes + 1
     size_t HCLEN = readBitsFromStream(bp, in, 4) + 4; //number of code length codes + 4
     zlibinfo->back().hlit = HLIT - 257;
     zlibinfo->back().hdist = HDIST - 1;
     zlibinfo->back().hclen = HCLEN - 4;
     std::vector<unsigned long> codelengthcode(19); //lengths of tree to decode the lengths of the dynamic tree
     for(size_t i = 0; i < 19; i++) codelengthcode[CLCL[i]] = (i < HCLEN) ? readBitsFromStream(bp, in, 3) : 0;
     //code length code lengths
     for(size_t i = 0; i < codelengthcode.size(); i++) zlibinfo->back().clcl.push_back(codelengthcode[i]);
     error = codelengthcodetree.makeFromLengths(codelengthcode, 7); if(error) return;
     size_t i = 0, replength;
     while(i < HLIT + HDIST)
     {
       unsigned long code = huffmanDecodeSymbol(in, bp, codelengthcodetree, inlength); if(error) return;
       zlibinfo->back().treecodes.push_back(code); //tree symbol code
       if(code <= 15)  { if(i < HLIT) bitlen[i++] = code; else bitlenD[i++ - HLIT] = code; } //a length code
       else if(code == 16) //repeat previous
       {
         if(bp >> 3 >= inlength) { error = 50; return; } //error, bit pointer jumps past memory
         replength = 3 + readBitsFromStream(bp, in, 2);
         unsigned long value; //set value to the previous code
         if((i - 1) < HLIT) value = bitlen[i - 1];
         else value = bitlenD[i - HLIT - 1];
         for(size_t n = 0; n < replength; n++) //repeat this value in the next lengths
         {
           if(i >= HLIT + HDIST) { error = 13; return; } //error: i is larger than the amount of codes
           if(i < HLIT) bitlen[i++] = value; else bitlenD[i++ - HLIT] = value;
         }
       }
       else if(code == 17) //repeat "0" 3-10 times
       {
         if(bp >> 3 >= inlength) { error = 50; return; } //error, bit pointer jumps past memory
         replength = 3 + readBitsFromStream(bp, in, 3);
         zlibinfo->back().treecodes.push_back(replength); //tree symbol code repetitions
         for(size_t n = 0; n < replength; n++) //repeat this value in the next lengths
         {
           if(i >= HLIT + HDIST) { error = 14; return; } //error: i is larger than the amount of codes
           if(i < HLIT) bitlen[i++] = 0; else bitlenD[i++ - HLIT] = 0;
         }
       }
       else if(code == 18) //repeat "0" 11-138 times
       {
         if(bp >> 3 >= inlength) { error = 50; return; } //error, bit pointer jumps past memory
         replength = 11 + readBitsFromStream(bp, in, 7);
         zlibinfo->back().treecodes.push_back(replength); //tree symbol code repetitions
         for(size_t n = 0; n < replength; n++) //repeat this value in the next lengths
         {
           if(i >= HLIT + HDIST) { error = 15; return; } //error: i is larger than the amount of codes
           if(i < HLIT) bitlen[i++] = 0; else bitlenD[i++ - HLIT] = 0;
         }
       }
       else { error = 16; return; } //error: somehow an unexisting code appeared. This can never happen.
     }
     if(bitlen[256] == 0) { error = 64; return; } //the length of the end code 256 must be larger than 0
     error = tree.makeFromLengths(bitlen, 15);
     if(error) return; //now we've finally got HLIT and HDIST, so generate the code trees, and the function is done
     error = treeD.makeFromLengths(bitlenD, 15);
     if(error) return;
     zlibinfo->back().treebits = bp - bpstart;
     //lit/len/end symbol lengths
     for(size_t j = 0; j < bitlen.size(); j++) zlibinfo->back().litlenlengths.push_back(bitlen[j]);
     //dist lengths
     for(size_t j = 0; j < bitlenD.size(); j++) zlibinfo->back().distlengths.push_back(bitlenD[j]);
   }
References lodepng::CLCL, codelengthcodetree, error, huffmanDecodeSymbol(), lodepng::ExtractZlib::HuffmanTree::makeFromLengths(), readBitsFromStream(), and zlibinfo.
Referenced by inflateHuffmanBlock().
huffmanDecodeSymbol()
unsigned long lodepng::ExtractZlib::huffmanDecodeSymbol (const unsigned char * in, size_t & bp, const HuffmanTree & tree, size_t inlength) inline
Definition at line 406 of file lodepng_util.cpp.
   {
     //decode a single symbol from given list of bits with given code tree. return value is the symbol
     bool decoded; unsigned long ct;
     for(size_t treepos = 0;;)
     {
       if((bp & 0x07) == 0 && (bp >> 3) > inlength) { error = 10; return 0; } //error: end reached without endcode
       error = tree.decode(decoded, ct, treepos, readBitFromStream(bp, in));
       if(error) return 0; //stop, an error happened
       if(decoded) return ct;
     }
   }
References lodepng::ExtractZlib::HuffmanTree::decode(), error, and readBitFromStream().
Referenced by getTreeInflateDynamic(), and inflateHuffmanBlock().
inflate()
void lodepng::ExtractZlib::inflate (std::vector< unsigned char > & out, const std::vector< unsigned char > & in, size_t inpos = 0) inline
Definition at line 372 of file lodepng_util.cpp.
   {
     size_t bp = 0, pos = 0; //bit pointer and byte pointer
     error = 0;
     unsigned long BFINAL = 0;
     while(!BFINAL && !error)
     {
       size_t uncomprblockstart = pos;
       size_t bpstart = bp;
       if(bp >> 3 >= in.size()) { error = 52; return; } //error, bit pointer will jump past memory
       BFINAL = readBitFromStream(bp, &in[inpos]);
       unsigned long BTYPE = readBitFromStream(bp, &in[inpos]); BTYPE += 2 * readBitFromStream(bp, &in[inpos]);
       zlibinfo->resize(zlibinfo->size() + 1);
       zlibinfo->back().btype = BTYPE;
       if(BTYPE == 3) { error = 20; return; } //error: invalid BTYPE
       else if(BTYPE == 0) inflateNoCompression(out, &in[inpos], bp, pos, in.size());
       else inflateHuffmanBlock(out, &in[inpos], bp, pos, in.size(), BTYPE);
       size_t uncomprblocksize = pos - uncomprblockstart;
       zlibinfo->back().compressedbits = bp - bpstart;
       zlibinfo->back().uncompressedbytes = uncomprblocksize;
     }
   }
References error, inflateHuffmanBlock(), inflateNoCompression(), readBitFromStream(), and zlibinfo.
Referenced by decompress().
inflateHuffmanBlock()
void lodepng::ExtractZlib::inflateHuffmanBlock (std::vector< unsigned char > & out, const unsigned char * in, size_t & bp, size_t & pos, size_t inlength, unsigned long btype) inline
Definition at line 492 of file lodepng_util.cpp.
   {
     size_t numcodes = 0, numlit = 0, numlen = 0; //for logging
     if(btype == 1) { generateFixedTrees(codetree, codetreeD); }
     else if(btype == 2) { getTreeInflateDynamic(codetree, codetreeD, in, bp, inlength); if(error) return; }
     for(;;)
     {
       unsigned long code = huffmanDecodeSymbol(in, bp, codetree, inlength); if(error) return;
       numcodes++;
       zlibinfo->back().lz77_lcode.push_back(code); //output code
       zlibinfo->back().lz77_dcode.push_back(0);
       zlibinfo->back().lz77_lbits.push_back(0);
       zlibinfo->back().lz77_dbits.push_back(0);
       zlibinfo->back().lz77_lvalue.push_back(0);
       zlibinfo->back().lz77_dvalue.push_back(0);
       if(code == 256) break; //end code
       else if(code <= 255) //literal symbol
       {
         out.push_back((unsigned char)(code));
         pos++;
         numlit++;
       }
       else if(code >= 257 && code <= 285) //length code
       {
         size_t length = LENBASE[code - 257], numextrabits = LENEXTRA[code - 257];
         if((bp >> 3) >= inlength) { error = 51; return; } //error, bit pointer will jump past memory
         length += readBitsFromStream(bp, in, numextrabits);
         unsigned long codeD = huffmanDecodeSymbol(in, bp, codetreeD, inlength); if(error) return;
         if(codeD > 29) { error = 18; return; } //error: invalid dist code (30-31 are never used)
         unsigned long dist = DISTBASE[codeD], numextrabitsD = DISTEXTRA[codeD];
         if((bp >> 3) >= inlength) { error = 51; return; } //error, bit pointer will jump past memory
         dist += readBitsFromStream(bp, in, numextrabitsD);
         size_t start = pos, back = start - dist; //backwards
         for(size_t i = 0; i < length; i++)
         {
           out.push_back(out[back++]);
           pos++;
           if(back >= start) back = start - dist;
         }
         numlen++;
         zlibinfo->back().lz77_dcode.back() = codeD; //output distance code
         zlibinfo->back().lz77_lbits.back() = numextrabits; //output length extra bits
         zlibinfo->back().lz77_dbits.back() = numextrabitsD; //output dist extra bits
         zlibinfo->back().lz77_lvalue.back() = length; //output length
         zlibinfo->back().lz77_dvalue.back() = dist; //output dist
       }
     }
     zlibinfo->back().numlit = numlit; //output number of literal symbols
     zlibinfo->back().numlen = numlen; //output number of length symbols
   }
References codetree, codetreeD, lodepng::DISTBASE, lodepng::DISTEXTRA, error, generateFixedTrees(), getTreeInflateDynamic(), huffmanDecodeSymbol(), lodepng::LENBASE, lodepng::LENEXTRA, readBitsFromStream(), and zlibinfo.
Referenced by inflate().
inflateNoCompression()
void lodepng::ExtractZlib::inflateNoCompression (std::vector< unsigned char > & out, const unsigned char * in, size_t & bp, size_t & pos, size_t inlength) inline
Definition at line 545 of file lodepng_util.cpp.
   {
     while((bp & 0x7) != 0) bp++; //go to first boundary of byte
     size_t p = bp / 8;
     if(p >= inlength - 4) { error = 52; return; } //error, bit pointer will jump past memory
     unsigned long LEN = in[p] + 256u * in[p + 1], NLEN = in[p + 2] + 256u * in[p + 3]; p += 4;
     if(LEN + NLEN != 65535) { error = 21; return; } //error: NLEN is not one's complement of LEN
     if(p + LEN > inlength) { error = 23; return; } //error: reading outside of in buffer
     for(unsigned long n = 0; n < LEN; n++)
     {
       out.push_back(in[p++]); //read LEN bytes of literal data
       pos++;
     }
     bp = p * 8;
   }
References error.
Referenced by inflate().
readBitFromStream()
unsigned long lodepng::ExtractZlib::readBitFromStream (size_t & bitp, const unsigned char * bits) inline
Definition at line 306 of file lodepng_util.cpp.
   {
     unsigned long result = (bits[bitp >> 3] >> (bitp & 0x7)) & 1;
     bitp++;
     return result;
   }
Referenced by huffmanDecodeSymbol(), inflate(), and readBitsFromStream().
readBitsFromStream()
unsigned long lodepng::ExtractZlib::readBitsFromStream (size_t & bitp, const unsigned char * bits, size_t nbits) inline
Definition at line 313 of file lodepng_util.cpp.
   {
     unsigned long result = 0;
     for(size_t i = 0; i < nbits; i++) result += (readBitFromStream(bitp, bits)) << i;
     return result;
   }
References readBitFromStream().
Referenced by getTreeInflateDynamic(), and inflateHuffmanBlock().
Member Data Documentation
codelengthcodetree
HuffmanTree lodepng::ExtractZlib::codelengthcodetree
Definition at line 405 of file lodepng_util.cpp.
Referenced by getTreeInflateDynamic().
codetree
HuffmanTree lodepng::ExtractZlib::codetree
Definition at line 405 of file lodepng_util.cpp.
Referenced by inflateHuffmanBlock().
codetreeD
HuffmanTree lodepng::ExtractZlib::codetreeD
Definition at line 405 of file lodepng_util.cpp.
Referenced by inflateHuffmanBlock().
error
int lodepng::ExtractZlib::error
Definition at line 303 of file lodepng_util.cpp.
Referenced by decompress(), getTreeInflateDynamic(), huffmanDecodeSymbol(), inflate(), inflateHuffmanBlock(), and inflateNoCompression().
zlibinfo
std::vector<ZlibBlockInfo>* lodepng::ExtractZlib::zlibinfo
Definition at line 302 of file lodepng_util.cpp.
Referenced by getTreeInflateDynamic(), inflate(), and inflateHuffmanBlock().
The documentation for this struct was generated from the following file:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/lodepng/lodepng_util.cpp