My Project: cTimer Class Reference
cTimer Class Reference
#include <Timer.h>
Classes
struct tParams
Public Types
enum eType { eTypeUniform, eTypeExp, eTypeMax }
Public Member Functions
cTimer ()
virtual ~cTimer ()
virtual void Init (const tParams &params)
virtual void Reset ()
virtual void Update (double timestep)
virtual bool IsEnd () const
virtual double GetTime () const
virtual double GetMaxTime () const
virtual void SetMaxTime (double time)
virtual const tParams & GetParams () const
virtual void SetParams (const tParams &params)
Static Public Member Functions
static eType ParseTypeStr (const std::string &str)
Protected Attributes
tParams mParams
double mMaxTime
double mTime
Detailed Description
Definition at line 5 of file Timer.h.
Member Enumeration Documentation
eType
enum cTimer::eType
Enumerator
eTypeUniform
eTypeExp
eTypeMax
Definition at line 8 of file Timer.h.
     {
         eTypeUniform,
         eTypeExp,
         eTypeMax
     };
Constructor & Destructor Documentation
cTimer()
cTimer::cTimer ()
Definition at line 22 of file Timer.cpp.
 {
     Reset();
 }
References Reset().
~cTimer()
cTimer::~cTimer () virtual
Definition at line 45 of file Timer.cpp.
 {
 }
Member Function Documentation
GetMaxTime()
double cTimer::GetMaxTime () const virtual
Definition at line 90 of file Timer.cpp.
 {
     return mMaxTime;
 }
References mMaxTime.
GetParams()
const cTimer::tParams & cTimer::GetParams () const virtual
Definition at line 100 of file Timer.cpp.
 {
     return mParams;
 }
References mParams.
GetTime()
double cTimer::GetTime () const virtual
Definition at line 85 of file Timer.cpp.
 {
     return mTime;
 }
References mTime.
Referenced by cScene::GetTime().
Init()
void cTimer::Init (const tParams & params) virtual
Definition at line 49 of file Timer.cpp.
 {
     SetParams(params);
     Reset();
 }
References Reset(), and SetParams().
Referenced by cObjTracer::Init(), and cScene::InitTimers().
IsEnd()
bool cTimer::IsEnd () const virtual
Definition at line 80 of file Timer.cpp.
 {
     return mTime >= mMaxTime;
 }
References mMaxTime, and mTime.
Referenced by cScene::IsEpisodeEnd(), cObjTracer::Update(), cObjTracer::UpdateTraceCOM(), and cObjTracer::UpdateTracePos().
ParseTypeStr()
cTimer::eType cTimer::ParseTypeStr (const std::string & str) static
Definition at line 27 of file Timer.cpp.
 {
     eType timer_type = eTypeUniform;
     if (str == "" || str == "uniform")
     {
     }
     else if (str == "exp")
     {
         timer_type = eTypeExp;
     }
     else
     {
         printf("Unsupported timer type %s\n", str.c_str());
         assert(false);
     }
     return timer_type;
 }
References eTypeExp, and eTypeUniform.
Referenced by cScene::ParseArgs().
Reset()
void cTimer::Reset () virtual
Definition at line 55 of file Timer.cpp.
 {
     mTime = 0;
     double max_time = 0;
     switch (mParams.mType)
     {
     case eTypeUniform:
         max_time = cMathUtil::RandDouble(mParams.mTimeMin, mParams.mTimeMax);
         break;
     case eTypeExp:
         max_time = mParams.mTimeMin + cMathUtil::RandDoubleExp(1 / mParams.mTimeExp);
         max_time = std::min(max_time, mParams.mTimeMax);
         break;
     default:
         assert(false); // Unsupported timer type
         break;
     }
     SetMaxTime(max_time);
 }
References eTypeExp, eTypeUniform, mParams, mTime, cTimer::tParams::mTimeExp, cTimer::tParams::mTimeMax, cTimer::tParams::mTimeMin, cTimer::tParams::mType, cMathUtil::RandDouble(), cMathUtil::RandDoubleExp(), and SetMaxTime().
Referenced by cTimer(), Init(), cObjTracer::ResetTimer(), and cScene::ResetTimers().
SetMaxTime()
void cTimer::SetMaxTime (double time) virtual
Definition at line 95 of file Timer.cpp.
 {
     mMaxTime = time;
 }
References mMaxTime.
Referenced by Reset(), and cRLSceneSimChar::ResetTimers().
SetParams()
void cTimer::SetParams (const tParams & params) virtual
Definition at line 105 of file Timer.cpp.
 {
     mParams = params;
 }
References mParams.
Referenced by Init(), and cRLSceneSimChar::UpdateTimerParams().
Update()
void cTimer::Update (double timestep) virtual
Definition at line 75 of file Timer.cpp.
 {
     mTime += timestep;
 }
References mTime.
Referenced by cObjTracer::Update(), and cScene::UpdateTimers().
Member Data Documentation
mMaxTime
double cTimer::mMaxTime protected
Definition at line 46 of file Timer.h.
Referenced by GetMaxTime(), IsEnd(), and SetMaxTime().
mParams
tParams cTimer::mParams protected
Definition at line 45 of file Timer.h.
Referenced by GetParams(), Reset(), and SetParams().
mTime
double cTimer::mTime protected
Definition at line 47 of file Timer.h.
Referenced by GetTime(), IsEnd(), Reset(), and Update().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/Timer.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/Timer.cpp