My Project: cDrawSceneSimChar Class Reference
cDrawSceneSimChar Class Reference
#include <DrawSceneSimChar.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cDrawSceneSimChar ()
virtual ~cDrawSceneSimChar ()
virtual void Init ()
virtual void Clear ()
virtual void Update (double time_elapsed)
virtual const std::shared_ptr< cSceneSimChar > & GetScene () const
virtual void MouseClick (int button, int state, double x, double y)
virtual void MouseMove (double x, double y)
virtual void Keyboard (unsigned char key, double device_x, double device_y)
virtual double GetTime () const
virtual bool IsEpisodeEnd () const
virtual bool CheckValidEpisode () const
virtual std::string GetName () const
Public Member Functions inherited from cDrawScene
virtual ~cDrawScene ()
virtual void ParseArgs (const std::shared_ptr< cArgParser > &parser)
virtual void Reset ()
virtual void Draw ()
virtual void EnableDrawInfo (bool enable)
Public Member Functions inherited from cScene
virtual ~cScene ()
virtual void Shutdown ()
virtual bool IsDone () const
virtual bool HasRandSeed () const
virtual void SetRandSeed (unsigned long seed)
virtual unsigned long GetRandSeed () const
Protected Member Functions
virtual void BuildScene (std::shared_ptr< cSceneSimChar > &out_scene) const
virtual void SetupScene (std::shared_ptr< cSceneSimChar > &out_scene)
virtual void UpdateScene (double time_elapsed)
virtual void ResetScene ()
virtual tVector GetCamTrackPos () const
virtual tVector GetCamStillPos () const
virtual tVector GetDefaultCamFocus () const
virtual void ResetParams ()
virtual void ToggleTrace ()
virtual void InitTracer ()
virtual void AddTraces ()
virtual void AddCharTrace (const std::shared_ptr< cSimCharacter > &character, const tVectorArr &cols)
virtual void UpdateTracer (double time_elapsed)
virtual void SpawnProjectile ()
virtual void SpawnBigProjectile ()
virtual void OutputCharState (const std::string &out_file) const
virtual std::string GetOutputCharFile () const
virtual void ResetUI ()
virtual void RayTest (const tVector &start, const tVector &end, cWorld::tRayTestResult &out_result)
virtual bool ObjectSelected () const
virtual void HandleRayTest (const cWorld::tRayTestResult &result)
virtual void ApplyUIForce (double time_step)
virtual void DrawObjs () const
virtual void DrawMisc () const
virtual void DrawCoM () const
virtual void DrawTorque () const
virtual void DrawBodyVel () const
virtual void DrawHeading () const
virtual void DrawTrace () const
virtual void DrawPerturbs () const
virtual void DrawGround () const
virtual void DrawCharacters () const
virtual void DrawCharacter (const std::shared_ptr< cSimCharacter > &character) const
virtual void UpdateGroundDrawMesh ()
virtual void BuildGroundDrawMesh ()
virtual void DrawInfo () const
virtual void DrawPoliInfo () const
Protected Member Functions inherited from cDrawScene
cDrawScene ()
virtual void ParseCamTrackMode (const std::shared_ptr< cArgParser > &parser, eCamTrackMode &out_mode) const
virtual void Reshape (int w, int h)
virtual void ResizeCamera (int w, int h)
virtual void InitCamera ()
virtual eCamTrackMode GetCamTrackMode () const
virtual void UpdateCamera ()
virtual void UpdateCameraTracking ()
virtual void UpdateCameraStill ()
virtual double GetCamStillSnapDistX () const
virtual void ResetCamera ()
virtual void ClearFrame ()
virtual tVector GetBkgColor () const
virtual void SetupView ()
virtual void RestoreView ()
virtual tVector GetLightDirection () const
virtual void DrawScene ()
virtual void DrawGrid () const
virtual void DrawGroundMainScene ()
virtual void DrawCharacterMainScene ()
virtual void DrawObjsMainScene ()
virtual void DrawMiscMainScene ()
virtual tVector GetVisOffset () const
virtual tVector GetLineColor () const
virtual tVector GetGroundColor () const
virtual void InitRenderResources ()
virtual bool LoadTextures ()
virtual void SetupMeshShader ()
virtual void DoShadowPass ()
Protected Member Functions inherited from cScene
cScene ()
virtual void InitTimers ()
virtual void ResetTimers ()
virtual void UpdateTimers (double timestep)
Protected Attributes
std::shared_ptr< cSceneSimChar > mScene
std::unique_ptr< cDrawMesh > mGroundDrawMesh
size_t mPrevGroundUpdateCount
bool mEnableTrace
cObjTracer mTracer
std::vector< int > mTraceHandles
tVector mClickScreenPos
tVector mDragScreenPos
tVector mSelectObjLocalPos
cSimObj * mSelectedObj
int mTracerBufferSize
double mTracerSamplePeriod
Protected Attributes inherited from cDrawScene
eCamTrackMode mCamTrackMode
cCamera mCamera
cCamera mShadowCam
bool mDrawInfo
std::unique_ptr< cShadowMap > mShadowMap
std::unique_ptr< cTextureDesc > mGridTex
std::unique_ptr< cShader > mShaderMesh
std::unique_ptr< cShader > mShaderDepth
GLuint mMeshLightDirHandle
GLuint mMeshLightColourHandle
GLuint mMeshAmbientColourHandle
GLuint mMeshShadowProjHandle
GLuint mMeshMaterialDataHandle
GLuint mMeshFogColorHandle
GLuint mMeshFogDataHandle
Protected Attributes inherited from cScene
cRand mRand
bool mHasRandSeed
unsigned long mRandSeed
std::shared_ptr< cArgParser > mArgParser
cTimer::tParams mTimerParams
cTimer mTimer
Additional Inherited Members
Public Types inherited from cDrawScene
enum eCamTrackMode {
eCamTrackModeXZ, eCamTrackModeY, eCamTrackModeXYZ, eCamTrackModeStill,
eCamTrackModeFixed, eCamTrackModeMax
}
Detailed Description
Definition at line 9 of file DrawSceneSimChar.h.
Constructor & Destructor Documentation
cDrawSceneSimChar()
cDrawSceneSimChar::cDrawSceneSimChar ()
Definition at line 20 of file DrawSceneSimChar.cpp.
 {
     mEnableTrace = false;
     mTracerBufferSize = 2000;
     mTracerSamplePeriod = 1 / 60.0;
     ResetUI();
 }
References mEnableTrace, mTracerBufferSize, mTracerSamplePeriod, and ResetUI().
~cDrawSceneSimChar()
cDrawSceneSimChar::~cDrawSceneSimChar () virtual
Definition at line 28 of file DrawSceneSimChar.cpp.
 {
 }
Member Function Documentation
AddCharTrace()
void cDrawSceneSimChar::AddCharTrace (const std::shared_ptr< cSimCharacter > & character, const tVectorArr & cols) protected virtual
Definition at line 276 of file DrawSceneSimChar.cpp.
 {
     cObjTracer::tParams com_params;
     com_params.mObj = character;
     com_params.mColors = cols;
     com_params.mType = cObjTracer::eTraceCOM;
     com_params.mBufferSize = mTracerBufferSize;
     int com_handle = mTracer.AddTrace(com_params);
     mTraceHandles.push_back(com_handle);
     int end_eff_idx = 0;
     for (int i = 0; i < character->GetNumBodyParts(); ++i)
     {
         if (character->IsValidBodyPart(i)
             && character->IsEndEffector(i))
         {
             cObjTracer::tParams contact_params;
             contact_params.mObj = character->GetBodyPart(i);
             contact_params.mColors = cols;
             contact_params.mType = cObjTracer::eTraceContact;
             contact_params.mShapeIdx = end_eff_idx;
             contact_params.mBufferSize = mTracerBufferSize / 10;
             int contact_handle = mTracer.AddTrace(contact_params);
             mTraceHandles.push_back(contact_handle);
             ++end_eff_idx;
         }
     }
 }
References cObjTracer::AddTrace(), cObjTracer::eTraceCOM, cObjTracer::eTraceContact, cObjTracer::tParams::mBufferSize, cObjTracer::tParams::mColors, cObjTracer::tParams::mObj, cObjTracer::tParams::mShapeIdx, mTraceHandles, mTracer, mTracerBufferSize, and cObjTracer::tParams::mType.
Referenced by AddTraces().
AddTraces()
void cDrawSceneSimChar::AddTraces () protected virtual
Definition at line 260 of file DrawSceneSimChar.cpp.
 {
     tVectorArr tracer_cols;
     tracer_cols.push_back(tVector(0, 0, 1, 0.5));
     tracer_cols.push_back(tVector(1, 0, 0, 0.5));
     tracer_cols.push_back(tVector(0, 0.5, 0, 0.5));
     tracer_cols.push_back(tVector(0.75, 0, 0.75, 0.5));
     tracer_cols.push_back(tVector(0, 0.5, 0.5, 0.5));
     tracer_cols.push_back(tVector(0, 0, 0, 0.5));
     for (int i = 0; i < mScene->GetNumChars(); ++i)
     {
         AddCharTrace(mScene->GetCharacter(i), tracer_cols);
     }
 }
References AddCharTrace(), and mScene.
Referenced by InitTracer().
ApplyUIForce()
void cDrawSceneSimChar::ApplyUIForce (double time_step) protected virtual
Definition at line 368 of file DrawSceneSimChar.cpp.
 {
     if (ObjectSelected())
     {
         const double force_scale = 1 / cDrawPerturb::gForceScale;
         tVector start = mCamera.ScreenToWorldPos(mClickScreenPos);
         tVector end = mCamera.ScreenToWorldPos(mDragScreenPos);
         start = mCamera.ProjectToFocalPlane(start);
         end = mCamera.ProjectToFocalPlane(end);
         tVector force = end - start;
         force *= force_scale;
         tPerturb perturb = tPerturb(tPerturb::ePerturbForce, mSelectedObj, mSelectObjLocalPos,
                                     force, time_step);
         GetScene()->AddPerturb(perturb);
     }
 }
References tPerturb::ePerturbForce, GetScene(), cDrawPerturb::gForceScale, cDrawScene::mCamera, mClickScreenPos, mDragScreenPos, mSelectedObj, mSelectObjLocalPos, ObjectSelected(), cCamera::ProjectToFocalPlane(), and cCamera::ScreenToWorldPos().
Referenced by UpdateScene().
BuildGroundDrawMesh()
void cDrawSceneSimChar::BuildGroundDrawMesh () protected virtual
Definition at line 519 of file DrawSceneSimChar.cpp.
 {
     mGroundDrawMesh = std::unique_ptr<cDrawMesh>(new cDrawMesh());
     mGroundDrawMesh->Init(1);
     const auto& ground = mScene->GetGround();
     cDrawGround::BuildMesh(ground.get(), mGroundDrawMesh.get());
     mPrevGroundUpdateCount = ground->GetUpdateCount();
 }
References cDrawGround::BuildMesh(), mGroundDrawMesh, mPrevGroundUpdateCount, and mScene.
Referenced by Init(), and ResetScene().
BuildScene()
void cDrawSceneSimChar::BuildScene (std::shared_ptr< cSceneSimChar > & out_scene) const protected virtual
Reimplemented in cDrawSceneImitate.
Definition at line 149 of file DrawSceneSimChar.cpp.
 {
     out_scene = std::shared_ptr<cSceneSimChar>(new cSceneSimChar());
 }
Referenced by Init().
CheckValidEpisode()
bool cDrawSceneSimChar::CheckValidEpisode () const virtual
Reimplemented from cScene.
Reimplemented in cDrawSceneImitate.
Definition at line 139 of file DrawSceneSimChar.cpp.
 {
     return mScene->CheckValidEpisode();
 }
References mScene.
Clear()
void cDrawSceneSimChar::Clear () virtual
Reimplemented from cScene.
Reimplemented in cDrawSceneImitate.
Definition at line 43 of file DrawSceneSimChar.cpp.
 {
     cDrawScene::Clear();
     mScene->Clear();
     mTracer.Clear();
     mPrevGroundUpdateCount = gInitGroundUpdateCount;
 }
References cScene::Clear(), cObjTracer::Clear(), gInitGroundUpdateCount, mPrevGroundUpdateCount, mScene, and mTracer.
Referenced by cDrawSceneImitate::Clear().
DrawBodyVel()
void cDrawSceneSimChar::DrawBodyVel () const protected virtual
Definition at line 440 of file DrawSceneSimChar.cpp.
 {
     const double lin_vel_scale = 0.1;
     const double ang_vel_scale = 1 / (2 * M_PI);
     for (int i = 0; i < mScene->GetNumChars(); ++i)
     {
         const auto& character = mScene->GetCharacter(i);
         cDrawSimCharacter::DrawBodyVel(*(character.get()), lin_vel_scale, ang_vel_scale, GetVisOffset());
     }
 }
References cDrawSimCharacter::DrawBodyVel(), cDrawScene::GetVisOffset(), and mScene.
DrawCharacter()
void cDrawSceneSimChar::DrawCharacter (const std::shared_ptr< cSimCharacter > & character) const protected virtual
Definition at line 500 of file DrawSceneSimChar.cpp.
 {
     const tVector fill_tint = tVector(1, 1, 1, 1);
     bool enable_draw_shape = true;
     cDrawSimCharacter::Draw(*(character.get()), fill_tint, GetLineColor(), enable_draw_shape);
 }
References cDrawSimCharacter::Draw(), and cDrawScene::GetLineColor().
Referenced by DrawCharacters().
DrawCharacters()
void cDrawSceneSimChar::DrawCharacters () const protected virtual
Reimplemented from cDrawScene.
Reimplemented in cDrawSceneImitate.
Definition at line 490 of file DrawSceneSimChar.cpp.
 {
     int num_chars = mScene->GetNumChars();
     for (int i = 0; i < num_chars; ++i)
     {
         const auto& curr_char = mScene->GetCharacter(i);
         DrawCharacter(curr_char);
     }
 }
References DrawCharacter(), and mScene.
Referenced by cDrawSceneImitate::DrawCharacters().
DrawCoM()
void cDrawSceneSimChar::DrawCoM () const protected virtual
Definition at line 418 of file DrawSceneSimChar.cpp.
 {
     const tVector col = tVector(0, 0.8, 0, 0.5);
     const double marker_size = 0.1;
     const double vel_scale = 0.1;
     for (int i = 0; i < mScene->GetNumChars(); ++i)
     {
         const auto& character = mScene->GetCharacter(i);
         cDrawSimCharacter::DrawCoM(*(character.get()), marker_size, vel_scale, col, GetVisOffset());
     }
 }
References cDrawSimCharacter::DrawCoM(), cDrawScene::GetVisOffset(), and mScene.
DrawGround()
void cDrawSceneSimChar::DrawGround () const protected virtual
Reimplemented from cDrawScene.
Definition at line 477 of file DrawSceneSimChar.cpp.
 {
     const auto& ground = mScene->GetGround();
     tVector focus = mCamera.GetFocus();
     double cam_w = mCamera.GetWidth();
     double cam_h = mCamera.GetHeight();
     tVector ground_col = GetGroundColor();
     cDrawUtil::SetColor(ground_col);
     mGroundDrawMesh->Draw();
 }
References cCamera::GetFocus(), cDrawScene::GetGroundColor(), cCamera::GetHeight(), cCamera::GetWidth(), cDrawScene::mCamera, mGroundDrawMesh, mScene, and cDrawUtil::SetColor().
DrawHeading()
void cDrawSceneSimChar::DrawHeading () const protected virtual
Definition at line 451 of file DrawSceneSimChar.cpp.
 {
     for (int i = 0; i < mScene->GetNumChars(); ++i)
     {
         const auto& character = mScene->GetCharacter(i);
         double arrow_size = 0.2;
         tVector arrow_col = tVector(0, 0.8, 0, 0.5);
         cDrawCharacter::DrawHeading(*(character.get()), arrow_size, arrow_col, GetVisOffset());
     }
 }
References cDrawCharacter::DrawHeading(), cDrawScene::GetVisOffset(), and mScene.
DrawInfo()
void cDrawSceneSimChar::DrawInfo () const protected virtual
Reimplemented from cDrawScene.
Definition at line 529 of file DrawSceneSimChar.cpp.
 {
     DrawPoliInfo();
 }
References DrawPoliInfo().
DrawMisc()
void cDrawSceneSimChar::DrawMisc () const protected virtual
Reimplemented from cDrawScene.
Definition at line 409 of file DrawSceneSimChar.cpp.
 {
     if (mEnableTrace)
     {
         DrawTrace();
     }
     DrawPerturbs();
 }
References DrawPerturbs(), DrawTrace(), and mEnableTrace.
DrawObjs()
void cDrawSceneSimChar::DrawObjs () const protected virtual
Reimplemented from cDrawScene.
Definition at line 387 of file DrawSceneSimChar.cpp.
 {
     int num_objs = mScene->GetNumObjs();
     for (int i = 0; i < num_objs; ++i)
     {
         const cSceneSimChar::tObjEntry& entry = mScene->GetObjEntry(i);
         if (entry.IsValid())
         {
             const auto& obj = entry.mObj;
             cDrawUtil::SetColor(entry.mColor);
             cDrawObj::Draw(obj.get(), cDrawUtil::eDrawSolid);
             tVector line_col = GetLineColor();
             if (line_col[3] > 0)
             {
                 cDrawUtil::SetColor(line_col);
                 cDrawObj::Draw(obj.get(), cDrawUtil::eDrawWireSimple);
             }
         }
     }
 }
References cDrawObj::Draw(), cDrawUtil::eDrawSolid, cDrawUtil::eDrawWireSimple, cDrawScene::GetLineColor(), cSceneSimChar::tObjEntry::IsValid(), cSceneSimChar::tObjEntry::mColor, cSceneSimChar::tObjEntry::mObj, mScene, and cDrawUtil::SetColor().
DrawPerturbs()
void cDrawSceneSimChar::DrawPerturbs () const protected virtual
Definition at line 471 of file DrawSceneSimChar.cpp.
 {
     const auto& world = mScene->GetWorld();
     cDrawWorld::DrawPerturbs(*world.get());
 }
References cDrawWorld::DrawPerturbs(), and mScene.
Referenced by DrawMisc().
DrawPoliInfo()
void cDrawSceneSimChar::DrawPoliInfo () const protected virtual
Definition at line 534 of file DrawSceneSimChar.cpp.
 {
     const auto& character = mScene->GetCharacter();
     const cDeepMimicCharController* trl_ctrl = dynamic_cast<cDeepMimicCharController*>(character->GetController().get());
     if (trl_ctrl != nullptr)
     {
         cDrawSimCharacter::DrawInfoValLog(trl_ctrl->GetValLog(), mCamera);
     }
 }
References cDrawSimCharacter::DrawInfoValLog(), cDeepMimicCharController::GetValLog(), cDrawScene::mCamera, and mScene.
Referenced by DrawInfo().
DrawTorque()
void cDrawSceneSimChar::DrawTorque () const protected virtual
Definition at line 431 of file DrawSceneSimChar.cpp.
 {
     for (int i = 0; i < mScene->GetNumChars(); ++i)
     {
         const auto& character = mScene->GetCharacter(i);
         cDrawSimCharacter::DrawTorque(*(character.get()), GetVisOffset());
     }
 }
References cDrawSimCharacter::DrawTorque(), cDrawScene::GetVisOffset(), and mScene.
DrawTrace()
void cDrawSceneSimChar::DrawTrace () const protected virtual
Definition at line 462 of file DrawSceneSimChar.cpp.
 {
     cDrawUtil::PushMatrixView();
     cDrawUtil::Translate(GetVisOffset());
     mTracer.Draw();
     cDrawUtil::PopMatrixView();
 }
References cObjTracer::Draw(), cDrawScene::GetVisOffset(), mTracer, cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixView(), and cDrawUtil::Translate().
Referenced by DrawMisc().
GetCamStillPos()
tVector cDrawSceneSimChar::GetCamStillPos () const protected virtual
Reimplemented from cDrawScene.
Definition at line 180 of file DrawSceneSimChar.cpp.
 {
     const auto& character = mScene->GetCharacter();
     tVector char_pos = character->CalcCOM();
     double cam_w = mCamera.GetWidth();
     double cam_h = mCamera.GetHeight();
     const auto& ground = mScene->GetGround();
     const int num_samples = 16;
     double ground_samples[num_samples] = { 0 };
     const double pad = std::min(0.5, 0.5 * cam_w);
     double avg_h = 0;
     double min_x = char_pos[0];
     double max_x = char_pos[0] + cam_w;
     int num_valid_samples = 0;
     for (int i = 0; i < num_samples; ++i)
     {
         tVector pos = char_pos;
         pos[0] = static_cast<double>(i) / (num_samples - 1) * (max_x - min_x) + min_x;
         bool valid_sample = true;
         double ground_h = ground->SampleHeight(pos, valid_sample);
         if (valid_sample)
         {
             ground_samples[i] = ground_h;
             avg_h += ground_h;
             ++num_valid_samples;
         }
     }
     avg_h /= num_valid_samples;
     std::sort(ground_samples, &(ground_samples[num_samples - 1]));
     double med_h = ground_samples[num_samples / 2];
     double min_h = ground_samples[0];
     tVector track_pos = char_pos;
     double target_h = avg_h;
     double y_pad = -0.4;
     track_pos[1] = target_h + y_pad + 0.5 * cam_h;
     return track_pos;
 }
References cCamera::GetHeight(), cCamera::GetWidth(), cDrawScene::mCamera, and mScene.
GetCamTrackPos()
tVector cDrawSceneSimChar::GetCamTrackPos () const protected virtual
Reimplemented from cDrawScene.
Definition at line 174 of file DrawSceneSimChar.cpp.
 {
     const auto& character = mScene->GetCharacter();
     return character->CalcCOM();
 }
References mScene.
GetDefaultCamFocus()
tVector cDrawSceneSimChar::GetDefaultCamFocus () const protected virtual
Reimplemented from cDrawScene.
Definition at line 228 of file DrawSceneSimChar.cpp.
 {
     return gCamFocus0;
 }
References gCamFocus0.
GetName()
std::string cDrawSceneSimChar::GetName () const virtual
Reimplemented from cDrawScene.
Reimplemented in cDrawSceneImitate.
Definition at line 144 of file DrawSceneSimChar.cpp.
 {
     return mScene->GetName();
 }
References mScene.
GetOutputCharFile()
std::string cDrawSceneSimChar::GetOutputCharFile () const protected virtual
Definition at line 328 of file DrawSceneSimChar.cpp.
 {
     return gOutputCharFile;
 }
References gOutputCharFile.
Referenced by Keyboard().
GetScene()
const std::shared_ptr< cSceneSimChar > & cDrawSceneSimChar::GetScene () const virtual
Definition at line 65 of file DrawSceneSimChar.cpp.
 {
     return mScene;
 }
References mScene.
Referenced by ApplyUIForce(), and RayTest().
GetTime()
double cDrawSceneSimChar::GetTime () const virtual
Reimplemented from cScene.
Definition at line 129 of file DrawSceneSimChar.cpp.
 {
     return mScene->GetTime();
 }
References mScene.
HandleRayTest()
void cDrawSceneSimChar::HandleRayTest (const cWorld::tRayTestResult & result) protected virtual
Definition at line 352 of file DrawSceneSimChar.cpp.
 {
     if (result.mObj != nullptr)
     {
         cSimObj::eType obj_type = result.mObj->GetType();
         if (obj_type == cSimObj::eTypeDynamic)
         {
             mSelectedObj = result.mObj;
             if (ObjectSelected())
             {
                 mSelectObjLocalPos = mSelectedObj->WorldToLocalPos(result.mHitPos);
             }
         }
     }
 }
References cSimObj::eTypeDynamic, cSimObj::GetType(), cWorld::tRayTestResult::mHitPos, cWorld::tRayTestResult::mObj, mSelectedObj, mSelectObjLocalPos, ObjectSelected(), and cSimObj::WorldToLocalPos().
Referenced by MouseClick().
Init()
void cDrawSceneSimChar::Init () virtual
Reimplemented from cDrawScene.
Reimplemented in cDrawSceneImitate.
Definition at line 32 of file DrawSceneSimChar.cpp.
 {
     BuildScene(mScene);
     SetupScene(mScene);
     cDrawScene::Init();
     InitTracer();
     BuildGroundDrawMesh();
 }
References BuildGroundDrawMesh(), BuildScene(), cDrawScene::Init(), InitTracer(), mScene, and SetupScene().
Referenced by cDrawSceneImitate::Init().
InitTracer()
void cDrawSceneSimChar::InitTracer () protected virtual
Definition at line 253 of file DrawSceneSimChar.cpp.
 {
     mTraceHandles.clear();
     mTracer.Init(mTracerSamplePeriod);
     AddTraces();
 }
References AddTraces(), cObjTracer::Init(), mTraceHandles, mTracer, and mTracerSamplePeriod.
Referenced by Init().
IsEpisodeEnd()
bool cDrawSceneSimChar::IsEpisodeEnd () const virtual
Reimplemented from cScene.
Reimplemented in cDrawSceneImitate.
Definition at line 134 of file DrawSceneSimChar.cpp.
 {
     return mScene->IsEpisodeEnd();
 }
References mScene.
Keyboard()
void cDrawSceneSimChar::Keyboard (unsigned char key, double device_x, double device_y) virtual
Reimplemented from cScene.
Reimplemented in cDrawSceneImitate.
Definition at line 106 of file DrawSceneSimChar.cpp.
 {
     cDrawScene::Keyboard(key, device_x, device_y);
     switch (key)
     {
     case 's':
         OutputCharState(GetOutputCharFile());
         break;
     case 'x':
         SpawnProjectile();
         break;
     case 'z':
         SpawnBigProjectile();
         break;
     case 'y':
         ToggleTrace();
         break;
     default:
         break;
     }
 }
References GetOutputCharFile(), cScene::Keyboard(), OutputCharState(), SpawnBigProjectile(), SpawnProjectile(), and ToggleTrace().
Referenced by cDrawSceneImitate::Keyboard().
MouseClick()
void cDrawSceneSimChar::MouseClick (int button, int state, double x, double y) virtual
Reimplemented from cDrawScene.
Definition at line 70 of file DrawSceneSimChar.cpp.
 {
     const double ray_max_dist = 1000;
     cDrawScene::MouseClick(button, state, x, y);
     if (button == GLUT_LEFT_BUTTON)
     {
         if (state == GLUT_DOWN)
         {
             mClickScreenPos = tVector(x, y, 0, 0);
             mDragScreenPos = mClickScreenPos;
             tVector start = mCamera.ScreenToWorldPos(mClickScreenPos);
             tVector dir = mCamera.GetRayCastDir(start);
             tVector end = start + dir * ray_max_dist;
             cWorld::tRayTestResult raytest_result;
             RayTest(start, end, raytest_result);
             HandleRayTest(raytest_result);
         }
         else if (state == GLUT_UP)
         {
             ResetUI();
         }
     }
 }
References cCamera::GetRayCastDir(), HandleRayTest(), cDrawScene::mCamera, mClickScreenPos, mDragScreenPos, cDrawScene::MouseClick(), RayTest(), ResetUI(), and cCamera::ScreenToWorldPos().
MouseMove()
void cDrawSceneSimChar::MouseMove (double x, double y) virtual
Reimplemented from cDrawScene.
Definition at line 96 of file DrawSceneSimChar.cpp.
 {
     cDrawScene::MouseMove(x, y);
     if (ObjectSelected())
     {
         mDragScreenPos = tVector(x, y, 0, 0);
     }
 }
References mDragScreenPos, cDrawScene::MouseMove(), and ObjectSelected().
ObjectSelected()
bool cDrawSceneSimChar::ObjectSelected () const protected virtual
Definition at line 347 of file DrawSceneSimChar.cpp.
 {
     return mSelectedObj != nullptr;
 }
References mSelectedObj.
Referenced by ApplyUIForce(), HandleRayTest(), and MouseMove().
OutputCharState()
void cDrawSceneSimChar::OutputCharState (const std::string & out_file) const protected virtual
Definition at line 323 of file DrawSceneSimChar.cpp.
 {
     mScene->OutputCharState(out_file);
 }
References mScene.
Referenced by Keyboard().
RayTest()
void cDrawSceneSimChar::RayTest (const tVector & start, const tVector & end, cWorld::tRayTestResult & out_result) protected virtual
Definition at line 342 of file DrawSceneSimChar.cpp.
 {
     return GetScene()->RayTest(start, end, out_result);
 }
References GetScene().
Referenced by MouseClick().
ResetParams()
void cDrawSceneSimChar::ResetParams () protected virtual
Reimplemented from cScene.
Definition at line 233 of file DrawSceneSimChar.cpp.
 {
     cDrawScene::ResetParams();
     ResetUI();
 }
References cScene::ResetParams(), and ResetUI().
ResetScene()
void cDrawSceneSimChar::ResetScene () protected virtual
Reimplemented from cScene.
Definition at line 166 of file DrawSceneSimChar.cpp.
 {
     cDrawScene::ResetScene();
     mScene->Reset();
     mTracer.Reset();
     BuildGroundDrawMesh();
 }
References BuildGroundDrawMesh(), mScene, mTracer, cObjTracer::Reset(), and cScene::ResetScene().
ResetUI()
void cDrawSceneSimChar::ResetUI () protected virtual
Definition at line 334 of file DrawSceneSimChar.cpp.
 {
     mClickScreenPos.setZero();
     mDragScreenPos.setZero();
     mSelectObjLocalPos.setZero();
     mSelectedObj = nullptr;
 }
References mClickScreenPos, mDragScreenPos, mSelectedObj, and mSelectObjLocalPos.
Referenced by cDrawSceneSimChar(), MouseClick(), and ResetParams().
SetupScene()
void cDrawSceneSimChar::SetupScene (std::shared_ptr< cSceneSimChar > & out_scene) protected virtual
Definition at line 154 of file DrawSceneSimChar.cpp.
 {
     out_scene->ParseArgs(mArgParser);
     out_scene->Init();
 }
References cScene::mArgParser.
Referenced by Init().
SpawnBigProjectile()
void cDrawSceneSimChar::SpawnBigProjectile () protected virtual
Definition at line 318 of file DrawSceneSimChar.cpp.
 {
     mScene->SpawnBigProjectile();
 }
References mScene.
Referenced by Keyboard().
SpawnProjectile()
void cDrawSceneSimChar::SpawnProjectile () protected virtual
Definition at line 313 of file DrawSceneSimChar.cpp.
 {
     mScene->SpawnProjectile();
 }
References mScene.
Referenced by Keyboard().
ToggleTrace()
void cDrawSceneSimChar::ToggleTrace () protected virtual
Definition at line 239 of file DrawSceneSimChar.cpp.
 {
     mTracer.Reset();
     mEnableTrace = !mEnableTrace;
     if (mEnableTrace)
     {
         printf("Enable character tracer\n");
     }
     else
     {
         printf("Disable character tracer\n");
     }
 }
References mEnableTrace, mTracer, and cObjTracer::Reset().
Referenced by Keyboard().
Update()
void cDrawSceneSimChar::Update (double time_elapsed) virtual
Reimplemented from cScene.
Definition at line 51 of file DrawSceneSimChar.cpp.
 {
     cDrawScene::Update(time_elapsed);
     UpdateScene(time_elapsed);
     if (mEnableTrace)
     {
         UpdateTracer(time_elapsed);
     }
     UpdateGroundDrawMesh();
     UpdateCamera();
 }
References mEnableTrace, cScene::Update(), cDrawScene::UpdateCamera(), UpdateGroundDrawMesh(), UpdateScene(), and UpdateTracer().
UpdateGroundDrawMesh()
void cDrawSceneSimChar::UpdateGroundDrawMesh () protected virtual
Definition at line 507 of file DrawSceneSimChar.cpp.
 {
     const auto& ground = mScene->GetGround();
     size_t update_count = ground->GetUpdateCount();
     if (update_count != mPrevGroundUpdateCount)
     {
         const auto& ground = mScene->GetGround();
         cDrawGround::BuildMesh(ground.get(), mGroundDrawMesh.get());
         mPrevGroundUpdateCount = ground->GetUpdateCount();
     }
 }
References cDrawGround::BuildMesh(), mGroundDrawMesh, mPrevGroundUpdateCount, and mScene.
Referenced by Update().
UpdateScene()
void cDrawSceneSimChar::UpdateScene (double time_elapsed) protected virtual
Definition at line 160 of file DrawSceneSimChar.cpp.
 {
     ApplyUIForce(time_elapsed);
     mScene->Update(time_elapsed);
 }
References ApplyUIForce(), and mScene.
Referenced by Update().
UpdateTracer()
void cDrawSceneSimChar::UpdateTracer (double time_elapsed) protected virtual
Definition at line 308 of file DrawSceneSimChar.cpp.
 {
     mTracer.Update(time_elapsed);
 }
References mTracer, and cObjTracer::Update().
Referenced by Update().
Member Data Documentation
mClickScreenPos
tVector cDrawSceneSimChar::mClickScreenPos protected
Definition at line 45 of file DrawSceneSimChar.h.
Referenced by ApplyUIForce(), MouseClick(), and ResetUI().
mDragScreenPos
tVector cDrawSceneSimChar::mDragScreenPos protected
Definition at line 46 of file DrawSceneSimChar.h.
Referenced by ApplyUIForce(), MouseClick(), MouseMove(), and ResetUI().
mEnableTrace
bool cDrawSceneSimChar::mEnableTrace protected
Definition at line 40 of file DrawSceneSimChar.h.
Referenced by cDrawSceneSimChar(), DrawMisc(), ToggleTrace(), and Update().
mGroundDrawMesh
std::unique_ptr<cDrawMesh> cDrawSceneSimChar::mGroundDrawMesh protected
Definition at line 37 of file DrawSceneSimChar.h.
Referenced by BuildGroundDrawMesh(), DrawGround(), and UpdateGroundDrawMesh().
mPrevGroundUpdateCount
size_t cDrawSceneSimChar::mPrevGroundUpdateCount protected
Definition at line 38 of file DrawSceneSimChar.h.
Referenced by BuildGroundDrawMesh(), Clear(), and UpdateGroundDrawMesh().
mScene
std::shared_ptr<cSceneSimChar> cDrawSceneSimChar::mScene protected
Definition at line 35 of file DrawSceneSimChar.h.
Referenced by AddTraces(), BuildGroundDrawMesh(), CheckValidEpisode(), Clear(), DrawBodyVel(), DrawCharacters(), DrawCoM(), DrawGround(), DrawHeading(), DrawObjs(), DrawPerturbs(), DrawPoliInfo(), DrawTorque(), GetCamStillPos(), GetCamTrackPos(), cDrawSceneImitate::GetKinChar(), GetName(), cDrawSceneImitate::GetRLScene(), GetScene(), GetTime(), Init(), IsEpisodeEnd(), OutputCharState(), ResetScene(), SpawnBigProjectile(), SpawnProjectile(), UpdateGroundDrawMesh(), and UpdateScene().
mSelectedObj
cSimObj* cDrawSceneSimChar::mSelectedObj protected
Definition at line 48 of file DrawSceneSimChar.h.
Referenced by ApplyUIForce(), HandleRayTest(), ObjectSelected(), and ResetUI().
mSelectObjLocalPos
tVector cDrawSceneSimChar::mSelectObjLocalPos protected
Definition at line 47 of file DrawSceneSimChar.h.
Referenced by ApplyUIForce(), HandleRayTest(), and ResetUI().
mTraceHandles
std::vector<int> cDrawSceneSimChar::mTraceHandles protected
Definition at line 42 of file DrawSceneSimChar.h.
Referenced by AddCharTrace(), and InitTracer().
mTracer
cObjTracer cDrawSceneSimChar::mTracer protected
Definition at line 41 of file DrawSceneSimChar.h.
Referenced by AddCharTrace(), Clear(), DrawTrace(), InitTracer(), ResetScene(), ToggleTrace(), and UpdateTracer().
mTracerBufferSize
int cDrawSceneSimChar::mTracerBufferSize protected
Definition at line 50 of file DrawSceneSimChar.h.
Referenced by AddCharTrace(), and cDrawSceneSimChar().
mTracerSamplePeriod
double cDrawSceneSimChar::mTracerSamplePeriod protected
Definition at line 51 of file DrawSceneSimChar.h.
Referenced by cDrawSceneSimChar(), and InitTracer().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/DrawSceneSimChar.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/DrawSceneSimChar.cpp