My Project: cDrawScene Class Reference
cDrawScene Class Reference
#include <DrawScene.h>
Public Types
enum eCamTrackMode {
eCamTrackModeXZ, eCamTrackModeY, eCamTrackModeXYZ, eCamTrackModeStill,
eCamTrackModeFixed, eCamTrackModeMax
}
Public Member Functions
virtual ~cDrawScene ()
virtual void ParseArgs (const std::shared_ptr< cArgParser > &parser)
virtual void Init ()
virtual void Reset ()
virtual void Draw ()
virtual void MouseClick (int button, int state, double device_x, double device_y)
virtual void MouseMove (double device_x, double device_y)
virtual void EnableDrawInfo (bool enable)
virtual std::string GetName () const
Public Member Functions inherited from cScene
virtual ~cScene ()
virtual void Clear ()
virtual void Update (double timestep)
virtual void Keyboard (unsigned char key, double device_x, double device_y)
virtual void Shutdown ()
virtual bool IsDone () const
virtual double GetTime () const
virtual bool HasRandSeed () const
virtual void SetRandSeed (unsigned long seed)
virtual unsigned long GetRandSeed () const
virtual bool IsEpisodeEnd () const
virtual bool CheckValidEpisode () const
Protected Member Functions
cDrawScene ()
virtual void ParseCamTrackMode (const std::shared_ptr< cArgParser > &parser, eCamTrackMode &out_mode) const
virtual void Reshape (int w, int h)
virtual void ResizeCamera (int w, int h)
virtual void InitCamera ()
virtual eCamTrackMode GetCamTrackMode () const
virtual void UpdateCamera ()
virtual void UpdateCameraTracking ()
virtual void UpdateCameraStill ()
virtual double GetCamStillSnapDistX () const
virtual tVector GetCamTrackPos () const
virtual tVector GetCamStillPos () const
virtual void ResetCamera ()
virtual tVector GetDefaultCamFocus () const
virtual void ClearFrame ()
virtual tVector GetBkgColor () const
virtual void SetupView ()
virtual void RestoreView ()
virtual tVector GetLightDirection () const
virtual void DrawScene ()
virtual void DrawGrid () const
virtual void DrawGroundMainScene ()
virtual void DrawCharacterMainScene ()
virtual void DrawObjsMainScene ()
virtual void DrawMiscMainScene ()
virtual void DrawGround () const
virtual void DrawCharacters () const
virtual void DrawObjs () const
virtual void DrawMisc () const
virtual void DrawInfo () const
virtual tVector GetVisOffset () const
virtual tVector GetLineColor () const
virtual tVector GetGroundColor () const
virtual void InitRenderResources ()
virtual bool LoadTextures ()
virtual void SetupMeshShader ()
virtual void DoShadowPass ()
Protected Member Functions inherited from cScene
cScene ()
virtual void ResetParams ()
virtual void ResetScene ()
virtual void InitTimers ()
virtual void ResetTimers ()
virtual void UpdateTimers (double timestep)
Protected Attributes
eCamTrackMode mCamTrackMode
cCamera mCamera
cCamera mShadowCam
bool mDrawInfo
std::unique_ptr< cShadowMap > mShadowMap
std::unique_ptr< cTextureDesc > mGridTex
std::unique_ptr< cShader > mShaderMesh
std::unique_ptr< cShader > mShaderDepth
GLuint mMeshLightDirHandle
GLuint mMeshLightColourHandle
GLuint mMeshAmbientColourHandle
GLuint mMeshShadowProjHandle
GLuint mMeshMaterialDataHandle
GLuint mMeshFogColorHandle
GLuint mMeshFogDataHandle
Protected Attributes inherited from cScene
cRand mRand
bool mHasRandSeed
unsigned long mRandSeed
std::shared_ptr< cArgParser > mArgParser
cTimer::tParams mTimerParams
cTimer mTimer
Detailed Description
Definition at line 8 of file DrawScene.h.
Member Enumeration Documentation
eCamTrackMode
enum cDrawScene::eCamTrackMode
Enumerator
eCamTrackModeXZ
eCamTrackModeY
eCamTrackModeXYZ
eCamTrackModeStill
eCamTrackModeFixed
eCamTrackModeMax
Definition at line 12 of file DrawScene.h.
     {
         eCamTrackModeXZ,
         eCamTrackModeY,
         eCamTrackModeXYZ,
         eCamTrackModeStill,
         eCamTrackModeFixed,
         eCamTrackModeMax
     };
Constructor & Destructor Documentation
~cDrawScene()
cDrawScene::~cDrawScene () virtual
Definition at line 24 of file DrawScene.cpp.
 {
 }
cDrawScene()
cDrawScene::cDrawScene () protected
Definition at line 18 of file DrawScene.cpp.
 {
     mCamTrackMode = eCamTrackModeXZ;
     mDrawInfo = true;
 }
References eCamTrackModeXZ, mCamTrackMode, and mDrawInfo.
Member Function Documentation
ClearFrame()
void cDrawScene::ClearFrame () protected virtual
Definition at line 313 of file DrawScene.cpp.
 {
     double depth = 1;
     tVector col = GetBkgColor();
     cDrawUtil::ClearDepth(depth);
     cDrawUtil::ClearColor(col);
 }
References cDrawUtil::ClearColor(), cDrawUtil::ClearDepth(), and GetBkgColor().
Referenced by Draw().
DoShadowPass()
void cDrawScene::DoShadowPass () protected virtual
Definition at line 560 of file DrawScene.cpp.
 {
     // front face culling to prevent shelf occlusion
     glCullFace(GL_FRONT);
     float dist = 30.f;
     const tVector& sun_dir = GetLightDirection();
     tVector delta = dist * sun_dir;
     tVector focus = mCamera.GetFocus();
     mShadowCam.SetPosition(focus + delta);
     mShadowCam.SetFocus(focus);
     mShadowMap->BindBuffer();
     mShaderDepth->Bind();
     cDrawUtil::ClearColor(tVector(1, 1, 1, 0));
     cDrawUtil::ClearDepth(1);
     // shadow pass
     cDrawUtil::PushMatrixProj();
     mShadowCam.SetupGLProj();
     cDrawUtil::PushMatrixView();
     mShadowCam.SetupGLView();
     DrawCharacters();
     DrawObjs();
     DrawMisc();
     glCullFace(GL_BACK);
     DrawGround();
     mShaderDepth->Unbind();
     mShadowMap->UnbindBuffer();
     cDrawUtil::PopMatrixProj();
     cDrawUtil::PopMatrixView();
 }
References cDrawUtil::ClearColor(), cDrawUtil::ClearDepth(), DrawCharacters(), DrawGround(), DrawMisc(), DrawObjs(), cCamera::GetFocus(), GetLightDirection(), mCamera, mShaderDepth, mShadowCam, mShadowMap, cDrawUtil::PopMatrixProj(), cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixProj(), cDrawUtil::PushMatrixView(), cCamera::SetFocus(), cCamera::SetPosition(), cCamera::SetupGLProj(), and cCamera::SetupGLView().
Referenced by DrawScene().
Draw()
void cDrawScene::Draw () virtual
Reimplemented from cScene.
Definition at line 49 of file DrawScene.cpp.
 {
     SetupView();
     ClearFrame();
     DrawScene();
     RestoreView();
 }
References ClearFrame(), DrawScene(), RestoreView(), and SetupView().
DrawCharacterMainScene()
void cDrawScene::DrawCharacterMainScene () protected virtual
Definition at line 407 of file DrawScene.cpp.
 {
     const double roughness = 0.4;
     const double enable_tex = 0;
     mShaderMesh->SetUniform4(mMeshMaterialDataHandle, tVector(roughness, enable_tex, 0, 0));
     DrawCharacters();
 }
References DrawCharacters(), mMeshMaterialDataHandle, and mShaderMesh.
Referenced by DrawScene().
DrawCharacters()
void cDrawScene::DrawCharacters () const protected virtual
Reimplemented in cDrawSceneSimChar, cDrawSceneKinChar, and cDrawSceneImitate.
Definition at line 435 of file DrawScene.cpp.
 {
 }
Referenced by DoShadowPass(), and DrawCharacterMainScene().
DrawGrid()
void cDrawScene::DrawGrid () const protected virtual
Definition at line 378 of file DrawScene.cpp.
 {
     const double spacing = 0.10f;
     const double line_width = 1;
     const double big_spacing = spacing * 5.f;
     const double big_line_width = 2;
     const tVector offset = tVector(0, 0, -1, 0);
     tVector origin = mCamera.GetFocus();
     origin += offset;
     tVector size = tVector(mCamera.GetWidth(), mCamera.GetHeight(), 0, 0);
     cDrawUtil::DrawGrid2D(origin, size, spacing, line_width);
     cDrawUtil::DrawGrid2D(origin, size, big_spacing, big_line_width);
 }
References cDrawUtil::DrawGrid2D(), cCamera::GetFocus(), cCamera::GetHeight(), cCamera::GetWidth(), and mCamera.
DrawGround()
void cDrawScene::DrawGround () const protected virtual
Reimplemented in cDrawSceneSimChar, and cDrawSceneKinChar.
Definition at line 431 of file DrawScene.cpp.
 {
 }
Referenced by DoShadowPass(), and DrawGroundMainScene().
DrawGroundMainScene()
void cDrawScene::DrawGroundMainScene () protected virtual
Definition at line 394 of file DrawScene.cpp.
 {
     const double roughness = 0.5;
     const double enable_tex = 1;
     mShaderMesh->SetUniform4(mMeshMaterialDataHandle, tVector(roughness, enable_tex, 0, 0));
     mGridTex->BindTex(GL_TEXTURE0);
     DrawGround();
     mGridTex->UnbindTex(GL_TEXTURE0);
 }
References DrawGround(), mGridTex, mMeshMaterialDataHandle, and mShaderMesh.
Referenced by DrawScene().
DrawInfo()
void cDrawScene::DrawInfo () const protected virtual
Reimplemented in cDrawSceneSimChar.
Definition at line 447 of file DrawScene.cpp.
 {
 }
Referenced by DrawScene().
DrawMisc()
void cDrawScene::DrawMisc () const protected virtual
Reimplemented in cDrawSceneSimChar.
Definition at line 443 of file DrawScene.cpp.
 {
 }
Referenced by DoShadowPass(), and DrawMiscMainScene().
DrawMiscMainScene()
void cDrawScene::DrawMiscMainScene () protected virtual
Definition at line 423 of file DrawScene.cpp.
 {
     const double roughness = 0.4;
     const double enable_tex = 0;
     mShaderMesh->SetUniform4(mMeshMaterialDataHandle, tVector(roughness, enable_tex, 0, 0));
     DrawMisc();
 }
References DrawMisc(), mMeshMaterialDataHandle, and mShaderMesh.
Referenced by DrawScene().
DrawObjs()
void cDrawScene::DrawObjs () const protected virtual
Reimplemented in cDrawSceneSimChar.
Definition at line 439 of file DrawScene.cpp.
 {
 }
Referenced by DoShadowPass(), and DrawObjsMainScene().
DrawObjsMainScene()
void cDrawScene::DrawObjsMainScene () protected virtual
Definition at line 415 of file DrawScene.cpp.
 {
     const double roughness = 0.4;
     const double enable_tex = 0;
     mShaderMesh->SetUniform4(mMeshMaterialDataHandle, tVector(roughness, enable_tex, 0, 0));
     DrawObjs();
 }
References DrawObjs(), mMeshMaterialDataHandle, and mShaderMesh.
Referenced by DrawScene().
DrawScene()
void cDrawScene::DrawScene () protected virtual
Definition at line 346 of file DrawScene.cpp.
 {
     DoShadowPass();
     mShaderMesh->Bind();
     SetupMeshShader();
     glEnable(GL_CULL_FACE);
     glCullFace(GL_BACK);
     DrawGroundMainScene();
     DrawCharacterMainScene();
     DrawObjsMainScene();
     DrawMiscMainScene();
     mShaderMesh->Unbind();
     if (mDrawInfo)
     {
         // info is drawn in screen space
         cDrawUtil::PushMatrixProj();
         cDrawUtil::LoadIdentityProj();
         cDrawUtil::PushMatrixView();
         cDrawUtil::LoadIdentityView();
         DrawInfo();
         cDrawUtil::PopMatrixProj();
         cDrawUtil::PopMatrixView();
     }
 }
References DoShadowPass(), DrawCharacterMainScene(), DrawGroundMainScene(), DrawInfo(), DrawMiscMainScene(), DrawObjsMainScene(), cDrawUtil::LoadIdentityProj(), cDrawUtil::LoadIdentityView(), mDrawInfo, mShaderMesh, cDrawUtil::PopMatrixProj(), cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixProj(), cDrawUtil::PushMatrixView(), and SetupMeshShader().
Referenced by Draw().
EnableDrawInfo()
void cDrawScene::EnableDrawInfo (bool enable) virtual
Definition at line 69 of file DrawScene.cpp.
 {
     mDrawInfo = enable;
 }
References mDrawInfo.
GetBkgColor()
tVector cDrawScene::GetBkgColor () const protected virtual
Definition at line 321 of file DrawScene.cpp.
 {
     return tVector(0.97, 0.97, 1, 0);
 }
Referenced by ClearFrame().
GetCamStillPos()
tVector cDrawScene::GetCamStillPos () const protected virtual
Reimplemented in cDrawSceneSimChar, and cDrawSceneKinChar.
Definition at line 281 of file DrawScene.cpp.
 {
     return tVector::Zero();
 }
Referenced by ResetCamera(), and UpdateCameraStill().
GetCamStillSnapDistX()
double cDrawScene::GetCamStillSnapDistX () const protected virtual
Definition at line 250 of file DrawScene.cpp.
 {
     const tVector axis = tVector(1, 0, 0, 0);
     double dist = 0.5 * mCamera.GetWidth();
     tVector view_delta = mCamera.GetFocus() - mCamera.GetPosition();
     tVector view_dir = view_delta.normalized();
     double len = view_delta.norm() - mCamera.GetNearZ();
     view_delta = view_dir * len;
     view_delta[1] = 0;
     view_delta[3] = 0;
     len = view_delta.norm();
     if (len > 0)
     {
         view_delta /= len;
         double dot = view_delta.dot(axis);
         double lerp = std::abs(dot);
         lerp = std::pow(lerp, 4);
         lerp = 1 - lerp;
         dist = lerp * dist + (1 - lerp) * 0.5 * len;
     }
     return dist;
 }
References cCamera::GetFocus(), cCamera::GetNearZ(), cCamera::GetPosition(), cCamera::GetWidth(), and mCamera.
Referenced by UpdateCameraStill().
GetCamTrackMode()
cDrawScene::eCamTrackMode cDrawScene::GetCamTrackMode () const protected virtual
Definition at line 136 of file DrawScene.cpp.
 {
     return mCamTrackMode;
 }
References mCamTrackMode.
Referenced by ResetCamera(), UpdateCamera(), and UpdateCameraTracking().
GetCamTrackPos()
tVector cDrawScene::GetCamTrackPos () const protected virtual
Reimplemented in cDrawSceneSimChar, and cDrawSceneKinChar.
Definition at line 276 of file DrawScene.cpp.
 {
     return tVector::Zero();
 }
Referenced by ResetCamera(), UpdateCameraStill(), and UpdateCameraTracking().
GetDefaultCamFocus()
tVector cDrawScene::GetDefaultCamFocus () const protected virtual
Reimplemented in cDrawSceneSimChar, and cDrawSceneKinChar.
Definition at line 308 of file DrawScene.cpp.
 {
     return tVector::Zero();
 }
Referenced by ResetCamera().
GetGroundColor()
tVector cDrawScene::GetGroundColor () const protected virtual
Definition at line 462 of file DrawScene.cpp.
 {
     return tVector::Ones();
 }
Referenced by cDrawSceneKinChar::DrawGround(), and cDrawSceneSimChar::DrawGround().
GetLightDirection()
tVector cDrawScene::GetLightDirection () const protected virtual
Definition at line 341 of file DrawScene.cpp.
 {
     return tVector(0.6, 0.67, 0.45, 0).normalized();
 }
Referenced by DoShadowPass(), and SetupMeshShader().
GetLineColor()
tVector cDrawScene::GetLineColor () const protected virtual
Definition at line 457 of file DrawScene.cpp.
 {
     return gLineColor;
 }
References gLineColor.
Referenced by cDrawSceneSimChar::DrawCharacter(), and cDrawSceneSimChar::DrawObjs().
GetName()
std::string cDrawScene::GetName () const virtual
Implements cScene.
Reimplemented in cDrawRLScene, cDrawSceneSimChar, cDrawSceneImitate, and cDrawSceneKinChar.
Definition at line 75 of file DrawScene.cpp.
 {
     return "Draw";
 }
GetVisOffset()
tVector cDrawScene::GetVisOffset () const protected virtual
Definition at line 452 of file DrawScene.cpp.
 {
     return tVector::Zero();
 }
Referenced by cDrawSceneSimChar::DrawBodyVel(), cDrawSceneSimChar::DrawCoM(), cDrawSceneSimChar::DrawHeading(), cDrawSceneSimChar::DrawTorque(), and cDrawSceneSimChar::DrawTrace().
Init()
void cDrawScene::Init () virtual
Reimplemented from cScene.
Reimplemented in cDrawSceneSimChar, cDrawSceneImitate, cDrawSceneKinChar, and cDrawRLScene.
Definition at line 34 of file DrawScene.cpp.
 {
     cScene::Init();
     InitCamera();
     ResetCamera();
     InitRenderResources();
 }
References cScene::Init(), InitCamera(), InitRenderResources(), and ResetCamera().
Referenced by cDrawRLScene::Init(), cDrawSceneKinChar::Init(), and cDrawSceneSimChar::Init().
InitCamera()
void cDrawScene::InitCamera () protected virtual
Definition at line 129 of file DrawScene.cpp.
 {
     cCamera::eProj proj = cCamera::eProjPerspective;
     mCamera = cCamera(proj, gCameraPosition, gCameraFocus, gCameraUp,
                         gViewWidth, gViewHeight, gViewNearZ, gViewFarZ);
 }
References cCamera::eProjPerspective, gCameraFocus, gCameraPosition, gCameraUp, gViewFarZ, gViewHeight, gViewNearZ, gViewWidth, and mCamera.
Referenced by Init().
InitRenderResources()
void cDrawScene::InitRenderResources () protected virtual
Definition at line 467 of file DrawScene.cpp.
 {
     bool succ = true;
     {
         mShaderDepth = std::unique_ptr<cShader>(new cShader());
         succ &= mShaderDepth->BuildShader("data/shaders/Mesh_VS.glsl", "data/shaders/Depth_PS.glsl");
     }
     {
         mShaderMesh = std::unique_ptr<cShader>(new cShader());
         succ &= mShaderMesh->BuildShader("data/shaders/Mesh_VS.glsl", "data/shaders/Lighting_Lambert_PS.glsl");
         mShaderMesh->Bind();
         mShaderMesh->GetUniformHandle(mMeshLightDirHandle, "gLightDir");
         mShaderMesh->GetUniformHandle(mMeshLightColourHandle, "gLightColour");
         mShaderMesh->GetUniformHandle(mMeshAmbientColourHandle, "gAmbientColour");
         mShaderMesh->GetUniformHandle(mMeshShadowProjHandle, "gShadowProj");
         mShaderMesh->GetUniformHandle(mMeshMaterialDataHandle, "gMaterialData");
         mShaderMesh->GetUniformHandle(mMeshFogColorHandle, "gFogColor");
         mShaderMesh->GetUniformHandle(mMeshFogDataHandle, "gFogData");
         GLint albedo_tex = glGetUniformLocation(mShaderMesh->GetProg(), "gTexture");
         glUniform1i(albedo_tex, 0);
         GLint shadow_tex = glGetUniformLocation(mShaderMesh->GetProg(), "gShadowTex");
         glUniform1i(shadow_tex, 1);
         mShaderMesh->Unbind();
     }
     float shadow_size = 40.f;
     float shadow_near_z = 1.f;
     float shadow_far_z = 60.f;
     int shadow_res = 2048;
     mShadowCam = cCamera(cCamera::eProjOrtho, tVector(0, 0, 1, 0), tVector::Zero(),
         tVector(0, 1, 0, 0), shadow_size, shadow_size, shadow_near_z,
         shadow_far_z);
     mShadowMap = std::unique_ptr<cShadowMap>(new cShadowMap());
     mShadowMap->Init(shadow_res, shadow_res);
     succ &= LoadTextures();
     if (!succ)
     {
         printf("Failed to setup render resources\n");
     }
 }
References cCamera::eProjOrtho, LoadTextures(), mMeshAmbientColourHandle, mMeshFogColorHandle, mMeshFogDataHandle, mMeshLightColourHandle, mMeshLightDirHandle, mMeshMaterialDataHandle, mMeshShadowProjHandle, mShaderDepth, mShaderMesh, mShadowCam, and mShadowMap.
Referenced by Init().
LoadTextures()
bool cDrawScene::LoadTextures () protected virtual
Definition at line 514 of file DrawScene.cpp.
 {
     bool succ = true;
     mGridTex = std::unique_ptr<cTextureDesc>(new cTextureDesc("data/textures/grid0.png", true));
     succ &= mGridTex->IsValid();
     return succ;
 }
References mGridTex.
Referenced by InitRenderResources().
MouseClick()
void cDrawScene::MouseClick (int button, int state, double device_x, double device_y) virtual
Reimplemented from cScene.
Reimplemented in cDrawSceneSimChar.
Definition at line 57 of file DrawScene.cpp.
 {
     cScene::MouseClick(button, state, x, y);
     mCamera.MouseClick(button, state, x, y);
 }
References mCamera, cScene::MouseClick(), and cCamera::MouseClick().
Referenced by cDrawSceneSimChar::MouseClick().
MouseMove()
void cDrawScene::MouseMove (double device_x, double device_y) virtual
Reimplemented from cScene.
Reimplemented in cDrawSceneSimChar.
Definition at line 63 of file DrawScene.cpp.
 {
     cScene::MouseMove(x, y);
     mCamera.MouseMove(x, y);
 }
References mCamera, cScene::MouseMove(), and cCamera::MouseMove().
Referenced by cDrawSceneSimChar::MouseMove().
ParseArgs()
void cDrawScene::ParseArgs (const std::shared_ptr< cArgParser > & parser) virtual
Reimplemented from cScene.
Definition at line 28 of file DrawScene.cpp.
 {
     cScene::ParseArgs(parser);
     ParseCamTrackMode(parser, mCamTrackMode);
 }
References mCamTrackMode, cScene::ParseArgs(), and ParseCamTrackMode().
ParseCamTrackMode()
void cDrawScene::ParseCamTrackMode (const std::shared_ptr< cArgParser > & parser, eCamTrackMode & out_mode) const protected virtual
Definition at line 80 of file DrawScene.cpp.
 {
     std::string str = "";
     parser->ParseString("cam_track_mode", str);
     if (str != "")
     {
         if (str == "xz")
         {
             out_mode = eCamTrackModeXZ;
         }
         else if (str == "y")
         {
             out_mode = eCamTrackModeY;
         }
         else if (str == "xyz")
         {
             out_mode = eCamTrackModeXYZ;
         }
         else if (str == "still")
         {
             out_mode = eCamTrackModeStill;
         }
         else if (str == "fixed")
         {
             out_mode = eCamTrackModeFixed;
         }
         else
         {
             assert(false); // unsupported track mode
         }
     }
 }
References eCamTrackModeFixed, eCamTrackModeStill, eCamTrackModeXYZ, eCamTrackModeXZ, and eCamTrackModeY.
Referenced by ParseArgs().
Reset()
void cDrawScene::Reset () virtual
Reimplemented from cScene.
Reimplemented in cDrawSceneKinChar.
Definition at line 43 of file DrawScene.cpp.
 {
     cScene::Reset();
     ResetCamera();
 }
References cScene::Reset(), and ResetCamera().
Referenced by cDrawSceneKinChar::Reset().
ResetCamera()
void cDrawScene::ResetCamera () protected virtual
Definition at line 286 of file DrawScene.cpp.
 {
     tVector target_pos = GetDefaultCamFocus();
     eCamTrackMode mode = GetCamTrackMode();
     if (mode == eCamTrackModeXZ
         || mode == eCamTrackModeY)
     {
         target_pos = GetCamTrackPos();
     }
     else if (mode == eCamTrackModeStill)
     {
         target_pos = GetCamStillPos();
     }
     tVector cam_pos = GetDefaultCamFocus();
     cam_pos[0] = target_pos[0];
     cam_pos[1] = target_pos[1];
     mCamera.TranslateFocus(cam_pos);
 }
References eCamTrackModeStill, eCamTrackModeXZ, eCamTrackModeY, GetCamStillPos(), GetCamTrackMode(), GetCamTrackPos(), GetDefaultCamFocus(), mCamera, and cCamera::TranslateFocus().
Referenced by Init(), and Reset().
Reshape()
void cDrawScene::Reshape (int w, int h) protected virtual
Reimplemented from cScene.
Definition at line 114 of file DrawScene.cpp.
 {
     cScene::Reshape(w, h);
     ResizeCamera(w, h);
 }
References cScene::Reshape(), and ResizeCamera().
ResizeCamera()
void cDrawScene::ResizeCamera (int w, int h) protected virtual
Definition at line 120 of file DrawScene.cpp.
 {
     double prev_view_w = mCamera.GetWidth();
     double prev_view_h = mCamera.GetHeight();
     double new_view_h = prev_view_h;
     double new_view_w = (prev_view_h * w) / h;
     mCamera.Resize(new_view_w, new_view_h);
 }
References cCamera::GetHeight(), cCamera::GetWidth(), mCamera, and cCamera::Resize().
Referenced by Reshape().
RestoreView()
void cDrawScene::RestoreView () protected virtual
Definition at line 335 of file DrawScene.cpp.
 {
     cDrawUtil::PopMatrixProj();
     cDrawUtil::PopMatrixView();
 }
References cDrawUtil::PopMatrixProj(), and cDrawUtil::PopMatrixView().
Referenced by Draw().
SetupMeshShader()
void cDrawScene::SetupMeshShader () protected virtual
Definition at line 522 of file DrawScene.cpp.
 {
     tMatrix view_mat = mCamera.BuildWorldViewMatrix();
     tVector cam_focus = mCamera.GetFocus();
     tVector cam_pos = mCamera.GetPosition();
     double near_dist = mCamera.GetNearZ();
     const double fog_cutoff = (cam_focus - cam_pos).norm() - near_dist;
     const double fog_decay = 0.001;
     const tVector ambient_col = tVector(0.6, 0.6, 0.6, 0);
     const tVector light_col = tVector(0.5, 0.5, 0.5, 0);
     const tVector fog_col = tVector(0.97, 0.97, 1, 1);
     const tVector fog_data = tVector(fog_cutoff, fog_decay, 0, 0);
     tVector light_dir = GetLightDirection();
     light_dir = view_mat * light_dir;
     mShaderMesh->SetUniform3(mMeshLightDirHandle, light_dir);
     mShaderMesh->SetUniform3(mMeshLightColourHandle, light_col);
     mShaderMesh->SetUniform3(mMeshAmbientColourHandle, ambient_col);
     mShaderMesh->SetUniform4(mMeshFogColorHandle, fog_col);
     mShaderMesh->SetUniform4(mMeshFogDataHandle, fog_data);
     tMatrix view_world = mCamera.BuildViewWorldMatrix();
     tMatrix shadow_view = mShadowCam.BuildWorldViewMatrix();
     tMatrix shadow_proj = mShadowCam.BuildProjMatrix();
     tMatrix shadow_mat = shadow_proj * shadow_view * view_world;
     float shadow_mat_data[] = { (float)shadow_mat(0, 0), (float)shadow_mat(1, 0), (float)shadow_mat(2, 0), (float)shadow_mat(3, 0),
         (float)shadow_mat(0, 1), (float)shadow_mat(1, 1), (float)shadow_mat(2, 1), (float)shadow_mat(3, 1),
         (float)shadow_mat(0, 2), (float)shadow_mat(1, 2), (float)shadow_mat(2, 2), (float)shadow_mat(3, 2),
         (float)shadow_mat(0, 3), (float)shadow_mat(1, 3), (float)shadow_mat(2, 3), (float)shadow_mat(3, 3) };
     glProgramUniformMatrix4fv(mShaderMesh->GetProg(), mMeshShadowProjHandle, 1, false, shadow_mat_data);
     mShadowMap->BindTex(GL_TEXTURE1);
 }
References cCamera::BuildProjMatrix(), cCamera::BuildViewWorldMatrix(), cCamera::BuildWorldViewMatrix(), cCamera::GetFocus(), GetLightDirection(), cCamera::GetNearZ(), cCamera::GetPosition(), mCamera, mMeshAmbientColourHandle, mMeshFogColorHandle, mMeshFogDataHandle, mMeshLightColourHandle, mMeshLightDirHandle, mMeshShadowProjHandle, mShaderMesh, mShadowCam, and mShadowMap.
Referenced by DrawScene().
SetupView()
void cDrawScene::SetupView () protected virtual
Definition at line 326 of file DrawScene.cpp.
 {
     cDrawUtil::PushMatrixProj();
     mCamera.SetupGLProj();
     cDrawUtil::PushMatrixView();
     mCamera.SetupGLView();
 }
References mCamera, cDrawUtil::PushMatrixProj(), cDrawUtil::PushMatrixView(), cCamera::SetupGLProj(), and cCamera::SetupGLView().
Referenced by Draw().
UpdateCamera()
void cDrawScene::UpdateCamera () protected virtual
Definition at line 141 of file DrawScene.cpp.
 {
     eCamTrackMode mode = GetCamTrackMode();
     if (mode == eCamTrackModeXZ
         || mode == eCamTrackModeY
         || mode == eCamTrackModeXYZ)
     {
         UpdateCameraTracking();
     }
     else if (mode == eCamTrackModeStill)
     {
         UpdateCameraStill();
     }
 }
References eCamTrackModeStill, eCamTrackModeXYZ, eCamTrackModeXZ, eCamTrackModeY, GetCamTrackMode(), UpdateCameraStill(), and UpdateCameraTracking().
Referenced by cDrawSceneKinChar::Update(), and cDrawSceneSimChar::Update().
UpdateCameraStill()
void cDrawScene::UpdateCameraStill () protected virtual
Definition at line 206 of file DrawScene.cpp.
 {
     tVector track_pos = GetCamTrackPos();
     tVector cam_focus = mCamera.GetFocus();
     double cam_w = mCamera.GetWidth();
     double cam_h = mCamera.GetHeight();
     double cam_still_snap_dist = GetCamStillSnapDistX();
     const double pad_x = std::min(0.5, 0.4 * cam_still_snap_dist);
     const double pad_y = std::min(0.0, 0.2 * cam_h);
     double avg_h = 0;
     bool snap_x = std::abs(track_pos[0] - cam_focus[0]) > cam_still_snap_dist - pad_x;
     bool snap_y = (track_pos[1] - cam_focus[1]) > 0.5 * cam_h - pad_y
         || (track_pos[1] - cam_focus[1]) < -(0.5 * cam_h - pad_y);
     if (snap_x || snap_y)
     {
         tVector snap_pos = GetCamStillPos();
         cam_focus[0] = snap_pos[0];
         cam_focus[1] = snap_pos[1];
         tVector pos_delta = track_pos - snap_pos;
         if (std::abs(pos_delta[0]) > cam_still_snap_dist - pad_x)
         {
             cam_focus[0] += pos_delta[0];
         }
         if ((pos_delta[1]) > 0.5 * cam_h - pad_y
             || (pos_delta[1]) < -(0.5 * cam_h - pad_y))
         {
             cam_focus[1] += pos_delta[1];
         }
         if (snap_x)
         {
             cam_focus[0] += cam_still_snap_dist - pad_x;
         }
     }
     mCamera.TranslateFocus(cam_focus);
 }
References GetCamStillPos(), GetCamStillSnapDistX(), GetCamTrackPos(), cCamera::GetFocus(), cCamera::GetHeight(), cCamera::GetWidth(), mCamera, and cCamera::TranslateFocus().
Referenced by UpdateCamera().
UpdateCameraTracking()
void cDrawScene::UpdateCameraTracking () protected virtual
Definition at line 156 of file DrawScene.cpp.
 {
     eCamTrackMode mode = GetCamTrackMode();
     if (mode == eCamTrackModeXYZ)
     {
         tVector track_pos = GetCamTrackPos();
         tVector focus_pos = mCamera.GetFocus();
         tVector cam_pos = mCamera.GetPosition();
         mCamera.TranslateFocus(track_pos);
     }
     else if (mode == eCamTrackModeXZ
         || mode == eCamTrackModeY)
     {
         tVector track_pos = GetCamTrackPos();
         tVector cam_focus = mCamera.GetFocus();
         double cam_w = mCamera.GetWidth();
         double cam_h = mCamera.GetHeight();
         const double y_pad = std::min(0.5, 0.8 * 0.5 * cam_h);
         const double x_pad = std::min(0.5, 0.8 * 0.5 * cam_w);
         if (mode == eCamTrackModeXZ)
         {
             cam_focus[0] = track_pos[0];
             cam_focus[2] = track_pos[2];
             if (std::abs(track_pos[1] - cam_focus[1]) > ((0.5 * cam_h) - y_pad))
             {
                 const double blend = 0.5;
                 double tar_y = track_pos[1] + ((0.5 * cam_h) - y_pad);
                 cam_focus[1] = (1 - blend) * cam_focus[1] + blend * tar_y;
             }
         }
         else
         {
             cam_focus[1] = track_pos[1];
             const double blend = 0.5;
             double tar_delta = track_pos[0] - cam_focus[0];
             if (std::abs(tar_delta) > ((0.5 * cam_w) - x_pad))
             {
                 double tar_x = track_pos[0] + cMathUtil::Sign(tar_delta) * ((0.95 * cam_w) - x_pad);
                 cam_focus[0] = (1 - blend) * cam_focus[0] + blend * tar_x;
             }
         }
         mCamera.TranslateFocus(cam_focus);
     }
 }
References eCamTrackModeXYZ, eCamTrackModeXZ, eCamTrackModeY, GetCamTrackMode(), GetCamTrackPos(), cCamera::GetFocus(), cCamera::GetHeight(), cCamera::GetPosition(), cCamera::GetWidth(), mCamera, cMathUtil::Sign(), and cCamera::TranslateFocus().
Referenced by UpdateCamera().
Member Data Documentation
mCamera
cCamera cDrawScene::mCamera protected
Definition at line 39 of file DrawScene.h.
Referenced by cDrawSceneSimChar::ApplyUIForce(), DoShadowPass(), DrawGrid(), cDrawSceneSimChar::DrawGround(), cDrawSceneSimChar::DrawPoliInfo(), cDrawSceneSimChar::GetCamStillPos(), GetCamStillSnapDistX(), InitCamera(), cDrawSceneSimChar::MouseClick(), MouseClick(), MouseMove(), ResetCamera(), ResizeCamera(), SetupMeshShader(), SetupView(), UpdateCameraStill(), and UpdateCameraTracking().
mCamTrackMode
eCamTrackMode cDrawScene::mCamTrackMode protected
Definition at line 37 of file DrawScene.h.
Referenced by cDrawScene(), GetCamTrackMode(), and ParseArgs().
mDrawInfo
bool cDrawScene::mDrawInfo protected
Definition at line 42 of file DrawScene.h.
Referenced by cDrawScene(), DrawScene(), and EnableDrawInfo().
mGridTex
std::unique_ptr<cTextureDesc> cDrawScene::mGridTex protected
Definition at line 46 of file DrawScene.h.
Referenced by DrawGroundMainScene(), and LoadTextures().
mMeshAmbientColourHandle
GLuint cDrawScene::mMeshAmbientColourHandle protected
Definition at line 55 of file DrawScene.h.
Referenced by InitRenderResources(), and SetupMeshShader().
mMeshFogColorHandle
GLuint cDrawScene::mMeshFogColorHandle protected
Definition at line 58 of file DrawScene.h.
Referenced by InitRenderResources(), and SetupMeshShader().
mMeshFogDataHandle
GLuint cDrawScene::mMeshFogDataHandle protected
Definition at line 59 of file DrawScene.h.
Referenced by InitRenderResources(), and SetupMeshShader().
mMeshLightColourHandle
GLuint cDrawScene::mMeshLightColourHandle protected
Definition at line 54 of file DrawScene.h.
Referenced by InitRenderResources(), and SetupMeshShader().
mMeshLightDirHandle
GLuint cDrawScene::mMeshLightDirHandle protected
Definition at line 53 of file DrawScene.h.
Referenced by InitRenderResources(), and SetupMeshShader().
mMeshMaterialDataHandle
GLuint cDrawScene::mMeshMaterialDataHandle protected
Definition at line 57 of file DrawScene.h.
Referenced by DrawCharacterMainScene(), DrawGroundMainScene(), DrawMiscMainScene(), DrawObjsMainScene(), and InitRenderResources().
mMeshShadowProjHandle
GLuint cDrawScene::mMeshShadowProjHandle protected
Definition at line 56 of file DrawScene.h.
Referenced by InitRenderResources(), and SetupMeshShader().
mShaderDepth
std::unique_ptr<cShader> cDrawScene::mShaderDepth protected
Definition at line 50 of file DrawScene.h.
Referenced by DoShadowPass(), and InitRenderResources().
mShaderMesh
std::unique_ptr<cShader> cDrawScene::mShaderMesh protected
Definition at line 49 of file DrawScene.h.
Referenced by DrawCharacterMainScene(), DrawGroundMainScene(), DrawMiscMainScene(), DrawObjsMainScene(), DrawScene(), InitRenderResources(), and SetupMeshShader().
mShadowCam
cCamera cDrawScene::mShadowCam protected
Definition at line 40 of file DrawScene.h.
Referenced by DoShadowPass(), InitRenderResources(), and SetupMeshShader().
mShadowMap
std::unique_ptr<cShadowMap> cDrawScene::mShadowMap protected
Definition at line 45 of file DrawScene.h.
Referenced by DoShadowPass(), InitRenderResources(), and SetupMeshShader().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/DrawScene.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/scenes/DrawScene.cpp