My Project: F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/Main.cpp File Reference
Main.cpp File Reference
#include <iostream>
#include "DeepMimicCore.h"
#include "util/FileUtil.h"
#include "render/DrawUtil.h"
#include "render/TextureDesc.h"
Functions
void SetupDeepMimicCore ()
void FormatArgs (int argc, char **argv, std::vector< std::string > &out_args)
void UpdateFrameBuffer ()
void Update (double time_elapsed)
void Draw (void)
void Reshape (int w, int h)
void StepAnim (double time_step)
void Reload ()
void Reset ()
int GetNumTimeSteps ()
int CalcDisplayAnimTime (int num_timesteps)
void Shutdown ()
int GetCurrTime ()
void InitTime ()
void Animate (int callback_val)
void ToggleAnimate ()
void ChangePlaybackSpeed (double delta)
void Keyboard (unsigned char key, int x, int y)
void MouseClick (int button, int state, int x, int y)
void MouseMove (int x, int y)
void InitFrameBuffers (void)
void InitDraw (int argc, char **argv)
void SetupDraw ()
void DrawMainLoop ()
int main (int argc, char **argv)
Variables
int gWinWidth = 800
int gWinHeight = static_cast<int>(gWinWidth * 9.0 / 16.0)
bool gReshaping = false
std::unique_ptr< cTextureDesc > gDefaultFrameBuffer
const double gFPS = 60.0
const double gAnimStep = 1.0 / gFPS
const int gDisplayAnimTime = static_cast<int>(1000 * gAnimStep)
bool gAnimating = true
int gSampleCount = 0
double gPlaybackSpeed = 1
const double gPlaybackDelta = 0.05
int gPrevTime = 0
double gUpdatesPerSec = 0
std::vector< std::string > gArgs
std::unique_ptr< cDeepMimicCore > gCore
Function Documentation
Animate()
void Animate (int callback_val)
Definition at line 215 of file Main.cpp.
 {
     const double counter_decay = 0;
     if (gAnimating)
     {
         int num_steps = GetNumTimeSteps();
         int curr_time = GetCurrTime();
         int time_elapsed = curr_time - gPrevTime;
         gPrevTime = curr_time;
         double timestep = (gPlaybackSpeed < 0) ? -gAnimStep : gAnimStep;
         for (int i = 0; i < num_steps; ++i)
         {
             Update(timestep);
         }
         // FPS counting
         double update_count = num_steps / (0.001 * time_elapsed);
         if (std::isfinite(update_count))
         {
             gUpdatesPerSec = counter_decay * gUpdatesPerSec + (1 - counter_decay) * update_count;
             gCore->SetUpdatesPerSec(gUpdatesPerSec);
         }
         int timer_step = CalcDisplayAnimTime(num_steps);
         int update_dur = GetCurrTime() - curr_time;
         timer_step -= update_dur;
         timer_step = std::max(timer_step, 0);
         glutTimerFunc(timer_step, Animate, 0);
         glutPostRedisplay();
     }
     if (gCore->IsDone())
     {
         Shutdown();
     }
 }
References CalcDisplayAnimTime(), gAnimating, gAnimStep, gCore, GetCurrTime(), GetNumTimeSteps(), gPlaybackSpeed, gPrevTime, gUpdatesPerSec, isfinite, Shutdown(), and Update().
Referenced by ChangePlaybackSpeed(), SetupDraw(), and ToggleAnimate().
CalcDisplayAnimTime()
int CalcDisplayAnimTime (int num_timesteps)
Definition at line 191 of file Main.cpp.
 {
     int anim_time = static_cast<int>(gDisplayAnimTime * num_timesteps / gPlaybackSpeed);
     anim_time = std::abs(anim_time);
     return anim_time;
 }
References gDisplayAnimTime, and gPlaybackSpeed.
Referenced by Animate().
ChangePlaybackSpeed()
void ChangePlaybackSpeed (double delta)
Definition at line 264 of file Main.cpp.
 {
     double prev_playback = gPlaybackSpeed;
     gPlaybackSpeed += delta;
     gCore->SetPlaybackSpeed(gPlaybackSpeed);
     if (std::abs(prev_playback) < 0.0001 && std::abs(gPlaybackSpeed) > 0.0001)
     {
         glutTimerFunc(gDisplayAnimTime, Animate, 0);
     }
 }
References Animate(), gCore, gDisplayAnimTime, and gPlaybackSpeed.
Referenced by Keyboard().
Draw()
void Draw (void)
Definition at line 142 of file Main.cpp.
 {
     UpdateFrameBuffer();
     gCore->Draw();
     glutSwapBuffers();
     gReshaping = false;
 }
References gCore, gReshaping, and UpdateFrameBuffer().
Referenced by SetupDraw().
DrawMainLoop()
void DrawMainLoop ()
Definition at line 359 of file Main.cpp.
 {
     InitTime();
     glutMainLoop();
 }
References InitTime().
Referenced by main().
FormatArgs()
void FormatArgs (int argc, char ** argv, std::vector< std::string > & out_args)
Definition at line 77 of file Main.cpp.
 {
     out_args.resize(argc);
     for (int i = 0; i < argc; ++i)
     {
         out_args[i] = std::string(argv[i]);
     }
 }
Referenced by main().
GetCurrTime()
int GetCurrTime ()
Definition at line 204 of file Main.cpp.
 {
     return glutGet(GLUT_ELAPSED_TIME);
 }
Referenced by Animate(), and InitTime().
GetNumTimeSteps()
int GetNumTimeSteps ()
Definition at line 180 of file Main.cpp.
 {
     int num_steps = static_cast<int>(gPlaybackSpeed);
     if (num_steps == 0)
     {
         num_steps = 1;
     }
     num_steps = std::abs(num_steps);
     return num_steps;
 }
References gPlaybackSpeed.
Referenced by Animate().
InitDraw()
void InitDraw (int argc, char ** argv)
Definition at line 332 of file Main.cpp.
 {
     glutInit(&argc, argv);
     glutInitContextVersion(3, 2);
     glutInitContextFlags(GLUT_FORWARD_COMPATIBLE);
     glutInitContextProfile(GLUT_CORE_PROFILE);
     glutInitDisplayMode(GLUT_RGBA | GLUT_DOUBLE | GLUT_DEPTH);
     glutInitWindowSize(gWinWidth, gWinHeight);
     glutCreateWindow("DeepMimic");
 }
References gWinHeight, and gWinWidth.
Referenced by main().
InitFrameBuffers()
void InitFrameBuffers (void)
Definition at line 327 of file Main.cpp.
 {
     gDefaultFrameBuffer = std::unique_ptr<cTextureDesc>(new cTextureDesc(0, 0, 0, gWinWidth, gWinHeight, 1, GL_RGBA, GL_RGBA));
 }
References gDefaultFrameBuffer, gWinHeight, and gWinWidth.
Referenced by SetupDraw().
InitTime()
void InitTime ()
Definition at line 209 of file Main.cpp.
 {
     gPrevTime = GetCurrTime();
     gUpdatesPerSec = 0;
 }
References GetCurrTime(), gPrevTime, and gUpdatesPerSec.
Referenced by DrawMainLoop().
Keyboard()
void Keyboard (unsigned char key, int x, int y)
Definition at line 276 of file Main.cpp.
 {
     gCore->Keyboard(key, x, y);
     switch (key) {
     case 27: // escape
         Shutdown();
         break;
     case ' ':
         ToggleAnimate();
         break;
     case '>':
         StepAnim(gAnimStep);
         break;
     case '<':
         StepAnim(-gAnimStep);
         break;
     case ',':
         ChangePlaybackSpeed(-gPlaybackDelta);
         break;
     case '.':
         ChangePlaybackSpeed(gPlaybackDelta);
         break;
     case '/':
         ChangePlaybackSpeed(-gPlaybackSpeed + 1);
         break;
     case 'l':
         Reload();
         break;
     case 'r':
         Reset();
         break;
     default:
         break;
     }
     glutPostRedisplay();
 }
References ChangePlaybackSpeed(), gAnimStep, gCore, gPlaybackDelta, gPlaybackSpeed, Reload(), Reset(), Shutdown(), StepAnim(), and ToggleAnimate().
Referenced by SetupDraw().
main()
int main (int argc, char ** argv)
Definition at line 365 of file Main.cpp.
 {
     FormatArgs(argc, argv, gArgs);
     InitDraw(argc, argv);
     SetupDeepMimicCore();
     SetupDraw();
     DrawMainLoop();
     return EXIT_SUCCESS;
 }
References DrawMainLoop(), FormatArgs(), gArgs, InitDraw(), SetupDeepMimicCore(), and SetupDraw().
MouseClick()
void MouseClick (int button, int state, int x, int y)
Definition at line 315 of file Main.cpp.
 {
     gCore->MouseClick(button, state, x, y);
     glutPostRedisplay();
 }
References gCore.
Referenced by SetupDraw().
MouseMove()
void MouseMove (int x, int y)
Definition at line 321 of file Main.cpp.
 {
     gCore->MouseMove(x, y);
     glutPostRedisplay();
 }
References gCore.
Referenced by SetupDraw().
Reload()
void Reload ()
Definition at line 170 of file Main.cpp.
 {
     SetupDeepMimicCore();
 }
References SetupDeepMimicCore().
Referenced by Keyboard().
Reset()
void Reset ()
Definition at line 175 of file Main.cpp.
 {
     gCore->Reset();
 }
References gCore.
Referenced by Keyboard().
Reshape()
void Reshape (int w, int h)
Definition at line 151 of file Main.cpp.
 {
     gReshaping = true;
     gWinWidth = w;
     gWinHeight = h;
     gDefaultFrameBuffer->Reshape(w, h);
     glViewport(0, 0, gWinWidth, gWinHeight);
     glutPostRedisplay();
 }
References gDefaultFrameBuffer, gReshaping, gWinHeight, and gWinWidth.
Referenced by SetupDraw().
SetupDeepMimicCore()
void SetupDeepMimicCore ()
Definition at line 38 of file Main.cpp.
 {
     bool enable_draw = true;
     gCore = std::unique_ptr<cDeepMimicCore>(new cDeepMimicCore(enable_draw));
     gCore->ParseArgs(gArgs);
     gCore->Init();
     int num_agents = gCore->GetNumAgents();
     for (int id = 0; id < num_agents; ++id)
     {
         int action_space = gCore->GetActionSpace(id);
         int state_size = gCore->GetStateSize(id);
         int goal_size = gCore->GetGoalSize(id);
         int action_size = gCore->GetActionSize(id);
         int num_actions = gCore->GetNumActions(id);
         auto s_offset = gCore->BuildStateOffset(id);
         auto s_scale = gCore->BuildStateScale(id);
         auto g_offset = gCore->BuildGoalOffset(id);
         auto g_scale = gCore->BuildGoalScale(id);
         auto a_offset = gCore->BuildActionOffset(id);
         auto a_scale = gCore->BuildActionScale(id);
         auto action_min = gCore->BuildActionBoundMin(id);
         auto action_max = gCore->BuildActionBoundMax(id);
         auto state_norm_groups = gCore->BuildStateNormGroups(id);
         auto goal_norm_groups = gCore->BuildGoalNormGroups(id);
         double reward_min = gCore->GetRewardMin(id);
         double reward_max = gCore->GetRewardMax(id);
         double reward_fail = gCore->GetRewardFail(id);
         double reward_succ = gCore->GetRewardSucc(id);
         int xx = 0;
         ++xx;
     }
 }
References gArgs, and gCore.
Referenced by main(), and Reload().
SetupDraw()
void SetupDraw ()
Definition at line 345 of file Main.cpp.
 {
     glutDisplayFunc(Draw);
     glutReshapeFunc(Reshape);
     glutKeyboardFunc(Keyboard);
     glutMouseFunc(MouseClick);
     glutMotionFunc(MouseMove);
     glutTimerFunc(gDisplayAnimTime, Animate, 0);
     InitFrameBuffers();
     Reshape(gWinWidth, gWinHeight);
     gCore->Reshape(gWinWidth, gWinHeight);
 }
References Animate(), Draw(), gCore, gDisplayAnimTime, gWinHeight, gWinWidth, InitFrameBuffers(), Keyboard(), MouseClick(), MouseMove(), and Reshape().
Referenced by main().
Shutdown()
void Shutdown ()
Definition at line 198 of file Main.cpp.
 {
     gCore->Shutdown();
     exit(0);
 }
References gCore.
Referenced by Animate(), and Keyboard().
StepAnim()
void StepAnim (double time_step)
Definition at line 163 of file Main.cpp.
 {
     Update(time_step);
     gAnimating = false;
     glutPostRedisplay();
 }
References gAnimating, and Update().
Referenced by Keyboard().
ToggleAnimate()
void ToggleAnimate ()
Definition at line 255 of file Main.cpp.
 {
     gAnimating = !gAnimating;
     if (gAnimating)
     {
         glutTimerFunc(gDisplayAnimTime, Animate, 0);
     }
 }
References Animate(), gAnimating, and gDisplayAnimTime.
Referenced by Keyboard().
Update()
void Update (double time_elapsed)
Definition at line 97 of file Main.cpp.
 {
     int num_substeps = gCore->GetNumUpdateSubsteps();
     double timestep = time_elapsed / num_substeps;
     num_substeps = (time_elapsed == 0) ? 1 : num_substeps;
     for (int i = 0; i < num_substeps; ++i)
     {
         for (int id = 0; id < gCore->GetNumAgents(); ++id)
         {
             if (gCore->NeedNewAction(id))
             {
                 auto s = gCore->RecordState(id);
                 auto g = gCore->RecordGoal(id);
                 double r = gCore->CalcReward(id);
                 ++gSampleCount;
                 std::vector<double> action = std::vector<double>(gCore->GetActionSize(id), 0);
                 gCore->SetAction(id, action);
             }
         }
         gCore->Update(timestep);
         if (gCore->IsRLScene())
         {
             bool end_episode = gCore->IsEpisodeEnd();
             bool valid_episode = gCore->CheckValidEpisode();
             if (end_episode || !valid_episode)
             {
                 for (int id = 0; id < gCore->GetNumAgents(); ++id)
                 {
                     int terminated = gCore->CheckTerminate(id);
                     if (terminated)
                     {
                         printf("Agent %i terminated\n", id);
                     }
                 }
                 gCore->SetSampleCount(gSampleCount);
                 gCore->Reset();
             }
         }
     }
 }
References gCore, and gSampleCount.
Referenced by Animate(), and StepAnim().
UpdateFrameBuffer()
void UpdateFrameBuffer ()
Definition at line 86 of file Main.cpp.
 {
     if (!gReshaping)
     {
         if (gWinWidth != gCore->GetWinWidth() || gWinHeight != gCore->GetWinHeight())
         {
             gCore->Reshape(gWinWidth, gWinHeight);
         }
     }
 }
References gCore, gReshaping, gWinHeight, and gWinWidth.
Referenced by Draw().
Variable Documentation
gAnimating
bool gAnimating = true
Definition at line 24 of file Main.cpp.
Referenced by Animate(), StepAnim(), and ToggleAnimate().
gAnimStep
const double gAnimStep = 1.0 / gFPS
Definition at line 22 of file Main.cpp.
Referenced by Animate(), and Keyboard().
gArgs
std::vector<std::string> gArgs
Definition at line 35 of file Main.cpp.
Referenced by main(), and SetupDeepMimicCore().
gCore
std::unique_ptr<cDeepMimicCore> gCore
Definition at line 36 of file Main.cpp.
Referenced by Animate(), ChangePlaybackSpeed(), Draw(), Keyboard(), MouseClick(), MouseMove(), Reset(), SetupDeepMimicCore(), SetupDraw(), Shutdown(), Update(), and UpdateFrameBuffer().
gDefaultFrameBuffer
std::unique_ptr<cTextureDesc> gDefaultFrameBuffer
Definition at line 18 of file Main.cpp.
Referenced by InitFrameBuffers(), and Reshape().
gDisplayAnimTime
const int gDisplayAnimTime = static_cast<int>(1000 * gAnimStep)
Definition at line 23 of file Main.cpp.
Referenced by CalcDisplayAnimTime(), ChangePlaybackSpeed(), SetupDraw(), and ToggleAnimate().
gFPS
const double gFPS = 60.0
Definition at line 21 of file Main.cpp.
gPlaybackDelta
const double gPlaybackDelta = 0.05
Definition at line 29 of file Main.cpp.
Referenced by Keyboard().
gPlaybackSpeed
double gPlaybackSpeed = 1
Definition at line 28 of file Main.cpp.
Referenced by Animate(), CalcDisplayAnimTime(), ChangePlaybackSpeed(), GetNumTimeSteps(), and Keyboard().
gPrevTime
int gPrevTime = 0
Definition at line 32 of file Main.cpp.
Referenced by Animate(), and InitTime().
gReshaping
bool gReshaping = false
Definition at line 15 of file Main.cpp.
Referenced by Draw(), Reshape(), and UpdateFrameBuffer().
gSampleCount
int gSampleCount = 0
Definition at line 26 of file Main.cpp.
Referenced by Update().
gUpdatesPerSec
double gUpdatesPerSec = 0
Definition at line 33 of file Main.cpp.
Referenced by Animate(), and InitTime().
gWinHeight
int gWinHeight = static_cast<int>(gWinWidth * 9.0 / 16.0)
Definition at line 12 of file Main.cpp.
Referenced by InitDraw(), InitFrameBuffers(), Reshape(), SetupDraw(), and UpdateFrameBuffer().
gWinWidth
int gWinWidth = 800
Definition at line 11 of file Main.cpp.
Referenced by InitDraw(), InitFrameBuffers(), Reshape(), SetupDraw(), and UpdateFrameBuffer().