My Project: cCtPDController Class Reference
cCtPDController Class Reference
#include <CtPDController.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cCtPDController ()
virtual ~cCtPDController ()
virtual void Reset ()
virtual void Clear ()
virtual void SetGravity (const tVector &gravity)
virtual std::string GetName () const
Public Member Functions inherited from cCtController
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cCtController ()
virtual ~cCtController ()
virtual void SetUpdateRate (double rate)
virtual double GetUpdateRate () const
virtual void UpdateCalcTau (double timestep, Eigen::VectorXd &out_tau)
virtual double GetCyclePeriod () const
virtual void SetCyclePeriod (double period)
virtual void SetInitTime (double time)
virtual double GetPhase () const
virtual int GetStateSize () const
virtual int GetActionSize () const
virtual void BuildStateOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionBounds (Eigen::VectorXd &out_min, Eigen::VectorXd &out_max) const
virtual void BuildActionOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildStateNormGroups (Eigen::VectorXi &out_groups) const
virtual void RecordState (Eigen::VectorXd &out_state)
Public Member Functions inherited from cDeepMimicCharController
virtual EIGEN_MAKE_ALIGNED_OPERATOR_NEW ~cDeepMimicCharController ()
virtual void Init (cSimCharacter *character, const std::string &param_file)
virtual void Update (double timestep)
virtual void PostUpdate (double timestep)
virtual void UpdateApplyTau (const Eigen::VectorXd &tau)
virtual bool NeedNewAction () const
virtual void RecordGoal (Eigen::VectorXd &out_goal) const
virtual void RecordAction (Eigen::VectorXd &out_action) const
virtual eActionSpace GetActionSpace () const
virtual double GetRewardMin () const
virtual double GetRewardMax () const
virtual void SetViewDistMin (double dist)
virtual void SetViewDistMax (double dist)
virtual double GetViewDistMin () const
virtual double GetViewDistMax () const
virtual void GetViewBound (tVector &out_min, tVector &out_max) const
virtual double GetPrevActionTime () const
virtual const tVector & GetPrevActionCOM () const
virtual double GetTime () const
virtual const Eigen::VectorXd & GetTau () const
virtual const cCircularBuffer< double > & GetValLog () const
virtual void LogVal (double val)
Public Member Functions inherited from cCharController
virtual ~cCharController ()
virtual int GetGoalSize () const
virtual int GetNumActions () const
virtual void HandlePoseReset ()
virtual void HandleVelReset ()
virtual void BuildGoalOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildGoalNormGroups (Eigen::VectorXi &out_groups) const
virtual int NumChildren () const
virtual const std::shared_ptr< cCharController > & GetChild (int i) const
Public Member Functions inherited from cController
virtual ~cController ()
virtual void Init (cSimCharacter *character)
virtual bool IsValid () const
virtual bool LoadParams (const std::string &param_file)
virtual int GetNumOptParams () const
virtual void BuildOptParams (Eigen::VectorXd &out_params) const
virtual void SetOptParams (const Eigen::VectorXd &params)
virtual void SetOptParams (const Eigen::VectorXd &params, Eigen::VectorXd &out_params) const
virtual void FetchOptParamScale (Eigen::VectorXd &out_scale) const
virtual void OutputOptParams (const std::string &file, const Eigen::VectorXd &params) const
virtual void OutputOptParams (FILE *f, const Eigen::VectorXd &params) const
virtual void SetActive (bool active)
virtual bool IsActive () const
virtual void SetMode (eMode mode)
virtual const cSimCharacter * GetChar () const
Protected Member Functions
virtual bool ParseParams (const Json::Value &json)
virtual void UpdateBuildTau (double time_step, Eigen::VectorXd &out_tau)
virtual void SetupPDControllers (const Json::Value &json, const tVector &gravity)
virtual void UpdatePDCtrls (double time_step, Eigen::VectorXd &out_tau)
virtual void ApplyAction (const Eigen::VectorXd &action)
virtual void BuildJointActionBounds (int joint_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max) const
virtual void BuildJointActionOffsetScale (int joint_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void ConvertActionToTargetPose (int joint_id, Eigen::VectorXd &out_theta) const
virtual cKinTree::eJointType GetJointType (int joint_id) const
virtual void SetPDTargets (const Eigen::VectorXd &targets)
Protected Member Functions inherited from cCtController
virtual void ResetParams ()
virtual int GetPosFeatureDim () const
virtual int GetRotFeatureDim () const
virtual bool CheckNeedNewAction (double timestep) const
virtual void NewActionUpdate ()
virtual int GetStatePoseSize () const
virtual int GetStateVelSize () const
virtual int GetStatePoseOffset () const
virtual int GetStatePhaseSize () const
virtual int GetStatePhaseOffset () const
virtual int GetActionPhaseOffset () const
virtual int GetActionPhaseSize () const
virtual int GetActionCtrlOffset () const
virtual int GetActionCtrlSize () const
virtual void BuildStatePhaseOffsetScale (Eigen::VectorXd &phase_offset, Eigen::VectorXd &phase_scale) const
virtual void BuildStatePose (Eigen::VectorXd &out_pose) const
virtual void BuildStateVel (Eigen::VectorXd &out_vel) const
virtual void BuildStatePhase (Eigen::VectorXd &out_phase) const
virtual bool FlipStance () const
virtual int RetargetJointID (int joint_id) const
virtual double GetPhaseRate () const
Protected Member Functions inherited from cDeepMimicCharController
cDeepMimicCharController ()
virtual void InitResources ()
virtual void InitAction ()
virtual void InitTau ()
virtual int GetPosDim () const
virtual void HandleNewAction ()
virtual void PostProcessAction (Eigen::VectorXd &out_action) const
virtual int GetStateVelOffset () const
Protected Member Functions inherited from cCharController
cCharController ()
Protected Member Functions inherited from cController
cController ()
Protected Attributes
cImpPDController mPDCtrl
tVector mGravity
Protected Attributes inherited from cCtController
double mUpdateRate
double mCyclePeriod
bool mEnablePhaseInput
bool mEnablePhaseAction
bool mRecordWorldRootPos
bool mRecordWorldRootRot
double mPhaseOffset
double mInitTimeOffset
Eigen::VectorXd mActionBoundMin
Eigen::VectorXd mActionBoundMax
Protected Attributes inherited from cDeepMimicCharController
double mTime
bool mNeedNewAction
Eigen::VectorXd mAction
Eigen::VectorXd mTau
double mViewDistMin
double mViewDistMax
int mPosDim
double mPrevActionTime
tVector mPrevActionCOM
cCircularBuffer< double > mValLog
Protected Attributes inherited from cController
cSimCharacter * mChar
eMode mMode
bool mValid
Additional Inherited Members
Public Types inherited from cController
enum eMode { eModeActive, eModeInactive, eModePassive, eModeMax }
Static Public Attributes inherited from cCharController
const static int gNormGroupSingle = 0
const static int gNormGroupNone = -1
Detailed Description
Definition at line 6 of file CtPDController.h.
Constructor & Destructor Documentation
cCtPDController()
cCtPDController::cCtPDController ()
Definition at line 6 of file CtPDController.cpp.
                                  : cCtController()
 {
     mGravity = gGravity;
 }
References gGravity, and mGravity.
~cCtPDController()
cCtPDController::~cCtPDController () virtual
Definition at line 11 of file CtPDController.cpp.
 {
 }
Member Function Documentation
ApplyAction()
void cCtPDController::ApplyAction (const Eigen::VectorXd & action) protected virtual
Reimplemented from cDeepMimicCharController.
Reimplemented in cCtVelController.
Definition at line 78 of file CtPDController.cpp.
 {
     cCtController::ApplyAction(action);
     SetPDTargets(action);
 }
References cDeepMimicCharController::ApplyAction(), and SetPDTargets().
BuildJointActionBounds()
void cCtPDController::BuildJointActionBounds (int joint_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) const protected virtual
Reimplemented from cCtController.
Reimplemented in cCtVelController.
Definition at line 84 of file CtPDController.cpp.
 {
     const Eigen::MatrixXd& joint_mat = mChar->GetJointMat();
     cCtCtrlUtil::BuildBoundsPD(joint_mat, joint_id, out_min, out_max);
 }
References cCtCtrlUtil::BuildBoundsPD(), cCharacter::GetJointMat(), and cController::mChar.
BuildJointActionOffsetScale()
void cCtPDController::BuildJointActionOffsetScale (int joint_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const protected virtual
Reimplemented from cCtController.
Reimplemented in cCtVelController.
Definition at line 90 of file CtPDController.cpp.
 {
     const Eigen::MatrixXd& joint_mat = mChar->GetJointMat();
     cCtCtrlUtil::BuildOffsetScalePD(joint_mat, joint_id, out_offset, out_scale);
 }
References cCtCtrlUtil::BuildOffsetScalePD(), cCharacter::GetJointMat(), and cController::mChar.
Clear()
void cCtPDController::Clear () virtual
Reimplemented from cDeepMimicCharController.
Definition at line 21 of file CtPDController.cpp.
 {
     cCtController::Clear();
     mPDCtrl.Clear();
 }
References cDeepMimicCharController::Clear(), cImpPDController::Clear(), and mPDCtrl.
ConvertActionToTargetPose()
void cCtPDController::ConvertActionToTargetPose (int joint_id, Eigen::VectorXd & out_theta) const protected virtual
Definition at line 96 of file CtPDController.cpp.
 {
 #if defined(ENABLE_PD_SPHERE_AXIS)
     cKinTree::eJointType joint_type = GetJointType(joint_id);
     if (joint_type == cKinTree::eJointTypeSpherical)
     {
         double rot_theta = out_theta[0];
         tVector axis = tVector(out_theta[1], out_theta[2], out_theta[3], 0);
         if (axis.squaredNorm() == 0)
         {
             axis[2] = 1;
         }
         axis.normalize();
         tQuaternion quat = cMathUtil::AxisAngleToQuaternion(axis, rot_theta);
         if (FlipStance())
         {
             cKinTree::eJointType joint_type = GetJointType(joint_id);
             if (joint_type == cKinTree::eJointTypeSpherical)
             {
                 quat = cMathUtil::MirrorQuaternion(quat, cMathUtil::eAxisZ);
             }
         }
         out_theta = cMathUtil::QuatToVec(quat);
     }
 #endif
 }
References cMathUtil::AxisAngleToQuaternion(), cMathUtil::eAxisZ, cKinTree::eJointTypeSpherical, cCtController::FlipStance(), GetJointType(), cMathUtil::MirrorQuaternion(), and cMathUtil::QuatToVec().
Referenced by SetPDTargets().
GetJointType()
cKinTree::eJointType cCtPDController::GetJointType (int joint_id) const protected virtual
Definition at line 125 of file CtPDController.cpp.
 {
     const cPDController& ctrl = mPDCtrl.GetPDCtrl(joint_id);
     const cSimBodyJoint& joint = ctrl.GetJoint();
     cKinTree::eJointType joint_type = joint.GetType();
     return joint_type;
 }
References cPDController::GetJoint(), cExpPDController::GetPDCtrl(), cSimBodyJoint::GetType(), and mPDCtrl.
Referenced by ConvertActionToTargetPose().
GetName()
std::string cCtPDController::GetName () const virtual
Reimplemented from cCtController.
Reimplemented in cCtVelController.
Definition at line 32 of file CtPDController.cpp.
 {
     return "ct_pd";
 }
ParseParams()
bool cCtPDController::ParseParams (const Json::Value & json) protected virtual
Reimplemented from cCtController.
Definition at line 59 of file CtPDController.cpp.
 {
     bool succ = cCtController::ParseParams(json);
     SetupPDControllers(json, mGravity);
     return succ;
 }
References mGravity, cCtController::ParseParams(), and SetupPDControllers().
Reset()
void cCtPDController::Reset () virtual
Reimplemented from cDeepMimicCharController.
Definition at line 15 of file CtPDController.cpp.
 {
     cCtController::Reset();
     mPDCtrl.Reset();
 }
References mPDCtrl, cDeepMimicCharController::Reset(), and cExpPDController::Reset().
SetGravity()
void cCtPDController::SetGravity (const tVector & gravity) virtual
Definition at line 27 of file CtPDController.cpp.
 {
     mGravity = gravity;
 }
References mGravity.
SetPDTargets()
void cCtPDController::SetPDTargets (const Eigen::VectorXd & targets) protected virtual
Definition at line 133 of file CtPDController.cpp.
 {
     int root_id = mChar->GetRootID();
     int root_size = mChar->GetParamSize(root_id);
     int num_joints = mChar->GetNumJoints();
     int ctrl_offset = GetActionCtrlOffset();
     for (int j = root_id + 1; j < num_joints; ++j)
     {
         if (mPDCtrl.IsValidPDCtrl(j))
         {
             int retarget_joint = RetargetJointID(j);
             int param_offset = mChar->GetParamOffset(retarget_joint);
             int param_size = mChar->GetParamSize(retarget_joint);
             param_offset -= root_size;
             param_offset += ctrl_offset;
             Eigen::VectorXd theta = targets.segment(param_offset, param_size);
             ConvertActionToTargetPose(j, theta);
             mPDCtrl.SetTargetTheta(j, theta);
         }
     }
 }
References ConvertActionToTargetPose(), cCtController::GetActionCtrlOffset(), cCharacter::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), cCharacter::GetRootID(), cExpPDController::IsValidPDCtrl(), cController::mChar, mPDCtrl, cCtController::RetargetJointID(), and cExpPDController::SetTargetTheta().
Referenced by ApplyAction().
SetupPDControllers()
void cCtPDController::SetupPDControllers (const Json::Value & json, const tVector & gravity) protected virtual
Reimplemented in cCtVelController.
Definition at line 37 of file CtPDController.cpp.
 {
     Eigen::MatrixXd pd_params;
     bool succ = false;
     if (!json[gPDControllersKey].isNull())
     {
         succ = cPDController::LoadParams(json[gPDControllersKey], pd_params);
     }
     if (succ)
     {
         mPDCtrl.Init(mChar, pd_params, gravity);
     }
     mValid = succ;
     if (!mValid)
     {
         printf("Failed to initialize Ct-PD controller\n");
         mValid = false;
     }
 }
References gPDControllersKey, cImpPDController::Init(), cPDController::LoadParams(), cController::mChar, mPDCtrl, and cController::mValid.
Referenced by ParseParams(), and cCtVelController::SetupPDControllers().
UpdateBuildTau()
void cCtPDController::UpdateBuildTau (double time_step, Eigen::VectorXd & out_tau) protected virtual
Reimplemented from cCtController.
Definition at line 66 of file CtPDController.cpp.
 {
     UpdatePDCtrls(time_step, out_tau);
 }
References UpdatePDCtrls().
UpdatePDCtrls()
void cCtPDController::UpdatePDCtrls (double time_step, Eigen::VectorXd & out_tau) protected virtual
Definition at line 71 of file CtPDController.cpp.
 {
     int num_dof = mChar->GetNumDof();
     out_tau = Eigen::VectorXd::Zero(num_dof);
     mPDCtrl.UpdateControlForce(time_step, out_tau);
 }
References cCharacter::GetNumDof(), cController::mChar, mPDCtrl, and cImpPDController::UpdateControlForce().
Referenced by UpdateBuildTau().
Member Data Documentation
mGravity
tVector cCtPDController::mGravity protected
Definition at line 24 of file CtPDController.h.
Referenced by cCtPDController(), ParseParams(), and SetGravity().
mPDCtrl
cImpPDController cCtPDController::mPDCtrl protected
Definition at line 22 of file CtPDController.h.
Referenced by cCtVelController::ApplyAction(), Clear(), GetJointType(), Reset(), SetPDTargets(), cCtVelController::SetupPDControllers(), SetupPDControllers(), and UpdatePDCtrls().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/CtPDController.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/CtPDController.cpp