My Project: cDrawObj Class Reference
cDrawObj Class Reference
#include <DrawObj.h>
Static Public Member Functions
static void Draw (const cSimObj *obj, cDrawUtil::eDrawMode draw_mode=cDrawUtil::eDrawSolid)
static void DrawBox (const cSimObj *box, cDrawUtil::eDrawMode draw_mode=cDrawUtil::eDrawSolid)
static void DrawBox (const cSimObj *box, const tVector &tex_coord_min, const tVector &tex_coord_max, cDrawUtil::eDrawMode draw_mode=cDrawUtil::eDrawSolid)
static void DrawPlane (const cSimObj *plane, double size, cDrawUtil::eDrawMode draw_mode=cDrawUtil::eDrawSolid)
static void DrawCapsule (const cSimObj *cap, cDrawUtil::eDrawMode draw_mode=cDrawUtil::eDrawSolid)
static void DrawSphere (const cSimObj *box, cDrawUtil::eDrawMode draw_mode=cDrawUtil::eDrawSolid)
static void DrawCylinder (const cSimObj *cylinder, cDrawUtil::eDrawMode draw_mode=cDrawUtil::eDrawSolid)
Detailed Description
Definition at line 7 of file DrawObj.h.
Member Function Documentation
Draw()
void cDrawObj::Draw (const cSimObj * obj, cDrawUtil::eDrawMode draw_mode = cDrawUtil::eDrawSolid) static
Definition at line 3 of file DrawObj.cpp.
 {
     cShape::eShape shape = obj->GetShape();
     switch (shape)
     {
     case cShape::eShapeBox:
         DrawBox(obj, draw_mode);
         break;
     case cShape::eShapePlane:
         DrawPlane(obj, draw_mode);
         break;
     case cShape::eShapeCapsule:
         DrawCapsule(obj, draw_mode);
         break;
     case cShape::eShapeSphere:
         DrawSphere(obj, draw_mode);
         break;
     case cShape::eShapeCylinder:
         DrawCylinder(obj, draw_mode);
         break;
     default:
         assert(false); // unsupported shape
         break;
     }
 }
References DrawBox(), DrawCapsule(), DrawCylinder(), DrawPlane(), DrawSphere(), cShape::eShapeBox, cShape::eShapeCapsule, cShape::eShapeCylinder, cShape::eShapePlane, cShape::eShapeSphere, and cSimObj::GetShape().
Referenced by cDrawSceneSimChar::DrawObjs(), and cDrawSimCharacter::DrawSimBody().
DrawBox() [1/2]
void cDrawObj::DrawBox (const cSimObj * box, cDrawUtil::eDrawMode draw_mode = cDrawUtil::eDrawSolid) static
Definition at line 29 of file DrawObj.cpp.
 {
     DrawBox(box, tVector::Zero(), tVector::Ones(), draw_mode);
 }
Referenced by Draw().
DrawBox() [2/2]
void cDrawObj::DrawBox (const cSimObj * box, const tVector & tex_coord_min, const tVector & tex_coord_max, cDrawUtil::eDrawMode draw_mode = cDrawUtil::eDrawSolid) static
Definition at line 34 of file DrawObj.cpp.
 {
     assert(box->GetShape() == cShape::eShapeBox);
     tVector pos = box->GetPos();
     tVector size = box->GetSize();
     tVector axis;
     double theta;
     box->GetRotation(axis, theta);
     cDrawUtil::PushMatrixView();
     cDrawUtil::Translate(pos);
     cDrawUtil::Rotate(theta, axis);
     cDrawUtil::DrawBox(tVector::Zero(), size, tex_coord_min, tex_coord_max, draw_mode);
     cDrawUtil::PopMatrixView();
 }
References cDrawUtil::DrawBox(), cShape::eShapeBox, cSimObj::GetPos(), cSimObj::GetRotation(), cSimObj::GetShape(), cSimObj::GetSize(), cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixView(), cDrawUtil::Rotate(), and cDrawUtil::Translate().
DrawCapsule()
void cDrawObj::DrawCapsule (const cSimObj * cap, cDrawUtil::eDrawMode draw_mode = cDrawUtil::eDrawSolid) static
Definition at line 59 of file DrawObj.cpp.
 {
     assert(cap->GetShape() == cShape::eShapeCapsule);
     tVector pos = cap->GetPos();
     tVector size = cap->GetSize();
     double r = 0.5 * size[0];
     double h = size[1] - 2 * r;
     tVector axis;
     double theta;
     cap->GetRotation(axis, theta);
     cDrawUtil::PushMatrixView();
     cDrawUtil::Translate(pos);
     cDrawUtil::Rotate(theta, axis);
     cDrawUtil::DrawCapsule(r, h, draw_mode);
     cDrawUtil::PopMatrixView();
 }
References cDrawUtil::DrawCapsule(), cShape::eShapeCapsule, cSimObj::GetPos(), cSimObj::GetRotation(), cSimObj::GetShape(), cSimObj::GetSize(), cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixView(), cDrawUtil::Rotate(), and cDrawUtil::Translate().
Referenced by Draw().
DrawCylinder()
void cDrawObj::DrawCylinder (const cSimObj * cylinder, cDrawUtil::eDrawMode draw_mode = cDrawUtil::eDrawSolid) static
Definition at line 96 of file DrawObj.cpp.
 {
     assert(cap->GetShape() == cShape::eShapeCylinder);
     tVector pos = cap->GetPos();
     tVector size = cap->GetSize();
     double r = 0.5 * size[0];
     double h = size[1];
     tVector axis;
     double theta;
     cap->GetRotation(axis, theta);
     cDrawUtil::PushMatrixView();
     cDrawUtil::Translate(pos);
     cDrawUtil::Rotate(theta, axis);
     cDrawUtil::DrawCylinder(r, h, draw_mode);
     cDrawUtil::PopMatrixView();
 }
References cDrawUtil::DrawCylinder(), cShape::eShapeCylinder, cSimObj::GetPos(), cSimObj::GetRotation(), cSimObj::GetShape(), cSimObj::GetSize(), cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixView(), cDrawUtil::Rotate(), and cDrawUtil::Translate().
Referenced by Draw().
DrawPlane()
void cDrawObj::DrawPlane (const cSimObj * plane, double size, cDrawUtil::eDrawMode draw_mode = cDrawUtil::eDrawSolid) static
Definition at line 52 of file DrawObj.cpp.
 {
     assert(plane->GetShape() == cShape::eShapePlane);
     tVector coeffs = plane->GetSize();
     cDrawUtil::DrawPlane(coeffs, size, draw_mode);
 }
References cDrawUtil::DrawPlane(), cShape::eShapePlane, cSimObj::GetShape(), and cSimObj::GetSize().
Referenced by Draw().
DrawSphere()
void cDrawObj::DrawSphere (const cSimObj * box, cDrawUtil::eDrawMode draw_mode = cDrawUtil::eDrawSolid) static
Definition at line 79 of file DrawObj.cpp.
 {
     assert(ball->GetShape() == cShape::eShapeSphere);
     tVector pos = ball->GetPos();
     tVector size = ball->GetSize();
     tVector axis;
     double theta;
     ball->GetRotation(axis, theta);
     double r = 0.5 * size[0];
     cDrawUtil::PushMatrixView();
     cDrawUtil::Translate(pos);
     cDrawUtil::Rotate(theta, axis);
     cDrawUtil::DrawSphere(r, draw_mode);
     cDrawUtil::PopMatrixView();
 }
References cDrawUtil::DrawSphere(), cShape::eShapeSphere, cSimObj::GetPos(), cSimObj::GetRotation(), cSimObj::GetShape(), cSimObj::GetSize(), cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixView(), cDrawUtil::Rotate(), and cDrawUtil::Translate().
Referenced by Draw().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/DrawObj.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/DrawObj.cpp