My Project: cCtVelController Class Reference
cCtVelController Class Reference
#include <CtVelController.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cCtVelController ()
virtual ~cCtVelController ()
virtual std::string GetName () const
Public Member Functions inherited from cCtPDController
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cCtPDController ()
virtual ~cCtPDController ()
virtual void Reset ()
virtual void Clear ()
virtual void SetGravity (const tVector &gravity)
Public Member Functions inherited from cCtController
EIGEN_MAKE_ALIGNED_OPERATOR_NEW cCtController ()
virtual ~cCtController ()
virtual void SetUpdateRate (double rate)
virtual double GetUpdateRate () const
virtual void UpdateCalcTau (double timestep, Eigen::VectorXd &out_tau)
virtual double GetCyclePeriod () const
virtual void SetCyclePeriod (double period)
virtual void SetInitTime (double time)
virtual double GetPhase () const
virtual int GetStateSize () const
virtual int GetActionSize () const
virtual void BuildStateOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildActionBounds (Eigen::VectorXd &out_min, Eigen::VectorXd &out_max) const
virtual void BuildActionOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildStateNormGroups (Eigen::VectorXi &out_groups) const
virtual void RecordState (Eigen::VectorXd &out_state)
Public Member Functions inherited from cDeepMimicCharController
virtual EIGEN_MAKE_ALIGNED_OPERATOR_NEW ~cDeepMimicCharController ()
virtual void Init (cSimCharacter *character, const std::string &param_file)
virtual void Update (double timestep)
virtual void PostUpdate (double timestep)
virtual void UpdateApplyTau (const Eigen::VectorXd &tau)
virtual bool NeedNewAction () const
virtual void RecordGoal (Eigen::VectorXd &out_goal) const
virtual void RecordAction (Eigen::VectorXd &out_action) const
virtual eActionSpace GetActionSpace () const
virtual double GetRewardMin () const
virtual double GetRewardMax () const
virtual void SetViewDistMin (double dist)
virtual void SetViewDistMax (double dist)
virtual double GetViewDistMin () const
virtual double GetViewDistMax () const
virtual void GetViewBound (tVector &out_min, tVector &out_max) const
virtual double GetPrevActionTime () const
virtual const tVector & GetPrevActionCOM () const
virtual double GetTime () const
virtual const Eigen::VectorXd & GetTau () const
virtual const cCircularBuffer< double > & GetValLog () const
virtual void LogVal (double val)
Public Member Functions inherited from cCharController
virtual ~cCharController ()
virtual int GetGoalSize () const
virtual int GetNumActions () const
virtual void HandlePoseReset ()
virtual void HandleVelReset ()
virtual void BuildGoalOffsetScale (Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
virtual void BuildGoalNormGroups (Eigen::VectorXi &out_groups) const
virtual int NumChildren () const
virtual const std::shared_ptr< cCharController > & GetChild (int i) const
Public Member Functions inherited from cController
virtual ~cController ()
virtual void Init (cSimCharacter *character)
virtual bool IsValid () const
virtual bool LoadParams (const std::string &param_file)
virtual int GetNumOptParams () const
virtual void BuildOptParams (Eigen::VectorXd &out_params) const
virtual void SetOptParams (const Eigen::VectorXd &params)
virtual void SetOptParams (const Eigen::VectorXd &params, Eigen::VectorXd &out_params) const
virtual void FetchOptParamScale (Eigen::VectorXd &out_scale) const
virtual void OutputOptParams (const std::string &file, const Eigen::VectorXd &params) const
virtual void OutputOptParams (FILE *f, const Eigen::VectorXd &params) const
virtual void SetActive (bool active)
virtual bool IsActive () const
virtual void SetMode (eMode mode)
virtual const cSimCharacter * GetChar () const
Protected Member Functions
virtual void SetupPDControllers (const Json::Value &json, const tVector &gravity)
virtual void ApplyAction (const Eigen::VectorXd &action)
virtual void BuildJointActionBounds (int joint_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max) const
virtual void BuildJointActionOffsetScale (int joint_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale) const
Protected Member Functions inherited from cCtPDController
virtual bool ParseParams (const Json::Value &json)
virtual void UpdateBuildTau (double time_step, Eigen::VectorXd &out_tau)
virtual void UpdatePDCtrls (double time_step, Eigen::VectorXd &out_tau)
virtual void ConvertActionToTargetPose (int joint_id, Eigen::VectorXd &out_theta) const
virtual cKinTree::eJointType GetJointType (int joint_id) const
virtual void SetPDTargets (const Eigen::VectorXd &targets)
Protected Member Functions inherited from cCtController
virtual void ResetParams ()
virtual int GetPosFeatureDim () const
virtual int GetRotFeatureDim () const
virtual bool CheckNeedNewAction (double timestep) const
virtual void NewActionUpdate ()
virtual int GetStatePoseSize () const
virtual int GetStateVelSize () const
virtual int GetStatePoseOffset () const
virtual int GetStatePhaseSize () const
virtual int GetStatePhaseOffset () const
virtual int GetActionPhaseOffset () const
virtual int GetActionPhaseSize () const
virtual int GetActionCtrlOffset () const
virtual int GetActionCtrlSize () const
virtual void BuildStatePhaseOffsetScale (Eigen::VectorXd &phase_offset, Eigen::VectorXd &phase_scale) const
virtual void BuildStatePose (Eigen::VectorXd &out_pose) const
virtual void BuildStateVel (Eigen::VectorXd &out_vel) const
virtual void BuildStatePhase (Eigen::VectorXd &out_phase) const
virtual bool FlipStance () const
virtual int RetargetJointID (int joint_id) const
virtual double GetPhaseRate () const
Protected Member Functions inherited from cDeepMimicCharController
cDeepMimicCharController ()
virtual void InitResources ()
virtual void InitAction ()
virtual void InitTau ()
virtual int GetPosDim () const
virtual void HandleNewAction ()
virtual void PostProcessAction (Eigen::VectorXd &out_action) const
virtual int GetStateVelOffset () const
Protected Member Functions inherited from cCharController
cCharController ()
Protected Member Functions inherited from cController
cController ()
Additional Inherited Members
Public Types inherited from cController
enum eMode { eModeActive, eModeInactive, eModePassive, eModeMax }
Static Public Attributes inherited from cCharController
const static int gNormGroupSingle = 0
const static int gNormGroupNone = -1
Protected Attributes inherited from cCtPDController
cImpPDController mPDCtrl
tVector mGravity
Protected Attributes inherited from cCtController
double mUpdateRate
double mCyclePeriod
bool mEnablePhaseInput
bool mEnablePhaseAction
bool mRecordWorldRootPos
bool mRecordWorldRootRot
double mPhaseOffset
double mInitTimeOffset
Eigen::VectorXd mActionBoundMin
Eigen::VectorXd mActionBoundMax
Protected Attributes inherited from cDeepMimicCharController
double mTime
bool mNeedNewAction
Eigen::VectorXd mAction
Eigen::VectorXd mTau
double mViewDistMin
double mViewDistMax
int mPosDim
double mPrevActionTime
tVector mPrevActionCOM
cCircularBuffer< double > mValLog
Protected Attributes inherited from cController
cSimCharacter * mChar
eMode mMode
bool mValid
Detailed Description
Definition at line 5 of file CtVelController.h.
Constructor & Destructor Documentation
cCtVelController()
cCtVelController::cCtVelController ()
Definition at line 4 of file CtVelController.cpp.
                                    : cCtPDController()
 {
 }
~cCtVelController()
cCtVelController::~cCtVelController () virtual
Definition at line 8 of file CtVelController.cpp.
 {
 }
Member Function Documentation
ApplyAction()
void cCtVelController::ApplyAction (const Eigen::VectorXd & action) protected virtual
Reimplemented from cCtPDController.
Definition at line 32 of file CtVelController.cpp.
 {
     cCtController::ApplyAction(action);
     int root_size = mChar->GetParamSize(mChar->GetRootID());
     int num_joints = mChar->GetNumJoints();
     int ctrl_offset = GetActionCtrlOffset();
     for (int j = 0; j < num_joints; ++j)
     {
         if (mPDCtrl.IsValidPDCtrl(j))
         {
             int param_offset = mChar->GetParamOffset(j);
             int param_size = mChar->GetParamSize(j);
             param_offset -= root_size;
             param_offset += ctrl_offset;
             Eigen::VectorXd theta_dot = mAction.segment(param_offset, param_size);
             mPDCtrl.SetTargetVel(j, theta_dot);
         }
     }
 }
References cDeepMimicCharController::ApplyAction(), cCtController::GetActionCtrlOffset(), cCharacter::GetNumJoints(), cCharacter::GetParamOffset(), cCharacter::GetParamSize(), cCharacter::GetRootID(), cExpPDController::IsValidPDCtrl(), cDeepMimicCharController::mAction, cController::mChar, cCtPDController::mPDCtrl, and cExpPDController::SetTargetVel().
BuildJointActionBounds()
void cCtVelController::BuildJointActionBounds (int joint_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) const protected virtual
Reimplemented from cCtPDController.
Definition at line 55 of file CtVelController.cpp.
 {
     const Eigen::MatrixXd& joint_mat = mChar->GetJointMat();
     cCtCtrlUtil::BuildBoundsVel(joint_mat, joint_id, out_min, out_max);
 }
References cCtCtrlUtil::BuildBoundsVel(), cCharacter::GetJointMat(), and cController::mChar.
BuildJointActionOffsetScale()
void cCtVelController::BuildJointActionOffsetScale (int joint_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) const protected virtual
Reimplemented from cCtPDController.
Definition at line 61 of file CtVelController.cpp.
 {
     const Eigen::MatrixXd& joint_mat = mChar->GetJointMat();
     cCtCtrlUtil::BuildOffsetScaleVel(joint_mat, joint_id, out_offset, out_scale);
 }
References cCtCtrlUtil::BuildOffsetScaleVel(), cCharacter::GetJointMat(), and cController::mChar.
GetName()
std::string cCtVelController::GetName () const virtual
Reimplemented from cCtPDController.
Definition at line 12 of file CtVelController.cpp.
 {
     return "ct_vel";
 }
SetupPDControllers()
void cCtVelController::SetupPDControllers (const Json::Value & json, const tVector & gravity) protected virtual
Reimplemented from cCtPDController.
Definition at line 17 of file CtVelController.cpp.
 {
     cCtPDController::SetupPDControllers(json, gravity);
     int num_joints = mPDCtrl.GetNumJoints();
     for (int j = 0; j < num_joints; ++j)
     {
         bool valid_pd = mPDCtrl.IsValidPDCtrl(j);
         if (valid_pd)
         {
             mPDCtrl.SetKp(j, 0);
         }
     }
 }
References cExpPDController::GetNumJoints(), cExpPDController::IsValidPDCtrl(), cCtPDController::mPDCtrl, cImpPDController::SetKp(), and cCtPDController::SetupPDControllers().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/CtVelController.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/CtVelController.cpp