My Project: cDrawCharacter Class Reference
cDrawCharacter Class Reference
#include <DrawCharacter.h>
Static Public Member Functions
static void Draw (const cCharacter &character, double link_width, const tVector &fill_col, const tVector &line_col)
static void DrawPose (const cCharacter &character, const Eigen::VectorXd &pose, const tVector &fill_tint, const tVector &line_col)
static void DrawHeading (const cCharacter &character, double arrow_size, const tVector &arrow_col, const tVector &offset)
Static Protected Member Functions
static void DrawShape (const cKinTree::tDrawShapeDef &def, const tMatrix &parent_world_trans, const tVector &fill_tint, const tVector &line_col)
static void DrawShapeMesh (const cKinTree::tDrawShapeDef &def, const tMatrix &parent_world_trans, cDrawMesh &mesh, const tVector &fill_tint)
static void DrawCharShapes (const cCharacter &character, const tVector &fill_tint, const tVector &line_col)
static void DrawPoseCharShapes (const cCharacter &character, const Eigen::VectorXd &pose, const tVector &fill_tint, const tVector &line_col)
static void DrawShapeBox (const cKinTree::tDrawShapeDef &def, const tMatrix &parent_world_trans, const tVector &fill_tint, const tVector &line_col)
static void DrawShapeCapsule (const cKinTree::tDrawShapeDef &def, const tMatrix &parent_world_trans, const tVector &fill_tint, const tVector &line_col)
static void DrawShapeSphere (const cKinTree::tDrawShapeDef &def, const tMatrix &parent_world_trans, const tVector &fill_tint, const tVector &line_col)
static void DrawShapeCylinder (const cKinTree::tDrawShapeDef &def, const tMatrix &parent_world_trans, const tVector &fill_tint, const tVector &line_col)
Detailed Description
Definition at line 6 of file DrawCharacter.h.
Member Function Documentation
Draw()
void cDrawCharacter::Draw (const cCharacter & character, double link_width, const tVector & fill_col, const tVector & line_col) static
Definition at line 6 of file DrawCharacter.cpp.
 {
     if (character.HasDrawShapes())
     {
         DrawCharShapes(character, tVector::Ones(), line_col);
     }
     else
     {
         const Eigen::MatrixXd& joint_mat = character.GetJointMat();
         const Eigen::VectorXd& pose = character.GetPose();
         cDrawKinTree::Draw(joint_mat, pose, link_width, fill_col, line_col);
     }
 }
References cDrawKinTree::Draw(), DrawCharShapes(), cCharacter::GetJointMat(), cCharacter::GetPose(), and cCharacter::HasDrawShapes().
Referenced by cDrawSimCharacter::Draw(), cDrawSceneKinChar::DrawCharacters(), and cDrawSceneImitate::DrawKinCharacter().
DrawCharShapes()
void cDrawCharacter::DrawCharShapes (const cCharacter & character, const tVector & fill_tint, const tVector & line_col) static protected
Definition at line 97 of file DrawCharacter.cpp.
 {
     assert(character.HasDrawShapes());
     const auto& shape_defs = character.GetDrawShapeDefs();
     size_t num_shapes = shape_defs.rows();
     cDrawUtil::SetLineWidth(1);
     for (int i = 0; i < num_shapes; ++i)
     {
         cKinTree::tDrawShapeDef curr_def = shape_defs.row(i);
         int parent_joint = cKinTree::GetDrawShapeParentJoint(curr_def);
         tMatrix parent_world_trans = character.BuildJointWorldTrans(parent_joint);
         int mesh_id = cKinTree::GetDrawShapeMeshID(curr_def);
         if (mesh_id != gInvalidIdx)
         {
             const auto& mesh = character.GetMesh(mesh_id);
             cDrawCharacter::DrawShapeMesh(curr_def, parent_world_trans, *mesh, fill_tint);
         }
         else
         {
             cDrawCharacter::DrawShape(curr_def, parent_world_trans, fill_tint, line_col);
         }
     }
 }
References cCharacter::BuildJointWorldTrans(), DrawShape(), DrawShapeMesh(), cCharacter::GetDrawShapeDefs(), cKinTree::GetDrawShapeMeshID(), cKinTree::GetDrawShapeParentJoint(), cCharacter::GetMesh(), gInvalidIdx, cCharacter::HasDrawShapes(), and cDrawUtil::SetLineWidth().
Referenced by Draw().
DrawHeading()
void cDrawCharacter::DrawHeading (const cCharacter & character, double arrow_size, const tVector & arrow_col, const tVector & offset) static
Definition at line 59 of file DrawCharacter.cpp.
 {
     tMatrix origin_trans = character.BuildOriginTrans();
     tMatrix heading_trans = cMathUtil::InvRigidMat(origin_trans);
     tVector root_pos = character.GetRootPos();
     cDrawUtil::SetColor(arrow_col);
     tVector start = tVector(0.25, root_pos[1], 0, 0);
     tVector end = tVector(1, root_pos[1], 0, 0);
     cDrawUtil::PushMatrixView();
     cDrawUtil::MultMatrixView(heading_trans);
     cDrawUtil::DrawArrow2D(start, end, arrow_size);
     cDrawUtil::PopMatrixView();
 }
References cCharacter::BuildOriginTrans(), cDrawUtil::DrawArrow2D(), cCharacter::GetRootPos(), cMathUtil::InvRigidMat(), cDrawUtil::MultMatrixView(), cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixView(), and cDrawUtil::SetColor().
Referenced by cDrawSceneSimChar::DrawHeading().
DrawPose()
void cDrawCharacter::DrawPose (const cCharacter & character, const Eigen::VectorXd & pose, const tVector & fill_tint, const tVector & line_col) static
Definition at line 20 of file DrawCharacter.cpp.
 {
     if (character.HasDrawShapes())
     {
         DrawPoseCharShapes(character, pose, tVector::Ones(), line_col);
     }
     else
     {
         const Eigen::MatrixXd& joint_mat = character.GetJointMat();
         cDrawKinTree::Draw(joint_mat, pose, 0, fill_tint, line_col);
     }
 }
References cDrawKinTree::Draw(), DrawPoseCharShapes(), cCharacter::GetJointMat(), and cCharacter::HasDrawShapes().
DrawPoseCharShapes()
void cDrawCharacter::DrawPoseCharShapes (const cCharacter & character, const Eigen::VectorXd & pose, const tVector & fill_tint, const tVector & line_col) static protected
Definition at line 123 of file DrawCharacter.cpp.
 {
     assert(character.HasDrawShapes());
     const auto& shape_defs = character.GetDrawShapeDefs();
     size_t num_shapes = shape_defs.rows();
     const auto& joint_mat = character.GetJointMat();
     cDrawUtil::SetLineWidth(1);
     for (int i = 0; i < num_shapes; ++i)
     {
         cKinTree::tDrawShapeDef curr_def = shape_defs.row(i);
         int parent_joint = cKinTree::GetDrawShapeParentJoint(curr_def);
         tMatrix parent_world_trans = cKinTree::JointWorldTrans(joint_mat, pose, parent_joint);
         int mesh_id = cKinTree::GetDrawShapeMeshID(curr_def);
         if (mesh_id != gInvalidIdx)
         {
             const auto& mesh = character.GetMesh(mesh_id);
             cDrawCharacter::DrawShapeMesh(curr_def, parent_world_trans, *mesh, fill_tint);
         }
         else
         {
             cDrawCharacter::DrawShape(curr_def, parent_world_trans, fill_tint, line_col);
         }
     }
 }
References DrawShape(), DrawShapeMesh(), cCharacter::GetDrawShapeDefs(), cKinTree::GetDrawShapeMeshID(), cKinTree::GetDrawShapeParentJoint(), cCharacter::GetJointMat(), cCharacter::GetMesh(), gInvalidIdx, cCharacter::HasDrawShapes(), cKinTree::JointWorldTrans(), and cDrawUtil::SetLineWidth().
Referenced by DrawPose().
DrawShape()
void cDrawCharacter::DrawShape (const cKinTree::tDrawShapeDef & def, const tMatrix & parent_world_trans, const tVector & fill_tint, const tVector & line_col) static protected
Definition at line 33 of file DrawCharacter.cpp.
 {
     cShape::eShape shape = static_cast<cShape::eShape>((int)def[cKinTree::eDrawShapeShape]);
     switch (shape)
     {
     case cShape::eShapeBox:
         DrawShapeBox(def, parent_world_trans, fill_tint, line_col);
         break;
     case cShape::eShapeCapsule:
         DrawShapeCapsule(def, parent_world_trans, fill_tint, line_col);
         break;
     case cShape::eShapeSphere:
         DrawShapeSphere(def, parent_world_trans, fill_tint, line_col);
         break;
     case cShape::eShapeCylinder:
         DrawShapeCylinder(def, parent_world_trans, fill_tint, line_col);
         break;
     case cShape::eShapeNull:
         break;
     default:
         assert(false); // unsupported draw shape
         break;
     }
 }
References DrawShapeBox(), DrawShapeCapsule(), DrawShapeCylinder(), DrawShapeSphere(), cKinTree::eDrawShapeShape, cShape::eShapeBox, cShape::eShapeCapsule, cShape::eShapeCylinder, cShape::eShapeNull, and cShape::eShapeSphere.
Referenced by DrawCharShapes(), and DrawPoseCharShapes().
DrawShapeBox()
void cDrawCharacter::DrawShapeBox (const cKinTree::tDrawShapeDef & def, const tMatrix & parent_world_trans, const tVector & fill_tint, const tVector & line_col) static protected
Definition at line 150 of file DrawCharacter.cpp.
 {
     double theta = 0;
     tVector euler = cKinTree::GetDrawShapeAttachTheta(def);
     int parent_joint = cKinTree::GetDrawShapeParentJoint(def);
     tVector attach_pt = cKinTree::GetDrawShapeAttachPt(def);
     tVector col = cKinTree::GetDrawShapeColor(def);
     tVector size = tVector(def[cKinTree::eDrawShapeParam0], def[cKinTree::eDrawShapeParam1], def[cKinTree::eDrawShapeParam2], 0);
     col = col.cwiseProduct(fill_tint);
     cDrawUtil::PushMatrixView();
     cDrawUtil::MultMatrixView(parent_world_trans);
     cDrawUtil::Translate(attach_pt);
     cDrawUtil::Rotate(euler);
     cDrawUtil::SetColor(col);
     cDrawUtil::DrawBox(tVector::Zero(), size, cDrawUtil::eDrawSolid);
     if (line_col[3] > 0)
     {
         cDrawUtil::SetColor(line_col);
         cDrawUtil::DrawBox(tVector::Zero(), size, cDrawUtil::eDrawWireSimple);
     }
     cDrawUtil::PopMatrixView();
 }
References cDrawUtil::DrawBox(), cKinTree::eDrawShapeParam0, cKinTree::eDrawShapeParam1, cKinTree::eDrawShapeParam2, cDrawUtil::eDrawSolid, cDrawUtil::eDrawWireSimple, cKinTree::GetDrawShapeAttachPt(), cKinTree::GetDrawShapeAttachTheta(), cKinTree::GetDrawShapeColor(), cKinTree::GetDrawShapeParentJoint(), cDrawUtil::MultMatrixView(), cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixView(), cDrawUtil::Rotate(), cDrawUtil::SetColor(), and cDrawUtil::Translate().
Referenced by DrawShape().
DrawShapeCapsule()
void cDrawCharacter::DrawShapeCapsule (const cKinTree::tDrawShapeDef & def, const tMatrix & parent_world_trans, const tVector & fill_tint, const tVector & line_col) static protected
Definition at line 178 of file DrawCharacter.cpp.
 {
     double theta = 0;
     tVector axis = tVector(0, 0, 1, 0);
     cKinTree::GetDrawShapeRotation(def, axis, theta);
     int parent_joint = cKinTree::GetDrawShapeParentJoint(def);
     tVector attach_pt = cKinTree::GetDrawShapeAttachPt(def);
     tVector col = cKinTree::GetDrawShapeColor(def);
     tVector size = tVector(def[cKinTree::eDrawShapeParam0], def[cKinTree::eDrawShapeParam1], 0, 0);
     col = col.cwiseProduct(fill_tint);
     double r = 0.5 * size[0];
     double h = size[1];
     cDrawUtil::PushMatrixView();
     cDrawUtil::MultMatrixView(parent_world_trans);
     cDrawUtil::Translate(attach_pt);
     cDrawUtil::Rotate(theta, axis);
     cDrawUtil::SetColor(col);
     cDrawUtil::DrawCapsule(r, h, cDrawUtil::eDrawSolid);
     if (line_col[3] > 0)
     {
         cDrawUtil::SetColor(line_col);
         cDrawUtil::DrawCapsule(r, h, cDrawUtil::eDrawWireSimple);
     }
     cDrawUtil::PopMatrixView();
 }
References cDrawUtil::DrawCapsule(), cKinTree::eDrawShapeParam0, cKinTree::eDrawShapeParam1, cDrawUtil::eDrawSolid, cDrawUtil::eDrawWireSimple, cKinTree::GetDrawShapeAttachPt(), cKinTree::GetDrawShapeColor(), cKinTree::GetDrawShapeParentJoint(), cKinTree::GetDrawShapeRotation(), cDrawUtil::MultMatrixView(), cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixView(), cDrawUtil::Rotate(), cDrawUtil::SetColor(), and cDrawUtil::Translate().
Referenced by DrawShape().
DrawShapeCylinder()
void cDrawCharacter::DrawShapeCylinder (const cKinTree::tDrawShapeDef & def, const tMatrix & parent_world_trans, const tVector & fill_tint, const tVector & line_col) static protected
Definition at line 241 of file DrawCharacter.cpp.
 {
     double theta = 0;
     tVector axis = tVector(0, 0, 1, 0);
     cKinTree::GetDrawShapeRotation(def, axis, theta);
     int parent_joint = cKinTree::GetDrawShapeParentJoint(def);
     tVector attach_pt = cKinTree::GetDrawShapeAttachPt(def);
     tVector col = cKinTree::GetDrawShapeColor(def);
     tVector size = tVector(def[cKinTree::eDrawShapeParam0], def[cKinTree::eDrawShapeParam1], 0, 0);
     col = col.cwiseProduct(fill_tint);
     double r = 0.5 * size[0];
     double h = size[1];
     cDrawUtil::PushMatrixView();
     cDrawUtil::MultMatrixView(parent_world_trans);
     cDrawUtil::Translate(attach_pt);
     cDrawUtil::Rotate(theta, axis);
     cDrawUtil::SetColor(col);
     cDrawUtil::DrawCylinder(r, h, cDrawUtil::eDrawSolid);
     if (line_col[3] > 0)
     {
         cDrawUtil::SetColor(line_col);
         cDrawUtil::DrawCylinder(r, h, cDrawUtil::eDrawWireSimple);
     }
     cDrawUtil::PopMatrixView();
 }
References cDrawUtil::DrawCylinder(), cKinTree::eDrawShapeParam0, cKinTree::eDrawShapeParam1, cDrawUtil::eDrawSolid, cDrawUtil::eDrawWireSimple, cKinTree::GetDrawShapeAttachPt(), cKinTree::GetDrawShapeColor(), cKinTree::GetDrawShapeParentJoint(), cKinTree::GetDrawShapeRotation(), cDrawUtil::MultMatrixView(), cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixView(), cDrawUtil::Rotate(), cDrawUtil::SetColor(), and cDrawUtil::Translate().
Referenced by DrawShape().
DrawShapeMesh()
void cDrawCharacter::DrawShapeMesh (const cKinTree::tDrawShapeDef & def, const tMatrix & parent_world_trans, cDrawMesh & mesh, const tVector & fill_tint) static protected
Definition at line 75 of file DrawCharacter.cpp.
 {
     double theta = 0;
     tVector euler = cKinTree::GetDrawShapeAttachTheta(def);
     int parent_joint = cKinTree::GetDrawShapeParentJoint(def);
     tVector attach_pt = cKinTree::GetDrawShapeAttachPt(def);
     tVector col = cKinTree::GetDrawShapeColor(def);
     tVector scale = tVector(def[cKinTree::eDrawShapeParam0], def[cKinTree::eDrawShapeParam1], def[cKinTree::eDrawShapeParam2], 0);
     col = col.cwiseProduct(fill_tint);
     cDrawUtil::PushMatrixView();
     cDrawUtil::MultMatrixView(parent_world_trans);
     cDrawUtil::Translate(attach_pt);
     cDrawUtil::Rotate(euler);
     cDrawUtil::Scale(scale);
     cDrawUtil::SetColor(col);
     mesh.Draw();
     cDrawUtil::PopMatrixView();
 }
References cDrawMesh::Draw(), cKinTree::eDrawShapeParam0, cKinTree::eDrawShapeParam1, cKinTree::eDrawShapeParam2, cKinTree::GetDrawShapeAttachPt(), cKinTree::GetDrawShapeAttachTheta(), cKinTree::GetDrawShapeColor(), cKinTree::GetDrawShapeParentJoint(), cDrawUtil::MultMatrixView(), cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixView(), cDrawUtil::Rotate(), cDrawUtil::Scale(), cDrawUtil::SetColor(), and cDrawUtil::Translate().
Referenced by DrawCharShapes(), and DrawPoseCharShapes().
DrawShapeSphere()
void cDrawCharacter::DrawShapeSphere (const cKinTree::tDrawShapeDef & def, const tMatrix & parent_world_trans, const tVector & fill_tint, const tVector & line_col) static protected
Definition at line 210 of file DrawCharacter.cpp.
 {
     double theta = 0;
     tVector axis = tVector(0, 0, 1, 0);
     cKinTree::GetDrawShapeRotation(def, axis, theta);
     int parent_joint = cKinTree::GetDrawShapeParentJoint(def);
     tVector attach_pt = cKinTree::GetDrawShapeAttachPt(def);
     tVector col = cKinTree::GetDrawShapeColor(def);
     tVector size = tVector(def[cKinTree::eDrawShapeParam0], def[cKinTree::eDrawShapeParam1], 0, 0);
     col = col.cwiseProduct(fill_tint);
     double r = 0.5 * size[0];
     cDrawUtil::PushMatrixView();
     cDrawUtil::MultMatrixView(parent_world_trans);
     cDrawUtil::Translate(attach_pt);
     cDrawUtil::Rotate(theta, axis);
     cDrawUtil::SetColor(col);
     cDrawUtil::DrawSphere(r, cDrawUtil::eDrawSolid);
     if (line_col[3] > 0)
     {
         cDrawUtil::SetColor(line_col);
         cDrawUtil::DrawSphere(r, cDrawUtil::eDrawWireSimple);
     }
     cDrawUtil::PopMatrixView();
 }
References cDrawUtil::DrawSphere(), cKinTree::eDrawShapeParam0, cKinTree::eDrawShapeParam1, cDrawUtil::eDrawSolid, cDrawUtil::eDrawWireSimple, cKinTree::GetDrawShapeAttachPt(), cKinTree::GetDrawShapeColor(), cKinTree::GetDrawShapeParentJoint(), cKinTree::GetDrawShapeRotation(), cDrawUtil::MultMatrixView(), cDrawUtil::PopMatrixView(), cDrawUtil::PushMatrixView(), cDrawUtil::Rotate(), cDrawUtil::SetColor(), and cDrawUtil::Translate().
Referenced by DrawShape().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/DrawCharacter.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/render/DrawCharacter.cpp