My Project: cRand Class Reference
cRand Class Reference
#include <Rand.h>
Public Member Functions
cRand ()
cRand (unsigned long int seed)
virtual ~cRand ()
virtual double RandDouble ()
virtual double RandDouble (double min, double max)
virtual double RandDoubleExp (double lambda)
virtual double RandDoubleNorm (double mean, double stdev)
virtual int RandInt ()
virtual int RandInt (int min, int max)
virtual int RandUint ()
virtual int RandUint (unsigned int min, unsigned int max)
virtual int RandIntExclude (int min, int max, int exc)
virtual void Seed (unsigned long int seed)
virtual int RandSign ()
virtual bool FlipCoin (double p=0.5)
Private Attributes
std::default_random_engine mRandGen
std::uniform_real_distribution< double > mRandDoubleDist
std::normal_distribution< double > mRandDoubleDistNorm
std::uniform_int_distribution< int > mRandIntDist
std::uniform_int_distribution< unsigned int > mRandUintDist
Detailed Description
Definition at line 5 of file Rand.h.
Constructor & Destructor Documentation
cRand() [1/2]
cRand::cRand ()
Definition at line 6 of file Rand.cpp.
 {
     unsigned long int seed = static_cast<unsigned long int>(time(NULL));
     mRandGen = std::default_random_engine(seed);
     mRandDoubleDist = std::uniform_real_distribution<double>(0, 1);
     mRandDoubleDistNorm = std::normal_distribution<double>(0, 1);
     mRandIntDist = std::uniform_int_distribution<int>(std::numeric_limits<int>::min() + 1, std::numeric_limits<int>::max()); // + 1 since there is one more neg int than pos int
     mRandUintDist = std::uniform_int_distribution<unsigned int>(std::numeric_limits<unsigned int>::min(), std::numeric_limits<unsigned int>::max());
 }
References mRandDoubleDist, mRandDoubleDistNorm, mRandGen, mRandIntDist, and mRandUintDist.
cRand() [2/2]
cRand::cRand (unsigned long int seed)
Definition at line 16 of file Rand.cpp.
                                    : cRand()
 {
     Seed(seed);
 }
References Seed().
~cRand()
cRand::~cRand () virtual
Definition at line 21 of file Rand.cpp.
 {
 }
Member Function Documentation
FlipCoin()
bool cRand::FlipCoin (double p = 0.5) virtual
Definition at line 137 of file Rand.cpp.
 {
     return (RandDouble(0, 1) < p);
 }
References RandDouble().
Referenced by cMathUtil::FlipCoin(), and RandSign().
RandDouble() [1/2]
double cRand::RandDouble () virtual
Definition at line 25 of file Rand.cpp.
 {
     return mRandDoubleDist(mRandGen);
 }
References mRandDoubleDist, and mRandGen.
Referenced by cSceneSimChar::ApplyRandForce(), FlipCoin(), cMathUtil::RandDouble(), cSceneImitate::ResetKinChar(), cSceneSimChar::ResetRandPertrub(), and cSceneSimChar::SpawnProjectile().
RandDouble() [2/2]
double cRand::RandDouble (double min, double max) virtual
Definition at line 30 of file Rand.cpp.
 {
     if (min == max)
     {
         return min;
     }
     // generate random double in [min, max]
     double rand_double = mRandDoubleDist(mRandGen);
     rand_double = min + (rand_double * (max - min));
     return rand_double;
 }
References mRandDoubleDist, and mRandGen.
RandDoubleExp()
double cRand::RandDoubleExp (double lambda) virtual
Definition at line 43 of file Rand.cpp.
 {
     std::exponential_distribution<double> dist(lambda);
     double rand_double = dist(mRandGen);
     return rand_double;
 }
References mRandGen.
Referenced by cMathUtil::RandDoubleExp().
RandDoubleNorm()
double cRand::RandDoubleNorm (double mean, double stdev) virtual
Definition at line 50 of file Rand.cpp.
 {
     double rand_double = mRandDoubleDistNorm(mRandGen);
     rand_double = mean + stdev * rand_double;
     return rand_double;
 }
References mRandDoubleDistNorm, and mRandGen.
Referenced by cMathUtil::RandDoubleNorm().
RandInt() [1/2]
int cRand::RandInt () virtual
Definition at line 57 of file Rand.cpp.
 {
     return mRandIntDist(mRandGen);
 }
References mRandGen, and mRandIntDist.
Referenced by cSceneSimChar::GetRandPerturbPartID(), RandInt(), cMathUtil::RandInt(), RandIntExclude(), cMathUtil::SeedRand(), and cSceneSimChar::SpawnProjectile().
RandInt() [2/2]
int cRand::RandInt (int min, int max) virtual
Definition at line 62 of file Rand.cpp.
 {
     if (min == max)
     {
         return min;
     }
     // generate random double in [min, max)
     int delta = max - min;
     int rand_int = std::abs(RandInt());
     rand_int = min + rand_int % delta;
     return rand_int;
 }
References RandInt().
RandIntExclude()
int cRand::RandIntExclude (int min, int max, int exc) virtual
Definition at line 97 of file Rand.cpp.
 {
     int rand_int = 0;
     if (exc < min || exc >= max)
     {
         rand_int = RandInt(min, max);
     }
     else
     {
         int new_max = max - 1;
         if (new_max <= min)
         {
             rand_int = min;
         }
         else
         {
             rand_int = RandInt(min, new_max);
             if (rand_int >= exc)
             {
                 ++rand_int;
             }
         }
     }
     return rand_int;
 }
References RandInt().
Referenced by cMathUtil::RandIntExclude().
RandSign()
int cRand::RandSign () virtual
Definition at line 132 of file Rand.cpp.
 {
     return FlipCoin() ? -1 : 1;
 }
References FlipCoin().
Referenced by cMathUtil::RandSign(), and cSceneSimChar::SpawnProjectile().
RandUint() [1/2]
int cRand::RandUint () virtual
Definition at line 77 of file Rand.cpp.
 {
     return mRandUintDist(mRandGen);
 }
References mRandGen, and mRandUintDist.
Referenced by RandUint(), and cMathUtil::RandUint().
RandUint() [2/2]
int cRand::RandUint (unsigned int min, unsigned int max) virtual
Definition at line 82 of file Rand.cpp.
 {
     if (min == max)
     {
         return min;
     }
     // generate random double in [min, max)
     int delta = max - min;
     int rand_int = RandUint();
     rand_int = min + rand_int % delta;
     return rand_int;
 }
References RandUint().
Seed()
void cRand::Seed (unsigned long int seed) virtual
Definition at line 123 of file Rand.cpp.
 {
     mRandGen.seed(seed);
     mRandDoubleDist.reset();
     mRandDoubleDistNorm.reset();
     mRandIntDist.reset();
     mRandUintDist.reset();
 }
References mRandDoubleDist, mRandDoubleDistNorm, mRandGen, mRandIntDist, and mRandUintDist.
Referenced by cRand(), cScene::cScene(), cMathUtil::SeedRand(), cGround::SeedRand(), and cScene::SetRandSeed().
Member Data Documentation
mRandDoubleDist
std::uniform_real_distribution<double> cRand::mRandDoubleDist private
Definition at line 27 of file Rand.h.
Referenced by cRand(), RandDouble(), and Seed().
mRandDoubleDistNorm
std::normal_distribution<double> cRand::mRandDoubleDistNorm private
Definition at line 28 of file Rand.h.
Referenced by cRand(), RandDoubleNorm(), and Seed().
mRandGen
std::default_random_engine cRand::mRandGen private
Definition at line 26 of file Rand.h.
Referenced by cRand(), RandDouble(), RandDoubleExp(), RandDoubleNorm(), RandInt(), RandUint(), and Seed().
mRandIntDist
std::uniform_int_distribution<int> cRand::mRandIntDist private
Definition at line 29 of file Rand.h.
Referenced by cRand(), RandInt(), and Seed().
mRandUintDist
std::uniform_int_distribution<unsigned int> cRand::mRandUintDist private
Definition at line 30 of file Rand.h.
Referenced by cRand(), RandUint(), and Seed().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/Rand.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/util/Rand.cpp