My Project: cCharacter Class Reference
cCharacter Class Reference
#include <Character.h>
Public Member Functions
virtual ~cCharacter ()
virtual void SetID (int id)
virtual int GetID () const
virtual bool Init (const std::string &char_file, bool load_draw_shapes)
virtual void Clear ()
virtual void Update (double time_step)
virtual void Reset ()
virtual int GetNumDof () const
virtual const Eigen::MatrixXd & GetJointMat () const
virtual int GetNumJoints () const
virtual const Eigen::VectorXd & GetPose () const
virtual void SetPose (const Eigen::VectorXd &pose)
virtual const Eigen::VectorXd & GetPose0 () const
virtual void SetPose0 (const Eigen::VectorXd &pose)
virtual const Eigen::VectorXd & GetVel () const
virtual void SetVel (const Eigen::VectorXd &vel)
virtual const Eigen::VectorXd & GetVel0 () const
virtual void SetVel0 (const Eigen::VectorXd &vel)
virtual int GetRootID () const
virtual tVector GetRootPos () const
virtual void GetRootRotation (tVector &out_axis, double &out_theta) const
virtual tQuaternion GetRootRotation () const
virtual void SetRootPos (const tVector &pos)
virtual void SetRootPos0 (const tVector &pose)
virtual void SetRootRotation (const tQuaternion &q)
virtual void RotateRoot (const tQuaternion &rot)
virtual void SetRootVel (const tVector &vel)
virtual void SetRootAngVel (const tVector &ang_vel)
virtual tQuaternion CalcHeadingRot () const
virtual double CalcHeading () const
virtual tMatrix BuildOriginTrans () const
virtual int GetParamOffset (int joint_id) const
virtual int GetParamSize (int joint_id) const
virtual bool IsEndEffector (int joint_id) const
virtual int GetParentJoint (int joint_id) const
virtual tVector CalcJointPos (int joint_id) const
virtual tVector CalcJointVel (int joint_id) const
virtual void CalcJointWorldRotation (int joint_id, tVector &out_axis, double &out_theta) const
virtual tQuaternion CalcJointWorldRotation (int joint_id) const
virtual double CalcJointChainLength (int joint_id)
virtual tMatrix BuildJointWorldTrans (int joint_id) const
virtual void CalcAABB (tVector &out_min, tVector &out_max) const
virtual int CalcNumEndEffectors () const
virtual double GetJointDiffWeight (int joint_id) const
virtual bool WriteState (const std::string &file) const
virtual bool WriteState (const std::string &file, const tMatrix &root_trans) const
virtual bool ReadState (const std::string &file)
virtual bool LoadSkeleton (const Json::Value &root)
virtual void InitDefaultState ()
virtual bool HasDrawShapes () const
virtual const Eigen::MatrixXd & GetDrawShapeDefs () const
virtual const std::shared_ptr< cDrawMesh > & GetMesh (int i) const
virtual int GetNumMeshes () const
Static Public Attributes
static const std::string gSkeletonKey = "Skeleton"
Protected Member Functions
cCharacter ()
virtual void ResetParams ()
virtual bool ParseState (const Json::Value &root, Eigen::VectorXd &out_state) const
virtual std::string BuildStateJson (const Eigen::VectorXd &pose, const Eigen::VectorXd &vel) const
virtual bool LoadDrawShapeDefs (const std::string &char_file, Eigen::MatrixXd &out_draw_defs) const
virtual bool LoadMeshes (const std::string &char_file, std::vector< std::shared_ptr< cDrawMesh >> &out_meshes) const
Protected Attributes
int mID
Eigen::MatrixXd mJointMat
Eigen::VectorXd mPose
Eigen::VectorXd mVel
Eigen::VectorXd mPose0
Eigen::VectorXd mVel0
Eigen::MatrixXd mDrawShapeDefs
std::vector< std::shared_ptr< cDrawMesh > > mMeshes
Detailed Description
Definition at line 7 of file Character.h.
Constructor & Destructor Documentation
~cCharacter()
cCharacter::~cCharacter () virtual
Definition at line 22 of file Character.cpp.
 {
 }
cCharacter()
cCharacter::cCharacter () protected
Definition at line 16 of file Character.cpp.
 {
     mID = gInvalidIdx;
     ResetParams();
 }
References gInvalidIdx, mID, and ResetParams().
Member Function Documentation
BuildJointWorldTrans()
tMatrix cCharacter::BuildJointWorldTrans (int joint_id) const virtual
Reimplemented in cSimCharacter.
Definition at line 288 of file Character.cpp.
 {
     return cKinTree::JointWorldTrans(mJointMat, mPose, joint_id);
 }
References cKinTree::JointWorldTrans(), mJointMat, and mPose.
Referenced by cSimCharacter::BuildJointWorldTrans(), and cDrawCharacter::DrawCharShapes().
BuildOriginTrans()
tMatrix cCharacter::BuildOriginTrans () const virtual
Definition at line 232 of file Character.cpp.
 {
     return cKinTree::BuildOriginTrans(mJointMat, mPose);
 }
References cKinTree::BuildOriginTrans(), mJointMat, and mPose.
Referenced by cCtController::BuildStatePose(), cDeepMimicCharController::BuildStatePose(), cCtController::BuildStateVel(), cDeepMimicCharController::BuildStateVel(), cSceneImitate::CalcRewardImitate(), and cDrawCharacter::DrawHeading().
BuildStateJson()
std::string cCharacter::BuildStateJson (const Eigen::VectorXd & pose, const Eigen::VectorXd & vel) const protected virtual
Definition at line 431 of file Character.cpp.
 {
     std::string json = "";
     std::string pose_json = cJsonUtil::BuildVectorJson(pose);
     std::string vel_json = cJsonUtil::BuildVectorJson(vel);
     json = "{\n\"Pose\":" + pose_json + ",\n\"Vel\":" + vel_json + "\n}";
     return json;
 }
References cJsonUtil::BuildVectorJson().
Referenced by WriteState().
CalcAABB()
void cCharacter::CalcAABB (tVector & out_min, tVector & out_max) const virtual
Reimplemented in cSimCharacter.
Definition at line 293 of file Character.cpp.
 {
     cKinTree::CalcAABB(mJointMat, mPose, out_min, out_max);
 }
References cKinTree::CalcAABB(), mJointMat, and mPose.
CalcHeading()
double cCharacter::CalcHeading () const virtual
Definition at line 227 of file Character.cpp.
 {
     return cKinTree::CalcHeading(mJointMat, mPose);
 }
References cKinTree::CalcHeading(), mJointMat, and mPose.
Referenced by cSceneImitate::SyncKinCharNewCycle().
CalcHeadingRot()
tQuaternion cCharacter::CalcHeadingRot () const virtual
Reimplemented in cSimCharacter.
Definition at line 222 of file Character.cpp.
 {
     return cKinTree::CalcHeadingRot(mJointMat, mPose);
 }
References cKinTree::CalcHeadingRot(), mJointMat, and mPose.
CalcJointChainLength()
double cCharacter::CalcJointChainLength (int joint_id) virtual
Definition at line 282 of file Character.cpp.
 {
     auto chain = cKinTree::FindJointChain(mJointMat, GetRootID(), joint_id);
     return cKinTree::CalcChainLength(mJointMat, chain);
 }
References cKinTree::CalcChainLength(), cKinTree::FindJointChain(), GetRootID(), and mJointMat.
CalcJointPos()
tVector cCharacter::CalcJointPos (int joint_id) const virtual
Reimplemented in cSimCharacter.
Definition at line 257 of file Character.cpp.
 {
     tVector pos = cKinTree::CalcJointWorldPos(mJointMat, mPose, joint_id);
     return pos;
 }
References cKinTree::CalcJointWorldPos(), mJointMat, and mPose.
CalcJointVel()
tVector cCharacter::CalcJointVel (int joint_id) const virtual
Reimplemented in cSimCharacter.
Definition at line 263 of file Character.cpp.
 {
     tVector pos = cKinTree::CalcJointWorldVel(mJointMat, mPose, mVel, joint_id);
     return pos;
 }
References cKinTree::CalcJointWorldVel(), mJointMat, mPose, and mVel.
CalcJointWorldRotation() [1/2]
tQuaternion cCharacter::CalcJointWorldRotation (int joint_id) const virtual
Reimplemented in cSimCharacter.
Definition at line 274 of file Character.cpp.
 {
     tVector axis;
     double theta;
     CalcJointWorldRotation(joint_id, axis, theta);
     return cMathUtil::AxisAngleToQuaternion(axis, theta);
 }
References cMathUtil::AxisAngleToQuaternion(), and CalcJointWorldRotation().
CalcJointWorldRotation() [2/2]
void cCharacter::CalcJointWorldRotation (int joint_id, tVector & out_axis, double & out_theta) const virtual
Reimplemented in cSimCharacter.
Definition at line 269 of file Character.cpp.
 {
     cKinTree::CalcJointWorldTheta(mJointMat, mPose, joint_id, out_axis, out_theta);
 }
References cKinTree::CalcJointWorldTheta(), mJointMat, and mPose.
Referenced by CalcJointWorldRotation().
CalcNumEndEffectors()
int cCharacter::CalcNumEndEffectors () const virtual
Definition at line 298 of file Character.cpp.
 {
     int num_end = 0;
     for (int j = 0; j < GetNumJoints(); ++j)
     {
         if (IsEndEffector(j))
         {
             ++num_end;
         }
     }
     return num_end;
 }
References GetNumJoints(), and IsEndEffector().
Clear()
void cCharacter::Clear () virtual
Reimplemented in cSimCharacter, and cKinCharacter.
Definition at line 81 of file Character.cpp.
 {
     ResetParams();
     mPose.resize(0);
     mVel.resize(0);
     mPose0.resize(0);
     mVel0.resize(0);
     mDrawShapeDefs.resize(0, 0);
     mMeshes.clear();
 }
References mDrawShapeDefs, mMeshes, mPose, mPose0, mVel, mVel0, and ResetParams().
Referenced by cKinCharacter::Clear(), cSimCharacter::Clear(), and Init().
GetDrawShapeDefs()
const Eigen::MatrixXd & cCharacter::GetDrawShapeDefs () const virtual
Definition at line 403 of file Character.cpp.
 {
     return mDrawShapeDefs;
 }
References mDrawShapeDefs.
Referenced by cDrawCharacter::DrawCharShapes(), and cDrawCharacter::DrawPoseCharShapes().
GetID()
int cCharacter::GetID () const virtual
Definition at line 31 of file Character.cpp.
 {
     return mID;
 }
References mID.
GetJointDiffWeight()
double cCharacter::GetJointDiffWeight (int joint_id) const virtual
Definition at line 312 of file Character.cpp.
 {
     return cKinTree::GetJointDiffWeight(mJointMat, joint_id);
 }
References cKinTree::GetJointDiffWeight(), and mJointMat.
GetJointMat()
const Eigen::MatrixXd & cCharacter::GetJointMat () const virtual
Definition at line 114 of file Character.cpp.
 {
     return mJointMat;
 }
References mJointMat.
Referenced by cCtVelController::BuildJointActionBounds(), cCtPDController::BuildJointActionBounds(), cCtController::BuildJointActionBounds(), cCtVelController::BuildJointActionOffsetScale(), cCtPDController::BuildJointActionOffsetScale(), cCtController::BuildJointActionOffsetScale(), cImpPDController::BuildRBDModel(), cImpPDController::CalcControlForces(), cKinCharacter::CalcFrameVel(), cSceneImitate::CalcRewardImitate(), cDrawCharacter::Draw(), cDrawCharacter::DrawPose(), cDrawCharacter::DrawPoseCharShapes(), cKinCharacter::MirrorFrame(), cKinCharacter::PostProcessFrame(), and cSimCharacter::UpdateLinkVel().
GetMesh()
const std::shared_ptr< cDrawMesh > & cCharacter::GetMesh (int i) const virtual
Definition at line 408 of file Character.cpp.
 {
     assert(i >= 0 && i < GetNumMeshes());
     return mMeshes[i];
 }
References GetNumMeshes(), and mMeshes.
Referenced by cDrawCharacter::DrawCharShapes(), and cDrawCharacter::DrawPoseCharShapes().
GetNumDof()
int cCharacter::GetNumDof () const virtual
Definition at line 108 of file Character.cpp.
 {
     int dofs = cKinTree::GetNumDof(mJointMat);
     return dofs;
 }
References cKinTree::GetNumDof(), and mJointMat.
Referenced by cSimCharacter::ApplyControlForces(), cKinCharacter::CalcVel(), cCtController::GetActionCtrlSize(), cExpPDController::GetNumDof(), InitDefaultState(), cDeepMimicCharController::InitTau(), cKinCharacter::LoadMotion(), ParseState(), SetPose(), SetVel(), cPDController::Update(), cCtController::UpdateBuildTau(), and cCtPDController::UpdatePDCtrls().
GetNumJoints()
int cCharacter::GetNumJoints () const virtual
Definition at line 119 of file Character.cpp.
 {
     return cKinTree::GetNumJoints(mJointMat);
 }
References cKinTree::GetNumJoints(), and mJointMat.
Referenced by cCtVelController::ApplyAction(), cSimCharacter::ApplyControlForces(), cCtController::BuildActionBounds(), cCtController::BuildActionOffsetScale(), cSimCharacter::BuildBodyLinks(), cSimCharacter::BuildConstraints(), cSimCharacter::BuildJoints(), cSimCharacter::BuildMultiBody(), cSimCharacter::BuildPose(), cSimCharacter::BuildVel(), CalcNumEndEffectors(), cSceneImitate::CalcRewardImitate(), cSimCharacter::ClearJointTorques(), cDrawSimCharacter::DrawTorque(), cExpPDController::GetNumJoints(), cSimCharacter::HasStumbled(), cExpPDController::Init(), cSimCharacter::LoadBodyDefs(), cCtPDController::SetPDTargets(), cSimCharacter::SetPose(), cSimCharacter::SetVel(), cCtController::UpdateBuildTau(), and cSimCharacter::UpdateJoints().
GetNumMeshes()
int cCharacter::GetNumMeshes () const virtual
Definition at line 414 of file Character.cpp.
 {
     return static_cast<int>(mMeshes.size());
 }
References mMeshes.
Referenced by GetMesh().
GetParamOffset()
int cCharacter::GetParamOffset (int joint_id) const virtual
Definition at line 237 of file Character.cpp.
 {
     return cKinTree::GetParamOffset(mJointMat, joint_id);
 }
References cKinTree::GetParamOffset(), and mJointMat.
Referenced by cCtVelController::ApplyAction(), cSimCharacter::ApplyControlForces(), cCtController::BuildActionBounds(), cCtController::BuildActionOffsetScale(), cSimCharacter::BuildPose(), cImpPDController::BuildTargetPose(), cImpPDController::BuildTargetVel(), cSimCharacter::BuildVel(), cImpPDController::CalcControlForces(), cImpPDController::InitGains(), cImpPDController::SetKd(), cImpPDController::SetKp(), cCtPDController::SetPDTargets(), cSimCharacter::SetPose(), cSimCharacter::SetVel(), cCtController::UpdateBuildTau(), and cPDController::UpdateControlForce().
GetParamSize()
int cCharacter::GetParamSize (int joint_id) const virtual
Definition at line 242 of file Character.cpp.
 {
     return cKinTree::GetParamSize(mJointMat, joint_id);
 }
References cKinTree::GetParamSize(), and mJointMat.
Referenced by cCtVelController::ApplyAction(), cSimCharacter::ApplyControlForces(), cCtController::BuildActionBounds(), cCtController::BuildActionOffsetScale(), cSimCharacter::BuildJointPose(), cSimCharacter::BuildJointVel(), cSimCharacter::BuildPose(), cImpPDController::BuildTargetPose(), cImpPDController::BuildTargetVel(), cSimCharacter::BuildVel(), cImpPDController::CalcControlForces(), cCtController::GetActionCtrlSize(), cPDController::GetJointDim(), cImpPDController::InitGains(), cImpPDController::SetKd(), cImpPDController::SetKp(), cCtPDController::SetPDTargets(), cSimCharacter::SetPose(), cSimCharacter::SetVel(), cCtController::UpdateBuildTau(), and cPDController::UpdateControlForce().
GetParentJoint()
int cCharacter::GetParentJoint (int joint_id) const virtual
Definition at line 252 of file Character.cpp.
 {
     return cKinTree::GetParent(mJointMat, joint_id);
 }
References cKinTree::GetParent(), and mJointMat.
GetPose()
const Eigen::VectorXd & cCharacter::GetPose () const virtual
Definition at line 124 of file Character.cpp.
 {
     return mPose;
 }
References mPose.
Referenced by cImpPDController::CalcControlForces(), cSceneImitate::CalcRewardImitate(), cDrawCharacter::Draw(), cKinCharacter::LoadMotion(), cSimCharacter::UpdateLinkVel(), cImpPDController::UpdateRBDModel(), and WriteState().
GetPose0()
const Eigen::VectorXd & cCharacter::GetPose0 () const virtual
Definition at line 135 of file Character.cpp.
 {
     return mPose0;
 }
References mPose0.
Referenced by Reset().
GetRootID()
int cCharacter::GetRootID () const virtual
Definition at line 166 of file Character.cpp.
 {
     int root_id = cKinTree::GetRoot(mJointMat);
     return root_id;
 }
References cKinTree::GetRoot(), and mJointMat.
Referenced by cCtVelController::ApplyAction(), cSimCharacter::ApplyForce(), cCtController::BuildActionBounds(), cCtController::BuildActionOffsetScale(), cSimCharacter::BuildSimBody(), cCtController::BuildStatePose(), cCtController::BuildStateVel(), CalcJointChainLength(), cSceneImitate::CalcRewardImitate(), cSimCharacter::FixedBase(), cCtController::GetActionCtrlSize(), cSimCharacter::GetContactPts(), cSimCharacter::GetLinearVelocity(), cSimCharacter::GetRootAngVel(), cSimCharacter::GetRootPart(), cSimCharacter::GetRootPos(), cSimCharacter::GetRootRotation(), cSimCharacter::GetRootVel(), cSimCharacter::GetWorldTransform(), cExpPDController::Init(), cCtPDController::SetPDTargets(), and cCtController::UpdateBuildTau().
GetRootPos()
tVector cCharacter::GetRootPos () const virtual
Reimplemented in cSimCharacter.
Definition at line 172 of file Character.cpp.
 {
     tVector pos = cKinTree::GetRootPos(mJointMat, mPose);
     return pos;
 }
References cKinTree::GetRootPos(), mJointMat, and mPose.
Referenced by cDrawCharacter::DrawHeading(), cKinCharacter::RotateOrigin(), cKinCharacter::SetRootPos(), and cSceneImitate::SyncKinCharNewCycle().
GetRootRotation() [1/2]
tQuaternion cCharacter::GetRootRotation () const virtual
Reimplemented in cSimCharacter.
Definition at line 184 of file Character.cpp.
 {
     return cKinTree::GetRootRot(mJointMat, mPose);
 }
References cKinTree::GetRootRot(), mJointMat, and mPose.
Referenced by GetRootRotation(), RotateRoot(), and cKinCharacter::SetRootRotation().
GetRootRotation() [2/2]
void cCharacter::GetRootRotation (tVector & out_axis, double & out_theta) const virtual
Reimplemented in cSimCharacter.
Definition at line 178 of file Character.cpp.
 {
     tQuaternion quat = GetRootRotation();
     cMathUtil::QuaternionToAxisAngle(quat, out_axis, out_theta);
 }
References GetRootRotation(), and cMathUtil::QuaternionToAxisAngle().
Referenced by cSceneImitate::CheckRootRotFail().
GetVel()
const Eigen::VectorXd & cCharacter::GetVel () const virtual
Definition at line 145 of file Character.cpp.
 {
     return mVel;
 }
References mVel.
Referenced by cImpPDController::CalcControlForces(), cSceneImitate::CalcRewardImitate(), cKinCharacter::LoadMotion(), cSimCharacter::UpdateLinkVel(), cImpPDController::UpdateRBDModel(), and WriteState().
GetVel0()
const Eigen::VectorXd & cCharacter::GetVel0 () const virtual
Definition at line 156 of file Character.cpp.
 {
     return mVel0;
 }
References mVel0.
Referenced by Reset().
HasDrawShapes()
bool cCharacter::HasDrawShapes () const virtual
Definition at line 398 of file Character.cpp.
 {
     return mDrawShapeDefs.size() > 0;
 }
References mDrawShapeDefs.
Referenced by cDrawCharacter::Draw(), cDrawSimCharacter::Draw(), cDrawCharacter::DrawCharShapes(), cDrawCharacter::DrawPose(), and cDrawCharacter::DrawPoseCharShapes().
Init()
bool cCharacter::Init (const std::string & char_file, bool load_draw_shapes) virtual
Definition at line 36 of file Character.cpp.
 {
     Clear();
     bool succ = true;
     if (char_file != "")
     {
         std::ifstream f_stream(char_file);
         Json::Reader reader;
         Json::Value root;
         succ = reader.parse(f_stream, root);
         f_stream.close();
         if (succ)
         {
             if (root[gSkeletonKey].isNull())
             {
                 succ = false;
             }
             else
             {
                 succ = LoadSkeleton(root[gSkeletonKey]);
             }
         }
     }
     if (succ)
     {
         InitDefaultState();
         if (cDrawUtil::EnableDraw() && load_draw_shapes)
         {
             succ &= LoadMeshes(char_file, mMeshes);
             succ &= LoadDrawShapeDefs(char_file, mDrawShapeDefs);
         }
     }
     if (!succ)
     {
         printf("Failed to parse character from file %s.\n", char_file.c_str());
     }
     return succ;
 }
References Clear(), cDrawUtil::EnableDraw(), gSkeletonKey, InitDefaultState(), LoadDrawShapeDefs(), LoadMeshes(), LoadSkeleton(), mDrawShapeDefs, mMeshes, and Json::Reader::parse().
Referenced by cKinCharacter::Init(), and cSimCharacter::Init().
InitDefaultState()
void cCharacter::InitDefaultState () virtual
Definition at line 389 of file Character.cpp.
 {
     int state_size = GetNumDof();
     cKinTree::BuildDefaultPose(mJointMat, mPose0);
     cKinTree::BuildDefaultVel(mJointMat, mVel0);
     mPose = mPose0;
     mVel = mVel0;
 }
References cKinTree::BuildDefaultPose(), cKinTree::BuildDefaultVel(), GetNumDof(), mJointMat, mPose, mPose0, mVel, and mVel0.
Referenced by Init().
IsEndEffector()
bool cCharacter::IsEndEffector (int joint_id) const virtual
Definition at line 247 of file Character.cpp.
 {
     return cKinTree::IsEndEffector(mJointMat, joint_id);
 }
References cKinTree::IsEndEffector(), and mJointMat.
Referenced by CalcNumEndEffectors(), cSceneImitate::CalcRewardImitate(), and cSimCharacter::HasStumbled().
LoadDrawShapeDefs()
bool cCharacter::LoadDrawShapeDefs (const std::string & char_file, Eigen::MatrixXd & out_draw_defs) const protected virtual
Definition at line 443 of file Character.cpp.
 {
     bool succ = cKinTree::LoadDrawShapeDefs(char_file, out_draw_defs);
     return succ;
 }
References cKinTree::LoadDrawShapeDefs().
Referenced by Init().
LoadMeshes()
bool cCharacter::LoadMeshes (const std::string & char_file, std::vector< std::shared_ptr< cDrawMesh >> & out_meshes) const protected virtual
Definition at line 449 of file Character.cpp.
 {
     bool succ = true;
     std::string str;
     std::ifstream f_stream(char_file.c_str());
     Json::Value root;
     Json::Reader reader;
     succ = reader.parse(f_stream, root);
     f_stream.close();
     if (succ)
     {
         if (!root[gMeshesKey].isNull())
         {
             Json::Value meshes = root.get(gMeshesKey, 0);
             int num_meshes = meshes.size();
             succ = true;
             out_meshes.resize(num_meshes);
             for (int i = 0; i < num_meshes; ++i)
             {
                 std::string curr_path = meshes.get(i, "").asString();
                 std::shared_ptr<cDrawMesh> curr_mesh = std::shared_ptr<cDrawMesh>(new cDrawMesh);
                 succ &= cMeshUtil::LoadObj(curr_path, *curr_mesh);
                 if (succ)
                 {
                     out_meshes[i] = curr_mesh;
                 }
                 else
                 {
                     printf("Failed to load mesh from %s\n", curr_path.c_str());
                     assert(false);
                     break;
                 }
             }
         }
     }
     if (!succ)
     {
         printf("Failed to load meshes from %s\n", char_file.c_str());
         assert(false);
     }
     return succ;
 }
References Json::Value::asString(), Json::Value::get(), gMeshesKey, cMeshUtil::LoadObj(), Json::Reader::parse(), and Json::Value::size().
Referenced by Init().
LoadSkeleton()
bool cCharacter::LoadSkeleton (const Json::Value & root) virtual
Definition at line 384 of file Character.cpp.
 {
     return cKinTree::Load(root, mJointMat);
 }
References cKinTree::Load(), and mJointMat.
Referenced by Init().
ParseState()
bool cCharacter::ParseState (const Json::Value & root, Eigen::VectorXd & out_state) const protected virtual
Definition at line 423 of file Character.cpp.
 {
     bool succ = cJsonUtil::ReadVectorJson(root, out_state);
     int num_dof = GetNumDof();
     assert(out_state.size() == num_dof);
     return succ;
 }
References GetNumDof(), and cJsonUtil::ReadVectorJson().
Referenced by ReadState().
ReadState()
bool cCharacter::ReadState (const std::string & file) virtual
Definition at line 358 of file Character.cpp.
 {
     std::ifstream f_stream(file);
     Json::Reader reader;
     Json::Value root;
     bool succ = reader.parse(f_stream, root);
     f_stream.close();
     if (succ && !root[gPoseKey].isNull())
     {
         Eigen::VectorXd pose;
         succ &= ParseState(root[gPoseKey], pose);
         cKinTree::PostProcessPose(mJointMat, pose);
         SetPose(pose);
     }
     if (succ && !root[gVelKey].isNull())
     {
         Eigen::VectorXd vel;
         succ &= ParseState(root[gVelKey], vel);
         SetVel(vel);
     }
     return succ;
 }
References gPoseKey, gVelKey, mJointMat, Json::Reader::parse(), ParseState(), cKinTree::PostProcessPose(), SetPose(), and SetVel().
Referenced by cKinCharacter::Init(), and cSimCharacter::Init().
Reset()
void cCharacter::Reset () virtual
Reimplemented in cSimCharacter, and cKinCharacter.
Definition at line 97 of file Character.cpp.
 {
     ResetParams();
     const Eigen::VectorXd& pose0 = GetPose0();
     const Eigen::VectorXd& vel0 = GetVel0();
     SetPose(pose0);
     SetVel(vel0);
 }
References GetPose0(), GetVel0(), ResetParams(), SetPose(), and SetVel().
Referenced by cKinCharacter::Reset(), and cSimCharacter::Reset().
ResetParams()
void cCharacter::ResetParams () protected virtual
Reimplemented in cKinCharacter.
Definition at line 419 of file Character.cpp.
 {
 }
Referenced by cCharacter(), Clear(), Reset(), and cKinCharacter::ResetParams().
RotateRoot()
void cCharacter::RotateRoot (const tQuaternion & rot) virtual
Definition at line 204 of file Character.cpp.
 {
     tQuaternion root_rot = GetRootRotation();
     root_rot = rot * root_rot;
     root_rot.normalize();
     SetRootRotation(root_rot);
 }
References GetRootRotation(), and SetRootRotation().
Referenced by cSceneImitate::SyncKinCharNewCycle().
SetID()
void cCharacter::SetID (int id) virtual
Definition at line 26 of file Character.cpp.
 {
     mID = id;
 }
References mID.
Referenced by cSimCharacter::Init().
SetPose()
void cCharacter::SetPose (const Eigen::VectorXd & pose) virtual
Reimplemented in cSimCharacter.
Definition at line 129 of file Character.cpp.
 {
     assert(pose.size() == GetNumDof());
     mPose = pose;
 }
References GetNumDof(), and mPose.
Referenced by cKinCharacter::Init(), cKinCharacter::Pose(), ReadState(), Reset(), and cSimCharacter::SetPose().
SetPose0()
void cCharacter::SetPose0 (const Eigen::VectorXd & pose) virtual
Definition at line 140 of file Character.cpp.
 {
     mPose0 = pose;
 }
References mPose0.
SetRootAngVel()
void cCharacter::SetRootAngVel (const tVector & ang_vel) virtual
Reimplemented in cSimCharacter.
Definition at line 217 of file Character.cpp.
 {
     cKinTree::SetRootAngVel(mJointMat, ang_vel, mVel);
 }
References mJointMat, mVel, and cKinTree::SetRootAngVel().
Referenced by cSimCharacter::SetRootAngVel().
SetRootPos()
void cCharacter::SetRootPos (const tVector & pos) virtual
Reimplemented in cSimCharacter, and cKinCharacter.
Definition at line 189 of file Character.cpp.
 {
     cKinTree::SetRootPos(mJointMat, pos, mPose);
 }
References mJointMat, mPose, and cKinTree::SetRootPos().
Referenced by cSimCharacter::SetRootPos().
SetRootPos0()
void cCharacter::SetRootPos0 (const tVector & pose) virtual
Definition at line 194 of file Character.cpp.
 {
     cKinTree::SetRootPos(mJointMat, pos, mPose0);
 }
References mJointMat, mPose0, and cKinTree::SetRootPos().
SetRootRotation()
void cCharacter::SetRootRotation (const tQuaternion & q) virtual
Reimplemented in cSimCharacter, and cKinCharacter.
Definition at line 199 of file Character.cpp.
 {
     cKinTree::SetRootRot(mJointMat, q, mPose);
 }
References mJointMat, mPose, and cKinTree::SetRootRot().
Referenced by RotateRoot().
SetRootVel()
void cCharacter::SetRootVel (const tVector & vel) virtual
Reimplemented in cSimCharacter.
Definition at line 212 of file Character.cpp.
 {
     cKinTree::SetRootVel(mJointMat, vel, mVel);
 }
References mJointMat, mVel, and cKinTree::SetRootVel().
Referenced by cSimCharacter::SetRootVel().
SetVel()
void cCharacter::SetVel (const Eigen::VectorXd & vel) virtual
Reimplemented in cSimCharacter.
Definition at line 150 of file Character.cpp.
 {
     assert(vel.size() == GetNumDof());
     mVel = vel;
 }
References GetNumDof(), and mVel.
Referenced by cKinCharacter::Init(), cKinCharacter::Pose(), ReadState(), Reset(), and cSimCharacter::SetVel().
SetVel0()
void cCharacter::SetVel0 (const Eigen::VectorXd & vel) virtual
Definition at line 161 of file Character.cpp.
 {
     mVel0 = vel;
 }
References mVel0.
Update()
void cCharacter::Update (double time_step) virtual
Reimplemented in cSimCharacter, and cKinCharacter.
Definition at line 93 of file Character.cpp.
 {
 }
Referenced by cKinCharacter::Update().
WriteState() [1/2]
bool cCharacter::WriteState (const std::string & file) const virtual
Definition at line 317 of file Character.cpp.
 {
     return WriteState(file, tMatrix::Identity());
 }
WriteState() [2/2]
bool cCharacter::WriteState (const std::string & file, const tMatrix & root_trans) const virtual
Definition at line 322 of file Character.cpp.
 {
     Eigen::VectorXd pose = GetPose();
     Eigen::VectorXd vel = GetVel();
     tQuaternion trans_q = cMathUtil::RotMatToQuaternion(root_trans);
     tVector root_pos = cKinTree::GetRootPos(mJointMat, pose);
     tQuaternion root_rot = cKinTree::GetRootRot(mJointMat, pose);
     tVector root_vel = cKinTree::GetRootVel(mJointMat, vel);
     tVector root_ang_vel = cKinTree::GetRootAngVel(mJointMat, vel);
     root_pos[3] = 1;
     root_pos = root_trans * root_pos;
     root_pos[3] = 0;
     root_rot = trans_q * root_rot;
     root_vel = root_trans * root_vel;
     root_ang_vel = root_trans * root_ang_vel;
     cKinTree::SetRootPos(mJointMat, root_pos, pose);
     cKinTree::SetRootRot(mJointMat, root_rot, pose);
     cKinTree::SetRootVel(mJointMat, root_vel, vel);
     cKinTree::SetRootAngVel(mJointMat, root_ang_vel, vel);
     std::string json = BuildStateJson(pose, vel);
     FILE* f = cFileUtil::OpenFile(file, "w");
     if (f != nullptr)
     {
         fprintf(f, "%s", json.c_str());
         cFileUtil::CloseFile(f);
         return true;
     }
     return false;
 }
References BuildStateJson(), cFileUtil::CloseFile(), GetPose(), cKinTree::GetRootAngVel(), cKinTree::GetRootPos(), cKinTree::GetRootRot(), cKinTree::GetRootVel(), GetVel(), mJointMat, cFileUtil::OpenFile(), cMathUtil::RotMatToQuaternion(), cKinTree::SetRootAngVel(), cKinTree::SetRootPos(), cKinTree::SetRootRot(), and cKinTree::SetRootVel().
Member Data Documentation
gSkeletonKey
const std::string cCharacter::gSkeletonKey = "Skeleton" static
Definition at line 10 of file Character.h.
Referenced by Init().
mDrawShapeDefs
Eigen::MatrixXd cCharacter::mDrawShapeDefs protected
Definition at line 91 of file Character.h.
Referenced by Clear(), GetDrawShapeDefs(), HasDrawShapes(), and Init().
mID
int cCharacter::mID protected
Definition at line 84 of file Character.h.
Referenced by cCharacter(), GetID(), cKinCharacter::Init(), and SetID().
mJointMat
Eigen::MatrixXd cCharacter::mJointMat protected
Definition at line 85 of file Character.h.
Referenced by cKinCharacter::BlendFrames(), cSimCharacter::BuildConsFactor(), cSimCharacter::BuildConstraints(), cSimCharacter::BuildJointPose(), cSimCharacter::BuildJoints(), cSimCharacter::BuildJointVel(), BuildJointWorldTrans(), cSimCharacter::BuildMultiBody(), BuildOriginTrans(), cSimCharacter::BuildPose(), cSimCharacter::BuildSimBody(), cSimCharacter::BuildVel(), CalcAABB(), cKinCharacter::CalcCycleRootDelta(), CalcHeading(), CalcHeadingRot(), CalcJointChainLength(), CalcJointPos(), cSimCharacter::CalcJointPos(), CalcJointVel(), cSimCharacter::CalcJointVel(), CalcJointWorldRotation(), cSimCharacter::CalcJointWorldRotation(), cKinCharacter::CalcPose(), cSimCharacter::FixedBase(), GetJointDiffWeight(), GetJointMat(), GetNumDof(), GetNumJoints(), GetParamOffset(), GetParamSize(), GetParentJoint(), GetRootID(), GetRootPos(), GetRootRotation(), InitDefaultState(), IsEndEffector(), LoadSkeleton(), cKinCharacter::MoveOrigin(), ReadState(), cKinCharacter::RotateOrigin(), cSimCharacter::SetPose(), SetRootAngVel(), SetRootPos(), SetRootPos0(), SetRootRotation(), cSimCharacter::SetRootTransform(), SetRootVel(), cSimCharacter::SetVel(), and WriteState().
mMeshes
std::vector<std::shared_ptr<cDrawMesh> > cCharacter::mMeshes protected
Definition at line 92 of file Character.h.
Referenced by Clear(), GetMesh(), GetNumMeshes(), and Init().
mPose
Eigen::VectorXd cCharacter::mPose protected
Definition at line 86 of file Character.h.
Referenced by BuildJointWorldTrans(), BuildOriginTrans(), CalcAABB(), CalcHeading(), CalcHeadingRot(), CalcJointPos(), CalcJointVel(), CalcJointWorldRotation(), Clear(), GetPose(), GetRootPos(), GetRootRotation(), cKinCharacter::Init(), cSimCharacter::Init(), InitDefaultState(), cKinCharacter::MoveOrigin(), cKinCharacter::Pose(), cSimCharacter::PostUpdate(), cKinCharacter::RotateOrigin(), SetPose(), SetRootPos(), cSimCharacter::SetRootPos(), SetRootRotation(), and cSimCharacter::SetRootTransform().
mPose0
Eigen::VectorXd cCharacter::mPose0 protected
Definition at line 88 of file Character.h.
Referenced by cKinCharacter::CalcPose(), Clear(), GetPose0(), cKinCharacter::Init(), cSimCharacter::Init(), InitDefaultState(), cKinCharacter::LoadMotion(), cKinCharacter::MoveOrigin(), cKinCharacter::RotateOrigin(), SetPose0(), and SetRootPos0().
mVel
Eigen::VectorXd cCharacter::mVel protected
Definition at line 87 of file Character.h.
Referenced by CalcJointVel(), Clear(), GetVel(), cKinCharacter::Init(), cSimCharacter::Init(), InitDefaultState(), cKinCharacter::Pose(), cSimCharacter::PostUpdate(), cKinCharacter::RotateOrigin(), SetRootAngVel(), cSimCharacter::SetRootAngVel(), cSimCharacter::SetRootTransform(), SetRootVel(), cSimCharacter::SetRootVel(), and SetVel().
mVel0
Eigen::VectorXd cCharacter::mVel0 protected
Definition at line 89 of file Character.h.
Referenced by Clear(), GetVel0(), cKinCharacter::Init(), cSimCharacter::Init(), InitDefaultState(), cKinCharacter::LoadMotion(), cKinCharacter::RotateOrigin(), and SetVel0().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/anim/Character.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/anim/Character.cpp