My Project: cCtCtrlUtil Class Reference
cCtCtrlUtil Class Reference
#include <CtCtrlUtil.h>
Static Public Member Functions
static void BuildBoundsTorque (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max)
static void BuildBoundsVel (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max)
static void BuildBoundsPD (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max)
static void BuildOffsetScaleTorque (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale)
static void BuildOffsetScaleVel (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale)
static void BuildOffsetScalePD (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale)
Static Protected Member Functions
static void BuildBoundsPDRevolute (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max)
static void BuildBoundsPDPrismatic (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max)
static void BuildBoundsPDPlanar (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max)
static void BuildBoundsPDFixed (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max)
static void BuildBoundsPDSpherical (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_min, Eigen::VectorXd &out_max)
static void BuildOffsetScalePDRevolute (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale)
static void BuildOffsetScalePDPrismatic (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale)
static void BuildOffsetScalePDPlanar (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale)
static void BuildOffsetScalePDFixed (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale)
static void BuildOffsetScalePDSpherical (const Eigen::MatrixXd &joint_mat, int joint_id, Eigen::VectorXd &out_offset, Eigen::VectorXd &out_scale)
Detailed Description
Definition at line 7 of file CtCtrlUtil.h.
Member Function Documentation
BuildBoundsPD()
void cCtCtrlUtil::BuildBoundsPD (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) static
Definition at line 89 of file CtCtrlUtil.cpp.
 {
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     switch (joint_type)
     {
     case cKinTree::eJointTypeRevolute:
         BuildBoundsPDRevolute(joint_mat, joint_id, out_min, out_max);
         break;
     case cKinTree::eJointTypePrismatic:
         BuildBoundsPDPrismatic(joint_mat, joint_id, out_min, out_max);
         break;
     case cKinTree::eJointTypePlanar:
         BuildBoundsPDPlanar(joint_mat, joint_id, out_min, out_max);
         break;
     case cKinTree::eJointTypeFixed:
         BuildBoundsPDFixed(joint_mat, joint_id, out_min, out_max);
         break;
     case cKinTree::eJointTypeSpherical:
         BuildBoundsPDSpherical(joint_mat, joint_id, out_min, out_max);
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References BuildBoundsPDFixed(), BuildBoundsPDPlanar(), BuildBoundsPDPrismatic(), BuildBoundsPDRevolute(), BuildBoundsPDSpherical(), cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, and cKinTree::GetJointType().
Referenced by cCtPDController::BuildJointActionBounds().
BuildBoundsPDFixed()
void cCtCtrlUtil::BuildBoundsPDFixed (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) static protected
Definition at line 318 of file CtCtrlUtil.cpp.
 {
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     assert(joint_type == cKinTree::eJointTypeFixed);
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     out_min = Eigen::VectorXd::Zero(joint_dim);
     out_max = Eigen::VectorXd::Zero(joint_dim);
 }
References cKinTree::eJointTypeFixed, cKinTree::GetJointType(), and cKinTree::GetParamSize().
Referenced by BuildBoundsPD().
BuildBoundsPDPlanar()
void cCtCtrlUtil::BuildBoundsPDPlanar (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) static protected
Definition at line 291 of file CtCtrlUtil.cpp.
 {
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     assert(joint_type == cKinTree::eJointTypePlanar);
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     out_min = Eigen::VectorXd::Zero(joint_dim);
     out_max = Eigen::VectorXd::Zero(joint_dim);
     tVector lim_low = cKinTree::GetJointLimLow(joint_mat, joint_id);
     tVector lim_high = cKinTree::GetJointLimHigh(joint_mat, joint_id);
     for (int i = 0; i < joint_dim; ++i)
     {
         double val_low = lim_low[i];
         double val_high = lim_high[i];
         bool valid_lim = val_high >= val_low;
         if (!valid_lim)
         {
             val_low = -gDefaultOffsetPDBound;
             val_high = gDefaultOffsetPDBound;
         }
         out_min[i] = val_low;
         out_max[i] = val_high;
     }
 }
References cKinTree::eJointTypePlanar, gDefaultOffsetPDBound, cKinTree::GetJointLimHigh(), cKinTree::GetJointLimLow(), cKinTree::GetJointType(), and cKinTree::GetParamSize().
Referenced by BuildBoundsPD().
BuildBoundsPDPrismatic()
void cCtCtrlUtil::BuildBoundsPDPrismatic (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) static protected
Definition at line 259 of file CtCtrlUtil.cpp.
 {
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     assert(joint_type == cKinTree::eJointTypePrismatic);
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     out_min = Eigen::VectorXd::Zero(joint_dim);
     out_max = Eigen::VectorXd::Zero(joint_dim);
     tVector lim_low = cKinTree::GetJointLimLow(joint_mat, joint_id);
     tVector lim_high = cKinTree::GetJointLimHigh(joint_mat, joint_id);
     for (int i = 0; i < joint_dim; ++i)
     {
         double val_low = lim_low[i];
         double val_high = lim_high[i];
         bool valid_lim = val_high >= val_low;
         if (!valid_lim)
         {
             val_low = -gDefaultOffsetPDBound;
             val_high = gDefaultOffsetPDBound;
         }
         double mean_val = 0.5 * (val_high + val_low);
         double delta = val_high - val_low;
         val_low = mean_val - delta;
         val_high = mean_val + delta;
         out_min[i] = val_low;
         out_max[i] = val_high;
     }
 }
References cKinTree::eJointTypePrismatic, gDefaultOffsetPDBound, cKinTree::GetJointLimHigh(), cKinTree::GetJointLimLow(), cKinTree::GetJointType(), and cKinTree::GetParamSize().
Referenced by BuildBoundsPD().
BuildBoundsPDRevolute()
void cCtCtrlUtil::BuildBoundsPDRevolute (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) static protected
Definition at line 226 of file CtCtrlUtil.cpp.
 {
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     assert(joint_type == cKinTree::eJointTypeRevolute);
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     out_min = Eigen::VectorXd::Zero(joint_dim);
     out_max = Eigen::VectorXd::Zero(joint_dim);
     tVector lim_low = cKinTree::GetJointLimLow(joint_mat, joint_id);
     tVector lim_high = cKinTree::GetJointLimHigh(joint_mat, joint_id);
     for (int i = 0; i < joint_dim; ++i)
     {
         double val_low = lim_low[i];
         double val_high = lim_high[i];
         bool valid_lim = val_high >= val_low;
         if (!valid_lim)
         {
             val_low = -gDefaultRotatePDBound;
             val_high = gDefaultRotatePDBound;
         }
         double mean_val = 0.5 * (val_high + val_low);
         double delta = val_high - val_low;
         val_low = mean_val - 2 * delta;
         val_high = mean_val + 2 * delta;
         out_min[i] = val_low;
         out_max[i] = val_high;
     }
 }
References cKinTree::eJointTypeRevolute, gDefaultRotatePDBound, cKinTree::GetJointLimHigh(), cKinTree::GetJointLimLow(), cKinTree::GetJointType(), and cKinTree::GetParamSize().
Referenced by BuildBoundsPD().
BuildBoundsPDSpherical()
void cCtCtrlUtil::BuildBoundsPDSpherical (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) static protected
Definition at line 328 of file CtCtrlUtil.cpp.
 {
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     assert(joint_type == cKinTree::eJointTypeSpherical);
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     out_min = -Eigen::VectorXd::Ones(joint_dim);
     out_max = Eigen::VectorXd::Ones(joint_dim);
 #if defined(ENABLE_PD_SPHERE_AXIS)
     tVector lim_low = cKinTree::GetJointLimLow(joint_mat, joint_id);
     tVector lim_high = cKinTree::GetJointLimHigh(joint_mat, joint_id);
     double val_low = lim_low.minCoeff();
     double val_high = lim_high.maxCoeff();
     bool valid_lim = val_high >= val_low;
     if (!valid_lim)
     {
         val_low = -gDefaultRotatePDBound;
         val_high = gDefaultRotatePDBound;
     }
     double mean_val = 0.5 * (val_high + val_low);
     double delta = val_high - val_low;
     val_low = mean_val - 2 * delta;
     val_high = mean_val + 2 * delta;
     out_min[0] = val_low;
     out_max[0] = val_high;
 #endif
 }
References cKinTree::eJointTypeSpherical, gDefaultRotatePDBound, cKinTree::GetJointLimHigh(), cKinTree::GetJointLimLow(), cKinTree::GetJointType(), and cKinTree::GetParamSize().
Referenced by BuildBoundsPD().
BuildBoundsTorque()
void cCtCtrlUtil::BuildBoundsTorque (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) static
Definition at line 8 of file CtCtrlUtil.cpp.
 {
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     out_min = std::numeric_limits<double>::quiet_NaN() * Eigen::VectorXd::Ones(joint_dim);
     out_max = std::numeric_limits<double>::quiet_NaN() * Eigen::VectorXd::Ones(joint_dim);
     double torque_lim = cKinTree::GetTorqueLimit(joint_mat, joint_id);
     double force_lim = cKinTree::GetForceLimit(joint_mat, joint_id);
     switch (joint_type)
     {
     case cKinTree::eJointTypeRevolute:
         out_min.fill(-torque_lim);
         out_max.fill(torque_lim);
         break;
     case cKinTree::eJointTypePrismatic:
         out_min.fill(-force_lim);
         out_max.fill(force_lim);
         break;
     case cKinTree::eJointTypePlanar:
         out_min.fill(-force_lim);
         out_max.fill(force_lim);
         out_min[joint_dim - 1] = -torque_lim;
         out_max[joint_dim - 1] = torque_lim;
         break;
     case cKinTree::eJointTypeFixed:
         break;
     case cKinTree::eJointTypeSpherical:
         out_min.segment(0, joint_dim - 1).fill(-torque_lim);
         out_max.segment(0, joint_dim - 1).fill(torque_lim);
         out_min[joint_dim - 1] = 0;
         out_max[joint_dim - 1] = 0;
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, cKinTree::GetForceLimit(), cKinTree::GetJointType(), cKinTree::GetParamSize(), and cKinTree::GetTorqueLimit().
Referenced by cCtController::BuildJointActionBounds().
BuildBoundsVel()
void cCtCtrlUtil::BuildBoundsVel (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_min, Eigen::VectorXd & out_max) static
Definition at line 48 of file CtCtrlUtil.cpp.
 {
     const double max_ang_vel = 20 * M_PI;
     const double max_lin_vel = 5;
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     out_min = std::numeric_limits<double>::quiet_NaN() * Eigen::VectorXd::Ones(joint_dim);
     out_max = std::numeric_limits<double>::quiet_NaN() * Eigen::VectorXd::Ones(joint_dim);
     switch (joint_type)
     {
     case cKinTree::eJointTypeRevolute:
         out_min.fill(-max_ang_vel);
         out_max.fill(max_ang_vel);
         break;
     case cKinTree::eJointTypePrismatic:
         out_min.fill(-max_lin_vel);
         out_max.fill(max_lin_vel);
         break;
     case cKinTree::eJointTypePlanar:
         out_min.fill(-max_lin_vel);
         out_max.fill(max_lin_vel);
         out_min[joint_dim - 1] = -max_ang_vel;
         out_max[joint_dim - 1] = max_ang_vel;
         break;
     case cKinTree::eJointTypeFixed:
         break;
     case cKinTree::eJointTypeSpherical:
         out_min.segment(0, joint_dim - 1).fill(-max_ang_vel);
         out_max.segment(0, joint_dim - 1).fill(max_ang_vel);
         out_min[joint_dim - 1] = 0;
         out_max[joint_dim - 1] = 0;
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, cKinTree::GetJointType(), and cKinTree::GetParamSize().
Referenced by cCtVelController::BuildJointActionBounds().
BuildOffsetScalePD()
void cCtCtrlUtil::BuildOffsetScalePD (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) static
Definition at line 198 of file CtCtrlUtil.cpp.
 {
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     switch (joint_type)
     {
     case cKinTree::eJointTypeRevolute:
         BuildOffsetScalePDRevolute(joint_mat, joint_id, out_offset, out_scale);
         break;
     case cKinTree::eJointTypePrismatic:
         BuildOffsetScalePDPrismatic(joint_mat, joint_id, out_offset, out_scale);
         break;
     case cKinTree::eJointTypePlanar:
         BuildOffsetScalePDPlanar(joint_mat, joint_id, out_offset, out_scale);
         break;
     case cKinTree::eJointTypeFixed:
         BuildOffsetScalePDFixed(joint_mat, joint_id, out_offset, out_scale);
         break;
     case cKinTree::eJointTypeSpherical:
         BuildOffsetScalePDSpherical(joint_mat, joint_id, out_offset, out_scale);
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References BuildOffsetScalePDFixed(), BuildOffsetScalePDPlanar(), BuildOffsetScalePDPrismatic(), BuildOffsetScalePDRevolute(), BuildOffsetScalePDSpherical(), cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, and cKinTree::GetJointType().
Referenced by cCtPDController::BuildJointActionOffsetScale().
BuildOffsetScalePDFixed()
void cCtCtrlUtil::BuildOffsetScalePDFixed (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) static protected
Definition at line 447 of file CtCtrlUtil.cpp.
 {
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     assert(joint_type == cKinTree::eJointTypeFixed);
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     out_offset = Eigen::VectorXd::Zero(joint_dim);
     out_scale = Eigen::VectorXd::Ones(joint_dim);
 }
References cKinTree::eJointTypeFixed, cKinTree::GetJointType(), and cKinTree::GetParamSize().
Referenced by BuildOffsetScalePD().
BuildOffsetScalePDPlanar()
void cCtCtrlUtil::BuildOffsetScalePDPlanar (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) static protected
Definition at line 420 of file CtCtrlUtil.cpp.
 {
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     assert(joint_type == cKinTree::eJointTypePlanar);
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     out_offset = Eigen::VectorXd::Zero(joint_dim);
     out_scale = Eigen::VectorXd::Ones(joint_dim);
     tVector lim_low = cKinTree::GetJointLimLow(joint_mat, joint_id);
     tVector lim_high = cKinTree::GetJointLimHigh(joint_mat, joint_id);
     for (int i = 0; i < joint_dim; ++i)
     {
         double val_low = lim_low[i];
         double val_high = lim_high[i];
         bool valid_lim = val_high >= val_low;
         if (!valid_lim)
         {
             val_low = -gDefaultOffsetPDBound;
             val_high = gDefaultOffsetPDBound;
         }
         out_offset[i] = -0.5 * (val_high + val_low);
         out_scale[i] = 2 / (val_high - val_low);
     }
 }
References cKinTree::eJointTypePlanar, gDefaultOffsetPDBound, cKinTree::GetJointLimHigh(), cKinTree::GetJointLimLow(), cKinTree::GetJointType(), and cKinTree::GetParamSize().
Referenced by BuildOffsetScalePD().
BuildOffsetScalePDPrismatic()
void cCtCtrlUtil::BuildOffsetScalePDPrismatic (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) static protected
Definition at line 393 of file CtCtrlUtil.cpp.
 {
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     assert(joint_type == cKinTree::eJointTypePrismatic);
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     out_offset = Eigen::VectorXd::Zero(joint_dim);
     out_scale = Eigen::VectorXd::Ones(joint_dim);
     tVector lim_low = cKinTree::GetJointLimLow(joint_mat, joint_id);
     tVector lim_high = cKinTree::GetJointLimHigh(joint_mat, joint_id);
     for (int i = 0; i < joint_dim; ++i)
     {
         double val_low = lim_low[i];
         double val_high = lim_high[i];
         bool valid_lim = val_high >= val_low;
         if (!valid_lim)
         {
             val_low = -gDefaultOffsetPDBound;
             val_high = gDefaultOffsetPDBound;
         }
         out_offset[i] = -0.5 * (val_high + val_low);
         out_scale[i] = 2 / (val_high - val_low);
     }
 }
References cKinTree::eJointTypePrismatic, gDefaultOffsetPDBound, cKinTree::GetJointLimHigh(), cKinTree::GetJointLimLow(), cKinTree::GetJointType(), and cKinTree::GetParamSize().
Referenced by BuildOffsetScalePD().
BuildOffsetScalePDRevolute()
void cCtCtrlUtil::BuildOffsetScalePDRevolute (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) static protected
Definition at line 361 of file CtCtrlUtil.cpp.
 {
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     assert(joint_type == cKinTree::eJointTypeRevolute);
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     out_offset = Eigen::VectorXd::Zero(joint_dim);
     out_scale = Eigen::VectorXd::Ones(joint_dim);
     tVector lim_low = cKinTree::GetJointLimLow(joint_mat, joint_id);
     tVector lim_high = cKinTree::GetJointLimHigh(joint_mat, joint_id);
     for (int i = 0; i < joint_dim; ++i)
     {
         double val_low = lim_low[i];
         double val_high = lim_high[i];
         bool valid_lim = val_high >= val_low;
         if (!valid_lim)
         {
             val_low = -gDefaultRotatePDBound;
             val_high = gDefaultRotatePDBound;
         }
         double curr_offset = -0.5 * (val_high + val_low);
         double curr_scale = 1 / (val_high - val_low);
         curr_scale *= 0.5;
         out_offset[i] = curr_offset;
         out_scale[i] = curr_scale;
     }
 }
References cKinTree::eJointTypeRevolute, gDefaultRotatePDBound, cKinTree::GetJointLimHigh(), cKinTree::GetJointLimLow(), cKinTree::GetJointType(), and cKinTree::GetParamSize().
Referenced by BuildOffsetScalePD().
BuildOffsetScalePDSpherical()
void cCtCtrlUtil::BuildOffsetScalePDSpherical (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) static protected
Definition at line 457 of file CtCtrlUtil.cpp.
 {
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     assert(joint_type == cKinTree::eJointTypeSpherical);
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     out_offset = Eigen::VectorXd::Zero(joint_dim);
     out_scale = Eigen::VectorXd::Ones(joint_dim);
 #if defined(ENABLE_PD_SPHERE_AXIS)
     tVector lim_low = cKinTree::GetJointLimLow(joint_mat, joint_id);
     tVector lim_high = cKinTree::GetJointLimHigh(joint_mat, joint_id);
     double val_low = lim_low.minCoeff();
     double val_high = lim_high.maxCoeff();
     bool valid_lim = val_high >= val_low;
     if (!valid_lim)
     {
         val_low = -gDefaultRotatePDBound;
         val_high = gDefaultRotatePDBound;
     }
     double curr_offset = 0;
     double curr_scale = 1 / (val_high - val_low);
     curr_scale *= 0.5;
     out_offset(0) = curr_offset;
     out_scale(0) = curr_scale;
     out_offset(3) = -0.2;
 #else
     out_offset(0) = -0.2;
 #endif
 }
References cKinTree::eJointTypeSpherical, gDefaultRotatePDBound, cKinTree::GetJointLimHigh(), cKinTree::GetJointLimLow(), cKinTree::GetJointType(), and cKinTree::GetParamSize().
Referenced by BuildOffsetScalePD().
BuildOffsetScaleTorque()
void cCtCtrlUtil::BuildOffsetScaleTorque (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) static
Definition at line 116 of file CtCtrlUtil.cpp.
 {
     const double default_torque_lim = 300;
     const double default_force_lim = 3000;
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     out_offset = Eigen::VectorXd::Zero(joint_dim);
     out_scale = Eigen::VectorXd::Ones(joint_dim);
     double torque_lim = cKinTree::GetTorqueLimit(joint_mat, joint_id);
     double force_lim = cKinTree::GetForceLimit(joint_mat, joint_id);
     if (!std::isfinite(torque_lim))
     {
         torque_lim = default_torque_lim;
     }
     if (!std::isfinite(force_lim))
     {
         force_lim = default_force_lim;
     }
     switch (joint_type)
     {
     case cKinTree::eJointTypeRevolute:
         out_scale.fill(1 / torque_lim);
         break;
     case cKinTree::eJointTypePrismatic:
         out_scale.fill(1 / force_lim);
         break;
     case cKinTree::eJointTypePlanar:
         out_scale.fill(1 / force_lim);
         out_scale[joint_dim - 1] = 1 / torque_lim;
         break;
     case cKinTree::eJointTypeFixed:
         break;
     case cKinTree::eJointTypeSpherical:
         out_scale.fill(1 / torque_lim);
         out_scale[joint_dim - 1] = 0;
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, cKinTree::GetForceLimit(), cKinTree::GetJointType(), cKinTree::GetParamSize(), cKinTree::GetTorqueLimit(), and isfinite.
Referenced by cCtController::BuildJointActionOffsetScale().
BuildOffsetScaleVel()
void cCtCtrlUtil::BuildOffsetScaleVel (const Eigen::MatrixXd & joint_mat, int joint_id, Eigen::VectorXd & out_offset, Eigen::VectorXd & out_scale) static
Definition at line 163 of file CtCtrlUtil.cpp.
 {
     int joint_dim = cKinTree::GetParamSize(joint_mat, joint_id);
     cKinTree::eJointType joint_type = cKinTree::GetJointType(joint_mat, joint_id);
     const double ang_vel_scale = 1 / (10 * M_PI);
     const double lin_vel_scale = 1 / 2.5;
     out_offset = Eigen::VectorXd::Zero(joint_dim);
     out_scale = Eigen::VectorXd::Ones(joint_dim);
     switch (joint_type)
     {
     case cKinTree::eJointTypeRevolute:
         out_scale.fill(ang_vel_scale);
         break;
     case cKinTree::eJointTypePrismatic:
         out_scale.fill(lin_vel_scale);
         break;
     case cKinTree::eJointTypePlanar:
         out_scale.fill(lin_vel_scale);
         out_scale[joint_dim - 1] = ang_vel_scale;
         break;
     case cKinTree::eJointTypeFixed:
         break;
     case cKinTree::eJointTypeSpherical:
         out_scale.segment(0, joint_dim - 1).fill(ang_vel_scale);
         out_scale[joint_dim - 1] = 1;
         break;
     default:
         assert(false); // unsupported joint type
         break;
     }
 }
References cKinTree::eJointTypeFixed, cKinTree::eJointTypePlanar, cKinTree::eJointTypePrismatic, cKinTree::eJointTypeRevolute, cKinTree::eJointTypeSpherical, cKinTree::GetJointType(), and cKinTree::GetParamSize().
Referenced by cCtVelController::BuildJointActionOffsetScale().
The documentation for this class was generated from the following files:
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/CtCtrlUtil.h
F:/MotionDev/DmmRec/test0815/DeepMimic/DeepMimicCore/sim/CtCtrlUtil.cpp